### ISSUE TITLE
"h265" module's "module_close()" function: double free()

### ISSUE THREAD

**Issue by czarkoff** [alfredh/baresip#106]
I get a crash when I quit baresip. From the stack trace I see that something within `x265_cleanup()` in `module_close()` of `modules/h265/h265.c` leads to double `free()`, seemingly in some ffmpeg code. The issue appears to be 100% reproducible with baresip 0.4.17 on OpenBSD -current with January 16 set of packages.

**Comment by czarkoff** [comment]
FWIW I am not really sure it is baresip's fault.  I'll try to look into this issue when I have time.

**Comment by alfredh** [comment]
which libx265 packages do you have installed, 8-bit or 10-bit?

can you also post the stack trace here?

**Comment by czarkoff** [comment]
> which libx265 packages do you have installed, 8-bit or 10-bit?
I don't have this choice. From what I see in the port, default one.

**Comment by czarkoff** [comment]
> can you also post the stack trace here?

I don't have that trace any more. I tried reproducing the crash, but it didn't happen again yet.

**Comment by alfredh** [comment]
I just tested the h265.so module on OSX 10.9 and Debian Testing, works fine:

```
h265: using x265 1.4-256-gce7bc82 [Mac OS X][clang 6.0.0][64 bit] 8bpp
h265: using x265 1.8 [Linux][GCC 5.3.1][64 bit] 8bit+10bit+12bit
```

**Comment by alfredh** [comment]
can we close this issue ?
