### ISSUE TITLE
"gtk" module appears to be broken when USE_LIBNOTIFY is defined

### ISSUE THREAD

**Issue by czarkoff** [alfredh/baresip#107]
In 0.4.17 "gtk" module doesn't build with USE_LIBNOTIFY because `notify_incoming_call()` contains two declarations for `notification` pointer.

**Comment by alfredh** [comment]
@clehner is this something you could have a look at ?

**Comment by clehner** [comment]
@czarkoff does #108 fix the build for you?

**Comment by czarkoff** [comment]
Yes, thank you!
