### ISSUE TITLE
Using CMake ?

### ISSUE THREAD

**Issue by LiohAu** [alfredh/baresip#110]
Hello,

I was wondering if there are any plans to use CMake instead of plain Makefiles as it would be easier to switch from linux/windows/osx.
Making xcode project files was not really easy, and each time a new file is added/renamed/removed I have to reflect that changes in Xcode. I guess it's the same issue on Windows with .sln/.csproj files, so using CMake with its generation ability would be really great :)

**Comment by alfredh** [comment]
you are welcome to contribute cmake files for baresip, and we are happy to include
them if you are willing to maintain them.

the main makefile-system for baresip will still be the toplevel Makefile.

libre has a Cmake-file under re/mk/. but it has not been updated in a long time.
