### ISSUE TITLE
CALL_EVENT_CLOSED is not dispatched

### ISSUE THREAD

**Issue by GGGO** [alfredh/baresip#111]
If a remote peer terminates the call, baresip will dispatch the CALL_EVENT_CLOSED and that's good.

But if baresip terminates or rejects the call, no CALL_EVENT_CLOSED is dispatched.

In libre, it seems sipsess_close_handler is never called in this case, so I guess we need to call sipsess_terminate(sess, ECONNRESET, NULL) too for bye_resp_handler() in sipsess/close.c, no ?

The close handler gets overrided by the internal_close_handler if sipsess_terminate is not called.

**Comment by alfredh** [comment]
these events are normally triggered by asynchronous events such as network or timers.

what is your use-case for receiving the CALL_EVENT_CLOSED event when terminating locally?

i.e. when calling ```call_hangup``` you already know that this call has been closed. Even
if the BYE request fails, that call object is still "closed" from the perspective of baresip.

**Comment by GGGO** [comment]
one or multiple modules could register to ua_event_handler, if one of these modules call ```call_hangup```, others modules don't know the current state of call.

I think about a module that monitor the call status (Idle, Ringing, InUse)

**Comment by alfredh** [comment]
Hi GGGO,

can you take a look at this commit:

https://github.com/alfredh/baresip/commit/7e002c7d0aad76fb78b57679d597fc270cd6e573

does it solve your issue ?

**Comment by GGGO** [comment]
Hi alfredh, 

it works perfectly, the closed event is now dispatched.

This event allows me to remove all references on call/ua and others objects in a custom module when a call is closed.

Thanks !
