### ISSUE TITLE
Support for "/etc/hosts" file dns entry

### ISSUE THREAD

**Issue by snapple42** [alfredh/baresip#112]
Sometimes I need to alter the DNS name being used for testing due to a virtual host based registration system (Kazoo & Sipwise).

From what I can see there baresip uses a direct connection to the dns server to query the IP. Is it possible to have an override in the config or in the account definition to allow a different IP for a domain name?

**Comment by alfredh** [comment]
baresip is using the DNS-module from libre, which implements its own DNS client talking
directly to the configured DNS nameservers(s).

I guess we could add this functionality in libre, by looking up A queries in /etc/hosts
before the DNS request is sent out.

**Comment by snapple42** [comment]
It is kind of what I figured.. just helps a lot when debugging servers...

**Comment by alfredh** [comment]
is it possible for you to use a local DNS proxy/cache that also reads entries
from /etc/hosts ?

at the moment I do not have any plans to add support for this in libre's resolver.

you are welcome to create a patch for this, and send it to us for review.

if there is no more activities then feel free to close this issue.
