### ISSUE TITLE
Enable audio codecs

### ISSUE THREAD

**Issue by jungle-boogie** [alfredh/baresip#116]
Hello,

I'd like to use opus and g722 codecs. I've made changes to .baresip/config:
```
module                  opus.so
module                  g722.so
```

I don't see this in my `/usr/local/lib/baresip/modules/`. Is there some flag I need to enable during building? I've uncommented it, make it and still not enabled.

**Comment by jungle-boogie** [comment]
Looks like 722 is now working after installing libspandsp-dev:
https://github.com/alfredh/baresip/wiki/Using-Baresip:-Codec-G722-G726

Any input for opus? Once I have it working, I'll update the wiki.

**Comment by juha-h** [comment]
jungle-boogie writes:

> Looks like 722 is now working after installing libspandsp-dev:
> https://github.com/alfredh/baresip/wiki/Using-Baresip:-Codec-G722-G726
> 
> Any input for opus? Once I have it working, I'll update the wiki.

you need to have libopus-dev package installed when you build baresip
(on debian).

-- juha

**Comment by jungle-boogie** [comment]
Thanks, that worked!
