### ISSUE TITLE
keep baresip running in cli

### ISSUE THREAD

**Issue by jungle-boogie** [alfredh/baresip#119]
Hello,

I've noticed that after a short amount of time (10 minutes), when I call the extension registered with baresip, the call won't completed even though baresip shows registered.

To test:
0. `baresip` on the cli
1. Ensure it registers to your provider (in my case a freeswitch server on my LAN)
2. Make a call to that extension
3. wait 10 minutes
4. Call the same extension again
5. `baresip` won't ring even though it shows as registered

Can anything be done to ensure baresip can available to receive calls regardless of how long the application is open on the cli?

baresip can make calls past the ten minute mark without any issues, just doesn't seem to receive phone calls.

**Comment by alfredh** [comment]
this should work, not sure why it is not working for you.

can you include the full output of baresip, your ```accounts``` file
and the SIP-traffic between baresip and freeswitch ?
(sudo ngrep -p -d any -W byline port 5060)

**Comment by jungle-boogie** [comment]
My `.baresip/accounts`:
`<sip:1001:password@freeswitch.example.net:5065>transport=tcp;answermode=auto`

Are you saying you want the pcap? I'm building tcpdump now from source and will include that. 

I AM able to dial out on baresip after the ten minutes to extension 1000.

**Comment by alfredh** [comment]
```transport=tcp``` is a URI-parameter and not a ADDR-parameter.

please pay close attention to the examples:

```
#  <sip:user:secret@domain.com;transport=tcp>
```

**Comment by alfredh** [comment]
is ```freeswitch.example.net``` a valid domain that you control? I am curious how the SIP
traffic is routed locally.

perhaps you should just use plain IP-addresses for a start, to get something working.

**Comment by jungle-boogie** [comment]
Back at the computer now.

I have ngrep installed and tcpdump now. I'll first make my accounts syntax correct. Then start baresip, make an inbound call, wait 10 minutes and then see what happens.

**Comment by jungle-boogie** [comment]
I don't even need to wait 10 minutes because I can't get the account config you recommend to work.

**WORKS**
`<sip:1001:password@192.168.0.13:5065>transport=tcp;answermode=auto`

**NOT WORKING**
`<sip:1001:password@192.168.0.13:5065;transport=tcp>;answermode=auto`

**Comment by jungle-boogie** [comment]
Do you see anything wrong with the format above as to why it wouldn't work when that's the expected format?

**Comment by lmangani** [comment]
Please capture and attach the REGISTER session at fault to get comments, guesswork is not going to help:  ```sudo ngrep -p -d any -W byline port 5060``` while reproducing the issue, throw it in a pastebin stripped of any sensible details and paste a link here

**Comment by jungle-boogie** [comment]
Hi @lmangani:

http://pastiebin.com/56e5ece80ef64

**Comment by lmangani** [comment]
looks likes you're getting a ```200 OK``` and no issues with the registration

**Comment by jungle-boogie** [comment]
Yep, that's what I see too.

But why won't phone calls come in at all when I have the transport section inside <>?

**Comment by jungle-boogie** [comment]
with sip2sip and the above config, calls were not ringing to baresip after a period of time.

**Comment by lmangani** [comment]
This is most likely your NAT and not Baresip. Try reducing the registration timers

**Comment by jungle-boogie** [comment]
> Try reducing the registration timers

A great suggestion, but why doesn't the registration string below function as expected:

`<sip:1001:password@192.168.0.13:5065;transport=tcp>;answermode=auto`

Does it not support sip ports in the manner have?

**Comment by alfredh** [comment]
I think perhaps the TCP-connection between Baresip and Freeswitch goes down after
some time. Can you make a full tcpdump/wireshark trace to confirm this ?

Also, please try pure UDP-transport for SIP:
(using IP-address will default to UDP-transport)

```
<sip:1001:password@192.168.0.13:5065>;answermode=auto
```

for the TCP-transport you can also try to enable SIP outbound (CRLF Keepalive)
using the ```;sipnat=outbound``` parameter.

**Comment by jungle-boogie** [comment]
Hello,

**WAS**
`<sip:1001:password@192.168.0.13:5065;transport=tcp>;answermode=auto`

**NOW**:
`<sip:1001:password@192.168.0.13:5065>;answermode=auto`

Registration:
http://pastiebin.com/56e7a3e610082

Inbound call to extension 1001 from extension 1000:
http://pastiebin.com/56e7a3fd7d81e

Outbound call to extension 1000 from 1001:
http://pastiebin.com/56e7a4aade707


Register and wait 5 minutes followed by a call to extension 1001 from extension 1000:
http://pastiebin.com/56e7a7e8b1c67

The last one is very interesting because it shows the call coming in, but baresip doesn't pick it up.

**Comment by jungle-boogie** [comment]
Running actual tcpdump to capture pcaps, I see the following in a scenario similar to the last one above:

`7	327.553199	327.654583	192.168.0.13	192.168.0.3	SIP/SDP	1284	5263	Request: INVITE sip:1001-0x24513f0@192.168.0.3:55216 | `

repeated four times.

In the scenario where 1000 calls 1001 within a few seconds of registering I see this:
`8	0.000858	3.869810	192.168.0.3	192.168.0.13	SIP	543	5802	Status: 180 Ringing | `


Would you like to see the pcaps?

**Comment by jungle-boogie** [comment]
Any advice/input from anyone?

If no one else experiences this, please provide a sample of your .baresip/accounts and some info about what baresip is connecting to.

Also, any idea why 
`<sip:1001:password@192.168.0.13:5065;transport=tcp>;answermode=auto`

Doesn't work even though this is the documented way of setting it up?

**Comment by lmangani** [comment]
Everyone's settings are as per documentation and wiki and they work without issues.

The problem is with your network configuration, confirmed by your pastie (trying to use 45925). Have you tried to lower your registration timers, enable NAT-keepalive mechanisms on the registrar, or you expect this to magically work through your broken NAT?

**Comment by jungle-boogie** [comment]
> The problem is with your network configuration, confirmed by your pastie (trying to use 45925).

Could you point me to the paste with the problem?

> Have you tried to lower your registration timer

Yes: `<sip:1001:password@192.168.0.13:5065>;answermode=auto;regint=900`

> or you expect this to magically work through your broken NAT?

It magically works with my softclient on my andriod,  polycom deskphone and jitsi all on the same LAN.

**Comment by alfredh** [comment]
did you get it working ? any progress on this ?

**Comment by jungle-boogie** [comment]
Well I now have naptr and srv records for my domain that's pointed at freeswitch; Internally, baresip registers via private IP, sip port is now 5060 (was 5065) and yet, I still get this message when starting baresip:
```
ua: outbound requires valid UUID!
module account.so: Function not implemented
```

config string:
`<sip:1001:password@sip.example.net>;sipnat=outbound;outbound="sip:192.168.0.13:5060;transport=tcp"`

Any advice to get it registered?

**Comment by alfredh** [comment]
can you please post a copy of your $HOME/.baresip/config file here, together with
a full debug log output from baresip -v

**Comment by jungle-boogie** [comment]
Here you are:
https://gist.github.com/jungle-boogie/7396b98843a1e2e3d878174df73dcd02

**Comment by alfredh** [comment]
the config file looks fine. We need to find out if the UUID module is loaded properly.

I added a small debug message in the uuid module:

https://github.com/alfredh/baresip/commit/488fa550651037a7e7f7ff21a4a11369ab3afec2

can you list the content of $HOME/.baresip ?
is there a file called ```uuid``` ?

please try the following steps:

1. remove $HOME/.baresip/uuid
2. run baresip -v
3. look for UUID-related log messages

**Comment by alfredh** [comment]
I just tried your config file with my locally compiled baresip, and it works fine.

this could mean that your baresip binary and/or modules are broken.
How did you compile it ?

Can you do a complete uninstall, re-compile from scratch, install
and test it again?

**Comment by alfredh** [comment]
can you also provide the output of the System ('s') command:

Example:

```
--- System info: ---
 Machine:  x86_64/linux
 Version:  0.4.18 (libre v0.4.15)
 Build:    64-bit little endian
 Kernel:   Linux debian 4.4.0-1-amd64 #1 SMP Debian 4.4.6-1 (2016-03-17) x86_64
 Uptime:   4 secs
 Started:  Mon Apr 18 22:38:45 2016
 Compiler: 5.3.1 20160323

```

**Comment by jungle-boogie** [comment]
> How did you compile it ?

just `make` and `sudo make install`
```
sudo make install
install -m 0755 baresip /usr/local/bin
install -m 0644 dtmfio.so stun.so turn.so ice.so natbd.so auloop.so presence.so menu.so contact.so vumeter.so mwi.so account.so natpmp.so httpd.so srtp.so uuid.so aubridge.so aufile.so vidloop.so selfview.so vidbridge.so fakevideo.so alsa.so cairo.so vidinfo.so cons.so dtls_srtp.so evdev.so g711.so g722.so g726.so gst.so gst1.so gst_video.so gst_video1.so l16.so opus.so oss.so plc.so portaudio.so sndfile.so stdio.so syslog.so v4l2.so x11.so x1install -m 0644 share/* /usr/local/share/baresip
```

Prior to fetching the src from github, I removed ~/bin/baresip and the binary at /usr/local/bin/baresip but the ~/.baresip files stayed behind.

Removing the .baresip dir and launching baresip will generate the .baresip directory.

no error with this registration string:
`<sip:1001:password@sip.example.net>;sipnat=outbound;outbound="sip:192.168.0.13:5060;transport=tcp"`

My config string is now this:
`<sip:2601:password@sip.example.net>;sipnat=outbound;outbound="sip:192.168.0.6:5060;transport=tcp";answermode=auto;;regint=900`

I'll test this to see if I can stay registered and get calls.

**Comment by jungle-boogie** [comment]
> can you also provide the output of the System ('s') command:

That command doesn't work. Any suggestions for ubuntu-like distros?

**Comment by jungle-boogie** [comment]
With this account string, baresip doesn't ring at all:

```
<sip:2601:password@sip.example.net>;sipnat=outbound;outbound="sip:192.168.0.6:5060;transport=tcp";answermode=auto;regint=900
````

**Comment by alfredh** [comment]
can you try this:

1. Start baresip
2. Press 'h' for Help:
```
--- Help ---
...
 s       System info
...
```

can you please paste the output of this command here?

**Comment by alfredh** [comment]
Hi, many thanks for your feedback.

What do you mean with "ring at all" ?

using that config lets try establish a couple of basic facts so we can try to resolve the problem.

1. Does outgoing calls work ?
2. Does registration work?
3. Does incoming calls work?
4. If incoming calls are not working, can you use ngrep to check if the incoming INVITE
  is arriving at baresip at all.
5. if the incoming INVITE arrives at baresip, what happens and what does it respond with?


it is a bit hard for me to try to help you when you have multiple problems and keep changing your
config and setup. It is much easier for me to help, if you can describe one clear problem with exactly corresponding config/account/debug/ngrep.

**Comment by jungle-boogie** [comment]
> can you please paste the output of this command here?

--- System info: ---
 Machine:  x86_64/linux
 Version:  0.4.18 (libre v0.4.15)
 Build:    64-bit little endian
 Kernel:   Linux ralph.in.lylie.net 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64
 Uptime:   1 sec
 Started:  Sun Apr 24 12:03:24 2016
 Compiler: 4.8.4

**Comment by jungle-boogie** [comment]
> Does outgoing calls work ?

Yes. Here's output from baresip calling out to the PSTN:
http://pastiebin.com/571d194ba4550

> Does registration work?

Yes, I can register to my freeswitch server.

> Does incoming calls work?

With the config string below, incoming calls do not work at all regardless of amount of time baresip is left running.

registration string:
`<sip:2601:password@sip.example.net>;sipnat=outbound;outbound="sip:192.168.0.6;transport=tcp";answermode=auto;regint=900`

Are there any problems with this registration string? sip.example.net has proper naptr and srv records setup.

> If incoming calls are not working, can you use ngrep to check if the incoming INVITE is arriving at baresip at all.

Nothing is being received at all on the machine that runs baresip.
I'm using `sudo ngrep -p -d any -W byline port 5060` to monitor any inbound calls on the machine that's running baresip.

On freeswitch, I see a trying request:

```
2016/04/24 19:11:55.997942 192.168.0.6:5060 -> 192.168.0.12:40279
SIP/2.0 100 Trying
Via: SIP/2.0/TCP 192.168.0.12;branch=z9hG4bK9f2a70dC892B0EC;rport=40279
From: "sean" <sip:2600@192.168.0.6>;tag=52D368F4-4A1AC113
To: <sip:2601@192.168.0.6;user=phone>
Call-ID: d1c8af0-3f07840f-f48a3d6e@192.168.0.12
CSeq: 2 INVITE
User-Agent: FreeSWITCH-mod_sofia/1.7.0+git~20160421T200430Z~f0dcd7066a~32bit
Content-Length: 0
```

> it is a bit hard for me to try to help you when you have multiple problems and keep changing your
config and setup

Understood. The original problem was calls could be received, but after a short amount of time, with the same config, baresip would stop ringing. I was advised the config string I had was incorrect and it was recommended I try a few different options. Towards the top of this issue, I've reported what config string allows incoming calls and what doesn't. Do you see anything wrong with my most recent config string for baresip?

**Comment by alfredh** [comment]
I tested the same scenario locally with baresip and freeswitch.

It looks like Freeswitch does not support SIP outbound, due to the lack
of ``Require: outbound`` in the 200 OK response:


```
##
T 10.0.0.2:54672 -> 10.0.0.2:5060 [AP]
REGISTER sip:10.0.0.2 SIP/2.0.
Via: SIP/2.0/TCP 10.0.0.2:37574;branch=z9hG4bK6eafb31d46456226;rport.
Contact: <sip:1000-0xa33e40@10.0.0.2:37574;transport=tcp>;expires=3820;+sip.instance="<urn:uuid:eaac0f81-8dcc-dd28-7989-3fe561c881cd>".
Max-Forwards: 70.
Authorization: Digest username="1000", realm="10.0.0.2", nonce="a9461a3e-5468-4b5f-a5b3-fa3fa1613772", uri="sip:10.0.0.2", response="16e051bd0063cf035da52256bd969d19", cnonce="fb90cf11a0ac37e3", qop=auth, nc=00000001.
Route: <sip:10.0.0.2;transport=tcp;lr>.
To: <sip:1000@10.0.0.2>.
From: <sip:1000@10.0.0.2>;tag=e1dad060179c63f1.
Call-ID: 5b8cf7fdb4a5ea90.
CSeq: 60694 REGISTER.
User-Agent: baresip v0.4.18 (x86_64/linux).
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,REFER,NOTIFY,SUBSCRIBE,INFO,MESSAGE.
Content-Length: 0.
.

#
T 10.0.0.2:5060 -> 10.0.0.2:54672 [AP]
SIP/2.0 200 OK.
Via: SIP/2.0/TCP 10.0.0.2:37574;branch=z9hG4bK6eafb31d46456226;rport=54672.
From: <sip:1000@10.0.0.2>;tag=e1dad060179c63f1.
To: <sip:1000@10.0.0.2>;tag=238p31tNvH3NK.
Call-ID: 5b8cf7fdb4a5ea90.
CSeq: 60694 REGISTER.
Contact: <sip:1000-0xa33e40@10.0.0.2:37574;transport=tcp>;expires=3820.
Date: Sun, 08 May 2016 11:41:47 GMT.
User-Agent: FreeSWITCH-mod_sofia/1.6.8-15-99de0ad~64bit.
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE.
Supported: timer, path, replaces.
Content-Length: 0.
.

```


I tested two baresip clients locally with username 1000 and username 1001.
After registration I could see from the Freeswitch console:

```
freeswitch@debian> sofia status profile internal reg


Registrations:
=================================================================================================
Call-ID:    	fd1b6c41512e1f5b
User:       	1000@10.0.0.2
Contact:    	"" <sip:1000-0xb15e40@10.0.0.2:38932;transport=tcp>
Agent:      	baresip v0.4.18 (x86_64/linux)
Status:     	Registered(TCP)(unknown) EXP(2016-05-08 14:26:29) EXPSECS(2709)
Ping-Status:	Reachable
Ping-Time:	0.00
Host:       	debian
IP:         	10.0.0.2
Port:       	54616
Auth-User:  	1000
Auth-Realm: 	10.0.0.2
MWI-Account:	1000@10.0.0.2

Call-ID:    	f50a2696058770e2
User:       	1001@10.0.0.2
Contact:    	"" <sip:1001-0x1c4ceb0@10.0.0.2:35134;transport=tcp>
Agent:      	baresip v0.4.18 (x86_64/linux)
Status:     	Registered(TCP)(unknown) EXP(2016-05-08 14:29:10) EXPSECS(2870)
Ping-Status:	Reachable
Ping-Time:	0.00
Host:       	debian
IP:         	10.0.0.2
Port:       	54626
Auth-User:  	1001
Auth-Realm: 	10.0.0.2
MWI-Account:	1001@10.0.0.2

```


Calling from 1000 to 1001 was possible, also the opposite direction. I waited 10, 20, 30 minutes
and it was still possible to call.

I can also see that Freeswitch is sending out TCP keepalives from port 5060.

Account config used:

```
<sip:1000:0000@10.0.0.2>;outbound="sip:10.0.0.2;transport=tcp"
<sip:1001:0000@10.0.0.2>;outbound="sip:10.0.0.2;transport=tcp"
```


Conclusion: baresip and freeswitch is working just fine.

**Comment by jungle-boogie** [comment]
> Conclusion: baresip and freeswitch is working just fine.

Great, thanks for the confirmation and I'll try your config example.

Thanks!
