### ISSUE TITLE
Outbound calls without transport method

### ISSUE THREAD

**Issue by jungle-boogie** [alfredh/baresip#120]
Hello,

Is it always necessary to specify the transport with baresip on outbound calls?

Without transport:
```
2061@example.me
call: connecting to 'sip:2061@example.me'..
sip:2061@example.me: session closed: Connection refused
```

With transport:
```
> 2601@example.me;transport=udp
call: connecting to 'sip:2601@example.me;transport=udp'..
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 180 Ringing (/)
audio: Set audio decoder: opus 48000Hz 2ch
audio: Set audio encoder: opus 48000Hz 2ch
audio tx pipeline:        alsa ---> vumeter ---> opus
audio rx pipeline:        alsa <--- vumeter <--- opus
1001@192.168.0.13: Call established: sip:2601@example.me;transport=udp
call: terminate call '1c1e7726e8840cd9' with sip:2601@example.me;transport=udp              ]
sip:1001@192.168.0.13:5065: Call with sip:2601@example.me;transport=udp terminated (duration: 52 secs)
```

Baresip is configured to use udp by default:
`<sip:1001:password@192.168.0.13:5065>;answermode=auto`

example.me is my domain that's setup with onsip and can actually receive sip uri calls.
My freeswitch server can call sip uris from other end points without manually specifying the transport.

**Comment by alfredh** [comment]
is your domain configured with the correct DNS entries for SIP?

for example:

```
$ host -t NAPTR creytiv.com
creytiv.com has NAPTR record 10 0 "s" "SIPS+D2T" "" _sips._tcp.creytiv.com.
creytiv.com has NAPTR record 30 0 "s" "SIP+D2U" "" _sip._udp.creytiv.com.
creytiv.com has NAPTR record 20 0 "s" "SIP+D2T" "" _sip._tcp.creytiv.com.
```

```
$ host -t SRV _sip._tcp.creytiv.com
_sip._tcp.creytiv.com has SRV record 0 0 5060 h5.creytiv.com.
```


you should probably use a SIP outbound config:

example with UDP Transport:

```
<sip:1001:password@example.me>;sipnat=outbound;outbound="sip:192.168.0.13:5065"
```

example with TCP Transport:

```
<sip:1001:password@example.me>;sipnat=outbound;outbound="sip:192.168.0.13:5065;transport=tcp"
```

- if Baresip is configured without "outbound" parameter all outgoing SIP Requests
(REGISTER, INVITE etc.) will be resolved using RFC 3261 / RFC 3263 method.

- if Baresip is configured with "outbound" parameter, all outgoing SIP Requests
  will be sent via that Outbound SIP proxy.

(and btw sipnat=outbound enables keepalives on the transport tuple from client
to server, which you should probably enable if your client is behind NAT).

**Comment by jungle-boogie** [comment]
Okay, I actually didn't have a srv record for tcp and I've added that. secondly, i need to work on adding NAPTR records.

> example with TCP Transport

With that example copied as is, I get this:

```
$ baresip
baresip v0.4.18 Copyright (C) 2010 - 2016 Alfred E. Heggestad et al.
Local network address: IPv4=em1:192.168.0.3
aucodec: opus/48000/2
aucodec: G722/8000/1
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
ausrc: alsa
auplay: alsa
medianat: stun
medianat: turn
medianat: ice
1001@example.me: Using sipnat: `outbound'
ua: outbound requires valid UUID!
module account.so: Function not implemented
Populated 1 contacts
Populated 4 audio codecs
Populated 1 audio filter
Populated 0 video codecs
Populated 0 video filters
baresip is ready.
```

Interesting line is this: `module account.so: Function not implemented` 

I have this in .baresip/config:
`module_tmp              account.so`

**Comment by alfredh** [comment]
you must load the uuid.so module (before account)

**Comment by jungle-boogie** [comment]
```
# Temporary Modules (loaded then unloaded)

module_tmp              uuid.so
module_tmp              account.so
```

Like that, right?

**Comment by alfredh** [comment]
yes that is correct.

did you try with sipnat=outbound ? is it work better ?
