### ISSUE TITLE
Can't compile v4l2_codec

### ISSUE THREAD

**Issue by Gilles76** [alfredh/baresip#124]
Hi,

I'm on a RPI 2 with raspbian jessie. It's like a debian 8.0 jessie.

I succeed building baresip with most modules, but can't build v4l2_codec.

What are needeed packages for building it ?

PS: baresip is really well done, it's easy to setup and easy to use. Thank you for your work.

**Comment by alfredh** [comment]
can you try this:

```
$ make EXTRA_MODULES=v4l2_codec
```

**Comment by Gilles76** [comment]
First thank you for your quick answer, it's working. A v4l2_codec.so is produce.
For your information, don't know if it's normal, but after doing a make "EXTRA_MODULES=v4l2_codec" and make install. the module isn't copy to the usr lib directory.

I've got a problem using baresip with v4l2_decode, Do you want me opening another issue or we can continu here ?

**Comment by alfredh** [comment]
can you please post the full debug log output (baresip -v) here ?

**Comment by Gilles76** [comment]
Hi,
Sorry for my late answer, I wasn't home.
Here is the results of the command baresip -v:

`baresip v0.4.18 Copyright (C) 2010 - 2016 Alfred E. Heggestad et al.
Binding to interface 'eth0'
net: eth0: could not get IPv6 address (No such device)
Local network address:  IPv4=eth0:10.10.1.62
ui: stdio
cons: UI console listening on 0.0.0.0:5555
ui: cons
evdev: device name: C-Media Electronics Inc. USB Audio Device
Supported event types:
  Event type 0x00  (Unknown event type: 0x0000)
  Event type 0x01  (Keys or Buttons)
  Event type 0x04  (Something miscellaneous)
Supported Keys:
  Key  0x71  (Mute)
  Key  0x72  (Volume Down)
  Key  0x73  (Volume Up)
Supported LEDs:
ui: evdev
ui: http
httpd: listening on 0.0.0.0:8888
aucodec: opus/48000/2
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
ausrc: alsa
auplay: alsa
v4l2_codec inited
vidcodec: H264
vidsrc: v4l2_codec
avcodec: x264 build 142
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidcodec: VP8
vidsrc: v4l2
medianat: stun
medianat: turn
medianat: ice
Populated 1 account
Populated 3 contacts
Populated 3 audio codecs
Populated 1 audio filter
Populated 5 video codecs
Populated 0 video filters
baresip is ready.
1000@10.10.1.62: {0/TLS/v4} 200 OK () [1 binding]
All 1 useragent registered successfully! (148 ms)`

**Comment by Gilles76** [comment]
After a vidéo call with linephone:

sip:1000@10.10.1.62: Incoming call from: Gilles sip:1001@10.10.1.62 - (press ENTER to accept)
alsa: reset: srate=8000, ch=1, num_frames=320, pcmfmt=S16_LE
alsa: playback started (default)
sip:1000@10.10.1.62: Answering incoming call
alsa: stopping playback thread (default)
answering call from sip:1001@10.10.1.62 with 200
audio: Set audio decoder: PCMU 8000Hz 1ch
alsa: reset: srate=8000, ch=1, num_frames=160, pcmfmt=S16_LE
alsa: playback started (default)
audio: Set audio encoder: PCMU 8000Hz 1ch
alsa: reset: srate=8000, ch=1, num_frames=160, pcmfmt=S16_LE
alsa: recording started (default)
audio tx pipeline:        alsa ---> vumeter ---> PCMU
audio rx pipeline:        alsa <--- vumeter <--- PCMU
Set video encoder: H264 packetization-mode=0 (500000 bit/s, 25 fps)
v4l2_codec: video encoder H264: 25 fps, 500000 bit/s, pktsize=1024
video: vidcodec 'H264' has no decoder
Set video decoder: H264 packetization-mode=0
avcodec: video decoder H264 ()
video: could not set vidisp '': No such file or directory
v4l2_codec: video-source alloc (device=/dev/video0)
v4l2_codec: opening video-encoder device (device=/dev/video0)
v4l2_codec: Driver Caps:
  Driver:        "bm2835 mmal"
  Card:          "mmal service 16.1"
  Bus:           "platform:bcm2835-v4l2"
  Version:       4.0
  Capabilities:  0x85200005
  FMT : CE Desc
--------------------
     YU12:    'Planar YUV 4:2:0'
     YUYV:    'YUYV 4:2:2'
     RGB3:    '24-bit RGB 8-8-8'
     JPEG: C  'JFIF JPEG'
  >  H264: C  'H.264'
     MJPG: C  'Motion-JPEG'
     YVYU:    'YVYU 4:2:2'
     VYUY:    'VYUY 4:2:2'
     UYVY:    'UYVY 4:2:2'
     NV12:    'Y/CbCr 4:2:0'
     BGR3:    '24-bit BGR 8-8-8'
     YV12:    'Planar YVU 4:2:0'
     NV21:    'Y/CrCb 4:2:0'
     BGR4:    '32-bit BGRA/X 8-8-8-8'

v4l2_codec: Selected Camera Mode:
  Width:   352
  Height:  288
  PixFmt:  H264
  Field:   1
video tx pipeline: v4l2_codec ---> H264
video rx pipeline:       disp <--- H264
1000@10.10.1.62: Call established: sip:1001@10.10.1.62
main: long async blocking: 469>100 ms (h=0x76eea4cc arg=0x10d1be0)
[0:00:00] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:00] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:00] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:00] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:01] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:01] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:01] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:01] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:01] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:01] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:01] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:01] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:01] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:01] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:02] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:02] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:02] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:02] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:02] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:02] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:02] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:02] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:02] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:02] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:03] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:03] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           [0:00:03] audio=0/0 video=0/0 (bit/s) efps=0/0              [                ]  [           call: terminate call 'c5eb165a-811c-1234-999c-b827eb7b3d70' with sip:1001@10.10.1.62
alsa: stopping recording thread (default)
alsa: stopping playback thread (default)
v4l2_codec: encoder stats (keyframes:1, deltaframes:0)
sip:1000-0x10df6a8@10.10.1.62:35236: Call with sip:1001@10.10.1.62 terminated (duration: 4 secs)
main: long async blocking: 1035>100 ms (h=0x769f2a28 arg=0x10d3f10)

**Comment by alfredh** [comment]
many thanks for the debug logs.

Can you please tell me what is the problem?

the only thing I could see from the log was very few video frames coming
from your device:

```
v4l2_codec: encoder stats (keyframes:1, deltaframes:0)
```

**Comment by Gilles76** [comment]
You're welcome for the log.

The problem is no video is send through baresip to another soft-phone.

I make some tests with linphone and antisip and it's the same result with h264 v4l2_codec.

What I see is like you: no frame send from baresip to soft-phone.

Another test with baresip and linphone on android:

> main: long async blocking: 495>100 ms (h=0x76ebd4cc arg=0xfe3be0)
[h264 @ 0xffb420] no frame!/0 (bit/s) efps=0/0              [                ]  [                ]
video: H264 decode error (seq=55171, 3 bytes): Bad message
call: terminate call '9942afad-84d4-1234-999c-b827eb7b3d70' with sip:1001@10.10.1.62             ]
alsa: stopping recording thread (default)
alsa: stopping playback thread (default)
v4l2_codec: encoder stats (keyframes:1, deltaframes:0)
sip:1000-0xff07e0@10.10.1.62:41141: Call with sip:1001@10.10.1.62 terminated (duration: 32 secs)
main: long async blocking: 1062>100 ms (h=0x769c5a28 arg=0xfe5f10)

What is the last line for you ?

For more information in my messages log in raspberry pi 2, I have "bcm2835-v4l2: error 0 waiting for frame completion" when a video conversation is ended.

The pi camera is functionnal as I can us it with baresip without v4l2_codec but it's to laggy.

An example with antisip and baresip.

If I make a call from baresip to antisip with avcodec, it's working but too slow.

> avcodec: x264 picture update                                [                ]  [===             ]
avcodec: x264 picture update0 (bit/s) efps=0/0              [                ]  [                ]
avcodec: x264 picture update0 (bit/s) efps=0/0              [                ]  [                ]
avcodec: x264 picture update0 (bit/s) efps=0/0              [                ]  [                ]
avcodec: x264 picture update0 (bit/s) efps=0/0              [                ]  [                ]
avcodec: x264 picture updatevideo=139994/0 (bit/s) efps=0/0 [                ]  [                ]
avcodec: x264 picture updatevideo=139994/0 (bit/s) efps=0/0 [                ]  [                ]
avcodec: x264 picture updatevideo=139994/0 (bit/s) efps=38/ [                ]  [                ]
avcodec: x264 picture update                                                    [                ]
avcodec: x264 picture updatevideo=61832/0 (bit/s) efps=38/0 [                ]  [                ]
avcodec: unknown NAL type 24video=61832/0 (bit/s) efps=38/0 [                ]  [                ]
video: H264 decode error (seq=14531, 20 bytes): Bad message
avcodec: unknown NAL type 24
video: H264 decode error (seq=14532, 20 bytes): Bad message
avcodec: x264 picture updatevideo=61832/0 (bit/s) efps=38/0 [                ]  [                ]
avcodec: unknown NAL type 24video=61832/0 (bit/s) efps=38/0 [                ]  [                ]
video: H264 decode error (seq=14611, 20 bytes): Bad message
avcodec: unknown NAL type 24
video: H264 decode error (seq=14612, 20 bytes): Bad message
avcodec: x264 picture updatevideo=61832/0 (bit/s) efps=38/0 [                ]  [                ]
avcodec: unknown NAL type 24video=61832/0 (bit/s) efps=38/0 [                ]  [                ]
video: H264 decode error (seq=14691, 20 bytes): Bad message
avcodec: unknown NAL type 24
video: H264 decode error (seq=14692, 20 bytes): Bad message
avcodec: x264 picture updatevideo=49922/0 (bit/s) efps=38/0 [                ]  [                ]
avcodec: x264 picture updatevideo=49922/0 (bit/s) efps=38/0
avcodec: unknown NAL type 24video=49922/0 (bit/s) efps=38/0 [                ]  [                ]
video: H264 decode error (seq=14781, 20 bytes): Bad message
avcodec: unknown NAL type 24
video: H264 decode error (seq=14782, 20 bytes): Bad message
sip:1001@10.10.1.62;transport=udp: session closed: Connection reset by peer  ]  [                ]
alsa: stopping recording thread (default)
alsa: stopping playback thread (default)
sip:1000@10.10.1.62: Call with sip:1001@10.10.1.62;transport=udp terminated (duration: 11 secs)
main: long async blocking: 103>100 ms (h=0x76ec74cc arg=0xb16be0)

If I call from antisip to baresip I can see the  video is send to baresip but baresip don't recive any video. This problem is not important for the moment as I want to make a video call from baresip.

**Comment by czarkoff** [comment]
Could you try with `x11` module loaded?

**Comment by Gilles76** [comment]
It's an headless machine, X11 is really needed ?

**Comment by czarkoff** [comment]
If you install client libraries, you may use X11 server on another machine.

From your logs it seems that only 1 frame is read from device. I did not dig deep into the video code, but I guess it may have something to do with output. Do you have `video_selfview` in your `~/.baresip/config`? Can you post the config?

**Comment by alfredh** [comment]
can you try to record raw H.264 frames using ffmpeg:

```
$ ffmpeg -f v4l2 -input_format h264 -standard pal-b -s 704x576 -i /dev/video0 -vcodec copy -loglevel debug test.mp4
```

if this does not work, then it will not work with baresip either ..

**Comment by alfredh** [comment]
I am closing this issue for now .. If you want to continue the debugging, then please
make sure that your device is working properly first and feel free to open a new Issue ..
