### ISSUE TITLE
baresip failed to start on config err on Android

### ISSUE THREAD

**Issue by seven1240** [alfredh/baresip#134]
Hi, I built baresip android demo with

baresip 0.4.19
re-0.4.16
rem-0.4.17

try to run baresip show the following err. I even did make config which pushed config files to Android. The path //.baresip/config looks strange, and hint to fix that? Thanks.

shell@icesky_msm8992:/data/local/tmp $ ./baresip
baresip v0.4.19 Copyright (C) 2010 - 2016 Alfred E. Heggestad et al.
config: creating config template //.baresip/config
config: writing //.baresip/config: No such file or directory
main: configure failed: No such file or directory
ua: stop all (forced=1)

**Comment by alfredh** [comment]
you need to specify the config path with baresip -f /data/local/tmp

an improvement could also be to add this to baresip source code:

```
ifdef ANDROID
config_path = "/data/local/tmp"
endif
```

a working patch is welcome :)

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> you need to specify the config path with baresip -f /data/local/tmp
> 
> an improvement could also be to add this to baresip source code:
> 
> ```
> ifdef ANDROID
> config_path = "/data/local/tmp"
> endif
> ```

Isn't there in Android a proper "home" directory for the user where to
place the .baresip dir?

-- Juha

**Comment by juha-h** [comment]
Actually there is a "home" directory. For the primary user it is
/storage/emulated/0.

I could try to create a patch.

-- Juha

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> a working patch is welcome :)

I tested and the enclosed patch seems to work.

Another question:  where should the wav files go?

One more:  When I try to make call, I get an error

audio: start_source failed (.): No such device

In config file have the default:

audio_source: opensles

What audio devices to use in Android?

-- Juha

**Comment by alfredh** [comment]
can you please try the fix which I just pushed (see above).

My Android device does not have the mentioned path:

```
$ ls -al /storage/emulated/0                     
/storage/emulated/0: No such file or directory

```

I chose `/data/local/tmp` because it works well on non-rooted Android devices
and also on Android emulator. 

Please keep in mind that baresip-android is mostly a test-platform, it is not
really a end-user product. I use it to test baresip code and retest code on
a real target.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> My Android device does not have the mentioned path:
> 
> $ ls -al /storage/emulated/0                     
> /storage/emulated/0: No such file or directory

That is strange, since both my 4.2 and 5.1 Android devices have that
path. It only shows if I'm normal user.  If I'm root user, it is mapped
to something else.

> I chose `/data/local/tmp` because it works well on non-rooted Android devices
> and also on Android emulator.

At least of my 4.2 Android device, normal user cannot even see contents
of /data/local/tmp.  When I do ls there, I get 'opendir
failed. Permission denied'

-- Juha

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> can you please try the fix which I just pushed (see above).

Sorry, but I have missed that push.  Which repo was it?

> I chose `/data/local/tmp` because it works well on non-rooted Android devices
> and also on Android emulator.

I would still make sense to have in re/src/sys/fs.c this:

#ifdef FORCED_HOME
	str_ncpy(path, FORCED_HOME, sz);
	return 0;
#elif WIN32
...

because it would allow people to use whatever home path they like.

The above combined with these changes in baresip-android Makefile:

# User's directory on your Android-device
TARGET_HOME=/storage/emulated/0
...
CFLAGS    := \
	-isystem $(SYSROOT)/include/ \
	-I$(PWD)/openssl/include \
	-march=armv7-a \
	-fPIE \
	-DFORCED_HOME='\"$(TARGET_HOME)\"'

is now working fine with me.  In the official Makefile TARGET_HOME could
be commented out.

-- Juha

**Comment by alfredh** [comment]
How are you coping the baresip binary to your Android device?

I am using "make install" inside the baresip-android project:

```
$ make install
...
  LD      baresip
make[1]: Leaving directory '/home/alfredh/git/baresip-android/baresip'
/home/alfredh/android/android-sdk/platform-tools/adb push baresip/baresip /data/local/tmp/baresip
3351 KB/s (3949748 bytes in 1.150s)

```
This is using `adb` to install the file on target. I guess adb is running as some kind
of non-root user:

```
adb shell id
uid=2000(shell) gid=2000(shell) groups=1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats) context=u:r:shell:s0
```

BTW: Have you tested that access to the audio device works, when running baresip
as that normal user ?

**Comment by alfredh** [comment]
https://github.com/alfredh/baresip/commit/7d197f802f5804a31365aad38cdcc0272084089d

**Comment by czarkoff** [comment]
@alfredh: generally adb runs unpriviledged, but:
```
  adb root                     - restarts the adbd daemon with root permissions
```

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> How are you coping the baresip binary to your Android device?

I don't have an usb cable, so I put baresip binary on my web server and
then download it from there to my Android device.
> 
> BTW: Have you tested that access to the audio device works, when
> running baresip as that normal user ?

After the hassle with undefined symbols, I just was able to try
again with using opensles as audio_* device and I get

audio: start_source failed (.): No such device

But I have not installed the wav files yet if that matters.  Need to get
audio_path to config file first.

-- Juha

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> How are you coping the baresip binary to your Android device?

After downloading the wav files to my Android device, I didn't anymore
get the error message about audio device.  When I placed a call, I was
able to hear ringing sound, i.e., audio worked. But then when callee
replied to the call , I got Segmentation Fault.

-- Juha

**Comment by alfredh** [comment]
Thanks for your review comments.

I pushed a fix to baresip adding CONFIG_PATH if defined, and a similar patch
to use it in baresip-android:

https://github.com/alfredh/baresip-android/commit/8045578febf544fd79ba7bcabda180c048ce0d86

no changes to libre are needed.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I pushed a fix to baresip adding CONFIG_PATH if defined, and a similar patch
> to use it in baresip-android:
> 
> https://github.com/alfredh/baresip-android/commit/8045578febf544fd79ba7bcabda180c048ce0d86
> 
> no changes to libre are needed.

That is good.  I have a suggestion though to baresip-android Makefile:

- add lines

# Config path where .baresip directory is located
CONFIG_PATH=/data/local/tmp

- change line

	-DCONFIG_PATH='\"$(TARGET_PATH)\"'

  to

	-DCONFIG_PATH='\"$(CONFIG_PATH)\"'

That way CONFIG_PATH does not need to be the same as TARGET_PATH.

-- Juha

**Comment by alfredh** [comment]
Hey Juha, your suggestion was added here:

https://github.com/alfredh/baresip-android/commit/e6a2674ac7ea4caef0d4ddc1e5a2eebaeddf3473


if everything works as expected now please close this Issue.


You are welcome to open new Issue related to Android audio, permissions etc.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> Hey Juha, your suggestion was added here:
> 
> https://github.com/alfredh/baresip-android/commit/e6a2674ac7ea4caef0d4ddc1e5a2eebaeddf3473

That is great. Thanks.

> if everything works as expected now please close this Issue.

I checked and I have not opened any issues in
alfredh/baresip-android or alfredh/baresip repos.

-- Juha

**Comment by seven1240** [comment]
Hi, thanks all the hardwork. I'll verify tomorrow

**Comment by seven1240** [comment]
confirmed it works. thanks.
