### ISSUE TITLE
audio (alsa->pulseaudio) does not work on mobile BQ E4.5

### ISSUE THREAD

**Issue by gurucubano** [alfredh/baresip#136]
I ported baresip (from git) to the device and can register fine. Only audio
does not works and an audio loop gives only grrr-grrr-grrr noices. The messages
in baresip are:

All 1 useragent registered successfully! (4925 ms)
Audio-loop: 8000Hz, 1ch
alsa: reset: srate=8000, ch=1, num_frames=160, pcmfmt=S16_LE
alsa: playback started (pulse)
alsa: reset: srate=8000, ch=1, num_frames=160, pcmfmt=S16_LE
alsa: recording started (pulse)
8000Hz 1ch  n_read=655 n_write=57 rw_ratio=11.49Quit
ua: stop all (forced=0)
alsa: stopping recording thread (pulse)
alsa: stopping playback thread (pulse)
Stopping 1 useragent..
main: long async blocking: 333>100 ms (h=0xf6d539e9 arg=0x118d78)

(please note the diff between n_read=655 n_write=57)

and the relevant config in .baresip/config is:

audio_player            alsa,pulse
audio_source            alsa,pulse
audio_alert             alsa,default
#audio_srate            8000-48000
audio_channels          1-2
ausrc_srate             48000
auplay_srate            48000
#ausrc_channels         0
#auplay_channels                0

Any ideas?
_

**Comment by alfredh** [comment]
can you try to find out if is the "Playback" or "Recording" that is buggy ?

A couple of options:

- Add some debug code to alsa.so, count overruns/underruns stats etc. and
  debug the audio device.

- You can test the portaudio.so module and see if that is working any better

- Implement a native Pulseaudio driver module, using the API that is defined
  in `/usr/include/pulse/pulseaudio.h` -- This module will be useful to have anyway.
  Any volunteers who want to implment a pulse module?

**Comment by alfredh** [comment]
a new module for pulseaudio can be found here, please test it:

https://github.com/alfredh/baresip/tree/pulse


```
module    pulse.so
audio_source  pulse,
audio_player pulse,
```

**Comment by gurucubano** [comment]
El día Saturday, June 11, 2016 a las 01:43:20AM -0700, Alfred E. Heggestad escribió:

> a new module for pulseaudio can be found here, please test it:
> 
> https://github.com/alfredh/baresip/tree/pulse

Hello Alfred,

On my Ubuntu BQ E4.5 I have had to install some more packages (only in
the chroot container I'm using for building, no changes in the phone
system itself) and tweak the mk/modules.mk file:

40d39
< #   USE_PULSE         PULSE audio driver
68,69d66
< USE_PULSE  := $(shell [ -f $(SYSROOT)/include/pulse/pulseaudio.h ] || \
< 	[ -f $(SYSROOT_ALT)/include/pulse/pulseaudio.h ] && echo "yes")
276,278d272
< ifneq ($(USE_PULSE),)
< MODULES   += pulse
< endif

after this pulse.so gets build and for the first time I can hear "The
call failed" when calling 'echo@ekiga.net' !!!  Hurrah!!!

Will do more tests.

Thanks

	matthias

-- 
Matthias Apitz, ✉ guru@unixarea.de, ⌂ http://www.unixarea.de/  ☎ +49-176-38902045
"Die Verkaufsschlager des Buchmarkts geben Auskunft über den Zustand einer Gesellschaft bzw.
sind, was diese Zeiten angeht, Gradmesser fortschreitenden Schwachsinns. ..." (jW 19.05.2016)

**Comment by gurucubano** [comment]
SIP calls to some echo service like echo@iptel.org do fine as well, the voice is clear and of high volume; this is a big step forward on the Ubuntu mobile devices BQ E4.5 and M10;

**Comment by alfredh** [comment]
Hi Matthias, thank you for the testing and your feedback.

If baresip is working on your os/device now, perhaps you could be so kind as to add it
to the Wiki, on the Interoperability section or Supported Platforms section:

https://github.com/alfredh/baresip/wiki/Supported-platforms

Would you also like be the maintainer of these binary packages for Ubuntu phone?
(if so please add your name to the list :)

I guess this issue can be closed now ?

**Comment by gurucubano** [comment]
The issue can be closed (should I do this?); I added the current binary to the table;

**Comment by alfredh** [comment]
thanks :)
