### ISSUE TITLE
GUI discusstion

### ISSUE THREAD

**Issue by seven1240** [alfredh/baresip#140]
https://github.com/alfredh/baresip/issues/139 mentioned GUI but I think it would be better to start a new issue and talk here.

I noticed there's already a windows GUI keep updating for years. I wondering how it works and maybe we can learn some from that.

I'm just started coding to see if I can make a GUI Mac app with https://github.com/andlabs/libui . The idea is to let libbaresip remain in a lib and create a new project for a GUI App. I'm trying to add a middle layer between the GUI and baresip. e.g. GUI know nothing about baresip and baresip headers are not needed. This might be easy to create different bindings for Android and iOS etc.

long-string commands is not a problem. If we can control everything with commands it's really a good middle layer. We just need a light wrap-up so it can be called from GUIs (whatever framework or language).

It's really just experimenting but if get enough interest I'd like to be involved in the discussion/coding of the new GUI. I mainly work on Mac but I want it to be cross platform.

Update: I found there's a gtk mod looks like already a feature rich UI.

**Comment by alfredh** [comment]
I added support for long commands, please review:

https://github.com/alfredh/baresip/commit/e3ecbddba06f91c3ef5b3cd8305a8f2fdb6c9cde

**Comment by alfredh** [comment]
in general baresip is a library and a command-line client. Third party projects
are welcome to create a new UI and use libbaresip as a base.

In addition to that we have the nice `gtk` module which can be used as a simple UI.

I am closing this ticket for now. Please feel free to open a new ticket with a more
concrete problem statement/task.

**Comment by r3code** [comment]
@alfredh Little question how to build the gtk module, it won't build when I run `make && make install` for baresip as it written in the readme?
If I receiving a video call must I see the window with a picture or I must enable `gtk`  or other modules?

**Comment by FallenChromium** [comment]
A bit of a weird question too. I installed all the dependencies needed to build gtk (huh, had to discover it inside makefiles, it's probably a good idea to document this, or am I blind and just not seeing this?). By the way, it built successfully but i can't run GUI - it just stucks at "launching GTK+ window/menu", and as I'm completely new to this library, I wasn't able to debug this (don't have huge experience with gtk either). Any suggestions on this? @alfredh I know it's kinda wrong to ask you about that module ((GUI not intended to grow in library project), but I'm gonna mod this a bit for my needs and just to makr it launch help would be really appreciated :joy_cat: 
I'm building on Ubuntu 18.04 by the way, if you need any other information ping me freely.

**Comment by FallenChromium** [comment]
UPDATE: I discovered awful Ubuntu GNOME 3 bug that leads to tray icon not showing, all works fine under MATE edition of Ubuntu 18.04, so it's not the issue of baresip. By the way, there's a workaround for this by changing XDG DE var to "Unity", so it will show the icon in tray. Feels a bit weird tho. Thanks anyway!

**Comment by gpolitis** [comment]
@FallenChromium alternatively you can install the [TopIcons Plus extension](https://extensions.gnome.org/extension/1031/topicons/). And since you're on Ubuntu you can simply `apt-get install gnome-shell-extension-top-icons-plus package`.
