### ISSUE TITLE
support multi calls

### ISSUE THREAD

**Issue by seven1240** [alfredh/baresip#141]
Based on https://github.com/alfredh/baresip/issues/139 I also has the problem.

I can make two calls with "d" but then I get a lot of

WARNING:  >aq> 982: Input ring buffer returning 0x400 frames of silence (trying to read: 81920 - 86016; current bounds 84630 - 117398) (0 previous warnings suppressed)

and there's no way to switch between calls.

**Comment by alfredh** [comment]
can you please give some details about platform (OS, compiler etc.)
and which audio driver module you are using?

this warning is not coming from baresip.

regarding switching between calls it should be possible to implement this,
which keys do you prefer ?

**Comment by GGGO** [comment]
The TAB key + the ID would be fine I think. 

By ID, I mean the line number of the call starting at 1. 

I'm looking for an algorythm to generate the new next ID and re-use the lowest available ID for new call. 

Pressing the TAB key will print the calls info with their LineID and we choose the line by number. 

Pressing TAB + ENTER will switch back to last hold line ?

**Comment by seven1240** [comment]
I was on Mac 10.11.1 (15B42)

**Comment by alfredh** [comment]
@GGGO thank you very much for your suggested idea.

The above commit adds support for Unique Line-numbers for each call,
sequential starting at 1. Example console output with 3 calls:

```
--- List of active calls (3): ---
  [line 1]  0:00:10  ESTABLISHED             sip:echo@creytiv.com
  [line 2]  0:00:06  ESTABLISHED             sip:radio@creytiv.com
  [line 3]  0:00:01  ESTABLISHED             sip:music@creytiv.com
```

I think we should reserve TAB for auto-completions of long commands,
so we need to find another Key.

**Comment by GGGO** [comment]
@alfredh thank you for this commit !

And what about the backspace key ?

**Comment by alfredh** [comment]
Please take a look at this commit:

https://github.com/alfredh/baresip/commit/49ea18057b64e2a806d6799bc2aa87b30491634e

it adds a new command '@' for switching the "current" call:

```
 @ ..    Set current call <line>
```

using the `l' command you can list the calls:
(the angle bracket on line 2 indicates current call)

```
--- List of active calls (4): ---
    [line 1]  0:00:08  ESTABLISHED             sip:echo@creytiv.com
  > [line 2]  0:00:35  ESTABLISHED             sip:radio@creytiv.com
    [line 3]  0:00:32  ESTABLISHED             sip:music@creytiv.com
    [line 4]  0:00:04  ESTABLISHED             sip:echo@creytiv.com
```


Please note that when switching calls, it only changes the current call.
It does not resume or hold any calls. I think we should keep it in such a way
that you can hold/resume any call, have multiple active calls etc.

**Comment by alfredh** [comment]
@seven1240 and @GGGO could you please test the latest version of baresip from git,
and see if your required features are working in that version?

the original bug in the top is related to 2 calls using the same audio-device.
if you want to make 2 outgoing calls, you should put the 1st on on hold and then
dial the 2nd call.

**Comment by GGGO** [comment]
On Windows, sometimes baresip crashes after switching between calls or after hanging up a call.

I think it's related the hold/unhold state before a hangup but I can't be sure.

What is the steps to enable full debug log in baresip and libre ? Maybe I could help.

**Comment by alfredh** [comment]
I just tested baresip with `audiounit.so` module on OSX 10.12
and multiple calls works just fine.

If there is a problem related to multiple calls on Windows could you please create a new
issue only for that issue ?
