### ISSUE TITLE
network interface cons.so is missing output about result of commands

### ISSUE THREAD

**Issue by gurucubano** [alfredh/baresip#144]
I was looking around for an interface to baresip to construct some GUI, for example in QML. Perhaps best would be the network socket driver cons.so which works fine, for example:

```
$ echo 'd echo@ekiga.net' | nc 10.42.0.1 5555
>                   echo@ekiga.net
```

the peer gets called, the call failed but this result is only visible in the console of baresip::

```
All 1 useragent registered successfully! (1751 ms)
call: connecting to 'sip:echo@ekiga.net'..
sip:echo@ekiga.net: session closed: 480 Offline
pulse: opening player (8000 Hz, 1 channels, device '')
pulse: playback started
pulse: stopping playback thread
```

to be able to build something, one would need the answer in the socket connection. Do I miss something here?

**Comment by alfredh** [comment]
your observation is correct.

commands use a kind of context-sensitive output, where the output to a given command
is printed into a `struct re_printf` print handler, implemented by that input subsystem
(for example cons.so).

example code from menu module:

```
static int cmd_answer(struct re_printf *pf, void *unused)
{
	err = re_hprintf(pf, "%s: Answering incoming call\n", ua_aor(ua));
}
```

other debug output lines are printed using the log.c subsystem, which can be printed
to stderr or a list of log handlers.

one possible solution could be to install a log-handler in cons.so, that receives a copy
of all log-lines. Inside this handler we can relay the text to the active UDP/TCP
connection/peer.

example pseudo code:

```
static void log_handler(uint32_t level, const char *msg)
{
    tcp_send(cons->tc, msg);
}
```

on the other hand I would not recommend using this interface for writing a GUI.
you would have to parse all the log lines and try to make sense of it, and your GUI
will then be very sensitive to changes in baresip logging lines.

a better approach is to interface the "C" api in baresip.h directly and duplicate the
calling logic of menu.c inside your GUI application. @clehner have done this
quite elegantly in the nice gtk.so module :)

**Comment by gurucubano** [comment]
Thanks for your helping comments. I was thinking in a very crude prototype in QML, mostly to verify the doability of a baresip-app for the BQ mobile device and to clarify open/unresolved questions, like the problem of the audio volume, for example.  

The app should have a one line text-input field, to enter the one-letter commands (only s upported subset), or a SIP addr; three buttons to (1)dial/hangup, (2)accept a call and (3)show status; and below a large output window with a scrolbar to show the result or output of baresip, as you would see it when you fire up the commands via TELNET. That's why my first thinking was in the network interface, I found it ideal for this. The only parsing of baresip's output would be to decide if the call is  now in progress to change the 'dial' button to 'hangup', but even this could be done having two separate buttons for this. The rest of the parsing will be done by the user reading the output window.

What do you think about such an approach? Is someone working on a GUI for Android?
 
```
 C       List contacts
 D       Accept incoming call    (button)
 b       Hangup call             (button)
 c       Call status
 d ..    Dial                    (button)
 g       Print configuration
 h       Help menu
 l       List active calls       (button)
 q       Quit                    (slide app away)
 r       Registration info
 s       System info

+--------------------------------------+
|+------------------------------------+|
||myuser@iptel.org                    ||
|+------------------------------------+|
||
|+---------+     +------+      +------+|
||dial/hang|     |accept|      |status||
|+---------+     +------+      +------+|
|                                      |
|output window:                        |
|+------------------------------------+|
||                                    ||
||                                    ||
||                                    ||
||                                    ||
||                                    ||
|+------------------------------------+|
+--------------------------------------+

```

**Comment by alfredh** [comment]
I just made a fix to relay log-messages to all active UDP/TCP connections.

Can you please test and see if it is working for you?
