### ISSUE TITLE
New pulse module?

### ISSUE THREAD

**Issue by athlon4011** [alfredh/baresip#145]
How do you compile the new pulse module for use? I see that its included in the modules section, but it doesn't generate the pulse.so for use.

**Comment by alfredh** [comment]
try this:

```
$ make EXTRA_MODULES=pulse
$ sudo make EXTRA_MODULES=pulse install
```

mk/modules.mk should be updated to autodetect libpulse-dev

**Comment by athlon4011** [comment]
Worked like a charm! Thanks for the new module.
