### ISSUE TITLE
Can't dial a number with '*'

### ISSUE THREAD

**Issue by GGGO** [alfredh/baresip#149]
Since the commit 7f35380ee3a39faad1f10fcbb6b115b8ddc5f2a7, we can't dial anymore a number with '*'.

**Comment by alfredh** [comment]
can you please describe the problem in more detail? please also include
exact steps how to reproduce the issue with full baresip log

**Comment by GGGO** [comment]
On windows with wincons. 

I can't dial *98 anymore. It will dial the previous number dialed.

**Comment by alfredh** [comment]
it looks like the Wincons driver is sending key=0x00 (KEYCODE_NONE) when the
star '*' (shift-8 on my keyboard) is pressed.

Can you please try again with latest HEAD (see above commit)

**Comment by GGGO** [comment]
Latest commit 961ced0a7b83e5d68de41a9442bbd4c810ad8a59 fixed it.

Thanks.
