### ISSUE TITLE
build error (master branch on Ubuntu 14 32bit latest updates)

### ISSUE THREAD

**Issue by cypa** [alfredh/baresip#155]
src/video.c: In function ‘video_stream_decode’:
src/video.c:597:3: warning: implicit declaration of function ‘vidframe_copy’ [-Wimplicit-function-declaration]
   vidframe_copy(frame_filt, frame);
   ^
src/video.c:597:3: warning: nested extern declaration of ‘vidframe_copy’ [-Wnested-externs]
  CC      build-i686/src/vidcodec.o
  CC      build-i686/src/vidfilt.o
  CC      build-i686/src/vidisp.o
  CC      build-i686/src/vidsrc.o
  CC      build-i686/src/main.o
  LD      baresip
build-i686/src/video.o: In function `video_stream_decode':
/home/cypa/tmp/baresip/src/video.c:597: undefined reference to `vidframe_copy'
collect2: error: ld returned 1 exit status
make: *** [baresip] Ошибка 1

**Comment by cypa** [comment]
how do I disable video? 
USE_VIDEO := 0 in Makefile doesn't help

**Comment by cypa** [comment]
commented next line in 2 files to build successfully

//                      vidframe_copy(frame_filt, frame);

**Comment by czarkoff** [comment]
@cypa: you should have updated [librem](http://creytiv.com/rem.html) to version 0.4.7 or later.

P.S.: to disable video you need to call make with `USE_VIDEO=` flag.

**Comment by cypa** [comment]
OK
