### ISSUE TITLE
Segmentation fault on fd_listen (using select multeplexer)

### ISSUE THREAD

**Issue by vit1251** [alfredh/baresip#156]
Hello,

Error in code

```
if (fd >= re->maxfds) {
    if (flags) {
        DEBUG_WARNING("fd_listen: fd=%d flags=0x%02x\n"
                  "\t- Max     %d fds\n",
                  fd, flags, re->maxfds);
    }
    return EMFILE;
}
```

in select pool method.

I have fd=616 and maxfds=64.

I think this is confusion between quantity in maxfds and max handler ID (absolute value).

**Comment by alfredh** [comment]
if you are using fd=616 then you must choose a maxfds that is higher than 616,
for example 1024. You can call the fd_setsize function to set it

```
fd_setsize(1024);
```

Which platform are you using, and can you please post the exact backtrace of your crash ?

**Comment by vit1251** [comment]
@alfredh I check it on Windows platform.

**Comment by alfredh** [comment]
Hi @vit1251 please see the baresip-win32 project for how to compile baresip
for windows:


https://github.com/alfredh/baresip-win32

in the Makefile we have this section:

```
CFLAGS    := -DFD_SETSIZE=1024 \
	-isystem $(PWD)/openssl/include
```


can you try to build libre with FD_SETSIZE=1024 ?

**Comment by alfredh** [comment]
this is not a bug, if the fd is larger than maxfds the function `fd_listen`
is returning `EMFILE` as expected.

I tested this locally, and the code does not crash.

You are welcome to re-open the issue but then please provide exact info about your
system, how you compiled it, full logs and backtraces.
