### ISSUE TITLE
avformat - directly pipe video in h264 without decoding/encoding from RTSP source

### ISSUE THREAD

**Issue by koman-maciej** [alfredh/baresip#160]
Hello,

I would like to stream video from IP camera over SIP (RTSP source) by using avformat (exactly the same issue: #97) to the sip client. The problem is that video stream from IP camera is decoded by avformat and encoded again by baresip. 

Is it possible to stream video without those operations (hardware limitations)? FFmpeg has an option `-vcodec` where you can set `copy` parameter to copy stream as is, maybe it's good start point?

Regards,
Maciej

**Comment by czarkoff** [comment]
So you use baresip on camera side, aren't you?  Did you try `v4l2_codec`?

**Comment by koman-maciej** [comment]
Unfortunately not, baresip will be on the server side which is low power and performance device. Assuming the IP camera supports only RTSP protocol, so I need RTSP client in baresip. `v4l2_codec` doesn't support that (hasn't rtsp client), I guess?

**Comment by koman-maciej** [comment]
Ok, I found simple solution. It requires to change flow of video data process in baresip - `avformat` AVPackets should be send directly to the SIP client

**Comment by beebuu** [comment]
koman-maciej, how to fix the proble?

**Comment by kemotz** [comment]
@koman-maciej , Could you please share the solution?

> Ok, I found simple solution. It requires to change flow of video data process in baresip - avformat AVPackets should be send directly to the SIP client

**Comment by pergolafabio** [comment]
hi @BlindCrow or @koman-maciej  or @beebuu 
sorry to wake an old thread, but its really interesting

I always used Asterisk, but asterisk isnt able to souce in the RTSP stream
What i have done, i did the change on client side, like with linphone/ i recompiled the app, and injected an RTSP player
it works , but then offcourse i'm limited to some softphone clients, and i need access to 554 (risk)

On server side its indeed better

Am i correct, that you can inject rtsp to an endpoint itself?
So if a door intercom is calling, i will see the rtsp stream instead? Will it work for early media AND during the call?
Will it work when you call to groups/follow me  users?

thnx for all feedback
