### ISSUE TITLE
Missing RTP packets from RTSP video source when using avformat

### ISSUE THREAD

**Issue by koman-maciej** [alfredh/baresip#163]
Hi,
I observed low quality of video stream when I'm using avformat with RTSP source. Take a look into the logs, it seems that RTP packets from RTSP source are missed and the video stream is corrupted because of that, I guess:

```
...
[rtsp @ 0xa372cc0] RTP: missed n packets
[rtsp @ 0xa3702e0] max delay reached. need to consume packet
[rtsp @ 0xa372cc0] RTP: missed n packets
[rtsp @ 0xa3702e0] max delay reached. need to consume packet
[rtsp @ 0xa372cc0] RTP: missed n packets
[rtsp @ 0xa3702e0] max delay reached. need to consume packet
...
```

When I'm using avformat with video file as a source, the problem is gone (ffmpeg hasn't problem with rtsp source also).
I investigated that problem and I saw a lot of similar issues in FFmpeg bug tracker related with many kind of reasons.

But I was digging deeper into the baresip and found that in the line [176](https://github.com/alfredh/baresip/blob/master/modules/avformat/avformat.c#L176) avformat.c (after getting video packet) 1 second delay function is invoked. I'm not a video stream engineer, so I don't know what is the cause of that delay, but for me it seemed to be too much. I reduced this value to the 100 ms and the problem was solved for me. Maybe RTP packets don't kept pace to be collected?

Regards,
Maciej

**Comment by alfredh** [comment]
thanks for the report,

the purpose of this code:

```
		ret = av_read_frame(st->ic, &pkt);
		if (ret < 0) {
			debug("avformat: rewind stream (ret=%d)\n", ret);
			sys_msleep(1000);
			av_seek_frame(st->ic, -1, 0, 0);
			continue;
		}
```

... is to rewind the input file when EOF has been reached. I guess you dont have
any EOF's for your RTSP stream.

could you please run baresip with -v (verbose debug) option and see if this code
is being run?

**Comment by koman-maciej** [comment]
Sorry, my fault.
I'm concerned about this [delay](https://github.com/alfredh/baresip/blob/master/modules/avformat/avformat.c#L190). `if (ret < 0)` condition is never reached for my rtsp stream, so it's fine

**Comment by alfredh** [comment]
aha, then I understand. You are talking about this piece of code:

```
    /* simulate framerate */
    sys_msleep(1000/st->fps);
```

this delay is intended for reading video files from local disk, and
is currently very inaccurate. For reading a stream over the network,
this simulated delay will not work.

We should solve this properly.

perhaps we can look at timestamp of each packet instead, to get
better timing.

**Comment by alfredh** [comment]
@koman-maciej could you please try latest version and see if it works better ?

**Comment by alfredh** [comment]
I would consider this issue fixed now, in the latest version.

you are welcome to re-test it both using a local source and a network source :)
reopen if it does not work.

**Comment by jimjinj** [comment]
ffmpeg -thread_queue_size 512 -r 25 -i rtsp://xxxx ..., after adding the two options, NO more missed packets, everything is OK

**Comment by naman03malhotra** [comment]
`ffmpeg  -rtsp_transport tcp -protocol_whitelist rtp,file,udp,tcp -i` add this before -i solved it for me.

**Comment by naman03malhotra** [comment]
https://stackoverflow.com/questions/38389489/how-to-save-rtsp-stream-without-packet-loss-by-using-ffmpeg - reason
