### ISSUE TITLE
message_send require full sip format

### ISSUE THREAD

**Issue by MobiSciLab** [alfredh/baresip#164]
message_send requires a full sip format: 
Ex: sip:contact_name@192.168.1.1
Meanwhile, its ok to just use "contact_name" for calling.

**Comment by MobiSciLab** [comment]
How can I find a full sip uri from contact name?

**Comment by alfredh** [comment]
it is the function `uri_complete` in `ua.c` that appends the domain if missing:

https://github.com/alfredh/baresip/blob/master/src/ua.c#L688

if you also want to use this from `message.c` we can add ua_ prefix and add
prototype to `core.h`, example:

```
int ua_uri_complete(...);
```

**Comment by MobiSciLab** [comment]
Thank you, I think message & call contacts should be in the same format
