### ISSUE TITLE
usr/bin/ld: cannot find -lrem

### ISSUE THREAD

**Issue by DheerubhaiBansal** [alfredh/baresip#167]
I am trying to compile baresip using this link https://github.com/alfredh/baresip-android/blob/master/README.md and I download latest verson of baresip,re,rem and openssl. When I am runing `make baresip` in terminal, I got  `/usr/bin/ld: cannot find -lrem` error.

**Comment by czarkoff** [comment]
Did you actually install build and install librem?

**Comment by DheerubhaiBansal** [comment]
I have just download and extract. How to install and build?

**Comment by czarkoff** [comment]
If you are using makefile from [alfredh/baresip-android](http://github.com/alfredh/baresip-android), it should take care of the process itself.  But you have to strip versions from dependency directories first:
```shell
mv -f baresip{-0.4.19,}
mv -f rem{-0.4.7,}
mv -f re{-0.4.16,}
mv -f retest{-0.4.5,}
mv -f openssl{-1.0.2h,}
mv -f opus{-1.1.3,}
mv -f speex{-1.2rc2,}
mv libzrtp{-master,}
```

**Comment by DheerubhaiBansal** [comment]
I have done same but I have got re.h no such file or directory. After that I have download latest version of all lib. Then I am getting error of lrem.

**Comment by czarkoff** [comment]
What do you mean by "recent"?  You are using release tarballs, right?  And you rename the directories, right?
