### ISSUE TITLE
Allow to set preference IPv6 or IPv4 [rfc7984]

### ISSUE THREAD

**Issue by nshopik** [alfredh/baresip#168]
Currently baresip only tries IPv6 and if its fails won't try IPv4 even if its available. Also there is no way to show your preference be it IPv6 or IPv4.

My setup was pretty simple with one SRV record which returns hostname with both A/AAA-records but only IPv6 tried.

https://tools.ietf.org/html/rfc7984 - give some update how to lookup and select DNS records in a Dual-Stack IP Network

**Comment by alfredh** [comment]
thanks for your input. Yes this is something that we should improve ..

**Comment by alfredh** [comment]
hi @nshopik 

in the setup that is failing for you, could you please provide the following info:

* output if `ifconfig` on your local machine

* DNS SRV,A,AAA records for your SIP domain, e.g.

```
$ host -t SRV _sip._tcp.domain.com
```

* full debug log from `baresip -v`

* output of `/sipstat` command


/Alfred

**Comment by nshopik** [comment]
Hi @alfredh 

It appears i have trouble reproducing it, right now. 

Quick investigation show that baresip select first DNS record as returned by DNS server w/o ordering, currently my DNS servers return IPv4 always as first result followed by IPv6 record. 

I could create separate DNS record only-ipv4 and only-ipv6 and put them with same priority in SRV record, but this is usually should be avoided.

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 44:87:fc:8d:a8:26 brd ff:ff:ff:ff:ff:ff
    inet 192.168.20.69/24 brd 192.168.20.255 scope global dynamic eth0
       valid_lft 84901sec preferred_lft 84901sec
    inet6 2002:5345:ca62:1:d918:4d4:81ab:7b5b/64 scope global temporary dynamic 
       valid_lft 603303sec preferred_lft 84303sec
    inet6 2002:5345:ca62:1:4687:fcff:fe8d:a826/64 scope global mngtmpaddr noprefixroute dynamic 
       valid_lft 2591866sec preferred_lft 604666sec
    inet6 2001:67c:2b8c:3:d918:4d4:81ab:7b5b/64 scope global temporary dynamic 
       valid_lft 603303sec preferred_lft 84303sec
    inet6 2001:67c:2b8c:3:4687:fcff:fe8d:a826/64 scope global mngtmpaddr noprefixroute dynamic 
       valid_lft 2591866sec preferred_lft 604666sec
    inet6 fe80::4687:fcff:fe8d:a826/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether 00:80:48:14:7e:99 brd ff:ff:ff:ff:ff:ff
4: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
5: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether 52:54:00:7a:b5:ed brd ff:ff:ff:ff:ff:ff
```

```
$ host -t SRV _sip._tcp.foxq.org
_sip._tcp.foxq.org has SRV record 20 5 5060 sip.foxq.org.
```

```
baresip v0.4.20 Copyright (C) 2010 - 2016 Alfred E. Heggestad et al.
Local network address:  IPv4=eth0:192.168.20.69  IPv6=eth0:2002:5345:ca62:1:d918:4d4:81ab:7b5b
ui: stdio
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
auplay: pulse
ausrc: pulse
gst: init: GStreamer 1.8.3
ausrc: gst
medianat: stun
medianat: turn
medianat: ice
mediaenc: srtp
mediaenc: srtp-mand
mediaenc: srtp-mandf
mediaenc: dtls_srtpf
mediaenc: dtls_srtp
mediaenc: srtp-mandf
DTLS-SRTP ready with profiles SRTP_AES128_CM_SHA1_80:SRTP_AES128_CM_SHA1_32
uuid: loaded UUID e54170fb-4cbb-9d85-de4d-8f1b27f4a91b from file /home/shopik/.baresip/uuid
using stunserver: 'stun:@stun.foxq.org'
899@foxq.org: Using medianat `stun'
Populated 1 account
Populated 4 contacts
Populated 2 audio codecs
Populated 1 audio filter
Populated 0 video codecs
Populated 0 video filters
baresip is ready.
899@foxq.org: {0/TCP/v4} 200 OK () [1 binding]
All 1 useragent registered successfully! (87 ms)

--- System info: ---
 Machine:  x86_64/linux
 Version:  0.4.20 (libre v0.4.13)
 Build:    64-bit little endian
 Kernel:   Linux G41T-M9 4.8.0-30-generic #32-Ubuntu SMP Fri Dec 2 03:43:27 UTC 2016 x86_64
 Uptime:   5 secs
 Started:  Tue Dec 13 14:09:38 2016
 Compiler: 5.4.0 20160609
transports:
  192.168.20.69:59796 (UDP)
  192.168.20.69:44033 (TCP)
  192.168.20.69:32919 (TLS)
  [2002:5345:ca62:1:d918:4d4:81ab:7b5b]:41008 (UDP)
  [2002:5345:ca62:1:d918:4d4:81ab:7b5b]:37375 (TCP)
  [2002:5345:ca62:1:d918:4d4:81ab:7b5b]:42357 (TLS)
client transactions:
server transactions:

--- System info: ---
 Machine:  x86_64/linux
 Version:  0.4.20 (libre v0.4.13)
 Build:    64-bit little endian
 Kernel:   Linux G41T-M9 4.8.0-30-generic #32-Ubuntu SMP Fri Dec 2 03:43:27 UTC 2016 x86_64
 Uptime:   5 secs
 Started:  Tue Dec 13 14:09:38 2016
 Compiler: 5.4.0 20160609
Timers (4):
  0x15a70c0: th=0x7fad9cb60d73 expire=250ms
  0x159e5e8: th=0x4169d3 expire=54937ms
  0x17aaf10: th=0x7fad9eda285c expire=895064ms
  0x17a4958: th=0x7fad9eda82ad expire=3266564ms
Audio-loop: 8000Hz, 1ch
pulse: opening player (8000 Hz, 1 channels, device '')
pulse: playback started
Timers (5):
  0x17aadc8: th=0x7fad97b9800d expire=69ms
  0x15a70c0: th=0x7fad9cb60d73 expire=250ms
  0x159e5e8: th=0x4169d3 expire=54906ms
  0x17aaf10: th=0x7fad9eda285c expire=895033ms
  0x17a4958: th=0x7fad9eda82ad expire=3266533ms
8000Hz 1ch  n_read=151 n_write=166 rw_ratio=0.90Quit
ua: stop all (forced=0)
menu: close (redial current_attempts=0)
pulse: stopping playback thread
Stopping 1 useragent.. 
ua: sip-stack exit
ua exited -- stopping main runloop

```

**Comment by alfredh** [comment]
I have tried to reproduce this locally, using latest libre+baresip and your server.

accounts:
`<sip:test:test@foxq.org;transport=tcp>`

the machine has both IPv4 and IPv6 address. when baresip starts it tries
both v4 and v6 entries from SRV/AAA/A:

```
### request: dst = [2a02:7aa0:1619::7cb7:32f]:5060
### request: dst = 95.215.44.62:5060
### request: dst = [2a02:7aa0:1619::7cb7:32f]:5060
### request: dst = 95.215.44.62:5060
reg: sip:test@foxq.org: 404 User unknown. ()
```

as expected it fails with 404 because my credentials are invalid. But at least
it was able to switch over to the IPv4 transport.

Looking at your DNS records:

```
$ host -t SRV _sip._tcp.foxq.org
_sip._tcp.foxq.org has SRV record 20 5 5060 sip.foxq.org.
$ host sip.foxq.org
sip.foxq.org has address 95.215.44.62
sip.foxq.org has IPv6 address 2a02:7aa0:1619::7cb7:32f
```

for your host `sip.foxq.org` which has both A and AAAA records the priority is
completely random. Any DNS server on the internet might return the answers
in any given order.

I think that if you want to configure your domain to prefer IPv6 then you need to
do this via the SRV records which has both Priority and Weight.
For example:

```
_sip._tcp.foxq.org has SRV record 10 0 5060 sip-v6.foxq.org.
_sip._tcp.foxq.org has SRV record 5 0 5060 sip-v4.foxq.org.
```

in this case baresip will always try the IPv6 transport first.


another thing, there has been some changes related to SIP-stack and IP-address
ordering between v0.4.13 and v0.5.0 .. could you please try to re-test using
latest baresip (v0.5.0) and libre (v0.5.0) ?


Thanks, hope this helps :)


/Alfred

**Comment by nshopik** [comment]
I've tried 0.5.0 release and it seems everything works as expected. Tested with more SRV records (with different ports, priority) and sorting works correctly. 

You may double check rfc7984 (its quite short) but otherwise it looks like you can add it to list of compliant rfc.

`/sipstat` is no longer exist in 0.5.0?

Since baresip now automatically select best available transport I don't think we need any preference then.

**Comment by alfredh** [comment]
the `/sipstat` command was moved to debug_cmd.so module

thank you for testing and good feedback :)

**Comment by nshopik** [comment]
Its looks like there is small problem in DNS code. 

When it resolve SRV record it usually receive A/AAAA records in additional second as well. But I've noticed that if additional section contains only AAAA record baresip won't try resolve A record, and thus expecting only IPv6 available which is false.

**Comment by alfredh** [comment]
could you please add some extra debugging in the relevant code?

then try to reproduce the bug and provide a matching PCAP file and log ?

**Comment by alfredh** [comment]
hi @nshopik 

do you still have the problem that you mentioned?

if so could you be so kind as to provide some traces and logs so I can look into it ?

**Comment by nshopik** [comment]
Hi @alfredh 

Yeah problem still there. So I retested to give better look. If DNS server doesn't had previously resolved A and/or AAAA records in its cache for SRV host in question it will return no additional section information and baresip will request both A/AAAA records.

But if you previously resolved AAAA or A only record only one in cache will be returned in additional section and baresip won't do additional lookup for other missing record and assume its only available record.

You can test this against any SRV record (you can use one in post above) with your own DNS server where you can clear cache. Lookup only AAAA record which will be pointed in SRV record and start baresip, you will notice it will only try IPv6 transport, even though A record available but it will never try to get it.

My C skills are only enough to write hello world at best, so can't help with tests in code

**Comment by alfredh** [comment]
```
alfredh@debian:~/svn/resolve$ ./resolve -t SRV _sip._tcp.foxq.org 216.87.155.33
using nameserver: 216.87.155.33
Header
  [id=0xb15f qr=1 opcode=0 aa=1 tc=0 rd=1 ra=0 z=0 rcode=0 nq=1]
Answers (1)
  _sip._tcp.foxq.org.             1800 IN   SRV      20   5 5060 sip.foxq.org.
Authority Information (2)
  foxq.org.                       1800 IN   NS      dns2.registrar-servers.com.
  foxq.org.                       1800 IN   NS      dns1.registrar-servers.com.
Additional information (2)
  sip.foxq.org.                   1799 IN   A       95.215.44.62
  sip.foxq.org.                  43200 IN   AAAA    2a02:7aa0:1619::7cb7:32f


alfredh@debian:~/svn/resolve$ ./resolve -t SRV _sip._tcp.foxq.org 8.8.8.8
using nameserver: 8.8.8.8
Header
  [id=0xf2ea qr=1 opcode=0 aa=0 tc=0 rd=1 ra=1 z=0 rcode=0 nq=1]
Answers (1)
  _sip._tcp.foxq.org.             1799 IN   SRV      20   5 5060 sip.foxq.org.
Authority Information (0)
Additional information (0)

```

if I resolve using your domain names authoritive server, it replies with
2 additional records. If I use google open DNS server, it has 0 additional records.

perhaps you can try to use another DNS server? This can be configured
in baresip config:

`dns_server    8.8.8.8:53`

I think your bug is a very rare combination of 2 things:

- Your SIP domain is advertising support for IPv6 (AAAA record) but your SIP server
is not listening on IPv6 port 5060
- Your DNS server only returns 1 out of 2 additional records, which I am not sure is 
normal

**Comment by nshopik** [comment]
Caching server may return only data already available to it in additional section.

If you query authoritative server, of course it will provide you with additional records since it know about them as they exist in same zone it serves.

Most public DNS are't returning additional record to avoid cache poisoning

**Comment by sbourji** [comment]
I set Allow IPV6 true, trying to register , but I get "address required" from add_handler which is in re/src/sip/request.c.
host -t SRV _sip._tcp.redcom.com
_sip._tcp.redcom.com has SRV record 100 30 5060 in-house-sigmacore.redcom.com.
any help
