### ISSUE TITLE
Extremely high bandwidth usage with null audio input

### ISSUE THREAD

**Issue by wolrah** [alfredh/baresip#169]
I am attempting to use a Raspberry Pi as a paging device.  It has no microphone connected and no need for one, so I configured it to use the null input with the following config line:  `audio_source            alsa,null`

If I didn't do this it would disconnect calls as soon as it tried to start sending audio, since the default `alsa,default` entry is looking for a non-existent default audio input device.

This technically works, but basically DoSes my internet connection as for whatever reason baresip decides to send "empty" audio packets at an absurd rate.  A 10 second test call generated a nearly 70MB packet capture.

accounts (sanitized): http://pastebin.com/i5p0GrgU
config: http://pastebin.com/TmxhmkpU

**Comment by alfredh** [comment]
can you try to find out where the high bitrate is coming from? for example add some debug
code in the alsa module or in `audio.c` ?

another alternative is the `aubridge` module

**Comment by alfredh** [comment]
I think this is an ALSA bug. You can try this:

```
$ arecord -D null a.wav
```

after 5 seconds the a.wav file is 2.1 Giga Bytes


the baresip alsa module is reading samples as fast as they are coming,
it is not using any timestamps or limiting the packetrate. This approach
is working very well with most audio drivers.

**Comment by wolrah** [comment]
That makes sense.

Disabling all audio drivers wouldn't work because I want it to play the audio out the speaker, I just don't need it to be inputting or sending anything.  I will try commenting out the audio_source line and see what happens.

**Comment by alfredh** [comment]
then can you please try this:

```
audio_player           alsa,default
audio_source           aubridge,dummy
```

if you have problems with NAT pinholes not opening for incoming RTP,
you can try the `rtpkeep` options.

**Comment by wolrah** [comment]
That seems to solve the problem.  Thanks.
