### ISSUE TITLE
GStreamer 1.4.5

### ISSUE THREAD

**Issue by ishmaelen** [alfredh/baresip#171]
Hello

I am trying to play a .wav file using the gst1.so module and GStreamer1.4.5. 

gst: Error: 1(Operation not permitted) message="Internal data flow error."
gst: Debug: gstwavparse.c(2186): gst_wavparse_loop (): /GstPipeline:pipeline/GstPlayBin:source/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstWavParse:wavparse0:
streaming task paused, reason not-negotiated (-4)
call: audio device error: Operation not permitted (Internal data flow error.)

I get no errors just playing the file with gst/aplay:
gst-launch-1.0 -v -m playbin uri=file:///home/dir/fc.wav 
aplay /home/vds/fc.wav -v

Here is [my config and session](http://pastebin.com/F5Mp8vYP) on pastebin.

Please let me know if I can add some more information to make the issue more clear.

**Comment by alfredh** [comment]
any gstreamer experts who can help with this one?

the module `aufile` can also be used to read WAV files.

**Comment by alfredh** [comment]
I just successfully tested `gst1.so` on Debian Testing which has Gstreamer 1.10.2

config:

```
audio_source            gst,http://relay.slayradio.org:8000/
module                  gst1.so
```

log:
```
gst: init: GStreamer 1.10.2
...
audio: Set audio decoder: opus 48000Hz 2ch
audio: Set audio encoder: opus 48000Hz 2ch
audio tx pipeline:         gst ---> opus
audio rx pipeline:        alsa <--- opus
xxx@creytiv.com: Call established: sip:aeh@creytiv.com
gst: title: Hazel - Aliens)
```

Can you please tell me which Operating System you are using ?

**Comment by ishmaelen** [comment]
Hello Alfred,

Thanks for your follow-up. This was on CentOS

You can close this issue if you want, I got it working on another machine (Debian).

PS! I tried the HTTP streaming (before it was file) and that segfaulted baresip.

# gdb baresip core.18996 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/bin/baresip...done.
[New LWP 18998]
[New LWP 18996]
[New LWP 18997]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `baresip'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f1659c4b263 in __tspi_obj_list_init () from /lib64/libtspi.so.1
Missing separate debuginfos, use: debuginfo-install alsa-lib-1.1.1-1.el7.x86_64 glib-networking-2.42.0-1.el7.x86_64 glib2-2.42.2-5.el7.x86_64 glibc-2.17-106.el7_2.8.x86_64 gmp-6.0.0-12.el7_1.x86_64 gnutls-3.3.8-14.el7_2.x86_64 gstreamer1-1.4.5-1.el7.x86_64 gstreamer1-plugins-base-1.4.5-2.el7.x86_64 gstreamer1-plugins-good-1.4.5-2.el7.x86_64 jbigkit-libs-2.0-11.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.13.2-12.el7_2.x86_64 libcom_err-1.42.9-7.el7.x86_64 libffi-3.0.13-16.el7.x86_64 libgcc-4.8.5-4.el7.x86_64 libjpeg-turbo-1.2.90-5.el7.x86_64 libmodman-2.0.1-8.el7.x86_64 libproxy-0.4.11-8.el7.x86_64 libselinux-2.2.2-6.el7.x86_64 libsoup-2.48.1-3.el7.x86_64 libstdc++-4.8.5-4.el7.x86_64 libtasn1-3.8-2.el7.x86_64 libtiff-4.0.3-25.el7_2.x86_64 libxml2-2.9.1-6.el7_2.3.x86_64 nettle-2.7.1-4.el7.x86_64 openssl-libs-1.0.1e-51.el7_2.5.x86_64 opus-1.0.2-6.el7.x86_64 orc-0.4.22-5.el7.x86_64 p11-kit-0.20.7-3.el7.x86_64 pcre-8.32-15.el7_2.1.x86_64 spandsp-0.0.6-0.10.pre21.el7.x86_64 sqlite-3.7.17-8.el7.x86_64 trousers-0.3.13-1.el7.x86_64 xz-libs-5.1.2-12alpha.el7.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) where
#0  0x00007f1659c4b263 in __tspi_obj_list_init () at /lib64/libtspi.so.1
#1  0x00007f16650533a3 in _dl_init_internal () at /lib64/ld-linux-x86-64.so.2
#2  0x00007f1665057ab6 in dl_open_worker () at /lib64/ld-linux-x86-64.so.2
#3  0x00007f16650531b4 in _dl_catch_error () at /lib64/ld-linux-x86-64.so.2
#4  0x00007f16650571ab in _dl_open () at /lib64/ld-linux-x86-64.so.2
#5  0x00007f1664bc202b in dlopen_doit () at /lib64/libdl.so.2
#6  0x00007f16650531b4 in _dl_catch_error () at /lib64/ld-linux-x86-64.so.2
#7  0x00007f1664bc262d in _dlerror_run () at /lib64/libdl.so.2
#8  0x00007f1664bc20c1 in dlopen@@GLIBC_2.2.5 () at /lib64/libdl.so.2
#9  0x00007f165f47a8c9 in g_module_open () at /lib64/libgmodule-2.0.so.0
#10 0x00007f165b7ee59b in g_io_module_load_module () at /lib64/libgio-2.0.so.0
#11 0x00007f165f9e7c91 in g_type_module_use () at /lib64/libgobject-2.0.so.0
#12 0x00007f165b7ee68b in lazy_load_modules.isra.1 () at /lib64/libgio-2.0.so.0
#13 0x00007f165b7ef24d in g_io_extension_point_get_extensions () at /lib64/libgio-2.0.so.0
#14 0x00007f165b7ef880 in _g_io_module_get_default () at /lib64/libgio-2.0.so.0
#15 0x00007f165bb7770a in soup_session_set_property () at /lib64/libsoup-2.4.so.1
#16 0x00007f165f9cb867 in g_object_set_valist () at /lib64/libgobject-2.0.so.0
#17 0x00007f165f9cc09c in g_object_set () at /lib64/libgobject-2.0.so.0
#18 0x00007f165bdda11e in gst_soup_http_src_session_open ()
    at /usr/lib64/gstreamer-1.0/libgstsouphttpsrc.so
#19 0x00007f165ccdfab8 in gst_base_src_start () at /lib64/libgstbase-1.0.so.0
#20 0x00007f165ccdfe90 in gst_base_src_activate_mode () at /lib64/libgstbase-1.0.so.0
#21 0x00007f165fc6f9df in gst_pad_activate_mode () at /lib64/libgstreamer-1.0.so.0
#22 0x00007f165fc6ffeb in gst_pad_set_active () at /lib64/libgstreamer-1.0.so.0
#23 0x00007f165fc525ab in activate_pads () at /lib64/libgstreamer-1.0.so.0
#24 0x00007f165fc6296c in gst_iterator_fold () at /lib64/libgstreamer-1.0.so.0
#25 0x00007f165fc5296a in iterator_activate_fold_with_resync.constprop.2 ()
    at /lib64/libgstreamer-1.0.so.0
#26 0x00007f165fc54530 in gst_element_pads_activate () at /lib64/libgstreamer-1.0.so.0
#27 0x00007f165fc5488a in gst_element_change_state_func () at /lib64/libgstreamer-1.0.so.0
#28 0x00007f165ccddf76 in gst_base_src_change_state () at /lib64/libgstbase-1.0.so.0
#29 0x00007f165fc56462 in gst_element_change_state () at /lib64/libgstreamer-1.0.so.0
#30 0x00007f165fc5665a in gst_element_change_state () at /lib64/libgstreamer-1.0.so.0
#31 0x00007f165fc56b3c in gst_element_set_state_func () at /lib64/libgstreamer-1.0.so.0
#32 0x00007f165fc39399 in gst_bin_change_state_func () at /lib64/libgstreamer-1.0.so.0
#33 0x00007f165d819b00 in gst_uri_decode_bin_change_state ()
    at /usr/lib64/gstreamer-1.0/libgstplayback.so
#34 0x00007f165fc56462 in gst_element_change_state () at /lib64/libgstreamer-1.0.so.0
#35 0x00007f165fc56b3c in gst_element_set_state_func () at /lib64/libgstreamer-1.0.so.0
#36 0x00007f165fc39399 in gst_bin_change_state_func () at /lib64/libgstreamer-1.0.so.0
#37 0x00007f165fc761b7 in gst_pipeline_change_state () at /lib64/libgstreamer-1.0.so.0
#38 0x00007f165d8218fc in gst_play_bin_change_state ()
    at /usr/lib64/gstreamer-1.0/libgstplayback.so
#39 0x00007f165fc56462 in gst_element_change_state () at /lib64/libgstreamer-1.0.so.0
#40 0x00007f165fc56b3c in gst_element_set_state_func () at /lib64/libgstreamer-1.0.so.0
#41 0x00007f165fc39399 in gst_bin_change_state_func () at /lib64/libgstreamer-1.0.so.0
#42 0x00007f165fc761b7 in gst_pipeline_change_state () at /lib64/libgstreamer-1.0.so.0
#43 0x00007f165fc56462 in gst_element_change_state () at /lib64/libgstreamer-1.0.so.0
#44 0x00007f165fc5665a in gst_element_change_state () at /lib64/libgstreamer-1.0.so.0
#45 0x00007f165fc56b3c in gst_element_set_state_func () at /lib64/libgstreamer-1.0.so.0
#46 0x00007f165ff11755 in thread (arg=0x100b9e0) at modules/gst1/gst.c:76
#47 0x00007f1664141dc5 in start_thread () at /lib64/libpthread.so.0
#48 0x00007f1663744ced in clone () at /lib64/libc.so.6

**Comment by alfredh** [comment]
given that gst.so and gst1.so works well on other platforms, I am guessing
that this is a bug in the gstreamer libraries specific for CentOS.

I am closing the issue for now, if someone wants to debug this further
feel free to reopen.

**Comment by nshopik** [comment]
Yeah I actually see this exact error on debian (oldstable) right now.
```
gst: Error: 1(Operation not permitted) message="Internal data flow error."
gst: Debug: gstwavparse.c(2186): gst_wavparse_loop (): /GstPipeline:pipeline/GstPlayBin:source/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstWavParse:wavparse0:
streaming task paused, reason not-negotiated (-4)                                                        
call: audio device error: Operation not permitted (Internal data flow error.)     
```

Even though I had working machine on ubuntu and decided to move to debian, could be this gst bug?
