### ISSUE TITLE
How to launch video call in windows?Is there any documents?

### ISSUE THREAD

**Issue by cnscns** [alfredh/baresip#172]

**Comment by alfredh** [comment]
it would be nice if you provided a bit more info about your usecase, such as
which Windows version you are using.

I have not tested video on Windows in a long time.

if you want to get it working, you need:

1. One or more video codecs (such as avcodec.so)
1. One video source (for example dshow.so)
1. One video display (for example sdl2.so).

Cross compiling using mingw32 is one way:
https://github.com/alfredh/baresip-win32

or you might try Visual Studio.
