### ISSUE TITLE
error while loading shared libraries: libre.so

### ISSUE THREAD

**Issue by winox** [alfredh/baresip#182]
Help me please :)
OS: Arch Linux ARM
baresip: baresip-0.4.20
re and rem: latest
> #baresip
 > baresip: error while loading shared libraries: libre.so: cannot open shared object file: No such file or directory

> #ldd /usr/local/bin/baresip
>         linux-vdso.so.1 (0x7ec1b000)
>         libre.so => not found
>         libdl.so.2 => /usr/lib/libdl.so.2 (0x76ebd000)
>         libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0x76e59000)
>         libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0x76ccd000)
>         libz.so.1 => /usr/lib/libz.so.1 (0x76caa000)
>         libpthread.so.0 => /usr/lib/libpthread.so.0 (0x76c81000)
>         librem.so => not found
>         libm.so.6 => /usr/lib/libm.so.6 (0x76c01000)
>         libc.so.6 => /usr/lib/libc.so.6 (0x76ac2000)
>         libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x76a96000)
>         /lib/ld-linux-armhf.so.3 (0x76ed2000)

> #ldconfig

no effect
Thanks!

**Comment by czarkoff** [comment]
Where are your `libre.so` and `librem.so`?

**Comment by winox** [comment]
> #cd re
> #make 
> .....
>  LD      libre.so
> AR      libre.a
> ar: `u' modifier ignored since `D' is the default (see `U')
rem problem too

**Comment by winox** [comment]
># ls /usr/local/lib
> baresip  libre.a  libre.so  librem.a  librem.so  pkgconfig

**Comment by czarkoff** [comment]
I guess your problem could be solved by rebuilding re and rem with SYSROOT=/usr flag (`make SYSROOT=/usr`), and it is a bit weird that it is not what you get by default.  Otherwise IIRC something like `ldconfig /usr/local/lib` should help.

P.S.:  И лучше по-английски, а то тут не все знают великий и могучий.

**Comment by alfredh** [comment]
assuming that libre.so and librem.so are installed in /usr/local/lib,
can you please try this:

```
LD_LIBRARY_PATH=/usr/local/lib baresip
```
