### ISSUE TITLE
while registering in baresip iam facing below mentioned error

### ISSUE THREAD

**Issue by sureshsanni** [alfredh/baresip#183]
>     R sip:6505550843@example.com
Creating UA for R sip:6505550843@example.com ...
Please enter password for 6505550843@example.com: At error case 38
ua: SIP register failed: Function not implemented

**Comment by lmangani** [comment]
@sureshsanni have you tried the standard format including the authentication?
```
R sip:user:password@example.com
```

If this fails too, could you capture the packets (ie:  ```ngrep -W byline port 5060 -d any```) while reproducing the issue and paste the obtained signaling here? (mask out any privacy sensitive parameter)

**Comment by sureshsanni** [comment]
could you please explain in detailed iam new to sip
Iam trying to register while entering password below error was getting,please find the below logs
Creating UA for R sip:6505550843@example.com ...
Please enter password for 6505550843@example.com: 
ua: SIP register failed: Function not implemented

**Comment by lmangani** [comment]
@sureshsanni please use the command as suggested, including the SIP username:password 
```
R sip:user:password@example.com
```

This might help confirm what the issue is - are you using special characters in your authentication?

**Comment by sureshsanni** [comment]
case 1: i have tried with this R sip:user:password@example.com getting below error
>  R sip:user:password@example.com
Creating UA for R sip:user:password@example.com ...
ua: SIP register failed: Function not implemented

menu: create_ua failed: Function not implemented
case 2:
i have tried with this R sip:user@example.com getting like below
baresip is ready.
>           R sip:user@example.com
Creating UA for R sip:user@example.com ...
Please enter password for user@example.com: ua: SIP register failed: Function not implemented

menu: create_ua failed: Function not implemented
main: long async blocking: 185167>100 ms (h=0x7efd15173dbd arg=0x24282a0)
user@BLTSP02702:~/Desktop/babu/baresip$ 

i need to change any thing in account file

**Comment by sureshsanni** [comment]
please find the my account file like below i need to change any thing in this file please let me know:
#
# SIP accounts - one account per line -- sample configuration
#
# Displayname <sip:user:password@domain;uri-params>;addr-params
#
#  uri-params:
#    ;transport={udp,tcp,tls}
#
#  addr-params:
#    ;answermode={manual,early,auto}
#    ;audio_codecs=speex/16000,pcma,...
#    ;auth_user=username
#    ;mediaenc={srtp,srtp-mand,srtp-mandf,dtls_srtp,zrtp}
#    ;medianat={stun,turn,ice}
#    ;outbound="sip:primary.example.com;transport=tcp"
#    ;outbound2=sip:secondary.example.com
#    ;ptime={10,20,30,40,...}
#    ;regint=3600
#    ;pubint=0 (publishing off)
#    ;regq=0.5
#    ;rtpkeep={zero,stun,dyna,rtcp}
#    ;sipnat={outbound}
#    ;stunserver=stun:[user:pass]@host[:port]
#    ;video_codecs=h264,h263,...
#
# Examples:
#
#  <sip:user:secret@domain.com;transport=tcp>
#  <sip:user:secret@1.2.3.4;transport=tcp>
#  <sip:user:secret@[2001:df8:0:16:216:6fff:fe91:614c]:5070;transport=tcp>
#


#
# A very basic example
#
<sip:user@iptel.org>


#
# Use SIP Outbound over TCP, with ICE for Media NAT Traversal, and DTLS-SRTP for encryption
#
<sip:user:pass@example.com>;sipnat=outbound;outbound="sip:example.com;transport=tcp";medianat=ice;mediaenc=dtls_srtp


#
# Use ICE for Media NAT Traversal, using a specific STUN-server
#
<sip:user:pass@example.com>;medianat=ice;stunserver="stun:username:password@stunserver.org"


#
# Force audio-codec 'opus' and video-codec 'vp8'
#
<sip:user:pass@example.com>;audio_codecs=opus/48000/2;video_codecs=vp8


# ... more examples can be added here ...

**Comment by lmangani** [comment]
I suspect you installed inconsistent versions of baresip and libre. Could you confirm how you installed?

**Comment by alfredh** [comment]
I just tested baresip@HEAD with 'R' command and it works:

Press 'R':

```
>         sip:aeh:xxx@iptel.org
Creating UA for sip:aeh:edmund@iptel.org ...
> sip:aeh@iptel.org                          zzz 

aeh@iptel.org: {0/TCP/v4} 200 OK (ser (3.3.0-pre1 (i386/linux))) [1 binding]
All 1 useragent registered successfully! (15510 ms)
```

@sureshsanni are you really using the example.com domain? if not can you please
post the exact domain you are using?

@sureshsanni which operating system are you using?

please make a clean install of latest libre, librem, baresip:

https://github.com/creytiv/re
https://github.com/creytiv/rem

**Comment by sureshsanni** [comment]
please find the below path i have followed below link procdure
http://creytiv.com/baresip.html

**Comment by sureshsanni** [comment]
iam using linux operating system 14.04LTS

**Comment by sureshsanni** [comment]
can you please share your account file (path:baresip/docs/examples) i will modify based on that.

**Comment by sureshsanni** [comment]
Hi All,
still iam facing this error. please help out me on this
user@BLTSP02702:~/Desktop/suoonchu/baresip$ ./baresip 
baresip v0.5.0 Copyright (C) 2010 - 2016 Alfred E. Heggestad et al.
Local network address:  IPv4=eth0:10.20.35.43 
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
dl: mod: /usr/local/lib/baresip/modules/alsa.so (/usr/local/lib/baresip/modules/alsa.so: cannot open shared object file: No such file or directory)
module alsa.so: No such file or directory
medianat: stun
medianat: turn
medianat: ice
Populated 0 accounts
account: No SIP accounts found
 -- check your config or add an account using 'R' command
Populated 3 contacts
Populated 2 audio codecs
Populated 1 audio filter
Populated 0 video codecs
Populated 0 video filters
baresip is ready.
> R sip:6505550171:PVZy4f8WY@example.com
Creating UA for R sip:6505550171:PVZy4f8WY@example.com ...
ua: SIP register failed: Function not implemented

menu: create_ua failed: Function not implemented

**Comment by sureshsanni** [comment]
yes iam using example.com only and operating sysytem is linux 14.04 LTS

**Comment by lmangani** [comment]
@sureshsanni please follow the guide on our wiki and make sure the latest version of RE and REM are installed before running Baresip: https://github.com/alfredh/baresip/wiki/Install:-Stable-Release

**Comment by sureshsanni** [comment]
Hi can u please tel me in acount file where i need to change with respect my details
user : 6505550171
password : PVZy43jdm

iam structed where i need to change in config file and also any other files is required to change please help on this

**Comment by lmangani** [comment]
@sureshsanni you first need to update the libraries or nothing will work!

When you launch baresip, a ```.baresip``` folder is created in your home directory, containing the configuration files. Your SIP accounts should go in file ```accounts``` as per examples

**Comment by sureshsanni** [comment]
please find the after compilation i got below files

user@BLTSP02702:~/Desktop/suoonchu/baresip$ ls
account.so   build-x86_64  docs          g711.so   Makefile  natbd.so     rpm          stdio.so   uuid.so        vumeter.so
aubridge.so  cons.so       dtls_srtp.so  httpd.so  menu.so   natpmp.so    selfview.so  stun.so    v4l2_codec.so
aufile.so    contact.so    dtmfio.so     ice.so    mk        oss.so       share        syslog.so  v4l2.so
auloop.so    debian        evdev.so      include   modules   presence.so  src          test       vidbridge.so
baresip      debug_cmd.so  fakevideo.so  l16.so    mwi.so    README.md    srtp.so      turn.so    vidloop.so
user@BLTSP02702:~/Desktop/suoonchu/baresip$

**Comment by sureshsanni** [comment]
user@BLTSP02702:/Desktop/suoonchu/baresip$ ls
account.so build-x86_64 docs g711.so Makefile natbd.so rpm stdio.so uuid.so vumeter.so
aubridge.so cons.so dtls_srtp.so httpd.so menu.so natpmp.so selfview.so stun.so v4l2_codec.so
aufile.so contact.so dtmfio.so ice.so mk oss.so share syslog.so v4l2.so
auloop.so debian evdev.so include modules presence.so src test vidbridge.so
baresip debug_cmd.so fakevideo.so l16.so mwi.so README.md srtp.so turn.so vidloop.so
user@BLTSP02702:/Desktop/suoonchu/baresip$

**Comment by sureshsanni** [comment]
please find the below configuration files where the files are created after compiled baresip:
root@BLTSP02702:/home/user/Desktop/suoonchu/baresip# cd docs/
root@BLTSP02702:/home/user/Desktop/suoonchu/baresip/docs# cd examples/
root@BLTSP02702:/home/user/Desktop/suoonchu/baresip/docs/examples# ls
accounts  config  contacts
root@BLTSP02702:/home/user/Desktop/suoonchu/baresip/docs/examples#

**Comment by lmangani** [comment]
@sureshsanni you're not following the provided advice.... at all

> When you launch baresip, a .baresip folder is created in your home directory, containing the configuration files. Your SIP accounts should go in file accounts as per examples

**Comment by sureshsanni** [comment]
it is generating .baresip folder inside that three files are generating 
1.account
2.config
3.contacts
in that files what i need to change could you please suggest me.

**Comment by lmangani** [comment]
@sureshsanni go ahead and edit ```accounts``` and add your SIP details at the bottom, using the examples as template

**Comment by alfredh** [comment]
what is the domain of your SIP provider ?

You should not use `example.com` it is a non-existing domain for testing purposes.

**Comment by sureshsanni** [comment]
Hi alfredh,

Thank you for your quick response, we have our setup clearwater IMS core which we are treting it as sip proxy server running on oracle virtual box , when i ping to the server ( clearwater bpx ) it is pinging but when i try to register it from baresip it is failing , but when i use the same setup with different ue which currenly i am using zoiper is working fine for me with example.com ,even we have tested with ip address instead of example.com its not working.(in case of baresip)

where we need to change example.com?

bare sip ue : 10.x.x.x ------->  clearwater IMS core (10.x.x.x) 

user@BLTSP02702:~/Desktop/suoonchu/baresip$ ./baresip
baresip v0.5.0 Copyright (C) 2010 - 2016 Alfred E. Heggestad et al.
Local network address: IPv4=eth0:10.20.35.43
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
dl: mod: /usr/local/lib/baresip/modules/alsa.so (/usr/local/lib/baresip/modules/alsa.so: cannot open shared object file: No such file or directory)
module alsa.so: No such file or directory
medianat: stun
medianat: turn
medianat: ice
Populated 0 accounts
account: No SIP accounts found
-- check your config or add an account using 'R' command
Populated 3 contacts
Populated 2 audio codecs
Populated 1 audio filter
Populated 0 video codecs
Populated 0 video filters
baresip is ready.

    R sip:6505550171:PVZy4f8WY@example.com
    Creating UA for R sip:6505550171:PVZy4f8WY@example.com ...
    ua: SIP register failed: Function not implemented

menu: create_ua failed: Function not implemented

**Comment by alfredh** [comment]
you need to put this line into $HOME/.baresip/accounts:

```
<sip:6505550171:PVZy4f8WY@example.com>;outbound="sip:10.x.x.x:5060"
```

**Comment by sureshsanni** [comment]
I have tried with that facing same issue only.
#
# Use SIP Outbound over TCP, with ICE for Media NAT Traversal, and DTLS-SRTP for encryption
#
<sip:6505550171:PVZy4f8WY@example.com>;outbound="sip:10.20.35.18:5060;transport=tcp";
#medianat=ice;mediaenc=dtls_srtp

LOGS:

baresip is ready.
> R sip:6505550171:PVZy4f8WY@example.com
Creating UA for R sip:6505550171:PVZy4f8WY@example.com ...
ua: SIP register failed: Function not implemented

menu: create_ua failed: Function not implemented

**Comment by sureshsanni** [comment]
please have look into this file (this is my account file) 

#
# SIP accounts - one account per line -- sample configuration
#
# Displayname <sip:user:password@domain;uri-params>;addr-params
#
#  uri-params:
#    ;transport={udp,tcp,tls}
#
#  addr-params:
#    ;answermode={manual,early,auto}
#    ;audio_codecs=speex/16000,pcma,...
#    ;auth_user=username
#    ;mediaenc={srtp,srtp-mand,srtp-mandf,dtls_srtp,zrtp}
#    ;medianat={stun,turn,ice}
#    ;outbound="sip:primary.example.com;transport=tcp"
#    ;outbound2=sip:secondary.example.com
#    ;ptime={10,20,30,40,...}
#    ;regint=3600
#    ;pubint=0 (publishing off)
#    ;regq=0.5
#    ;rtpkeep={zero,stun,dyna,rtcp}
#    ;sipnat={outbound}
#    ;stunserver=stun:[user:pass]@host[:port]
#    ;video_codecs=h264,h263,...
#
# Examples:
#
#  <sip:user:secret@domain.com;transport=tcp>
#  <sip:user:secret@1.2.3.4;transport=tcp>
#  <sip:user:secret@[2001:df8:0:16:216:6fff:fe91:614c]:5070;transport=tcp>
#


#
# A very basic example
#
#<sip:user@iptel.org>


#
# Use SIP Outbound over TCP, with ICE for Media NAT Traversal, and DTLS-SRTP for encryption
#
<sip:6505550171:PVZy4f8WY@example.com>;outbound="sip:10.x.x.x:5060;transport=tcp";


#
# Use ICE for Media NAT Traversal, using a specific STUN-server
#
#<sip:user:pass@example.com>;medianat=ice;stunserver="stun:username:password@stunserver.org"


#
# Force audio-codec 'opus' and video-codec 'vp8'
#
#<sip:user:pass@example.com>;audio_codecs=opus/48000/2;video_codecs=vp8


# ... more examples can be added here ...

    Contact GitHub API Training Shop Blog About

**Comment by alfredh** [comment]
are you sure that baresip is picking up your accounts file ?

try the following:

* copy your config files to `/tmp/baresip`
* add exactly 1 line with SIP account in `accounts`
* Run `baresip -v -f /tmp/baresip`

If this does not work, then please include here the full debug output and your exact config files.

BTW: Can you also try to run the selfself and see if that is passing:

```
make test
```

**Comment by lmangani** [comment]
There's an elephant in the room, some libraries must be desynchronized or how would this happen?
```
ua: SIP register failed: Function not implemented
```

**Comment by sureshsanni** [comment]
i have followed which you have shared all the steps

**Comment by sureshsanni** [comment]
Hi All,
while baresip registration i am facing below error

aresip is ready.
> sip:6505550171:PVZy4f8WY@example.com
Creating UA for sip:6505550171:PVZy4f8WY@example.com ...
> sip:6505550171@example.com                 zzz 

reg: sip:6505550171@example.com: Register: Connection timed out

**Comment by sureshsanni** [comment]
while baresip registration i am facing below error,registration was not success getting connection timed out error.

> sip:6505550363:DHjqdXpZQ@example.com
Creating UA for sip:6505550xxx:DHjqxxxxx@example.com ...
> sip:6505550363@example.com                 zzz 

reg: sip:6505550363@example.com: Register: Connection timed out
reg: sip:6505550363@example.com: Register: Connection timed out

**Comment by lmangani** [comment]
@sureshsanni just replace ```example.com``` with your actual domain or IP of your SIP Server

**Comment by sureshsanni** [comment]
Hi,
I have given server ip instead of example.com below error is coming

baresip is ready.
> sip:6505550363:DHjqdXpZQ@10.20.35.18
Creating UA for sip:6505550363:DHjqdXpZQ@10.20.35.18 ...
> sip:6505550363@10.20.35.18                 zzz 

reg: sip:6505550363@10.20.35.18: 404 Not Found ()

**Comment by lmangani** [comment]
Congratulations, Baresip is now working correctly! 
404 means you just need to adjust the authentication details, probably by using the real or fictional domain you configured. Please refer to your SIP Softswitch documentation, we can't help you with that as its unrelated to Baresip and impossible to guess.

**Comment by sureshsanni** [comment]
Thank you Imangani for ur support
could you please look at once in to my account file and let me know any changes i have to do 

SIP accounts - one account per line -- sample configuration
#
# Displayname <sip:user:password@domain;uri-params>;addr-params
#
#  uri-params:
#    ;transport={udp,tcp,tls}
#
#  addr-params:
#    ;answermode={manual,early,auto}
#    ;audio_codecs=speex/16000,pcma,...
#    ;auth_user=username
#    ;mediaenc={srtp,srtp-mand,srtp-mandf,dtls_srtp,zrtp}
#    ;medianat={stun,turn,ice}
#    ;outbound="sip:primary.example.com;transport=tcp"
#    ;outbound2=sip:secondary.example.com
#    ;ptime={10,20,30,40,...}
#    ;regint=3600
#    ;pubint=0 (publishing off)
#    ;regq=0.5
#    ;rtpkeep={zero,stun,dyna,rtcp}
#    ;sipnat={outbound}
#    ;stunserver=stun:[user:pass]@host[:port]
#    ;video_codecs=h264,h263,...
#
# Examples:
#
#  <sip:6505550363:DHjqdXpZq@10.20.35.18;transport=udp>
#  <sip:6505550668:ZWPASKz9M@10.20.35.18:5060>transport=tcp;answermode=auto;
#  <sip:user:secret@[2001:df8:0:16:216:6fff:fe91:614c]:5070;transport=tcp>
#


#
# A very basic example
#
#<sip:user@iptel.org>

#
# Use SIP Outbound over TCP, with ICE for Media NAT Traversal, and DTLS-SRTP for encryption
#
<sip:6505550XXX:DHjqdXpZq@10.20.X.X>;sipnat=outbound;outbound="sip:10.20.X.X:5060;transport=udp";answermode=auto;regint=900;medianat=ice;mediaenc=dtls_srtp


#
# Use ICE for Media NAT Traversal, using a specific STUN-server
#
#<sip:user:pass@example.com>;medianat=ice;stunserver="stun:username:password@stunserver.org"


#
# Force audio-codec 'opus' and video-codec 'vp8'
#
#<sip:user:pass@example.com>;audio_codecs=opus/48000/2;video_codecs=vp8


# ... more examples can be added here ...
                                                                                                                              58,1          Bot

**Comment by lmangani** [comment]
I'm sorry we cannot guess by the wrong config what the right one would be. 
The correct settings depend on your SIP server somain and user setup.

```
sip:6505550XXX:DHjqdXpZq@example.com;outbound="sip:10.20.X.X:5060;transport=udp";answermode=auto;regint=900;medianat=ice;mediaenc=dtls_srtp
```

**Comment by sureshsanni** [comment]
Hi All,

could you please help out me on below issue.
I am trying to register UA it is not getting success getting time out error, even server is pinging form my machine .
please find the below logs:

 sip:6505550363:DHjqdXpZq@example.com
Creating UA for sip:6505550363:DHjqdXpZq@example.com ...
> sip:6505550363@example.com                 zzz 

reg: sip:6505550363@example.com: Register: Connection timed out

--- Useragents: 1 ---
> sip:6505550363@example.com                 ERR 


Thanks in advance..

**Comment by alfredh** [comment]
Hey @sureshsanni 

it is quite difficult to help you because you are reporting multiple issues at the same time.

from an experienced software developer I can give you some advice:

* Get a very simple setup working first
* Only change one parameter at a time and test
* If something stops working, you know that it was caused by the last change

You already have a case where the server replies with 404, that means that you can
talk to the server. Please start with this case and try to debug it yourself.


/Alfred
