### ISSUE TITLE
Remote-Party-ID

### ISSUE THREAD

**Issue by MobiSciLab** [alfredh/baresip#184]
Does baresip support Remote-Party-ID?
How can I add a Remote-Party-ID value to the header when registering?

**Comment by alfredh** [comment]
Remote-Party-ID is not supported.

If we want to add support for this, should we rather use P-Asserted-Identity which
is defined in RFC 3325?

http://www.voip-info.org/wiki/view/P-Asserted-Identity+and+Remote-Party-ID+header

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> If we want to add support for this, should we rather use
> P-Asserted-Identity which is defined in RFC 3325?

Actually, I think for SIP User Agents, the correct header is
P-Preferred-Identity header.  For example, if one wants to make an
anonymous call, from header would be

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> Remote-Party-ID is not supported.
> 
> If we want to add support for this, should we rather use
> P-Asserted-Identity which is defined in RFC 3325?

Actually, SIP User Agents should not use either, but
P-Preferred-Identity.  For example, if one wants to make an anonymous
call, headers would look like this:

INVITE sip:test@test.tutpro.com SIP/2.0
Via: SIP/2.0/TCP 192.26.133.10:5072;rport;branch=z9hG4bKplvydmti
Max-Forwards: 70
To: <sip:test@test.tutpro.com>
From: "Anonymous" <sip:anonymous@anonymous.invalid>;tag=dxwfd
Call-ID: ofrhqndyrxigrpv@lohi.tutpro.com
CSeq: 975 INVITE
Contact: <sip:192.26.133.10:5072;transport=tcp>
Content-Type: application/sdp
Privacy: id
P-Preferred-Identity: "Juha Heinanen" <sip:jh@test.tutpro.com>
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,PRACK,REFER,NOTIFY,SUBSCRIBE,INFO,MESSAGE
Supported: replaces,norefersub,100rel
User-Agent: Twinkle/1.10.1
Content-Length: 288

When SIP proxy of the caller then forwards this, for example, to another
provider and wants to tell who the actual caller was, it would remove
replace P-P-I header with P-Asserted-Identity header.

This all is specified in some RFC, but I don't remember which.

-- Juha

**Comment by alfredh** [comment]
@MobiSciLab could you please describe your SIP environment and tell me why you
need this header.

I am happy to receive patches for adding PPI and PAI headers.

**Comment by alfredh** [comment]
I have updated the Roadmap and added the PPI RFC:

https://github.com/alfredh/baresip/wiki/Roadmap

before I start coding this I would like to have a better understanding of the
use case from @MobiSciLab . I am closing the issue for now.


/Alfred
