### ISSUE TITLE
play file on call

### ISSUE THREAD

**Issue by jungle-boogie** [alfredh/baresip#185]
Hi,

During a call, can you play a local audio file for the remote end?
I see this in help:
`/play ..                     Play audio file`

What's this mean?

**Comment by alfredh** [comment]
`play` plays a WAV file to the local audio driver, you can try it:

```
/play busy.wav
```

mixing audio files into the active call audio stream is not supported.

however you can use the module `aufile.so` to use a WAV file as an audio source.


/Alfred

**Comment by jungle-boogie** [comment]
Hi Alfred,

```
/play /home/sean/track02.wav
playing audio file "/home/sean/track02.wav" ..
play: /usr/local/share/baresip//home/sean/track02.wav: No such file or directory
debug_cmd: play_file(/home/sean/track02.wav) failed (No such file or directory)
```

```
% ls -l /home/sean/track02.wav
-rwxr-xr-x  1 sean  sean  31970780 Dec 12 15:05 /home/sean/track02.wav
```

And without specifying the full path:
```
/play track02.wav
playing audio file "track02.wav" ..
play: /usr/local/share/baresip/track02.wav: No such file or directory
debug_cmd: play_file(track02.wav) failed (No such file or directory)
```

Why's it looking in `/usr/local/share/baresip/` in both cases?

**Comment by alfredh** [comment]
this is the default location for all audio files.

you can configure it using this config item:

```
audio_path   /home/sean
```

**Comment by jungle-boogie** [comment]
Hi Alfred,

> however you can use the module aufile.so to use a WAV file as an audio source.

So while on a call, could I switch to an audio source to play the file and switch back to mic?

**Comment by alfredh** [comment]
Yes, you can try the `audev` command.

**Comment by alfredh** [comment]
hi @jungle-boogie ,

did you have a chance to try the `/audev` command ?


/Alfred

**Comment by jungle-boogie** [comment]
Hey @alfredh,

Well I don't think it can work under FreeBSD with just /dev/dsp* and oss. Alsa isn't supported under freeBSD, best I can tell. The gst module may work but that would likely pull down many dependencies.

I did load gst on linux, had it setup to play a remote and local file, this worked when the call was answered on the far end. The file will loop continuously, unless the audio source is changed.
You can switch to something like `/audev alsa.default` but you can't switch back to `gst,file:///home/alfred/song.ogg` Is that a known issue?

**Comment by alfredh** [comment]
looks like the `/audev` command is setting BOTH audio source AND audio player.

perhaps we could split the command:

```
/ausrc -- Set audio source module+device
/auplay -- Set audio player module+device
```

**Comment by jungle-boogie** [comment]
That would be neat! Would it still require alsa to play files?

**Comment by ernierasta** [comment]
Hi Alfred,
at first - thank you for amazing work you are guys doing. 

So great architecture and execution!

Sorry for hijacking this bug report, but I am trying to achieve the same thing. 

Problem is, I can not see `/audev` command if I try it in cli or press `?`. 
I have tried 0.5 release and current git code. 
Tried with default configs with only one modification - enabling `aufile.so` module - nothing helped. 
What I am missing?

Sorry for probably lame question.

**Comment by alfredh** [comment]
Hi @ernierasta and thanks for the nice feedback.

how is the C coding skills of you guys, are you able to modify the code
as suggested and submit a PR ?

I guess it is a bit confusing since `/audev` is only available in the menu
if there is an active call.

we can try the following:

* move audev to general menu
* split `audev` into `ausrc` and `auplay`
* each command will update config first, and then update the active audio device
  for all active calls (if any).

what do you think?

**Comment by alfredh** [comment]
please see the commit above:

you can use these commands to change the audio-source
or audio-player at any time. If there are any active calls
they will be updated.

example:

```
  /ausrc alsa,default
  /ausrc aufile,input.wav
  /ausrc pulse,

  /auplay alsa,default
  /auplay pulse,
```

**Comment by alfredh** [comment]
@jungle-boogie could you please test these commands and see if it solves your issue?

**Comment by r3dapple** [comment]
Just for clarification, for automatic sound file playback over the call, my setup was, on Debian 10:
sudo apt update && sudo apt install baresip
baresip (run once to create ~/.baresip)
nano ~/.baresip/config
Uncomment "module aufile.so" under Modules -> Audio driver Modules
Now run "baresip -e "/ausrc aufile,sample8kHz1Channel.wav"
-> Every call will now play the sample.wav
(for auto answering append ";answermode=auto" to your accounts config file entry)

**Comment by cspiel1** [comment]
> `play` plays a WAV file to the local audio driver, you can try it:
> 
> ```
> /play busy.wav
> ```
> 
> mixing audio files into the active call audio stream is not supported.
> 
> however you can use the module `aufile.so` to use a WAV file as an audio source.
> 
> /Alfred

We have a module mixausrc, that mixes an audiofile into the microphone stream. We use this for mixing a "location message" at the beginning of a call into the transmission RTP stream. I will make a PR.

r,chris.
