### ISSUE TITLE
coredump on quitting baresip while audio file plays

### ISSUE THREAD

**Issue by jungle-boogie** [alfredh/baresip#186]
HI Alfred,

While testing https://github.com/alfredh/baresip/issues/185, I quit baresip while it was playing busy.wav, which resulted in a coredump:

```
$ baresip
/play busy.wav
playing audio file "busy.wav" ..
oss: init: 8000 Hz 1 ch, blocksize=128
Quit
ua: stop all (forced=0)
Stopping 1 useragent..
zsh: segmentation fault (core dumped)  baresip
```

here's the backtrace. Do you need bt full, too?

```
(gdb) bt
#0  0x28cd9190 in ?? ()
#1  0x280f1a3a in mem_deref () from /usr/local/lib/libre.so
#2  0x08065eba in destructor (arg=0x28a2c100) at src/play.c:133
#3  0x280f1a3a in mem_deref () from /usr/local/lib/libre.so
#4  0x280e8d39 in list_flush () from /usr/local/lib/libre.so
#5  0x080667bc in player_destructor (data=0x28a6ea20) at src/play.c:326
#6  0x280f1a3a in mem_deref () from /usr/local/lib/libre.so
#7  0x08057036 in baresip_close () at src/baresip.c:58
#8  0x080769c8 in main (argc=1, argv=0xbfbfec00) at src/main.c:250
```

This is with baresip from master and this has happened on freebsd 11-release along with Ubtuntu/Debian system, also on baresip from master.

**Comment by alfredh** [comment]
many thanks for the bug report :)

I think what is happening here is that the module is unloaded before it's destructor
is called.

I will have a look and see if I can fix this properly.

A workaround can be to compile modules statically linked into the baresip core.

```
$ make clean
$ make STATIC=1
```

**Comment by alfredh** [comment]
@jungle-boogie I made a fix, could you please test latest version?

**Comment by jungle-boogie** [comment]
@alfredh, yes, this is much better and it doesn't coredump/segfault!
