### ISSUE TITLE
Turn on TLS 

### ISSUE THREAD

**Issue by MobiSciLab** [alfredh/baresip#191]
What is the purpose of USE_TLS in makefile? since even if I don't turn on this variable, the SIP signal is still tls with register format: <sip:account:password@domain; transport=tls>

**Comment by alfredh** [comment]
the `USE_TLS` variable is auto-detected in re.mk and is set to `yes` if OpenSSL
is detected.

if you want to build baresip with no TLS you must do:

```
$ make USE_TLS= USE_OPENSSL=
```

**Comment by alfredh** [comment]
I have updated the Wiki with this build option:

https://github.com/alfredh/baresip/wiki/Install:-GIT-Version
