### ISSUE TITLE
sndfile module unrecognized on freebsd

### ISSUE THREAD

**Issue by jungle-boogie** [alfredh/baresip#192]
Hi Alfred,

I have libsndfile installed on my freebsd system:
https://www.freshports.org/audio/libsndfile/

The header file location: `/usr/local/include/sndfile.h`

```
% ls -l /usr/local/lib/libsndfile.*
-rw-r--r--  1 root  wheel  694852 Nov  5 18:15 /usr/local/lib/libsndfile.a
lrwxr-xr-x  1 root  wheel      20 Nov  5 18:15 /usr/local/lib/libsndfile.so -> libsndfile.so.1.0.27
lrwxr-xr-x  1 root  wheel      20 Nov  5 18:15 /usr/local/lib/libsndfile.so.1 -> libsndfile.so.1.0.27
-rwxr-xr-x  1 root  wheel  495124 Nov  5 18:15 /usr/local/lib/libsndfile.so.1.0.27
```

When starting baresip, `dl: mod: /usr/local/lib/baresip/modules/sndfile.so (Cannot open "/usr/local/lib/baresip/modules/sndfile.so")
module sndfile.so: No such file or directory`

Why can't it make sndfile.so? Does this file need to be updated?
https://github.com/alfredh/baresip/blob/d64acc9d9c02c53308759f65280bbb25233dee99/modules/sndfile/sndfile.c

Thanks for any pointers!

**Comment by alfredh** [comment]
most of the modules have a simple auto detect system.

most of the modules can be forced to build, for example:

```
$ make USE_SNDFILE=1
```

to fix it properly this file needs updating (modules.mk)

```
USE_SNDFILE := $(shell [ -f $(SYSROOT)/include/sndfile.h ] || \
	[ -f $(SYSROOT_ALT)/include/sndfile.h ] && echo "yes")
```

perhave you can submit a patch for this?

**Comment by alfredh** [comment]
@jungle-boogie many thanks for your patch, it was merged to master:

https://github.com/alfredh/baresip/commit/200dc84f9e1b15076e814b3090642d1871c86f51
