### ISSUE TITLE
please implement support for SCReAM algorithm

### ISSUE THREAD

**Issue by jonassmedegaard** [alfredh/baresip#196]

**Comment by jonassmedegaard** [comment]
The SCReAM algorithm - https://github.com/EricssonResearch/scream - offers a way to efficiently compute dynamically the available bandwith for RTP streams.

Would be awesome for baresip to support optionally linking against SCReAM.

Even if over time it might turn out that the Google GCC algorithm or something else does a better job at bandwidth prediction, I imagine that work now on what seems to me the most efficient contender in the field likely aids also in hooking into alternative algorithms later.

**Comment by alfredh** [comment]
many thanks for the input regarding congestion control. For now I have added it to
the roadmap:

https://github.com/alfredh/baresip/wiki/Roadmap


adding support for CC and testing it properly is quite a large task. Even if the 3rd party
library contains a working stack, it will still have to be integrated with baresip.

personally I have no time to work on this any time soon. If someone is interested
in implementing and testing this, please let me know.



/Alfred
