### ISSUE TITLE
IPv6 address selection UI bug [cosmetic]

### ISSUE THREAD

**Issue by nshopik** [alfredh/baresip#199]
There is small issue with IPv6 address selection, though it doesn't affect connectivity it appears only apply to UI. 

Adding second IPv6 prefix will make baresip announce as new default (even though it still use correct one). According rfc6724 2002::/16 suppose to have lower precedence in that case and shouldn't be selected

`net: local IPv6 address changed: 2001:67c:2b8c:3:b065:e5e2:c73:962a -> 2002:5345:ca62:1:b065:e5e2:c73:962a`

**Comment by alfredh** [comment]
Hi @nshopik many thanks for your report.

could you please tell me which OS you are on?

can you paste here the output of `ip -6 addr` or `ifconfig`

can you please try this test program with latest version
of libre:

https://gist.github.com/alfredh/e039f5cbd8eb43e99c7d8cb5631c2a40

* put test.c in the re folder
* build it with `make test`
* run it with `./test`

I am trying to figure out how net_getifaddrs behaves on your system.
do you know if the precedence calculations are suppose to happen
in userspace programs, or is it part of the POSIX/Platform libraries?



/Alfred

**Comment by nshopik** [comment]
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 2002:5345:ca62:1:1c48:c216:275a:4427/64 scope global temporary dynamic 
       valid_lft 604402sec preferred_lft 85402sec
    inet6 2002:5345:ca62:1:4687:fcff:fe8d:a826/64 scope global mngtmpaddr noprefixroute dynamic 
       valid_lft 2591932sec preferred_lft 604732sec
    inet6 2001:67c:2b8c:3:1c48:c216:275a:4427/64 scope global temporary dynamic 
       valid_lft 604402sec preferred_lft 85402sec
    inet6 2001:67c:2b8c:3:4687:fcff:fe8d:a826/64 scope global mngtmpaddr noprefixroute dynamic 
       valid_lft 2591932sec preferred_lft 604732sec
    inet6 fe80::4687:fcff:fe8d:a826/64 scope link 
       valid_lft forever preferred_lft forever
```

```
shopik@G41T-M9:~/re-0.5.0⟫ ./test 
ifaddr:          lo  127.0.0.1
ifaddr:        eth0  192.168.20.69
ifaddr:      virbr0  192.168.122.1
ifaddr:          lo  ::1
ifaddr:        eth0  2002:5345:ca62:1:1c48:c216:275a:4427
ifaddr:        eth0  2002:5345:ca62:1:4687:fcff:fe8d:a826
ifaddr:        eth0  2001:67c:2b8c:3:1c48:c216:275a:4427
ifaddr:        eth0  2001:67c:2b8c:3:4687:fcff:fe8d:a826
ifaddr:        eth0  fe80::4687:fcff:fe8d:a826
```

Yeah I dig little more and found that source address selection is part of kernel job, so that's why it worked even though shows wrong address in UI. 

From what I've see in `./test` output it looks like you just pickup top record. So my first guess its sorting problem, but `netstats` confirms baresip actually bind to this only socket.

But I believe baresip should show all IPv6 addresses available to it. And actually bind to all available addresses or at least privacy enabled.

I'm running `Linux G41T-M9 4.8.0-34-generic #36-Ubuntu SMP Wed Dec 21 17:24:18 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by alfredh** [comment]
@nshopik thanks for helping out

I have added some code to calculate precedence:

https://gist.github.com/alfredh/e039f5cbd8eb43e99c7d8cb5631c2a40

could you please test it again on your machine (same procedure)?

on my box the output is something like this (no public IPv6 addr):

```
./test 
List of IPv6 addresses:
ifaddr:          lo0                                ::1   precedence=50
ifaddr:          lo0                            fe80::1   precedence=40
ifaddr:          en1            fe80::226:8ff:fee1:cdf3   precedence=40
```


/Alfred

**Comment by alfredh** [comment]
@palerikm you are also an IPv6 expert :) could you give us some recommendations here?

**Comment by palerikm** [comment]
How do you calculate precedence for temporary vs global? How do you detect temporary addresses in linux? (In MacOS you can check for IN6_IFF_TEMPORARY after getting flags)

Sorry more questions than answers..

**Comment by alfredh** [comment]
@nshopik could you please test this commit:

https://github.com/alfredh/baresip/commit/179c9f9e5c77251e884afb1b5efaf6ef077f47d9


I have added a policy table in net.c would be interesting to see if it works on your machine :)

**Comment by nshopik** [comment]
Here result from test you asked.
```
List of IPv6 addresses:
ifaddr:           lo                                ::1   precedence=50
ifaddr:         eth0   2002:5345:ca62:1:4016:799f:9d21:14f9   precedence=30
ifaddr:         eth0   2002:5345:ca62:1:4687:fcff:fe8d:a826   precedence=30
ifaddr:         eth0   2001:67c:2b8c:3:4016:799f:9d21:14f9   precedence=40
ifaddr:         eth0   2001:67c:2b8c:3:4687:fcff:fe8d:a826   precedence=40
ifaddr:         eth0          fe80::4687:fcff:fe8d:a826   precedence=40
```

And here result from https://github.com/alfredh/baresip/commit/179c9f9e5c77251e884afb1b5efaf6ef077f47d9 commit

```
baresip v0.5.0 Copyright (C) 2010 - 2017 Alfred E. Heggestad et al.
net: ifaddr:           lo                                ::1   precedence=50
net: precedence 50 > 0
net: ifaddr:         eth0   2002:5345:ca62:1:4016:799f:9d21:14f9   precedence=30
net: ifaddr:         eth0   2002:5345:ca62:1:4687:fcff:fe8d:a826   precedence=30
net: ifaddr:         eth0   2001:67c:2b8c:3:4016:799f:9d21:14f9   precedence=40
net: ifaddr:         eth0   2001:67c:2b8c:3:4687:fcff:fe8d:a826   precedence=40
net: ifaddr:         eth0          fe80::4687:fcff:fe8d:a826   precedence=40
pre: 40
pre: 30
Local network address:  IPv4=eth0:192.168.20.69  IPv6=eth0:::1
```

And it periodically dump into console list of ipv6 addresses just like in first test

**Comment by alfredh** [comment]
thank you, very nice with your testing. do you think the precedence values are correct?

**Comment by nshopik** [comment]
Yeah I believe it is, only issue i see here when one may have non-default policy-table. 

Is it possible to dump source address when call and/or registration made?

**Comment by alfredh** [comment]
to summarize the current issues:

* should the SIP stack bind to all available network interfaces and all
  available IPv6 addresses, or should it bind to the "default" address ?
  (there is not really such as thing as "default" address).

* the media transport for RTP also needs to bind to something,
  either 0.0.0.0 or :: (any address). Or in the case of ICE all network interfaces
  are enumerated, including multiple IPv6 addresses.

* detecting change of IP-address should trigger a SIP re-registration
  and sending Re-INVITE of all active calls. if a IPv4 interface gets added/removed
  should it trigger this. if a IPv6 interface gets added/removed should it be
  triggered? if a network interface has 3 IPv6 addresses and it gets an extra one
  should it trigged this event?

solving all these issues is quite hard I think. it would be good to check with other
SIP useragents how they do it :)

**Comment by nshopik** [comment]
* Bind to all, since there is option to force bind to specific interface, same goes for RTP
* I was mostly talking about source address selection when you already have many IPv6 addresses and need to know what source was used.
* Trigger state change when IPv6 address added/removed probably out of scope here for now to keep it simple for now

**Comment by alfredh** [comment]
hi @nshopik many thanks for your input

I am not able to implement all these features right now, mainly because I am lacking
the deep knowledge of how to do it best. I have added the topic to the Baresip roadmap:

https://github.com/alfredh/baresip/wiki/Roadmap

the whole topic requires more discussion.

for example, if you want to bind to all interfaces for the RTP stream, which IP-address
do you advertise in the SDP ? This will only work if ICE is used.
The baresip core is designed to not know anything about this and use a generic
media-nat traversal modules (such as ICE). However, baresip should still work
if no media-nat is used.
