### ISSUE TITLE
How to provision a stun/turn/ice account that includes @ 

### ISSUE THREAD

**Issue by tgueslin** [alfredh/baresip#200]
Some ICE servers provides accounts using email address or special chars in username.
How to setup a such account?

The parsing fails in such case.

**Comment by alfredh** [comment]
could you please give an example of a username that fails, and also the baresip log.

**Comment by tgueslin** [comment]
Example:
username: bob@bob.com
password: password
server: server.com

It is not possible to write the configuration with a uri syntax 
(stunserver=stun:username:password@server.com)

same type of issue with:
username: user1
password: taj:aa
...

**Comment by alfredh** [comment]
can you please try this patch:

https://gist.github.com/alfredh/ab96b75b16a3c313770d9a85836388c9

it adds support for escaped characters in username/password.

the STUN uri can be then written like this:

```
stunserver="stun:bob%40bob.com:taj%3Aaa@server.com"
```

if you think this is inconvenient, perhaps we should instead add some new
parameters `stunuser` and `stunpass` ?

**Comment by alfredh** [comment]
hi @tgueslin 

I have added 2 new parameters for configuring the STUN username and password.

example:

```
;stunuser=bob@bob.com;stunpass=taj:aa;stunserver=stun:server.com
```

could you please test latest version from GIT and check if this is working for you ?

**Comment by alfredh** [comment]
I consider this issue fixed for now. Please reopen if it is not working.
