### ISSUE TITLE
sdl2 does not convert pixel formats properly?

### ISSUE THREAD

**Issue by hargut** [alfredh/baresip#202]
Dear Alfred,

I've just tried to play around a little with nvenc/cuvid & avformat and stumbled across another issue/lack with sdl2. When using cuvid to decode the pixel format seems to be wrong. The picture looks similar to what I've seen during implementing nv12_to_rgb32.

Attached please find a screenshot of the sdl2 displayed picture when decoded with h264_cuvid.
![baresip_sdl2_cuvid](https://cloud.githubusercontent.com/assets/415705/21820195/0b382ff4-d76f-11e6-87e8-973caa25870b.png)

Setup is as follows: baresip (avformat,file & avcodec_h264enc h264_nvenc) <-> baresip (avcodec_h264dec h264_cuvid / sdl2)

**Comment by alfredh** [comment]
the `display` function in sdl2 does not check the pixel format of the
incoming frame, and the code assumes YUV420P format:

https://github.com/alfredh/baresip/blob/master/modules/sdl2/sdl.c#L88

your frame is probably NV12, hence the U and V planes (coloring) looks strange.

a solution to fix this, could be to add a mapping from NV12
to SDL_PIXELFORMAT_NV12 (if exist).


/Alfred

**Comment by hargut** [comment]
Thank you for your information it looks very reasonable.
Probably I'll have a look into the details, but since sdl2 is not one of the main areas of interest it might take longer.

**Comment by alfredh** [comment]
hi @hargut I have added support for NV12 and RGB32 in this commit:

https://github.com/alfredh/baresip/commit/055e3dff56b39b973774605b49c787c03d6a6d78

could you please test it and see if it works for you?

**Comment by hargut** [comment]
Dear Alfred,

many thanks for adding NV12 and RGB32 support to the sdl2 module. The commit works nicely and fixes 
#201 & #202.

Just for beeing a little more flexible in terms of libsdl dependency I do suggest this minor modification since BGRA32 was added in 2.0.5, and did not exist earlier. It is an alias for BGRA8888.
```
**diff --git a/modules/sdl2/sdl.c b/modules/sdl2/sdl.c
index 938039d..4291987 100644
--- a/modules/sdl2/sdl.c
+++ b/modules/sdl2/sdl.c
@@ -37,7 +37,7 @@ static uint32_t match_fmt(enum vidfmt fmt)
 
        case VID_FMT_YUV420P:   return SDL_PIXELFORMAT_IYUV;
        case VID_FMT_NV12:      return SDL_PIXELFORMAT_NV12;
-       case VID_FMT_RGB32:     return SDL_PIXELFORMAT_BGRA32;
+       case VID_FMT_RGB32:     return SDL_PIXELFORMAT_BGRA8888;
        default:                return SDL_PIXELFORMAT_UNKNOWN;
        }
 }
```
https://github.com/spurious/SDL-mirror/search?utf8=%E2%9C%93&q=SDL_PIXELFORMAT_BGRA32&type=Code

```
hargut@benchvice:~/baresip.git$ ./baresip -v -e"/vidloop h264"
baresip v0.5.0 Copyright (C) 2010 - 2017 Alfred E. Heggestad et al.
Local network address:  IPv4=enp2s0:10.0.0.11 
ui: stdio
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
avcodec: x264 build 148
avcodec: using h264 decoder by name (h264_cuvid)
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
avcodec: using h264 encoder by name (h264_nvenc)
vidsrc: avformat
vidisp: x11
vidisp: sdl2
medianat: stun
medianat: turn
medianat: ice
uuid: loaded UUID a7eaa70b-877c-6095-f8c8-27b1770f8985 from file /home/hargut/.baresip/uuid
Populated 1 account
module: loading app auloop.so
module: loading app contact.so
Populated 3 contacts
module: loading app debug_cmd.so
module: loading app menu.so
module: loading app vidloop.so
Populated 2 audio codecs
Populated 1 audio filter
Populated 3 video codecs
Populated 0 video filters
baresip is ready.
/vidloop h264
Enable video-loop on avformat,/home/hargut/dwhelper/st-pl.mp4: 1280 x 720
vidloop: avformat,/home/hargut/dwhelper/st-pl.mp4: open video source: 1280 x 720 at 50 fps
avformat: stream 0:  1280 x 720   time_base=1/90000
vidloop: open video display (sdl2.nil)
vidloop: enabled encoder H264 (50 fps, 1000000 bit/s)
vidloop: enabled decoder H264
avcodec: video encoder H264: 50 fps, 1000000 bit/s, pktsize=1480
avcodec: h264 decoder activated
x264 [warning]: frame MB size (80x45) > level limit (396)
x264 [warning]: DPB size (1 frames, 3600 mbs) > level limit (0 frames, 2376 mbs)
x264 [warning]: MB rate (180000) > level limit (6000)
[h264_cuvid @ 0x55f82c5fe2e0] Invalid pkt_timebase, passing timestamps as-is.
avcodec: video decoder H264 ()
Enabled codec: H264
vidloop: codec decode: Bad message
vidloop: codec decode: Bad message
vidloop: codec decode: Bad message
vidloop: codec decode: Bad message
Quitus: [H264] [H264]  intra=4  EFPS=16.9      1341 kbit/s       
ua: stop all (forced=0)
module: unloading app vidloop
module: unloading app menu
menu: close (redial current_attempts=0)
module: unloading app debug_cmd
module: unloading app contact
module: unloading app auloop
Stopping 1 useragent.. 
ua: sip-stack exit
ua exited -- stopping main runloop
main: unloading modules..
hargut@benchvice:~/baresip.git$
```

**Comment by alfredh** [comment]
many thanks for testing it.

I merged the branch to master and did the RGB change as suggested.

**Comment by hargut** [comment]
Is there any reason for keeping this bug open?
The colors are with the commits from yesterday fixed.

In my view this is solved.
