### ISSUE TITLE
Problem using httpd module

### ISSUE THREAD

**Issue by elektm93** [alfredh/baresip#209]
Hi,

I've issues using the httpd module. I browsed through the code, but I didn't got any hint, how to correctly use the httpd module with the long commands.

It is not a problem to call functions with a short one, e.g.
`http://0.0.0.0:8008/?b`

But is it also to use the long ones? E.g.
`http://0.0.0.0:8008/?/dial xxx`

and if, what is the delimeter to the parameter?

Regards,
Martin

**Comment by lmangani** [comment]
@elektm93 there are none, commands delimiters and their input should be automatically detected, so the dial command would look like:
` ` `
http://0.0.0.0:8008/?/d12345
 ` ` `

**Comment by elektm93** [comment]
@lmangani my issue is, that I also want to use commands, where only the long commands and no short are available. E.g. auplay or ausrc.

**Comment by elektm93** [comment]
I tried to tackle this issue made an [pull request on libre](https://github.com/creytiv/re/pull/42).

**Comment by elektm93** [comment]
I tried to tackle this issue and made a [pull request with minor changes](https://github.com/alfredh/baresip/pull/213).

**Comment by alfredh** [comment]
shall we close this one now? I believe the issue has been solved via your PR.

**Comment by elektm93** [comment]
Got solved with #213. Thanks!
