### ISSUE TITLE
Documentation or sample for using libbaresip

### ISSUE THREAD

**Issue by jamesbond3142** [alfredh/baresip#211]
Hi,
I notice that baresip can now be built as a library libbaresip.
Is there a documentation or sample of how to use this library?
Preferably, how to use libbaresip from an existing mainloop (not using re_mainloop), e.g. from within GTK or glib?

Thank you.

**Comment by alfredh** [comment]
the main api to libbaresip is in baresip.h

the main usage examples are:

- main.c show the init, setup and close sequence
- modules/menu shows the rest (how to make calls etc.)

you need to have 1 thread running for the re_main loop.
if you want to post from other threads (such as GTK) into RE-thread
you can use the mqueue for events. A working example of how to do this
is in the "gtk" module.

**Comment by jamesbond3142** [comment]
Thank you Alfred. I'll give it a try.
