### ISSUE TITLE
win32 visual studio build errors

### ISSUE THREAD

**Issue by yaroslav1988** [alfredh/baresip#212]
hi !

i can't build baresip under windows(ver 7, 10) using suggested in readme visual studio project (**baresip.sln**) under mk/win32 folder.

The problem is VS project missing some codec dependencies, which included in code:

**..\..\modules\avcodec\h264.c: No such file or directory baresip-win32** in **c1**
**libavcodec/avcodec.h: No such file or directory baresip-win32** in **h263.c**
**libavcodec/avcodec.h: No such file or directory baresip-win32** in **encode.c**
**libavcodec/avcodec.h: No such file or directory baresip-win32** in **decode.c**
**libavcodec/avcodec.h: No such file or directory baresip-win32** in **avcodec.c**

it seems that baresip-win32 requires ffmpeg headers to build properly, but there are none in src path

Are some folders missing from project ?  Or may be i do something wrong (but all i do is run solution and press **Build**) ? Or may be visual studio project which shipped with source code is out of date?

Any thoughts appreciated, thanks!

PS full specifications:
os: windows 10
visual studio 2015 ver 14 update 3
latest baresip src from this git repo
latest libre src from git repo
latest librem src from svn repo

**Comment by alfredh** [comment]
I think the VC project file is out of date.

could you please create a clean VC project file and then add all .c files under src/* ?

if it works you can continue by adding modules one at a time,
such as menu, g711 etc.

**Comment by yaroslav1988** [comment]
thanks for reply

 i succeded with building in VS after recreating project from empty one like you suggested.

PS but it wasnt that fun and fast so i cant advise to use VS as a build tool for baresip, especially on modern windows (10).

**Comment by alfredh** [comment]
would you be interested in submitting a PR for this VC project that works?

this can benefit many people so that they dont have to experience the same
problems as you did :)

**Comment by yaroslav1988** [comment]
i dont consider myself a skilful C developer, so i dont think that my results are good enough to be published as "best practice example" via pull request. But if i become more confident i will publish it surely.
