### ISSUE TITLE
v4l2_codec with C920 webcam - could not find decoder (H264)

### ISSUE THREAD

**Issue by ripleyXLR8** [alfredh/baresip#215]
Hi everybody,

First of all, thank you very much alfredh for your work on Baresip.

I'm trying to use my C920 logitech webcam with v4l2_codec but when i'm starting a call i'v got an error : 

`video: vidcodec 'H264' has no decoder
video: could not find decoder (H264)
call: video stream error: No such file or directory`

May be I'm missing a library?

Here is my starting log 👍 

`baresip v0.5.0 Copyright (C) 2010 - 2016 Alfred E. Heggestad et al.
Local network address:  IPv4=ens33:192.168.100.35  IPv6=ens33:2a01:e35:8a83:90b0:20c:29ff:feaa:3c1a
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
ausrc: alsa
auplay: alsa
v4l2_codec inited
vidcodec: H264
vidsrc: v4l2_codec
medianat: stun
medianat: turn
medianat: ice
Populated 1 account
Populated 3 contacts
Populated 2 audio codecs
Populated 1 audio filter
Populated 1 video codec
Populated 0 video filters
baresip is ready.
intercom@192.168.100.20: {0/TCP/v4} 200 OK () [1 binding]
All 1 useragent registered successfully! (1 ms)`

Best regards

Richard

**Comment by alfredh** [comment]
please note that `v4l2_codec.so` only provides a H.264 encoder

if you want an H.264 _decoder_ you must also load e.g. `avcodec.so`
but after `v4l2_codec.so`

**Comment by ripleyXLR8** [comment]
Thank you for your answer and your work on this software. The previous error is now gone when I activated the avcodec.so module but now I have another problem.

The call start, the audio is working but the video is frozen. I only see one image at the beginning of the call on the receiving side (using linphone on OSX).

Could you help me again?

[http://pastebin.com/enRPePhg](url)

**Comment by alfredh** [comment]
it looks like the H.264 encoder is working:

```
v4l2_codec: encoder stats (keyframes:3, deltaframes:632)
```

can you please try to enable this in config, to see if your encoder
is sending any packets:

```
rtp_stats               yes
```

can you also try to replace Linphone with something else
(e.g. baresip) to see if that is working ?

**Comment by ripleyXLR8** [comment]
Here is the result of the rtp_stat : http://pastebin.com/3XshQZF9 ... everything seems fine.

I'm currently installing baresip on another computer and switching my MiniSIPServer to FreePBX. Does anybody have any knowledge of the interoperability with baresip?

 I will keep you updated.

**Comment by juha-h** [comment]
Richard Perez writes:

> I'm currently installing baresip on another computer and switching my
> MiniSIPServer to FreePBX. Does anybody have any knowledge of the
> interoperability with baresip?

Baresip is by far the most standards compliant SIP UA.  If there are
interoperability issues, they are most likely due to the other parties.

-- Juha

**Comment by ripleyXLR8** [comment]
Ok so i'ts  working between 2 baresip Client!!! Cheers!
I just have one remaining problem does the BareSip-Android version support H264 video? or do you know an android client supporting H264  video?

Best regards

Richard

**Comment by alfredh** [comment]
this version of baresip for Android is without UI and without video codecs:

https://github.com/alfredh/baresip-android

but we can add cross-compilation of ffmpeg and then enable avcodec.so
you still need a GUI to see the video screen :)


/Alfred

**Comment by ripleyXLR8** [comment]
Ok I Will try to work with the baresip-android. I will keep you updated.

Just one last thing, i saw a parameter allowing to start baresip as a daemon. But how can we interact with it after?

Best regards

Richard

**Comment by alfredh** [comment]
as the original issue appears to be solved, can you please close this Issue ?

please open new Issue for non-related topics.
