### ISSUE TITLE
avformat: ‘const struct AVStream’ has no member named ‘avg_frame_rate’

### ISSUE THREAD

**Issue by alfredh** [alfredh/baresip#217]
I am getting this error when compiling on Debian 6.0:

```
modules/avformat/avformat.c: In function ‘alloc’:
modules/avformat/avformat.c:345: error: ‘const struct AVStream’ has no member named ‘avg_frame_rate’
make: *** [build-i586/modules/avformat/avformat.o] Error 1
```

versions of libavformat installed:

```
ii  libavformat-dev                    4:0.5.10-1                   development files for libavformat
ii  libavformat52                      4:0.5.10-1                   ffmpeg file format library
```

other versions of Debian:

Debian 7: OK
Debian 8: OK

**Comment by alfredh** [comment]
Hi @hargut could you please have a look at this?

**Comment by hargut** [comment]
@alfredh 
Do we really have to keep it backward compatible till Debian 6?

https://www.debian.org/releases/squeeze/
```
Squeeze had benefited from Long Term Support (LTS) until the end of February 2016. The LTS was limited to i386 and amd64. For more information, please refer to the LTS section of Debian Wiki. 
```
EOL already a year ago. I'm not really sure if we should spend time on keeping that supported.

**Comment by alfredh** [comment]
I guess this version of debian is quite old and we should not support it :)

I have removed Debian 6.0 from the list of Supported platforms:

https://github.com/alfredh/baresip/wiki/Supported-platforms

if someone really wants to keep supporting it, please contact me and
offer to help as a maintainer.
