### ISSUE TITLE
H264 video is working in the android version of "VoIP by Antisip (+Video)"

### ISSUE THREAD

**Issue by ripleyXLR8** [alfredh/baresip#219]
Dear Alfredh,

After testing a lot of Android SIP client. I found out that the Android Version of antisip works fine with Baresip for the H264 video (from v4l2_codec). May be you can add it to the interoperability list.

Best regards.

Richard

**Comment by juha-h** [comment]
Richard Perez writes:

> After testing a lot of Android SIP client. I found out that the
> Android Version of antisip works fine with Baresip for the H264 video
> (from v4l2_codec). May be you can add it to the interoperability
> list.

How about antisip dtls and zrtp?  Do they work against baresip, i.e.,
can antisip call baresip safely?

-- Juha

**Comment by alfredh** [comment]
Thank you, I added the info here:

https://github.com/alfredh/baresip/wiki/Interoperability

The Wiki is open for everyone to edit.

**Comment by ripleyXLR8** [comment]
> How about antisip dtls and zrtp?  Do they work against baresip, i.e.,
can antisip call baresip safely?

I will try tomorow.

**Comment by ripleyXLR8** [comment]
> How about antisip dtls and zrtp? Do they work against baresip, i.e.,
can antisip call baresip safely?

Nope, it did'nt work.
