### ISSUE TITLE
How to Interact with the baresip as a daemon

### ISSUE THREAD

**Issue by ripleyXLR8** [alfredh/baresip#220]
Hi, 

I haven't found any documentation about the interaction with baresip started as a daemon.
Could you give me some hints?

Best regards

Richard

**Comment by ripleyXLR8** [comment]
Ok I found two ways of interacting with the daemon, httpd.so (for interacting using your web broswer), cons.so (for interaction using telnet). Is there any other way?

**Comment by dekardkrr** [comment]
Hello.
I have a config file with params: 
audio_source            aufile,test.wav
module                  aufile.so
module                  httpd.so
When i started baresip without -d key and connect over http i dial command http://ip_adres/?d1234 
and audio file test.wav playing auto.
But when i started baserip as daemon with key -d file test.wav not playing and when i answer call is break.
What do i incorrect?
