### ISSUE TITLE
Loading gtk module fails

### ISSUE THREAD

**Issue by andreygursky** [alfredh/baresip#222]
Hi,

I'm on Debian Testing using baresip 0.5.0. I'd suppose baresip module could be loaded like ```baresip -m gtk```. But this fails. Even specifying the full path: ```baresip -m /usr/lib/baresip/modules/gtk.so``` fails:
```
Local network address:  IPv4=...
pre-loading modules: 1
dl: mod: .//usr/lib/baresip/modules/gtk.so (.//usr/lib/baresip/modules/gtk.so: cannot open shared object file: No such file or directory)
module /usr/lib/baresip/modules/gtk.so: No such file or directory
could not pre-load module '/usr/lib/baresip/modules/gtk.so' (No such file or directory)
```
After ```cd /``` the module file is found but still cannot be loaded:
```
Local network address:  IPv4=...
pre-loading modules: 1
aufilt: gtk_vumeter
gtk: message_init failed (Invalid argument)
module /usr/lib/baresip/modules/gtk.so: Invalid argument
could not pre-load module '/usr/lib/baresip/modules/gtk.so' (Invalid argument)
```

Could you please comment on these 2 issues: only relative path to the module file allowed and gtk module loading failure?

Thanks,
Andrey

**Comment by alfredh** [comment]
the GTK module has to be loaded via config-file using the `module_app` directive:

```
module_app             gtk.so
```

absolute paths are not allowed.

**Comment by andreygursky** [comment]
After uncommenting the line
```
module_app              gtk.so
```
in ```~/.baresip/config```, gtk module has been loaded successfully. Thanks!

> absolute paths are not allowed.

Is this anywhere documented? And also what modules cannot be loaded via command line at all?

**Comment by ldutra** [comment]
No one answered Andrey about it being documented…
