### ISSUE TITLE
Seg fault when restarting after a crash

### ISSUE THREAD

**Issue by ripleyXLR8** [alfredh/baresip#224]
Dear Alfred,

Sometimes after a crash or baresip when i restart it I have a segmentation fault with the following message.

> Creation of the FIFO errored. This might cause issues. (File exists)
> Erreur de segmentation (core dumped)

This is caused by the presence of the file /tmp/dtmf.out. The remove the segfault i have to manualy remove the file then everything is OK.

I can patch the dtmfio module to make it check if the file exist and then delete it if necessary. Do you agree?

Best regards

Richard

**Comment by alfredh** [comment]
can you provide a backtrace using gdb/lldb ?

in module_close, the fd should be checked before calling fclose().

perhaps we should treat "File Exists" as a non-error ?

**Comment by alfredh** [comment]
@ripleyXLR8 I added a check for fd in module_close 

could you please try latest version and see if is crashing?
