### ISSUE TITLE
Video not working after re-invites

### ISSUE THREAD

**Issue by bboelaert** [alfredh/baresip#225]
Hi,

I'm using baresip to connect pure IP camera's to SIP (= I'm using ffmpeg to grab the images from the IP camera + convert it to a v4l source /dev/video1, which is linked to baresip on startup).
When I call baresip directly from another softphone or when baresip calls another softphone, I successfully get the video stream.
But when I originate a call in Asterisk (using Originate action form Asterisk manager), with the baresip extension as caller (in this case 7011) and another softphone as the callee (in this case 9009) the video stream is not display.
However, I suspect that baresip does not handle the SIP RE-INVITES from Asterisk 
correctly. The other way around (9009 as caller and 7011/baresip as callee) it does work!
In attach you can find the wireshark trace.
Could you have a look at it?
[20170320_SIP_Wireshark_traces.zip](https://github.com/alfredh/baresip/files/858061/20170320_SIP_Wireshark_traces.zip)

Thanks in advance!

Kind regards,

Bart.

**Comment by alfredh** [comment]
could you please also include the baresip debug log (use -v for verbose) that is matching
the attached Wireshark traces ?

in the moment when Asterisk sends the re-INVITE please indicate in the baresip
log when this is happening.

**Comment by bboelaert** [comment]
Hi,

In attach you can find a new Wireshark trace + baresip debug log, into which I've but the timestamps from the trace. Hopefully this reveals something.



[20170325_SIP_trace.zip](https://github.com/alfredh/baresip/files/870222/20170325_SIP_trace.zip)

**Comment by alfredh** [comment]
many thanks Bart,

is the problem that the video-stream stops after the re-invite?
does it stop in both directions?

* could you enable RTP statistics in your `config`:

```
rtp_stats		yes
```

* after receiving the first re-invite, try to press `V` for video debug
  to see if any RTP video packets are arriving

* which SIP client are you using on the otherside? the wireshark trace
  says Antisip. As a quick test could you try to replace it with baresip
  to see if the problem is related?

* one difference I have found:

antisip: `a=fmtp:117 profile-level-id=42800c; packetization-mode=1.`
baresip: `a=fmtp:99 packetization-mode=0;profile-level-id=42800c.`

i.e. H.264 packetization modes are not compatible.
(but these are from the OPTIONS reply of antisip not sure why it is related).

**Comment by bboelaert** [comment]
Hi Alfred,

First just a little bit of background : 
- Via the Asterisk Manager Interface, I send an "Originate" action with ext. 7011 as the caller (= baresip) and ext 9009 as the callee (Zoiper).
- In response to this command Asterisk first establishes a SIP call with the caller (7011/baresip).
- When the caller answers (baresip is set to auto-answer the call), Asterisk calls up the callee for the caller
- When the callee answers both parties are connected

In this set-up the video stream does not come through on the Zoiper softphone.
But when I directly call the Zoiper extension from baresip (using the d command), the video stream IS shown.

Below is the video debug after the second re-invite (can't do it after the first one, because first and second re-INVITES follow very quickly) + when the call is answered by Zoiper (ext 9009) : 


[20170325_baresip_video_debug.log.zip](https://github.com/alfredh/baresip/files/870339/20170325_baresip_video_debug.log.zip)


Kind regards,

Bart.

**Comment by alfredh** [comment]
could you please try baresip from git@HEAD? I added some extra debugging.

please also add some debug prints in video.c to check if the sending is done:
(around line 258):

```
	while (le) {

		struct vidqent *qent = le->data;

		sent += mbuf_get_left(qent->mb);

		stream_send(vtx->video->strm, qent->marker, qent->pt,
			    qent->ts, qent->mb);

```
