### ISSUE TITLE
unable to send video stream

### ISSUE THREAD

**Issue by kmmndr** [alfredh/baresip#226]
Hi
Thank you very much for baresip, I was dreaming of such a sip client ! :-) 
But I'm having difficulties to configure video stream.
I can preview the video-loop (hitting `v` in the cli).
I can see incoming video (using x11 or sdl2).
The trace in console seems to confirm my configuration, but anyway no picture of the buddy I'm calling.
```
Set video encoder: VP8  (500000 bit/s, 25 fps)
Set video decoder: VP8 
v4l2: /dev/video0: found valid V4L2 device (640 x 480) pixfmt=YUYV
v4l2: Current input: "Camera 1"
video tx pipeline:       v4l2 ---> VP8
video rx pipeline:       sdl2 <--- VP8
```

Is it a bug ? any idea how to debug further ?

**Comment by alfredh** [comment]
can you try to enable this in config:

```
rtp_stats               yes
```

then after the call you will see if any packets sent/received.

is audio working but not video?

how is your network topology, are you behind NAT?

**Comment by kmmndr** [comment]
Sorry for the delay of my answer, and thank you very much for your help !
The problem was due to my config file and video bitrate.
```
# value too high
video_bitrate 512000

# working
video_bitrate 256
```
