### ISSUE TITLE
SRTP does not work for early media

### ISSUE THREAD

**Issue by janh** [alfredh/baresip#229]
When the remote end sends early media with SRTP during an outgoing call, audio is broken until the call is answered. Depending on the used codec, either errors are shown or noise is played (probably the encrypted audio stream). 

It seems that the media encryption session handler is only called when the call is answered (through `stream_update` in stream.c which is called by `update_media` in call.c).

**Comment by alfredh** [comment]
which SIP endpoint are you testing against ?

**Comment by janh** [comment]
I'm testing with baresip connected to Asterisk 13.14.0 with PJSIP. (Making SRTP work at all in this combination currently requires patching either Asterisk or baresip because of another issue: Asterisk expects the crypto tag to be >= 1 and baresip uses 0 by default)

I tried adding a call to `update_media` in `sipsess_progr_handler` in call.c which seems to make SRTP work for early media.

**Comment by alfredh** [comment]
could you please re-test with HEAD ?

could you also include here a tcpdump/ngrep of the INVITE+183 (incl. SDP).

**Comment by janh** [comment]
Here is a dump of an outgoing call with baresip compiled from git HEAD. Interoperability with Asterisk is now fixed, i.e. SRTP media works after the call is answered.

[srtp-early-media.zip](https://github.com/alfredh/baresip/files/908531/srtp-early-media.zip)
[srtp-early-media-output.txt](https://github.com/alfredh/baresip/files/908534/srtp-early-media-output.txt)

**Comment by alfredh** [comment]
Hi @janh 

I have made an attempt to solve your issue, could you please test the
branch above?

from https://tools.ietf.org/html/rfc4568#section-5.1.1

```
When issuing an offer, the offerer MUST be prepared to support media
   security in accordance with any of the crypto attributes included in
   the offer.  There are, however, two problems associated with this.
   First of all, the offerer does not know which key the answerer will
   be using for media sent to the offerer.  Second, the offerer may not
   be able to deduce which of the offered crypto attributes were
   accepted.  Since media may arrive prior to the answer, delay or
   clipping can occur.  If this is unacceptable to the offerer, the
   offerer SHOULD use a mechanism outside the scope of this document to
   prevent the above problem.
```

until the SDP offer/answer exchange is complete, we dont know if SRTP should
be used or not. And there is no way to find out if an incoming packet
is RTP or SRTP.

**Comment by janh** [comment]
The issue is solved with your changes.
