### ISSUE TITLE
Baresip logo competition

### ISSUE THREAD

**Issue by alfredh** [alfredh/baresip#232]
The baresip project needs a nice logo.

Requirements:

- The logo should be in some kind of Vector format, so that it can be scaled up and down
  and converted to bitmap
- The text in the logo should say "baresip" or "Baresip", but not "bareSIP".
- The logo should be clean and simple and nice to look at

You are welcome to contribute your suggestion here!

**Comment by strfry** [comment]
𝖇𝖆𝖗𝖊𝖘𝖎𝖕

**Comment by pravdinalex** [comment]
just a variant, not in vector
![baresip logo](https://cloud.githubusercontent.com/assets/2210640/25947826/b57683aa-3659-11e7-8e1e-720553319d33.png)

**Comment by alfredh** [comment]
![baresip_jpeg](https://user-images.githubusercontent.com/114750/26933465-ef1a074e-4c66-11e7-9c2f-c0f4573adc4a.jpg)

**Comment by czarkoff** [comment]
@alfredh you might want to reduce the gap between "r" and "e" a tiny bit. Otherwise this one would be hard to beat.

**Comment by lmangani** [comment]
@alfredh I think visually a lowercase ```b``` would be best mirror the final ```p```

**Comment by alfredh** [comment]
I think we need more contributions :)

**Comment by singalen** [comment]
@pravdinalex, what if you just pixel-censor the letter "I" or "P" in "SIP"? Or the lower part of "SIP"?

**Comment by czarkoff** [comment]
![baresip](https://user-images.githubusercontent.com/977491/28078521-6c2fc2ba-6665-11e7-9af2-394b07f642c3.png)

This is a bare text logo with vector font. The original SVG ([in this archive](https://github.com/alfredh/baresip/files/1139565/baresip-logo.zip)) simply contains the text "baresip" in DejaVu Sans Semi-Condensed converted to paths in order to make file self-contained. (I slightly repositioned 'r' to make the image more appealing.) I like the idea that the proposed logo for baresip is a bare text in a rather bare-bones font.

**Comment by github-ernst** [comment]
Here are a few raw ideas (outlining and scale not really finetuned).

My preference it to use different typesettings, so the words 'bare' and 'sip' are better to distinguish; therefor the function of the application is better presented by the name.


![baresip-1b](https://user-images.githubusercontent.com/13802616/28108651-9570d42a-66ec-11e7-8ee2-26072ca63939.png)


![baresip-1c](https://user-images.githubusercontent.com/13802616/28108657-9a7df2b8-66ec-11e7-8c45-d77f841ed88b.png)


![baresip-2a](https://user-images.githubusercontent.com/13802616/28108662-9fe7b0a4-66ec-11e7-98d4-030c74b3ecbf.png)


![baresip-2b](https://user-images.githubusercontent.com/13802616/28108669-a4b288ac-66ec-11e7-9e76-8fb1216bfea9.png)


![baresip-2c](https://user-images.githubusercontent.com/13802616/28108687-acc3f0e4-66ec-11e7-9f58-ad760101ad32.png)


![baresip-3a](https://user-images.githubusercontent.com/13802616/28108696-b2818c1c-66ec-11e7-9317-fd33ef8c8af4.png)


![baresip-3b](https://user-images.githubusercontent.com/13802616/28108704-b9a1a194-66ec-11e7-9e3a-853a59e7c3b9.png)


![baresip-3d](https://user-images.githubusercontent.com/13802616/28108711-c20247a8-66ec-11e7-9226-c144a9556504.png)

**Comment by jungle-boogie** [comment]
@github-ernst, I like the shadowing and border around sip in the latter two. What about making it more of a button, like on a desk phone?

**Comment by alfredh** [comment]
I think the ideas from Ernst.

would it be a good idea to also have 2 different colors for the text "bare" and "sip" ?
if the 2 colors chosen can be expressed using ANSI color codes, we can also have
a nice coloured "logo" in the terminal:


logo:

![baresip_colors](https://user-images.githubusercontent.com/114750/28225877-630813ce-68d4-11e7-852f-3c08bbd336e2.png)

terminal:

<img width="567" alt="baresip_screenshot" src="https://user-images.githubusercontent.com/114750/28225894-6d06974c-68d4-11e7-97ae-2cc07850b602.png">

**Comment by singalen** [comment]
Great idea! Maybe not so poisonously bright in graphic variant.

**Comment by github-ernst** [comment]
@jungle-boogie 

Is this sort of what you mean?

![baresip-4e](https://user-images.githubusercontent.com/13802616/28237619-c2e702c2-6943-11e7-84a6-364ccf1ca769.png)

**Comment by jungle-boogie** [comment]
@github-ernst,

Those are nice! I prefer the first one as it seems to fit better.

**Comment by github-ernst** [comment]
Here are a few other logo's for inspiration.

![baresip-5e](https://user-images.githubusercontent.com/13802616/28268114-446b988e-6afd-11e7-8b0f-db9becb9b0e8.png)
![baresip-6](https://user-images.githubusercontent.com/13802616/28268131-55c59a6c-6afd-11e7-8f15-cd9c7cb45aea.png)
![baresip-6a](https://user-images.githubusercontent.com/13802616/28268224-b181e856-6afd-11e7-9ebd-3b984773c265.png)
![baresip-6b](https://user-images.githubusercontent.com/13802616/28268835-0f0bc44a-6b00-11e7-9572-81c548128379.png)

**Comment by github-ernst** [comment]
Few extra's:

![baresip-9c](https://user-images.githubusercontent.com/13802616/28276092-316bc380-6b16-11e7-8ead-d2accf5ab8e2.png)

![baresip-9b](https://user-images.githubusercontent.com/13802616/28276109-3edbfe86-6b16-11e7-8b37-dc8223b4b7fe.png)

![baresip-9](https://user-images.githubusercontent.com/13802616/28276125-44a875ec-6b16-11e7-8e31-4c7798e865fb.png)

![baresip-9a](https://user-images.githubusercontent.com/13802616/28276131-49ce32a0-6b16-11e7-8837-87e019eb3469.png)

**Comment by jungle-boogie** [comment]
Nice work, @github-ernst!

nice, but not crazy about the gray/white:
https://user-images.githubusercontent.com/13802616/28268224-b181e856-6afd-11e7-9ebd-3b984773c265.png

**Comment by github-ernst** [comment]
Thanks @jungle-boogie.

The first batch logo's for today are sort of a retro console style design. Not every logo has been overthough before uploading and it shouldn't be (that is not how creativity works). :) 

All the designs are done based on my creative mood for today and it is work in process. Over a period of time we will have a look what we like the most. Maybe (hopefully) one of the logo's will just be a source for inspiration to someone else's design. :)

Which logo do you like the most so far?

**Comment by jungle-boogie** [comment]
Yeah, I like the retro design!

I would say these are the ones I like:
https://user-images.githubusercontent.com/13802616/28237619-c2e702c2-6943-11e7-84a6-364ccf1ca769.png

https://user-images.githubusercontent.com/13802616/28268114-446b988e-6afd-11e7-8b0f-db9becb9b0e8.png

https://user-images.githubusercontent.com/13802616/28268835-0f0bc44a-6b00-11e7-9572-81c548128379.png

What about you, @alfredh?

**Comment by alfredh** [comment]
many thanks for all the great contributions.

I would like to conclude this work soon, and I think we should go for
one of the suggestions from @github-ernst 

would you like to create a new version in SVG format
so I can do some testing with it ?

(clarification; I think it looks best if the logo only has 2 colors
with a clean logo and a professional look.)

/Alfred

**Comment by github-ernst** [comment]
@alfredh: From which logo would you like to have the SVG format?
BTW, if you would like to have some kind of logo showed in the console, you might consider a logo converted to ascii.

[baresip-logo-console_a.txt](https://github.com/alfredh/baresip/files/1172931/baresip-logo-console_a.txt)

[baresip-logo-console_c.txt](https://github.com/alfredh/baresip/files/1172932/baresip-logo-console_c.txt)

[baresip-logo-console_d.txt](https://github.com/alfredh/baresip/files/1172946/baresip-logo-console_d.txt)

[baresip-logo-console_e.txt](https://github.com/alfredh/baresip/files/1172947/baresip-logo-console_e.txt)

[baresip-logo-console_f.txt](https://github.com/alfredh/baresip/files/1172948/baresip-logo-console_f.txt)

[baresip-logo-console_g.txt](https://github.com/alfredh/baresip/files/1172951/baresip-logo-console_g.txt)

The following [logo](https://user-images.githubusercontent.com/13802616/28276131-49ce32a0-6b16-11e7-8837-87e019eb3469.png) converted to ansii doesn't come out very well, but just for showing the idea:
[baresip-logo-console_h.txt](https://github.com/alfredh/baresip/files/1172952/baresip-logo-console_h.txt)

**Tool for converting jpeg to ansii:**

`jp2a --color --width=60 --background=light console-logo.jpeg --output=filenameyouwant.txt`

**Tool for ansii art:**

`toilet baresip -f script > filenameyouwant.txt`

`figlet "baresip" > filenameyouwant.txt`

**Online tool:**
http://patorjk.com/software/taag/#p=display&f=Doh&t=baresip%0A%0A
http://patorjk.com/software/taag/#p=display&f=Blocks&t=baresip%0A%0A
http://patorjk.com/software/taag/#p=display&f=Keyboard&t=baresip%0A%0A
http://patorjk.com/software/taag/#p=display&f=Larry%203D&t=baresip%0A%0A
http://patorjk.com/software/taag/#p=display&f=Rammstein&t=baresip%0A%0A
http://patorjk.com/software/taag/#p=display&f=Stick%20Letters&t=baresip%0A%0A
Etc...

What do you think about a specific logo in ansii format, for the console?

**Comment by alfredh** [comment]
I am thinking about something like this, where one of the words is inverted:

<img width="445" alt="baresip-2colors" src="https://user-images.githubusercontent.com/114750/28584158-fce686f2-716b-11e7-84e6-951f07c63379.png">

**Comment by alfredh** [comment]
Here is the winner of the competition:

![logo](https://user-images.githubusercontent.com/114750/31136837-95e02b0e-a869-11e7-9e7f-12aeea87ffa8.png)

thanks to E.J.C. Lindner for designing the logo.

thanks to input from the Baresip community.


/Alfred

**Comment by gogonowski** [comment]
Does anyone have a vector version of the winning baresip logo?
SVG anyone?
Thanks.
/greg.
