### ISSUE TITLE
Opus stereo not actually arriving in stereo

### ISSUE THREAD

**Issue by tonylangley** [alfredh/baresip#234]
Hi,

I'm very impressed with how lightweight your baresip code is! Thank you for creating this :)

I'm trying to use the Opus codec in stereo and assume that this should work 'out of the box'. What seems to happen at some stage during encoding or decoding is that the stereo is down-mixed to mono. I can test this by unplugging the left input jack and back in, repeating for the right. The audio on the receiving end continues in both speakers, but at a lower volume when either the left or right input jack is unplugged. This happens regardless of which end sends the stereo audio and regardless of whether I use JACK or CoreAudio.

Here's what I see in the console:

Using JACK  (sending stereo audio from user2 to user1):
```
sip:user1@sip.org: Answering incoming call
answering call from sip:user2@sip.org with 200
call: update media
audio: Set audio decoder: opus 48000Hz 2ch
jack: play 48000Hz,2ch
jack: engine sample rate: 48000 max_frames=512
jack: sampc=1024
audio: Set audio encoder: opus 48000Hz 2ch
opus: encoder fmtp (stereo=1;sprop-stereo=1;maxaveragebitrate=28000;cbr=0;useinbandfec=1;usedtx=0)
jack: unique name `baresip-01' assigned
jack: engine sample rate: 48000 max_frames=512
jack: source sampc=1024
audio tx pipeline:        jack ---> opus
audio rx pipeline:        jack <--- opus
opus: encoder fmtp (stereo=1;sprop-stereo=1;maxaveragebitrate=28000;cbr=0;useinbandfec=1;usedtx=0)
user1@sip.org: Call established: sip:user2@sip.org
```

Using CoreAudio (sending stereo audio from user1 to user2):
```
sip:user1@sip.org: Answering incoming call
answering call from sip:user2@sip.org with 200
call: update media
audio: Set audio decoder: opus 48000Hz 2ch
audio: Set audio encoder: opus 48000Hz 2ch
opus: encoder fmtp (stereo=1;sprop-stereo=1;maxaveragebitrate=28000;cbr=0;useinbandfec=1;usedtx=0)
audio tx pipeline:   coreaudio ---> opus
audio rx pipeline:   coreaudio <--- opus
opus: encoder fmtp (stereo=1;sprop-stereo=1;maxaveragebitrate=28000;cbr=0;useinbandfec=1;usedtx=0)
user1@sip.org: Call established: sip:user2@sip.org
```

Hope you can help!

Thanks,
Tony

**Comment by sreimers** [comment]
Hi Tony,

try to set a higher opus bitrate in the config file. 

```
# Opus codec parameters
opus_bitrate            64000
```
At lower bitrates the opus codec is mixing the channels.

**Comment by sreimers** [comment]
See: https://wiki.xiph.org/Opus_Recommended_Settings

**Comment by tonylangley** [comment]
@sreimers - thanks for that! Seems to have resolved the issue. Wasn't obvious at all!
