### ISSUE TITLE
Trying to eliminate dropouts using Opus codec

### ISSUE THREAD

**Issue by tonylangley** [alfredh/baresip#237]
Hi again 😀

I've been furthering my experiments with baresip and trying various configurations, customising code using various hardware (MacBook Pros, BeagleBoards, BeagleBones) and have resulted in the following observations:

When establishing a direct LAN connection between e.g. MacBook Pros as follows:

In ~/.baresip/accounts:
`<sip:user1:user1@192.168.0.27>;regint=0`

In ~/.baresip/config:
`sip_listen		192.168.0.27:5060`

Apart from a glitch or two when starting up (on every occasion), I get zero dropouts 😊

However, as soon as I traverse the internet, I can't find any configuration or customisation of the Opus encode.c file that won't result in dropouts 😕

Using the following Opus configuration:
```
# Opus codec parameters
opus_bitrate		64000 # 6000-510000
opus_inbandfec	yes
opus_cbr			no
opus_dtx			no
```

I am willing to trade latency to eliminate dropouts, but despite using very large jitter buffer delay values (e.g. 1000-1005) I still get the same dropout behaviour. My experience is that increasing the value of the jitter buffer delay only slightly improves things, but doesn't completely eliminate the dropouts.

I have tried adding the OPUS_SET_PACKET_LOSS_PERC to the opus_encoder_ctl in the Opus encode.c file with various values (currently set at 10%). This appears/sounds like it has zero effect.

Sample RTP Stats:

```
audio           Transmit:     Receive:
packets:          14478        13745
avg. bitrate:      64.0         56.0  (kbit/s)
errors:               0            0
pkt.report:       14259        13527
lost:               744          717
jitter:             1.0          1.0  (ms)
```

I've read the following on https://hydrogenaud.io/index.php/topic,108570.0.html with interest:

> As you indicate, the problems you report (drops and edits) may be caused by the decoder not having a packet available when it needs it.  That packet was either lost, hasn't arrived yet, or there is a bug in the jitter buffer that stores packets and feeds them to the decoder.  
> 
> There is also a possibility that the audio player isn't able to provide audio data in time when the OS needs it.  In this case your decoder/playout application may need a larger audio buffer towards to OS.  And check that your CPU load on both sender and receiver side is no more than ~50%, for the core that runs the process.  These problems could cause what you call drops, but not edits.
> 
> For the best possible streaming, I'd recommend to:
> - Use TCP, and make sure retransmission is enabled.  Sometimes VoIP applications use TCP without retransmission just to deal with certain firewalls, but this doesn't help in the your case.
> - To benefit from TCP's retransmission you'll need a large buffer size in the receiver.  The reason is that it takes time to figure out a packet was lost, request a new one, send it over, etc. Use a buffer size of at least 10x a typical roundtrip time.  (Or just use a buffer of 10 seconds or so, if your application is ok with this kind of delay.)
> - Make sure that your jitter buffer can handle packet reordering (some don't).  Packets get naturally delivered out of order once in a while, and any TCP retransmission would also reorder packets.
> - With TCP and a long enough buffer you should be able to avoid all lost packets.  So you might as well combine as many audio frames as possible in a packet (high packet groups size).

Given the issues I'm having and the advice in the quote above, do you have any suggestions as to how I can achieve reduced/eliminated dropouts?

**Comment by alfredh** [comment]
your network has around 5.2% packet loss which I think is very high.

can you try to reduce the opus_bitrate to a low value such as 24000 (bits/s)

on the other hand, the RTP jitter buffer in baresip is not very good, and it
needs some improvements to handle high packet loss


/Alfred

**Comment by alfredh** [comment]
hey @tonylangley any updates from you?

do you think we should try to solve it in baresip?

**Comment by tonylangley** [comment]
Hi @alfredh

Thanks for reviewing this issue again.

I've not focused on using baresip for the time being (because of the issues I raised).

I know that the drop-outs are high (likely from using a VPN), but I gather that it's still not so high that it's unworkable. My belief is that if an effective jitter buffer is implemented that works in unison with the codec's OPUS_SET_PACKET_LOSS_PERC then this would be viable. Whilst I can probably reduce packet loss, it's unlikely I can completely eliminate it.

So I do think that baresip should help solve this with improvements to the implementation.

Do you agree?

**Comment by alfredh** [comment]
thanks for your comments,

this will be quite a lot of work for me to implement and test this properly,
I am afraid I do not have the time for that at the moment.

you are welcome to modify the code and test it, please send a patch/PR if you
get it working.

I will close the ticket for now, feel free to reopen it if you get something working.


/Alfred
