### ISSUE TITLE
alsa: could not open auplay device 'default' (Device or resource busy)

### ISSUE THREAD

**Issue by C-Volume** [alfredh/baresip#249]
Hi 
I hava a problem 
When someone accept my calling
It retrun this :
**alsa: could not open auplay device 'default' (Device or resource busy)
audio: start_player failed (alsa.default): Unknown error -16**

But when I accept someone's calling
It will not be wrong

why?
thanks

**Comment by GGGO** [comment]
Just to clarify, when you accept the incoming call, does the audio work in both direction ?

**Comment by alfredh** [comment]
could you please share with us the following information:

- Which platform you are using
- Which baresip version
- The baresip config files
- The baresip debug output

some ALSA drivers support only 1 client, and other drivers support
multiple clients (using software mixing).


/Alfred

**Comment by alfredh** [comment]
please re-open if you want to provide more info

**Comment by anug7** [comment]
I am also facing the same issue. I have attached the config files for baresip, alsa and the output of "aplay -l". I am using linux running on armv5te..
<-------------------------------------->

> $aplay -L null
    Discard all samples (playback) or generate zero samples (capture)
default:CARD=W55FA92SPU
    W55FA92_SPU, 
    Default Audio Device
<---------------------------------------->
config files:
[config.zip](https://github.com/alfredh/baresip/files/1128747/config.zip)

**Comment by llunohodl** [comment]
I solve same problem on my Nano PI NEO Core by using ALSA dmx 
```
$ sudo nano /etc/asound.conf
```
replace content to
```
pcm.dmixer {
    type dmix
    ipc_key 1024
    slave {
        pcm "hw:2,0"
        period_time 0
        period_size 1024
        buffer_size 8192
        rate 44100
    }

    bindings {
        0 0
        1 1
    }
}

pcm.asymed {
        type asym
        playback.pcm "dmixer"
        capture.pcm "hw:2,0"
}

pcm.dsp0 {
    type plug
    slave.pcm "asymed"
}

pcm.!default {
    type plug
    slave.pcm "asymed"
}

pcm.default {
   type plug
   slave.pcm "asymed"
}

ctl.mixer0 {
    type hw
    card 2
}
```
it is my configuration for sound card 2, number of card may be found like this:
```
$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Dummy [Dummy], device 0: Dummy PCM [Dummy PCM]
...
card 1: Loopback [Loopback], device 0: Loopback PCM [Loopback PCM]
...
card 1: Loopback [Loopback], device 1: Loopback PCM [Loopback PCM]
...
card 2: Codec [H3 Audio Codec], device 0: CDC PCM Codec-0 []
...
card 3: allwinnerhdmi [allwinner,hdmi], device 0: 1c22800.i2s-i2s-hifi i2s-hifi-0 []
...
```
replace `card 2` and `"hw:2,0"` in `asound.conf` for use it with another card
i.e. for card 3 - set  `card 3` and `"hw:3,0"`

**Comment by llunohodl** [comment]
Also this `/etc/asound.conf` may work:
```
pcm.speakers {
    type dmix
    ipc_key 1024
    slave {
        pcm "hw:2,0"
	rate 48000
    }

    bindings {
        0 0
        1 1
     }
}

pcm.microphones {
    type dsnoop
    ipc_key 1024
    slave {
        pcm "hw:2,0"
        rate 48000
    }

    bindings {
        0 0
        1 1
     }
}


 pcm.!default {
         type asym
         playback.pcm {
                 type plug
                 slave {
                   pcm "speakers"
                 }
         }
 
         capture.pcm {
                type plug
                slave {
                   pcm "microphones"
                }
         }
 }
```
