### ISSUE TITLE
Does Baresip support video conference?

### ISSUE THREAD

**Issue by MobiSciLab** [alfredh/baresip#250]
We are using FreeSwitch/Kamailio and Baresip on our project. The audio/video calls are ok on mobile devices now. However, we need to support video conference. Can we implement it using Baresip?

**Comment by alfredh** [comment]
calling into a server-side Video conference is supported by Baresip.

Hosting a video conference inside Baresip is not supported.

**Comment by MobiSciLab** [comment]
Thank you.
