### ISSUE TITLE
User-Agent header

### ISSUE THREAD

**Issue by smokersonly** [alfredh/baresip#251]
Hi, I would like to change the User-Agent header in the sip request (REGISTER, INVITE, etc)
This because my service provider needs a specific value :(

Now it is something like:
User-Agent: baresip v0.4.20 (x86 64/linux)
Would like to change to:
User-Agent: xyz

Is it possible in the current version to do this through configuration?
If not, could you point to the specifics in the code (I have very basic knowledge of cplusplus)

David

**Comment by GGGO** [comment]
In the current version, it's not possible through configuration file.

But if you want to, see src/main.c and look for `err = ua_init("baresip v" BARESIP_VERSION " (" ARCH "/" OS ")",` you can change the User-agent here.

In your case: `err = ua_init("xyz", true, true, true, prefer_ipv6);`

**Comment by smokersonly** [comment]
Thanks! That worked perfectly.
