### ISSUE TITLE
specify different user for digest authentification

### ISSUE THREAD

**Issue by smokersonly** [alfredh/baresip#253]
Hello,

When baresip sends a REGISTER it uses the username specified in the .baresip/accounts file.<sip:username:password@example.com>

It will use this username to populate the From URI and Authorization Digest username.
I would need to specify a different username in the Authorization header.

Is this possible in the current version of baresip?
If not, maybe you could point me to some place in the code where this Authorization header is populated?

Thanks in advance!

David

**Comment by GGGO** [comment]
Did you try the auth_user parameter ?

Like this: `<sip:user:secret@domain.com;transport=udp>;auth_user=username`

This is documentes in the default accounts file, or see it in docs/examples/accounts

**Comment by smokersonly** [comment]
Sorry, I overlooked it :(
