### ISSUE TITLE
Support multiple ice servers or change ice server ip address at runtime

### ISSUE THREAD

**Issue by MobiSciLab** [alfredh/baresip#254]
From previous questions, I see that Baresip has not supported multiple ice servers. Is there any plan to support this? Besides, may I update the ice server ip address at runtime?

**Comment by alfredh** [comment]
Baresip supports only 1 ICE server (STUN or TURN Server). This is a limitation
from libre's ICE stack.

the plan is to merge two ICE-stacks from libre and librew (trice):

https://github.com/creytiv/re/wiki/ICE-Stacks-merge

one of the items here is to move candidate gathering away from the library
and up to the application. This would enable baresip's ice module to add
support for multiple ICE servers.


/Alfred

**Comment by MobiSciLab** [comment]
Ok, thank you
