### ISSUE TITLE
Fault address when hanging up on some devices

### ISSUE THREAD

**Issue by MobiSciLab** [alfredh/baresip#261]
I got crashes on some devices (fault address) when hanging up. However, if I delay mem_deref(call); (baresip/src/ua.c/ua_hangup) about 1 or 2 seconds, it works well. Therefore, I think this function is called before the incoming/outgoing streams finished. Please help check this.

**Comment by alfredh** [comment]
on which platform are you running this?

can you please provide a backtrace for the crash ?


/Alfred

**Comment by MobiSciLab** [comment]
The crash happens on some Android devices, for instance: Motorola Moto G
Below is the backtrace:

Crash dump is completed

********** Crash dump: **********
Build fingerprint: 'motorola/thea_retasia_ds/thea_ds:6.0/MPBS24.65-34-5/8:user/release-keys'
pid: 16931, tid: 17128, name: DaemonBaresipTh  >>> net.edge_works.androidbaresip <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x41a80008
Stack frame #00 pc 0020fa84  /data/app/net.edge_works.androidbaresip-1/lib/arm/libbaresipwrapper.so (mbuf_write_mem+60)

**Comment by MobiSciLab** [comment]
For more information, it just happens on the device which calls api: ua_hangup

**Comment by alfredh** [comment]
there is not much information in your backtrace.

can you try to get a better backtrace and use some android tools to
symbolize it, such as:

https://developer.android.com/ndk/guides/ndk-stack.html

please also include the baresip log that is matching the crash.

you can also try to add debug logging around the crashed functions,
to try to nail it down, for example:

```
info("marker %s:%u\n", __FILE__, __LINE__);
mem_deref(call);
info("marker %s:%u\n", __FILE__, __LINE__);
```

then insert lines in the call destructor for every line to see how far the program got.
continue until you have found the function that is crashing.


/Alfred

**Comment by MobiSciLab** [comment]
@alfredh , the backtrace is from ndk-stack. Your method of debugging is my favorite too. There is no line of code which causes the crash immediately. However, the mem_deref(call); method will lead to the crash after 1 or 2 seconds (when I removed the method, there is no crash although the streams wouldn't stop).

**Comment by alfredh** [comment]
is this stock baresip running on Android, or have you made custom modifications/modules
that you are using ?

if you are able to compile the same code on e.g. linux you can run it with valgrind
and check for warnings like accessing data which has been freed.

you can also try the elimination method; disable modules one by one and see if the
crash disappears.

given that your backtrace is correct, grep all the code for `mbuf_write_xxx` and then
determine the likelyhood that there is a crash there.

I am running stock baresip on my Android device/emulator and it does not crash.


/Alfred

**Comment by MobiSciLab** [comment]
@alfredh , the crash just happens with video call on a few devices. I made a customized module of video source and video display. I also closed all streams before calling hangup.
Let see if I can find a linux machine and try valgrind.

**Comment by alfredh** [comment]
most likely the bug is in your own code.

Please note that this is an Issue tracker for the Baresip project, and does not include
external code that is not part of the stock source code.

I cannot help you more on this, you need to be patient and sit down and debug your
own code.

**Comment by sbourji** [comment]
this indue is happening to me 2, on iOS device. Place call from iPhone as the other end accept the call you hangup on the call from iPhone, that will cause the crash. There is a race condition 
my backtrace
hangup is free memory of the call, will the other trie still trying to setup the stream, I can always reproduce this issue, it's timing between 2 threads.
