### ISSUE TITLE
Issue with autoanswer, registration interval 

### ISSUE THREAD

**Issue by AshwiniAJ** [alfredh/baresip#263]
Hi,
I am not able to get autoanswer working. The setting used was
sip:5001:xxx@10.90.x.x;autoanswer={auto}
sip:5002:xxx@10.90.x.x>

When i dial from 5002 to 5001, the call should be accepted automatically right? but it does not work.
I am trying command line with baresip on linux machine and Asterisk as VoIP server

Even the registration interval did not create any difference. Even with default setting of 3600, the response of registration status in case of a failure is prompted immediately.

**Comment by jungle-boogie** [comment]
Use something like https://github.com/irontec/sngrep on both asterisk and your baresip side to see what traffic is received/sent.

**Comment by GGGO** [comment]
Could you post your account file ?

Note that the right syntax is answermode=auto and not autoanswer={auto}

**Comment by alfredh** [comment]
Hi @AshwiniAJ 

the correct syntax is:

```
<sip:5001:xxx@10.90.x.x>;answermode=auto
```

/Alfred
