### ISSUE TITLE
Echo cancellation doesn't work - "your application is buggy and/or got xruns"

### ISSUE THREAD

**Issue by maci3k90** [alfredh/baresip#269]
Hello.

Enabling echo cancellation with speex_aec.so seems doesn't work. It also generates warning during call:

`warning: No playback frame available (your application is buggy and/or got xruns)
warning: No playback frame available (your application is buggy and/or got xruns)
warning: No playback frame available (your application is buggy and/or got xruns)
warning: No playback frame available (your application is buggy and/or got xruns)
warning: No playback frame available (your application is buggy and/or got xruns)                ]
warning: Auto-filling the buffer (your application is buggy and/or got xruns)
warning: Had to discard a playback frame (your application is buggy and/or got xruns)
warning: Had to discard a playback frame (your application is buggy and/or got xruns)
warning: Had to discard a playback frame (your application is buggy and/or got xruns)
warning: Had to discard a playback frame (your application is buggy and/or got xruns)            ]
warning: Had to discard a playback frame (your application is buggy and/or got xruns)
warning: Had to discard a playback frame (your application is buggy and/or got xruns)
warning: No playback frame available (your application is buggy and/or got xruns)                ]
warning: No playback frame available (your application is buggy and/or got xruns)
warning: No playback frame available (your application is buggy and/or got xruns)
warning: No playback frame available (your application is buggy and/or got xruns)
`

Any tips for that?

My baresip version is 0.5.0 and my config:

`# baresip configuration
#

#------------------------------------------------------------------------------

# Core
poll_method             epoll           # poll, select, epoll ..

# SIP
sip_trans_bsize         128
#sip_listen             0.0.0.0:5060
#sip_certificate        cert.pem

# Call
call_local_timeout      120
call_max_calls  4

# Audio
#audio_path             /usr/local/share/baresip
audio_player            alsa,default
audio_source            alsa,default
audio_alert             alsa,default
audio_srate             8000-48000
audio_channels          1-2
#ausrc_srate            48000
#auplay_srate           48000
#ausrc_channels         1
#auplay_channels        1

# Video
video_source            v4l2,/dev/video0
#video_display          x11,nil
video_size              320x240
video_bitrate           50000
video_fps               15

# AVT - Audio/Video Transport
rtp_tos                 184
#rtp_ports              10000-20000
rtp_bandwidth           512-2048 # [kbit/s]
rtcp_enable             yes
rtcp_mux                no
jitter_buffer_delay     0               # frames
rtp_stats               no
#rtp_timeout            60

# Network
#dns_server             127.0.0.1:53
#net_interface          wlan0

# BFCP
#bfcp_proto             udp

#------------------------------------------------------------------------------
# Modules

module_path             /usr/local/lib/baresip/modules

# UI Modules
module                  stdio.so
#module                 cons.so
#module                 evdev.so
module                  httpd.so

# Audio codec Modules (in order)
module                  opus.so
#module                 silk.so
#module                 amr.so
#module                 g7221.so
#module                 g722.so
#module                 g726.so
module                  g711.so
#module                 gsm.so
#module                 l16.so
#module                 speex.so
#module                 bv32.so
#module                 mpa.so
#module                 codec2.so
#module                 ilbc.so
#module                 isac.so

# Audio filter Modules (in encoding order)
module                  vumeter.so
#module                 sndfile.so
module                  speex_aec.so
module                  speex_pp.so
#module                 plc.so

# Audio driver Modules
module                  alsa.so
#module                 pulse.so
#module                 jack.so
#module                 portaudio.so
#module                 aubridge.so
#module                 aufile.so

# Video codec Modules (in order)
module                  avcodec.so
module                  vp8.so
#module                 vp9.so
#module                 h265.so

# Video filter Modules (in encoding order)
#module                 selfview.so
#module                 snapshot.so
#module                 swscale.so
#module                 vidinfo.so

# Video source modules
#module                 v4l.so
module                  v4l2.so
#module                 v4l2_codec.so
#module                 x11grab.so
#module                 cairo.so
#module                 vidbridge.so

# Video display modules
#module                 directfb.so
#module                 x11.so
#module                 sdl2.so
#module                 fakevideo.so

# Audio/Video source modules
#module                 rst.so
#module                 gst1.so
#module                 gst_video1.so

# Media NAT modules
module                  stun.so
module                  turn.so
module                  ice.so
#module                 natpmp.so

# Media encryption modules
#module                 srtp.so
#module                 dtls_srtp.so
#module                 zrtp.so

#------------------------------------------------------------------------------
# Temporary Modules (loaded then unloaded)

module_tmp              uuid.so
module_tmp              account.so

#------------------------------------------------------------------------------
# Application Modules

module_app              auloop.so
module_app              contact.so
module_app              debug_cmd.so
module_app              dtmfio.so
#module_app             echo.so
#module_app                     gtk.so
module_app              menu.so
#module_app             mwi.so
#module_app             natbd.so
#module_app             presence.so
#module_app             syslog.so
module_app              vidloop.so

#------------------------------------------------------------------------------
# Module parameters

cons_listen             0.0.0.0:5555

http_listen             0.0.0.0:8000

evdev_device            /dev/input/event0

# Speex codec parameters
speex_quality           10 # 0-10
speex_complexity        10 # 0-10
speex_enhancement       1 # 0-1
speex_mode_nb           3 # 1-6
speex_mode_wb           6 # 1-6
speex_vbr               0 # Variable Bit Rate 0-1
speex_vad               0 # Voice Activity Detection 0-1
speex_agc_level         8000

# Opus codec parameters
opus_bitrate            28000 # 6000-510000

# Selfview
#video_selfview         window # {window,pip}
#selfview_size          64x64

# ICE
ice_turn                no
ice_debug               no
ice_nomination          regular # {regular,aggressive}
ice_mode                full    # {full,lite}

# Menu
#redial_attempts                3 # Num or <inf>
#redial_delay           5 # Delay in seconds`

Thank you in advance.
Best regards,
Maciej

**Comment by alfredh** [comment]
the speex_aec module is not really working.

we should add support for alternative AEC with better quality.
patches are welcome.

/Alfred

**Comment by maci3k90** [comment]
Ok, thank you for answer.

Using PulseAudio and its echo canceling has any sense?

**Comment by Moisesbr** [comment]
@maci3k90 
I'm using Baresip with Pulse and aec_method=webrtc works really good.
Put this in your system.pa (config for pulse)

```
>  load-module module-echo-cancel source_name=baresip aec_method=webrtc
>  set-default-source baresip
>  set-default-sink 2 (That will change in your system use the command pulse pacmd list-sinks to list your sink)
```

**Comment by alfredh** [comment]
@Moisesbr many thanks for your input regarding this topic.

Do you think you could add a little Wiki article about this ?


/Alfred

**Comment by Moisesbr** [comment]
@alfredh 
Yes of course, https://github.com/alfredh/baresip/wiki/Using-PulseAudio:-Module-module-echo-cancel

**Comment by alfredh** [comment]
@Moisesbr thank you, we appreciate your contribution.

**Comment by maci3k90** [comment]
Hello and thank you for answers.

@Moisesbr have you faced something like this? :
`I: [pulseaudio] source.c: Created source 5 "alsa_output.platform-audiocodec.analog-stereo.echo-cancel.monitor" with sample spec float32le 1ch 8000Hz and channel map mono
I: [pulseaudio] source.c:     device.description = "Monitor of audiocodec Analog Stereo (echo cancelled with audiocodec Analog Stereo)"
I: [pulseaudio] source.c:     device.class = "monitor"
I: [pulseaudio] source.c:     device.icon_name = "audio-input-microphone"
I: [pulseaudio] source-output.c: Trying to change sample rate
I: [alsa-source-SUNXI-CODEC sndcodec-0] alsa-source.c: Device suspended...
I: [pulseaudio] alsa-source.c: Updating rate for device hw:0, new rate is 48000
I: [pulseaudio] source.c: Changed sampling rate successfully
I: [alsa-source-SUNXI-CODEC sndcodec-0] alsa-source.c: Trying resume...
I: [alsa-source-SUNXI-CODEC sndcodec-0] alsa-util.c: Cannot disable ALSA period wakeups
I: [alsa-source-SUNXI-CODEC sndcodec-0] alsa-util.c: ALSA period wakeups were not disabled
I: [alsa-source-SUNXI-CODEC sndcodec-0] alsa-source.c: Time scheduling watermark is 18.38ms
I: [alsa-source-SUNXI-CODEC sndcodec-0] alsa-source.c: Resumed successfully...
I: [alsa-source-SUNXI-CODEC sndcodec-0] alsa-source.c: Starting capture.
I: [pulseaudio] source-output.c: Rate changed to 48000 Hz
I: [pulseaudio] remap_neon.c: Using ARM NEON stereo to mono remapping
I: [pulseaudio] source-output.c: Created output 0 "Echo-Cancel Source Stream" on alsa_input.platform-audiocodec.analog-stereo with sample spec float32le 1ch 8000Hz and channel map mono
I: [pulseaudio] source-output.c:     media.name = "Echo-Cancel Source Stream"
I: [pulseaudio] source-output.c:     media.role = "filter"
I: [pulseaudio] source-output.c:     module-stream-restore.id = "source-output-by-media-role:filter"
I: [pulseaudio] remap_neon.c: Using ARM NEON mono to stereo remapping
I: [pulseaudio] sink-input.c: Created input 0 "Echo-Cancel Sink Stream" on alsa_output.platform-audiocodec.analog-stereo with sample spec float32le 1ch 8000Hz and channel map mono
I: [pulseaudio] sink-input.c:     media.name = "Echo-Cancel Sink Stream"
I: [pulseaudio] sink-input.c:     media.role = "filter"
I: [pulseaudio] sink-input.c:     module-stream-restore.id = "sink-input-by-media-role:filter"
I: [pulseaudio] module.c: Loaded "module-echo-cancel" (index: #12; argument: "source_name=baresip aec_method=webrtc format=s16le rate=8000 channels=1").
I: [pulseaudio] main.c: Daemon startup complete.
E: [alsa-source-SUNXI-CODEC sndcodec-0] module-echo-cancel.c: Doing resync
E: [alsa-source-SUNXI-CODEC sndcodec-0] module-echo-cancel.c: Playback after capture (-9910245), drop sink 317164
Killed`

It is always killing itself.

**Comment by Moisesbr** [comment]
Hello,
@maci3k90 Could you try Edit default.pa or system.pa with that config ?

load-module module-udev-detect tsched=0

/Moisés

**Comment by maci3k90** [comment]
Yes, now it is not killing itself, thank you.

Unfortunately still some errors appears and baresip tells "connection refused" (I have followed your wiki post).
`D: [pulseaudio] module-udev-detect.c: /dev/snd/controlC1 is accessible: yes
D: [pulseaudio] module-udev-detect.c: Resuming all sinks and sources of card alsa_card.platform-sndhdmi.
E: [alsa-source-SUNXI-CODEC sndcodec-0] module-echo-cancel.c: Doing resync
D: [alsa-source-SUNXI-CODEC sndcodec-0] module-echo-cancel.c: Diff -549663 (146717 - 714000 + 17182) 609000 0 18750 438
E: [alsa-source-SUNXI-CODEC sndcodec-0] module-echo-cancel.c: Playback after capture (-549663), drop sink 17628
D: [pulseaudio] source.c: The reference volume of source alsa_input.platform-audiocodec.analog-stereo changed from front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB to front-left: 21845 /  33% / -28.63 dB,   front-right: 21845 /  33% / -28.63 dB.
D: [pulseaudio] source.c: The reference volume of source baresip changed from mono: 65536 / 100% to mono: 21845 /  33%.
D: [pulseaudio] source-output.c: The volume of source output 0 changed from mono: 65536 / 100% / 0.00 dB to mono: 21845 /  33% / -28.63 dB.
E: [alsa-source-SUNXI-CODEC sndcodec-0] alsa-source.c: ALSA woke us up to read new data from the device, but there was actually nothing to read.
E: [alsa-source-SUNXI-CODEC sndcodec-0] alsa-source.c: Most likely this is a bug in the ALSA driver '(null)'. Please report this issue to the ALSA developers.
E: [alsa-source-SUNXI-CODEC sndcodec-0] alsa-source.c: We were woken up with POLLIN set -- however a subsequent snd_pcm_avail() returned 0 or another value < min_avail.
I: [pulseaudio] module-suspend-on-idle.c: Source alsa_input.platform-sndhdmi.analog-stereo idle for too long, suspending ...
D: [pulseaudio] source.c: Suspend cause of source alsa_input.platform-sndhdmi.analog-stereo is 0x0004, suspending
I: [alsa-source-SUNXI-HDMIAUDIO sndhdmi-0] alsa-source.c: Device suspended...
`
I am not expirienced in PulseAudio, actually I have never used it before, so if you could give me any tip, I will appriciate.

Best regards.

**Comment by maci3k90** [comment]
Finally something works, thank you. 

Unfortunately, when the baresip establishes connection it hangs and returns a lot of lines:

pulse: pa_simple_write error (Connection terminated)

@Moisesbr do you have any idea what is wrong?

**Comment by Moisesbr** [comment]
@maci3k90 may be your PULSE_SERVER env. var. is pointing to wrong location, pay very close attention to export PULSE_SERVER="unix:/usr/local/var/run/pulse/native" this location must have your unix socket created by pulse server.

**Comment by maci3k90** [comment]
@Moisesbr yes this I have already figured out :) thanks.

New problem is: 

pulse: pa_simple_write error (Connection terminated)

**Comment by maci3k90** [comment]
@Moisesbr Thank you for all your help. 

Unfortunately in my case pulseaudio echo cancellation doesn't work. 

I am running it on embedded system which communicates with Android device. When I am talking to my Android device I can here myself. I was also discussing the problem with developers of Android SIP client, and they are almost sure that my echo cancellation doesn't work and it is not a problem with their app.

Do you use baresip for direct communication with other devices or you use also asterisk? I am thinking if asterisk shouldn't be the source for echo cancellation if it is used?

Actually my communication looks like this:

baresip -> asterisk -> Android SIP client

Maybe one more suggestion? :) I will appriciate.

**Comment by Moisesbr** [comment]
@maci3k90 
I really belive that you are using wrong sink, Lets try another approach, 

Edit your system.pa e put this, the difference is that way we ensure the default sink

- load-module module-echo-cancel aec_method=webrtc aec_args="analog_gain_control=0 digital_gain_control=0" source_name=echoCancel_source sink_name=echoCancel_sink
- set-default-source echoCancel_source
- set-default-sink echoCancel_sink

**Comment by maci3k90** [comment]
Finally it works, thank you very much.

Working configuration in my case is:

- load-module module-echo-cancel source_master=alsa_input.platform-audiocodec.analog-stereo source_name=baresipsrc sink_master=alsa_output.platform-audiocodec.analog-stereosink_name=baresipsink aec_method=webrtc

- set-default-source baresipsrc

- set-default-sink baresipsink
