### ISSUE TITLE
Error during compilation of the source code

### ISSUE THREAD

**Issue by RemsHag** [alfredh/baresip#270]
Hello,

i tried to compile baresip on OS X but i got some issues

My configuration :

MacOS Sierra
Version 10.12.5

XCode 8.3.3 (8E3004b)

XCode command tools line installed

Here is my logs:

> ld: warning: directory not found for option '-L-lre'
> Undefined symbols for architecture arm64:
>   "_list_append", referenced from:
>       _aubuf_append in aubuf.o
>       _aumix_source_enable in aumix.o
>       _vidmix_source_enable in vidmix.o
>   "_list_count", referenced from:
>       _aumix_source_count in aumix.o
>   "_list_flush", referenced from:
>       _aubuf_destructor in aubuf.o
>       _aubuf_flush in aubuf.o
>   "_list_unlink", referenced from:
>       _auframe_destructor in aubuf.o
>       _source_destructor in aumix.o
>       _aumix_source_enable in aumix.o
>       _source_destructor in vidmix.o
>       _vidmix_source_enable in vidmix.o
>   "_lock_alloc", referenced from:
>       _aubuf_alloc in aubuf.o
>   "_lock_read_get", referenced from:
>       _aubuf_debug in aubuf.o
>       _aubuf_cur_size in aubuf.o
>   "_lock_rel", referenced from:
>       _aubuf_append in aubuf.o
>       _aubuf_read in aubuf.o
>       _aubuf_get in aubuf.o
>       _aubuf_flush in aubuf.o
>       _aubuf_debug in aubuf.o
>       _aubuf_cur_size in aubuf.o
>   "_lock_write_get", referenced from:
>       _aubuf_append in aubuf.o
>       _aubuf_read in aubuf.o
>       _aubuf_get in aubuf.o
>       _aubuf_flush in aubuf.o
>   "_mbuf_alloc", referenced from:
>       _aubuf_write in aubuf.o
>   "_mbuf_read_mem", referenced from:
>       _aubuf_read in aubuf.o
>   "_mbuf_write_mem", referenced from:
>       _aubuf_write in aubuf.o
>   "_mbuf_write_u16", referenced from:
>       _autone_sine in tone.o
>       _autone_dtmf in tone.o
>   "_mem_alloc", referenced from:
>       _aumix_thread in aumix.o
>       _aumix_source_alloc in aumix.o
>   "_mem_deref", referenced from:
>       _aubuf_alloc in aubuf.o
>       _aubuf_destructor in aubuf.o
>       _aubuf_append in aubuf.o
>       _auframe_destructor in aubuf.o
>       _aubuf_write in aubuf.o
>       _aubuf_read in aubuf.o
>       _aufile_open in aufile.o
>       ...
>   "_mem_ref", referenced from:
>       _aubuf_append in aubuf.o
>       _aumix_source_alloc in aumix.o
>       _vidmix_source_alloc in vidmix.o
>   "_mem_zalloc", referenced from:
>       _aubuf_alloc in aubuf.o
>       _aubuf_append in aubuf.o
>       _aufile_open in aufile.o
>       _aumix_alloc in aumix.o
>       _aumix_thread in aumix.o
>       _aumix_source_alloc in aumix.o
>       _vidmix_alloc in vidmix.o
>       ...
>   "_re_fprintf", referenced from:
>       _wav_header_decode in wave.o
>       _auconv_from_s16 in auconv.o
>       _auconv_to_s16 in auconv.o
>       _vidframe_draw_point in draw.o
>       _vidframe_draw_hline in draw.o
>   "_re_hprintf", referenced from:
>       _aubuf_debug in aubuf.o
>   "_re_printf", referenced from:
>       _vidframe_init_buf in frame.o
>       _vidframe_fill in frame.o
>       _vidframe_copy in frame.o
>       _vidconv in vconv.o
>   "_sys_htoll", referenced from:
>       _wav_header_encode in wave.o
>   "_sys_htols", referenced from:
>       _wav_header_encode in wave.o
>   "_sys_ltohl", referenced from:
>       _wav_header_decode in wave.o
>   "_sys_ltohs", referenced from:
>       _wav_header_decode in wave.o
>   "_tmr_jiffies", referenced from:
>       _aubuf_get in aubuf.o
>       _aumix_thread in aumix.o
>       _content_thread in vidmix.o
>       _vidmix_thread in vidmix.o
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[1]: *** [librem.dylib] Error 1
> make: *** [librem] Error 2

----------------------------------------------------------

When i try to compile libre alone :

> LD      libre.dylib
> Undefined symbols for architecture x86_64:
>   "__mod_close", referenced from:
>       _mod_destructor in mod.o
>   "__mod_open", referenced from:
>       _mod_load in mod.o
>   "__mod_sym", referenced from:
>       _mod_load in mod.o
>   "_lock_alloc", referenced from:
>       _rtcp_sess_alloc in sess.o
>   "_lock_read_get", referenced from:
>       _rtcp_stats in sess.o
>       _rtcp_debug in sess.o
>   "_lock_rel", referenced from:
>       _rtcp_sess_tx_rtp in sess.o
>       _rtcp_stats in sess.o
>       _rtcp_debug in sess.o
>       _mk_sr in sess.o
>   "_lock_write_get", referenced from:
>       _rtcp_sess_tx_rtp in sess.o
>       _mk_sr in sess.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [libre.dylib] Error 1

-----------------------------------------------

When i try to compile librem alone : 

> LD      librem.dylib
> ld: warning: directory not found for option '-L-lre'
> Undefined symbols for architecture x86_64:
>   "_list_append", referenced from:
>       _aubuf_append in aubuf.o
>   "_list_flush", referenced from:
>       _aubuf_destructor in aubuf.o
>       _aubuf_flush in aubuf.o
>   "_list_unlink", referenced from:
>       _auframe_destructor in aubuf.o
>   "_lock_alloc", referenced from:
>       _aubuf_alloc in aubuf.o
>   "_lock_read_get", referenced from:
>       _aubuf_debug in aubuf.o
>       _aubuf_cur_size in aubuf.o
>   "_lock_rel", referenced from:
>       _aubuf_append in aubuf.o
>       _aubuf_read in aubuf.o
>       _aubuf_get in aubuf.o
>       _aubuf_flush in aubuf.o
>       _aubuf_debug in aubuf.o
>       _aubuf_cur_size in aubuf.o
>   "_lock_write_get", referenced from:
>       _aubuf_append in aubuf.o
>       _aubuf_read in aubuf.o
>       _aubuf_get in aubuf.o
>       _aubuf_flush in aubuf.o
>   "_mbuf_alloc", referenced from:
>       _aubuf_write in aubuf.o
>   "_mbuf_read_mem", referenced from:
>       _aubuf_read in aubuf.o
>   "_mbuf_write_mem", referenced from:
>       _aubuf_write in aubuf.o
>   "_mbuf_write_u16", referenced from:
>       _autone_sine in tone.o
>       _autone_dtmf in tone.o
>   "_mem_deref", referenced from:
>       _aubuf_alloc in aubuf.o
>       _aubuf_destructor in aubuf.o
>       _aubuf_append in aubuf.o
>       _auframe_destructor in aubuf.o
>       _aubuf_write in aubuf.o
>       _aubuf_read in aubuf.o
>       _aufile_open in aufile.o
>       ...
>   "_mem_ref", referenced from:
>       _aubuf_append in aubuf.o
>   "_mem_zalloc", referenced from:
>       _aubuf_alloc in aubuf.o
>       _aubuf_append in aubuf.o
>       _aufile_open in aufile.o
>       _vidframe_alloc in frame.o
>   "_re_fprintf", referenced from:
>       _wav_header_decode in wave.o
>       _auconv_from_s16 in auconv.o
>       _auconv_to_s16 in auconv.o
>       _vidframe_draw_point in draw.o
>       _vidframe_draw_hline in draw.o
>   "_re_hprintf", referenced from:
>       _aubuf_debug in aubuf.o
>   "_re_printf", referenced from:
>       _vidframe_init_buf in frame.o
>       _vidframe_fill in frame.o
>       _vidframe_copy in frame.o
>       _vidconv in vconv.o
>   "_sys_htoll", referenced from:
>       _wav_header_encode in wave.o
>   "_sys_htols", referenced from:
>       _wav_header_encode in wave.o
>   "_sys_ltohl", referenced from:
>       _wav_header_decode in wave.o
>   "_sys_ltohs", referenced from:
>       _wav_header_decode in wave.o
>   "_tmr_jiffies", referenced from:
>       _aubuf_get in aubuf.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [librem.dylib] Error 1
> 

Rems

**Comment by juha-h** [comment]
RemsHag writes:

> > ld: warning: directory not found for option '-L-lre'

Syntax of the options above does not look valid.

-- Juha

**Comment by RemsHag** [comment]
What is the correct syntax?

**Comment by RemsHag** [comment]
if i use the correction here (https://github.com/alfredh/baresip-ios/issues/2#issuecomment-21413975), it seems to be good.

I have others issues with web rtc, but we can close this issue

**Comment by juha-h** [comment]
RemsHag writes:

> What is the correct syntax?

See 'man ld'.

-- Juha

**Comment by alfredh** [comment]
you can also install binary version from Macports or Homebrew:

```
brew install baresip

or

sudo port install baresip
```


/Alfred
