### ISSUE TITLE
rtp_timeout conflicts with video_mute

### ISSUE THREAD

**Issue by MobiSciLab** [alfredh/baresip#271]
if we set rtp_timeout = timeout and video_mute(true) at the same time, the call will drop after the timeout period. I think it is better to have  separated configurations: video timeout and audio timeout

**Comment by alfredh** [comment]
would it be okay if also incoming RTCP packets can reset the timer?

**Comment by MobiSciLab** [comment]
Yes, it would work. Thank you.
