### ISSUE TITLE
feature/help for anti-block secure tunnel

### ISSUE THREAD

**Issue by dipenpatel235** [alfredh/baresip#272]
hello,,,
in this is there any feature to antiblock tunnel for blocked voip country ?

thanks

**Comment by alfredh** [comment]
Hi @dipenpatel235 

I have some questions for you:

1. in which country are you based?
2. which SIP provider are you using?
3. have you tried any VPN solutions?
4. can you please include full debug logs?

first of all, what kind of traffic is blocked is it e.g. SIP or RTP?
you should first make sure that it really is blocked, and that is is not
a NAT misconfiguration problem.

without knowing more details, I think the following may help:

1. use a VPN client and let baresip bind to that tunneling interface
2. add support for TURN over TLS for the media stream.


/Alfred

**Comment by dipenpatel235** [comment]
1. in which country are you based?-o am in India but solution for block
   country like dubai
   2. which SIP provider are you using? - linphone
   3. have you tried any VPN solutions? - yes but that is also block due to
   upstream n downstream same
   4. can you please include full debug logs? - I have not log of that

Thanks.

**Comment by alfredh** [comment]
Baresip is a SIP useragent that is designed to work on the Internet.

if you are using Linphone then you should contact them instead.


/alfred
