### ISSUE TITLE
Special characters in SIP password

### ISSUE THREAD

**Issue by PikaYellow35** [alfredh/baresip#273]
Hello.
I can not use the SIP account with special characters, for example @. The standard version with %40 does not work. Checked for the latest version of the baresip 0.5.4.

Sorry for my poor English.

**Comment by alfredh** [comment]
maybe we should add a new `;password=xxx` parameter and deprecate the
password field in the SIP uri ?

**Comment by alfredh** [comment]
@PikaYellow35 could you please test this patch:

```
diff --git a/src/account.c b/src/account.c
index e23d5c8..c3f26eb 100644
--- a/src/account.c
+++ b/src/account.c
@@ -396,7 +396,9 @@ int account_alloc(struct account **accp, const char *sipaddr)
                        goto out;
        }
        else {
-               err = pl_strdup(&acc->auth_pass, &acc->laddr.uri.password);
+               err = re_sdprintf(&acc->auth_pass, "%H",
+                                 uri_password_unescape,
+                                 &acc->laddr.uri.password);
                if (err)
                        goto out;
        }
```

it adds unescaping of the password field, so you use e.g. %40 instead of @ 


/Alfred

**Comment by PikaYellow35** [comment]
I'm sorry for the long answer. Thanks for patch. I'm recompile baresip and report the results.

**Comment by PikaYellow35** [comment]
Yes, it work. Many thanks. =)

**Comment by alfredh** [comment]
@PikaYellow35 many thanks for reporting and testing
