### ISSUE TITLE
Support for ARMv5

### ISSUE THREAD

**Issue by gunasekaran7** [alfredh/baresip#274]
Does the library support armv5 architecture?

**Comment by alfredh** [comment]
which hardware/compiler are you using?

if your compiler can generate ARMv5 code then it will most likely work just fine.

**Comment by gunasekaran7** [comment]
I am using gcc-4.8 compiler from android-ndk-r8e. And building Mobile phone with android-2.1

**Comment by gunasekaran7** [comment]
And is there a Makefile configuration for cross compiling?

**Comment by alfredh** [comment]
you are using a very old Android NDK I must say :)

the latest Android NDK is r14

for cross-compiling to Android please have a look here:

https://github.com/alfredh/baresip-android

**Comment by gunasekaran7** [comment]
I have updated the Android NDK. And I am able to use it with Android. I would like to use it with Linux running on ARMv5. Is there a Makefile configuration for cross compiling?

**Comment by alfredh** [comment]
can you please clarify if this question is about Android or Linux/ARMv5 ?

you can cross compile libre/baresip by using the `CC` option:

```
$ make CC=arm-linux-gcc
```

(which Hardware and Toolchain are you using for the Linux/ARMv5) ?

/Alfred

**Comment by gunasekaran7** [comment]
I was able to compile it successfully. Thank you :+1: 

Note:
I was trying with NDK to build for Linux on ARMv5 and later I used the CROSS_COMPILER to compile it directly without NDK.
