### ISSUE TITLE
Configuration Parameter of various modules in config file

### ISSUE THREAD

**Issue by gunasekaran7** [alfredh/baresip#277]
Is there doc which explains the parameter that can be set in "config" file for various modules?

And, What are the modules should I enable if I need only video encoding? (No need of Audio encoding/decoding and video decoding)?

**Comment by oej** [comment]
This is a very good set of questions for the mailing list, but not the bug tracker. The tracker is for reporting and fixing bugs in the software. Please send your question to the mailing list and I'm sure someone will happily answer you!
