### ISSUE TITLE
X-RTP-Stat header: report of packet delay always set to zero

### ISSUE THREAD

**Issue by smokersonly** [alfredh/baresip#278]
It seems the packet delay is always set to zero. (PD=0). The other parameters like PL, JI are all working.
Using Baresip 0.5.3

Example:
X-RTP-Stat: EX=BareSip;CS=1000;CD=29;PR=1463;PS=1490;PL=0,0;PD=0,0;JI=3.0,3.0;IP=0.0.0.0:48926,10.57.26.195:12856;EN=PCMA/8000;DE=PCMA/8000

**Comment by lmangani** [comment]
If memory doesn't fail me, and it's been a while both delay and IP fields were pending some patches in libRE I never got around actually using them.... will attempt to take a look if time allows

**Comment by smokersonly** [comment]
THX!

**Comment by alfredh** [comment]
@smokersonly what does the specification say about the PD field?

according to the source code it means Packets Discarded:
(audio.c line 1712)

```
			 "PD=%d,%d;"     /* Packets Discarded, RX, TX        */
```


/Alfred

**Comment by smokersonly** [comment]
hmm, there is no RFC for this as far as I know, just this reference:
https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/xrtpv32.pdf

there is indeed no PD parameter in that document, so my assumption that it had anything to do with delay was wrong.
