### ISSUE TITLE
/play - No sound on receiver 

### ISSUE THREAD

**Issue by jrodriguesnum1** [alfredh/baresip#280]
Hello,

I'm trying to play a wav from baresip to an yate client. Both are registered on an Asterisk server. The baresip v0.5.4 instance is running in a Unbuntu 16.04 virtual machine, Asterisk 14 is running on Freepbx 14.0.1.1, also on a virtual machine, and the yate client is running on the windows host.

During the call I attempt to play a wav file with the command:

`/play ringback.wav`

I can ear the sound of the file playing on the ubuntu guest that is running baresip. However, if I mute the volume in that machine I stop listening to the file, but I keep listing the input from the mic on the yate client.

Here is the output of baresip:
![baresip-init](https://user-images.githubusercontent.com/4401376/28181644-459d4620-6801-11e7-861e-2fc8cc0b4f3c.PNG)

Thank you for your attention.

**Comment by jungle-boogie** [comment]
Hi @jrodriguesnum1,

`/play` is for local playback of a file. You will want to use `/auplay`

See this issue for a similar question from me:
https://github.com/alfredh/baresip/issues/185

**Comment by jrodriguesnum1** [comment]
Thank you for your quick response.

Where can I find examples of the use of `/auplay`?
I attempted `/auplay ringback.wav` but I got `Format should be: driver,device`.

**Comment by jungle-boogie** [comment]
Screenshots don't help. Provide logs from when you're attempting to play files.

**Comment by jungle-boogie** [comment]
Also worth checking this out:
https://github.com/alfredh/baresip/wiki/Using-Baresip:-Module-alsa

> alsa: could not open auplay device.

Sounds like you might need to configure alsa.

**Comment by jrodriguesnum1** [comment]
I've already figured out how to do it:

`/ausrc aufile,<audio file>`

Thank you for the help.

**Comment by flintt** [comment]
If it prompted for audio file at 8000 sample rate: `ffmpeg -i test.wav -ac 1 -ar 8000 -acodec pcm_s16le test2.wav `
