### ISSUE TITLE
account.c: uric: unescape: illegal '^'

### ISSUE THREAD

**Issue by jungle-boogie** [alfredh/baresip#281]
Hi Alfred,

I see this issue: https://github.com/alfredh/baresip/issues/273 and this commit: https://github.com/alfredh/baresip/commit/5b1f3237c1cc181d216a02ce604614adb792aa17

Does this commit support escaping the caret sign (`^`)? Interestingly, baresip doesn't have an issue with the `&` sign.

**Comment by alfredh** [comment]
the caret sign ('^') must now be escaped, try to use `%5e` instead.

given that escaping passwords is cumbersome for users and that the
password field in a SIP uri is deprecated, I will add a new parameter
`;auth_pass=xxx` for this.

**Comment by jungle-boogie** [comment]
> I will add a new parameter ;auth_pass=xxx for this.

That would be very welcomed!

**Comment by alfredh** [comment]
@jungle-boogie could you please test this commit:

https://github.com/alfredh/baresip/commit/19e66aa85ac3cbc610ed2280064495ae66a7bdb2

try to change your SIP account line to something like:

```
<sip:username@domain.com>;auth_pass="xxxxxx"
```

(double quotes around xxxxxx are optional)


/Alfred

**Comment by jungle-boogie** [comment]
This is all better! Thank you!
