### ISSUE TITLE
v4l doesn't support any format except RGB24

### ISSUE THREAD

**Issue by gunasekaran7** [alfredh/baresip#282]
V4L video source module has support for only RGB24 image format. Why it's constrained like that?
What we need to consider if we want to add support for other formats?

**Comment by alfredh** [comment]
the baresip core will convert pixelformat to YUV420P if needed.

can you try the `vidloop` command using v4l as vidsrc , and paste the full
log here ?

**Comment by gunasekaran7** [comment]
My image sensor support only YUV420.In the case, how I should handle this.

Note:
I will add the log as I dont have the board currently.

**Comment by gunasekaran7** [comment]
Log with Vidloop command:

> v4l:supported palette 7 (only RGB24 supp.)

**Comment by alfredh** [comment]
Hi @gunasekaran7 

could you please include the full log, and not just the last line? it is very helpful
for me and others to have the full context.

is there any chance that you can use v4l2 instead of v4l ?

the v4l module is currently hardcoded to only support RGB32 pixel format.
if you want to try to add support for more pixel formats, here are some
hints and tips for how to do it:

(ref https://github.com/alfredh/baresip/tree/master/modules/v4l)


```
	if (VIDEO_PALETTE_RGB24 != pic.palette) {
		warning("v4l: unsupported palette %d (only RGB24 supp.)\n",
			pic.palette);
		return ENODEV;
	}

```
instead of this, create a mapping function to convert from v4l palette
to `enum vidfmt` and save the pixel format on the state.

```
static void call_frame_handler(struct vidsrc_st *st, uint8_t *buf)
{
	struct vidframe frame;

	vidframe_init_buf(&frame, VID_FMT_RGB32, &st->size, buf);

	st->frameh(&frame, st->arg);
}
```

instead of RGB32, use the saved pixel format. you must also split the buffer
into 3 planes and save it on `frame->data[0-2]` and `frame->linesize[0-2`.

```
static uint32_t rgb24_size(const struct vidsz *sz)
{
	return sz ? (sz->w * sz->h * 24/8) : 0;
}
```
instead of this, allocate a buffer which is big enough for the
used palette (pixel format).


/Alfred

**Comment by gunasekaran7** [comment]
@alfredh , I have modified the buffer size in the place that you have mentioned. And I am getting the following error,

>Enable video-loop on v4l,/dev/viVideoIn port 1 opened(0)
>Init NT_99141 in port 1
>Sensor reset
>video0: 352 x 288
>vidloop: added video-filter `selfview_window'
>vidloop: v4l,/dev/video0: open video source: 352 x 288 at 25 fps
>v4l: open: /dev/video0 (352 x 288)
>I2C added
>detectd sensor id0=14 id1=10
>NTSetResolution:1
>sensor change resolution begin---— 
>Programming sensor init value
>Programming sensor resolution value = 1
>sensor change resolution end---—
>video driver open successful
>v4l: video: "W55FA92 Camera dev1" (160x120) - (1videoin_close: current_task:baresip pid:660
280x720)
>v4l: not a capture device (641)
>v4l: Format is YUV
>v4l: video window: x,y=0I2C removed
,0 (856 x 480)
>vidloop: open video display (.)
>vidloop: video display failed: No such file or directory
> vidloop: alloc: No such file or directory

And the modification in the code is as follows:

`static int v4l_check_palette(struct vidsrc_st *st)
{
	struct video_picture pic;

	if (-1 == ioctl(st->fd, VIDIOCGPICT, &pic)) {
		warning("v4l: VIDIOCGPICT: %m\n", errno);
		return errno;
	}

	switch (pic.palette) {
	case VIDEO_PALETTE_RGB24:
		st->frame_size = 3;
		info("v4l: Format is RGB\n");
		return 0;
	case VIDEO_PALETTE_YUV422:
	case VIDEO_PALETTE_YUV422P:
	case VIDEO_PALETTE_YUV420:
	case VIDEO_PALETTE_YUV420P:
		st->frame_size = 2;
		info("v4l: Format is YUV\n");
		return 0;
	default:
		warning("v4l: unsupported palette %d (only RGB24 & YUV422 are supp.)\n",
			pic.palette);
		return ENODEV;
	}

	return 0;
}`

`static void call_frame_handler(struct vidsrc_st *st, uint8_t *buf)
{
	struct vidframe frame;

	unsigned int fmt_type = VID_FMT_RGB32;

	if(st->frame_size == 2){
		fmt_type = VID_FMT_YUV420P;
	}

	vidframe_init_buf(&frame, fmt_type, &st->size, buf);

	st->frameh(&frame, st->arg);
}`


`static uint32_t get_frame_size(const struct vidsz *sz, unsigned int bpp)
{
	return sz ? (sz->w * sz->h * bpp) : 0;
}`

In the `alloc` function,
`st->mb = mbuf_alloc(get_frame_size(&st->size, st->frame_size));`

**Comment by alfredh** [comment]
the vidloop is mainly for local testing, you also need to load a `vidisp` module
such as sdl2.so or x11.so (if your device has a display).

otherwise you can just make a normal video-call to your device.

**Comment by gunasekaran7** [comment]
@alfredh , are those changes are fine?

**Comment by alfredh** [comment]
it depends if the code is working or not.

if you get it working your are welcome to send me a patch/PR for review.

**Comment by alfredh** [comment]
Hi @gunasekaran7 

I added support for multiple pixel formats. Could you please test git HEAD
and see if that works for you?

/Alfred

**Comment by gunasekaran7** [comment]
@alfredh. Will check it on the board and let you know

**Comment by gunasekaran7** [comment]
@alfredh. I myself updated that in a different way and it's working fine. And I am unable to test your update with my changes as I am adding HW H264 encoder support.

I will close the issue.
