### ISSUE TITLE
No video frames from H.264 USB camera using v4l2_codec with baresip to baresip

### ISSUE THREAD

**Issue by stephenvharvey** [alfredh/baresip#283]
When using a h.264 USB camera, I only get a view keyframes and no deltas so that in effect there is no video at all. Strangly when I disable the module avcodec I get a lot of errors "video: No video decoder!" but I do get a few very hacky video frames.

As Alfred suggested in [this](https://github.com/alfredh/baresip/issues/124) issue - which seems very similar to my issue -  I dumped the raw stream with 
`ffmpeg -f v4l2 -input_format h264 -standard pal-b -s 704x576 -i /dev/video0 -vcodec copy -loglevel debug h264_usb_cam_raw.mp4
`  
The file is here: [https://s3-us-west-2.amazonaws.com/baresip-test/h264_usb_cam_raw.mp4](https://s3-us-west-2.amazonaws.com/baresip-test/h264_usb_cam_raw.mp4)

version: baresip 0.5.1
objective: video streaming from H.264 camera via v4l2_codec module form barsip to baresip

Log:
------
```
Set video encoder: H264 packetization-mode=0 (500000 bit/s, 25 fps)
video: no video display
v4l2_codec: Driver Caps:
  Driver:        "uvcvideo"
  Card:          "USB 2.0 Camera"
  Bus:           "usb-0000:00:14.0-6"
  Version:       4.0
  Capabilities:  0x84200001
  Formats:
  >  H264: C  'H.264'

v4l2_codec: Selected Camera Mode:
  Width:   1920
  Height:  1080
  PixFmt:  H264
  Field:   1
main: long async blocking: 808>100 ms (h=0x7fc217337f20 arg=0x55758802bbc0)
Set video decoder: H264 packetization-mode=0     
```
------

------
```
[0:00:00] audio=0/0 video=0/0 (bit/s) efps=0/0  
ua: stop all (forced=0)
Stopping 1 useragent.. 
v4l2_codec: encoder stats (keyframes:9, deltaframes:0)
```
------

**Comment by alfredh** [comment]
other people have also reported similar issues.

I am wondering if this happens because we are using `fd_listen`
in v4l2_codec to wait for async events. Perhaps we should try to
create a thread instead that does a blocking read.

/Alfred

**Comment by stephenvharvey** [comment]
Alfred, if there is anything you would like to try - I am more than happy to test and will give you fast feedback. Out of interest: is there any H.264 camera combination / setup that is known to work? (as the Logitech and ELP cams are mentioned)

Stephen

**Comment by stephenvharvey** [comment]
One strange thing that was also mentioned here: [https://github.com/alfredh/baresip/issues/64](https://github.com/alfredh/baresip/issues/64)
If avcodec appears before v4l2_codec in the config (which is default) - I will never get a visible video frame. But if I put it behind v4l2_codec in the config I do get some (albeit very few) visible frames. Which is consitent with the pattern I described that I do see some frames when I outcomment avcodec and get error messages.

**Comment by alfredh** [comment]
please note that the video codecs are used in the same order as the modules
are loaded, and the first matching codec will be used.


This will use encoder+decoder from avcodec:
```
module  avcodec.so
module v4l2_codec.so
```

This will use v4l2_codec encoder and avcodec decoder:
```
module v4l2_codec.so
module  avcodec.so
```


/Alfred

**Comment by stephenvharvey** [comment]
ok understood. But back to the core issue: if you have an idea on a threaded implementation - as I said I am happy to test. 

Also: do you have a h.264 usb camera that works without issues using v4l2_codec?

**Comment by alfredh** [comment]
I have a Logitech C920 camera that works with Debian Testing.

please see a v4l2 dump here:

https://gist.github.com/alfredh/28d43a88e1fdb6fa4e7f54529f021d54

**Comment by petergerten** [comment]
ok, I'll get a C920 to check if that works.
So you can't reproduce the issue that I and others reported that you suspect might be related to the async reads?

**Comment by stephenvharvey** [comment]
ok, I'll get a C920 to check if that works.
So you can't reproduce the issue that I and others reported that you suspect might be related to the async reads?

**Comment by alfredh** [comment]
can you also try to change the async io option in .baresip/config:

```
# Core
poll_method             epoll           # poll, select, epoll ..
```

**Comment by stephenvharvey** [comment]
ok. I tried epoll, poll, select -> behavior stays the same. Are there any other poll methods?

**Comment by alfredh** [comment]
For Linux there is only poll, select, epoll. Thanks for testing that :)
(which system are you on BTW).

1. could you please test the regular `v4l2` module and see if that one is working ?

2. in the `v4l2_codec` module could you add some extra log-lines in the
  `read_handler` (either using re_printf or info). I am interested to see how many
  times the read_handler is called.

**Comment by stephenvharvey** [comment]
I am on arch linux (Linux pg 4.11.9-1-ARCH #1 SMP PREEMPT Wed Jul 5 18:23:08 CEST 2017 x86_64 GNU/Linux) for testing, put plan to deploy it on an embedded arm system once I get the h.264 cam working.

The v4l2 module works without issues in combination with the software encoder.

The C920 camera just arrived and I took it for a test run. It does behave different from my other h.264 camera (which is an ELP module using a SONIX h.264 asic encoder):
The first thing I noticed with the C920 is that it takes 17seconds until I get the first image and then I have a latency of those 17seconds for the duration of the call (localhost baresip to baresip connection). But with the logitech camera I do get deltaframes and the video is smoother than with the other camera where I only get keyframes. But the video is still not perfect and I see compression artifacts. For a 2 minute video call with the C920 I get (keyframes:15, deltaframes:4255) which seems ok - looks like the encoder has a long interval for keyframes configured. I have no idea what introduces the 17 sconds latency though.

On the ELP camera I never get any delta frames at all. It has a much shorter key frame interval though.

As you suggested I will add some debug output and will report back.

**Comment by stephenvharvey** [comment]
FYI: I deployed the setup on my ARM target system running a 4.1.21 kernel (using baresip/libre git) and can reproduce the behavior I see on mu Arch desktop test system with both the ELP and the C920 camera.

**Comment by alfredh** [comment]
I added some extra debugging in v4l2_codec.

some differences between v4l2.so and v4l2_codec.so:

- v4l2 uses up to 4 mmap buffers, while v4l2_codec uses only 1
- v4l2 uses pthread, while v4l2_codec uses async fd_listen

**Comment by alfredh** [comment]
Hi @stephenvharvey 

BTW, could you also include kernel log while capturing?

**Comment by alfredh** [comment]
Hi @stephenvharvey 

I added support for multiple buffers in this branch:

https://github.com/alfredh/baresip/tree/v4l2_codec_buffers

can you please test it, and start baresip with -v flag (verbose)


/Alfred

**Comment by stephenvharvey** [comment]
Thanks Alfred.
Sorry for the late feedback but something strange happened and I am still tryring to reproduce / clarify it.
After some tinkering on my build system for the target platfirm suddenly everything worked. I get a smooth video now using the ELP camera with v4l2_codec and currently can't reproduce the issue I pointed out before. Will keep investigating and also try out the new branch.

**Comment by alfredh** [comment]
did you have a chance to test my branch ?

**Comment by alfredh** [comment]
Hi @stephenvharvey 

I would appreciate if you could test the branch that I created to try to solve
this case. If I dont hear anything soon I will close the ticket.

Given that many people have reported that this module works just fine
with their camera, and a couple of people have reported that it is not working,
I can only assume that there is a bug in the Linux driver. Aside from that
it is hard for me to debug the problem without access to hardware.


/Alfred

**Comment by swedmike** [comment]
My e920 shows the same behavior in Debian testing. ffmpeg and gstreamer/v4l2 pulls encoded H.264 as expected but baresip vidloop gives no frames. "status: [] []  intra=0  EFPS=0.0      0 kbit/s" is written to the terminal.

Please let me know if I can be of any help on this issue. Output follows.
```

# Working ffmpeg:

$ ffmpeg -r 30 -use_wallclock_as_timestamps 1 -copytb 0 -f v4l2 -video_size 1920x1080 -vcodec h264 -i /dev/video0 -vcodec copy -f h264 - > test.mp4

# Working gstreamer:

$ gst-launch-1.0 -v -e v4l2src device=/dev/video0 ! queue !  video/x-h264,width=1920,height=1080,framerate=30/1 !  h264parse ! avdec_h264 ! xvimagesink sync=false

# Nonworking baresip:

$ baresip -ve /vidloop 

baresip v0.5.0 Copyright (C) 2010 - 2016 Alfred E. Heggestad et al.
Local network address:  IPv4=eth0:172.18.20.2 
ui: stdio
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aucodec: speex/32000/2
aucodec: speex/16000/2
aucodec: speex/8000/2
aucodec: speex/32000/1
aucodec: speex/16000/1
aucodec: speex/8000/1
aufilt: vumeter
aufilt: speex_aec
aufilt: speex_pp
ausrc: alsa
auplay: alsa
auplay: pulse
ausrc: pulse
h265: using x265 0.0 [Linux][GCC 6.3.0][64 bit] 8bit+10bit+12bit
vidcodec: H265
avcodec: using libavcodec H.264 encoder
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidcodec: VP8
vidfilt: selfview_window
vidfilt: vidinfo
v4l2_codec inited
vidcodec: H264
vidsrc: v4l2_codec
vidsrc: v4l2
vidisp: x11
vidcodec: H264
gst_video: using gstreamer (GStreamer 1.10.4)
medianat: stun
uuid: loaded UUID 804a8c85-b32f-92cd-4c37-684218605298 from file /home/nord/.baresip/uuid
nordhel@172.18.20.91: Using sipnat: `172.18.20.2'
Populated 1 account
module: loading app auloop.so
module: loading app contact.so
Populated 3 contacts
module: loading app debug_cmd.so
module: loading app dtmfio.so
module: loading app menu.so
module: loading app vidloop.so
Populated 8 audio codecs
Populated 3 audio filters
Populated 7 video codecs
Populated 2 video filters
baresip is ready.
vidloop: added video-filter `selfview_window'
vidloop: added video-filter `vidinfo'
vidloop: v4l2_codec,/dev/video0: open video source: 650 x 480 at 30 fps
v4l2_codec: video-source alloc (device=/dev/video0)
v4l2_codec: opening video-encoder device (device=/dev/video0)
v4l2_codec: Driver Caps:
  Driver:        "uvcvideo"
  Card:          "HD Pro Webcam C920"
  Bus:           "usb-0000:00:1d.0-1.4"
  Version:       4.0
  Capabilities:  0x84200001
  Formats:
     YUYV:    'YUYV 4:2:2'
  >  H264: C  'H.264'
     MJPG: C  'Motion-JPEG'

v4l2_codec: Selected Camera Mode:
  Width:   640
  Height:  480
  PixFmt:  H264
  Field:   1
vidloop: open video display (x11.nil)
ua: incoming OPTIONS message from sip:asterisk@172.18.20.91 (172.18.20.91:5060)
call: alloc with params laddr=172.18.20.2, af=AF_INET
call: use_video=1
nordhel@172.18.20.91: {0/UDP/v4} 200 OK (Heimdal Asterisk PBX) [1 binding]
[32mAll 1 useragent registered successfully! (220 ms)[;m
status: [] []  intra=0  EFPS=0.0      0 kbit/s       
status: [] []  intra=0  EFPS=0.0      0 kbit/s       
terminated by signal 2
ua: stop all (forced=0)
module: unloading app vidloop
v4l2_codec: encoder stats (keyframes:1, deltaframes:101)
module: unloading app menu
menu: close (redial current_attempts=0)
module: unloading app dtmfio
module: unloading app debug_cmd
module: unloading app contact
module: unloading app auloop
Stopping 1 useragent.. 
ua: sip-stack exit
ua exited -- stopping main runloop
/
/v
/vi
/vid
/vidl
/vidlo
/vidloo
/vidloop
Enable video-loop on v4l2_codec,/dev/video0: 650 x 480

# Configuration
$ grep -v '^[# ]' .baresip/config | grep -v "^$" >> .baresip/config

Local network address:  IPv4=eth0:172.18.20.2 
poll_method		epoll		# poll, select, epoll ..
sip_trans_bsize		128
sip_listen		172.18.20.2:5060
call_local_timeout	120
call_max_calls	4
audio_player		alsa,default
audio_source		alsa,default
audio_alert		alsa,default
audio_srate		8000-48000
audio_channels		1-2
video_source		v4l2_codec,/dev/video0
video_display		x11,nil
video_bitrate		9999999
video_fps		30
rtp_tos			184
rtp_ports		10000-20000
rtp_bandwidth		512-9999999 # [kbit/s]
rtcp_enable		yes
rtcp_mux		no
jitter_buffer_delay	5-10		# frames
rtp_stats		no
module_path		/usr/lib/baresip/modules
module			stdio.so
module			g711.so
module			speex.so
module			vumeter.so
module			speex_aec.so
module			speex_pp.so
module			alsa.so
module			pulse.so
module			h265.so
module			avcodec.so
module			vp8.so
module			selfview.so
module			vidinfo.so
module			v4l2_codec.so
module			v4l2.so
module			x11.so
module			gst_video1.so
module			stun.so
module_tmp		uuid.so
module_tmp		account.so
module_app		auloop.so
module_app		contact.so
module_app		debug_cmd.so
module_app		dtmfio.so
module_app		menu.so
module_app		vidloop.so
cons_listen		0.0.0.0:5555
http_listen		0.0.0.0:8000
evdev_device		/dev/input/event0
speex_quality		7 # 0-10
speex_complexity	7 # 0-10
speex_enhancement	0 # 0-1
speex_mode_nb		3 # 1-6
speex_mode_wb		6 # 1-6
speex_vbr		0 # Variable Bit Rate 0-1
speex_vad		0 # Voice Activity Detection 0-1
speex_agc_level		8000
opus_bitrate		28000 # 6000-510000
video_selfview		window # {window,pip}
selfview_size		100x100
ice_turn		no
ice_debug		no
ice_nomination		regular	# {regular,aggressive}
ice_mode		full	# {full,lite}

# ffmpeg --list-formats

$ ffmpeg -f v4l2 -list_formats all -i /dev/video0

ffmpeg version 2.7.2 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.2 (Debian 4.9.2-10)
  configuration: --enable-gpl --enable-postproc --enable-swscale --enable-avfilter --enable-shared --enable-pthreads --enable-nonfree
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
[video4linux2,v4l2 @ 0xfe9400] Raw       :     yuyv422 :           YUYV 4:2:2 : 640x480 160x90 160x120 176x144 320x180 320x240 352x288 432x240 640x360 800x448 800x600 864x480 960x720 1024x576 1280x720 1600x896 1920x1080 2304x1296 2304x1536
[video4linux2,v4l2 @ 0xfe9400] Compressed:        h264 :                H.264 : 640x480 160x90 160x120 176x144 320x180 320x240 352x288 432x240 640x360 800x448 800x600 864x480 960x720 1024x576 1280x720 1600x896 1920x1080
[video4linux2,v4l2 @ 0xfe9400] Compressed:       mjpeg :          Motion-JPEG : 640x480 160x90 160x120 176x144 320x180 320x240 352x288 432x240 640x360 800x448 800x600 864x480 960x720 1024x576 1280x720 1600x896 1920x1080
/dev/video0: Immediate exit requested
```

**Comment by alfredh** [comment]
hi @swedmike 

in your case the v4l2_codec is actually working:

```
v4l2_codec: encoder stats (keyframes:1, deltaframes:101)
```

but you did not start vidloop with a codec.

Can you try this:

```
$ baresip -mv4l2_codec.so -mavcodec.so -msdl2.so -e"/vidloop h264"
```

(Also note that v4l2_codec.so must be loaded _before_ avcodec.so)


/Alfred

**Comment by swedmike** [comment]
Thank you Alfred. Just adding h264 made no difference, but your other params did. This kind of works in the git version (only) but unfortunately the picture quality is very bad with too many artifacts to even recognise a human face. I got no sdl2.so in my baresip directory so maybe this is a related problem. I have not yet investigated why.

**Comment by swedmike** [comment]
Ok, problem is not related to SDL output. Antisip on my Android Samsung J5 (left) and baresip with unaccelerated v4l2 (right) both gives video output in baresip without artifacts: https://raw.githubusercontent.com/swedmike/randomstuff/master/antisip-baresip-v4l2-codec.png The v4l2_codec image is full of errors, but much faster: https://raw.githubusercontent.com/swedmike/randomstuff/master/baresip-v4l2.png

**Comment by alfredh** [comment]
Hi @swedmike 

can you please create a new ticket for your issue?

the original issue here was that only full frames was read, no delta frames.
Your issue is different.

Alfred

**Comment by mo8Zomo0** [comment]
Hi @alfredh,

I spend some time unsuccessful testing around till I found this thread.
An other thread mentioned a tip to delete the config file to let baresip generate 
one automatically which I did on the way.

But the "bare" config will have the avcodec before the video input definition.

.baresip# egrep "v4l|avco" config
video_source		v4l2_codec,/dev/video0
module			avcodec.so
#module			v4l.so
#module			v4l2.so
module			v4l2_codec.so

Is it possible to switch the position of these in the code, have it documented or at least make a comment so others do not run in the same issue? 

Not sure if I could have interpreted this in the start up dialog or if there could be more verbose info around that.

**Comment by alfredh** [comment]
yes we can do that.

could you please create a PR that implements your suggestion?

Alfred

**Comment by mo8Zomo0** [comment]
Hmm, I am new to git and co and not a programmer, ok, its only the config but not sure how to do it proper.
