### ISSUE TITLE
Can't build 0.5.4 release or git master due to error in ice module

### ISSUE THREAD

**Issue by stephenvharvey** [alfredh/baresip#284]
Building older releases works without issues but I am unable to build the 0.5.4 release or git master:

`CC [M]  build-x86_64/modules/ice/ice.o
modules/ice/ice.c: In function 'call_gather_handler':
modules/ice/ice.c:104:2: warning: implicit declaration of function 'icem_cand_redund_elim'; did you mean 'ice_cand_encode'? [-Wimplicit-function-declaratio ]
  icem_cand_redund_elim(m->icem);
  ^~~~~~~~~~~~~~~~~~~~~
  ice_cand_encode
modules/ice/ice.c:104:2: warning: nested extern declaration of 'icem_cand_redund_elim' [-Wnested-externs]
modules/ice/ice.c:106:8: warning: implicit declaration of function 'icem_comps_set_default_cand'; did you mean 'icem_lite_set_default_candidates'? [-Wimplicit-function-declaration]
  err = icem_comps_set_default_cand(m->icem);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
        icem_lite_set_default_candidates
modules/ice/ice.c:106:8: warning: nested extern declaration of 'icem_comps_set_default_cand' [-Wnested-externs]
modules/ice/ice.c: In function 'stun_resp_handler':
modules/ice/ice.c:135:10: warning: implicit declaration of function 'icem_cand_find'; did you mean 'icem_cand_add'? [-Wimplicit-function-declaration]
  lcand = icem_cand_find(icem_lcandl(m->icem), comp->id, NULL);
          ^~~~~~~~~~~~~~
          icem_cand_add
modules/ice/ice.c:135:10: warning: nested extern declaration of 'icem_cand_find' [-Wnested-externs]
modules/ice/ice.c:135:8: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  lcand = icem_cand_find(icem_lcandl(m->icem), comp->id, NULL);
        ^
modules/ice/ice.c:148:8: warning: implicit declaration of function 'icem_lcand_add'; did you mean 'icem_cand_add'? [-Wimplicit-function-declaration]
  err = icem_lcand_add(m->icem, icem_lcand_base(lcand),
        ^~~~~~~~~~~~~~
        icem_cand_add
modules/ice/ice.c:148:8: warning: nested extern declaration of 'icem_lcand_ad ' [-Wnested-externs]
modules/ice/ice.c:148:32: warning: implicit declaration of function 'icem_lcand_base'; did you mean 'icem_cand_add'? [-Wimplicit-function-declaration]
  err = icem_lcand_add(m->icem, icem_lcand_base(lcand),
                                ^~~~~~~~~~~~~~~
                                icem_cand_add
modules/ice/ice.c:148:32: warning: nested extern declaration of 'icem_lcand_base' [-Wnested-externs]
modules/ice/ice.c: In function 'send_binding_request':
modules/ice/ice.c:167:37: warning: implicit declaration of function 'icem_stu '; did you mean 'inet_pton'? [-Wimplicit-function-declaration]
  err = stun_request(&comp->ct_gath, icem_stun(m->icem), IPPROTO_UDP,
                                     ^~~~~~~~~
                                     inet_pton
modules/ice/ice.c:167:37: warning: nested extern declaration of 'icem_stun' [-Wnested-externs]
modules/ice/ice.c:167:37: warning: passing argument 2 of 'stun_request' makes pointer from integer without a cast [-Wint-conversion]
In file included from /usr/include/re/re.h:51:0,
                 from modules/ice/ice.c:10:
/usr/include/re/re_stun.h:187:6: note: expected 'struct stun *' but argument is of type 'int'
 int  stun_request(struct stun_ctrans **ctp, struct stun *stun, int proto,
      ^~~~~~~~~~~~
modules/ice/ice.c: In function 'turnc_handler':
modules/ice/ice.c:195:3: warning: implicit declaration of function 'icem_set_turn_client'; did you mean 'video_set_orient'? [-Wimplicit-function-declaratio ]
   icem_set_turn_client(m->icem, comp->id, NULL);
   ^~~~~~~~~~~~~~~~~~~~
   video_set_orient
modules/ice/ice.c:195:3: warning: nested extern declaration of 'icem_set_turn_client' [-Wnested-externs]
modules/ice/ice.c:216:8: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  lcand = icem_cand_find(icem_lcandl(m->icem), comp->id, NULL);
        ^
modules/ice/ice.c:220:21: warning: implicit declaration of function 'icem_lcand_addr'; did you mean 'icem_cand_add'? [-Wimplicit-function-declaration]
  if (!sa_cmp(relay, icem_lcand_addr(icem_lcand_base(lcand)), SA_ALL)) {
                     ^~~~~~~~~~~~~~~
                     icem_cand_add
modules/ice/ice.c:220:21: warning: nested extern declaration of 'icem_lcand_addr' [-Wnested-externs]
modules/ice/ice.c:220:21: warning: passing argument 2 of 'sa_cmp' makes pointer from integer without a cast [-Wint-conversion]
In file included from /usr/include/re/re.h:20:0,
                 from modules/ice/ice.c:10:
/usr/include/re/re_sa.h:56:10: note: expected 'const struct sa *' but argument is of type 'int'
 bool     sa_cmp(const struct sa *l, const struct sa *r, int flag);
          ^~~~~~
modules/ice/ice.c: In function 'cand_gather_relayed':
modules/ice/ice.c:245:38: warning: passing argument 1 of 'stun_conf' makes pointer from integer without a cast [-Wint-conversion]
  err = turnc_alloc(&turnc, stun_conf(icem_stun(m->icem)),
                                      ^~~~~~~~~
In file included from /usr/include/re/re.h:51:0,
                 from modules/ice/ice.c:10:
/usr/include/re/re_stun.h:179:19: note: expected 'struct stun *' but argument is of type 'int'
 struct stun_conf *stun_conf(struct stun *stun);
                   ^~~~~~~~~
modules/ice/ice.c: At top level:
modules/ice/ice.c:293:12: error: conflicting types for 'icem_gather_srflx'
 static int icem_gather_srflx(struct mnat_media *m)
            ^~~~~~~~~~~~~~~~~
In file included from /usr/include/re/re.h:33:0,
                 from modules/ice/ice.c:10:
/usr/include/re/re_ice.h:77:6: note: previous declaration of 'icem_gather_srflx' was here
 int  icem_gather_srflx(struct icem *icem, const struct sa *stun_srv);
      ^~~~~~~~~~~~~~~~~
modules/ice/ice.c:302:12: error: conflicting types for 'icem_gather_relay'
 static int icem_gather_relay(struct mnat_media *m,
            ^~~~~~~~~~~~~~~~~
In file included from /usr/include/re/re.h:33:0,
                 from modules/ice/ice.c:10:
/usr/include/re/re_ice.h:78:6: note: previous declaration of 'icem_gather_relay' was here
 int  icem_gather_relay(struct icem *icem, const struct sa *stun_srv,
      ^~~~~~~~~~~~~~~~~
modules/ice/ice.c: In function 'ice_start':
modules/ice/ice.c:763:6: warning: implicit declaration of function 'ice_candpair_set_states'; did you mean 'ice_cand_attr_decode'? [-Wimplicit-function-declaration]
      ice_candpair_set_states(m->icem);
      ^~~~~~~~~~~~~~~~~~~~~~~
      ice_cand_attr_decode
modules/ice/ice.c:763:6: warning: nested extern declaration of 'ice_candpair_set_states' [-Wnested-externs]
modules/ice/ice.c: In function 'media_alloc':
modules/ice/ice.c:799:29: error: incompatible type for argument 2 of 'icem_alloc'
  err = icem_alloc(&m->icem, ice.mode, sess->offerer,
                             ^~~
In file included from /usr/include/re/re.h:33:0,
                 from modules/ice/ice.c:10:
/usr/include/re/re_ice.h:71:6: note: expected 'struct ice *' but argument is of type 'enum ice_mode'
 int  icem_alloc(struct icem **icemp, struct ice *ice, int proto, int layer,
      ^~~~~~~~~~
modules/ice/ice.c:801:5: warning: passing argument 6 of 'icem_alloc' makes pointer from integer without a cast [-Wint-conversion]
     sess->tiebrk, sess->lufrag, sess->lpwd,
     ^~~~
In file included from /usr/include/re/re.h:33:0,
                 from modules/ice/ice.c:10:
/usr/include/re/re_ice.h:71:6: note: expected 'void (*)(int,  _Bool,  void *)' but argument is of type 'uint64_t {aka long unsigned int}'
 int  icem_alloc(struct icem **icemp, struct ice *ice, int proto, int layer,
      ^~~~~~~~~~
modules/ice/ice.c:799:8: error: too many arguments to function 'icem_alloc'
  err = icem_alloc(&m->icem, ice.mode, sess->offerer,
        ^~~~~~~~~~
In file included from /usr/include/re/re.h:33:0,
                 from modules/ice/ice.c:10:
/usr/include/re/re_ice.h:71:6: note: declared here
 int  icem_alloc(struct icem **icemp, struct ice *ice, int proto, int layer,
      ^~~~~~~~~~
modules/ice/ice.c:806:2: warning: implicit declaration of function 'icem_conf'; did you mean 'ice_conf'? [-Wimplicit-function-declaration]
  icem_conf(m->icem)->nom   = ice.nom;
  ^~~~~~~~~
  ice_conf
modules/ice/ice.c:806:2: warning: nested extern declaration of 'icem_conf' [-Wnested-externs]
modules/ice/ice.c:806:20: error: invalid type argument of '->' (have 'int')
  icem_conf(m->icem)->nom   = ice.nom;
                    ^~
modules/ice/ice.c:807:20: error: invalid type argument of '->' (have 'int')
  icem_conf(m->icem)->debug = ice.debug;
                    ^~
modules/ice/ice.c: In function 'sdp_attr_handler':
modules/ice/ice.c:841:24: warning: passing argument 1 of 'ice_sdp_decode' from incompatible pointer type [-Wincompatible-pointer-types]
   (void)ice_sdp_decode(m->icem, name, value);
                        ^
In file included from /usr/include/re/re.h:33:0,
                 from modules/ice/ice.c:10:
/usr/include/re/re_ice.h:62:6: note: expected 'struct ice *' but argument is of type 'struct icem *'
 int  ice_sdp_decode(struct ice *ice, const char *name, const char *value);
      ^~~~~~~~~~~~~~
make: *** [mk/mod.mk:44: build-x86_64/modules/ice/ice.o] Error 1
`

**Comment by alfredh** [comment]
unfortunately I had to break the ICE api for some refactoring.

baresip 0.5.4 -> need libre 0.5.4
baresip git -> need libre git


/Alfred

**Comment by stephenvharvey** [comment]
Ah, ok - thanks!
