### ISSUE TITLE
Baresip does not install properly

### ISSUE THREAD

**Issue by dvizma** [alfredh/baresip#287]
Hi,

I am trying to install baresip on Linkit Smart 7688. However, after installation no .baresip folder is created. I get the following error

Configuring libre.
Configuring librem.
Configuring baresip.
baresip v0.4.12 Copyright (C) 2010 - 2014 Alfred E. Heggestad et al.
conf: could not get config path: No such file or directory
main: configure failed: No such file or directory

I have been stuck here for past few days, tried all versions of firmware. Kindly help

**Comment by jungle-boogie** [comment]
> baresip v0.4.12 

If that's really the version number, I'd say upgrade. Build baresip, re and rem from source if your OS package doesn't have something more recent.

**Comment by alfredh** [comment]
can you please share which command you used to install it ?

please try to force install it, and then start it with a specific config folder:

```
$ baresip -f /tmp
```

/Alfred
