### ISSUE TITLE
how to setup video call

### ISSUE THREAD

**Issue by jimverwu** [alfredh/baresip#288]
### the type of these two device as follow:
baresip@baresip-virtual-machine:~$ v4l2-ctl --device=/dev/video0 --list-formats
ioctl: VIDIOC_ENUM_FMT
    Index       : 0
    Type        : Video Capture
    Pixel Format: 'MJPG' (compressed)
    Name        : Motion-JPEG

    Index       : 1
    Type        : Video Capture
    Pixel Format: 'YUYV'
    Name        : YUYV 4:2:2

baresip@baresip-virtual-machine:~$ v4l2-ctl --device=/dev/video1 --list-formats
ioctl: VIDIOC_ENUM_FMT
    Index       : 0
    Type        : Video Capture
    Pixel Format: 'H264' (compressed)
    Name        : H.264

### I used two configuration. the first is :
```
# Video
video_source        v4l2_codec,/dev/video1
video_display        x11,nil
video_size        352x288
video_bitrate        512000
video_fps        25


# Video codec Modules (in order)
module            v4l2_codec.so
module            avcodec.so
module            vpx.so
```

### when i running vidloop. it info as follow:
baresip v0.4.20 Copyright (C) 2010 - 2016 Alfred E. Heggestad et al.
Local network address:  IPv4=ens33:192.168.0.127 
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
ausrc: alsa
auplay: alsa
v4l2_codec inited
vidcodec: H264
vidsrc: v4l2_codec
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidsrc: v4l2
vidisp: x11
medianat: stun
medianat: turn
medianat: ice
Populated 1 account
Populated 3 contacts
Populated 2 audio codecs
Populated 1 audio filter
Populated 4 video codecs
Populated 0 video filters
baresip is ready.
Enable video-loop on v4l2_codec,/dev/video1: 352 x 288
vidloop: v4l2_codec,/dev/video1: open video source: 352 x 288 at 25 fps
v4l2_codec: Driver Caps:
  Driver:        "uvcvideo"
  Card:          "2M WebCam"
  Bus:           "usb-0000:02:03.0-1"
  Version:       4.0
  Capabilities:  0x84200001
  Formats:
     MJPG: C  'Motion-JPEG'
     YUYV:    'YUYV 4:2:2'

v4l2_codec: Doesn't support H264.
v4l2_codec: encoder stats (keyframes:0, deltaframes:0)
vidloop: vidsrc '/dev/video1' failed: No such device
vidloop: alloc: No such device

### the second configuration is:
```
# Video
video_source        v4l2,/dev/video0
video_display        x11,nil
video_size        352x288
video_bitrate        512000
video_fps        25

# Video codec Modules (in order)
#module            v4l2_codec.so
module            avcodec.so
module            vpx.so
```

### and vidloop info as follow:
baresip v0.4.20 Copyright (C) 2010 - 2016 Alfred E. Heggestad et al.
Local network address:  IPv4=ens33:192.168.0.127 
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
ausrc: alsa
auplay: alsa
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidsrc: v4l2
vidisp: x11
medianat: stun
medianat: turn
medianat: ice
Populated 1 account
Populated 3 contacts
Populated 2 audio codecs
Populated 1 audio filter
Populated 3 video codecs
Populated 0 video filters
baresip is ready.
Enable video-loop on v4l2,/dev/video0: 352 x 288
vidloop: v4l2,/dev/video0: open video source: 352 x 288 at 25 fps
v4l2: /dev/video0: found valid V4L2 device (320 x 180) pixfmt=YUYV
v4l2: Current input: "Camera 1"
vidloop: open video display (x11.nil)
status: [] [] EFPS=0.0      0 kbit/s

**Comment by alfredh** [comment]
version 0.4.20 is now old, please upgrade to latest (version 0.5.4)

* for pixel-format YUYV you should use `v4l2.so`
* for H.264 you should use `v4l2_codec.so`

can you please share more information about your OS and
the hardware info of you web camera(s) ?

does your webcams work with other programs ?


/Alfred

**Comment by jimverwu** [comment]
My OS is ubuntu 17.04 running on VMware virtual machine. The webcam is a HW H.264 supported uvc camera. 

Yes the webcams can work with pjsip and xlite et.al.

I will try upgrade to version 0.5.4. I am not familiar with linux. Hope it won't take much time.

**Comment by jimverwu** [comment]
@alfredh 
### I have upgraded to 0.5.4. The video does not display too. 

### for /dev/video0, I use configuration as follow
```
# Video
video_source           v4l2,/dev/video0
video_display           x11,nil
video_size              352x288
#video_bitrate          256
video_bitrate           500000
video_fps               25
video_fullscreen                yes

#Video source module
module                v4l2.so
```
### baresip display:
/vidloop
Enable video-loop on v4l2,/dev/video0: 352 x 288
vidloop: added video-filter `selfview_window'
vidloop: open video display (x11.nil)
vidloop: v4l2,/dev/video0: open video source: 352 x 288 at 25 fps
v4l2: /dev/video0: found valid V4L2 device (320 x 180) pixfmt=YUYV
v4l2: Current input: "Camera 1"
main: long async blocking: 432>100 ms (h=0x7fe448b35dd9 arg=0x55f3f1f3cc10)
Quitus: [] []  intra=0  EFPS=0.0      0 kbit/s


### for /dev/video1, I use configuration as follow:
```
# Video
video_source           v4l2_codec,/dev/video1
video_display           x11,nil
video_size              352x288
#video_bitrate          256
video_bitrate           500000
video_fps               25
video_fullscreen                yes

#Video source module
module                v4l2_codec.so
```

### baresip display: 
/vidloop
Enable video-loop on v4l2_codec,/dev/video1: 352 x 288
vidloop: open video display (x11.nil)
vidloop: v4l2_codec,/dev/video1: open video source: 352 x 288 at 25 fps
v4l2_codec: Driver Caps:
  Driver:        "uvcvideo"
  Card:          "USB 2.0 Camera"
  Bus:           "usb-0000:02:03.0-1"
  Version:       4.0
  Capabilities:  0x84200001
  Formats:
  >  H264: C  'H.264'

v4l2_codec: Selected Camera Mode:
  Width:   320
  Height:  180
  PixFmt:  H264
  Field:   1
main: long async blocking: 701>100 ms (h=0x7f559e9a7dd9 arg=0x561f233e3c10)
reg: sip:10002@192.168.1.211: Register: Connection timed out
status: [] []  intra=0  EFPS=0.0      0 kbit/s

### I used cheese to test my camera.  cheese can display video.

### Is there anything missing in the configuration file?

**Comment by alfredh** [comment]
when using the v4l2_codec module you must specify a video-codec in vidloop command:

```
/vidloop h264
```

and make sure a video-decoder (such as avcodec.so) is loaded, after v4l2_codec.so

It looks like you are getting zero video frames, perhaps there is 
a problem with the VMware setup?

**Comment by jimverwu** [comment]
I found these and tested, but there was no video.
The vmware should has no problem. because cheese can display the video. 
I will try to read the source code. 
Thank you very much!

**Comment by jimverwu** [comment]
Hi, alfredh

It just because i load avcodec.so before v4l2_codec.so. When I changed the order of these two modules. The video is displayed!
Thank you very much!
