### ISSUE TITLE
baresip throws segmentation fault after answering a call

### ISSUE THREAD

**Issue by stephenvharvey** [alfredh/baresip#289]
Platform: ARM;  4.1.21 kernel using baresip git with v4l2_codec
The system is configured to automaticly answer calls. After picking up a call I sometimes get a segfault/core dump and sometimes everything works as expected (roughly 50/50). If calling from baresip instead of answering, this never happens.

```
v4l2_codec: Selected Camera Mode:
  Width:   1920
  Height:  1080
  PixFmt:  H264
  Field:   1

Program received signal SIGSEGV, Segmentation fault.
0x76ded7f4 in memcpy () from /lib/libc.so.6
(gdb) bt
#0  0x76ded7f4 in memcpy () from /lib/libc.so.6
#1  0x76fac858 in mbuf_write_mem () from /usr/lib/libre.so
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 

```

**Comment by alfredh** [comment]
hmm, a bit difficult to see where this is coming from.

could you perhaps add a bunch of re_printf around the relevant code
and try to nail down where it crashes ?

**Comment by alfredh** [comment]
please re-open if you can provide more info.

Alfred
