### ISSUE TITLE
How can I print options message ?

### ISSUE THREAD

**Issue by MoustafaMohA** [alfredh/baresip#294]
How can I print options message from baresip ?

**Comment by alfredh** [comment]
which OPTIONS message do you mean?

1. when sending OPTIONS, printing the received 200 OK reply ?
2. the incoming OPTIONS message received ?

when sending OPTIONS you can see the reply when it arrives:

```
/options music
----- OPTIONS of sip:music@iptel.org -----
SIP/2.0 200 OK
Via: SIP/2.0/TCP 192.168.100.216:50528;branch=z9hG4bK2d9ad247bfec597f;rport=50530;received=138.62.237.156
To: <sip:music@iptel.org>;tag=3E8CB89C-59B3C0BB000B2A87-24821700
From: <sip:aeh@iptel.org>;tag=f86b7cf8cc4c2ef5
Call-ID: 3977b13c1d7fae86
CSeq: 15205 OPTIONS
Server: Sip Express Media Server (1.1.1-aefe2 (x86_64/linux))
X-Call-ID: 1585B7C0-59B3C0BB000B2CBC-24821700
Contact: <sip:3E8CB89C-59B3C0BB000B2A87-24821700@212.79.111.155;transport=tcp>
Content-Length: 0
```

**Comment by MoustafaMohA** [comment]
The incoming OPTIONS message, a server will send me the call quality test result in the options message.
(I am mean by incoming, as a user using Baresip for SIP account registration with that server)

**Comment by lmangani** [comment]
Do you have some examples of such report headers?

**Comment by alfredh** [comment]
you can catch the incoming OPTIONS message here, in ua.c:

```
static void handle_options(struct ua *ua, const struct sip_msg *msg)
{
	struct sip_contact contact;
	struct call *call = NULL;
	struct mbuf *desc = NULL;
	const struct sip_hdr *hdr;
	bool accept_sdp = true;
	int err;

	debug("ua: incoming OPTIONS message from %r (%J)\n",
	      &msg->from.auri, &msg->src);

	/* application/sdp is the default if the
	   Accept header field is not present */
	hdr = sip_msg_hdr(msg, SIP_HDR_ACCEPT);
	if (hdr) {
		accept_sdp = 0==pl_strcasecmp(&hdr->val, "application/sdp");
	}
```

you can print out a specific header if you want, or the whole message.

**Comment by MoustafaMohA** [comment]
Yes, I think that's going to be very useful.

**Comment by MoustafaMohA** [comment]
Sorry for re opening the issue again I tried to solve it but it seems that I am stuck again.

This is the OPTIONS message that's supposed to be sent by the server


`OPTIONS sip:s@IP:port;transport=TLS SIP/2.0
Via: SIP/2.0/TLS ip:port;branch=z9hG4bKccoblg104ge52upcvgj0.1
To: sip:sip@domain.com
From: <sip:sip@domain>;tag=SDk3rf702-84bd981afba0c568c19eb364827595be-5fce
CSeq: 10 OPTIONS
Call-ID: SDk3rf702-1719722929c9170d33e52543be0412f6-06ab0k0
Max-Forwards: 68
Content-Length: 120
User-Agent: VLT TEAMING
Content-Type: text
 
'callid'='ID'
'duration'='19'
'Preceived'='848'
'Plost'='0'
'QOS'='45'`

I tried `/options sipAccount` 
the output I get  
`/options music
----- OPTIONS of sip:music@iptel.org -----
SIP/2.0 200 OK
Via: SIP/2.0/TCP 192.168.100.216:50528;branch=z9hG4bK2d9ad247bfec597f;rport=50530;received=138.62.237.156
To: <sip:music@iptel.org>;tag=3E8CB89C-59B3C0BB000B2A87-24821700
From: <sip:music@iptel.org>;tag=f86b7cf8cc4c2ef5
Call-ID: 3977b13c1d7fae86
CSeq: 15205 OPTIONS
Server: Sip Express Media Server (1.1.1-aefe2 (x86_64/linux))
X-Call-ID: 1585B7C0-59B3C0BB000B2CBC-24821700
Contact: <sip:3E8CB89C-59B3C0BB000B2A87-24821700@212.79.111.155;transport=tcp>
Content-Length: 0`


I used the example you used to declare that To and From fields are the same value, which is the sip account I am registered with.
