### ISSUE TITLE
libbaresip.so: Name collision of error() with glibc

### ISSUE THREAD

**Issue by strfry** [alfredh/baresip#295]
Hello,

I found a nasty problem, debugging my application that uses libbaresip.so from Python code.
It appears, there is a function in glibc of the name error(), with different parameters and behaviour. While baresip's error() just prints a message with a different log level than warning, the glibc one takes different paramters and terminates the program.
So when libbaresip.so is dynamically loaded by a program that already linked to glibc, the wrong function will be called, and the program terminates (or crashes) with a confusing message.

Maybe be there is some linker magic to work around this problem, but probably the portable solution is to consistently rename the function in all of baresip.

Let me know what you think.

Regards,
Jonathan

**Comment by alfredh** [comment]
thanks for finding and reporting the issue.

these log functions are available in baresip:

```
void debug(const char *fmt, ...);
void info(const char *fmt, ...);
void warning(const char *fmt, ...);
void error(const char *fmt, ...);
```

the `error` function is only supposed to be used in extremely serious
cases, such as assert/abort or when the program cannot continue.

we can rename `error` if you can suggest a good name :)
I dont think we should rename all functions.


/Alfred
