### ISSUE TITLE
H264 stream gets decoded and encoded again before sending the video

### ISSUE THREAD

**Issue by kemotz** [alfredh/baresip#296]
Hi,

When I setup a baresip (0.5.4) to use a H264 mp4 file or rstp H264 stream as a video source via avformat, the H264 gets decoded and encoded back to H264. The video stream is smooth however this behaviour leads to high cpu utilization that is pointless. Is it possible to bypass the decoding/encoding and send H264 frames directly over the network?

Thanks,
Tomek.

>> Config <<
#
# baresip configuration
#

#------------------------------------------------------------------------------

# Core
poll_method		epoll		# poll, select, epoll ..

# SIP
sip_trans_bsize		128
sip_listen		192.168.1.10:5060
#sip_certificate	cert.pem

# Call
call_local_timeout	120
call_max_calls	4

# Audio
#audio_path		/usr/share/baresip
audio_player		alsa,default
audio_source		alsa,default
audio_alert		alsa,default
audio_srate		8000-48000
audio_channels		1-2
#ausrc_srate		48000
#auplay_srate		48000
#ausrc_channels		0
#auplay_channels		0

# Video
video_source		avformat,/home/tomek/mov.mp4
#video_display		x11,nil
#video_size		352x288
video_bitrate		500000
video_fps		25

# AVT - Audio/Video Transport
rtp_tos			184
#rtp_ports		10000-20000
#rtp_bandwidth		512-1024 # [kbit/s]
rtcp_enable		yes
rtcp_mux		no
jitter_buffer_delay	5-10		# frames
rtp_stats		no
#rtp_timeout		60

# Network
#dns_server		10.0.0.1:53
#net_interface		enp0s3

# BFCP
#bfcp_proto		udp

#------------------------------------------------------------------------------
# Modules

module_path		/home/tomek/baresip

# UI Modules
module			stdio.so
#module			cons.so
#module			evdev.so
#module			httpd.so

# Audio codec Modules (in order)
#module			opus.so
#module			silk.so
#module			amr.so
#module			g7221.so
#module			g722.so
#module			g726.so
module			g711.so
#module			gsm.so
#module			l16.so
#module			speex.so
#module			bv32.so
#module			mpa.so
#module			codec2.so
#module			ilbc.so
#module			isac.so

# Audio filter Modules (in encoding order)
module			vumeter.so
#module			sndfile.so
#module			speex_aec.so
#module			speex_pp.so
#module			plc.so

# Audio driver Modules
module			alsa.so
#module			pulse.so
#module			jack.so
#module			portaudio.so
#module			aubridge.so
#module			aufile.so

# Video codec Modules (in order)
module			avcodec.so
#module			vp8.so
#module			vp9.so
#module			h265.so

# Video filter Modules (in encoding order)
#module			selfview.so
#module			snapshot.so
#module			swscale.so
#module			vidinfo.so

# Video source modules
#module			v4l.so
#module			v4l2.so
#module			v4l2_codec.so
module			avformat.so
#module			x11grab.so
#module			cairo.so
#module			vidbridge.so

# Video display modules
#module			directfb.so
#module			x11.so
#module			sdl2.so
#module			fakevideo.so

# Audio/Video source modules
#module			rst.so
#module			gst1.so
#module			gst_video1.so

# Media NAT modules
module			stun.so
module			turn.so
module			ice.so
#module			natpmp.so

# Media encryption modules
#module			srtp.so
#module			dtls_srtp.so
#module			zrtp.so

#------------------------------------------------------------------------------
# Temporary Modules (loaded then unloaded)

module_tmp		uuid.so
module_tmp		account.so

#------------------------------------------------------------------------------
# Application Modules

module_app		auloop.so
module_app		contact.so
module_app		debug_cmd.so
module_app		dtmfio.so
#module_app		echo.so
#module_app			gtk.so
module_app		menu.so
#module_app		mwi.so
#module_app		natbd.so
#module_app		presence.so
#module_app		syslog.so
module_app		vidloop.so

#------------------------------------------------------------------------------
# Module parameters

cons_listen		0.0.0.0:5555

http_listen		0.0.0.0:8000

evdev_device		/dev/input/event0

# Speex codec parameters
speex_quality		7 # 0-10
speex_complexity	7 # 0-10
speex_enhancement	0 # 0-1
speex_mode_nb		3 # 1-6
speex_mode_wb		6 # 1-6
speex_vbr		0 # Variable Bit Rate 0-1
speex_vad		0 # Voice Activity Detection 0-1
speex_agc_level		8000

# Opus codec parameters
opus_bitrate		28000 # 6000-510000

# Selfview
video_selfview		window # {window,pip}
#selfview_size		64x64

# ICE
ice_turn		no
ice_debug		no
ice_nomination		regular	# {regular,aggressive}
ice_mode		full	# {full,lite}

# Menu
#redial_attempts		3 # Num or <inf>
#redial_delay		5 # Delay in seconds

>> Config <<

**Comment by kemotz** [comment]
The same can be observed with rtsp stream:

video_source		avformat,rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov

**Comment by alfredh** [comment]
passthrough of H.264 is currently not supported, the baresip video architecture
is not designed for that.

what if the SIP endpoint is using a different codec, such as H.263 or VP8 ?

you can try to implement a hybrid module with avformat+avcodec, where
the raw H.264 frames are packetized and sent out via RTP. this is similar
to how the v4l2_codec module works.


/Alfred

**Comment by kemotz** [comment]
Hi Alfred,

Thanks for looking into this. 
I think that h264 IP cameras are so spread today and quite cheap (~$10-15) hence implementing this feature makes a lot of sense for the embedded systems, like e.g. door bell video phone. BareSIP could run on cheap HW like RPI or OPI and be far from the camera itself (not doable with USB).
I have taken a look into the code of avcodec and avformat, made sense out of it on how it works (encoding/decoding) but unfortunately it is beyond my capabilities to implement a module to perform the h264 passthrough.

Maybe it would be a good idea to add it to the roadmap ? ;-)

I have also seen the similar bug opened https://github.com/alfredh/baresip/issues/160 and @koman-maciej mentioned his hack, but not shared the solution unfortunately.

Anyways ... as this is not a bug but rather a feature request I believe it an be closed ...

Cheers,
Tomek.

**Comment by alfredh** [comment]
thanks for your insight, I agree with you :)

I updated the roadmap with your suggestions, other people have also asked about
the same in the past:

https://github.com/alfredh/baresip/wiki/Roadmap

we will consider implementing this at some point.

Please close the ticket (Issue tracker is mainly for defects/bugs).


/Alfred

**Comment by kemotz** [comment]
Thanks Alfred!
