### ISSUE TITLE
add support for Session Timers (RFC 4028)

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#297]

**Comment by alfredh** [comment]
Hi @juha-h 

I have added this to the Baresip Roadmap:

https://github.com/alfredh/baresip/wiki/Roadmap

personally I will not have any time to implement this very soon.
are you or anyone else planning to implement it ?

/Alfred

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I have added this to the Baresip Roadmap:
> 
> https://github.com/alfredh/baresip/wiki/Roadmap
> 
> personally I will not have any time to implement this very soon.
> are you or anyone else planning to implement it ?

Thanks. Session Timers is not very easy to implement, since there is the
negotiation process involving minimum timer as well as who is the active
party.

-- Juha

**Comment by alfredh** [comment]
I would like to keep the Issues list for defects and small tasks.

Let's reopen this issue when we start working on Session Timers.
(it is already on the Roadmap)

/alfred
