### ISSUE TITLE
Error: While making call

### ISSUE THREAD

**Issue by anug7** [alfredh/baresip#299]
I am getting an error while making call.

> <sip_uri>: session closed: Function not implemented

I am able to accept call successfully. 

Could anyone point me where could be the issue?. I am adding the config file for reference.
[config.txt](https://github.com/alfredh/baresip/files/1303082/config.txt)

**Comment by alfredh** [comment]
Please see here for an explanation about how to make outgoing calls:

https://github.com/alfredh/baresip/issues/298


/Alfred
