### ISSUE TITLE
un-registration at quit

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#30]
When quitting baresip, make somehow sure that UAs are not unregistered before mwi and presence un-SUBSCRIBE NOTIFY requests have had change to reach the UAs.

**Comment by juha-h** [comment]
I'm returning to this old issue.  The hack below to src/ua.c delays un-registration by 1 second that is normally enough to allow un-subscribe notifys to reach the UA.  Is a real fix possible in baresip architecture?  I imagine that at quit un-registration should  be triggered when all un-subscribes (if any) have been completed or when a timeout occurs.

diff --git a/src/ua.c b/src/ua.c
index ccbb9f3..598cab6 100644
--- a/src/ua.c
+++ b/src/ua.c
@@ -77,6 +77,7 @@ static struct {
 #endif
 };
 
+static struct tmr tmr;
 
 /* prototypes */
 static int  ua_call_alloc(struct call **callp, struct ua *ua,
@@ -1166,6 +1167,8 @@ int ua_init(const char *software, bool udp, bool tcp, bool tls,
    uint32_t bsize;
    int err;
 
+   tmr_init(&tmr);
+
    uag.cfg = &cfg->sip;
    bsize = cfg->sip.trans_bsize;
 
@@ -1229,6 +1232,20 @@ int ua_init(const char *software, bool udp, bool tcp, bool tls,
 
 
 /**
+ * Stop user agents after delay in order to allow un-publishes and
+ * un-subscribes to complete
+ */
+static void tmr_handler(void *arg)
+{
+   (void)arg;
+
+   list_flush(&uag.ual);
+   sip_close(uag.sip, false);
+   tmr_cancel(&tmr);
+}
+
+
+/**
  * Close all active User-Agents
  */
 void ua_close(void)
@@ -1260,6 +1277,12 @@ void ua_close(void)
  */
 void ua_stop_all(bool forced)
 {
+   unsigned int need_some_sleep;
+
+   need_some_sleep = mod_find("mwi.so") || mod_find("presence.so");
+   if (forced || !need_some_sleep)
+       tmr_cancel(&tmr);
+
    module_app_unload();
 
    if (!list_isempty(&uag.ual)) {
@@ -1268,12 +1291,15 @@ void ua_stop_all(bool forced)
             n, n==1 ? "" : "s", forced ? "(Forced)" : "");
    }
 
-   if (forced)
+   if (forced) {
        sipsess_close_all(uag.sock);
-   else
+       sip_close(uag.sip, true);
+   } else if (need_some_sleep)
+       tmr_start(&tmr, 1000, tmr_handler, NULL);
+   else {
        list_flush(&uag.ual);
-
-   sip_close(uag.sip, forced);
+       sip_close(uag.sip, false);
+   }
 }

**Comment by alfredh** [comment]
hey Juha, I am looking into finding a proper solution for this, it should be possible ..

I think that we should try to avoid code in the Baresip core, that loads or looks for 
a specific module (like mod_find("mwi")).

If I understand you correctly, you would like all the subsystems in baresip using
SUBSCRIBE to un-SUBSCRIBE on quit before we do un-REGISTER? This is to make sure
that your registrar still has a location entry, which things are being un-SUBSCRIBED
and NOTIFY sent to that client ?

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> If I understand you correctly, you would like all the subsystems in
> baresip using 
> SUBSCRIBE to un-SUBSCRIBE on quit before we do un-REGISTER? This is to
> make sure 
> that your registrar still has a location entry, which things are being
> un-SUBSCRIBED 
> and NOTIFY sent to that client ?

Exactly.  Currently NOTIFY to un-SUBSCRIBE (wmi or presence) does not
reach the client, because it has already un-REGISTERED.  So it should
somehow be possible to delay un-REGISTER until un-SUBSCRIBE completed
event has been received.

-- Juha

**Comment by alfredh** [comment]
aha, I understand the issue now.

so maybe the same should be true also for the inverse sequence,
i.e. REGISTER and subsequent SUBs ?

Startup:

1. REGISTER/200 OK
2. SUBSCRIBE various services like presence,mwi


Shutdown:

1. un-SUBSCRIBE all services
2. wait for un-SUB to reply with 200 OK (or a small timeout).
3. un-REGISTER

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> Startup:
> 
> 1. REGISTER/200 OK
> 2. SUBSCRIBE various services like presence,mwi
> 
> 
> Shutdown:
> 
> 1. un-SUBSCRIBE all services
> 2. wait for un-SUB to reply with 200 OK (or a small timeout).
> 3. un-REGISTER

Yes, but with the addition that after presence server replies to
un-SUBSCRIBE with 200 OK, it also sends to the client final NOTIFY.  It
is this in-dialog NOTIFY that in many case comes after the client has
already un-registered and whose delivery to the client thus fails.

According to my tests, the order in which un-REGISTER and un-SUBSCRIBE
is done is currently unpredictable.

-- Juha

**Comment by alfredh** [comment]
I think we can elegantly solve this by letting e.g. mwi have 1 mem_ref to the
struct ua object. We can add a new ua event e.g. UA_EVENT_CLOSE which is signaled
when application is quitting. When e.g. MWI receives this event, it can start the shutdown
process and wait for confirmation. When the final subscription has been closed, the
mwi_destructor will call mem_deref(mwi->ua); and the last person to do this will then
make sure ua_destructor is called, and hence un-registered.

in libre the SIPEVENT api currently does not let you un-SUB and wait for confirmation,
so that API needs to be tuned too.

a simple workaround for now can be to start an async-timer in mwi,
for example 500-1000 ms.

**Comment by alfredh** [comment]
preliminary support for this has been added in the ua_shutdown branch.

to test it you need to patch libre:

1. https://github.com/alfredh/patches/blob/master/re-sipevent-terminate.patch
2. https://github.com/alfredh/baresip/tree/ua_shutdown


it works by sending an event UA_SHUTDOWN from ua.c to all listeners, which will
start the un-SUBSCRIBE process. when each subscription is terminated, it will
destroy itself and thus deref its reference to the "struct ua" object. Finally after all
references to ua is gone, the SIP-stack will also shutdown.

Please review the code and test it.
