### ISSUE TITLE
No doxygen documentation

### ISSUE THREAD

**Issue by vit1251** [alfredh/baresip#301]
Hello,

    Your documentation link http://www.creytiv.com/doxygen/re-dox/html return 404 File not Found.

Thanks.

**Comment by alfredh** [comment]
can you try now:

http://www.creytiv.com/doxygen/baresip-dox/html/


/Alfred

**Comment by vit1251** [comment]
Hello, 

Yep. Documentation is reveal itself ;-)

Thanks.

**Comment by vit1251** [comment]
Problem return back. Request on address http://www.creytiv.com/doxygen/baresip-dox/html/ return 404.

**Comment by alfredh** [comment]
sorry about that .. could you please try again now ?

**Comment by vit1251** [comment]
Yep. Open right now.
Could you add please documentation in you CI system for automatic generate.
Do u use Jenkins or another system for Quality Check (QC)?

**Comment by bhautik-ziniya** [comment]
Hello @alfredh 
Your documentation link [http://www.creytiv.com/doxygen/baresip-dox/html/](url) is failed to open.

Thanks
