### ISSUE TITLE
How to use baresip infrastructure in custom application

### ISSUE THREAD

**Issue by vit1251** [alfredh/baresip#302]
Now baresip is only standalone application how about make it library like
libbaresip and export most popular and usable modules like UA and other
for uses in custom application.

How about embedding your solution in another application?

**Comment by mikhail-barg** [comment]
I'd also agree on this, we are adapting baresip code for use in our app effectively building it as a library and disabling UI related code, etc.

**Comment by alfredh** [comment]
Hi,

thanks for the input. I wrote a small Wiki article explaining how to do this:

https://github.com/alfredh/baresip/wiki/Using-baresip-as-a-library


can you please have a look and see if this what you are looking for ?


/Alfred
