### ISSUE TITLE
SIPS proxy

### ISSUE THREAD

**Issue by anug7** [alfredh/baresip#303]
@alfredh wrt #298 ending notes, I have some doubts

1. Want to understand how calling from linphone to baresip works without any issues (in the set up I mentioned changing caller->callee).
2. If I use custom sip server (opensips), will the problem get resolved?
3. If I want to add support for SIPS proxy, how hard would that be?

Thanks for you support
Anug

**Comment by alfredh** [comment]
To deploy SIPS properly all endpoints and proxy must support SIPS, and you must
ensure that each hop is using TLS transport. If one hop is sent unencrypted this breaks
the whole chain and thus makes SIPS pointless.

Baresip is using libre SIP stack which only supports SIP and not SIPS. Hence
you cannot securely deploy baresip with SIPS. We are not planning to add support for SIPS.

I would recommend you to setup a very basic SIP proxy such as Kamailio and disable
all bells and whistles even authentication, and as a first step make sure that the
SIP signaling and media part is working properly first. Only after that you can continue
by adding more advanced features.

Some further reading:

https://tools.ietf.org/html/rfc5630

/Alfred
