### ISSUE TITLE
Opus encoder ignores opus_bitrate setting

### ISSUE THREAD

**Issue by glenvt18** [alfredh/baresip#305]
if a peer doesn't send `maxaveragebitrate`.

After 11efdf7 this code (78885f3) no longer works because auc->fmtp is now NULL and conf_prm.bitrate is always OPUS_AUTO:
```
	conf_prm.bitrate = OPUS_AUTO;
	opus_decode_fmtp(&conf_prm, auc->fmtp);

	if ((prm.bitrate == OPUS_AUTO) ||
	    ((conf_prm.bitrate != OPUS_AUTO) &&
	     (conf_prm.bitrate < prm.bitrate)))
		prm.bitrate = conf_prm.bitrate;
```

For example, a call to sip:4444@sip2sip.info (free echo test)
our offer:
```
a=rtpmap:96 opus/48000/2
a=fmtp:96 stereo=1;sprop-stereo=1;maxaveragebitrate=28000
```
their response:
```
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
```
encoder fmtp == `useinbandfec=1` and the codec encodes at ~97 kbit/s.

**Comment by juha-h** [comment]
glenvt18 writes:

> For example, a call to sip:4444@sip2sip.info (free echo test)

Looks like they need to upgrade the test:

Sep 30 11:33:08 box /usr/bin/sip-proxy[1507]: ERROR: tls [tls_util.h:42]: tls_err_ret(): TLS write:error:1417118C:SSL routines:tls_process_server_hello:version too low

-- Juha

**Comment by glenvt18** [comment]
@juha-h You can connect to sip2sip.info directly (no authorization required), or use `;transport=udp`.
I've just tested it with linphone: linphone also sends `useinbandfec=1`, but it's codec runs at 34 kbit/s.

**Comment by alfredh** [comment]
Hi @glenvt18 

your observation is indeed correct.

could you please try this patch and see if it works better:

```
diff --git a/modules/opus/opus.c b/modules/opus/opus.c
index 78ed3bf..48311f1 100644
--- a/modules/opus/opus.c
+++ b/modules/opus/opus.c
@@ -63,13 +63,12 @@ static struct aucodec opus = {
        .srate     = 48000,
        .crate     = 48000,
        .ch        = 2,
-       .fmtp      = NULL,
+       .fmtp      = fmtp,
        .encupdh   = opus_encode_update,
        .ench      = opus_encode_frm,
        .decupdh   = opus_decode_update,
        .dech      = opus_decode_frm,
        .plch      = opus_decode_pkloss,
-       .fmtp_ench = opus_fmtp_enc,
 };
 
 
@@ -134,6 +133,9 @@ static int module_init(void)
 
        (void)conf_get_bool(conf, "opus_mirror", &opus_mirror);
 
+       if (opus_mirror)
+               opus.fmtp_ench = opus_fmtp_enc;
+
        debug("opus: fmtp=\"%s\"\n", fmtp);
 
        aucodec_register(baresip_aucodecl(), &opus);
```


/Alfred

**Comment by glenvt18** [comment]
@alfredh Looks like the bitrate setting is fixed now. Mirroring works. If mirroring is active, there are two fmtp lines in the answer (.fmtp, .fmtp_ench):
```
a=fmtp:96 stereo=1;sprop-stereo=1;maxaveragebitrate=42000;cbr=1;useinbandfec=1
a=fmtp:96 stereo=1;sprop-stereo=1;maxaveragebitrate=60000
```
If that is OK, the issue is fixed.

Here are the logs.

Alice's config:
```
opus_bitrate		60000 # 6000-510000
```
Bob's config:
```
opus_bitrate		42000 # 6000-510000
opus_cbr			yes
opus_inbandfec		yes
opus_mirror			no
```
Alice calls Bob. Both operate at 42000 bit/s.
https://pastebin.com/t7dJ3kYu

Now Bob has
```
opus_mirror			yes
```
Alice calls Bob. Alice operates at 60000 bit/s. Bob operates at 42000 bit/s.
https://pastebin.com/DmApGZJJ
When Bob calls Alice, both operate at 42000 bit/s.

BTW. What's the idea behind mirroring?

**Comment by alfredh** [comment]
Hi @glenvt18 

many thanks for your detailed and precise bug report, and for testing the fix.
I have pushed a fix now to master.

mirroring is a special mode for incoming calls where the SDP Answer will contain
exactly the same opus parameters as the SDP Offer.


/Alfred
