### ISSUE TITLE
It's time to start G.729 elsewhere

### ISSUE THREAD

**Issue by vit1251** [alfredh/baresip#309]
Hello,

As you probably heard G.729 licences is done in 1 January 2017 it is good news for every one who want use good quality and have small bandwith network channel.

I suggest start using BeladonnaCommunication G.729 implementation.

I have good experience with bcg729 (with small contract fixes).

Links:

* https://en.wikipedia.org/wiki/G.729 (part Licences)
* https://github.com/BelledonneCommunications/bcg729

How about implementation G.729 codecs ?

Thanks.

**Comment by alfredh** [comment]
I have added G.729 to the Baresip Roadmap:

https://github.com/alfredh/baresip/wiki/Roadmap

Do you want to contribute a new module "g729" ?


/Alfred

**Comment by alfredh** [comment]
Hi @vit1251 a Pull Request for this is welcome.

in the meantime I will close this issue for now ..

**Comment by vit1251** [comment]
OK, I will return little bit later now I research another issue and I call or write message direcly via LinkedIn.
