### ISSUE TITLE
Configurable SIP Timers

### ISSUE THREAD

**Issue by alfredh** [alfredh/baresip#312]
Add support for run-time configurable SIP timers including T1.

Suggested config (values in milliseconds):

```
sip_timer_t1            500
```

perhaps also Timer TB will be added later.

@oej 

This feature has been requested by Sveriges Radio, and the development
is sponsored by Sveriges Radio.

**Comment by alfredh** [comment]
Hi @oej 

according to SIP RFC 3261 The Timer B must be 64 times T1:

https://tools.ietf.org/html/rfc3261#section-17.1.1.2

```
   For
   any transport, the client transaction MUST start timer B with a value
   of 64*T1 seconds (Timer B controls transaction timeouts).
```

do you have a need to set Timer B to something else than 64*T1 ?

**Comment by oej** [comment]
Yes, in many cases you want to be able to set it to another value. T1 then determines the number of retransmissions you have until TB fires. For satellite links, we need fine tuning.

**Comment by alfredh** [comment]
this has now been implemented in a testing branch:

commit 509a7259415197009b51b1699a450068a0f98ed3
