### ISSUE TITLE
Scripts support

### ISSUE THREAD

**Issue by daniel-lucio** [alfredh/baresip#315]
More a question than an issue. Is there a way to input script actions? Let's say, dial a number, wait X seconds, send a DTMF sequence.

**Comment by lmangani** [comment]
You can easily control Baresip as you describe using the HTTP API and sending commands from curl, a script, etc. I do this spinning up Baresip instances in Docker and sending them commands and it works fine for predictable scenarios.

**Comment by daniel-lucio** [comment]
Thank you.
