### ISSUE TITLE
stderr abuse (?)

### ISSUE THREAD

**Issue by jmillan** [alfredh/baresip#320]
Hi everyone,

Does baresip abuse using `stderr` or is it somehow intentional?

I see that for example the `menu` module prints the call status (audio|video received bytes) few times per second.

Kind regards

**Comment by jmillan** [comment]
I would be glad to collaborate with the change to use stderr only for errors.

**Comment by jmillan** [comment]
Just for the shake of having a representation, this is the output of an ongoing call when the `menu` module is loaded and `stderr` is redirected to a file. To this, the `vumeter` graphs are added if that module is also loaded.

````
[0:00:13] audio=64000/76800 (bit/s)
[0:00:13] audio=64000/76800 (bit/s)
[0:00:13] audio=64000/76800 (bit/s)
[0:00:13] audio=64000/76800 (bit/s)
[0:00:13] audio=64000/76800 (bit/s)
[0:00:13] audio=64000/76800 (bit/s)
[0:00:13] audio=64000/76800 (bit/s)
[0:00:13] audio=64000/76800 (bit/s)
[0:00:13] audio=64000/76800 (bit/s)
[0:00:14] audio=64000/76800 (bit/s)
[0:00:14] audio=64000/76800 (bit/s)
[0:00:14] audio=64000/76800 (bit/s)
[0:00:14] audio=64000/53333 (bit/s)
[0:00:14] audio=64000/53333 (bit/s)
[0:00:14] audio=64000/53333 (bit/s)
[0:00:14] audio=64000/53333 (bit/s)
[0:00:14] audio=64000/53333 (bit/s)
[0:00:14] audio=64000/53333 (bit/s)
[0:00:14] audio=64000/53333 (bit/s)
[0:00:15] audio=64000/53333 (bit/s)
[0:00:15] audio=64000/53333 (bit/s)
[0:00:15] audio=64000/53333 (bit/s)
[0:00:15] audio=64000/53333 (bit/s)
[0:00:15] audio=64000/53333 (bit/s)
[0:00:15] audio=64000/53333 (bit/s)
[0:00:15] audio=64000/53333 (bit/s)
[0:00:15] audio=64000/53333 (bit/s)
[0:00:15] audio=64000/53333 (bit/s)
[0:00:15] audio=64000/53333 (bit/s)
[0:00:16] audio=64000/53333 (bit/s)
[0:00:16] audio=64000/53333 (bit/s)
[0:00:16] audio=64000/53333 (bit/s)
[0:00:16] audio=64000/53333 (bit/s)
[0:00:16] audio=64000/53333 (bit/s)
[0:00:16] audio=64000/53333 (bit/s)
[0:00:16] audio=64000/53333 (bit/s)
[0:00:16] audio=64000/53333 (bit/s)
[0:00:16] audio=64000/53333 (bit/s)
[0:00:16] audio=64000/53333 (bit/s)
[0:00:17] audio=64000/53333 (bit/s)
[0:00:17] audio=64000/53333 (bit/s)
[0:00:17] audio=64000/53333 (bit/s)
````

**Comment by jmillan** [comment]
Hi,

I would just like to say that `syslog` or even `cons` module do the job if one wants to get the 'real' log.

Please, feel free to close the issue if you find there's nothing to fix here.

Kind regards.

**Comment by alfredh** [comment]
hi @jmillan 

many thanks for the report.

The choice to use `stderr` was done a long time ago, when I was implementing
the call status bar. The call status bar is updated by printing `\r` which moves the
cursor to the beginning of the line. (See `call_status` function for details).

when I was using `stdout` this did not seem to work, I guess because stdout
is linebuffered. so I decided to use `stderr` instead, which was working :)


I agree that the code is abusing stderr.


Do you have any good suggestions for how to solve this ?


/Alfred

**Comment by jmillan** [comment]
Hi @alfredh,

I'm not an expert. But since `stdout` is line buffered you can do two things:

* `fflush(stdout)` every time you write the call status.

````c
#include <stdio.h>
#include <unistd.h>

static char bar[] = "========>";

int main() {
    int i;
    for (i = 7; i >= 0; i--) {
        fprintf(stdout, "[%s]\r", &bar[i]);
        fflush(stdout);
        sleep(1);
    }

    printf("\n");

    return 0;
}
```` 

* Make `stdio` unbuffered.

````c
#include <stdio.h>
#include <unistd.h>

static char bar[] = "========>";

int main() {
    int i;

    setbuf(stdout, NULL);

    /* or
    setvbuf(stdout, NULL, _IONBF, 0);
    */

    for (i = 7; i >= 0; i--) {
        fprintf(stdout, "[%s]\r", &bar[i]);
        sleep(1);
    }

    printf("\n");

    return 0;
}
````

**Comment by alfredh** [comment]
thanks for the explanation and sample code.

in this case, I think we should go for the fflush solution. Using unbuffered mode
seems a bit inefficient.

Almost all the log-lines printed have a trailing newline, so they will work with stdout.
It is only a couple of places, like call status, that needs to flush.

would you like to create a PR for this ?

Alfred

**Comment by jmillan** [comment]
You are very welcome.

> would you like to create a PR for this ?

I'm perfectly fine if you do it. You know exactly where to hit the hammer. :-)

**Comment by alfredh** [comment]
I did some changes to move printing from stderr to stdout.

if you grep for stderr in the code, you will see that there are some places
that it needs changing:

```
modules/contact/contact.c:		(void)re_fprintf(stderr, " \x1b[31m%m\x1b[;m\n", err);
modules/contact/contact.c:		(void)re_fprintf(stderr, " \x1b[31m%u %r\x1b[;m\n",
modules/menu/menu.c:		(void)re_fprintf(stderr, "%H\r", call_status, call);
modules/menu/menu.c:	(void)re_fprintf(stderr, "\r%r: \"%b\"\n", peer,
modules/vumeter/vumeter.c:	re_fprintf(stderr, "\x1b[%dG", pos);
modules/vumeter/vumeter.c:	re_fprintf(stderr, " \x1b[%dm%H\x1b[;m\r",
src/log.c:			(void)re_fprintf(stderr, "\x1b[31m"); /* Red */
src/log.c:		(void)re_fprintf(stderr, "%s", buf);
src/log.c:			(void)re_fprintf(stderr, "\x1b[;m");
src/main.c:	(void)re_fprintf(stderr,
src/main.c:	(void)re_fprintf(stderr, "baresip v%s"
src/main.c:				re_fprintf(stderr,
```

which places would you like to use stdout instead?

also the logging system needs to print to stdout instead of stderr. what
do you suggest here ? We have different levels, like INFO, WARNING, ERROR.
should WARNING print to stderr ?

I would still encourage you to create a small PR even just for a couple of lines
of code. That way you can test it and get it working exactly as you want.

Code contributions are very welcome.

Alfred

**Comment by jmillan** [comment]
Hi,

The scenario is that baresip is much used (AFAIK) as a command line tool. It provides realtime information and control capabilities useful for the user. On the other hand, someone may want to redirect the `stdio` for logging purposes or in order to pipe with another program.

Considering the above, I would say that in fact it is correct to print this real time information in the `stderr` as long as the INFO, WARNING, ERROR log levels are redirected to `stdio`. This way all the relevant software log is redirected to `stdio` and `stderr` is left for user interaction though the command line.

**Comment by alfredh** [comment]
Hi @jmillan 

I have done a small update for this in commit 5eeadba9af3e03abf0af046fb20b64f3f7393658

* log messages are printed to stdout
* command/stdio module printed to stderr
* interactive status bars printed to stdout or stderr

could you please test it and see if this is what you want ?

Alfred

**Comment by jmillan** [comment]
Hi @alfredh,

I like it very much. It makes a lot of sense.

**Comment by nickmicky** [comment]
Hi @jmillan and @alfredh,
I've came across this issue recently. I am creating a Python wrapper for baresip, which is based on baresip's process output. But - the output that I am receiving when running with Python is different from the one I am receiving when running from the console.

@jmillan  - I've tried to enable syslog.so module in the config but nothing changed.

What am I missing here?

Thank you for your help

**Comment by jmillan** [comment]
Hi,

Just redirect `stdout` and `stderr` to different files in order see what is logged where.

**Comment by nickmicky** [comment]
Hi @jmillan ,
So no change is required to the config file?
The below code doesn't work:
```
sip_process = subprocess.Popen('baresip', stdout=subprocess.PIPE, stderr=subprocess.STDOUT, stdin=subprocess.PIPE)
self.sip_process.stdin.write('/dial xxx' + '\n')
self.sip_process.stdin.flush()
while sip_process.poll() is None:
    output = sip_process.stdout.readline()
    print 'output = ', output
    if "established" in output: #This is to to determine if the call has been answered or not
          #do that...
```
What am I missing here?

Thanks again :-)

**Comment by jmillan** [comment]
I would suggest you to lauch baresip from your system directly and redirect or filter `stdout` and `stderr` to see what is logged where. Ie:

Filter `stdout`: `$baresip > /dev/null`
Filter `stderr`: `$baresip 2> /dev/null`

**Comment by nickmicky** [comment]
Thank you for your help, @jmillan.
Running baresip with these filters changes the output for some reason, I don't get indications that the call was answered or terminated.

Have you faced these errors?

Thanks
