### ISSUE TITLE
Baresip does use a fixed network interface regardless of the SIP destination

### ISSUE THREAD

**Issue by jmillan** [alfredh/baresip#330]
Ie:

System interfaces:
```
eth0: PUBLIC_IP_ADDR
eth1: PRIVATE_IP_ADDR
lo  : LOOPBACK_IP_ADDR
```

* Start baresip without `net_interface` configured and with a SIP account pointing to a SIP registrar accessible through the private interface (eth1). Registration is enabled.
* On startup It takes the first network interface: "Local network address: eth0: PUBLIC_IP_ADDR"
* Sends the SIP REGISTER request from the PUBLIC_IP_ADDR even though the system routing table defines a direct route to the LAN through eth1.

**Comment by alfredh** [comment]
The SIP-stack used by baresip (libre) does not support proper Multi-homing yet.
It will support dual stack with IPv4 and IPv6, but not multiple IPv4 addresses.
The SIP stack will choose the first transport address.

Baresip will try to guess the best network interface, from the kernel routing table.

You should use the `sip_listen` config to force the SIP-stack to listen on
a specific address/interface:

```
sip_listen              10.0.0.2:5050
```

Alfred
