### ISSUE TITLE
MQTT API and events

### ISSUE THREAD

**Issue by oej** [alfredh/baresip#331]
I have created two separate proposals on syntax for the MQTT module being added to baresip. I like to see feedback from the rest of the community on these documents.

* https://github.com/alfredh/baresip/wiki/Proposal:-Baresip-MQTT-API
* https://github.com/alfredh/baresip/wiki/Proposal:-MQTT-event-handler

You can add comments on this issue and I'll try to merge as we reach consensus.
Cheers
/O

**Comment by alfredh** [comment]
many thanks @oej 

I have merged the new `mqtt` module to master, for more testing:

https://github.com/alfredh/baresip/commit/bfe2b0562e020de68628d050b4a4a7997d8a8c4b

as agreed, all payloads (request,response,event) should always be encoded
as JSON. this way the JSON blob can be standarized and also transported over
other protocols (e.g. Websocket).

**Comment by jmillan** [comment]
Hi,

 > as agreed, all payloads (request,response,event) should always be encoded
as JSON. this way the JSON blob can be standarized and also transported over
other protocols (e.g. Websocket).

Definitely agreed.

Regarding to commands, I think there should be a core`cmd_process_long_json` function that receives a JSON object representing the command to be run. The MQTT module's `handle_command` would just call this function, retrieve the response and send it back.

In my opinion this code should also be part of the core accessible for other modules so they don't have to know the specific format for a command and construct it by hand:

```C
/* Constructs a JSON object representing the command given in the buffer */
int cmd_decode_json(struct odict **op, const char *str);
```

Regarding to event registrations, I think there should be a core `uag_event_register_json` function, which handler receives the JSON object representing the event. The MQTT module's `ua_event_handler` would be called with a JSON object representing the event, which the module can just serialize and send.

This way creating different 'transports' for receiving commands and sending events will be decoupled from the representation of the data.

**Comment by alfredh** [comment]
I have added encoding of events to event.c , this code can now be shared
by all modules.

please feel free to suggest changes/improvements to the syntax, but please be kind
and send it as suggested PR (small diffs please).

**Comment by alfredh** [comment]
Basic support for MQTT should now be in place.
