### ISSUE TITLE
Video/Audio storing option

### ISSUE THREAD

**Issue by gunasekaran7** [alfredh/baresip#333]
Is there an option to record the Video/Audio while in the call?

**Comment by lmangani** [comment]
@gunasekaran7 for audio take a look at ```sndfile``` module

**Comment by alfredh** [comment]
1. audio: you can use the `sndfile` module to write WAV files:
http://www.creytiv.com/doxygen/baresip-dox/html/group__sndfile.html

2. video: you can implement a new vidfilt module that writes raw video
frames to a container, such as .y4m
https://wiki.multimedia.cx/index.php/YUV4MPEG2

Alfred

**Comment by gunasekaran7** [comment]
Thank you for the suggestion. Sounds like a good idea implementing through the 

> vidfilt
