### ISSUE TITLE
Canceled call reported as Connection reset by peer

### ISSUE THREAD

**Issue by nshopik** [alfredh/baresip#335]
This is cosmetic issue, as I found that when remote call canceled baresip will reported it as `Connection reset by peer` which is not entirely true. Its nitpicking but `connection reset` sound like hard reset on transport level UDP/TCP and not proper cancel on SIP level

Maybe better wording like `Call canceled by remote peer` will suit here better.

**Comment by alfredh** [comment]
many thanks for your comments, 

I am afraid that I would like to keep the current logic, which is to display the error codes
coming from the SIP stack.

If I have to check different error values, it will be a lot of extra code just
to have better cosmetics.

Alfred

**Comment by nshopik** [comment]
Well maybe just return SIP error then instead current ambiguous text? Like `487 Request Terminated `
