### ISSUE TITLE
ringback on sip response 180

### ISSUE THREAD

**Issue by Ola-Palm** [alfredh/baresip#336]
When using same the output for player and alert, the ringback when sip 180 is received results in call not possible to establish. This due to the sound card is busy playing sound files in one format, and opus tries to set the card in another format. 
I'm not sure If problem exist if using G711 or other 8kHz codecs. But we are having problems when using opus.

**Comment by alfredh** [comment]
this was implemented in commit e223601e6ac48e0c4829c77c016a38ee21b5633a
