### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kayb94** [alfredh/baresip#343]
Hi,

I was happy to see, that your baresip is written to be BSD licensed in the README.md ("Distributed under BSD license"). However, every actual source file says: "Copyright (C) 2017 Creytiv.com".
To me this looks a bit confusing; which is the actual license? 

Kind Regards
Kay

**Comment by jungle-boogie** [comment]
What would you rather have it say?

**Comment by jungle-boogie** [comment]
FreeBSD uses the BSD license and they have a copyright: https://www.freebsd.org/copyright/freebsd-license.html

**Comment by jungle-boogie** [comment]
Another example:
https://www.openbsd.org/policy.html

**Comment by kayb94** [comment]
Thank you for your responses, @jungle-boogie. What I miss is:
"Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: ..." and so on, which is in both of your examples. Without that, it's just copyright, which (I'm not a legal expert), as far as I know, simply means bare copyright whithout granting anyone any rights.

Regards

**Comment by jungle-boogie** [comment]
yeah, perhaps it would be a good idea for @alfredh to include a LICENSE file in the repo for clarity.

**Comment by alfredh** [comment]
the BSD License file is already here:

https://github.com/alfredh/baresip/blob/master/docs/COPYING

All the source code in baresip is under BSD license. Repeating the license text
in each source file is just silly.

**Comment by jungle-boogie** [comment]
Oh, sorry, @alfredh, I missed the location of the license.
