### ISSUE TITLE
omx: build error on Raspbian

### ISSUE THREAD

**Issue by alfredh** [alfredh/baresip#344]
System is Raspberry Pi with Raspbian.

```
$ cat /etc/debian_version 
8.0

$ make omx.so
  CC [M]  build-arm6/modules/omx/omx.o
modules/omx/omx.c: In function ‘omx_init’:
modules/omx/omx.c:116:2: warning: implicit declaration of function ‘bcm_host_init’ [-Wimplicit-function-declaration]
  bcm_host_init();
  ^
modules/omx/omx.c:116:2: warning: nested extern declaration of ‘bcm_host_init’ [-Wnested-externs]
modules/omx/omx.c: In function ‘omx_display_disable’:
modules/omx/omx.c:175:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  OMX_ERRORTYPE err;
  ^
  CC [M]  build-arm6/modules/omx/module.o
  LD [M]  omx.so
```

@strfry does it build without errors on your system?

**Comment by alfredh** [comment]
should be fixed in https://github.com/alfredh/baresip/commit/adbae9ce7955e6c70ab90d173054b875831d456e

@strfry please verify that it builds for you ..

Alfred

**Comment by strfry** [comment]
I'm quite sure these errors also happened on my system, i'm just too lazy when it comes to cleaning up compiler warnings ;) (and these only appear when building on the RPi, not with omx-bellagio).

Also i noticed that i have another bugfix for the omx module in my branch. I will try to clean that up and submit a pull request in the next days.
