### ISSUE TITLE
Read Baresip's process output via a python script?

### ISSUE THREAD

**Issue by nickmicky** [alfredh/baresip#345]
Hi Alfred,
First let me express my appreciation for this project- I really think that this is the future of SIP clients. Baresip is lightweight, simple to use and powerful.

I have a python script that is lunching Baresip using subprocess, and redirecting it's output to subprocess.PIPE.
The problem here is that there is no output from the process.

Do you familiar with that?
Thanks

**Comment by kayb94** [comment]
Have you checked, whether it arrives on STDERR instead of STDOUT?

**Comment by alfredh** [comment]
which baresip version are you using, and how do you invoke it ?

Baresip is now writing the output to stdout. Some interactive output might be
written to stderr. When launching baresip with `-d` option (Daemon mode) the
stdout and stderr file descriptors are closed and nothing is written. In daemon
mode you should use the `syslog` module.

Alfred

**Comment by nickmicky** [comment]
Sorry for the delay here.
I was using baresip 0.5.7 and now 0.5.8, and I want a simple python script that will initiate calls using baresip, and detect when the call was hanged up by the far end. For some reason, baresip does not prints information that the call is terminated, and while in active call, only the [00:01:01] line of the call time is being printed.

Here is my code:
baresip_process = subprocess.Popen('baresip', stdout=PIPE, stderr=STDOUT, stdin=PIPE)
output = baresip_process.stdout.readline()
if 'terminated' in output:
   #Do something....

The problems are:
1) The baresip_process.stdout.readline() is blocking forever
2) Basically, baresip never prints 'terminated' or other call related info to the stderr/stdout.

Thank you for your help

**Comment by JarbasAl** [comment]
@nickmicky see https://github.com/JarbasAl/baresipy for a python wrapper around baresip
