### ISSUE TITLE
macOS build fails - CLOCK_MONOTONIC

### ISSUE THREAD

**Issue by sreimers** [alfredh/baresip#347]
```
src/timer.c:33:2: error: unknown type name 'clockid_t'; did you mean 'clock_t'?
        clockid_t clock_id;
        ^~~~~~~~~
        clock_t
/usr/include/sys/_types/_clock_t.h:30:33: note: 'clock_t' declared here
typedef __darwin_clock_t        clock_t;
                                ^
src/timer.c:38:13: error: use of undeclared identifier 'CLOCK_MONOTONIC'
        clock_id = CLOCK_MONOTONIC;
                   ^
src/timer.c:41:11: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
        if (0 != clock_gettime(clock_id, &now)) {
                 ^
1 warning and 2 errors generated.
make: *** [build-x86_64/src/timer.o] Error 1
```
Worker: travis-ci-osx10.10-xcode6.4

**Comment by alfredh** [comment]
thanks for the report.

can you please check if CLOCK_MONOTONIC is available on your system?

is there some magic define that we have to define before including headers ?

**Comment by sreimers** [comment]
i did some research and it seams that `clock_gettime` is only supported with macOS Sierra 10.12 (September 2016, XCode 8) and later. Maybe I upgrade the macOS build pipeline.

**Comment by alfredh** [comment]
@sreimers baresip should build on your platform.

I added a compile-time check for `clock_gettime` with fallback to `gettimeofday`.
I also have reports from other users about the build errors on some platforms.

Could you please re-test with GIT @HEAD ?

**Comment by sreimers** [comment]
Works now.

**Comment by ebolainfluenza** [comment]
It's back.  I'm running Mac OS X 10.11.6 (El Capitan), and getting this:

  CC      trace/control.o
In file included from trace/control.c:29:
In file included from qemu/include/monitor/monitor.h:4:
In file included from qemu/include/block/block.h:4:
In file included from qemu/include/block/aio.h:23:
qemu/include/qemu/timer.h:843:9: warning: implicit declaration of function 'clock_gettime' is invalid in C99
      [-Wimplicit-function-declaration]
        clock_gettime(CLOCK_MONOTONIC, &ts);
        ^
qemu/include/qemu/timer.h:843:23: error: use of undeclared identifier 'CLOCK_MONOTONIC'
        clock_gettime(CLOCK_MONOTONIC, &ts);
                      ^
1 warning and 1 error generated.
make: *** [trace/control.o] Error 1

Submodule init and update, and configure went perfectly.

What's the best way to proceed, please?

Shall I Merge pull request #5 from alfredh/master?

Thanks all!

**Comment by sreimers** [comment]
Your errors come from `qemu` not from a baresip source file.

**Comment by ebolainfluenza** [comment]
> Your errors come from `qemu` not from a baresip source file.

Wow, you are correct.  I apologize.  After finding this page in GitHub, I stopped paying attention.  I'll chase this down through proper channels.
