### ISSUE TITLE
How to compile the avahi-module?

### ISSUE THREAD

**Issue by abeutel89** [alfredh/baresip#348]
Hi,
I'm running Ubuntu 16.04 and want to use avahi 0.6.32 with baresip.
All avahi libraries are installed ( -dev as well) but avahi.so is not compiled.
Probably the makefiles cannot access it.

What do I have to do to compile the avahi module?

Thanks a lot, best regards
Adrian

**Comment by alfredh** [comment]
The avahi module should be auto-detected, if avahi-client headers are installed.

in any case you can force enable it:

```sh
$ make USE_AVAHI=yes
```

which version of baresip are you using ?

Please paste here the output of `make info` and the build log.

Alfred

**Comment by abeutel89** [comment]
Hi Alfred,
thanks for your reply. I'm using re-0.5.6, rem-0.5.2 and baresip-0.5.7. Unfortunately, "make USE_AVAHI=yes" has not worked for me yet... Please find the related output attached.

Cheers,
Adrian
[Baresip_installation.txt](https://github.com/alfredh/baresip/files/1677965/Baresip_installation.txt)

**Comment by alfredh** [comment]
there is a bug in mk/modules that is fixed in GIT head.

you can try this:

```
$ make USE_AVCODEC=yes USE_AVAHI=yes
$ sudo make USE_AVCODEC=yes USE_AVAHI=yes install
```

or you can try baresip from GIT head.

you can also do this:

```
$ make EXTRA_MODULES=avahi
```

**Comment by abeutel89** [comment]
Hey Alfred,
thanks a lot. The third option worked for me with the old version. 
$ make EXTRA_MODULES=avahi

Then I tested with the new head as well. It works fine.
Cheers
Adrian
