### ISSUE TITLE
g722 codec implementation

### ISSUE THREAD

**Issue by sreimers** [alfredh/baresip#350]
Hi Alfred, at the moment the g722 module needs the external spandsp library. But the spandsp author has released the g722 code under a separate license, so maybe we can import them like asterisk directly in baresip or rem:

https://github.com/asterisk/asterisk/tree/master/codecs/g722

```
/*
 * SpanDSP - a series of DSP components for telephony
 *
 * g722_decode.c - The ITU G.722 codec, decode part.
 *
 * Written by Steve Underwood <steveu@coppice.org>
 *
 * Copyright (C) 2005 Steve Underwood
 *
 *  Despite my general liking of the GPL, I place my own contributions
 *  to this code in the public domain for the benefit of all mankind -
 *  even the slimy ones who might try to proprietize my work and use it
 *  to my detriment.
 *
 * Based in part on a single channel G.722 codec which is:
 *
 * Copyright (c) CMU 1993
 * Computer Science, Speech Group
 * Chengxiang Lu and Alex Hauptmann
 *
 * $Id$
 */
```

**Comment by alfredh** [comment]
I think we should not import source code project other projects, unless no other
option exist.

What happens after the code is imported/copied, is in practice that the code is forked.
From this moment we have to maintain 2 projects and sync features/bugfixes between
them. After some years the codes are completely out of sync, and merging between
them becomes impossible.

For example distributions like Debian and others have the `spandsp` package which
is properly maintained. For the baresip project it is very easy and convenient to
link to `-lspandsp` and have a package dependency to spandsp.

We could of course make an exception for g722, do you have specific usecase for that?

We should also ask Steve Underwood about his opinion of this.


Alfred

**Comment by sreimers** [comment]
My problem with spandsp is the license, the GPL forbids static linking with licenses that are not compatible  (like BSD/MIT) with my understanding of the law restrictions. Dynamic linking and distribution is no option for my use case (easy execution, without a installer on all platforms). I understand your argumentation and this is why I ask before and put work into a pull request. So I can fork the g722 by myself and implement it this way.

**Comment by alfredh** [comment]
https://www.soft-switch.org/installing-spandsp.html

```
Note than recent versions of SpanDSP are licenced under LGPL 2.1. Earlier versions were licenced under GPL 2.0.
```

**Comment by oej** [comment]
Even if you fork, the license does not change. In fact, running Baresip with old versions of SpanDSP makes your baresip GPL licensed. LGPL is a better choice.

I agree with Alfred, importing source code is not a good thing and ends up a headache. The Debian maintainers are strict about this.

**Comment by jonassmedegaard** [comment]
For the record, Debian is not fundamentally *against* embedded code copies, only strongly discourages it because it is harder (not impossible) to maintain.
