### ISSUE TITLE
FF_MIN_BUFFER_SIZE undefined 

### ISSUE THREAD

**Issue by saket424** [alfredh/baresip#351]
When compiling with ffmpeg git HEAD, I got the following error
  CC [M]  build-x86_64/modules/avcodec/encode.o
modules/avcodec/encode.c: In function ‘encode_update’:
modules/avcodec/encode.c:516:23: error: ‘FF_MIN_BUFFER_SIZE’ undeclared (first use in this function)
  st->mb  = mbuf_alloc(FF_MIN_BUFFER_SIZE * 20);
                       ^
modules/avcodec/encode.c:516:23: note: each undeclared identifier is reported only once for each function it appears in
mk/mod.mk:42: recipe for target 'build-x86_64/modules/avcodec/encode.o' failed
make: *** [build-x86_64/modules/avcodec/encode.o] Error 1

The new define is AV_INPUT_BUFFER_MIN_SIZE instead of FF_MIN_BUFFER_SIZE

**Comment by alfredh** [comment]
thanks for the report,

could you please test again with GIT head and see if it works better ?

Alfred
