### ISSUE TITLE
dial out without registration

### ISSUE THREAD

**Issue by mo8Zomo0** [alfredh/baresip#355]
Hi!

When I try to dial out without an entry in the accounts file I do not manage to dial out.

I only get a:
menu: ua_connect failed: Invalid argument

when I add an account:
<sip:test:invalid@invalid>
it will comlain with:
account: username:password is now deprecated please use ;auth_pass=xxx instead
reg: sip:test@invalid: Register: Destination address required

If I do not add a password 

What would be the right way to place direct calls to sip addresses (uri with domain) and not being registered.

Next step would be how to do that via a proxy and step after that, proxy with auth.

**Comment by alfredh** [comment]
You need to have 1 or more SIP accounts in the `accounts` file.

Example:

`<sip:test@invalid>;auth_pass=none;regint=0`

The regint=0 means that registration is disabled.
The SIP password should not be in the SIP aor anymore,
this is currently deprecated and will be disabled later.

Then you can make an outgoing direct call:

`/dial target@10.0.0.2`


Alfred

**Comment by mo8Zomo0** [comment]
Hi Alfred, 

thank you for your feedback.
I used the auto generated file as the base, possibly handy to upgrade it to reflect the new config style
