### ISSUE TITLE
b2bua config file syntax and use

### ISSUE THREAD

**Issue by saket424** [alfredh/baresip#361]
@alfredh ,
Would you mind elaborating on how the b2bua module is configured/used. It is listed as experimental but I assume that just means it is not automatically included in mk/modules.mk

A wiki post or some quick getting started information would be very helpful to me

Thanks
Anand

**Comment by saket424** [comment]
@alfredh  

I figured out the usage after I saw what you were doing in test_uag_find_param() in https://github.com/alfredh/baresip/blob/master/test/ua.c

You  need to specify 2 UAs with the specific keyvalue pair that the b2bua module is expecting 

<sip:foo@127.0.0.1>;regint=0;auth_pass=foo;b2bua=outbound
<sip:bar@example.com>;auth_pass=bar;b2bua=inbound

Then the b2bua association of inbound and outbound can succeed with uag_find_param

ua_in  = uag_find_param("b2bua", "inbound");
ua_out = uag_find_param("b2bua", "outbound");


Now I confirm that b2bua module got loaded successfully

/modules

--- Modules (13) ---
            stdio type=ui           ref=1
             g711 type=audio codec  ref=1
          vumeter type=filter       ref=1
             alsa type=sound        ref=1
             stun type=mnat         ref=1
             turn type=mnat         ref=1
              ice type=mnat         ref=1
           auloop type=application  ref=1
            b2bua type=application  ref=1
          contact type=application  ref=1
        debug_cmd type=application  ref=1
             menu type=application  ref=1
          vidloop type=application  ref=1

**Comment by saket424** [comment]
@alfredh 
I am not out of the woods yet. I have not yet been able to get b2bua to work quite right yet

Do I use
# Audio
audio_player		aubridge,nil
audio_source		aubridge,nil

or something different for audio_player and audio_source ? Any pointers you give are greatly appreciated.
Thanks in advance

**Comment by saket424** [comment]
When the b2bua module is enabled and I try to place an inbound call with answermode not set to auto, I am able to see that the b2bua receives an incoming call event. however it places another inbound call to itself and this loop soon exceeds the max number of call 4. I am clearly doing something horribly wrong.

Again, if you can post a working sample config & sample accounts when b2bua is enabled it will greatly help clarify the syntax and usage

Why is the b2bua placing a call to itself?

**Comment by alfredh** [comment]
hi,

I will write up a Wiki article about how to use the b2bua module.

Alfred

**Comment by saket424** [comment]
Alfred, Thanks in advance for the b2bua wiki article. Looking forward to it

**Comment by alfredh** [comment]
Hi @saket424 

you can now test master HEAD, please use commit 57bd2be20bcc484499c5d57a96ebaa8a85787735

I wrote a small article on how to use b2bua module:

https://github.com/alfredh/baresip/wiki/b2bua-module

please feel free to read and test it, and update the article with any extra information.


Alfred

**Comment by saket424** [comment]
Alfred,
Preliminary test using the wiki and the new commit says it worked! Thanks

I was thinking of doing it slightly differently rather than implementing it as an outbound proxy.

Instead, I was thinking of calling the inbound number specified in b2bua=inbound and it, in turn, dialed the outbound extension specified in b2bua=outbound;b2bua_outbound_exten=XYZ

i.e., a call on the inbound extension arrives on the inbound ua_context triggers a call to a pre-specified extension XYZ using the outbound ua_context

Your thoughts?

**Comment by alfredh** [comment]
this should be possible;

1. the inbound side can be kept as is, or enable register client (`;regint=600`) if you
want to register it to a SIP proxy.

2. the outbound side can be modified to dial a specified number, either as a new
account parameter (as you suggest) or a new config item that is read by the b2bua.so module

you will need to change this portion in `b2bua.c`

```
	err = ua_connect(ua_out, &sess->call_out, call_peeruri(call),
			 call_localuri(call), NULL,
			 call_has_video(call) ? VIDMODE_ON : VIDMODE_OFF);
```

does my fix and Wiki article answer your original question? if so we can consider
this case closed, and we can continue your modifications as a PR or a new Issue.

Alfred

**Comment by saket424** [comment]
Many Thanks for the b2bua wiki article and the clarifications you provided. Closing this issue as resolved. If I come up with some b2bua enhancements, I will propose it as a PR for your approval.

**Comment by pergolafabio** [comment]
seems starting from release 2.2.0 , the b2bua folder is gone

**Comment by sreimers** [comment]
b2bua is moved to apps: https://github.com/baresip/baresip-apps

**Comment by pergolafabio** [comment]
hey, @sreimers , thnx, was able to compile now with the b2bua module, it created the .so file
the b2bua.so file is in the same folder as the other ones, but it seems it doesnt load?

i added in config:
`module_app		b2bua.so`

i even manually specified the app folder:
`module_path		/home/debian/baresip/build/`

but always get error below:

![image](https://user-images.githubusercontent.com/43251136/203304058-27af38aa-9092-4048-b33c-a9060f74b833.png)

**Comment by sreimers** [comment]
The module is loaded, but closed with error, since its maybe not configured properly:

https://github.com/baresip/baresip-apps/blob/main/modules/b2bua/b2bua.c#L200-L201

**Comment by pergolafabio** [comment]
hmm, i have the accounts enabled as a test with a sip_listen = on

<sip:b2bua-inbound@0.0.0.0>;auth_pass=none;regint=0;b2bua=inbound
<sip:b2bua-outbound@0.0.0.0>;auth_pass=none;regint=0;b2bua=outbound

the error actually tells me the b2bua.so file cant be found ?

**Comment by pergolafabio** [comment]
you are right, seems b2bua is closing , i see thta when i enable verbose:

![image](https://user-images.githubusercontent.com/43251136/203317814-342afcb8-eca1-466a-bcda-151dd7891148.png)

in accounts i have below, whats wrong then? i have specified inbound and outbound?

```
<sip:7001@192.168.0.17>;auth_pass=xxx;b2bua=inbound;regint=0
<sip:6001@192.168.0.17>;auth_pass=xxx;b2bua=outbound;regint=0
```

**Comment by pergolafabio** [comment]
justa question about this b2bua:
Can i setp something like below? so i have sip listen enabled on the localhost, the invites comes in from some local IP
after the invites comes in, the call gets forwarded to an asterisk user

is something like that possible with b2bua?
If not, how can i do somekind of transer with accounts? i want an incoming call directly forwarded to another call, without answering first
thnx!!

```
<sip:inbound@localhost>;auth_pass=none;regint=0;b2bua=inbound
<sip:outbound@asterisk>;auth_pass=XXX;b2bua=outbound
```
