### ISSUE TITLE
Missing event

### ISSUE THREAD

**Issue by ernierasta** [alfredh/baresip#364]
Hi!
I have two questions about notifications

**1) Network failures.**

As I mentioned here: https://github.com/alfredh/baresip/issues/362

When using ctrl_tcp, when network goes down I receive type: REGISTERING event, but not cause of problem. In cli I can see:

    ua: SIP register failed: Network is unreachable

Would it be possible to notify "Network is unreachable" type of errors?

**2) CALL_RTCP event for incoming**

CALL_RTCP event/notification is available only for outgoing calls, is it technical limitation, or it is possible to get it also for incoming calls?

**Comment by alfredh** [comment]
about question number 1, yes we can add this.

about question number 2, I just made a call from baresip to baresip and while the
call is ongoing, I am getting the CALL_RTCP event approx. every 5 seconds
(both outgoing and incoming). Can you please provide a bit more details
why CALL_RTCP for incoming is not working for you ?


Alfred

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I am getting the CALL_RTCP event approx. every 5 seconds
> (both outgoing and incoming). Can you please provide a bit more details
> why CALL_RTCP for incoming is not working for you ?

I'm also seeing those in my Android app at the same kind of frequency.
What are they for?  Call quality info?

-- Juha

**Comment by ernierasta** [comment]
Yes, it is QOS info. Should be exchanged between peers. I supouse in my case SIP will not play a peer role if another end does not support this protocol. If it so, it is strange, that I am receiving them for outgoing (but I receive just 2 and that is all, maybe they are send before reaching peer ...)

Anyway lets ignore this. Only valid point is 1).

**Comment by alfredh** [comment]
hi @ernierasta 

could you please test commit 5855ca50919828adf8102390710995d7446bf8b8
and see if you are getting the wanted event ?

regarding CALL_RTCP event; if RTCP is enabled and supported by the peer,
baresip should receive an RTCP packet every 5 seconds. when this RTCP packet
is received, it is relayed to the event subsystem as UA_EVENT_CALL_RTCP
and anyone who is interested can call `stream_rtcp_stats` to fetch the latest
RTCP statistics.

Alfred

**Comment by ernierasta** [comment]
Now at conference, but will do so at Saturday. Thanx!

**Comment by alfredh** [comment]
@ernierasta still waiting for you to verify this. if I dont hear from you in a few days I will close the issue.

Alfred

**Comment by ernierasta** [comment]
Hi @alfredh sorry, I completely forgot. I generally works, but for only for one (first) registered UA. In baresip cli you can see this message twice, but REGISTER_FAIL is sent once. Tested 2 times.

**Comment by alfredh** [comment]
this could be because the event handler is registered already after the
event has been sent, meaning that the first event will be missed.

do you have any logs to show the case you are describing ?

**Comment by ernierasta** [comment]
I do not know why, but today all looks ok. Maybe that was bug on my end. I tested it today twice, with simplest code possible and it looks ok. So sorry for noise. 

Thank you for implementing this!

Have a great day Alfred.
