### ISSUE TITLE
486 on missing audio device

### ISSUE THREAD

**Issue by oej** [alfredh/baresip#365]
BareSIP sends 486 when there's no audio device or something is wrong. I suggest either changing or adding an option so that we can get a 5xx class error message on this type of error. Hard to judge if 500 or 503 is the best option here, but at least not 486.

**Comment by alfredh** [comment]
hi @oej 

many thanks for your feedback.

it would be very helpful if you can include a log and SIP traffic when this
scenario happens. for example is it valid for outgoing calls, incoming calls
or both ?

Alfred

**Comment by oej** [comment]
Incoming calls. I'll try to repeat it.

**Comment by alfredh** [comment]
I will close this issue for now. When you have the log and traces for the
scenario that you want to fix, please attach it here and re-open the Issue.
