### ISSUE TITLE
Baresip on Busybox 

### ISSUE THREAD

**Issue by gianlucadisimone** [alfredh/baresip#367]
There is possibility to install baresip on board with chip nuvoton n32926 with installed busybox 1.x?

Gianluca

**Comment by wnetbal** [comment]
Dear gianlucadisimone,

I use it on an older microcontroller with busybox v1.26, so I am pretty sure you get it up and running on your ARM9 core.

Kind regards
Wolfgang

**Comment by alfredh** [comment]
Hi @gianlucadisimone ,

do you have a bit more information about your chip and the OS that runs on it ?

in general it is possible to run baresip on many micrcontrollers, as long as it
has a medium speed 32-bit cpu and enough Flash/RAM. You also need a cross-compiler
to build libre+baresip for your target.

for example baresip is part of OpenWRT which runs on many embedded platforms.
You can see some details about how to cross compile it here:

https://github.com/openwrt/telephony/blob/master/net/baresip/Makefile

Alfred

**Comment by gianlucadisimone** [comment]
Hi Alfredh  I have board with CPU Nuvoton model N3292x with busybox v1.15.2 and want create Video SIP DOOR PHONE. 
I use openwrt and crosscomplie it for CPU mips so and now have to make the same thing for baresip on busybox , right? you know if exist a guide?

Gianluca

**Comment by alfredh** [comment]
do you have a cross compiler for your chip ? Perhaps you got this from your vendor ?

you can cross compile libre/baresip with:

```
$ make CC=cross-compiler-gcc
```

perhaps @wnetbal can share his guide for cross compilation?


In general this issues tracker is for tracking bugs and problems with baresip.
It may be better for you to ask on the mailing list:

http://lists.creytiv.com/mailman/listinfo/re-devel

Alfred

**Comment by gianlucadisimone** [comment]
@wnetbal can you share guide for cross compilation?

**Comment by wnetbal** [comment]
To be able to build baresip in my environment I have to set a few environment variables.
As Alfred already wrote I use the CC environment variable to set my cross compiler

export CC=cross-compiler-gcc

I had some problems to find the default functions and datatypes located in libc, but setting the SYSROOT variable to my location fixed that problem.

Additional I save all my binaries and includes to a staging directory, thats the reason why in the following code snippet using the variable STAGEDIR.

Here the relevant part of my Makefile.
```
VER =v0.5.8

export SYSROOT = ~/linux-uclibc/runtime/usr
export OS = linux
export LIBRE_SO=$(STAGEDIR)/usr/lib
export LIBRE_INC=$(STAGEDIR)/usr/include/re
export LIBRE_MK=$(STAGEDIR)/usr/share/re/re.mk
export LIBREM_PATH=$(STAGEDIR)/usr

all: $(VER)
        make -C $(VER) info
        make -C $(VER) install DESTDIR=$(STAGEDIR)

```

I hope you can use a some things from this commit.

Wolfgang

**Comment by ggrandis** [comment]
Hi guys and thanks for your support. I'm @gianlucadisimone colleague and working on cross compilation of baresip for arm. We need also video support (H264 and VP8), should we use eclipse to cross compile? Should be easier? We don't have so much experience with Makefile.
Tnx in advance
Giordano

**Comment by alfredh** [comment]
lets continue the discussion on the mailing list. The Issues tracker is mainly
for reporting bugs against baresip.
