### ISSUE TITLE
Documentation typo in modul ctrl_tcp

### ISSUE THREAD

**Issue by wnetbal** [alfredh/baresip#369]
In line 76 in file modules/ctrl_tcp/ctrl_tcp.c
in the description of the event response is a type 
modules/ctrl_tcp/ctrl_tcp.c
-"peer"       : "sip:bob@biloxy.com", 
+"peeruri"       : "sip:bob@biloxy.com", 

Kind regards
Wolfgang

**Comment by jmillan** [comment]
Thanks PR done.
