### ISSUE TITLE
Failed to link on archlinux.

### ISSUE THREAD

**Issue by diasbruno** [alfredh/baresip#375]
Hi,

Following the compilation steps in all repositories (re, rem and baresip)...

```shell
./baresip: error while loading shared libraries: libre.so: cannot open shared object file: No such file or directory
```

```shell 
$ ldd baresip                                                                                                                                                                 
        linux-vdso.so.1 (0x00007ffd054e4000)                                                                                                                                                     
        libre.so => not found
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f3cba3fb000)
        libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007f3cba191000)
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007f3cb9d14000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f3cb9afd000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f3cb98df000)
        librem.so => not found
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f3cb9593000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f3cb91dc000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f3cba83d000)
```

Simple workaround (for now):

```shell
LD_LIBRARY_PATH="../re:../rem" ./baresip
```

**Comment by alfredh** [comment]
after installing libre and librem, you need to run:

```
sudo ldconfig
```

make sure that the path to /usr/local/lib exist in /etc/ld.so.conf*


Alfred

**Comment by diasbruno** [comment]
Sorry, I forgot to mention the `ldconfig` step (even after this command it fails).

I'll check again to see if I made something wrong.

Thanks.

**Comment by alfredh** [comment]
Arch Linux is a supported platform, we are testing on it from time to time,
so it _should_ be working just fine.

do you have this line in `/etc/ld.so.conf` ?

```
/usr/local/lib
```

**Comment by alfredh** [comment]
https://aur.archlinux.org/packages/baresip/

**Comment by diasbruno** [comment]
Completely forget to give feedback. I've completely ignored when you mention this and just saw the command. 

That path is not on the list or any ld config in `ld.so.config.d/*.conf`. So, that's why the `LD_LIBRARY_PATH` worked.

**Comment by diasbruno** [comment]
Everything is linking correctly now. Thank you, @alfredh.

**Comment by diasbruno** [comment]
Since I don't have much experience on linking stuff, can I ask why this path was not included in the `ld.so.conf` by any of the linking steps?
