### ISSUE TITLE
Suggestion:  "vumeter_tcp"

### ISSUE THREAD

**Issue by Ken2050** [alfredh/baresip#377]
Hi,

I like to have the possibility to get VU meter values (in stereo) via tcp or mqtt.  Maybe a module "vumeter_tcp" that push out a JSON string on a 100 ms timer with the VU values.

Thanks!

**Comment by Ken2050** [comment]
Alfred, that would be great! Is it also possible to get levels for each audio channel, ex if the audio stream is in stereo?

Thanks!

**Comment by Ola-Palm** [comment]
Hi. This is something that would be very helpful for us in radio broadcast scenarios as well.  Relay via MQTT sound great, if we could set time intervall via Config, even better. 
/ Ola Palm

**Comment by alfredh** [comment]
So, to summarise:

You want to receive an event with the value of the average audio level (in -dB0V)
for the last 100 milliseconds (or configurable) for the following channels:

* Recording direction
* Playback direction
* For stereo, a channel index (0=left, 1=right)

**Comment by Ken2050** [comment]
Hi,

Alfred, yes that's exactly what I like to see, In tcp and MQTT.

Thanks!

**Comment by djhenley** [comment]
@alfredh , Ken2050 & Ola-Palm
I definitely agree, this sounds just perfect.
Recording/playback direction & stereo indication via MQTT, great! If we could set time interval via config, even better!! Anyone got a suggestion how to solve it?
Thanks!

**Comment by Ola-Palm** [comment]
Hi. I got a working example where the already calculated values from the module vumeter is pushed over mqtt as well as printed to screen.
It doesn’t show left/right values, only Tx/Rx.

**Comment by alfredh** [comment]
hi @Ola-Palm 

if you have some working code, would you like to submit a PR with your patch?
perhaps we can review it and test it.

Alfred

**Comment by alfredh** [comment]
hi,

I got a nice patch from @Ola-Palm which I made some improvements to:

https://gist.github.com/alfredh/5ad83d7a3fe4cead3f7ac80a9e1435a9

could you please all test this patch and see if works as expected?
(must be applied on top of master HEAD)

run baresip like this:

```
./baresip -mvumeter.so -v
```

you should see the periodic VU events, something like this:

```
menu: [ ua=sip:aeh@iptel.org call=7837c7434ed834ee ] event: VU_TX_REPORT (-59.16)
menu: [ ua=sip:aeh@iptel.org call=7837c7434ed834ee ] event: VU_RX_REPORT (-42.64)
menu: [ ua=sip:aeh@iptel.org call=7837c7434ed834ee ] event: VU_TX_REPORT (-70.67)
menu: [ ua=sip:aeh@iptel.org call=7837c7434ed834ee ] event: VU_RX_REPORT (-40.94)
menu: [ ua=sip:aeh@iptel.org call=7837c7434ed834ee ] event: VU_TX_REPORT (-82.19)
```

the value is in -dB0V, where -127.0 is silence and 0.0 is max volume.

**Comment by alfredh** [comment]
hi,

here is the PR:

https://github.com/alfredh/baresip/pull/450

@Ken2050 and @djhenley do you have some time to test this patch ?


Alfred

**Comment by djhenley** [comment]
@alfredh  & @Ola-Palm. This is great, thanks! We've actually planned to test the patch here tomorrow. I'll get back with feedback here during the day.

**Comment by alfredh** [comment]
thanks for testing. you should see both TX and RX values. are you getting
any audio packets? perhaps post the baresip output and enable `rtp_stats` config.

a PR is welcome, if you want to add support for configurable interval
in the vumeter module. please add the name of the module as prefix, e.g.:

```
vumeter_interval  100 # ms
```
