### ISSUE TITLE
Gstreamer 1.0 for gst_video?

### ISSUE THREAD

**Issue by ts468** [alfredh/baresip#38]
Hi,

is there any particular restriction in baresip that requires gstreamer 0.10 for gst_video? What would be needed to port it to gstreamer 1.0?

Many thanks,
Thomas

**Comment by czarkoff** [comment]
Feel free to file a pull request with your update to gst 1.0.

**Comment by alfredh** [comment]
we can upgrade modules gst.so and gst_video.so to Gstreamer 1.0
if that is someone we want/need.

Porting guide:
http://cgit.freedesktop.org/gstreamer/gstreamer/plain/docs/random/porting-to-1.0.txt

for porting to 1.0 I think we have 3 options:

1. upgrade to 1.0 and drop 0.10 support
2. upgrade to 1.0 and keep 0.10 support (compile-time switch)
3. do nothing (i.e. keep only 0.10 support).

What does people think ?

**Comment by alfredh** [comment]
I made a small attempt here:

https://github.com/alfredh/baresip/tree/gstreamer-1.0

so far gst.so fails with "Internal data flow error."

if people are willing to work on this and provide patches, I shall gladly accept them!

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> for porting to 1.0 I think we have 3 options:
> 
> 1. upgrade to 1.0 and drop 0.10 support
> 2. upgrade to 1.0 and keep 0.10 support (compile-time switch)
> 3. do nothing (i.e. keep only 0.10 support).
> 
> What does people think ?

1) would be fine with me.

-- juha

**Comment by czarkoff** [comment]
I would prefer upgrading to 1.0 *and* keeping 0.10. It would be probably served best by renaming current gst module to "gst-0.10" and adding new "gst-1.0" module. I guess project's resources are limited, so I would probably suggest to leave gst-0.10 to rot and have it removed once someone notices that it doesn't build any more.

**Comment by alfredh** [comment]
this is also possible :)

**Comment by singalen** [comment]
Voting for @czarkoff's option. 0.10 is ancient, and still I had a platform that required it not so long ago - the platform was also ancient, though.

The 1.0 module could be named just "gst"; otherwise we'll get stuck with the 1.0 name. For instance, GStreamer itself is at version 1.4 now, and still the packages everywhere have the confusing suffix "1.0".

**Comment by alfredh** [comment]
does anyone have time to help out with porting the module gst.so and gst_video.so
to 1.0 ? I can take care of the final testing and merging into baresip tree.

**Comment by ts468** [comment]
I started porting the gst_video module to gst 1.0, but I haven't finished it, yet. It is hard for me to predict when I'll be done, but it might take a while.

A question that I have in that respect is whether there is a way to use DMABUF for passing the data from the camera to the encoder? I could build a gst encoding pipeline that reads from the camera device directly, but then so far I don't know how that would interfere with the other functionality of baresip. Any thoughts?

**Comment by alfredh** [comment]
I think the first step should be to get something working, and then we can tune and optimize
after that.

Feel free to share your work-in-progress patch either here or on the re-devel
mailinglist :)

**Comment by alfredh** [comment]
thanks to Thomas for the initial patch :)

after some trimming and tuning I managed to get the gst_video working with 1.0

https://github.com/alfredh/baresip/commit/1bde01b6cad76a558d06f702078a33e878b21ee7

some open issues:

- is it necessary to have all these mutexes and conditionals to sync between the 2 threads?

- the encode/pipeline_push function should not block, i.e. it should not call cond_wait.
 the whole libre/baresip execution model is based on async I/O with small functions
 running very fast and not blocking. If the GST encoder is very busy and the buffer
 is full, I guess the only thing we can do is to drop raw frames from the camera ?

**Comment by ts468** [comment]
@alfredh, thank you very much for your efforts to port gst_video to 1.0!

My thoughts about the issues:
- Looking at the interface to video codecs in general, as defined in "struct vidcodec", it seems as the async I/O is on the calling side of the interface. From my quick look into the other modules I thought that 'encupdh' and 'ench' are called asynchronously and 'fmtp_ench' and '	fmtp_cmph' are called synchronously from within 'ench'? So I just wonder why there should be another asynchronous coupling when calling into the gst_video module. You know the source better than me, so please correct me if I'm wrong. :) So if introducing another layer of asynchronous coupling, then I'm wondering about the calling of fmtp_ench/fmtp_cmph, that is for sending out the data after they left the encoder?

- An interesting question about the async I/O system is, I guess, how the pipeline is managed, that is how information, e.g., for setting the framerate, is propagating upwards and downwards to the processing stages.
For example, I wonder whether it would be better to dynamically reduce or adapt the framerate when the encoder or sending stage can't keep up. Especially, the gst pipeline seems to assume a fixed framerate anyway, and I'm unsure how the pipeline is affected by simply not feeding enough data into it. The question how to manage the pipeline somehow relates back to the question how asynchronous or synchronous the pipeline is designed, and led me to step-lock 'ench' and gst so to not introduce a hidden, loose coupling within gst_video.

**Comment by alfredh** [comment]
this commit should add the 2 new module gst1.so and gst_video1.so

you can build gst_video1.so by installing the correct gstreamer-dev header files,
or enable it explicitly:

$ make USE_GST_VIDEO1

Testing and feedback it welcome :)
