### ISSUE TITLE
Encountered unknown AudioTrack event 6 for CAudioPlayer 0x61a1d860

### ISSUE THREAD

**Issue by cloud-jxy** [alfredh/baresip#380]
I use baresip lib to develop a android app. When hungup, the app crash. There is the log on Logcat  view:

04-16 15:11:49.065 24839-24839/com.xyt.baresip E/baresip: call: terminate call 'dfaefb50d289dd0e' with sip:9196@xswitch.cn:7060
04-16 15:11:49.155 24839-24902/com.xyt.baresip E/libOpenSLES: Encountered unknown AudioTrack event 6 for CAudioPlayer 0x61a1d860

By breakpoint debugging, I find the crash code. The position is baresip/modules/opensles/recorder.c:43.

static void ausrc_destructor(void *arg)
{
	struct ausrc_st *st = arg;

	if (st->recObject != NULL) {
		SLuint32 state;

		if (SL_OBJECT_STATE_UNREALIZED !=
		    (*st->recObject)->GetState(st->recObject,&state)) {
			(*st->recObject)->Destroy(st->recObject);
		}
	}

	st->bufferId = 0;
	for (int i=0; i<N_REC_QUEUE_BUFFERS; i++) {
		mem_deref(st->sampv[i]);
	}
}

crash on running " (*st->recObject)->Destroy(st->recObject);".

**Comment by alfredh** [comment]
does it crash on a specific device, or in the emulator (or both) ?

I am running baresip on Samsung J5 and emulator, no crash.

perhaps you could add a line with printf to print the pointer of
` (*st->recObject)->Destroy(st->recObject);` ? if the pointer is NULL
we can check it. if the pointer is valid, then perhaps the crash is
happening inside the audio driver.

Alfred

**Comment by cloud-jxy** [comment]
I have debug it. There is no null pointer. All the params look right.
The crash happen on android 19. But, it don't happen on newest android os.

**Comment by alfredh** [comment]
do you have any more debug info about the crash, for example more
logs and backtraces?

does it only crash on one device using Android 19 or more devices?

does it crash on e.g. Android 18 or 20 ?

**Comment by alfredh** [comment]
could you please test this patch:

```
diff --git a/modules/opensles/recorder.c b/modules/opensles/recorder.c
index b26190b..e3645b1 100644
--- a/modules/opensles/recorder.c
+++ b/modules/opensles/recorder.c
@@ -38,8 +38,9 @@ static void ausrc_destructor(void *arg)
        if (st->recObject != NULL) {
                SLuint32 state;
 
-               if (SL_OBJECT_STATE_UNREALIZED !=
-                   (*st->recObject)->GetState(st->recObject,&state)) {
+               if (SL_RESULT_SUCCESS ==
+                   (*st->recObject)->GetState(st->recObject, &state) &&
+                   SL_OBJECT_STATE_UNREALIZED != state) {
                        (*st->recObject)->Destroy(st->recObject);
                }
        }
```

it looks like the original code for checking the object state is wrong.
calling Destroy should only be done if the state is realized.
