### ISSUE TITLE
audio breaking up in OSX

### ISSUE THREAD

**Issue by galberti** [alfredh/baresip#382]
Hello,
after successfully starting a call, when rtp stream comes in I get

main: long async blocking: 210>100 ms (h=0x104d8c790 arg=0x7fb9b2c0a4e0)

(not sure if relevant) and the audio is broken, with clips here and there, similar to clipping due to high levels after the decoder. Encoder used is PCMA 8000Hz 1ch, coreaudio module. I am not sure what further information I can provide.

**Comment by galberti** [comment]
hello @alfredh 
thank you for your answer. After running baresip -v I got loads of these
audio: rx aubuf overrun (total 1)
audio: rx aubuf overrun (total 2)
...
I made some research in the code, increased the ptime in the account file, all is OK now. 
Justo FYI, I am using OSX 10.13.4, v0.5.8 with coreaudio module.

Thank you for your help!

**Comment by alfredh** [comment]
hi @galberti 

do you still have the issue, or is it working for you now ?

**Comment by galberti** [comment]
Hi @alfredh 
it's working, as reported above it was a too small ptime setting. We can close the issue.

Thanks for your support!
