### ISSUE TITLE
How to use realm and SIP proxy server

### ISSUE THREAD

**Issue by drscream** [alfredh/baresip#383]
At the moment the following information are provided to me from my SIP provider:

- username (for authentication)
- password
- realm (which is not an IP address or hostname)
- SIP server IP address

Somehow I fail to configure `baresip` correctly to use these credentials but they work well with linphone. Also from the examples for accounts I'm not sure how to combine these information correctly to be sure the authentication is working.

What I've tried:

```
<sip:USERNAME@REALM;transport=udp>;auth_user=USERNAME;outbound="sip:SIP_IP_ADDRESS;transport=udp"
```

or

```
<sip:USERNAME@SIP_IP_ADDRESS;transport=udp>;auth_user=USERNAME@REALM
```

Maybe I miss something here?

**Comment by GGGO** [comment]
Try this: `<sip:username@sip_ip_address>;auth_pass=password`

**Comment by drscream** [comment]
@GGGO well the realm is required to authenticate correctly or use the SIP provider.

**Comment by alfredh** [comment]
hi @drscream  can you share the baresip log and possibly also the SIP traffic ?

the `realm` is usually part of the authenticate challenge that comes from the server
and it is not something that the client should configure.

example SIP trace with iptel.org:

```
SIP/2.0 401 Unauthorized.
WWW-Authenticate: Digest realm="iptel.org", nonce="WtzWr1rc1FdAsCD3BKspCqOeHhJHmf00".
```


```
REGISTER sip:iptel.org SIP/2.0.
Authorization: Digest username="aeh", realm="iptel.org", nonce="WtzWr1rc1FdAsCD3BKspCqOeHhJHmf00", uri="sip:iptel.org", response="0b63c591bb86d4d59af3263b29fa3e00".
```

the Client copies the "realm" value from the response to the new request.

to configure baresip you need username, password and domain. The outbound proxy
is optional:

```
<sip:user@domain.com>;auth_pass=XXX;outbound="sip:1.2.3.4"
```

perhaps in your case the realm is the same as domain ?

Alfred

**Comment by drscream** [comment]
Hello @alfredh,

thanks a lot, it looks like it's more or less a different issue than I thought. With `linphone` i've configured an proxy which is used for the connection and the domain (for the registration) is used as realm for authentication.

![linphone screenshot](http://up.frubar.net/3793/2018-04-23-113712_527x323_scrot.png)

Also `ngrep` logs it look different:

**baresip** (no response from the server)

```
#
U 192.168.4.225:21994 -> 10.11.1.31:5060
REGISTER sip:10.11.1.31;transport=udp SIP/2.0.
Via: SIP/2.0/UDP 192.168.4.225:21994;branch=z9hG4bKd6b0b1fa381f5cd0;rport.
Contact: <sip:5107-0x8018ee2c0@192.168.4.225:21994>;expires=3684;+sip.instance="<urn:uuid:891fa6c7-8713-b00a-10e3-efe49c3e3c00>".
Max-Forwards: 70.
To: <sip:5107@10.11.1.31>.
From: <sip:5107@10.11.1.31>;tag=73ac88d3d73831b4.
Call-ID: 69cbb6c4ed9a75a4.
CSeq: 34041 REGISTER.
User-Agent: baresip v0.4.19 (amd64/freebsd).
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,REFER,NOTIFY,SUBSCRIBE,INFO,MESSAGE.
Content-Length: 0.
.
```

**linphone** (response maybe because proxy is used and realm is correct)

```
#
U 10.12.7.17:5060 -> 10.11.1.31:5060
REGISTER sip:specialcust SIP/2.0.
Via: SIP/2.0/UDP 10.12.7.17:5060;branch=z9hG4bK.Pe1FeTDl3;rport.
From: <sip:5107@specialcust>;tag=dsxecmuHL.
To: sip:5107@specialcust.
CSeq: 20 REGISTER.
Call-ID: D3OVLwyEmZ.
Max-Forwards: 70.
Supported: replaces, outbound.
Accept: application/sdp.
Accept: text/plain.
Accept: application/vnd.gsma.rcs-ft-http+xml.
Contact: <sip:5107@10.12.7.17;transport=udp>;+sip.instance="<urn:uuid:70e150f7-1caf-4421-a1dd-b2364c046c69>".
Expires: 3600.
User-Agent: Linphone/3.10.2 (belle-sip/1.5.0).
.

#
U 10.11.1.31:5060 -> 10.12.7.17:5060
SIP/2.0 401 Unauthorized.
Via: SIP/2.0/UDP 10.12.7.17:5060;branch=z9hG4bK.Pe1FeTDl3;rport=5060;received=10.12.7.17.
From: <sip:5107@specialcust>;tag=dsxecmuHL.
To: <sip:5107@specialcust>;tag=2755876490.
Call-ID: D3OVLwyEmZ.
CSeq: 20 REGISTER.
Server: OpenScape 4000 - HiPath 4000 SoftGate.
WWW-Authenticate: Digest realm="specialcust",nonce="xxxxx",algorithm=MD5.
Content-Length: 0.
.

#
U 10.12.7.17:5060 -> 10.11.1.31:5060
REGISTER sip:specialcust SIP/2.0.
Via: SIP/2.0/UDP 10.12.7.17:5060;branch=z9hG4bK.PZ4JvijOT;rport.
From: <sip:5107@specialcust>;tag=dsxecmuHL.
To: sip:5107@specialcust.
CSeq: 21 REGISTER.
Call-ID: D3OVLwyEmZ.
Max-Forwards: 70.
Supported: replaces, outbound.
Accept: application/sdp.
Accept: text/plain.
Accept: application/vnd.gsma.rcs-ft-http+xml.
Contact: <sip:5107@10.12.7.17;transport=udp>;+sip.instance="<urn:uuid:70e150f7-1caf-4421-a1dd-b2364c046c69>".
Expires: 3600.
User-Agent: Linphone/3.10.2 (belle-sip/1.5.0).
Authorization:  Digest realm="specialcust", nonce="xxxxxx", algorithm=MD5, username="5107",  uri="sip:specialcust", response="37bc08f734b3ad511dc22e5271e14f51".
.

#
U 10.11.1.31:5060 -> 10.12.7.17:5060
SIP/2.0 200 OK.
Via: SIP/2.0/UDP 10.12.7.17:5060;branch=z9hG4bK.PZ4JvijOT;rport=5060;received=10.12.7.17.
From: <sip:5107@specialcust>;tag=dsxecmuHL.
To: <sip:5107@specialcust>;tag=2755090578.
Call-ID: D3OVLwyEmZ.
CSeq: 21 REGISTER.
Contact: <sip:5107@10.12.7.17;transport=udp>;expires=3223.
Expires: 3223.
Server: OpenScape 4000 - HiPath 4000 SoftGate.
Content-Length: 0.
```

Do you have any idea to maybe provide the proxy configuration also to baresip as well?

**Comment by alfredh** [comment]
baresip 0.4.19 is very old :) you should upgrade to latest.

is there IP connectivity from 192.168.4.225:21994 -> 10.11.1.31:5060 ?

**Comment by drscream** [comment]
@alfredh i've updated to the latest version of baresip (v0.5.8) but this basically do not change the issue :-)
The connection is possible from 192.168.4.225 to 10.11.1.31 without any issue, also the connection works with linphone so I do not expect a network issue itself.

**Comment by alfredh** [comment]
due to lack of response, I am closing this one.
