### ISSUE TITLE
Different channels/audio devices per call

### ISSUE THREAD

**Issue by Frando** [alfredh/baresip#384]
Hi,
is it possible to route different calls to different audio devices? 
If I have a soundcard with e.g. 3 stereo out channels, is it possible to have baresip route each incoming call to a different channel (when multiple calls happen at the same time)?
Thanks,
Franz

**Comment by alfredh** [comment]
hi @Frando 

this is not possible with the current codebase.

the audio config is global, and applies for all accounts and calls:

```
# Audio
audio_player            portaudio,1
audio_source            coreaudio,0
audio_alert             coreaudio,null
```

we could add the option to override this on a per account basis,
for example:

`<sip:user@domain>;audio_player="coreaudio,foo";audio_source="coreaudio,bar"`

if we have this, and you want to achieve your feature, you can just register 3 useragents
with the same SIP account but different audio devices. The first account to receive the call
will answer it, and the rest will be cancelled.

the other option for you is to implement some custom logic to handle this :)


Alfred

**Comment by premultiply** [comment]
Hi @alfredh,

would it be possible to add the per account override for the audio devices as you suggested above?
This would be perfect for studio call-in applications.

Thanks!
