### ISSUE TITLE
Media transmission disabled if attr a:sendonly set on stream

### ISSUE THREAD

**Issue by AndreasHansson73** [alfredh/baresip#385]
Hi!
The default in baresip is to set the media stream attribute a:sendrecv on a video stream. But if I set a:sendonly , no video is sent. 

I tried to change the line 504 in function stream_send in stream.c from
`
    if (sdp_media_dir(s->sdp) != SDP_SENDRECV)
`
to 

`
    if (!(sdp_media_dir(s->sdp) & SDP_SENDONLY))
`
And it seemed to solve the problem. 

I do not fully understand if there are side effects of this change, so what do you think about it? 

Also, this change will add a:sendonly to a video stream if there are no displays.
On line 833 in video.c add
`    if (vidisp_find(baresip_vidispl(), NULL) == NULL)
        sdp_media_set_ldir(v->strm->sdp, SDP_SENDONLY);
`
How about that?

**Comment by alfredh** [comment]
hi @AndreasHansson73 

many thanks for the report and the suggested fixes.

the SDP direction is a bitfield enum, defined in `re_sdp.h`:

```
/** SDP Direction */
enum sdp_dir {
	SDP_INACTIVE = 0,
	SDP_RECVONLY = 1,
	SDP_SENDONLY = 2,
	SDP_SENDRECV = 3,
};
```

so SENDRECV is an alias for RECVONLY+SENDONLY.
sdp_media_dir is a combination of the ldir and rdir (local and remote) state in the SDP.

when we are doing a local call host, the local dir is set to SENDONLY:

```
void stream_hold(struct stream *s, bool hold)
{
	if (!s)
		return;

	sdp_media_set_ldir(s->sdp, hold ? SDP_SENDONLY : SDP_SENDRECV);
}
```

I will do some testing of this, and also check what the RFC says.

The second change is also very useful and elegant :)


Alfred

**Comment by AndreasHansson73** [comment]
Hi @alfredh 
I will test this and write a PR. I will get back with the result in a couple of days.

Andreas

**Comment by AndreasHansson73** [comment]
@alfredh I created a PR: https://github.com/alfredh/baresip/pull/423

I also wrote a question on your commit.

**Comment by AndreasHansson73** [comment]
@alfredh I tested https://github.com/alfredh/baresip/commit/6c4c557cb6f624e230f063c7e0f418ebc6042c48
and it seems to work fine for me. I am using two computers both of them are running baresip and I am doing a direct call. I manually changed the code on one side so `sendonly` was used on the video stream. Both parties behaved as expected.

**Comment by alfredh** [comment]
Great, thanks for testing!
