### ISSUE TITLE
v4l2.c mplane capture support

### ISSUE THREAD

**Issue by RobGries** [alfredh/baresip#386]
Is it possible to use mplane capture support with the v4l2 capture module in baresip?

I am learning now that my camera seems to only support this mode of capure.

**Comment by alfredh** [comment]
hi @RobGries 

I am wondering what is mplane support?

Any logs you can share, or v4l2-ctl dump of your camera ?


Alfred

**Comment by alfredh** [comment]
I will close this Issue now, as I dont understand the request.

If you can provide more info, then please reopen it.
