### ISSUE TITLE
baresip: different hashes between the github and website releases

### ISSUE THREAD

**Issue by micmac1** [alfredh/baresip#388]
Hi Alfred,

I downloaded baresip-0.5.9.tar.gz from http://www.creytiv.com/pub and from the github release section. While there is no difference between the contents, the checksums differ.
```

6a4b4c0d26932aa9abcbbc2ad401285e  baresip-0.5.9.github.tar.gz
40fae16eca6f5fe3cdd3435b0cb07e99  baresip-0.5.9.www.tar.gz
```
This isn't very nice. People might get suspicious that something funky is going on only to find out that there's no difference. But it causes unnecessary extra efforts.

;-)

Kind regards,
Seb

**Comment by micmac1** [comment]
Same for re/rem :)

**Comment by jungle-boogie** [comment]
I think the openBSD ports group discovered this recently:
https://marc.info/?l=openbsd-ports&m=151973450514279&w=2

> These are *not* guaranteed to be stable, they can change as github
> update software and caches expire (this has happened at some point over
> the last few months so we have been seeing a number of hash failures
> recently).

**Comment by alfredh** [comment]
it looks like there is a small difference in the header:

```
-00000000: 1f8b 0800 543b db5a 0003 ec3c 6977 db46  ....T;.Z...<iw.F
+00000000: 1f8b 0800 0000 0000 0003 ec3c 6977 db46  ...........<iw.F
```

the tarball on the www.creytiv.com server is generated using this command:

```
$ make git_release
```

and also the SHA256 hash is generated from that binary.

do you think we should copy the Assets (tarball) from github instead ?


Alfred

**Comment by micmac1** [comment]
Hi Alfred,

If I understand the text you provided correctly, it's possible to upload your own tarball to github, preventing regeneration by github scripts. That sounds like the way to go. You could even sign your releases cryptographically if you wanted.

Kind regards,
Seb

**Comment by alfredh** [comment]
then I see two alternatives:

1. use github release tarball as the reference, and copy it to www.creytiv.com
  as part of the release process.

2. use www.creytiv.com release tarball as reference, and upload to github.

I think I prefer alternative 1 since it means one less step for me.

current released files will not be changed. the next release of re/rem or baresip
will then follow this scheme.

sounds good @micmac1 ?

Thanks for reporting this BTW.

**Comment by micmac1** [comment]
Am May 12, 2018 9:02:23 PM UTC schrieb "Alfred E. Heggestad" <notifications@github.com>:
>then I see two alternatives:
>
>1. use github release tarball as the reference, and copy it to
>www.creytiv.com
>  as part of the release process.
>
>2. use www.creytiv.com release tarball as reference, and upload to
>github.
>
>I think I prefer alternative 1 since it means one less step for me.
>
>current released files will not be changed. the next release of re/rem
>or baresip
>will then follow this scheme.
>
>sounds good @micmac1 ?
>
>Thanks for reporting this BTW.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/alfredh/baresip/issues/388#issuecomment-388582637

The text sounds like github generated release tarballs do not guarantee a stable hash. The hash may change over time. So #2 would be great, as with #1 there is still a chance of differing hashes.

**Comment by alfredh** [comment]
Aha, I get it now.

I uploaded the tarball from www.creytiv.com for baresip version 0.5.9 here:

https://github.com/alfredh/baresip/releases/download/v0.5.9/baresip-0.5.9.tar.gz

could you please test it and see if this is what you want ?

The link to "Source Code (tar.gz)" is still there, though.

**Comment by micmac1** [comment]
Hello Alfred,

Now the checksums are the same. That looks good. Thank you very much!

I think it's normal that the github generated source still shows up. See
this project: https://github.com/fln/addrwatch/releases

It's the same. The author uploaded his/her own release and github
generated another tar.gz. The checksums differ. I don't see a problem
with that, as long as there's one reliable package up on github.

Again, thank you!

Kind regards,
Seb

**Comment by alfredh** [comment]
I have also uploaded tarballs for re/rem:

https://github.com/creytiv/re/releases/tag/v0.5.8

https://github.com/creytiv/rem/releases/tag/v0.5.3

so I will change the release procedure a bit then; after the version
is released and tagged, I will generate a tarball and upload it to
www.creytiv.com and github.

older releases will just stay as they are.

**Comment by alfredh** [comment]
hi @micmac1 okay to close this one now ?

**Comment by micmac1** [comment]
Am May 13, 2018 12:34:14 PM UTC schrieb "Alfred E. Heggestad" <notifications@github.com>:
>hi @micmac1 okay to close this one now ?
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/alfredh/baresip/issues/388#issuecomment-388623646

Hi Alfred,

Sure, all OK. Have a good Sunday!

Thanks,
Seb
