### ISSUE TITLE
Reregister after half expire time failed with 401 Unauthorized 

### ISSUE THREAD

**Issue by wnetbal** [alfredh/baresip#390]
I build the latest version of baresip, libre and librem on my ubuntu 16.04 amd64 and connected to a local asterisk server with IP 192.168.1.10.

I set the expire time to 120 seconds (regint=120) 

The registration works fine after adding the ua with /uanew but after the half expire time baresip tries to refresh the registration by sending a new REGISTER
The server answers with 401 Unauthorized because the REGISTER has no authentification data, but then nothing happens.
When running /reginfo I see that the server is in ERR

When the exprire time reached baresip sends a REGISTER to server, gets again a 401 Unauthorized and then sends REGISTER with authentification data and status in /reginfo changed to OK.

Please find attached a wireshark capture [Baresip_reregister.pcapng.zip](https://github.com/alfredh/baresip/files/1973618/Baresip_reregister.pcapng.zip)

Here is the output to baresip shell

/uanew Baresip <sip:6011@192.168.1.10:5060;transport=udp>;regint=120;auth_pass=1234;auth_user=6011;answermode=manual
Creating UA for Baresip <sip:6011@192.168.1.10:5060;transport=udp>;regint=120;auth_pass=1234;auth_user=6011;answermode=manual ...
> sip:6011@192.168.1.10:5060                 zzz 

6011@192.168.1.10: {0/UDP/v4} 200 OK (Asterisk PBX 13.1.0~dfsg-1.1ubuntu4.1) [1 binding]
All 1 useragent registered successfully! (41140 ms)
reg: sip:6011@192.168.1.10:5060: 401 Unauthorized (Asterisk PBX 13.1.0~dfsg-1.1ubuntu4.1)
6011@192.168.1.10: {0/UDP/v4} 200 OK (Asterisk PBX 13.1.0~dfsg-1.1ubuntu4.1) [1 binding]

/uastat
--- sip:6011@192.168.1.10:5060 ---
 nrefs:     1
 cuser:     6011-0x25df850
 pub-gruu:  
 af:        AF_INET
 Supported: gruu

Account:
 address:      Baresip <sip:6011@192.168.1.10:5060;transport=udp>;regint=120;auth_pass=1234;auth_user=6011;answermode=manual
 luri:         sip:6011@192.168.1.10:5060;transport=udp
 aor:          sip:6011@192.168.1.10:5060
 dispname:     Baresip
 answermode:   manual
 auth_user:    6011

 mediaenc:     none
 medianat:     none
 ptime:        20
 regint:       120
 pubint:       0
 regq:         
 rtpkeep:      
 sipnat:       
 stunserver:   stun:6011@192.168.1.10:0

Register client:
 id:     0
 scode:  200 (OK )
 srv:    Asterisk PBX 13.1.0~dfsg-1.1ubuntu4.1

Kind regards
Wolfgang

**Comment by alfredh** [comment]
I think this is a bug in Asterisk. Baresip will cache the authentication challenge
so that it only has to send 1 subsequent REGISTER instead of 2. If the server does not want
to use the cached challenge, it should reply with 401/403 and include the parameter
`stale=true` in the authentication challenge.

here is the message sequence with the Digest authentication extracted:

```
REGISTER 1:
(none)

401:
WWW-Authenticate: Digest algorithm=MD5, realm="asterisk", nonce="7b040269".

REGISTER 2:
Authorization: Digest username="6011", realm="asterisk", nonce="7b040269", uri="sip:192.168.1.10:5060;transport=udp", response="2c22f839aed3ebd0df88930e4fdc77f2".

200:
(none)

REGISTER 3:
Authorization: Digest username="6011", realm="asterisk", nonce="7b040269", uri="sip:192.168.1.10:5060;transport=udp", response="2c22f839aed3ebd0df88930e4fdc77f2".

401:
WWW-Authenticate: Digest algorithm=MD5, realm="asterisk", nonce="4af727c7".
```

the code to handle "stale" is already in libre (src/sip/auth.c:)

```
		if (!pl_isset(&ch.stale) || pl_strcasecmp(&ch.stale, "true")) {
			err = EAUTH;
			goto out;
		}
```

do you have the asterisk log, in the same time period as the REGISTER happens ?
could you also test with a different version of Asterisk and see if the result is the same ?

**Comment by wnetbal** [comment]
Dear Alfred,

thanks a lot for your answer.
You are right it was a failed configuration of asterisk, on another server it works fine.

Kind regards
Wolfgang
