### ISSUE TITLE
Enable Speaker on Android

### ISSUE THREAD

**Issue by Hmart** [alfredh/baresip#391]
Im not able to control the opensles audio stream, more specifically enabling and disabling the speaker mode within my android application. 

Im currently building Baresip with some minor adjustments to the openSLES module in order for this to work.

https://github.com/Hmart/baresip/commit/96fc1bfe2a6b7c5ccb56b5ba5898fe5f972bb040

The patch works by setting an Android specific stream type which allows me to control the stream via the Android AudioManager.

Is there any other way to handle the native stream within an android application or is this the way to go?

thanks.

**Comment by juha-h** [comment]
Hannes Martinsson writes:

> Im not able to control the opensles audio stream, more specifically
> enabling and disabling the speaker mode within my android application. 
> 
> Im currently building Baresip with some minor adjustments to the
> openSLES module in order for this to work. 
> 
> https://github.com/Hmart/baresip/commit/96fc1bfe2a6b7c5ccb56b5ba5898fe5f972bb040
> 
> The patch works by setting an Android specific stream type which
> allows me to control the stream via the Android AudioManager. 
> 
> Is there any other way to handle the native stream within an android
> application or is this the way to go?

Hannes,

Nice to notice that also some other people are developing baresip for
Android.

I have played a bit with AudioManager:

  am = appContext.getSystemService(Context.AUDIO_SERVICE) as AudioManager
  ...
  am.mode = AudioManager.MODE_IN_COMMUNICATION
  am.isSpeakerphoneOn = false
  am.setStreamVolume(AudioManager.STREAM_VOICE_CALL, N,
      AudioManager.STREAM_VOICE_CALL))
  ...
  am.mode = AudioManager.MODE_RINGTONE
  am.isSpeakerphoneOn = true

Are you saying that the above does not work?

How are you controlling speaker mode after your patch?

-- Juha

**Comment by Hmart** [comment]
Hi Juha,

It seems like the patch is unnecessary, it enables using the audiomangers IN_CALL mode. however it seems like the more appropriate mode for a voip app would be [IN_COMMUNICATION](https://developer.android.com/reference/android/media/AudioManager.html#MODE_IN_COMMUNICATION), which seems to resolve the issues I was previously having.

Regarding your code, toggling the speakerMode does not work for me properly using the MODE_RINGTONE.
The following snippet works just fine tho! 

```
mAudioManager = (AudioManager) getSystemService(Context.AUDIO_SERVICE); 
mAudioManager.setMode(AudioManager.MODE_IN_COMMUNICATION);
mAudioManager.setSpeakerphoneOn(!mAudioManager.isSpeakerphoneOn());
```

Im closing this issue.
