### ISSUE TITLE
ctrl_tcp module lack licensing

### ISSUE THREAD

**Issue by jonassmedegaard** [alfredh/baresip#393]
Hi,

Files modules/ctrl_tcp/* have different copyright from generally in the baresip project, and lacks licensing.

Files modules/ctrl_tcp/netstring/* lack both copyright and licensing - and according to http://lists.creytiv.com/pipermail/re-devel/2017-December/001137.html is also not by same author as generally for the project.

Please include copyright and licensing statements for (at least) above files.

Also, please consider consistently adding copyright and licensing statements (even just a single line for each) at the top of each and every file substantial enough for being copyright-protected in most jurisdictions. Mentioning a project-wide copyright and licensing is not reliable, especially when more than a single copyright holder is involved.

**Comment by alfredh** [comment]
Hi @jonassmedegaard 

many thanks for your feedback! We can add copyright headers to the ctrl_tcp module.
The netstring code is from an external author and should be attributed properly.

@jmillan would you like to update the ctrl_tcp module ?

All files have a copyright header but not license info, for example main.c:

```
/**
 * @file src/main.c  Main application code
 *
 * Copyright (C) 2010 - 2015 Creytiv.com
 */
```

the default license for all files is BSD license, unless explicitly stated.

I dont want to update all the source files with this license info, it will just add more
clutter to the source code. 

Many other open source projects have a huge header in every single .c file
with a full license text, which is very annoying. After opening a file in xemacs you have
to scroll down many pages before you can start to read the code.


Alfred

**Comment by jmillan** [comment]
So all files related to tcp_ctrl have the copyright info:

```
$ head -n6 modules/ctrl_tcp/*
==> modules/ctrl_tcp/ctrl_tcp.c <==
/**
 * @file ctrl_tcp.c  TCP control interface using JSON payload
 *
 * Copyright (C) 2018 46 Labs LLC
 */


==> modules/ctrl_tcp/module.mk <==
#
# module.mk
#
# Copyright (C) 2018 46 Labs LLC
#


==> modules/ctrl_tcp/netstring <==
head: Error reading modules/ctrl_tcp/netstring

==> modules/ctrl_tcp/tcp_netstring.c <==
/**
 * @file tcp_netstring.c  TCP netstring framing
 *
 * Copyright (C) 2018 46 Labs LLC
 */


==> modules/ctrl_tcp/tcp_netstring.h <==
/**
 * @file tcp_netstring.h  TCP netstring framing
 *
 * Copyright (C) 2018 46 Labs LLC
 */
```

The license is BSD unless explicitly stated, as for the rest of the project, so no need to explicitly add here unless it's added everywhere else IMHO.

Definitely the copyright and license related to `netstring-c` is missing. Let me fix that.

**Comment by jmillan** [comment]
https://github.com/PeterScott/netstring-c/issues/5

**Comment by alfredh** [comment]
Great @jmillan thanks !

**Comment by jmillan** [comment]
Added licensing text according to nestring-c author suggestion.

**Comment by jonassmedegaard** [comment]
Thanks! That helps our redistribution of Baresip in Debian.

**Comment by alfredh** [comment]
patch from @jmillan merged to master.

thanks @jonassmedegaard and @jmillan !
