### ISSUE TITLE
BareSIP multiple audio

### ISSUE THREAD

**Issue by AndyW999** [alfredh/baresip#399]
Hi All

Please could anybody give me an idea of how to solve my audio problem?

I want to use Baresip with 2 user agents - fine.

My target which is an Olimex A20 board which has one stereo audio device.

I would like one ua to use the left channel and the other to use the right channel.

Any ideas?

Thanks

Andy.

**Comment by alfredh** [comment]
hi @AndyW999 

the audio device config is global, i.e. it applies to all useragents.

a workaround can be to run multiple instances of baresip, with different audio device config.

perhaps you can use ALSA to map the different channels to different virtual devices ?

you can also test the `jack` audio device module.


Alfred

**Comment by AndyW999** [comment]
Hi Alfred

Please could you tell me how to run multiple instances and not have a conflict with binding to 5060?

Thanks

Andy.

**Comment by juha-h** [comment]
AndyW999 writes:

> Please could you tell me how to run multiple instances and not have a
> conflict with binding to 5060?

you can change listening port in config (sip_listen).

-- juha

**Comment by AndyW999** [comment]
But that also means that the SIP switch would have to have another port enabled and exposed.

I know it is not a problem for me as FreeSwitch has 5080 available for external ports.

But it would be nice to do it without.

**Comment by AndyW999** [comment]
Will give it a try soon...

Thanks

Andy.
