### ISSUE TITLE
attended transfer

### ISSUE THREAD

**Issue by axonaro** [alfredh/baresip#402]
Здравствуйте

Спасибо за вашу работу.

Мои вопросы:
1) Возможно ли добавить функционал перевода с уведомлением?
2) Я сделал два исходящих вызова, возможно ли сделать перевод одного вызова на другой?

Спасибо.

---- google translate :

Hello

Thanks for your work.

My questions:
1) Is it possible to add translation functionality with notification?
2) I made two outgoing calls, is it possible to transfer one call to another?

Thank you.

**Comment by alfredh** [comment]
hi @axonaro 

not sure if your google translate was correctly translater, but if you are asking
about _translation_ features I'm afraid that this is outside the scope for baresip.

regarding Call Transfer, yes it is supported.

In an active call, you can use the `/transfer` or `t` command to transfer the
current call to another target.

Alfred

**Comment by axonaro** [comment]
Yes, i asking about call transfer.

/transfer is UnattendedTransfer (or BlindTransfer) feature.

What about AttendedTransfer feature?

**Comment by alfredh** [comment]
Attended transfer is not supported.

**Comment by xllwhoami** [comment]
> 

why

/transfer
command not found (transfer)
