### ISSUE TITLE
ipv4 scope global vs scope host

### ISSUE THREAD

**Issue by nshopik** [alfredh/baresip#403]
i have vm where have 2 ipv4 address where first one 127.0.0.2/32 with scope host and second routable with scope global. How can I force baresip ignore 127.0.0.2 and don't announce when establishing RTP session?

**Comment by alfredh** [comment]
hi @nshopik 

you can force baresip to use a specific network interface, by setting this
in `~/.baresip/config`:

```
net_interface          eth0
```

did you already try this ?


Alfred

**Comment by nshopik** [comment]
Hi @alfredh both address on same interface. Maybe ignore or make lowest priority for scope host?
```
4: venet0: <BROADCAST,POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN 
    link/void 
    inet 127.0.0.2/32 scope host venet0
    inet 192.0.2.1/32 brd 192.0.2.1 scope global venet0:0
```

**Comment by alfredh** [comment]
hi @nshopik 

could you please try this commit 507cf074ddd1495c460d89833552cab47e9c04e8

add this to your config:

```
net_interface    192.0.2.1
```

**Comment by nshopik** [comment]
Yeah, this one fixes problem
