### ISSUE TITLE
auth_user should not be set by by default to uri.user

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#407]
I noticed that when I allocate new user agent using ua_alloc() API function with aor parameter "<sip:foo@bar>;regint=0", auth_user is set to "foo".  I'm  my opinion, auth_user should be left empty instead, since it may be that no authentication is needed or that value "foo" is not correct.

Looks like it is done here in account.c/sip_params_decode:

	if (0 == msg_param_decode(&aor->params, "auth_user", &auth_user))
		err |= pl_strdup(&acc->auth_user, &auth_user);
	else
		err |= pl_strdup(&acc->auth_user, &aor->uri.user);

If people agree, I can leave the else part out.

-- Juha

**Comment by alfredh** [comment]
fixed in commit a4d28ea335086eed4d7cfb61fdee0be9527e73bd
