### ISSUE TITLE
Can't found Gsm.h

### ISSUE THREAD

**Issue by BigDwarf** [alfredh/baresip#414]
odules/gsm/gsm.c:6:10: fatal error: 'gsm.h' file not found
#include <gsm.h> /* please report if you have problems finding this file */

So, i'm reporting :)
OS: mac OS
baresip v.0.5.9

Thank you in advance.

**Comment by alfredh** [comment]
you need to install the gsm package from Homebrew:

```
$ brew install libgsm
```


you can also disable building the gsm module with:

```
$ make USE_GSM=
```

Alfred
