### ISSUE TITLE
Video frame weirdness with mingw

### ISSUE THREAD

**Issue by perwx3** [alfredh/baresip#415]
Hello, 

I'm having video problems with baresip compiled as 32-bit windows binary, compiled with mingw on linux. 

The incoming video is randomly scrambled and I have traced it down to that the incoming packets are not what they are supposed to be when handled in src/video.c video_stream_decode. I have printed the complete frame sizes when receiving rtp marker bit (signaling last packet in frame) and the frame sizes  differ between my windows build and a OSX build (built on same baresip code of course). The source of the stream is bit exact every time and on mac everything is fine, video is not scrambled whatsoever, ever. 

On windows however video is somewhat randomly scrambled every call. This random scrambling is regardless of codec and the source is not really relevant, I get the same effect regardless of the source. The scrambling also increases with bigger data amounts (i.e. higher resolution or higher bitrate => greater number of udp fragments for each video frame). 

I'm suspecting some kind of underlaying udp socket error or a synchronization issue. Could also be some issue with the marker bit not being read correctly...  Some examples: 

Stream on mac:
...
frame no 36: 9998 bytes 
frame no 37: 3996 bytes. 
...
frame no 61: 8978 bytes
frame no 62: 4208 bytes
...

Same stream on windows: 
...
frame no 36: 12501 bytes
frame no 37: does not exist
....
frame no 61: 12713 bytes
frame no 62: does not exist
....

With exception for these frames, all other frames are the same. The whole sequence is ~120 frames and just 4 frames are scrambled. The frame size is just an additiong of mb->size which resets when hdr->m and prints total size. 

Do you have any idea what this could be and how to proceed searching for the error? 

Br, 
Per Enstedt

**Comment by perwx3** [comment]
Hi again,

Still searching for the error here.. 

I'm currently running one mac and two seperate windows machines, at the same time, connected to the same switch, streaming media from the same source, the exact same video stream. 
Result: mac plays without a single glitch and both windows machines have scrambled video. 

I've drilled deeper into the code and there is a udp 'packet loss' in the code somewhere,,, as early as udp_recv_handler there are packet that simply does not exist. It behaves basically the same as network packet loss, but packets are indeed sent to the machines (verified with wireshark). 

Going to have a look in udp.c now. 

To be continued...

**Comment by perwx3** [comment]
Problem located!

This is an issue with the internal receive buffer size of udp sockets on windows. Default value is 8192 and if the buffer size is raised then the problem goes away. 

So this seems to be an issue of CPU load really. As the machine gets higher CPU load because of video encoding/decoding it can't keep up with handling of incoming udp packets, the udp buffer is overrun with new packets and some packets are thereby lost, resulting in scrambled video. This could be the result of just too little CPU for what you want to do or that packets are sometimes 'bursted' over the network. You get essentially packet loss when there is no real network packet loss. 

Btw: What is the threading model for this? Which thread is actually doing the video decoding? 

Solution is:
There is a method to set both send and receive buffer size in udp.c: udp_sockbuf_set. Problem is that this function is never called anywhere. :) 

So quick fix for this issue, if anyone's interested, is to just add:
   udp_sockbuf_set(us, 65535);
for example just before 
   err = udp_thread_attach(us); 
in udp.c, udp_listen. 

Happy coding everybody!

Br,
Per

**Comment by alfredh** [comment]
hi @perwx3 

many thanks for your report and suggested fix.

perhaps we could add a new config option to set the buffer size,
which is then applied to all RTP sockets:

```
# AVT - Audio/Video Transport
rtp_sockbuf_size    65536
```

video decoding is usually much faster then encoding. the video decoding
is done in the same thread as is receiving the RTP packets, i.e. re_main.
but many decoders such as ffmpeg will offload the real work to multiple
worker threads, I guess this depends on your configuration.


Alfred

**Comment by alfredh** [comment]
hi @perwx3 could you please test this commit ?

**Comment by perwx3** [comment]
@alfredh Tried it and it works great!

**Comment by alfredh** [comment]
Thanks for testing!
