### ISSUE TITLE
multiple FU-A groups in a h264 frame, does baresip support?

### ISSUE THREAD

**Issue by cloud-jxy** [alfredh/baresip#432]
I code a private codec module which uses the mediacodec of java sdk to ecode/decode by jni. I use a echo session to test video quality.  The decode quality is too bad. The remote view from echo session caton.
I found the 264 encoded by java's mediacodec  have multiple FU-A groups in a h264 frame. Usual a h264 frame has only a FU-A group. Dose baresip's parse code support multiple FU-A groups in a h264 frame.

**Comment by alfredh** [comment]
can you share your *.264 binary files ?

also, what operating system are you using, which version of ffmpeg etc.


Alfred

**Comment by alfredh** [comment]
your encoder is probably sending STAP-A packets
(Single Time Aggregation Packet):

https://tools.ietf.org/html/rfc6184#section-5.7.1

this is not supported, it is part of packetization-mode=1.
you can try to configure your encoder to use packetization-mode=0 (mandatory).

packetization-mode 1 is on the roadmap, we will try to add it
when we have some time for that:

https://github.com/alfredh/baresip/wiki/Roadmap
