### ISSUE TITLE
Print Call Flow, Invite, Trying, ACK ...

### ISSUE THREAD

**Issue by MoustafaMohA** [alfredh/baresip#433]
I want to print all call flow requests and responses, for example we have the following high level for `a` and `b` making a call.

```
a -------------------- INVITE           -------------------->b
a<--------------------TRYING         --------------------   b
a<--------------------180RINIGING --------------------   b
a<--------------------200 ANSWERING --------------------  b
a -------------------- ACK-------------------->b
a -------------------- BYE-------------------->b
```

I need to see the details of each request  and response by baresip, I managed to print only the requests by modifying the `request_handler function in ua.c`. and print the content of the `mbuf `in the `msg`

Thanks

**Comment by jmillan** [comment]
Isn't it enough for you any existing network capturer?

* ngrep
* sngrep
* tshark
* wireshark
...

**Comment by MoustafaMohA** [comment]
Yes, I tried them but I need the output to be on console to be taken into my application, Parent process starts baresip and the output to be redirected to the parent app.

**Comment by jmillan** [comment]
You can redirect the output of ngrep and tshark to the desired file descriptor.

**Comment by MoustafaMohA** [comment]
All capture tools will get requests encrypted, I am using SIP over TLS.

**Comment by alfredh** [comment]
If you have the TLS private key, you can use Wireshark or ssldump to show
the network traffic, even if TLS is used.

SIP packet tracing is not supported by baresip, sorry ..


Alfred

**Comment by lmangani** [comment]
@MoustafaMohA If your proxy or B2BUA supports HEP (kamailio, opensips, asterisk, freeswitch) you might be able to trace using HOMER and the HEP stack without breaking your own encryption and get everything you need to build directional flows from its API

**Comment by MoustafaMohA** [comment]
@alfredh I am confused about something, I managed to print some requests. Why I can't do the same and print responses ?
And I don't have the private key.

**Comment by alfredh** [comment]
you can try this patch for libre:

https://github.com/alfredh/patches/blob/master/re-sip-trace.patch

just install a trace handler in your application, and you should see
all outgoing/incoming SIP messages.
