### ISSUE TITLE
iOS not using wifi

### ISSUE THREAD

**Issue by mathipalm** [alfredh/baresip#434]
So I'm developing an app thats using baresip and should connect to a local freeswitch server. But Baresip wont use wifi when used on iPhone, even though i'm connected to a wifi. Baresip does how ever use wifi if I turn of mobile data in the phones settings but this is not really a solution.

Any advice on how to force baresip to prioritise wifi? I've tried `net_interface        eth0` without success.

Cheers

**Comment by perwx3** [comment]
Hello, 

Had the same issue, fixed it in this issue:

See https://github.com/creytiv/re/issues/85

Br, 
Per

**Comment by perwx3** [comment]
However, I later noticed a problem with just copying the file as I wrote in issue 85. 

When the iPhone SDK is updated, this copied file will 'disappear'. So I made some small changes to my build to make it more persistent:

Route.h has now been copied to re/include/net and mk/re.mk has
a check which forces the build var HAVE_NET_ROUTE_H = 1 if we are building for darwin, 
thereby disabling dynamic checking for darwin systems. 

Br,
Per

**Comment by alfredh** [comment]
can you share the baresip log?

can you also run the `netstat` command and share the routing table:

```
re_printf("%H\n", net_debug, baresip_network());
```


here is the output from my netstat command:

```
/netstat
--- Network debug ---
 Preferred AF:  AF_INET
 Local IPv4:       en0 - 10.0.0.109
 Local IPv6:     utun0 - ::
 Domain: getinternet.no
net interfaces:
        lo0:  127.0.0.1
        lo0:  ::1
        lo0:  fe80::1
        en0:  fe80::1c08:ecc4:f702:8c6d
        en0:  10.0.0.109
      awdl0:  fe80::8422:60ff:fee7:94b
      utun0:  fe80::84a0:e59f:bbbf:1709
net routes:
 Destination                                 Next Hop                                 Iface           Type
 0.0.0.0/0                                   10.0.0.1                                 en0             
 17.252.108.134/0                            10.0.0.1                                 en0             
 84.208.13.59/0                              10.0.0.1                                 en0             
 91.121.30.149/0                             10.0.0.1                                 en0             
 173.194.222.16/0                            10.0.0.1                                 en0             
 192.30.253.124/0                            10.0.0.1                                 en0             
 192.30.253.125/0                            10.0.0.1                                 en0             
 216.58.211.138/0                            10.0.0.1                                 en0             
 ::/0                                        fe80:a::                                 utun0           
 DNS Servers from System: (1)
   0: 10.0.0.1:53
```

**Comment by alfredh** [comment]
as mentioned by @perwx3 the solution is to copy the route.h headers ..


Alfred
