### ISSUE TITLE
vumeter compiler warnings

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#447]
CC [m]  build-arm/modules/vumeter/vumeter.o
modules/vumeter/vumeter.c: In function 'encode_update':
modules/vumeter/vumeter.c:109:25: warning: unused parameter 'au' [-Wunused-parameter]
     const struct audio *au)
                         ^
modules/vumeter/vumeter.c: In function 'decode_update':
modules/vumeter/vumeter.c:135:25: warning: unused parameter 'au' [-Wunused-parameter]
     const struct audio *au)
                         ^

**Comment by alfredh** [comment]
fixed in 14864377cbe7e502a1b27dccc76a93a96303ea02
