### ISSUE TITLE
Call fails because of stun protocol error

### ISSUE THREAD

**Issue by clehner** [alfredh/baresip#45]
When I use in my account config medianat=stun;stunserver=stun:... and make a call, I get the following:
```
call: medianat 'stun' failed: Protocol error
```
What could be causing this? I have tried multiple stun servers. Looking at the UA debug shows that my auth_user is being used as the user for the stunserver URL, whereas I am used to using STUN servers not requiring authentication. Could it be the STUN server isn't expecting to get a username?

Using libre 0.4.12, librem 0.4.6, baresip 502385d0 (master), on Debian testing amd64.

**Comment by czarkoff** [comment]
Could you post a log?

**Comment by clehner** [comment]
```
$ baresip -v
baresip v0.4.13 Copyright (C) 2010 - 2015 Alfred E. Heggestad et al.
Local network address: IPv4=wlan0:192.168.0.108 IPv6=tun0:fc5f:947e:d682:38e6:25b2:4938:3990:b325
ui: stdio
cons: UI console listening on 0.0.0.0:5555
ui: cons
aucodec: L16/44100/2
aucodec: L16/32000/2
aucodec: L16/16000/2
aucodec: L16/8000/2
aucodec: L16/44100/1
aucodec: L16/32000/1
aucodec: L16/16000/1
aucodec: L16/8000/1
aucodec: speex/32000/2
aucodec: speex/16000/2
aucodec: speex/8000/2
aucodec: speex/32000/1
aucodec: speex/16000/1
aucodec: speex/8000/1
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aucodec: opus/48000/2
aufilt: vumeter
ausrc: alsa
auplay: alsa
avcodec: x264 build 146
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
medianat: stun
medianat: turn
medianat: ice
mediaenc: srtp
mediaenc: srtp-mand
mediaenc: srtp-mandf
mediaenc: dtls_srtpf
mediaenc: dtls_srtp
mediaenc: srtp-mandf
DTLS-SRTP ready with profiles SRTP_AES128_CM_SHA1_80:SRTP_AES128_CM_SHA1_32
using stunserver: 'stun:stun.callwithus.com:3478'
106718612@sip.callwithus.com: Using medianat `stun'
Populated 1 account
Populated 9 contacts
Populated 17 audio codecs
Populated 1 audio filter
Populated 3 video codecs
Populated 0 video filters
baresip is ready.
106718612@sip.callwithus.com: {0/UDP/v4} 200 OK (CWU SIP GW) [1 binding]
All 1 useragent registered successfully! (104 ms)
>              sip:301@ideasip.com
call: connecting to 'sip:301@ideasip.com'..
call: medianat 'stun' failed: Protocol error
```

**Comment by alfredh** [comment]
libre and baresip only supports the "new" type of STUN servers, defined in RFC 5389.

the STUN-server you are using (Vovida 0.96) is very old and only supports the "old" STUN.

you can verify this with the STUN client restunc:

```
$ ./restunc -u -b stun.callwithus.com
STUN client: local=192.168.0.2 srv=stun.callwithus.com:0 (rto=500)
Service: "stun", Protocol: "udp"
Resolved STUN server: 198.27.81.168:3478
Doing Binding Discovery test..
restunc: Mapped address error (Protocol error)
```

An instance of restund ("new" STUN) is running here:

stun.creytiv.com:3478
(UDP and TCP protocols)



NOTE: the old STUN has many limitations and we are not interested in adding support
for old STUN in the code. Instead we should ask the community to upgrade their
STUN Servers.

**Comment by alfredh** [comment]
STUN Client: https://github.com/alfredh/restunc
STUN Server: http://creytiv.com/restund.html

**Comment by clehner** [comment]
Great, thanks!
