### ISSUE TITLE
Only video when call initiated from baresip

### ISSUE THREAD

**Issue by daanpape** [alfredh/baresip#452]
Hello,

I'm using baresip 0.5.9 on OpenWRT with a H264 USB camera. It's working ok (somtimes long before i see the first video) if the call is initiated through baresip;

`stream: incoming rtp for 'audio' established, receiving from 178.62.210.188:18384
stream: incoming rtp for 'video' established, receiving from 178.62.210.188:17208==              ]
[0:00:01] audio=0/0 video=0/0 (bit/s) efps=0.0/0.0          [=========       ]  [===             ]
--- Video stream ---
 started: yes
 tx: encode: H264 yuv420p
     source: v4l2 352 x 288, fps=15.00 frames=25
     skipc=2 sendq=1
     time = 1.466 sec
 rx: decode: H264 ???
     vidisp: none 0 x 0 frames=0
     n_intra=0, n_picup=0
     time = 0.740 sec
 video dir=sendrecv pt_enc=96
 local: 0.0.0.0:15646, remote: 178.62.210.188:17208/178.62.210.188:17209
RTP debug:
 Encode: seq=24949 ssrc=0x6a764bc6
----- RTCP Session: -----
  cname=sip:2@sip1.bluecherry.io:443 SSRC=0x6a764bc6/1786137542 rx=90000Hz
  member 0x40f47521: lost=0 Jitter=0.0ms RTT=0.0ms
                 IP=178.62.210.188:17208 psent=0 rcvd=49
  TX: packets=70, octets=43455
[h264 @ 0x4d87d0] no frame! video=457119/227689 (bit/s) efp [=========       ]  [==              ]
avcodec: avcodec_send_packet error, packet=24 bytes, ret=-1094995529 (Invalid data found when processing input)
video: H264 decode error (seq=7152, 4 bytes): Bad message
`

But if I initiate the call from my Antisip on android it fails (i use auto answer);

`2@sip1.bluecherry.io: Call established: sip:1@178.62.210.188
stream: incoming rtp for 'audio' established, receiving from 178.62.210.188:17302
[0:00:04] audio=63573/0 video=0/0 (bit/s) efps=0.0/0.0      [=========       ]  [==              ]
--- Video stream ---
 started: no
 tx: encode: none ?
     source: none 0 x 0, fps=0.00 frames=0
     skipc=0 sendq=0
     time = (not started)
 rx: decode: none ???
     vidisp: none 0 x 0 frames=0
     n_intra=0, n_picup=0
     time = 0.000 sec
 video dir=sendrecv pt_enc=-1
 local: 0.0.0.0:2672, remote: 178.62.210.188:17774/178.62.210.188:17775
RTP debug:
 Encode: seq=29103 ssrc=0x8e2f6d6d
----- RTCP Session: -----
  cname= SSRC=0x8e2f6d6d/2385472877 rx=0Hz
  TX: packets=0, octets=0
`

I use an asterisk server and only h264 is supported. How can I debug this?

Kind regards,
Daan

**Comment by alfredh** [comment]
I will close this one now, if you want to provide more information please re-open it.
