### ISSUE TITLE
How run baresip to get info log messages from modules?

### ISSUE THREAD

**Issue by alishir** [alfredh/baresip#453]
Hi @alfredh,
Thanks for your great library. I want to get log message from modules, e.g. x11 module. How should I run the baresip to see info level log messages?

**Comment by alfredh** [comment]
you should run baresip as normal, all info and warning log messages are printed.

do you see this line:

```
	info("baresip is ready.\n");
```

adding an extra `-v` gives you also verbose debug:

```
./baresip -h
baresip v0.5.9 Copyright (C) 2010 - 2018 Alfred E. Heggestad et al.
Usage: baresip [options]
options:
	-6               Prefer IPv6
	-d               Daemon
	-e <commands>    Execute commands (repeat)
	-f <path>        Config path
	-m <module>      Pre-load modules (repeat)
	-p <path>        Audio files
	-h -?            Help
	-t               Test and exit
	-u <parameters>  Extra UA parameters
	-v               Verbose debug
```

Alfred

**Comment by alishir** [comment]
Thanks, I see the logs, is it possible to change visible log levels?
