### ISSUE TITLE
Is it possible to switch video source during call?

### ISSUE THREAD

**Issue by alishir** [alfredh/baresip#457]
Is it possible to switch video source from webcam to x11grab during call?

**Comment by alfredh** [comment]
it is possible to change the video source in a call by calling this function:

```
int video_set_source(struct video *v, const char *name, const char *dev)
```

currently there are no commands to do it. it should be relatively easy
to implement such a command, PR welcome.

**Comment by alishir** [comment]
Thanks a lot.
