### ISSUE TITLE
Audio on USB Headset/speaker is delayed by almost 30 seconds

### ISSUE THREAD

**Issue by jraghvan** [alfredh/baresip#46]
With 0.13 version (as well as from GIT) i see that Audio seems to be broken for almost 30 seconds when the Default device from ALSA is set to USB headset/speaker. This issue was not seen in version 0.4.6 but is seen in 0.4.11 onwards.  

I use Pulseaudio (latest from ubuntu from 15.04) and wrap around ALSA with it. Let me know if you need any more information.   This issue is very easy to recreate, if you need any more information, do let me know. 

Here is the Audio portion of the config file i am using -

# Audio
audio_player            alsa,default
audio_source            alsa,default
audio_alert             alsa,default
audio_srate             8000-48000
audio_channels          1-2
#ausrc_srate            48000
#auplay_srate           48000
#ausrc_channels         0
#auplay_channels                0

**Comment by jraghvan** [comment]
Sorry to mention Additional details -

baresip version : 0.4.12
ALSA version :  1.0.27.2
Pulseaudio Version : 6.0.0 

The Issue happens with Pulseaudio 6.0.0. However after downgrading pulse audio to 4.0.0, the problem seems to disappear.  So this looks like a Pulseaudio 6.0.0 issue than a baresip issue.  

This should serve as an FYI, rather than an issue :)

**Comment by alfredh** [comment]
should we create a new module called "pulseaudio" to handle Pulseaudio API natively?

**Comment by jraghvan** [comment]
That would be a Good idea.  

Speaking of modules, i was wondering if we could add two more -

(1) dbus  (for legacy old systems that need them)
(2) openh264 (i think it is royalty free now because of Cisco)

**Comment by juha-h** [comment]
jraghvan writes:

> Sorry to mention Additional details -
> 
> baresip version : 0.4.12
> ALSA version :  1.0.27.2
> Pulseaudio Version : 6.0.0 
> 
> The Issue happens with Pulseaudio 6.0.0. However after downgrading
> pulse audio to 4.0.0, the problem seems to disappear.  So this looks
> like a Pulseaudio 6.0.0 issue than a baresip issue.

pulseaudio 5.0 of debian jessie works fine.

-- juha
