### ISSUE TITLE
Multiple SIP certificates. Client Side and  Server Side

### ISSUE THREAD

**Issue by Naegolus** [alfredh/baresip#460]
Hello Alfred,

Referring to: https://github.com/alfredh/baresip/issues/401

We have a similar question:

First: We would like to use multiple different client certificates (identities) for multiple servers and use the right certificate for each server.
Second: We would like to trust multiple servers with different certificates from different CAs / PKIs.

Can this be done with only one instance of baresip?

Joe

**Comment by alfredh** [comment]
Hi @Naegolus 

just to give you some background first;

the TLS context `struct tls` is global and stored in `uag.tls`. it is allocated here, in src/ua.c:

```
#ifdef USE_TLS
	if (uag.use_tls) {
		/* Build our SSL context*/
		if (!uag.tls) {
			const char *cert = NULL;

			if (str_isset(uag.cfg->cert)) {
				cert = uag.cfg->cert;
				info("SIP Certificate: %s\n", cert);
			}

			err = tls_alloc(&uag.tls, TLS_METHOD_SSLV23,
					cert, NULL);
			if (err) {
				warning("ua: tls_alloc() failed: %m\n", err);
				return err;
			}
		}

		if (sa_isset(&local, SA_PORT))
			sa_set_port(&local, sa_port(&local) + 1);

		err = sip_transp_add(uag.sip, SIP_TRANSP_TLS, &local, uag.tls);
		if (err) {
			warning("ua: SIP/TLS transport failed: %m\n", err);
			return err;
		}
	}
#endif
```

the "tls" api is defined in `libre` and is a thin wrapper on top of OpenSSL.

the filename configured in the `sip_certificate` will be passed into tls_alloc
and the file should contain a PEM certificate and the private key. Inside tls_alloc
it is further passed on to OpenSSL `SSL_CTX_use_certificate_chain_file`
so if this function supports multiple certificates, then also baresip/libre supports it.

from OpenSSL documentation:

```
SSL_CTX_use_certificate_chain_file() loads a certificate chain from file into ctx. The certificates must be in PEM format and must be sorted starting with the subject's certificate (actual client or server certificate), followed by intermediate CA certificates if applicable, and ending at the highest level (root) CA . There is no corresponding function working on a single SSL object.
```

I think the best thing for you is just to test it and see if/how it works. I have
never tested multiple certificates.

are you planning to use multiple SIP accounts per instance ? it is possible to
move the SIP transport and TLS context from global to each SIP account, but
that would require some refactoring.


hope this helps!

Alfred

**Comment by Naegolus** [comment]
Hi @alfredh ,

thanks for your quick reply! It was helpful.
Yes, we are planning to use multiple SIP accounts per instance.

If we have any interesting news I will let you know.

Joe

**Comment by markatz** [comment]
Hi @alfredh ,

I wonder if you could help with this:

In modules.mk I selected USE_AMR := 1 by accident. Now, even if I remove it, make clean, build, install, I still get an error when I run baresip (0.5.11) "dl: mod: ...... module amr.so: No such file or directory"

I also select USE_SRTP := 1 and append my account name with ;mediaenc=srtp but I get an error when I run baresip  - account: mediaenc not found: 'srtp'

**Comment by markatz** [comment]
Ahh sorry - solved it myself. I forgot to correct the settings in the config
