### ISSUE TITLE
Adding H.224 mime type and controling far end camera.

### ISSUE THREAD

**Issue by alishir** [alfredh/baresip#463]
Hi Alfred,

Commercial video conferencing end points usually have PTZ camera. The protocol used for controlling far end camera control is [H.281/H.224](https://tools.ietf.org/html/rfc4573). I read `baresip` code and found that there is `video_alloc` and `audio_alloc` functions to set mime types for video and audio stream. With regarding to rfc4573 adding H.224 mime type require to add new media description with `application` value.

I decided to implement RFC 4537 as a module, would you please guide me to implementing this module? I think I should do something like `video_alloc` but I don't know how I should send/receive RTP packets? 

Regards,
Ali

**Comment by alfredh** [comment]
hi @alishir 

if you want to add support for FECC, I think you can start by copying audio.c or video.c
and create a new file called `fecc.c` which defines something like `struct fecc`

the struct fecc object must have a pointer to `struct stream` that is used for
sending and receiving RTP/RTCP packets.

1. to send RTP packets: call `stream_send`
2. to recv RTP packets: use `stream_recv_handler`


Alfred

**Comment by alishir** [comment]
hi @alfredh 

Thanks for your guidance, I will try it.

Ali

**Comment by alfredh** [comment]
I added FECC to the roadmap/wishlist:

https://github.com/alfredh/baresip/wiki/Roadmap

the Issue tracker is mainly for defects and small fixes.
