### ISSUE TITLE
Recently dshow fixes

### ISSUE THREAD

**Issue by Encamy** [alfredh/baresip#464]
Hello @nicotyze and @alfredh 
Recently dshow was updated aa91b8559fb3ffa8bb82e35499b2581066931848
Previously, me and @mikhail-barg were using this file: [qedit.h](https://github.com/thegrandpoobah/dsgrab/blob/master/qedit.h) as header because we don't have DirectX SDK (Also we are using Windows).
This file already declares CLSID_SampleGrabber so it conflicts with the one that is declared in dshow.cpp.
If we try to use the [file](https://code.google.com/p/webm/source/browse/qedit.h?repo=udpsample) from comment (it can be accessed via WayBack Machine: [link](https://web.archive.org/web/20130722082039/https://code.google.com/p/webm/source/browse/qedit.h?repo=udpsample)), then the compilation error occurs.

I'll be glad if you tell me how to correct this error in the right way.
My assumptions is that we can remove second declaration using this code:
```c++
#ifndef WIN32
const CLSID CLSID_SampleGrabber = { 0xc1f400a0, 0x3f08, 0x11d3,
  { 0x9f, 0x0b, 0x00, 0x60, 0x08, 0x03, 0x9e, 0x37 }
};
#endif
```
Is this right way?

Thank you,
Alexey

**Comment by alfredh** [comment]
it would be nice if the dshow module can be compiled both
for Windows and for Mingw.

it looks like this variable just contains some binary values.
perhaps one option is simply to rename the variable ?

e.g. 

`MySampleGrabber`

Alfred

**Comment by Encamy** [comment]
How about to get rid of `qedit.h` completely?
As I understand, only one file includes `qedit.h`, and we can just declare `ISampleGrabberCB` and `ISampleGrabber` in `dshow.cpp`.
Is this method suitable for other users?

Alexey

**Comment by nicotyze** [comment]
Hello,
It sounds ok for me, I just expect to be still able to compile with mingw.

Nicolas

**Comment by Encamy** [comment]
Thank you
