### ISSUE TITLE
Is there exists any contribution guide?

### ISSUE THREAD

**Issue by alishir** [alfredh/baresip#466]
Hi @alfredh 

Thanks for your great project. Because of good project structure and excellent architecture I tried to have some contribution, but unfortunately after each pull request I encountered some error in CI check and I closed my pull request and try again. Is there any way to check the code structure on my local machine before creating a pull request?

Regards,
Ali

**Comment by alishir** [comment]
I found that `ccheck.py` hosted here `https://github.com/alfredh/pytools/raw/master/ccheck.py`.
Thanks ;)

**Comment by alfredh** [comment]
sorry to reply in a closed post, but I wrote a quick contribution guide
as requested:

https://github.com/alfredh/baresip/wiki/Contribution-Guide

Alfred

**Comment by alishir** [comment]
Thanks a lot.
