### ISSUE TITLE
how to un-register ua?

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#469]
I have not been able to figure out how to un-register ua, i.e., generate REGISTER request where ;expires has value 0.

I first tried ua_unregister(), but that just produces UNREGISTERING event and does not send any REGISTER request.  Then I tried ua_register() with regint=0, but re's 
sipreg_register() method does not accept expires parameter value 0.

**Comment by alfredh** [comment]
to unregister you should call this function:

```
void ua_unregister(struct ua *ua)
```

it will call `reg_unregister` for each Register client. I just tested it locally
and it works.

Please verify that `reg_unregister` is actually called.


Alfred

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> to unregister you should call this function:
> 
> ```
> void ua_unregister(struct ua *ua)
> ```

That is what I tried first.

> it will call `reg_unregister` for each Register client. I just tested
> it locally and it works.
> 
> Please verify that `reg_unregister` is actually called.

I added info statement to ua_unregister:

    ...
	if (!list_isempty(&ua->regl))
		ua_event(ua, UA_EVENT_UNREGISTERING, NULL, NULL);

	for (le = ua->regl.head; le; le = le->next) {
		struct reg *reg = le->data;
		info("ua: calling reg_unregister\n");
		reg_unregister(reg);
	}
    ...

and I get to log:

06-24 16:26:09.668 23480 23480 D Baresip : ua event (UNREGISTERING) 
06-24 16:26:09.671 23480 23505 D Baresip : ua: calling reg_unregister

I now checked with ngrep and, indeed, REGISTER message with ;expires=0
is generated and my sip proxy responds to that with 200 OK, but

ua event (REGISTER_OK) 200 OK

(that baresip generates when ua_register() is called) is missing.

So my app does not become aware that unregister worked.

-- Juha

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> the application should just assume that the un-register went fine.

OK, I'll consider UNREGISTERING event as indication that un-register
succeeded.

-- Juha
