### ISSUE TITLE
How to change v4l2 capture format?

### ISSUE THREAD

**Issue by mk6032** [alfredh/baresip#477]
Is it possible to set the capture format for v4l2? For example, I want to use index 4 h264 (see #443 for full list) ..

        Index       : 4
        Type        : Video Capture
        Pixel Format: 'H264' (compressed)
        Name        : H.264

I've tried in .baresip/config ..

pi@ntp:~ $ grep video_source .baresip/config
video_source            v4l2,/dev/video0,pixelformat=4

.. and other variations like pix_fmt=4, pix_fmt=H264, pixelformat=H264, etc. This doesn't seem to make a difference. If I specify v4l2_codec in video_source, it uses h264 by default, however this breaks the stream to a Polycom.

There are two pcaps in the attached zip. v4l2.pcap is using regular v4l2 codec ..
[v4l2_pcaps.zip](https://github.com/alfredh/baresip/files/2136899/v4l2_pcaps.zip)

baresip is ready.
206@192.168.1.14: {0/TCP/v4} 200 OK () [0 bindings]
All 1 useragent registered successfully! (15 ms)
>                              208
call: connecting to 'sip:208@192.168.1.14;transport=tcp'..
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 180 Ringing (/)
audio: Set audio decoder: G722 16000Hz 1ch
audio: enable auplay resampler: 16000Hz/1ch --> 48000Hz/1ch
audio: start_player failed (.): No such device
audio: Set audio encoder: G722 16000Hz 1ch
audio: start_player failed (.): No such device
audio: enable ausrc resampler: 16000Hz/1ch <-- 48000Hz/1ch
audio: start_source failed (.): No such device
Set video encoder: H264 packetization-mode=0 (2500000 bit/s, 30.00 fps)
v4l2: /dev/video0: found valid V4L2 device (352 x 288) pixfmt=YU12
v4l2: Current input: "Camera 0"
v4l2: current framerate is 30.00 fps
audio: start_player failed (.): No such device
audio: start_source failed (.): No such device
call: start: audio_encoder_set error: No such device
call: start: audio_decoder_set error: No such device
Set video decoder: H264 packetization-mode=0
206@192.168.1.14: Call established: sip:208@192.168.1.14;transport=tcp
stream: incoming rtp for 'audio' established, receiving from 192.168.2.19:2230
call: terminate call '1a1e5458e0b9e457' with sip:208@192.168.1.14;transport=tcp [=====           ]
sip:206@192.168.1.14: Call with sip:208@192.168.1.14;transport=tcp terminated (duration: 16 secs)

audio           Transmit:     Receive:
packets:              0          773
avg. bitrate:       0.0         63.6  (kbit/s)
errors:               0            0
pkt.report:           0          530
lost:                 0            0
jitter:             0.0          0.0  (ms)

video           Transmit:     Receive:
packets:           5708            0
avg. bitrate:    2483.2          0.0  (kbit/s)
errors:               0            0
Quit
ua: stop all (forced=0)
Stopping 1 useragent..

... next is v4l2_codec

pi@ntp:~ $ nano .baresip/config
pi@ntp:~ $ grep video_source .baresip/config
video_source            v4l2_codec,/dev/video0
pi@ntp:~ $ baresip
baresip v0.5.9 Copyright (C) 2010 - 2018 Alfred E. Heggestad et al.
Binding to interface or IP address 'eth0'
net: eth0: could not get IPv6 address (No such device)
Local network address:  IPv4=eth0:192.168.2.133
aucodec: opus/48000/2
aucodec: G722/16000/1
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
dl: mod: /usr/local/lib/baresip/modules/alsa.so (/usr/local/lib/baresip/modules/alsa.so: cannot open shared object file: No such file or directory)
module alsa.so: No such file or directory
dl: mod: /usr/local/lib/baresip/modules/pulse.so (/usr/local/lib/baresip/modules/pulse.so: cannot open shared object file: No such file or directory)
module pulse.so: No such file or directory
dl: mod: /usr/local/lib/baresip/modules/jack.so (/usr/local/lib/baresip/modules/jack.so: cannot open shared object file: No such file or directory)
module jack.so: No such file or directory
ausrc: aubridge
auplay: aubridge
ausrc: aufile
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidcodec: VP8
vidcodec: VP9
h265: using x265 0.0 [Linux][GCC 6.1.1][32 bit][noasm] 8bit+10bit+12bit
vidcodec: H265
vidsrc: v4l2
v4l2_codec inited
vidcodec: H264
vidsrc: v4l2_codec
vidsrc: avformat
vidsrc: fakevideo
vidisp: fakevideo
account: video codec not found: pixfmt=mjpeg
account: username:password is now deprecated please use ;auth_pass=xxx instead
Populated 1 account
Populated 4 audio codecs
Populated 1 audio filter
Populated 7 video codecs
Populated 0 video filters
baresip is ready.
206@192.168.1.14: {0/TCP/v4} 200 OK () [0 bindings]
All 1 useragent registered successfully! (14 ms)
>                              208
call: connecting to 'sip:208@192.168.1.14;transport=tcp'..
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 180 Ringing (/)
audio: Set audio decoder: G722 16000Hz 1ch
audio: enable auplay resampler: 16000Hz/1ch --> 48000Hz/1ch
audio: start_player failed (.): No such device
audio: Set audio encoder: G722 16000Hz 1ch
audio: start_player failed (.): No such device
audio: enable ausrc resampler: 16000Hz/1ch <-- 48000Hz/1ch
audio: start_source failed (.): No such device
Set video encoder: H264 packetization-mode=0 (2500000 bit/s, 30.00 fps)
v4l2_codec: Driver Caps:
  Driver:        "bm2835 mmal"
  Card:          "mmal service 16.1"
  Bus:           "platform:bcm2835-v4l2"
  Version:       4.0
  Capabilities:  0x85200005
  Formats:
     YU12:    'Planar YUV 4:2:0'
     YUYV:    'YUYV 4:2:2'
     RGB3:    '24-bit RGB 8-8-8'
     JPEG: C  'JFIF JPEG'
  >  H264: C  'H.264'
     MJPG: C  'Motion-JPEG'
     YVYU:    'YVYU 4:2:2'
     VYUY:    'VYUY 4:2:2'
     UYVY:    'UYVY 4:2:2'
     NV12:    'Y/CbCr 4:2:0'
     BGR3:    '24-bit BGR 8-8-8'
     YV12:    'Planar YVU 4:2:0'
     NV21:    'Y/CrCb 4:2:0'
     BGR4:    '32-bit BGRA/X 8-8-8-8'

v4l2_codec: Selected Camera Mode:
  Width:   352
  Height:  288
  PixFmt:  H264
  Field:   1
audio: start_player failed (.): No such device
audio: start_source failed (.): No such device
call: start: audio_encoder_set error: No such device
call: start: audio_decoder_set error: No such device
Set video decoder: H264 packetization-mode=0
206@192.168.1.14: Call established: sip:208@192.168.1.14;transport=tcp
stream: incoming rtp for 'audio' established, receiving from 192.168.2.19:2232
/callstat audio=0/63978 video=0/0 (bit/s) efps=0.0/0.0                          [========        ]

===== Call debug (ESTABLISHED) =====
 local_uri: BareSIP <sip:206@192.168.1.14>
 peer_uri:   <sip:208@192.168.1.14;transport=tcp>
 af=AF_INET id=1108705eb533de70
 direction: Outgoing
SDP session
  local attributes:
    tool='baresip 0.5.9'
  remote attributes:
session media:
audio RTP/AVP
  local formats:
     96 opus/48000/2 (stereo=1;sprop-stereo=1;maxaveragebitrate=28000)
      9 G722/8000/1 () *
      0 PCMU/8000/1 ()
      8 PCMA/8000/1 ()
    101 telephone-event/8000/1 (0-15) *
  remote formats:
      9 G722/8000/1 *
    101 telephone-event/8000/1 *
  local attributes:
    label='1'
    rtcp-rsize
    ssrc='1584540312 cname:sip:206@192.168.1.14'
    rtcp-mux
    ptime='20'
  remote attributes:
video RTP/AVP
  local formats:
     96 H264/90000/1 () *
  remote formats:
     96 H264/90000/1 (profile-level-id=428014) *
  local attributes:
    label='2'
    rtcp-rsize
    ssrc='3388109718 cname:sip:206@192.168.1.14'
    rtcp-mux
    framerate='30.00'
    rtcp-fb='* nack pli'
    content='main'
  remote attributes:
    label='1'
local media:

/video_debugdio=0/64000 video=0/0 (bit/s) efps=0.0/0.0                          [========        ]

--- Video stream ---
 started: yes
 tx: encode: H264 ?
     source: v4l2_codec 352 x 288, fps=30.00 frames=0
     skipc=0 sendq=0
     time = (not started)
 rx: decode: H264 ???
     vidisp: fakevideo 0 x 0 frames=0
     n_intra=0, n_picup=0
     time = 0.000 sec
 video dir=sendrecv pt_enc=96
 local: 0.0.0.0:8460, remote: 192.168.2.19:2234/192.168.2.19:2235
RTP debug:
 Encode: seq=6974 ssrc=0xc9f27396
----- RTCP Session: -----
  cname=sip:206@192.168.1.14 SSRC=0xc9f27396/3388109718 rx=90000Hz
  member 0x76f9fe11: lost=0 Jitter=0.0ms RTT=7.6ms
  TX: packets=0, octets=0
--- jitter buffer debug---
 running=0 min=5 cur=0 max=10 [frames]
 seq_put=0
 Stat: put=0 get=0 oos=0 dup=0 late=0 or=0 ur=0 flush=1       put/get_ratio=0% lost=0 (0.00%)
Quit0:15] audio=0/63978 video=0/0 (bit/s) efps=0.0/0.0                          [====            ]
ua: stop all (forced=0)
Stopping 1 useragent..
sip:206@192.168.1.14: Call with sip:208@192.168.1.14;transport=tcp terminated (duration: 15 secs)
v4l2_codec: encoder stats (keyframes:1, deltaframes:0)

audio           Transmit:     Receive:
packets:              0          708
avg. bitrate:       0.0         59.3  (kbit/s)
errors:               0            0
pkt.report:           0          708
lost:                 0            0
jitter:             0.0          0.0  (ms)
main: long async blocking: 1109>100 ms (h=0x76eb0a88 arg=0x201e770)
pi@ntp:~ $

Also as a FYI, I noticed some weirdness in baresip if there's an issue with the camera. For example this morning I was testing and there something was wrong with the camera. I'm not sure exactly what was wrong with it because it just kinda fixed itself... but there for a while I couldn't get a video stream to establish to the polycom where as previously I was successful. If I ran a 'raspistill -o test.jpg' it would say ..

mmal: No data received from sensor. Check all connections, including the Sunny one on the camera board

... so I (re)checked all connections and everything was good, but still getting that message, reboot a few times, etc. Eventually I added a -v to raspistill and it just started working again. Weird. Anyways, during the "I couldn't get a video stream to establish" part I noticed baresip would completely freeze when I ended the call with either q or b. I would have to kill -9 from a separate ssh session to regain control. In /var/log/syslog I could see 

Jun 26 10:27:31 ntp kernel: [ 1304.963439] bcm2835-v4l2: error 0 waiting for frame completion

**Comment by alfredh** [comment]
there are 2 modules for V4L2:

* v4l2: handles only raw frames
* v4l2_codec: handles only compressed H.264 frames

so you cannot specify pixelformat H.264 to the v4l2 module :)


from the log it looks like there are no frames coming from your device when
using v4l2_codec. this issue has been reported by other people multiple times.
in some cases it was a bug in the kernel/driver/hardware.

you can try to use other programs such as ffmpeg to read H.264 frames
from your device, and see if you get any frames or not.


Alfred

**Comment by alfredh** [comment]
hi @mk6032 

are you still having this problem ? are you able to do the tests that I requested ?

Alfred

**Comment by alfredh** [comment]
due to lack of response, I am closing this issue. Please re-open if you want to follow up.
