### ISSUE TITLE
Editor setting to support project code style

### ISSUE THREAD

**Issue by alishir** [alfredh/baresip#478]
Hi @alfredh,

First of all I'd like to say thank you for concise project structure and clean code style.
I just started to implement FECC #463 but unfortunately my editor(vscode) auto formatter differ from current code style.

Would you please share your code style settings?

Regards,
Ali

**Comment by juha-h** [comment]
Ali Shirvani writes:

> Would you please share your code style settings?

I tried a few months ago to create .clang-format file to match baresip
coding style.  I gave up as it appeared impossible.



-- Juha

**Comment by alishir** [comment]
@juha-h thanks for your reply.
But applying code style by hand is so tedious, do you have any automatic or even semi-automatic approach?

**Comment by juha-h** [comment]
Ali Shirvani writes:

> But applying code style by hand is so tedious, do you have any
> automatic or even semi-automatic approach?

Yes, and if there would exist .clang-format file, there would be many
tools and editors (such as emacs) that could format the code correctly.

-- Juha

**Comment by alfredh** [comment]
hi @alishir 

I am using xemacs and can share my .xemacs files if anybody wants it :)

The coding standard is not too strict, and you can use this script to check that
the code complies to it:

https://github.com/alfredh/pytools/blob/master/ccheck.py

A loosely defined list is available from libre project:

https://github.com/creytiv/re#coding-guidelines

In addition to that, here are some of the rules:

* Indentation is TAB
* 2 empty lines between functions
* A line is max 78 chars
* Declare variables at the beginning of function or block
* No trailing whitespace
* Space after if/for/switch

A clang format file is welcome if somebody wants to create it.

Alfred

**Comment by Encamy** [comment]
Hello @alfredh 
I've tried to create a clang-format file and here it is: [pastebin](https://pastebin.com/k37kfB1b)
But it seems that clang cannot correctly format enum (if there are no comments inside), multi-line comments, move variables at the beginning of the function and etc.
Also it can limit the maximum of empty lines, but cannot add additional empty line if only one is there.

May be somebody can set up it in the right way?

**Comment by alfredh** [comment]
I tried the clang-format file on the baresip source code, and the result is:

1. the code is completely reformatted, giving a diff of > 100K lines

2. the code does not compile anymore ..


my view here is that it is wishful thinking to hope that a tool can
format a code base 100% correctly. Perhaps if someone spends
many weeks tuning the clang-format file we can get something
which is 95% close.

But in any case we should not retrofit the source code, just to try to
satisfy a tool.

The code which is working and running for long time on many devices
in production, should not be modified by an external tool.


Alfred

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> my view here is that it is wishful thinking to hope that a tool can
> format a code base 100% correctly. Perhaps if someone spends
> many weeks tuning the clang-format file we can get something
> which is 95% close.

Fully agree.  I tried a few months to get a small baresip function
formatted correctly and had to give.  clang-format simply does not have
enough variables to get it correctly.

-- Juha

**Comment by alfredh** [comment]
ok, I will close this issue then.
