### ISSUE TITLE
websocket transport support (RFC-7118)

### ISSUE THREAD

**Issue by mk6032** [alfredh/baresip#479]
Is the patch in #92 included in recent builds, or still separate? When I attempt to dial ws or wss transport, and I've specified tcp transport in .baresip/account for my registration, this happens ..

> 123@test.domain.com;transport=ws
call: connecting to 'sip:123@test.domain.com;transport=ws;transport=tcp'..
call: sipsess_connect: Protocol not supported
menu: ua_connect failed: Protocol not supported
> 123@test.domain.com;transport=wss
call: connecting to 'sip:123@test.domain.com;transport=wss;transport=tcp'..
call: sipsess_connect: Protocol not supported
menu: ua_connect failed: Protocol not supported

When I take the ;transport=tcp off and register without any specifications ..

baresip is ready.
206@192.168.1.14: {0/UDP/v4} 200 OK () [0 bindings]
All 1 useragent registered successfully! (19 ms)
> 123@test.domain.com;transport=ws
call: connecting to 'sip:123@test.domain.com;transport=ws'..
call: sipsess_connect: Protocol not supported
menu: ua_connect failed: Protocol not supported
> 123@test.domain.com;transport=wss
call: connecting to 'sip:123@test.domain.com;transport=wss'..
call: sipsess_connect: Protocol not supported
menu: ua_connect failed: Protocol not supported

I was thinking this should look like...
call: connecting to 'ws://123@test.domain.com' 
or...
call: connecting to 'wss://123@test.domain.com'

Interesting enough, if I go back into .baresip/account and specify transport=tcp again, then specify a udp transport SIP call, I get the same and 'q' doesn't work to exit. I have to ctrl-c ..

baresip is ready.
206@192.168.1.14: {0/TCP/v4} 200 OK () [0 bindings]
All 1 useragent registered successfully! (28 ms)
> 123@test.domain.com;transport=udp
call: connecting to 'sip:123@test.domain.com;transport=udp;transport=tcp'..
Quit
ua: stop all (forced=0)
Stopping 1 useragent..
Quit
ua: stop all (forced=0)
Quit
ua: stop all (forced=0)
Quit

Attached pcap of the following tests ..

baresip is ready.
206@192.168.1.14: {0/TCP/v4} 200 OK () [0 bindings]
All 1 useragent registered successfully! (33 ms)
>   208@192.168.1.14;transport=udp
call: connecting to 'sip:208@192.168.1.14;transport=udp;transport=tcp'..
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 180 Ringing (/)
call: terminate call 'ed86ce12fe01dc11' with sip:208@192.168.1.14;transport=udp;transport=tcp
>   208@192.168.1.14;transport=tcp
call: connecting to 'sip:208@192.168.1.14;transport=tcp;transport=tcp'..
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 180 Ringing (/)
call: terminate call 'a52836f729381937' with sip:208@192.168.1.14;transport=tcp;transport=tcp
>   208@192.168.1.14;transport=tls
call: connecting to 'sip:208@192.168.1.14;transport=tls;transport=tcp'..
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 180 Ringing (/)
call: terminate call '57658457031e805a' with sip:208@192.168.1.14;transport=tls;transport=tcp
Quit
ua: stop all (forced=0)
Stopping 1 useragent..
pi@ntp:~ $

[test_transports.zip](https://github.com/alfredh/baresip/files/2142434/test_transports.zip)
![udp_invite](https://user-images.githubusercontent.com/8421707/41993409-5d059e36-7a19-11e8-8a52-89ef58f269f6.PNG)

**Comment by alfredh** [comment]
hi @mk6032 

SIP over Websockets is not supported (it is not in the code/build).

There is a patch for libre here that adds it:

https://github.com/alfredh/patches/blob/master/re-sip-websock-003.patch

Alfred

**Comment by jmillan** [comment]
Hi,

`wss` is not a valid SIP URI transport parameter. You must use `ws`.

https://tools.ietf.org/html/rfc7118#section-5.2

**Comment by juha-h** [comment]
José Luis Millán writes:

> `wss` is not a valid SIP URI transport parameter. You must use `ws`.

I got ;transport=wss from the re patch.

So baresip ;outbound param should look like

;outbound="wss://192.168.43.107:443;transport=ws

or just

outbound="wss://192.168.43.107:443

?

**Comment by jmillan** [comment]
To me it's much more clear: `wss://192.168.43.107:443`. This is, a Websocket URI as [such](https://tools.ietf.org/html/rfc6455#section-3)

**Comment by juha-h** [comment]
José Luis Millán writes:

> To me it's much more clear: `wss://192.168.43.107:443`.

I agree.

**Comment by andrewhodel** [comment]
Here's a WebSocket SIP/2.0 client that's in the browser and uses WebRTC media.

https://xyzbots.com/sip/
