### ISSUE TITLE
Dumping SDP content beforce call establishment.

### ISSUE THREAD

**Issue by alishir** [alfredh/baresip#480]
Hi @alfredh,

Would you please help me to dump SDP content before call establishment?
I found that there exists method for debugging during call, but I want to dump sdp content before starting a call.

Regards,
Ali

**Comment by alfredh** [comment]
hi @alishir 

I added some debug here:

https://github.com/alfredh/baresip/blob/master/src/call.c#L1589

just change the `#if 0` to `#if 1` and compile. You should then see the
SDP offer for the outgoing INVITE.

Is this what you are after ?

Alfred

**Comment by alfredh** [comment]
hi @alishir the commit above should address your question.

**Comment by alishir** [comment]
Hi @alfredh sorry for late comment, yes that commit solved the problem, thanks for your commit.
