### ISSUE TITLE
Feature request: CoreAudio device switch

### ISSUE THREAD

**Issue by vanrein** [alfredh/baresip#483]
As far as I can see, baresip cannot be made to use USB devices as `audio_player` and `audio_source`.  Is it possible to allow more than the current `nil` as device description to enable such plugin devices?  This would make `baresip` a perfect handler for a plugin USB phone as they are commonly sold for Skype.  Of course the `audio_alert` should still be settable to the internal speaker, and perhaps the plugin of the device during the call would be supportable.

**Comment by github-ernst** [comment]
You can.

Example from my config:

# ++++++ ALERT +++++++
audio_alert             alsa,default

# ++++++ SPEAKER +++++++
audio_player            alsa,plughw:1,0

# ++++++ MICROPHONE +++++++
audio_source            alsa,plughw:1,0


Use 'lsusb' in the terminal of your OS, to find out the specific device id of your USB device.

**Comment by vanrein** [comment]
Sorry, I should have said this is a request for Mac OS X.  I thought coreaudio was strictly for that platform.  In the source code for coreaudio, I found that the "char *device" is ignored, hence the request to do something with it :)

**Comment by vanrein** [comment]
This is the ignoring line I meant:
https://github.com/alfredh/baresip/blob/master/modules/coreaudio/player.c#L89

**Comment by alfredh** [comment]
hi @vanrein 

I have a solution for this, using `kAudioQueueProperty_CurrentDevice`.
will post the code in the next couple of days.

are you available for testing ?

Alfred

**Comment by vanrein** [comment]
Hi Alfred,

> I have a solution for this, using `kAudioQueueProperty_CurrentDevice`.
> will post the code in the next couple of days.

Cool.

> are you available for testing ?

Sure.  I don't have much of a build environment on Mac OS X, but enough for something as simple as baresip, AFAIK.

Thanks,
 -Rick

**Comment by alfredh** [comment]
hi @vanrein 

could you please test the `coreaudio` module in this branch:

https://github.com/alfredh/baresip/tree/coreaudio_select_device

When your USB device is plugged in and you start baresip, you
should see a list of audio devices:

```
## devices: 2
  [0] UID:  'AppleHDAEngineInput:1B,0,1,0:1'
  [0] Name: 'Built-in Microphone'
  [0] Manu: 'Apple Inc.'
  [1] UID:  'AppleHDAEngineOutput:1B,0,1,1:0'
  [1] Name: 'Built-in Output'
  [1] Manu: 'Apple Inc.'
```

if you find the right UID, use it as the audio device in e.g. `audio_player` option.


Alfred

**Comment by vanrein** [comment]
Hi,

Partial results; I need to stop working; we're under a rather extreme heat these days.  Will report more in a few days.

COMPILING:
Code looks code, and compiles properly after an update of libre/librem/baresip with Brew,
libre 0.5.1 -> 0.5.7 librem 0.5.0 -> 0.5.2, baresip 0.5.0 -> 0.5.8.

SEGFAULT (DUE TO VERSION MIXUP):
Brew's 0.5.8 as well as my locally compiled baresip crash with a segmentation fault.
Debugging leads me to a version conflict from using an older library, I haven't figured out yet why.
The problem is visible in mod_load, and causes a SEGFAULT crash in list_append for accessing protected ui in ui_register.
Fixed by editing ~/.baresip/confg, the module_path setting.

AUDIO REPORT:
Didn't see devices listed, not even one.  Trying to figure out breakpoings on loadable modules.

-Rick

**Comment by alfredh** [comment]
It is also warm here, around 34C a couple of days ago :)

I would suggest that you compile baresip/rem/re from git source, and uninstall
all versions from Macports/Homebrew. Some versions are not binary compatible
and can sometimes cause segfault.

**Comment by alfredh** [comment]
hi @vanrein how is the heat wave ?

did you have a chance to test my code ?

**Comment by vanrein** [comment]
Hey,

> hi @vanrein how is the heat wave ?

It's still going strong...

> did you have a chance to test my code ?

...so sorry, but no :(

-Rick

**Comment by alfredh** [comment]
there is a small improvement in 943ee657ecd5c03f2598a709599a88a37cf0a7f7

you can now specify the canonical name as the device:

```
audio_player            coreaudio,"Built-in Output"
```

**Comment by alfredh** [comment]
![sound-prefs](https://user-images.githubusercontent.com/114750/43853855-9a38398c-9b41-11e8-8f2e-5184f2c6910d.png)

**Comment by alfredh** [comment]
you can also use the portaudio module:

```
portaudio: device count is 4
portaudio: device 0: Built-in Microphone
portaudio: device 1: Built-in Output
portaudio: device 2: C-Media USB Headphone Set  
portaudio: device 3: C-Media USB Headphone Set  
```

Sample config:

```
audio_player  portaudio,2
audio_source  portaudio,3
```
