### ISSUE TITLE
how to figure out which UA message was sent to?

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#484]
When message comes in, message handler is called:

typedef void (message_recv_h)(const struct pl *peer, const struct pl *ctype,
			      struct mbuf *body, void *arg);

How can the handler find out which UA the message was sent to?

**Comment by Encamy** [comment]
Maybe it uses current UA?
There are two methods for getting and setting current UA
```c++
void uag_current_set(struct ua *ua)
{
	uag.ua_cur = ua;
}


struct ua *uag_current(void)
{
	if (list_isempty(uag_list()))
		return NULL;

	return uag.ua_cur;
}
```
It's just a guess, I can not be sure

**Comment by juha-h** [comment]
I made a test.  When message arrives to sip:bar@test.tutpro.com and current UA is sip:foo@test.tutpro.com, current UA is not automatically changed to bar.  The question thus is still unanswered.

**Comment by juha-h** [comment]
juha-h writes:

> When message comes in, message handler is called:
> 
> typedef void (message_recv_h)(const struct pl *peer, const struct pl *ctype,
> 			      struct mbuf *body, void *arg);
> 
> How can the handler find out which UA the message was sent to?

message.c/handle_message() that calls the handler has the ua as
argument, but does not use it:

  static void handle_message(struct message_lsnr *lsnr, struct ua *ua,
  			   const struct sip_msg *msg)
  {
  	static const char ctype_text[] = "text/plain";
  	struct pl ctype_pl = {ctype_text, sizeof(ctype_text)-1};
  	(void)ua;

  	if (msg_ctype_cmp(&msg->ctyp, "text", "plain") && lsnr->recvh) {

  		lsnr->recvh(&msg->from.auri, &ctype_pl,
  			       msg->mb, lsnr->arg);

  		(void)sip_reply(uag_sip(), msg, 200, "OK");
  	}
  	else {
  		(void)sip_replyf(uag_sip(), msg, 415, "Unsupported Media Type",
  				 "Accept: %s\r\n"
  				 "Content-Length: 0\r\n"
  				 "\r\n",
  				 ctype_text);
  	}
  }

Should ua be added as argument to receive handler function?

**Comment by juha-h** [comment]
Solved by commit https://github.com/alfredh/baresip/pull/485
