### ISSUE TITLE
Can call to the same address multiple times

### ISSUE THREAD

**Issue by AlexMarlo** [alfredh/baresip#49]

**Comment by lmangani** [comment]
Please kindly provide a clear description, expected vs. actual results and steps to reproduce your issue

**Comment by AlexMarlo** [comment]
--- List of active calls (3): ---
  0:00:47  ESTABLISHED  sip:5555@192.168.0.108;audio_codecs=gsm/8000
  0:00:34  ESTABLISHED  sip:5555@192.168.0.108;audio_codecs=gsm/8000
  0:00:03  ESTABLISHED  sip:5555@192.168.0.108;audio_codecs=gsm/8000

multiple calls to same address

**Comment by czarkoff** [comment]
What is wrong about it? How do you want baresip to manage multiple calls to the same address?

**Comment by AlexMarlo** [comment]
Most obvious and logical way is to reject to call until existed call to same address is finished

**Comment by nshopik** [comment]
I doubt it should reject that, same number may routed differently each time by some GW for example

**Comment by alfredh** [comment]
baresip is by nature a flexible tool, with few restrictions on what the user can do.

multiple calls to the same target is a feature, by design.
