### ISSUE TITLE
Error when build zrtp for Android on MacOS using ndk version 16b and above

### ISSUE THREAD

**Issue by caominhvu** [alfredh/baresip#497]
When I executed command: make zrtp, I got error

> ========================= configuring bnlib ==============================
> checking For C compiler... /Users/victorcao/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc --sysroot /Users/victorcao/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-arm
> checking whether we are using GNU CC... yes
> checking for ranlib... /Users/victorcao/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-ranlib
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... configure: error: in `/Users/victorcao/Documents/workspace/EdgeWorks/SuperBaresip/baresip-android/libzrtp/third_party/bnlib':
> configure: error: cannot run C compiled programs.
> If you meant to cross compile, use `--host'.
> See `config.log' for more details

This is config.log file

[config.log](https://github.com/alfredh/baresip/files/2260219/config.log)

Can you please help check this?

**Comment by juha-h** [comment]
I tried and didn't have the problem you described.  I use ndk/sdk from
Android Studio if that makes any difference.

-- Juha

**Comment by caominhvu** [comment]
Dear Juha,

Thank you for your quick response. I am using ndk ver16 from Android Studio too.
Can you please let me know your versions of autobuild, autoconf, makefile ?
Also, did you build on MacOS, Window or Linux ?

**Comment by juha-h** [comment]
I'm on Debian Linux (Stretch) and have edited baresip-android Makefile like this:

NDK_PATH  := /usr/local/Android/Sdk/ndk-bundle
SDK_PATH  := /usr/local/Android/Sdk

Otherwise everything is as described in README.

**Comment by caominhvu** [comment]
yes, I did similar too. Can you please tell me your versions of autobuild, autoconf, Makefile?

**Comment by caominhvu** [comment]
Seems this issue just occurs on MacOS only, no problem with Ubuntu

**Comment by alfredh** [comment]
in your config.log file there is an error:

```
./configure: line 2945: ./conftest: cannot execute binary file
```

is it only zrtp that fails, or does also opus fail ?

which version of MacOSX are you using ? do you have Homebrew and/or Macports installed ?



Alfred

**Comment by caominhvu** [comment]
Hi @alfredh 
opus also failed. I am using MacOSX 10.13.6 with Macports installed
(please note that android ndk version 15c is ok for all)

**Comment by alfredh** [comment]
I tried to build opus on Debian Testing with Android NDK r16b and it works fine.

```
opus 1.2.1

autoconf (GNU Autoconf) 2.69

automake (GNU automake) 1.15.1

GNU Make 4.2.1

libtoolize (GNU libtool) 2.4.6
```

are you using opus from git or opus tarball ? I think the tarball contains
the `configure` script but with git you have to generate it yourself.

**Comment by alfredh** [comment]
btw, can you check that you are using latest version of baresip-android
Makefile, i.e. commit afd49a3778e09bd0b8f8faada9b6ba86ed9ca7c8

can you also provide the full log output from "make opus",
here is from my build:

```
cd opus && \
	rm -rf include_opus && \
	CC="/home/alfredh/android/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot /home/alfredh/android/android-ndk-r16b/platforms/android-21/arch-arm" \
	RANLIB="/home/alfredh/android/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ranlib" AR="/home/alfredh/android/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar" PATH="/home/alfredh/android/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin:/home/alfredh/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/alfredh/git/.3rd/depot_tools" \
	./configure --host=arm-linux-androideabi --disable-shared \
		--disable-doc \
		--disable-extra-programs \
		CFLAGS="-D__ANDROID_API__=21 -isystem /home/alfredh/android/android-ndk-r16b/sysroot/usr/include/ -isystem /home/alfredh/android/android-ndk-r16b/sysroot/usr/include/arm-linux-androideabi -I/home/alfredh/git/baresip-android/openssl/include -I/home/alfredh/git/baresip-android/opus/include_opus -I/home/alfredh/git/baresip-android/libzrtp/include -I/home/alfredh/git/baresip-android/libzrtp/third_party/bnlib -I/home/alfredh/git/baresip-android/libzrtp/third_party/bgaes -march=armv7-a -fPIE -fPIC -DCONFIG_PATH='\"/data/local/tmp\"'" && \
	CC="/home/alfredh/android/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot /home/alfredh/android/android-ndk-r16b/platforms/android-21/arch-arm" \
	RANLIB="/home/alfredh/android/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ranlib" AR="/home/alfredh/android/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar" PATH="/home/alfredh/android/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin:/home/alfredh/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/alfredh/git/.3rd/depot_tools" \
	make && \
	mkdir include_opus && \
	mkdir include_opus/opus && \
	cp include/* include_opus/opus
checking whether make supports nested variables... yes
```

BTW2: perhaps it is better to move this ticket to the baresip-android project ?

**Comment by alfredh** [comment]
please create a new issue here:

https://github.com/alfredh/baresip-android

and also please include full build logs.
