### ISSUE TITLE
srtp.c - SRTP_AES_128_GCM

### ISSUE THREAD

**Issue by jungle-boogie** [alfredh/baresip#499]
Hi,

I hope to not be wasting your time with this report and that it's something at least partially legitimate.

```
modules/srtp/srtp.c: In function 'resolve_suite':
modules/srtp/srtp.c:125: error: 'SRTP_AES_128_GCM' undeclared (first use in this function)
modules/srtp/srtp.c:125: error: (Each undeclared identifier is reported only once
modules/srtp/srtp.c:125: error: for each function it appears in.)
modules/srtp/srtp.c: In function 'get_master_keylen':
modules/srtp/srtp.c:137: error: 'SRTP_AES_128_GCM' undeclared (first use in this function)
gmake: *** [mk/mod.mk:44: build-x86_64/modules/srtp/srtp.o] Error 1
```

openBSD -current amd64

**Comment by alfredh** [comment]
aha, you need to upgrade libre to latest version :)

AES GCM (Galois Counter Mode) was added in this commit:

https://github.com/creytiv/re/commit/25dfb8ccf77adef3667d92d87df6b36c966af744


Alfred

**Comment by jungle-boogie** [comment]
Hi @alfredh,

Thank you!

Sorry for the noise here.
