### ISSUE TITLE
Can't hold current active call if have incoming call

### ISSUE THREAD

**Issue by AlexMarlo** [alfredh/baresip#50]

**Comment by lmangani** [comment]
Please kindly provide a clear description, expected vs. actual results and steps to reproduce your issue

**Comment by AlexMarlo** [comment]
I have active call. When i have incoming call i cant put active call on hold and switch to incoming. All what i can do is answer o hangup and if i answer i will hear and speak with both calls like in conference. This is incorrect logic.

**Comment by alfredh** [comment]
yeah .. this calling logic needs some rather big improvements ..

**Comment by lmangani** [comment]
Just to wrap up, a few items are being discussed altogether - while audio from the two separate calls is not "bridged" for the remote parties with the scenario you mentioned, both calls will play back audio to the same local interface creating the "conference" like result when receiving RTP from both sessions contextually - the only option I would see for those wanting one, would be a preference to automatically hold the existing session(s) for calls reaching the very same account or switching calls, which is currently unavailable.

On a larger scale, a new dedicated CLI & API command for selecting and interacting with open calls in Baresip (other than the spacebar account switch mode) for sessions initiated by either of the registered accounts on the system could also be the catch-all solution, providing integrators options to handle multiple call scenarios case-by-case using external logic.

**Comment by AlexMarlo** [comment]
great! thanks

**Comment by sbourji** [comment]
is there a way to have 3 way audio conference in baresip?
