### ISSUE TITLE
baresip overrides empty contacts file

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#500]
If I make contacts file empty and start baresip, my empty contacts file is replaced by the default contacts file.  In my opinion, default file should be generated only if contacts file does not exist at all.  Any other opinions?

**Comment by alfredh** [comment]
this logic is done by this function:

```
bool conf_fileexist(const char *path)
{
        struct stat st;

        if (!path)
                 return false;

        if (stat(path, &st) < 0)
                 return false;

        if ((st.st_mode & S_IFMT) != S_IFREG)
                 return false;

        return st.st_size > 0;
}
```

it checks if the size is > 0. 

if you add an empty comment to the file, it will not be re-generated:

~/.baresip/contacts:
```
# empty
```

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> it checks if the size is > 0. 
> 
> if you add an empty comment to the file, it will not be re-generated:
> 
> ~/.baresip/contacts:
> ```
> # empty

Yes, I figured that out.  But why the size test?  Empty contacts file is
a valid contacts file.

-- Juha

**Comment by alfredh** [comment]
there is no specific reason for the size test, I think.

I dont have any strong opinions about this.

**Comment by juha-h** [comment]
I propose replacing

return st.st_size > 0;

with

return true.

**Comment by alfredh** [comment]
the sounds good.

would you please be so kind to create a PR for that change ?

also please test that it does not have any strange side-effects :)


Alfred

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> would you please be so kind to create a PR for that change ?
> 
> also please test that it does not have any strange side-effects :)

Done, Juha

**Comment by juha-h** [comment]
Closed by commit
https://github.com/alfredh/baresip/commit/2fd98cd6977b0beae8cf98d25e344ced9bc93af4
