### ISSUE TITLE
Fails to build b2bua module with GCC 8.2.0: multiple definition of `exports'

### ISSUE THREAD

**Issue by jonassmedegaard** [alfredh/baresip#506]
Hi,

Building baresip 0.5.10 on Debian unstable - i.e. with GCC 8.2.0 - fails:

ccache gcc -DRELEASE -Wall -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wbad-function-cast -Wsign-compare -Wnested-externs -Wshadow -Waggregate-return -Wcast-align -g -O3   -Wuninitialized -Wno-strict-aliasing -fPIC -DLINUX -DOS=\"linux\" -std=c99 -pedantic -DARCH=\"x86_64\" -DUSE_OPENSSL -DUSE_TLS -DUSE_OPENSSL_DTLS -DUSE_DTLS -DUSE_OPENSSL_SRTP -DUSE_DTLS_SRTP -DUSE_ZLIB -DHAVE_PTHREAD -DHAVE_GETIFADDRS -DHAVE_STRERROR_R -DHAVE_GETOPT -DHAVE_INTTYPES_H -DHAVE_NET_ROUTE_H -DHAVE_SYS_SYSCTL_H -DHAVE_STDBOOL_H -DHAVE_INET6 -DHAVE_RESOLV -DHAVE_SYSLOG -DHAVE_FORK -DHAVE_INET_NTOP -DHAVE_PWD_H -DHAVE_POLL    -DHAVE_INET_PTON -DHAVE_SELECT -DHAVE_SELECT_H -DHAVE_SETRLIMIT -DHAVE_SIGNAL -DHAVE_SYS_TIME_H -DHAVE_EPOLL -DHAVE_UNAME -DHAVE_UNISTD_H -DHAVE_STRINGS_H -DHAVE_GAI_STRERROR -DVERSION=\"0.5.10\" -g -O2 -fdebug-prefix-map=/build/baresip-0.5.10=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -I. -Iinclude -I/usr/include/re -I/usr/include -I/include -I/usr/local/include/rem -I/usr/include/rem -D_GNU_SOURCE -DUSE_VIDEO=1 -DMODULE_CONF -DPREFIX=\"/usr\" -DMOD_PATH=\"/usr/lib/baresip/modules\" -DSHARE_PATH=\"/usr/share/baresip\" -DUSE_AVCODEC -DUSE_AVFORMAT  \
        -c modules/b2bua/b2bua.c -o build-x86_64/modules/b2bua/b2bua.o -MD -MF build-x86_64/modules/b2bua/b2bua.d -MT build-x86_64/modules/b2bua/b2bua.o
  LD [M]  b2bua.so
gcc -fPIC -Wl,-z,relro -shared  -L/usr/local/lib \
        build-x86_64/modules/b2bua/b2bua.o build-x86_64/modules/b2bua/b2bua.o    \
         -L -lre -o b2bua.so
/usr/bin/ld: build-x86_64/modules/b2bua/b2bua.o:./modules/b2bua/b2bua.c:244: multiple definition of `exports'; build-x86_64/modules/b2bua/b2bua.o:./modules/b2bua/b2bua.c:244: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [mk/mod.mk:36: b2bua.so] Error 1

**Comment by alfredh** [comment]
how is the make command invoked ?

the b2bua module is now built by default, there is no longer need to add
it to the EXTRA_MODULES parameter.


Alfred

**Comment by jonassmedegaard** [comment]
whoops, then my (i.e. the official Debian packaging) controversial (ab)use of your make infrastructure is to blame. Sorry!

**Comment by jonassmedegaard** [comment]
In case you are curious, here's how Debian build is currently executed: https://buildd.debian.org/status/fetch.php?pkg=baresip&arch=amd64&ver=0.5.9-1%2Bb3&stamp=1531997504&raw=0

And here's the debian/rules file triggering that build: https://sources.debian.org/src/baresip/0.5.9-1/debian/rules/

**Comment by jonassmedegaard** [comment]
adjusting for b2bua, and the code builds flawlessly across architectures in Debian: https://buildd.debian.org/status/package.php?p=baresip

Thanks for a very nicely written codebase - pleasant to deal with as a distribution package maintainer!
