### ISSUE TITLE
Error in x11 module - will not work over remote x11 session

### ISSUE THREAD

**Issue by rmundkowsky** [alfredh/baresip#507]
Your code does not correctly check if shared memory is usable.  Shared memory only works if X11 server and client are on the same server.  I have a patch to correct your code, the diff is below.  I tested this on MobaXterm from a remote of baresip.  Be warned I know very little about X11, so hope the code is clean.  BTW, nice software, the modules are nice and small enough for a guy like me to understand.
```
194c194,195
<               XDestroyImage(st->image);
---
>               st->image->data = NULL;
>               XDestroyImage(st->image);
224,226c225,229
<       if (!XShmAttach(st->disp, &st->shm)) {
<               warning("x11: failed to attach X to shared memory\n");
<               return ENOMEM;
---
>       if (st->xshmat){
>         if (!XShmAttach(st->disp, &st->shm)) {
>                       warning("x11: failed to attach X to shared memory\n");
>                       return ENOMEM;
>                }
232c235,236
<       if (x11.shm_error)
---
>       if (!XShmQueryExtension(st->disp)){
>       //      if (x11.shm_error)
234c238,240
<       else
---
>               st->xshmat = false;
>       }
>       else{
235a242
>       }
```

**Comment by alfredh** [comment]
I tested with a remote X11 server and it was working.

thanks for the patch anyway, I will test it

**Comment by rmundkowsky** [comment]
Shared memory extensions for X11 only work if the client and server are on the same box. I was running X11 server on Windows laptop and client on AWS server. And did not work without the changes.

Robert Mundkowsky

**Comment by alfredh** [comment]
I have some problems to apply your patch, could you please make a PR instead ?


I tested the current code on two platforms, OSX and Linux

* OSX, xclient and xserver on same machine:
x11: shared memory enabled

* Linux: local xclient and xserver on osx:
x11: shared memory disabled
DISPLAY=localhost:10.0


so those 2 cases are working, perhaps there is a bug in your usecase
(Windows and AWS).

if you can provide a debug log from the non-working case that would be awesome :)


Alfred

**Comment by rmundkowsky** [comment]
Sure, I’ll make a pull request. Might be a bug in mobaXterm.


I tried to disable shared memory via following environment variables, but did not help:
export QT_X11_NO_MITSHM=1
export _X11_NO_MITSHM=1
export _MITSHM=0

Main issue seen in the logs is:
Xlib:  extension "MIT-SHM" missing on display "localhost:10.0".
x11: failed to attach X to shared memory

root@ip-10-0-3-18:~# baresip
baresip v0.5.10 Copyright (C) 2010 - 2018 Alfred E. Heggestad et al.
Local network address:  IPv4=eth0:10.0.3.18  IPv6=eth0:2600:1f18:63cf:b000:e544:25ae:f89a:65e5
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
dl: mod: /usr/local/lib/baresip/modules/alsa.so (/usr/local/lib/baresip/modules/alsa.so: cannot open shared object file: No such file or directory)
module alsa.so: No such file or directory
vidcodec: VP8
dl: mod: /usr/local/lib/baresip/modules/vp9.so (/usr/local/lib/baresip/modules/vp9.so: cannot open shared object file: No such file or directory)
module vp9.so: No such file or directory
vidisp: x11
medianat: stun
medianat: turn
medianat: ice
Populated 1 account
Populated 3 contacts
Populated 2 audio codecs
Populated 1 audio filter
Populated 1 video codec
Populated 0 video filters
baresip is ready.
2000@10.0.3.23: {0/UDP/v4} 200 OK () [1 binding]
All 1 useragent registered successfully! (2 ms)
sip:2000@10.0.3.23: Incoming call from: Extension 2002 sip:2002@10.0.3.23 - (press 'a' to accept)
sip:2000@10.0.3.23: Answering incoming call
answering call from sip:2002@10.0.3.23 with 200
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: Set audio encoder: PCMU 8000Hz 1ch
audio tx pipeline:         src ---> vumeter ---> PCMU
audio rx pipeline:        play <--- vumeter <--- PCMU
Set video encoder: VP8  (500000 bit/s, 25.00 fps)
video: no video source
main: long async blocking: 1119>100 ms (h=0x7f4108e1cdf9 arg=0x13e12c0)
Set video decoder: VP8
2000@10.0.3.23: Call established: sip:2002@10.0.3.23
stream: incoming rtp for 'video' established, receiving from 10.0.3.23:32328
Xlib:  extension "MIT-SHM" missing on display "localhost:10.0".
x11: failed to attach X to shared memory
Xlib:  extension "MIT-SHM" missing on display "localhost:10.0".
x11: failed to attach X to shared memory
Xlib:  extension "MIT-SHM" missing on display "localhost:10.0".
x11: failed to attach X to shared memory
Xlib:  extension "MIT-SHM" missing on display "localhost:10.0".
x11: failed to attach X to shared memory
Xlib:  extension "MIT-SHM" missing on display "localhost:10.0".
…


Robert Mundkowsky

**Comment by rmundkowsky** [comment]
Still need write permission in github for my account to push the branch and do PR

Username:

                rmundkowsky

Robert Mundkowsky

From: Mundkowsky, Robert
Sent: Monday, August 20, 2018 11:36 AM
To: 'alfredh/baresip' <reply@reply.github.com>; alfredh/baresip <baresip@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [alfredh/baresip] Error in x11 module - will not work over remote x11 session (#507)

Sure, I’ll make a pull request. Might be a bug in mobaXterm.


I tried to disable shared memory via following environment variables, but did not help:
export QT_X11_NO_MITSHM=1
export _X11_NO_MITSHM=1
export _MITSHM=0

Main issue seen in the logs is:
Xlib:  extension "MIT-SHM" missing on display "localhost:10.0".
x11: failed to attach X to shared memory

root@ip-10-0-3-18:~# baresip
baresip v0.5.10 Copyright (C) 2010 - 2018 Alfred E. Heggestad et al.
Local network address:  IPv4=eth0:10.0.3.18  IPv6=eth0:2600:1f18:63cf:b000:e544:25ae:f89a:65e5
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
dl: mod: /usr/local/lib/baresip/modules/alsa.so (/usr/local/lib/baresip/modules/alsa.so: cannot open shared object file: No such file or directory)
module alsa.so: No such file or directory
vidcodec: VP8
dl: mod: /usr/local/lib/baresip/modules/vp9.so (/usr/local/lib/baresip/modules/vp9.so: cannot open shared object file: No such file or directory)
module vp9.so: No such file or directory
vidisp: x11
medianat: stun
medianat: turn
medianat: ice
Populated 1 account
Populated 3 contacts
Populated 2 audio codecs
Populated 1 audio filter
Populated 1 video codec
Populated 0 video filters
baresip is ready.
2000@10.0.3.23<mailto:2000@10.0.3.23>: {0/UDP/v4} 200 OK () [1 binding]
All 1 useragent registered successfully! (2 ms)
sip:2000@10.0.3.23: Incoming call from: Extension 2002 sip:2002@10.0.3.23 - (press 'a' to accept)
sip:2000@10.0.3.23: Answering incoming call
answering call from sip:2002@10.0.3.23 with 200
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: Set audio encoder: PCMU 8000Hz 1ch
audio tx pipeline:         src ---> vumeter ---> PCMU
audio rx pipeline:        play <--- vumeter <--- PCMU
Set video encoder: VP8  (500000 bit/s, 25.00 fps)
video: no video source
main: long async blocking: 1119>100 ms (h=0x7f4108e1cdf9 arg=0x13e12c0)
Set video decoder: VP8
2000@10.0.3.23<mailto:2000@10.0.3.23>: Call established: sip:2002@10.0.3.23
stream: incoming rtp for 'video' established, receiving from 10.0.3.23:32328
Xlib:  extension "MIT-SHM" missing on display "localhost:10.0".
x11: failed to attach X to shared memory
Xlib:  extension "MIT-SHM" missing on display "localhost:10.0".
x11: failed to attach X to shared memory
Xlib:  extension "MIT-SHM" missing on display "localhost:10.0".
x11: failed to attach X to shared memory
Xlib:  extension "MIT-SHM" missing on display "localhost:10.0".
x11: failed to attach X to shared memory
Xlib:  extension "MIT-SHM" missing on display "localhost:10.0".
…


Robert Mundkowsky

**Comment by alfredh** [comment]
hi @rmundkowsky 

you need to fork the project first and then make the PR from there.

Please read here how to do it:

https://help.github.com/articles/creating-a-pull-request-from-a-fork/


Alfred

**Comment by rmundkowsky** [comment]
Ok, but a branch would be easier. There is no reason to make a fork, I don’t plan to have my own copy.  Also I then have to make sure the fork is keep up to date with the master.

Robert Mundkowsky
