### ISSUE TITLE
no user agents when baresip is started w/o networks access

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#508]
When baresip is started without network access, no user agents are created and uag_list() is empty.  This creates a problem to my baresip app, which shows to user that no user agents exists.  Why can't baresip create the user agents even when network access does not exist?  If they would exist, it would then be easy for a baresip app to register the UAs when network access becomes available.

**Comment by juha-h** [comment]
Here is example.  I start baresip without network access (only local address is available):

````$ baresip
baresip v0.5.10 Copyright (C) 2010 - 2018 Alfred E. Heggestad et al.
Local network address:  IPv4=:127.0.0.1 
aucodec: opus/48000/2
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
ausrc: alsa
auplay: alsa
auplay: pulse
ausrc: pulse
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
medianat: stun
medianat: ice
mediaenc: srtp
mediaenc: srtp-mand
mediaenc: srtp-mandf
mediaenc: dtls_srtpf
mediaenc: dtls_srtp
mediaenc: srtp-mandf
mediaenc: zrtp
ua: SIP register failed: Network is unreachable
module account.so: Network is unreachable
Populated 0 contacts
Subscribing to 0 contacts
Populated 3 audio codecs
Populated 0 audio filters
Populated 3 video codecs
Populated 0 video filters
baresip is ready.
````
Then I connect to wifi and a bit later get to console:

````net: local IPv4 address changed: 127.0.0.1 -> 192.168.43.107
IP-address changed: 192.168.43.107
````

However, the UA is not registered, because the account was not added when baresip was started w/o
network access.

So I need to quit:
````
Quit
ua: stop all (forced=0)
````

**Comment by juha-h** [comment]
More info about this.  If I have not given outbound proxy for the account, the account is added even without network connection:
````
...
mediaenc: zrtp
Populated 1 account
Populated 0 contacts
...
````
And if I add outbound proxy to the account, which, of course, is not reachable without network connection, the account is not added:
````
...
mediaenc: zrtp
test@test.tutpro.com: Using sipnat: `outbound'
test@test.tutpro.com: Using media encryption `zrtp'
ua: SIP register failed: Network is unreachable
module account.so: Network is unreachable
Populated 0 contacts
...
````
Does this start to look like a bug, i.e., baresip should add the account with or without network connection?

**Comment by juha-h** [comment]
Reading of the code revealed that if ua_register() fails, ua_alloc() fails and the ua is destroyed. Simple "fix" is to allow registering to fail:
````
diff --git a/src/ua.c b/src/ua.c
index 4975a73..054213e 100644
--- a/src/ua.c
+++ b/src/ua.c
@@ -203,21 +203,21 @@ int ua_register(struct ua *ua)
 
    for (le = ua->regl.head, i=0; le; le = le->next, i++) {
        struct reg *reg = le->data;
 
        err = reg_register(reg, reg_uri, params,
                   acc->regint, acc->outboundv[i]);
        if (err) {
            warning("ua: SIP register failed: %m\n", err);
 
            ua_event(ua, UA_EVENT_REGISTER_FAIL, NULL, "%m", err);
-           goto out;
+           err = 0;
        }
    }
 
  out:
    mem_deref(reg_uri);
 
    return err;
 }
````
Another possible patch could be to use some dedicated error code for register failure due to network issues and if that code matches, the ua is not destroyed.

Comments?

**Comment by juha-h** [comment]
Here is an example after the above patch.  Baresip starts without network connection:
````
Local network address:  IPv4=:127.0.0.1 
aucodec: opus/48000/2
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
ausrc: alsa
auplay: alsa
auplay: pulse
ausrc: pulse
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
medianat: stun
medianat: ice
mediaenc: srtp
mediaenc: srtp-mand
mediaenc: srtp-mandf
mediaenc: dtls_srtpf
mediaenc: dtls_srtp
mediaenc: srtp-mandf
mediaenc: zrtp
ua event: REGISTERING
ua: SIP register failed: Network is unreachable
ua event: REGISTER_FAIL
Populated 1 account
Populated 0 contacts
Subscribing to 0 contacts
Populated 3 audio codecs
Populated 0 audio filters
Populated 3 video codecs
Populated 0 video filters
````
Then network connection is established and after a short while the ua is automatically registered:
````
net: local IPv4 address changed: 127.0.0.1 -> 192.168.43.107
IP-address changed: 192.168.43.107
ua event: REGISTERING
test@test.tutpro.com: {0/TLS/v4} 200 OK (OpenSIPg SIP Proxy (5.2.0-0a04 (x86_64/linux))) [2 bindings]
ua event: REGISTER_OK
All 1 useragent registered successfully! (60043 ms)
````
Must better than without the patch!

**Comment by alfredh** [comment]
I think one solution here is to split `ua_alloc` into `ua_alloc` and something like `ua_start`.

the ua_alloc will do the things it is already doing, except register.

the ua_start will basically "start" the UA incl. sending register etc.


Alfred

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I think one solution here is to split `ua_alloc` into `ua_alloc` and something like `ua_start`.
> 
> the ua_alloc will do the things it is already doing, except register.
> 
> the ua_start will basically "start" the UA incl. sending register etc.

Sounds good.  I'm pretty busy right now, but can look it during the next
few days.

**Comment by alfredh** [comment]
there is also another solution; setting the regint to 0

1. create ua_alloc with regint=0
2. wait for network
3. when network is up, set regint to e.g. 600 and call
  `ua_update_account` and then `ua_register`

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> there is also another solution; setting the regint to 0
> 
> 1. create ua_alloc with regint=0
> 2. wait for network
> 3. when network is up, set regint to e.g. 600 and call
>   `ua_update_account` and then `ua_register`

That sounds like a hack to me.  The true regint would need to be stored
somewhere else and always save accounts with regint=0.

-- Juha

**Comment by alfredh** [comment]
hi @juha-h 

please have a look at this branch/PR:

https://github.com/alfredh/baresip/pull/509

the suggestion is to remove the "register" step from `ua_alloc` and let the application
call `ua_register` explicitly (if regint is set). this also makes the API a bit more flexible.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> please have a look at this branch/PR:
> 
> https://github.com/alfredh/baresip/pull/509
> 
> the suggestion is to remove the "register" step from `ua_alloc` and
> let the application 
> call `ua_register` explicitly (if regint is set). this also makes the
> API a bit more flexible.

Looks good.  I'll give it a test during the weekend,

One question: in account.c, should password be asked before ua_register
is called?

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> the suggestion is to remove the "register" step from `ua_alloc` and
> let the application 
> call `ua_register` explicitly (if regint is set). this also makes the
> API a bit more flexible.

As an example, how would

https://github.com/alfredh/baresip/wiki/Using-baresip-as-a-library

look like after the change?

**Comment by alfredh** [comment]
the new sequence would be:

1. ua_alloc

2. ua_register

**Comment by juha-h** [comment]
Fixed by commit https://github.com/alfredh/baresip/commit/26c9f03ff8950e70a303246032662b3e293de541.

**Comment by juha-h** [comment]
I have to reopen this issue.  If there is more than one account in accounts file and baresip is started without network access, only the first account is created.

The reason seems to be that in account module
````
err =  conf_parse(file, line_handler, NULL);
````
stops parsing lines if parsing of a line returns error and line_handler returns error if registration fails.

**Comment by alfredh** [comment]
the reason is most likely this code in account module:


```
	if (account_regint(acc) != 0) {
		err = ua_register(ua);
		if (err) {
			warning("account: failed to register ua (%m)\n", err);
		}
	}

```

a suggestion could be to just ignore the return value.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> the reason is most likely this code in account module:
> 
> ```
> 	if (account_regint(acc) != 0) {
> 		err = ua_register(ua);
> 		if (err) {
> 			warning("account: failed to register ua (%m)\n", err);
> 		}
> 	}
> 
> ```
> 
> a suggestion could be to just ignore the return value.

Yes.

**Comment by alfredh** [comment]
okay, could you please try again with commit 3774a2a1a73bebbbd27285de19510f75676576ba ?

**Comment by juha-h** [comment]
Now works also with more than one account.
