### ISSUE TITLE
No calls control from anywhere 

### ISSUE THREAD

**Issue by AlexMarlo** [alfredh/baresip#51]
i hope to see that i cant get call id and them use it to control call with that id
Now i can control only current call

**Comment by AlexMarlo** [comment]
For implementing this task i have following:

add unique id for call which is independent from any infrastructure (like sip) 

I tried to add call id but it is hard task to add crossplatform unique id generator.
To solve this problem we can use incremental call id but i don't know about any thread in design of baresip which can cause same call ids for different calls

**Comment by lmangani** [comment]
See comments in https://github.com/alfredh/baresip/issues/50

**Comment by alfredh** [comment]
how about this algorithm for generating a globally unique "Call" ID?

GCID = BASE64(HMAC_SHA1(rand, call | rand| ua))

```
static void mk_uid(struct call *call, struct ua *ua)
{
	char buf[256];
	uint8_t fp[20];
	uint8_t key[8];
	size_t n;
	char b64[128];
	size_t b64_len = sizeof(b64);

	rand_bytes(key, sizeof(key));

	n = re_snprintf(buf, sizeof(buf), "%p%u%p", call, rand_u32(), ua);

	hmac_sha1(key,
		  sizeof(key),
		  (void *)buf,
		  n,
		  fp,
		  sizeof(fp));

	base64_encode(fp, sizeof(fp), b64, &b64_len);

	re_printf("CALL-UID: %b\n", b64, b64_len);
}
```

**Comment by AlexMarlo** [comment]
i think that call id should be independent from call initialisation.
This means that even before call is created we can generate uid and control it.
But it is only my view on this.

**Comment by alfredh** [comment]
can you suggest a good way to generate this CALLID ?

I am not sure if I understand your suggestions?

**Comment by AlexMarlo** [comment]
For c++ i use http://www.boost.org/doc/libs/1_56_0/doc/html/boost_random.html this library and it can provide very good id generation, but for C i don't know such library.

**Comment by alfredh** [comment]
I have some problems understanding the requirements, so I am going to close
this issue for now.

If someone really needs this, please open a new issue with a very clear description
and preferably also some sample application code to see how the wanted API should be.
