### ISSUE TITLE
Http interface: CORS header ‘Access-Control-Allow-Origin’ missing

### ISSUE THREAD

**Issue by nicotyze** [alfredh/baresip#515]
I'm trying to develop a more "advanced" user interface based on the http module.

This is a simple example:
[test_html.txt](https://github.com/alfredh/baresip/files/2314049/test_html.txt) (to be renamed test.html)

As it is, it does not not really work with the http server provided by libre: web browsers block cross-origin requests.

With this simple patch, it would be ok:
```diff
--- a/src/http/server.c
+++ b/src/http/server.c
@@ -485,6 +485,7 @@ int http_creply(struct http_conn *conn, uint16_t scode, const char *reason,
        err = http_reply(conn, scode, reason,
                         "Content-Type: %s\r\n"
                         "Content-Length: %zu\r\n"
+                        "Access-Control-Allow-Origin: *\r\n"
                         "\r\n"
                         "%b",
                         ctype,
```
Would this modification, as a PR in libre, would be acceptable ? 

Open to consider an other approach if this proposal is a wrong track.

**Comment by alfredh** [comment]
There is no need to modify the libre HTTP module.

Custom headers can be added to the fmt parameter in http_reply:

http://www.creytiv.com/doxygen/re-dox/html/re__http_8h.html#aa76f1bb2c6718c1c844953b05219b8fa

in your case you can use `http_reply` like this:

```c
http_reply(struct http_conn *conn, 200, "OK",
           "Content-Length: 12345\r\n"
           "Access-Control-Allow-Origin: *\r\n"
)
```


Alfred

**Comment by nicotyze** [comment]
Hi Alfred ,

Many thanks for you answer, suggestion.

I've found a way to add  this custom header in http_req_handler (httpd.c).
I would like to propose a PR for that.

Would it be acceptable to use the last argument void* arg of the function to provide custom headers ?
And would it be acceptable to have a new configurable module parameter like (http_acao ) to specify URI for Access-Control-Allow-Origin ?

Nicolas

**Comment by alfredh** [comment]
I think you can modify the httpd module to just always include that header in the reply.

HTTP Clients that dont understand the header will still work, no ?

If you feel that there is a need to configure it, sure we can add it if you want :)
