### ISSUE TITLE
Mirror EBU ACIP parameters (jitter buffer)

### ISSUE THREAD

**Issue by djhenley** [alfredh/baresip#519]
Hi,

Today Baresip signals the EBU ACIP parameters regarding RX jitter buffer perfectly well in the SDP when setting up an **outgoing** call. 
All according to tech3368 (see chapter 3.4 and 3.4.4)
https://tech.ebu.ch/docs/tech/tech3368.pdf

```
a=ebuacip:jb 0
a=ebuacip:jbdef 0 fixed 150
```

However, an **incoming** call with these parameters in the SDP is ignored by Baresip, consequently the jitter buffer is not being set accordingly.

**Would it be possible in any way to parse the ebuacip parameter regarding jitter buffer and thereby use the offered jitter buffer values when answering the incoming call?**

Example 1:
```
a=ptime:20
a=ebuacip:jb 0
a=ebuacip:jbdef 0 fixed 150
```
Result: offered jitter buffer(150ms)/ptime(20ms) = 7.5 frames 

...which would result in:
`jitter_buffer_delay 7-8` (today set as an interval in the config file)

Example 2:
```
a=ptime:20
a=ebuacip:jb 0
a=ebuacip:jbdef 0 fixed 200

```
 ...would result in:
`jitter_buffer_delay 9-10`

Why this is very useful (quote from the ebu document chapter 3.4)

> ...It is likely that the caller user agent, or the person or system using the caller user agent, may well be aware of the network properties of the network that will be used for the call. This makes it reasonable for the caller to suggest settings for the receiving buffer (at the callee end).
---------------------------------------------------------------------------------------

For further consideration, I'm aware it might be acquire some major changes, but if it would be possible to set the jitter-buffer during on ongoing call/on the fly it would be awesome. E.g, that would enable Baresip to automatically adjust the jitter buffer according to the current network conditions.

**Comment by alfredh** [comment]
this should be possible to implement.

you need to parse the relevant SDP parameters for incoming calls,
for exampling in audio_sdp_attr_decode. then we can add a new function
in stream.c to set the jitter buffer parameters.

in stream.c the jitter buffer is created here:

```c
	/* Jitter buffer */
	if (cfg->jbuf_del.min && cfg->jbuf_del.max) {

		err = jbuf_alloc(&s->jbuf, cfg->jbuf_del.min,
				 cfg->jbuf_del.max);
		if (err)
			goto out;
	}
```


this is something we can look at after Baresip 0.5.11 is released.

**Comment by djhenley** [comment]
Alfred, this sounds perfect. Thanks! We'll start looking in the files you specify and see if we manage to come up with a suggestion that we can look at after the 0.5.11 release.

**Comment by Ola-Palm** [comment]
Alfred, this is perfekt, of course I will help you with testing. Just tell me when, or if there is something else I could do to help you.

**Comment by alfredh** [comment]
hi @djhenley do you have any progress regarding this feature ?

or do you want me to help with any code ?

**Comment by djhenley** [comment]
Hello Alfredh!
Sadly, I have no working code or any other positive progress regarding this feature, we are struggeling a bit/get stuck when trying to achieve something, so yes, I think we will need a little help from you if possible. Thanks a lot for asking!

**Comment by alfredh** [comment]
I added a new function `stream_jbuf_reset` to reset the jitter-buffer on the fly.

in audio.c you can try to add this sample code:

```c
static bool ebuacip_handler(const char *name, const char *value, void *arg)
{
	struct audio *au = arg;
	struct aurx *rx = &au->rx;
	struct pl type, val;

	if (0 == re_regex(value, str_len(value),
			  "jbdef [0-9]+ [^ ]+ [0-9]+", NULL, &type, &val)) {

		if (0 == pl_strcasecmp(&type, "fixed")) {

			uint32_t frames = pl_u32(&val) / rx->ptime;

			stream_jbuf_reset(au->strm, 1, frames);
		}
	}

	return false;
}
```

which is called from audio_sdp_attr_decode:

```
	sdp_media_rattr_apply(stream_sdpmedia(a->strm), "ebuacip",
			      ebuacip_handler, a);
```

currently I used 1 for the jbuf min value. you can play around with these (min/max)
and see which ones work best.


Alfred

**Comment by djhenley** [comment]
Alfred, super, thanks for this. I'll try this out asap.

**Comment by djhenley** [comment]
Hi,
Almost perfect.

1. Yes, now the incoming suggested jitter buffer setting (ebuacip) is being used - very well done!!

2. This value is on the other hand not sent in the following 200 answer SDP from Baresip, here the values from the config file is being sent instead of the suggested/new ones.

3. This results in the following at the moment:
* Baresip is using the correct jitter buffer setting
* The other part (the caller) is forced to use whatever setting is in the baresip config file as this codec follows the ebuacip parameters that is in the answer from Baresip.

**This seems to be very easily achieved and we will have a working suggestion tomorrow when we have some more time to work on it.**

Then we also will look closer on the min value that is 1 at the moment (probably our suggestion will be to set this to _max -1_ when a fixed jitter buffer is being suggested, _1_ otherwise.

**Comment by Ola-Palm** [comment]
Hello, this is  untested code, but something like this would perhaps work? 

`static bool ebuacip_handler(const char *name, const char *value, void *arg)
{
	struct audio *au = arg;
	struct aurx *rx = &au->rx;
	struct autx *tx = &au->tx;
	struct pl type, val;
	int err;
	uint32_t frames;

	if (0 == re_regex(value, str_len(value),
					  "jbdef [0-9]+ [^ ]+ [0-9]+", NULL, &type, &val))
	{
		frames = pl_u32(&val) / rx->ptime;
		if (0 == pl_strcasecmp(&type, "fixed"))
		{	// fixed jb, set to frames -1 as min and frames as max.
			stream_jbuf_reset(au->strm, frames - 1, frames);
			// update tx ebuacip section
			err |= sdp_media_set_lattr(sdp, true, "ebuacip", "jbdef %i fixed 								%d", 0, frames);
		}
		if (0 == pl_strcasecmp(&type, "auto"))
		{
			stream_jbuf_reset(au->strm, 1, frames);
			// update tx ebuacip section
			err |= sdp_media_set_lattr(sdp, true, "ebuacip", "jbdef %i 
										auto %d-%d", 0, 1, frames);
		}
	}
	return false;
}

`

**Comment by Ola-Palm** [comment]
We now have done some tests and find the solution below working best. 
If we get an invite with EBUACIP params we erase our own EBUACIP params in our answer.
This because we don't want the peer to change the settings suggested .

The only thing that is not solved with this solution:
- when jb auto is suggested, we currently don't know the max value. In our solution we set max to 2 times min value, in our use case this is absolutely not a show stopper.


static bool ebuacip_handler(const char *name, const char *value, void *arg)
{
	struct sdp_media *sdp;
	struct audio *au = arg;
	struct aurx *rx = &au->rx;
	struct pl type, val;
	uint32_t frames;

	if (0 == re_regex(value, str_len(value), "jbdef [0-9]+ [^ ]+ [0-9]+", NULL, &type, &val))
	{
		sdp = stream_sdpmedia(au->strm);
		frames = pl_u32(&val) / rx->ptime;
		if (0 == pl_strcasecmp(&type, "fixed"))
		{
                        // fixed jb, set to frames -1 as min and frames as max.
			stream_jbuf_reset(au->strm, frames - 1, frames);
		}
		else if (0 == pl_strcasecmp(&type, "auto"))
		{
			// currently we dont know the max value from an invite that has jb auto set. until we do, we double the min value and set as max.
			stream_jbuf_reset(au->strm, frames, frames*2);
		}
	}
	sdp_media_del_lattr(sdp,"ebuacip");
	return false;
}

**Comment by djhenley** [comment]
Hi,
We have now made a pull request with an adjusted proposal.

**Comment by alfredh** [comment]
thanks, is the PR from Ola Palm or from djhenley :)

in any case I will merge it to master ..

**Comment by djhenley** [comment]
Hi Alfred,
The pull request is from Ola-Palm, we have just been cooperating on it and been testing it together.
Also, both of us totally agree on your minor comments in the PR, and we will adjust as soon as we find a little time for it:

1. On line 1084: check if rx->ptime is zero, to avoid potential division by zero errors.
2. On line 1091: check that frames is 1 or more, to avoid min frames wrapping around
3. ebuacip_handler should be protected by the ebuacip config option

Do you want the above to be adjusted before merge or will the above adjustments be a separate/new PR asap?
