### ISSUE TITLE
REFER ua event?

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#521]
When baresip ua receives REFER request from the other party of the call, I don't see a ua event being generated so that the ua receiving the REFER could decide whether to accept of reject it.  Instead the ua  automatically accepts the REFER with 202 response and generates INVITE based on it.

This seems dangerous to me.  Is there any means to allow the ua receiving REFER to ask the user what to do with the REFER?

**Comment by juha-h** [comment]
Before asking of confirmation is supported, it should be possible to remove REFER from uag_allowed_methods() and use null as refer handler in sipsess_connect() call.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> you are right, it is currently implemented like that. But there is no
> specific reason for it, we can easily change the behaviour.
> 
> the code in question is here in ua.c:
> 
> ```c
> 	case CALL_EVENT_TRANSFER:
...
> ```
> 
> one solution can be to move this block out of libbaresip.a, to menu.so
> or app.

Yes, app (menu.so is app) would be the right place so that app can act on
the event.

And we would need to have an acc param to tell if REFER is advertised at
all, since if the app decides not to support call transfer, it does
not make sense to let the other party think that is supported because
REFER appears in Allow header.

**Comment by juha-h** [comment]
Currently API does not have this call:
```
		err = ua_call_alloc(&call2, ua, VIDMODE_ON, NULL, call,
				    call_localuri(call), true);
```
Perhaps should be added to API?  Or would it be better to leave the call
in 'case CALL_EVENT_TRANSFER' and then give call2 as arg to the ua_event?

This one does not exist in API either:
```
(void)call_notify_sipfrag(call, 500, "Call Error");
```

**Comment by alfredh** [comment]
thanks @juha-h 

just a note about timing; this work will be merged to master after 0.5.11 is released.

**Comment by alfredh** [comment]
I think we first need to decide if the `call_transfer=yes|no` config option
should be global, or per SIP Account.

perhaps "Call Transfer" is a better and more descriptive term than "refer".
Refer is very SIP specific.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I think we first need to decide if the `call_transfer=yes|no` config option
> should be global, or per SIP Account.

I my opinion, per SIP account.  Sometimes I need transfer and sometimes
I want to be protected from it.

> perhaps "Call Transfer" is a better and more descriptive term than "refer".
> Refer is very SIP specific.

So, the account param would be called ;call_tansfer with "yes" and "no"
as possible values?

**Comment by juha-h** [comment]
I renamed account param to ;call_transfer and added account_call_transfer() and account_set_call_transfer() functions plus test case.

Now it should be possible to turn off call transfer. Next step would be to add the ua event, but would need guidance on it.

**Comment by alfredh** [comment]
can you create a PR from your branch, so I can review it and comment on it ?

**Comment by juha-h** [comment]
I'll close this one and open a new one on handling of CALL_EVENT_TRANSFER in application (menu) module.
