### ISSUE TITLE
Streaming received video stream to third party sites.

### ISSUE THREAD

**Issue by alishir** [alfredh/baresip#523]
Hi @alfredh,
Is it possible to stream received video stream to third party sites such as youtube?

Cheers,
Ali

**Comment by alfredh** [comment]
no, this is not supported.

the `avformat` module supports reading a video stream from file or network.


Alfred

**Comment by alishir** [comment]
Thanks, would you please specify the format of `video_src` setting in config file in order to reading video stream from file on network?

Also I have a capture card that shipped with embedded H.264 encoder, is it possible to read video stream from embedded encoder in order to reduce cpu usage?

Cheers,
Ali

**Comment by alfredh** [comment]
an example can be found here:

http://www.creytiv.com/doxygen/baresip-dox/html/group__avformat.html

the device parameter takes the same format as libavformat.

```
 video_source            avformat,/tmp/testfile.mp4
 video_source            avformat,rtsp://example.com/media.mp4
```

for using the H.264 encoder found in webcams, try the `v4l2_codec` module :)


Alfred

**Comment by alishir** [comment]
Hi @alfredh,

Thanks, this is a great feature.
I read `v4l2_codec` documentation, but I could not find sample configuration, is the following config ok?
```
video_source                   v4l2_codec,/dev/video1
```

Also is it possible to use `avformat` module with `video_display`? I want to stream received video to third party site.

And I found that ffmpeg could use hardware accelerated codecs such as h264_vaapi, is there any plan to use hardware accelerated codecs in baresip?

Cheers,
Ali

**Comment by alfredh** [comment]
this is a lot of questions :) with many different topics...

Please lets try to keep the Issue tracker to report defects and bugs.

**Comment by alishir** [comment]
I'm sorry, I think I could ask my questions here.
