### ISSUE TITLE
H.265 codec doesn't utilize available bandwidth.

### ISSUE THREAD

**Issue by alishir** [alfredh/baresip#525]
Hi @alfredh,

I installed x265, ffmpeg and baresip from source. I enabled `module h265.so` in config file and changed the `video_bitrate` to `5120000`. I also changed the `video_size` to `1920x1080` and `video_fps` to `60`.
But when I call peer baresip with similar settings the maximum bandwidth usage is below 1Mb/s. I also should mentioned that the only enabled codec in config file is H.265.

Would you please help me to fix this issue?

Regards,
Ali

**Comment by alfredh** [comment]
the H.265 video codec uses around 50% of the bitrate compared to H.264

do you really want the H.265 codec to use *more* bandwidth ?
perhaps I dont understand the issue.

**Comment by alishir** [comment]
You are right, but there exists lots of artifact in received video, as you can see in image below while the bandwidth usage is below 1Mb/s. I think H.265 could use more bandwidth in order to increase video quality. 


![image](https://user-images.githubusercontent.com/978306/44972909-0f23c300-af70-11e8-839f-8b8d1f2266be.png)

**Comment by alfredh** [comment]
the reason for this could be packet loss on your network.

could you please enable `rtp_stats    yes` in your config,
re-run your test and then include the config file and baresip output here ?

I tested H.265 on Debian Testing and it works well.

libx265 is version 2.8

here is parts of the log:

```
x265 [info]: HEVC encoder version 2.8
x265 [info]: build info [Linux][GCC 7.3.0][64 bit] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
x265 [info]: Main profile, Level-3.1 (Main tier)
x265 [info]: Thread pool created using 4 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 1 / wpp(23 rows)
x265 [info]: Coding QT: max CU size, min CU size : 32 / 16
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : dia / 57 / 0 / 2
x265 [info]: Keyframe min / max / scenecut / bias: 10 / 250 / 0 / 5.00
x265 [info]: Lookahead / bframes / badapt        : 0 / 0 / 0
x265 [info]: b-pyramid / weightp / weightb       : 0 / 0 / 0
x265 [info]: References / ref-limit  cu / depth  : 1 / off / off
x265 [info]: Rate Control / qCompress            : CRF-28.0 / 0.60
x265 [info]: VBV/HRD buffer / max-rate / init    : 819200 / 4096 / 0.900
x265 [info]: tools: rd=2 psy-rd=2.00 early-skip rskip tmvp fast-intra
x265 [info]: tools: strong-intra-smoothing lslices=4 deblock
```

after the call the RTP stats is shown:

```
x265 [info]: frame I:      4, Avg QP:22.84  kb/s: 3774.34 
x265 [info]: frame P:    895, Avg QP:25.06  kb/s: 63.50   
x265 [info]: consecutive B-frames: 100.0% 

encoded 899 frames in 60.42s (14.88 fps), 80.01 kb/s, Avg QP:25.05

video           Transmit:     Receive:
packets:           1139            0
avg. bitrate:     120.2          0.0  (kbit/s)
errors:               0            0
pkt.report:        1134            0
lost:                 0            0
jitter:             3.6          0.0  (ms)
```

average bitrate is around 120 kBit/s which is not too high.

also please verify that your network can handle UDP packets up to 1024 bytes
which is the max limit for video traffic, set in video.c:

```
		struct videnc_param prm;

		prm.bitrate = v->cfg.bitrate;
		prm.pktsize = 1024;
		prm.fps     = get_fps(v);
		prm.max_fs  = -1;
```

**Comment by alishir** [comment]
Hi @alfredh,

Thanks for you detailed comment. I run both caller and callee on the same machine.
Here is the caller and callee config file:

[caller_conf.txt](https://github.com/alfredh/baresip/files/2364096/caller_conf.txt)
[callee_conf.txt](https://github.com/alfredh/baresip/files/2364097/callee_conf.txt)

And here is the output of caller and callee:

[caller.log](https://github.com/alfredh/baresip/files/2364093/caller.log)
[callee.log](https://github.com/alfredh/baresip/files/2364094/callee.log)

Surprisingly there exist packet loss, but I'm running both caller and callee on same machine. 
Also I should note that the CPU usage is about 180% on a dual core CPU, and I'm using x265 in ABR mode.
```
video           Transmit:     Receive:
packets:          73723        18908
avg. bitrate:    7036.7       1777.4  (kbit/s)
errors:               0            0
pkt.report:       70748        18074
lost:              4770            0
jitter:             0.5          0.6  (ms)
```

Cheers,
Ali

**Comment by alfredh** [comment]
it looks like the encoder is using too much CPU.

you can try to reduce the video resolution and/or framerate, until the
picture becomes good quality.

there are no warnings for high cpu usage .. most likely the packets
are lost inside the software/kernel due to the high CPU usage :)

**Comment by alishir** [comment]
Thanks for you reply.

Do you know how I can find where the packet lost occur?
Also is it possible to use hevc_vaapi to offload encoding to GPU?

**Comment by alfredh** [comment]
can you try the vidloop command with different options and see how fast you can
get it ?

```
/vidloop h265
```

and look at the summary...


HW accellerated H.265 is not supported, but it is something that we should
perhaps consider to implement. Different options include hevc_vaapi
and video toolbox (OSX). We can add this item to the Wiki Roadmap page.

**Comment by alfredh** [comment]
hi @alishir 

did you have any luck with my suggestions ?

keep in mind that H.265 encoder is using around 2x computing power compared with H.264

I think it could be a good idea to test different resolutions and framerates,
start with small values and increase it until you get frame loss / artifacts.

for example:

1. 320 x 240 @ 15 fps
2. 640 x 480 @ 15 fps
3. 720 x 640 @ 15 fps
4. 1024 x 720 @ 15 fps

etc ...

**Comment by alishir** [comment]
Hi @alfredh 

Sorry for late reply and thanks for you comments.

I tested `/vidloop h265` with different resolutions. In resolutions below `1920x1080` all thing is good, but in `1920x1080@30fps` the frame rate reduces from 30 to 15, and I got to warnings that indicates long async blocking. Here is the summary:

```
/vidloop h265
Enable video-loop on v4l2,/dev/video0: 1920 x 1080
vidloop: open video display (x11.nil)
vidloop: enabled encoder H265 (30.00 fps, 500000 bit/s)
vidloop: enabled decoder H265
Enabled codec: H265
vidloop: v4l2,/dev/video0: open video source: 1920 x 1080 at 30.00 fps
v4l2: /dev/video0: found valid V4L2 device (1920 x 1080) pixfmt=YUYV
v4l2: Current input: "Camera 1"
v4l2: current framerate is 30.00 fps
main: long async blocking: 102>100 ms (h=0x7fa8a4b5830e arg=0x55e23b2ccb60)
vidloop: NOTE: pixel-format conversion needed: yuyv422  -->  yuv420p
x265 [info]: HEVC encoder version 2.8
x265 [info]: build info [Linux][GCC 7.3.0][64 bit] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2
x265 [info]: Main profile, Level-4 (Main tier)
x265 [info]: Thread pool created using 2 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 1 / wpp(34 rows)
x265 [info]: Coding QT: max CU size, min CU size : 32 / 16
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : dia / 57 / 0 / 2
x265 [info]: Keyframe min / max / scenecut / bias: 25 / 250 / 0 / 5.00
x265 [info]: Lookahead / bframes / badapt        : 0 / 0 / 0
x265 [info]: b-pyramid / weightp / weightb       : 0 / 0 / 0
x265 [info]: References / ref-limit  cu / depth  : 1 / off / off
x265 [info]: Rate Control / qCompress            : CRF-28.0 / 0.60
x265 [info]: VBV/HRD buffer / max-rate / init    : 33333 / 500 / 0.900
x265 [info]: tools: rd=2 psy-rd=2.00 early-skip rskip tmvp fast-intra
x265 [info]: tools: strong-intra-smoothing lslices=6 deblock
x11: shared memory enabled
tmr: long async blocking: 233>100 ms (h=0x7fa8a0aa15d0 arg=0x55e23b2f6cb0)8 kbit/s       
tmr: long async blocking: 188>100 ms (h=0x7fa8a0aa15d0 arg=0x55e23b2f6cb0) kbit/s        
terminated by signal 155] [H265]  fmt=yuv420p  intra=6  EFPS=18.0      401 kbit/s       
ua: stop all (forced=0)
~~~~~ Videoloop summary: ~~~~~
* Source
  module      v4l2
  resolution  1920 x 1080 (actual 1920 x 1080)
  pixformat   yuyv422
  frames      1502
  framerate   30.00 fps  (avg 18.53 fps)
  duration    81.001 sec  (real 81.259 sec)

* Vidconv
  pixformat   yuv420p

* Encoder
  module      H265
  bitrate     500000 bit/s (avg 534523.5 bit/s)
  packets     4420     (avg 54.5 pkt/s)
  duration    80.935 sec

* Decoder
  module      H265
  key-frames  7

* Display
  module      x11
  resolution  1920 x 1080
  fullscreen  Yes
  frames      1501


x265 [info]: frame I:      7, Avg QP:29.83  kb/s: 18488.33
x265 [info]: frame P:   1495, Avg QP:33.49  kb/s: 778.53  
x265 [info]: consecutive B-frames: 100.0% 

encoded 1502 frames in 81.30s (18.48 fps), 861.07 kb/s, Avg QP:33.47

```

**Comment by alfredh** [comment]
I see that you are using the x11 module for video display. In my experience the
sdl2.so module is much faster than x11.so -- perhaps you can try it ?

some time is also spent inside the vidconv function. is there any way you can
force your camera to use YUV420P pixel format, to avoid the conversion ?

another topic is the x265 encoder supports all color depths (8,10,12 bits)
while baresip is only using 8 bit. perhaps it could be worth testing if recompiling
x265 only with 8-bit affects performance ?

**Comment by alfredh** [comment]
hi @alishir did you have time to test my ideas ?

if nothing helps, I am afraid your solution is to buy a more powerful PC ... :)

**Comment by alishir** [comment]
Hi @alfred,
I received an other PC, I didn't configure it yet, I'm going to configure
it this weekend and test your ideas.

Cheers,
Ali

**Comment by alfredh** [comment]
please try to convert a mediafile to HEVC using ffmpeg on your machine.
if this takes longer time than the duration of the mediafile, it cannot run in real-time
on your machine.

please understand that H.265 is around 2 times as computational intensive
compared to H.264 and that it might be too much for some PCs.

I dont regard this issue as a "bug" in baresip. Hope you understand.


Alfred

**Comment by alishir** [comment]
Thanks for your useful comment. I checked the CPU model in this list
http://x265.ru/en/x265-hd-benchmark/ and found that my CPU doesn't have
enough processing power for encoding H.265 in real time.

You are completely right, this is not a bug in baresip, and thanks again
for your useful comments.
