### ISSUE TITLE
gtk module compile error on OpenBSD 5.7

### ISSUE THREAD

**Issue by alfredh** [alfredh/baresip#53]
building Baresip on OpenBSD 5.7 fails in gtk.so module:

```
modules/gtk/gtk_mod.c: In function 'notify_incoming_call':
modules/gtk/gtk_mod.c:279: warning: implicit declaration of function 'g_notification_set_priority'
modules/gtk/gtk_mod.c:279: warning: nested extern declaration of 'g_notification_set_priority'
modules/gtk/gtk_mod.c:280: error: 'G_NOTIFICATION_PRIORITY_URGENT' undeclared (first use in this function)
modules/gtk/gtk_mod.c:280: error: (Each undeclared identifier is reported only once
modules/gtk/gtk_mod.c:280: error: for each function it appears in.)
modules/gtk/gtk_mod.c: In function 'gtk_thread':
modules/gtk/gtk_mod.c:591: warning: declaration of 'error' shadows a global declaration
include/baresip.h:387: warning: shadowed declaration is here
gmake: *** [build-x86_64/modules/gtk/gtk_mod.o] Error 1

```

@clehner could you have a look plz ? is the usage of
G_NOTIFICATION_PRIORITY_URGENT a portable API between all libgtk
implementations? can we avoid using this api, or using another portable api?

**Comment by clehner** [comment]
According to `/usr/include/glib-2.0/gio/gnotification.h`, g_notification_set_priority was added in GLib 2.42. I'm not too familiar with how OpenBSD does packaging/ports. If it carries an older version of GLib, perhaps a macro could be used to pick g_notification_set_urgent instead (which was deprecated in 2.42 in favor of g_notification_set_priority.

**Comment by alfredh** [comment]
hmm, tried to fix it but now get an error on linux  :)

looks like OpenBSD is using GTK 2.24

**Comment by clehner** [comment]
What version of GLib (or GIO)? That is where GNotification is from. Perhaps gio-2.0 should be added to the pkgconfig command. Also, G_NOTIFICATION_PRIORITY_URGENT is an enum.

**Comment by clehner** [comment]
My mistake, the version check macro was wrong. Try `GLIB_CHECK_VERSION(2,42,0)`

**Comment by alfredh** [comment]
ok! will try that soon

**Comment by alfredh** [comment]
fixed in commit 52d1c338fa429ca4a37c0737190d1e6099af37a9

thanks @clehner !

**Comment by clehner** [comment]
Great!

**Comment by sebd77** [comment]
Hi! I do have a very similar issue over Centos6. I could install properly re-0.4.15 and rem-0.4.7, however when I try to install baresip-0.4.18, the make returns the following error:
