### ISSUE TITLE
cannot call Reguest-URI that has parameters

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#532]
When I try to place a call e.g. to sip:foo@bar;param=value, ;param=value is stripped from the Request-URI and call goes to sip:foo@bar.  Looks like stripping happens in src/call.c call_connect() function:
````
/* if the peer-address is a full SIP address then we need
	 * to parse it and extract the SIP uri part.
	 */
	if (0 == sip_addr_decode(&addr, paddr)) {
		err = pl_strdup(&call->peer_uri, &addr.auri);
	}
````
According to RFC 3261 Request-URI can contain parameters:
````
Request-Line   =  Method SP Request-URI SP SIP-Version CRLF
Request-URI    =  SIP-URI / SIPS-URI / absoluteURI
SIP-URI            =  "sip:" [ userinfo ] hostport uri-parameters [ headers ]
uri-parameters  =  *( ";" uri-parameter)
````

**Comment by alfredh** [comment]
thanks for the report. we recently made some changes in that code.

I will investigate and see if we can make a proper fix.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> thanks for the report. we recently made some changes in that code.
> 
> I will investigate and see if we can make a proper fix.

API has function:
````
int  ua_connect(struct ua *ua, struct call **callp,
                const char *from_uri, const char *uri,
                const char *params, enum vidmode vmode);
````
I'm not sure that params param is for.  Would it be cleaner to have like
this:
````
int  ua_connect(struct ua *ua, struct call **callp,
                const char *from_uri, const char *request_uri,
                enum vidmode vmode);
````
since Request-URI can have parameters?

**Comment by alfredh** [comment]
this bug was introduced in commit dd2822e61494e72ce329481592112308687d0c8c

let me have a look and see if we can fix it properly.

**Comment by cspiel1** [comment]
Dear Alfred,
In my opinion this are two faults. We need both commits. sip_addr_decode has to work for addresses with and without angle brackets. And in both cases the uri-parameters should be part of addr->auri. Which is later decoded by uri_decode into an uri structure. And finally the parameters should be in uri->params, right?

regards, chris.

**Comment by juha-h** [comment]
Christian Spielberger writes:

> In my opinion this are two faults. We need both
> commits. sip_addr_decode has to work for addresses with and without
> angle brackets. And in both cases the uri-parameters should be part of
> addr->auri. Which is later decoded by uri_decode into an uri
> structure. And finally the parameters should be in uri->params, right?

I don't care about the internal functions as long as the API function
ua_connect() accepts as uri param value anything that according to
RFC3261 is a valid request uri.

**Comment by alfredh** [comment]
I am currently looking into this.

I think we should first define a list of valid URI types that we can send
to ua_connect.

for example:

```
sip:user
sip:user@example.com
sip:user@example.com;param=value
"User" <sip:user@example.com>
```

A raw uri can be sent straight through, however if the string is a
SIP Address (with angle brackets) the string has to be parsed/decoded
and built up again.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I think we should first define a list of valid URI types that we can send
> to ua_connect.
> 
> for example:
> 
> ```
> sip:user
> sip:user@example.com
> sip:user@example.com;param=value
> "User" <sip:user@example.com>
> ```
> 
> A raw uri can be sent straight through, however if the string is a
> SIP Address (with angle brackets) the string has to be parsed/decoded
> and built up again.

I my opinion, ua_connect should only accept a valid Request-URI.  If
application wants to call a name-addr, then there could be a utility
function, perhaps in re, that strips SIP-URI from name-addr.  It is not
a good idea to overload functions with lots of stuff, i.e., is it better
that one function does one thing only.

**Comment by alfredh** [comment]
thanks for your opinions, I agree with you and think we should go that way.

will push some code soon that addresses this.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> will push some code soon that addresses this.

Thanks, but there is no hurry!

**Comment by alfredh** [comment]
please have a look at this branch:

https://github.com/alfredh/baresip/tree/ua_connect_uri

based on discussions with Juha I have changed ua_connect to only accept SIP uri.

A different function `ua_uri_complete` was added to be used by the application.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> please have a look at this branch:
> 
> https://github.com/alfredh/baresip/tree/ua_connect_uri

> based on discussions with Juha I have changed ua_connect to only
> accept SIP uri.

I'll give the branch a try soon, but would request_uri be better name
than to_uri for the param in ua_connect?  To me to_uri associates with
To header.

**Comment by alfredh** [comment]
thanks for review and testing!

open issue is that ua_connect appends the local uri parameters,
for example ";transport=tcp". this code is here:

```
	/* Append any optional URI parameters */
	err |= mbuf_write_pl(dialbuf, &ua->acc->luri.params);
```

is this still wanted/intended ?

it can lead to problems for example the transport param is appended twice:

Dial sip:target@domain.com;transport=tcp

`INVITE sip:target@domain.com;transport=tcp;transport=tls SIP/2.0`

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> open issue is that ua_connect appends the local uri parameters,
> for example ";transport=tcp". this code is here:
> 
> ```
> 	/* Append any optional URI parameters */
> 	err |= mbuf_write_pl(dialbuf, &ua->acc->luri.params);
> ```
> 
> is this still wanted/intended ?

In my opinion, it should not be done.  Request-URI contains what user
specifies as target of the request.  If there is an outbound proxy
defined, then the request is sent accordingly without touching
Request-URI.

**Comment by juha-h** [comment]
Looks like URI param addition is gone now.  Please merge.  I'm a bit confused with so many things going on at the same time.

**Comment by alfredh** [comment]
thanks for review and testing.

most of the fixed should be in master branch now:

could you test this commit 69714e02d500329e0acb8b411ff890d380d9dc83 ?


there are also extra fixes in the branch, but they are not essential.
for example the branch code will not work for call transfer and dialing
from contacts, as the string is a SIP address and the call_connect function
now expects a SIP uri.

**Comment by juha-h** [comment]
Thanks for the merge.  I made basic tests (also calling from contacts) and they worked fine.  I'll now close this issue.   Will reopen if problems appear in later tests.
