### ISSUE TITLE
allow handling of CALL_EVENT_TRANSFER event in application

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#538]
User must to be in charge of call transfer requests, which means that CALL_EVENT_TRANSFER event needs to be handled in the application (such as menu module).

**Comment by alfredh** [comment]
hi @juha-h 

I added a new event UA_EVENT_CALL_TRANSFER and moved the
call transfer logic to menu module.

please review the code. if this is what you want, just close the issue.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:
> hi @juha-h 

> I added a new event UA_EVENT_CALL_TRANSFER and moved the
> call transfer logic to menu module.
> 
> please review the code. if this is what you want, just close the
> issue.

Looks good.  I already got incoming transfer working in my Android app.
