### ISSUE TITLE
Does baresip support H.263+ codec?

### ISSUE THREAD

**Issue by alishir** [alfredh/baresip#540]
Hi @alfredh 

Is it possible to add H.263+ support? I found that H.263 and H.264 are supported by `avcodec` module, I think we could add H.263+ also.

Regards,
Ali

**Comment by alfredh** [comment]
what is the usecase for H.263+ ?

which video endpoints are you testing with, that supports it ?

IMO we should instead focus on making H.264 better

**Comment by alfredh** [comment]
okay I added it to the Roadmap:

https://github.com/alfredh/baresip/wiki/Roadmap

I dont have access to endpoints with H.263+ so hopefully we can rely
on you for testing/coding :)

BTW: could you try to get a wireshark/ngrep trace of the INVITE with SDP
going from the PCS, showing the codecs etc (incl. H.263+).

**Comment by alfredh** [comment]
lets track it on the roadmap for now (PR is welcome)

lets keep the Issues tracker for defects and minor features.
