### ISSUE TITLE
sip auto register

### ISSUE THREAD

**Issue by cloud-jxy** [alfredh/baresip#545]
Now, I find baresip can't auto register. I use wireshark to capture sip package, I can't find any sip register package in 30 minutes.

**Comment by cloud-jxy** [comment]
In my memory, baresip can auto register. It seems a bug in one update. My barsip version is 0.5.7.

Do I need to invoke register api periodicity?

**Comment by alishir** [comment]
Hi @cloud-jxy,
Would you please post the content of `~/.baresip/account` and `~/.baresip/config`?

**Comment by alfredh** [comment]
hi @cloud-jxy

can you please test with latest version of libre and baresip from GIT ?

please include the debug log output.


Alfred

**Comment by alfredh** [comment]
please re-open if you can provide more information.

**Comment by cloud-jxy** [comment]
I don't use ~/.baresip/account. I  invoke  `ua_alloc` to register acount. The config file is default, auto generated.

`int ua_alloc(struct ua **uap, const char *aor)`

`ua_alloc(NULL, aor);`

aor likes `sip:1122:test1234@192.168.3.192;audio_codecs=pcma`. 1122 is account, test1234 is password.
