### ISSUE TITLE
replace gcc with clang?

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#547]
How about roadmap item about replacing gcc with clang?  Android ndk r18 does not anymore support gcc.

**Comment by alfredh** [comment]
yes, good idea.

this is specific to the baresip-android project.

the generic baresip project will still continue to support
both gcc and clang.


Alfred

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> this is specific to the baresip-android project.

Yes, added android specific roadmap item.
