### ISSUE TITLE
audio_started()?

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#560]
There is API function 
```
bool audio_rxaubuf_started(const struct audio *au)
```
Could there also be API function
```
bool audio_started(const struct audio *au)
```
that would return au->started?

Alternatively, could start_audio(struct audio *a) have test
```
	if (a->started)
		return 0;
```

**Comment by alfredh** [comment]
yes, both are possible.

it is probably best to add the accessor function `audio_started`

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> yes, both are possible.
> 
> it is probably best to add the accessor function `audio_started`

How about https://github.com/alfredh/baresip/pull/563?
