### ISSUE TITLE
Is it possible to develop new module in other languages than C?

### ISSUE THREAD

**Issue by alishir** [alfredh/baresip#562]
Hi all,

I want to develop new module for baresip. As I found baresip modules are shared memory with `.so` extension. Is it possible to develop a module in other languages such as rust and use that module in baresip?

Regards,
Ali

**Comment by alfredh** [comment]
it is possible to implement any language as long as the language has a C interface.

some modules already support other languages than C, for example:

* C++ (dshow, gzrtp)
* Objective C (avcapture, opengl, opengles, qtcapture)

based on other projects that I have been involved with in the past,
we also added a Python interpreter as a module. it was working fine,
but unfortunately this code is not available any more.

a baresip module is just a piece of code that can do anything you want.
the functions module_init and module_close are called during loading and unloading,
and inside those functions you can register any api you want and call any
functions you want.

just be careful that your functions follow the async I/O rules; no blocking function
calls etc. For code that cannot work within the async I/O framework you can create
new threads (pthread) for doing that work.

what kind of application/extension are you planning to write in Rust ?


Alfred

**Comment by alishir** [comment]
I'm going to try second approach. I want to develop simple module to stream streams to youtube or other video hosting site.

**Comment by alfredh** [comment]
@alishir great, does the above posts answer your question ?

then we can close the issue.

**Comment by alishir** [comment]
It is not clear for me how should I register my function and how should I call other baresip functions?
Would you please describe more about function registration and calling other function from other module?

**Comment by alfredh** [comment]
There is some documentation about modules here:

https://github.com/alfredh/baresip/wiki/How-to-add-new-modules


what type of module are you planning to implement ?
i.e. application module, video display module, audio driver etc ?

For example if you are creating a video-display module, take a look
at this example in the sdl2.so module:

https://github.com/alfredh/baresip/blob/master/modules/sdl2/sdl.c#L325

```
	err = vidisp_register(&vid, baresip_vidispl(),
			      "sdl2", alloc, NULL, display, hide);
```

by calling `vidisp_register` you register your video-display with the baresip core.
the callback functions (alloc, display etc) will be called when the module is used.

in general, from a module you can call any function that is publicly
available in the `baresip.h` API. But to make it clean, an audio driver should
only call audio-related functions such as `ausrc_register`. 

does this help ?

**Comment by alishir** [comment]
Thanks for your useful guidance. Yes it helps very much.
