### ISSUE TITLE
alsa error

### ISSUE THREAD

**Issue by timmrogers** [alfredh/baresip#571]
I would like to use baresip as a pager with some Raspberry Pis (3B+).

I have it working - but I am getting alsa errors and poor audio quality. I assume that they are related - but I'm not sure.

Here is what I am setting when I call the extension:

pi@raspager-1:~ $ baresip
baresip v0.5.0 Copyright (C) 2010 - 2016 Alfred E. Heggestad et al.
Local network address:  IPv4=wlan0:172.16.0.96 
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
ausrc: alsa
auplay: alsa
ausrc: aubridge
auplay: aubridge
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
medianat: stun
medianat: turn
medianat: ice
Populated 1 account
Populated 3 contacts
Populated 2 audio codecs
Populated 1 audio filter
Populated 3 video codecs
Populated 0 video filters
baresip is ready.
7961@172.16.0.6: {0/UDP/v4} 200 OK (FPBX-14.0.4.5(13.22.0)) [1 binding]
All 1 useragent registered successfully! (116 ms)
answering call from sip:7403@172.16.0.6 with 200
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: Set audio encoder: PCMU 8000Hz 1ch
aubridge: created device 'dummy'
audio tx pipeline:    aubridge ---> vumeter ---> PCMU
audio rx pipeline:        alsa <--- vumeter <--- PCMU
7961@172.16.0.6: Call established: sip:7403@172.16.0.6
alsa: write: wrote 108 of 160 samples
alsa: write: wrote 90 of 160 samples                                            [===             ]
alsa: write: wrote 32 of 160 samples                                            [===             ]
alsa: write: wrote 95 of 160 samples                                            [                ]
alsa: write: wrote 37 of 160 samples                                            [                ]
alsa: write: wrote 63 of 160 samples                                            [===             ]
alsa: write: wrote 58 of 160 samples                                            [===             ]
alsa: write: wrote 96 of 160 samples                                            [                ]
alsa: write: wrote 38 of 160 samples                                            [                ]
alsa: write: wrote 64 of 160 samples                                            [                ]
alsa: write: wrote 59 of 160 samples                                            [                ]
alsa: write: wrote 96 of 160 samples                                            [                ]
alsa: write: wrote 38 of 160 samples                                            [                ]
alsa: write: wrote 65 of 160 samples                                            [                ]
alsa: write: wrote 60 of 160 samples                                            [                ]
alsa: write: wrote 97 of 160 samples                                            [                ]
alsa: write: wrote 39 of 160 samples                                            [                ]
alsa: write: wrote 66 of 160 samples                                            [                ]
alsa: write: wrote 61 of 160 samples                                            [                ]
alsa: write: wrote 97 of 160 samples                                            [=               ]
alsa: write: wrote 39 of 160 samples                                            [                ]
alsa: write: wrote 68 of 160 samples                                            [                ]
alsa: write: wrote 62 of 160 samples                                            [                ]
alsa: write: wrote 58 of 160 samples                                            [                ]
alsa: write: wrote 96 of 160 samples                                            [                ]
alsa: write: wrote 37 of 160 samples                                            [                ]
alsa: write: wrote 64 of 160 samples                                            [                ]
sip:7403@172.16.0.6: session closed: Connection reset by peer                   [                ]
alsa: write: wrote 59 of 160 samples
sip:7961-0xfb8208@172.16.0.96: Call with sip:7403@172.16.0.6 terminated (duration: 7 secs)
Quit
ua: stop all (forced=0)
Stopping 1 useragent.. 

I know that this is an older version of baresip. If this is a known issue and if a newer version resolves the problem, I'm happy to upgrade. But this version is packaged as a .deb - so if I can resolve it with version 0.5.0, that would be great.

Thanks in advance for any help or suggestions you may have.

**Comment by alfredh** [comment]
the alsa player thread should write a complete block of samples for each iteration.
the alsa device should also be using blocking mode, which is the default.

the warnings in your log says that only X number of samples was written,
that explains the bad audio.

possible reasons:

1. audio samples are coming in too fast from the network -> buffer overrun
2. audio driver is buggy or running too slow -> buffer overrun
3. alsa driver is using non-blocking mode, for some reason

can you try to run a session for about 60 seconds and then press 'A' to see the
audio debug status ? (paste the output here verbatim).

can you try to play a local file to rule out network issues ?
i.e. "/play ring.wav"

**Comment by timmrogers** [comment]
I don't seem to be able to get any audio debugging information. Pressing A
or /audio_debug. I see the option - but neither seems to provide any
output.

Playing a local file does seem to sound much better than the voice or tone
for a page. There seems to be a warning about "long async blocking" though.
I don't know if that is meaningful.

/play ring.wav
playing audio file "ring.wav" ..
alsa: reset: srate=8000, ch=1, num_frames=320, pcmfmt=S16_LE
alsa: playback started (default)
play: player complete.
alsa: stopping playback thread (default)
*tmr: long async blocking: 165>100 ms (h=0x2e104 arg=0x1ef5d58)*
ua: incoming OPTIONS message from sip:7961@172.16.0.6 (172.16.0.6:5060)
call: alloc with params laddr=172.16.0.96, af=AF_INET, use_rtp=0
call: use_video=0
audio: destroyed (started=0)

Can you suggest useful tests for network or audio driver issues, and how I
can confirm that the ALSA driver is using blocking mode? The local file
test suggests that it is, right?

Thanks again for your help.

**Comment by alfredh** [comment]
you can also try the audio-loop with different sampling rates:

```
/auloop 16000 1
/auloop_stop

/auloop 48000 2
/auloop_stop
```

to verify that your sound card is working properly. Try different sampling rates,
perhaps it is just 1 sampling rate that is buggy.

The default packet time (ptime) is 20ms. You can also try to increase this
by setting the `;ptime=40` parameter in account.

The "long async blocking" warning is not critical. You can get rid of it by
building libre in release mode (`make RELEASE=yes`).

BTW: did you post your `~/.baresip/config` file here ?

**Comment by timmrogers** [comment]
Adding ;ptime=40 to the account information seems to have completely solved
the problem. No error message, and dramatically improved sound quality.

What does that setting do?

Here is my config file. I'd be happy for any corrections or suggestions -
but, at this point, it looks like it is working nicely for me. Thank you
very much!

pi@raspager-1:~/.baresip $ more config

#

# baresip configuration

#


#------------------------------------------------------------------------------


# Core

poll_method epoll # poll, select, epoll ..


# SIP

sip_trans_bsize 128

#sip_listen 0.0.0.0:5060

#sip_certificate cert.pem


# Call

call_local_timeout 120

call_max_calls 4


# Audio

#audio_path /usr/share/baresip

audio_player alsa,default

# audio_source alsa,default

audio_source aubridge,dummy

audio_alert alsa,default

audio_srate 8000-48000

audio_channels 1-2

#ausrc_srate 48000

#auplay_srate 48000

#ausrc_channels 0

#auplay_channels 0

# auplay_channels 0


# Video

#video_source v4l2,/dev/video0

#video_display x11,nil

video_size 352x288

video_bitrate 500000

video_fps 25


# AVT - Audio/Video Transport

rtp_tos 184

#rtp_ports 10000-20000

#rtp_bandwidth 512-1024 # [kbit/s]

rtcp_enable yes

rtcp_mux no

jitter_buffer_delay 5-10 # frames

rtp_stats no

#rtp_timeout 60


# Network

#dns_server 10.0.0.1:53

#net_interface wlan0


# BFCP

#bfcp_proto udp


#------------------------------------------------------------------------------

# Modules


# module_path /usr/lib/baresip/modules

module_path /usr/local/lib/baresip/modules


# UI Modules

module stdio.so

#module cons.so

#module evdev.so

#module httpd.so


# Audio codec Modules (in order)

module opus.so

#module silk.so

#module amr.so

#module g7221.so

#module g722.so

#module g726.so

module g711.so

#module gsm.so

#module l16.so

#module speex.so

#module bv32.so

#module mpa.so

#module codec2.so

#module ilbc.so

#module isac.so


# Audio filter Modules (in encoding order)

module vumeter.so

#module sndfile.so

#module speex_aec.so

#module speex_pp.so

#module plc.so


# Audio driver Modules

module alsa.so

#module pulse.so

#module jack.so

#module portaudio.so

module aubridge.so

#module aufile.so


# Video codec Modules (in order)

## module avcodec.so

#module vp8.so

#module vp9.so

#module h265.so


# Video filter Modules (in encoding order)

#module selfview.so

#module snapshot.so

#module swscale.so

#module vidinfo.so


# Video source modules

#module v4l.so

#module v4l2.so

#module v4l2_codec.so

#module avformat.so

#module x11grab.so

#module cairo.so

#module vidbridge.so


# Video display modules

#module directfb.so

#module x11.so

#module sdl2.so

#module fakevideo.so


# Audio/Video source modules

#module rst.so

#module gst1.so

#module gst_video1.so


# Media NAT modules

module stun.so

module turn.so

module ice.so

#module natpmp.so


# Media encryption modules

#module srtp.so

#module dtls_srtp.so

#module zrtp.so



#------------------------------------------------------------------------------

# Temporary Modules (loaded then unloaded)


module_tmp uuid.so

module_tmp account.so



#------------------------------------------------------------------------------

# Application Modules


module_app auloop.so

module_app contact.so

module_app debug_cmd.so

module_app dtmfio.so

#module_app echo.so

#module_app gtk.so

module_app menu.so

#module_app mwi.so

#module_app natbd.so

#module_app presence.so

#module_app syslog.so

module_app vidloop.so



#------------------------------------------------------------------------------

# Module parameters



cons_listen 0.0.0.0:5555


http_listen 0.0.0.0:8000


evdev_device /dev/input/event0


# Speex codec parameters

speex_quality 7 # 0-10

speex_complexity 7 # 0-10

speex_enhancement 0 # 0-1

speex_mode_nb 3 # 1-6

speex_mode_wb 6 # 1-6

speex_vbr 0 # Variable Bit Rate 0-1

speex_vad 0 # Voice Activity Detection 0-1

speex_agc_level 8000


# Opus codec parameters

# opus_bitrate 28000 # 6000-510000

opus_bitrate 500000 # 6000-510000


# Selfview

video_selfview window # {window,pip}

#selfview_size 64x64


# ICE

ice_turn no

ice_debug no

ice_nomination regular # {regular,aggressive}

ice_mode full # {full,lite}


# Menu

#redial_attempts 3 # Num or <inf>

#redial_delay 5 # Delay in seconds

**Comment by alfredh** [comment]
ptime=40 sets the packet time to 40ms

by default it uses 20ms. The amount of samples that baresip writes to the
soundcard is equal to this, same with recording.

Normal music playback applications like mpg123 and mplayer uses much larger
buffers, but for VoIP where low latency matters we use 20ms. Some soundcards
does not handle low buffers very well, so in your case it helped to increase the ptime.
(you can also try larger values such as 60ms 80ms etc.)

I am glad it worked for you :)
