### ISSUE TITLE
Feature Request: 'sip_announced' configuration parameter

### ISSUE THREAD

**Issue by jmillan** [alfredh/baresip#576]
This configuration parameter would specify the accessible IP address in the SIP Contact header field as well as in the SDP 'c=' line.

Useful when baresip is deployed in a server with private IP address (such as AWS) or when running in a container, where the host IP address is not reachable from the outside.

**Comment by alfredh** [comment]
do you want to configure only the IP-address, or both IP-address and port number ?

I assume that in this configuration the baresip runs behind a NAT. Are you not supposed
to use ICE to solve that ?

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> do you want to configure only the IP-address, or both IP-address and
> port number ? 
> 
> I assume that in this configuration the baresip runs behind a NAT. Are
> you not supposed to use ICE to solve that ?

This is what Kamailio has:

  You can specify an advertise address (like ip:port) per listening
  socket - it will be used to build headers such as Via and Record-Route:

    listen=udp:10.10.10.10:5060 advertise  11.11.11.11:5060

  A typical use case for advertise address is when running SIP server
  behind a NAT/Firewall, when the local IP address (to be used for bind)
  is different than the public IP address (to be used for advertising).

I guess Jose was asking something similar.

**Comment by oej** [comment]
Both Kamailio and Asterisk has similar features. The AWS server has some kind of port forwarding into the internal addresses.

**Comment by alfredh** [comment]
AWS has Symmetric NAT with port preserving. This means that if the application
is listening on e.g. 10.0.0.1:2222 the public address will be x.x.x.x:2222,
i.e. the port number is the same.

baresip SIP stack is by default listening to an ephemeral port, that is why I was asking
if you want to have the publicly mapped port number configurable also.

perhaps it is enough to configure public IP-address (no port number) ?

**Comment by alfredh** [comment]
BTW, which SIP server are you using? does it support SIP Outbound ?

**Comment by alfredh** [comment]
This feature can be split into 2 separate tasks:

1. specify public address for SIP sockets
2. specify public address for RTP socket(s)

number 1.) is currently not possible, and would require additional features
in libre SIP stack. I have added the feature to the Roadmap.

number 2.) is actually already possible today by using the STUN module
to detect the public address for RTP. It is also possible to configure
the network on your AWS box with a virtual interface (public) that maps
to your physical interface (private).

so for RTP we have at least some options:

1. use virtual interface on AWS (no code changes needed).

2. use the STUN module to detect public address.

3. create a new module of type `medianat` that takes one configuration
  parameter; the public IP-address

4. same as 3.) but implemented in the core (no module).


@jmillan could you try 1. and 2. and test how it is working ?

**Comment by alfredh** [comment]
lets wait for the new api to arrive in libre. until then, closing the issue.

**Comment by webstean** [comment]
Was the new api ever added to libre? I think this is worth adding to baresip, for all the reasons given above.
