### ISSUE TITLE
transfer support

### ISSUE THREAD

**Issue by cloud-jxy** [alfredh/baresip#577]
README file tells me baresip unattended call transfer. But, I find `call_transfer` function in src code.
Does forget to upgrade README file?

**Comment by alfredh** [comment]
Unattended call transfer is supported.

Attended call transfer is not supported yet, it is on the Roadmap:
https://github.com/alfredh/baresip/wiki/Roadmap

the `call_transfer` function you found is most likely referring to "unattended" call transfer.


Alfred
