### ISSUE TITLE
[Segmentation Fault] Toggle UAs

### ISSUE THREAD

**Issue by junk0xc0de** [alfredh/baresip#59]
pressing space key (Toggle UAs) when no UAs are registered makes a segmentation fault.

**Comment by alfredh** [comment]
which version of baresip are you using, do you have a backtrace from gdb/lldb ?

using latest version from git does not segfault.

**Comment by lmangani** [comment]
Just to confirm what Alfred already stated, this issue cannot be reproduced with latest builds (but it indeed used to be an issue in older versions I tested at random, such as 034ec8f for instance)

Please update, confirm and close if cleared.

**Comment by junk0xc0de** [comment]
oh im so sorry, i have lastest version and an old version too. i was mistakenly using the old version :( good luck.
[i really enjoy your coding style. one of the cleanest source codes i have ever seen]

**Comment by alfredh** [comment]
time for me to make a new release then :)
