### ISSUE TITLE
Audio and video are out of sync

### ISSUE THREAD

**Issue by cloud-jxy** [alfredh/baresip#590]
Audio and video are out of sync, video is always 1 to 2 seconds slower than audio.

**Comment by alfredh** [comment]
hi @cloud-jxy 

do you have a bit more information about your issue ?

The video source is using correct timestamp, but the video display does not use
the timestamps. For playout of audio and video, the timestamps are not used and the
audio and video are just played out as soon as possible. Lip sync is not implemented.

We are planning to improve this, and add a video playout logic that would use
the timestamps to pace the video frames.

Also added to roadmap:

https://github.com/alfredh/baresip/wiki/Roadmap
