### ISSUE TITLE
long async blocking

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#591]
Each time after a call is established, I get to log 1-3 messages about long async blocking:
```
12-04 17:21:32.175 26628 26652 D Baresip : ua event (CALL_INCOMING) sip:test@test.tutpro.com
12-04 17:21:35.723 26628 26653 D Baresip : answering call from sip:test@test.tutpro.com with 200
12-04 17:21:35.724 26628 26653 D Baresip : audio: Set audio decoder: opus 48000Hz 2ch
12-04 17:21:35.730 26628 26653 D Baresip : audio: player started with sample format S16LE
12-04 17:21:35.730 26628 26653 D Baresip : audio: Set audio encoder: opus 48000Hz 2ch
12-04 17:21:35.741 26628 26653 D Baresip : audio: source started with sample format S16LE
12-04 17:21:35.741 26628 26653 D Baresip : audio tx pipeline:    opensles ---> opus
12-04 17:21:35.741 26628 26653 D Baresip : audio rx pipeline:    opensles <--- opus
12-04 17:21:35.928 26628 26652 D Baresip : ua event (CALL_ESTABLISHED) sip:test@test.tutpro.com
12-04 17:21:36.331 26628 26653 D Baresip : main: long async blocking: 402>100 ms (h=0x9bd1650c arg=0xa8e3b660)
12-04 17:21:36.331 26628 26653 D Baresip : stream: incoming rtp for 'audio' established, receiving from 192.168.43.107:30232
12-04 17:21:36.490 26628 26653 D Baresip : main: long async blocking: 144 > 100 ms (h=0x9bd1242c arg=0x9b473490)
12-04 17:21:36.652 26628 26653 D Baresip : main: long async blocking: 136 > 100ms (h=0x9bd1242c arg=0x9b473490)
12-04 17:21:36.672 26628 26652 D Baresip : ua event (CALL_MENC) 2,54b3a3e690b61ed117683cd5
```
Usually only one if zrtp is not enabled.

Could that too have something to do with threads?  In the above, 26652 is the main re thread.  Audio messages and async blocking messages thus come from another thread.

If not thread issue, what else could it be?

**Comment by alfredh** [comment]
the long async blocking warning can be disabled if you build libre in RELEASE mode:

```
$ cd re
$ make RELEASE=yes
```

since baresip and libre is using async I/O (e.g. epoll) for the execution module,
each function call should be fast and it should not block.

the upper limit 100ms is an arbitrary value; in average the execution time
is much lower than that. you need to investigate each call and see where the
blocking delay is coming from.

**Comment by juha-h** [comment]
Thanks.  I was able to figure out, where the delay comes from and how to prevent it.

**Comment by Ola-Palm** [comment]
I’ve also seen these messages on our units, not very often but sometimes.
Where your messages originate from and how did you prevent this?

All the best
/Ola Palm

Skickat från min iPhone

6 dec. 2018 kl. 01:08 skrev juha-h <notifications@github.com<mailto:notifications@github.com>>:


Thanks. I was able to figure out, where the delay comes from and how to prevent it.

**Comment by juha-h** [comment]
Ola-Palm writes:

> I’ve also seen these messages on our units, not very often but sometimes.
> Where your messages originate from and how did you prevent this?

The delay came from ua_event_handler, which called an Android UI
function, which in turn made some audioManager calls that took too long.
I'm now returning from the UI function as soon as possible and do the
long lasting UI things asynchronously.

Put some log messages in your code to find out where it spends too much
time.
