### ISSUE TITLE
H264 : no i-frame

### ISSUE THREAD

**Issue by eric-jswang** [alfredh/baresip#592]
Hi  alfredh,
I made a video call from Antisip (Android) to Linux baresip (x86_x64) + V4L2 (yuv420p), and found that there is not video displayed on Antisip (Android). 

By capturing the RTP frames, it is found that there is only SPS, PPS and p-frames, no any i-frames were sent from Linux baresip. Attached are the antisip config, pcap and h.264 files. Would you kindly guide me where something is wrong ? Thanks !
[data.zip](https://github.com/alfredh/baresip/files/2643386/data.zip)

**Comment by eric-jswang** [comment]
The Linux baresip used is version 0.6,0.

**Comment by alfredh** [comment]
hi @eric-jswang 

many thanks for your report.

would you please be so kind to also include the debug log output from baresip ?
(baresip -v)

does it work if you test baresip to baresip ?

**Comment by eric-jswang** [comment]
Hi, Alfredh ,

In the baresip to baresip testing, the audio/video are played fine both in the caller and callee side. The captured H.264 file is attached (baresip_to_baresip.zip). There is 1 leading i-frame in the baresip-to-baresip connections. 

As to the no-iframe issue in the Antisip (Android), I think I misses some frames during my capturing operation. I will close this no-iframe issue for now. Appreciate for your time.

[baresip_to_baresip.zip](https://github.com/alfredh/baresip/files/2655601/baresip_to_baresip.zip)
