### ISSUE TITLE
access to call's audio codecs

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#594]
I would like to get access to call's audio codecs.  API call call_audio() returns struct audio of the call.  It has rx and tx fields, both of which include a struct aucodec field, that is exposed in the API.  So would it be appropriate if I implement
```
struct aucodec *audio_tx_codec(const struct audio *au)
struct aucodec *audio_rx_codec(const struct audio *au)
```
API functions for that purpose or is there a better alternative?

**Comment by alfredh** [comment]
yes should be fine to expose this in the api.

alternative api:

```
struct aucodec *audio_codec(const struct audio *au, bool tx);
```

this will return the audio codec in use.

**Comment by juha-h** [comment]
OK, I'll work on it.
