### ISSUE TITLE
Error building baresip

### ISSUE THREAD

**Issue by SimonSchnurrbart** [alfredh/baresip#596]
Hi,
I'm getting the following error when using the make command:
`  
LD [M]  g722.so
/usr/bin/ld: /usr/local/lib/libspandsp.a(vector_int.o): relocation R_X86_64_PC32 against symbol vec_dot_prodi16 can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Ungültiger Wert
collect2: error: ld returned 1 exit status
mk/mod.mk:35: recipe for target g722.so failed
make: *** [g722.so] Error 1
`
I followed exactly the install instructions, how can I resolve that issue?
I'm trying it on Ubuntu 18.04

**Comment by juha-h** [comment]
This could be a hint:
```
recompile with -fPIC 
```

**Comment by SimonSchnurrbart** [comment]
I just recompiled libspandsp again and now it works, Thanks!
As for -fPIC, I was not able to use this extension, but since it works anyway now I'm satisfied.
