### ISSUE TITLE
video for android baresip?

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#597]
Any recommendations on where to start in order to add video support for android baresip?  One option might be using WebRTC for sending and receicing video and somehow signal it using baresip.  I think CSipSimple did something like that.

**Comment by juha-h** [comment]
I started to work on this by trying to include opengles module to android libbaresip.a.  I got it done using ndk r18 after I made the following changes to modules/opengles code:
```
diff --git a/modules/opengles/module.mk b/modules/opengles/module.mk
index a9c5300..51524bd 100644
--- a/modules/opengles/module.mk
+++ b/modules/opengles/module.mk
@@ -7,6 +7,8 @@
 MOD		:= opengles
 $(MOD)_SRCS	+= opengles.c
 
+$(MOD)_CFLAGS	+= -DGL_GLEXT_PROTOTYPES
+
 ifeq ($(OS),darwin)
 $(MOD)_SRCS	+= context.m
 
diff --git a/modules/opengles/opengles.c b/modules/opengles/opengles.c
index a9057fb..661849f 100644
--- a/modules/opengles/opengles.c
+++ b/modules/opengles/opengles.c
@@ -7,8 +7,8 @@
 #include <re.h>
 #include <rem.h>
 #include <baresip.h>
-#include <OpenGLES/ES1/gl.h>
-#include <OpenGLES/ES1/glext.h>
+#include <GLES/gl.h>
+#include <GLES/glext.h>
 #include "opengles.h"
```
Is it OK if I commit such a change?

**Comment by alfredh** [comment]
the opengles module was used in a commercial project many years ago,
and it was working on both iOS and Android.

today the module would most likely need some updating to compile and run.

it is probably best to do the changes via a PR, so that we can test that it compiles
on Android and iOS.

**Comment by alfredh** [comment]
the opengles module was fixed in db078bb3b19343c44f3216de9f74afbea58aee8e

thanks to @juha-h for the patch

**Comment by alfredh** [comment]
@juha-h is there anything more to do on this one, or can we close it ?

**Comment by juha-h** [comment]
We can close the issue for now.

**Comment by juha-h** [comment]
As a start, I wrote a JNI function that gets from Android UI activity a Surface as an argument when the surface becomes available for video.  The JNI function then creates ANativeWindow from the surface and then creates from that an EGLSurface.

After that, I have no clue on how to make baresip opengles module to produce video frames on that EGLSurface. Please comment, if you have done it or if you have some ideas on how to proceed.
