### ISSUE TITLE
how to use API functions with 'struct re_printf *pf' argument?

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#599]
I would like to use API function
```
 int call_status(struct re_printf *pf, const struct call *call)
```
to print call status to a char buffer, but didn't find any example in the code on how I should define pf argument to achieve the goal.

struct re_printf has handler field for printing and arg field for the buffer. Do I need to use mbuf_alloc to allocate the buffer or will simple char array do?

An example would be appreciated.

**Comment by alfredh** [comment]
the re_print extensions should be documented here:

http://www.creytiv.com/doxygen/re-dox/html/re__fmt_8h.html#ac0b798cc09138aac907c765dcead0fbc

Example:

```c
char *buf;
re_sdprintf(&buf, "%H", call_status, call);
mem_deref(buf);
```

**Comment by juha-h** [comment]
Thanks.  I ended up using:
```
re_snprintf(&(status_buf[0]), 255, "%H", call_status, call)
```
