### ISSUE TITLE
libbaresip Making an outgoing call.

### ISSUE THREAD

**Issue by Redevice7** [alfredh/baresip#602]
Hi. I use libbaresip, I want to use it to call with raspberry pi. But I can't figure out how to use the function to make a call. For example, when you press the baresip button, it makes a call. And I wanted to use `ua_connect (uag_current (), NULL, NULL, "sip: music@iptel.org", NULL, VIDMODE_OFF); ` but compilation ends in error.

**Comment by alfredh** [comment]
is the problem that you can't compile it ?

can you please include some information about the building, like:

* baresip version
* platform
* how you compile it
* full build log.
* compiler/tools version


Alfred

**Comment by alfredh** [comment]
hi @Redevice7 please re-open if you can provide additional info.
