### ISSUE TITLE
Looking to use OpusMSEncoder with baresip for multichannel audio call

### ISSUE THREAD

**Issue by tonylangley** [alfredh/baresip#604]
Any hints on how I could implement the multistream/multichannel version of the opus codec in baresip so that I can configure number of channels and other parameters relevant to the OpusMSEncoder?

I've tried to find any related info here and elsewhere, but have not found anything.

**Comment by alfredh** [comment]
hi @tonylangley 

what is your use-case for Opus Multistream ?

the opus module supports normal opus, but not opus multistream.
the libopus API is different so we would have to implement it either in
opus.so or opusms.so

I think the FFmpeg project supports Opus Multistream.

is there a large interest for this? if so we could add it to the Roadmap.


Alfred

**Comment by tonylangley** [comment]
Hi @alfredh 

Thanks for having a look at my query.

I'm interested in enabling at least a 4-channel [networked music performance](https://en.wikipedia.org/wiki/Networked_music_performance) bi-directional, session-initiated "call" between compatible parties.

I've had some success with integrating OpusMSEncoder into liblinphone, but that framework is much heavier than what I'm looking for (on a Beagleboard-xM Beaglebone Black, or Beagleboard-X15).

For my use-case I need all 4 channels to be closely sample-locked, i.e. no significant drift between channels 1&2 and 3&4.

I can't determine whether there's large interest in this capability. But I do advocate for more than just stereosonic interactions, particularly when there are many people involved in a conference call and directional audio is important for intelligibility.

I'm guessing that more than just the opus module would need to be updated to enable 4-channels to work end-to-end through baresip - right?

Tony

**Comment by alfredh** [comment]
This sounds like a fun project :)

Personally I have tested channel count of 1 and 2 in baresip, which is working.
The channel count is just an 8-bit unsigned integer, meaning that in theory up
to 255 channels can be supported (is that enough for Frank Zappa and Pink Floyd ?)

For example here is the audio-source parameters:

```c
/** Audio Source parameters */
struct ausrc_prm {
	uint32_t   srate;       /**< Sampling rate in [Hz]      */
	uint8_t    ch;          /**< Number of channels         */
	uint32_t   ptime;       /**< Wanted packet-time in [ms] */
	int        fmt;         /**< Sample format (enum aufmt) */
};
```

Channel mapping is not supported.

For example if your sound-card supports 4 channels, you could just test
the current code and see how it works:

1. audio source with 4 channels (e.g. alsa)
2. audio codec with 4 channels (e.g. opus or L16 hacked)

```c
static struct aucodec opus = {
	.name      = "opus",
	.srate     = 48000,
	.crate     = 48000,
	.ch        = 2,               /* <--- change this to 4 */
	.pch       = 2,
	.fmtp      = fmtp,
	.encupdh   = opus_encode_update,
	.ench      = opus_encode_frm,
	.decupdh   = opus_decode_update,
	.dech      = opus_decode_frm,
	.plch      = opus_decode_pkloss,
};
```


hope this helps!

Alfred

**Comment by alfredh** [comment]
hi @tonylangley 

I have added the multistream info to the roadmap:

https://github.com/alfredh/baresip/wiki/Roadmap

does the previous post answer your question ? if so please be so kind
to close the ticket.

**Comment by tonylangley** [comment]
Hi @alfredh 

Thanks for your reply. Your suggestions of how to get this working have helped :)

I'm currently attempting to integrate an opus_multistream module, ideally so that it can be enabled/disabled via the config. I'm basically copying modules/opus to modules/opus_multistream, refactoring all the opus calls to the multistream variant and updating mk/modules.mk to include this new module. The opus_multistream API requires additional parameters for **streams**, **coupled_streams** and **channel_mappings** in (at least) the **opus_multistream_encoder_create** and **opus_multistream_decoder_create** calls, so I'm not yet sure how best to incorporate these into the config (as they're only needed for multistream i.e. > 2 channels) and make them available to modules/opus_multistream.

Happy to close, as I think I have all I need to try and get this working.

Thanks again :)
