### ISSUE TITLE
Libre with WEBRTC in IOS

### ISSUE THREAD

**Issue by sandeep2244** [alfredh/baresip#607]
how to use libre as SIP gateway in IOS ?

```
I have my own SIP server(Astrisk) credential wich i need to just configure in gateway and call to PSTN number

Webrtc -> SIP gateway(Libre) -> Server(Asterisk) -> PSTN

```
Thank you

**Comment by alfredh** [comment]
hi @sandeep2244 

libre is a protocol library, if you have questions about libre you should
open issues on that project.

this is the baresip project.

it is possible to use baresip as a B2BUA, which is like a SIP Gateway:

https://github.com/alfredh/baresip/wiki/b2bua-module

you might also want to check out the Janus project, which is a WebRTC gateway.


Alfred
