### ISSUE TITLE
audio.c: noisy log line

### ISSUE THREAD

**Issue by jmillan** [alfredh/baresip#609]
Hi there,

I would just like to comment that this line may generate a log line per incoming RTP packet which may be too much. I don't know how important it is to log it though.

https://github.com/alfredh/baresip/blob/6ac4e554663dbc6ee6f47f1f2d8c36fe6c75463d/src/audio.c#L928

**Comment by alfredh** [comment]
which unknown header extension are you receiving ?

I think you should not receive it unless you have advertised it in the SDP.

in any case, changing it from `info` to `debug` is an option

**Comment by jmillan** [comment]
Thanks @alfred,

`A -> middle-box -> B`

It may happen that a middle-box negotiates the header with A but not with B. Then B will receive the header extension and should just ignore it.

**Comment by alfred** [comment]
@jmillan In the future, do you mind double-checking who you're tagging on Github?

**Comment by jmillan** [comment]
@alfred, I'm really sorry. This is the second time. My apologies.
