### ISSUE TITLE
[discontent] bad names

### ISSUE THREAD

**Issue by junk0xc0de** [alfredh/baresip#61]
there are structure and function and variable names that make me confused. i think it would be better if you name them more exact. i can't see any difference between names like "cfg","conf","config","configure" which you used them all inside the project
thanks.

**Comment by alfredh** [comment]
```struct conf``` is from libre, defined in re_conf.h
```struct config``` is baresip core configuration (global) from ~/.baresip/config file

we can rename "struct config" to e.g. "struct baresip_config" or "struct config_core".

if you feel that the source code is very hard to read, I would like you to point out exact places
in the code that are bad and how to improve it.

Perhaps you can suggest improvements via a PR/patch ?


you dont have to rewrite the whole baresip source code, just a couple of places
to illustrate where we can improve :)


Thanks in advance!
