### ISSUE TITLE
(/usr/lib/baresip/modules/stdio.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by thc2018** [alfredh/baresip#613]
1) I have installed re
2) I have installed rem
3) Then I am installing baresip everything looks fine, but after launching baresip it cannot find out any libraries in /usr/bin/baresip

Actually, there is no such directory - /usr/bin/baresip

During installation (sudo make install) I can see that installer tries to copy modules and libraries:
`install -m 0755 baresip /usr/local/bin
install -m 0644 dtmfio.so stun.so turn.so ice.so natbd.so auloop.so presence.so menu.so contact.so vumeter.so mwi.so account.so natpmp.so httpd.so srtp.so uuid.so debug_cmd.so ctrl_tcp.so b2bua.so aubridge.so aufile.so vidloop.so selfview.so vidbridge.so fakevideo.so alsa.so cons.so evdev.so g711.so l16.so oss.so pulse.so stdio.so syslog.so v4l.so v4l2.so v4l2_codec.so omx.so x11.so x11grab.so /usr/local/lib/baresip/modules
install -m 0644 share/* /usr/local/share/baresip`

Full error log:
`baresip v0.6.0 Copyright (C) 2010 - 2018 Alfred E. Heggestad et al.
Local network address:  IPv4=wlan0:192.168.240.22
dl: mod: /usr/lib/baresip/modules/stdio.so (/usr/lib/baresip/modules/stdio.so: cannot open shared object file: No such file or directory)
module stdio.so: No such file or directory
dl: mod: /usr/lib/baresip/modules/g711.so (/usr/lib/baresip/modules/g711.so: cannot open shared object file: No such file or directory)
module g711.so: No such file or directory
dl: mod: /usr/lib/baresip/modules/vumeter.so (/usr/lib/baresip/modules/vumeter.so: cannot open shared object file: No such file or directory)
module vumeter.so: No such file or directory
dl: mod: /usr/lib/baresip/modules/alsa.so (/usr/lib/baresip/modules/alsa.so: cannot open shared object file: No such file or directory)
module alsa.so: No such file or directory
dl: mod: /usr/lib/baresip/modules/avcodec.so (/usr/lib/baresip/modules/avcodec.so: cannot open shared object file: No such file or directory)
module avcodec.so: No such file or directory
dl: mod: /usr/lib/baresip/modules/stun.so (/usr/lib/baresip/modules/stun.so: cannot open shared object file: No such file or directory)
module stun.so: No such file or directory
dl: mod: /usr/lib/baresip/modules/turn.so (/usr/lib/baresip/modules/turn.so: cannot open shared object file: No such file or directory)
module turn.so: No such file or directory
dl: mod: /usr/lib/baresip/modules/ice.so (/usr/lib/baresip/modules/ice.so: cannot open shared object file: No such file or directory)
module ice.so: No such file or directory
dl: mod: /usr/lib/baresip/modules/uuid.so (/usr/lib/baresip/modules/uuid.so: cannot open shared object file: No such file or directory)
module uuid.so: No such file or directory
dl: mod: /usr/lib/baresip/modules/account.so (/usr/lib/baresip/modules/account.so: cannot open shared object file: No such file or directory)
module account.so: No such file or directory
dl: mod: /usr/lib/baresip/modules/auloop.so (/usr/lib/baresip/modules/auloop.so: cannot open shared object file: No such file or directory)
module auloop.so: No such file or directory
dl: mod: /usr/lib/baresip/modules/contact.so (/usr/lib/baresip/modules/contact.so: cannot open shared object file: No such file or directory)
module contact.so: No such file or directory
dl: mod: /usr/lib/baresip/modules/debug_cmd.so (/usr/lib/baresip/modules/debug_cmd.so: cannot open shared object file: No such file or directory)
module debug_cmd.so: No such file or directory
dl: mod: /usr/lib/baresip/modules/dtmfio.so (/usr/lib/baresip/modules/dtmfio.so: cannot open shared object file: No such file or directory)
module dtmfio.so: No such file or directory
dl: mod: /usr/lib/baresip/modules/menu.so (/usr/lib/baresip/modules/menu.so: cannot open shared object file: No such file or directory)
module menu.so: No such file or directory
dl: mod: /usr/lib/baresip/modules/vidloop.so (/usr/lib/baresip/modules/vidloop.so: cannot open shared object file: No such file or directory)
module vidloop.so: No such file or directory
Populated 0 audio codecs
Populated 0 audio filters
Populated 0 video codecs
Populated 0 video filters
baresip is ready.`

**Comment by alfredh** [comment]
@thc2018 

can you try to set the correct path to the modules in ~/.baresip/config:

```
module_path            /usr/local/lib/baresip/modules
```


Alfred

**Comment by thc2018** [comment]
Thanks for your answer!

1 error occure:
`dl: mod: /usr/local/lib/baresip/modules/avcodec.so (/usr/local/lib/baresip/modules/avcodec.so: cannot open shared object file: No such file or directory)
module avcodec.so: No such file or directory`

**Comment by alfredh** [comment]
@thc2018 

you need to install libavcodec-dev and then recompile.

or just comment out avcodec.so in the config.

module documentation:

http://www.creytiv.com/doxygen/baresip-dox/html/group__avcodec.html

**Comment by thc2018** [comment]
`sudo apt-get install libavcodec-dev`

& recompile and everything now works fine!
