### ISSUE TITLE
RPI3 - alsa: cannot set sample rate to 8000 Hz (Invalid argument)

### ISSUE THREAD

**Issue by thc2018** [alfredh/baresip#621]
Cannot make outgoing call from Raspberry Pi 3 (Raspbian stretch). Baresip crashes then I am picking up the phone on incoming call (remote SIP client - linphone on Android):

 # baresip
baresip v0.6.0 Copyright (C) 2010 - 2018 Alfred E. Heggestad et al.
Local network address:  IPv4=wlan0:192.168.1.12
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
ausrc: alsa
auplay: alsa
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
medianat: stun
medianat: turn
medianat: ice
Populated 1 account
Populated 3 contacts
Populated 2 audio codecs
Populated 1 audio filter
Populated 3 video codecs
Populated 0 video filters
baresip is ready.
test2000-sip@sip.linphone.org: {0/TCP/v4} 200 Registration successful (Flexisip/1.0.13 (sofia-sip-nta/2.0)) [1 binding]
All 1 useragent registered successfully! (466 ms)
>    testax-sip@sip.linphone.org
call: connecting to 'sip:testax-sip@sip.linphone.org'..
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 180 Ringing (/)

***** I see the incoming call, pick up a phone and baresip crashes ----->

audio: Set audio decoder: PCMU 8000Hz 1ch
audio: player started with sample format S16LE
audio: Set audio encoder: PCMU 8000Hz 1ch
**alsa: cannot set sample rate to 8000 Hz (Invalid argument)
alsa: init failed: err=-22
alsa: could not reset source 'hw:1,0' (Invalid argument)
audio: start_source failed (alsa.hw:1,0): Unknown error -22**
sip:testax-sip@sip.linphone.org: session closed: Unknown error -22
main: long async blocking: 241>100 ms (h=0x76f0dc08 arg=0x1b730d0)

**Comment by alfredh** [comment]
can you try to use a different ALSA device ?

for example:

```
audio_source    alsa,default
audio_player    alsa,default
```

use the ALSA program `arecord` to list audio devices on your system:

```
arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: ALC887-VD Analog [ALC887-VD Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 2: ALC887-VD Alt Analog [ALC887-VD Alt Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: C920 [HD Pro Webcam C920], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

(or arecord -L).

**Comment by Ola-Palm** [comment]
On all our devices we use plughw:device,sub device. So you could try plughw:1,0.

Plughw will do the transcoding if needed.

Skickat från min iPhone

28 dec. 2018 kl. 17:07 skrev Alfred E. Heggestad <notifications@github.com<mailto:notifications@github.com>>:


can you try to use a different ALSA device ?

for example:

audio_source    alsa,default
audio_player    alsa,default


use the ALSA program arecord to list audio devices on your system:

arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: ALC887-VD Analog [ALC887-VD Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 2: ALC887-VD Alt Analog [ALC887-VD Alt Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: C920 [HD Pro Webcam C920], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0


(or arecord -L).

**Comment by alfredh** [comment]
hi @thc2018 did you manage to get it working ?

**Comment by thc2018** [comment]
Sorry for late response.
No, I cannot do anything.
I have USB sound card and Web-Camera microphone:
`$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: U0x93a0x2622 [USB Device 0x93a:0x2622], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
`
I have tried to use it with Web-Camera microphone and get the same error:
` $ baresip
baresip v0.6.0 Copyright (C) 2010 - 2018 Alfred E. Heggestad et al.
Local network address:  IPv4=eth0:192.168.1.2
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
ausrc: alsa
auplay: alsa
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
medianat: stun
medianat: turn
medianat: ice
Populated 1 account
Populated 3 contacts
Populated 2 audio codecs
Populated 1 audio filter
Populated 3 video codecs
Populated 0 video filters
baresip is ready.
test-sip@sip.linphone.org: {0/TCP/v4} 200 Registration successful (Flexisip/1.0.13 (sofia-sip-nta/2.0)) [2 bindings]
All 1 useragent registered successfully! (205 ms)
>   testax-sip@sip.linphone.org
call: connecting to 'sip:testax-sip@sip.linphone.org'..
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 180 Ringing (/)
call: SIP Progress: 110 Push sent (/)
main: long async blocking: 132>100 ms (h=0x76e9bc08 arg=0x123d0d0)
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: player started with sample format S16LE
audio: Set audio encoder: PCMU 8000Hz 1ch
alsa: cannot set sample rate to 8000 Hz (Invalid argument)
alsa: init failed: err=-22
alsa: could not reset source 'hw:1,0' (Invalid argument)
audio: start_source failed (alsa.hw:1,0): Unknown error -22
sip:testax-sip@sip.linphone.org: session closed: Unknown error -22
main: long async blocking: 280>100 ms (h=0x76e9bc08 arg=0x123d0d0)
`
I have tried with USB sound card microphone. The result is the same:
`$ baresip
baresip v0.6.0 Copyright (C) 2010 - 2018 Alfred E. Heggestad et al.
Local network address:  IPv4=eth0:192.168.1.2
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
ausrc: alsa
auplay: alsa
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
medianat: stun
medianat: turn
medianat: ice
Populated 1 account
Populated 3 contacts
Populated 2 audio codecs
Populated 1 audio filter
Populated 3 video codecs
Populated 0 video filters
baresip is ready.
test-sip@sip.linphone.org: {0/TCP/v4} 200 Registration successful (Flexisip/1.0.13 (sofia-sip-nta/2.0)) [2 bindings]
All 1 useragent registered successfully! (215 ms)
>    testax-sip@sip.linphone.org
call: connecting to 'sip:testax-sip@sip.linphone.org'..
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 180 Ringing (/)
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: player started with sample format S16LE
audio: Set audio encoder: PCMU 8000Hz 1ch
alsa: cannot set sample rate to 8000 Hz (Invalid argument)
alsa: init failed: err=-22
alsa: could not reset source 'hw:0,0' (Invalid argument)
audio: start_source failed (alsa.hw:0,0): Unknown error -22
sip:testax-sip@sip.linphone.org: session closed: Unknown error -22
main: long async blocking: 123>100 ms (h=0x76f14c08 arg=0x1a9c9a8)
`
Moreover, the correct output of audio is aviable only thru built-in sound card. If I try to output sound thrue USB card, i get error:
`call: SIP Progress: 100 Trying (/)
call: SIP Progress: 180 Ringing (/)
alsa: cannot set sample rate to 8000 Hz (Invalid argument)
alsa: init failed: err=-22
alsa: could not reset player 'hw:0,0' (Invalid argument)
`
-------------------------------------------------------
Bye the way. It all good with the equipment, becase everything works fine with ekiga SIP client.
But I want to use baresip because it can be controlled thrue terminal

**Comment by thc2018** [comment]
From the box it comes with this settings:
`audio_source    alsa,default
audio_player    alsa,default`

Result:
`call: SIP Progress: 100 Trying (/)
call: SIP Progress: 180 Ringing (/)
alsa: could not open auplay device 'default' (No such file or directory)
audio: Set audio decoder: PCMU 8000Hz 1ch
alsa: could not open auplay device 'default' (No such file or directory)
audio: start_player failed (alsa.default): Unknown error -2
audio: Set audio encoder: PCMU 8000Hz 1ch
alsa: could not open auplay device 'default' (No such file or directory)
audio: start_player failed (alsa.default): Unknown error -2
alsa: cannot set sample rate to 8000 Hz (Invalid argument)
alsa: init failed: err=-22
alsa: could not reset source 'default' (Invalid argument)
audio: start_source failed (alsa.default): Unknown error -22
`

**Comment by alfredh** [comment]
could you please try one of these 2 options:

1. use `audio_source plughw:1,0` as @Ola-Palm suggested

2. force a audio sampling-rate by setting this config option:
 `ausrc_srate            48000`

**Comment by thc2018** [comment]
Works for me:
--------------------------------------------
audio_player            alsa,hw:0,0 #default
audio_source            alsa,hw:1,0 #default
audio_alert             alsa,hw:0,0
audio_srate             8000-48000
audio_channels          1-2
ausrc_srate             48000
auplay_srate            48000
ausrc_channels          1
auplay_channels         2
---------------------------------------------
ausrc_channels  and auplay_channels  are also IMPORTANT!

Now It is showing error, but works:
---------------------------------------------
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 180 Ringing (/)
alsa: cannot set sample rate to 8000 Hz (Invalid argument)
alsa: init failed: err=-22
alsa: could not reset player 'hw:0,0' (Invalid argument)
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: enable auplay resampler: 8000Hz/1ch --> 48000Hz/2ch
audio: player started with sample format S16LE
audio: Set audio encoder: PCMU 8000Hz 1ch
audio: enable ausrc resampler: 8000Hz/1ch <-- 48000Hz/1ch
audio: source started with sample format S16LE
audio tx pipeline:        alsa ---> vumeter ---> PCMU
audio rx pipeline:        alsa <--- vumeter <--- PCMU
-----------------------------------------------

**Comment by thc2018** [comment]
Could you help me once again?
How can I start baresip and making it call to sip account automatically? Using bash or console or python?
I have tried "baresip /call sip@account" but it only starts, show baresip is ready and waiting for d been pressed and sip account entered....

**Comment by alfredh** [comment]
if the original problem was solved, please close the ticket and create a new one.

1. add your SIP account in `~/.baresip/accounts`

2. start baresip

3. press `h` for help

from the terminal you can make it dial out on start:

```
$ baresip -e "/dial sip:test@example.com"
```
