### ISSUE TITLE
sip register fail after I modify re

### ISSUE THREAD

**Issue by cloud-jxy** [alfredh/baresip#622]
I'm worried about list has multithreaded conflict. So, I code a patch of re.

I find baresip sip register fail after using my patch. The sip service don't recevie sip register request.
Baresip occur sip registering log, but not register fail log or register ok log.

This is my patch.
[re_list.diff.zip](https://github.com/alfredh/baresip/files/2714240/re_list.diff.zip)

**Comment by alfredh** [comment]
we are not planning to add lock/mutex to the re `struct list` container.
this has to be done on the level of the owner of the list.

the issues reported here should be reported againt the code in git.
if you make local changes and something stops working, I'm afraid you have
to analyze the code yourself.

if you want to discuss more high-level ideas like this, please use the
mailing list:

http://lists.creytiv.com/mailman/listinfo/re-devel


Alfred
