### ISSUE TITLE
#Retitled# Opus Multistream will not work beyond 4 channels due to a decoder error (JACK module now supports above 4)

### ISSUE THREAD

**Issue by tonylangley** [alfredh/baresip#625]
Hi,

In reference to Issue #604 and thanks to @alfredh for his suggestions, I've been able to add a new module called opus_multistream and set up 3 new entries in the config to support this.

```
# Opus Multistream codec parameters
opus_ms_channels    4   #total channels
opus_ms_streams     2   #number of uncoupled streams (number of mono channels)
opus_ms_c_streams   2   #number of coupled streams (number of channels coupled as stereo pairs)
```

So far I've successfully tested 2 and 4 channel configurations via ALSA and PortAudio. I am now trying to get this to work via Jack.

In the following two files, the maximum channel count is hardcoded (via the jack port count) to 2...

**jack_play.c**
```
struct auplay_st {
	const struct auplay *ap;  /* pointer to base-class (inheritance) */

	struct auplay_prm prm;
	int16_t *sampv;
	size_t sampc;             /* includes number of channels */
	auplay_write_h *wh;
	void *arg;

	jack_client_t *client;
	jack_port_t *portv[2];  /* HARD CODED */
	jack_nframes_t nframes;       /* num frames per port (channel) */
};
```

**jack_src.c**
```
struct ausrc_st {
	const struct ausrc *as;  /* pointer to base-class (inheritance) */

	struct ausrc_prm prm;
	int16_t *sampv;
	size_t sampc;             /* includes number of channels */
	ausrc_read_h *rh;
	void *arg;

	jack_client_t *client;
	jack_port_t *portv[2];  /* HARD CODED */
	jack_nframes_t nframes;       /* num frames per port (channel) */
};
```

Ideally the size of the `portv` array should be configurable by a single channel count parameter, or the size is dynamically set based on the needs of the interconnecting modules.

What do you suggest would be the best way to refactor this to:

1. enable configurable multichannel support via Jack
2. minimise/eliminate conflicting channel counts

**Comment by alfredh** [comment]
this is great stuff @tonylangley !

probably the best thing is to allocate array of `jack_port_t` pointers where
the size is the same as the number of channels from the audio parameters:

```c
/** Audio Source parameters */
struct ausrc_prm {
	uint32_t   srate;       /**< Sampling rate in [Hz]      */
	uint8_t    ch;          /**< Number of channels         */
	uint32_t   ptime;       /**< Wanted packet-time in [ms] */
	int        fmt;         /**< Sample format (enum aufmt) */
};
```

how many channels is realistic ? more than 8?
you can also just increase the capacity to something larger, such as 4 or 8.

since the type of `ch` is uint8_t the maximum number of channels we can
support is 255.

also, please note that the JACK module is converting to/from Float <-> Signed 16-bit.
since baresip now supports different sample formats, it might be worth adding
float to Jack module and eliminate the need for the format conversion.


Alfred

**Comment by tonylangley** [comment]
Thanks @alfredh :)

Here's a patch of what I've done so far...

[baresip-0.6.0-opusMultistream.patch.zip](https://github.com/alfredh/baresip/files/2730239/baresip-0.6.0-opusMultistream.patch.zip)

I've not been able to extend the capabilities beyond 4 channels as there are the following errors in the opus multistream decoder when I attempt 8 channels...
```
opus_multistream: decode error: buffer too small
audio: opus_multistream codec decode 239 bytes: Protocol error
```
4 channels is all I require right now so I've left the maximum (`portv` array size) as 4 in both jack_play.c and jack_src.c files, but I think @sreimers might be interested in more channels ;)

As you'd probably expect, `/auloop 48000 8` works perfectly via JACK with the `portv` array size set to 8.

Thanks also for your suggestion of extending  the JACK module to support Float internally. I can see how this has been done in the Opus module, but (because I'm a bit of a newbie with C programming) I'm not sure how to refactor the source code to make the `fmt` value (`AUFMT_S16LE` or `AUFMT_FLOAT`) available within the `process_handler` function of both jack_play.c and jack_src.c files.

Thanks again for your help.

**Comment by alfredh** [comment]
there are 3 different patches that can be done here:

1. add opus_ms module

2. dynamically allocate ports in jack module

3. increase audio buffer size in core.

I can help out with point 3.

perhaps someone else can help out with point 2. ?

**Comment by alfredh** [comment]
the jack module should now support up to 255 channels.
tested with 1 and 2 channels.

@tonylangley could you please test it with 4 channels ?

**Comment by alfredh** [comment]
@tonylangley 

do you think that your patch is ready for a PR ?
even if it is not working perfectly I would encourage you to submit a PR for it.

in audio.c I have changed the maximum sample size a bit:

```c
enum {
	MAX_SRATE       = 48000,  /* Maximum sample rate in [Hz] */
	MAX_CHANNELS    =     2,  /* Maximum number of channels  */
	MAX_PTIME       =    60,  /* Maximum packet time in [ms] */

	AUDIO_SAMPSZ    = MAX_SRATE * MAX_CHANNELS * MAX_PTIME / 1000,
};
```

lacking a better solution, you can just set MAX_CHANNELS to 4 for now.

**Comment by tonylangley** [comment]
@alfredh Thanks for your updates:)I do think my patch is ready for a PR, so I'm just working out how to actually do that!

I did try originally to submit my patch that way, but had noobie issues! I've been given a bit of help, so I'll incorporate the latest updates you made into my branch and try creating a PR. I'm back at work now, so my time for this is minimal. I hope to be able to get this done in the next 5 days.

**Comment by tonylangley** [comment]
It would be great to be able to set MAX_CHANNELS via the config, but I'm unsure of how to make that work!

**Comment by alfredh** [comment]
it would be better if the buffer size was calculated in run-time, but I dont have
a good solution for this yet.

the challenge is that when decoding the audio frame, we dont know how many
samples we get after the decoding. for example the remote peer might send
with ptime=100ms.

there are 2 ways to do this:

1. allocate a large sample buffer in audio_alloc

2. allocate the buffer for each decoded frame.

the downside of 1.) is that it will allocate a very large buffer, where most of the time
the large part of it will be unused.

**Comment by alfredh** [comment]
the original issue has been addressed, so closing this.

@tonylangley lets continue this work when you submit a PR with opus_ms
