### ISSUE TITLE
GTK: call_window destructor problem? call_timer not destroyed properly, segfaults

### ISSUE THREAD

**Issue by FallenChromium** [alfredh/baresip#630]
Hello! I was testing different versions of baresip, from master to May ones, and looks like this bug is as far as 5.7.0 (I didn't checked even more earlier, but this seems far enough).

**Error logs:**
What I get is infinite
```
(baresip:24624): Gtk-CRITICAL **: 21:18:15.260: IA__gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(baresip:24624): Gtk-CRITICAL **: 21:18:16.260: IA__gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(baresip:24624): Gtk-CRITICAL **: 21:18:16.261: IA__gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed
```
**Problem:**
Besides it's messing up logs, also it bugs next calls timer (and sometimes also calls segfaults when I try to place next call, which is not nice at all)
But, I should describe how to get this:

1. Build baresip with GTK module (i tried debuild and make \CC=clang\RELEASE=1)
2. Launch baresip, load GTK module, connect with account
3. Try to call someone, wait until timer appears (processing\established status)
4. Hangup.
5. You should see this in terminal now

**Where issue is located:**
After commenting out `gtk_label_set_text(win->duration, buf);` in ` call_window_update_duration` inside _modules/gtk/call_window.c_ I don't get such errors. 

**What is the cause?** I think the problem is inside `call_window_destructor` function, as it's happening after window (supposedly) destroyed. Giving that the timer tag inside this function is wrapped in if condition which I can't really understand and race conditions note, I'm quite sure that's the source of the problem. I didn't tried to fix it yet (I'm not really C guy, I can understand it a bit because I use golang), so I really hope it would be fixed soon. Thanks, and good luck!

**Comment by FallenChromium** [comment]
@clehner I'm not really sure if you're still interested, but can you take a look at this please?

**Comment by clehner** [comment]
I'm sorry, I don't think I will be able to fix this.

**Comment by FallenChromium** [comment]
@clehner oh, that's really sad. I thought it's because G_SOURCE_CONTINUE iniside *_timer function which calling update function in a main loop, but I didn't found a way to stop it (isn't main loop stopped when window is closed, huh? Or it's context-independent?)

**Comment by alfredh** [comment]
@FallenChromium I can have a look at this when I get some time.

could you please share the full baresip log and the full gdb backtrace ?

**Comment by FallenChromium** [comment]
Yeah, sure! Sorry for a bit late answer. Interestingly enough, I can't reproduce that when using linphone test SIP server and their test echo account, it's skipping "processing" step and becoming established already. Here's the log: [baresip-crash.log](https://github.com/alfredh/baresip/files/2782904/baresip-crash.log). If that makes any difference, I'm using Asterisk as SIP server.

**Comment by alfredh** [comment]
@FallenChromium I managed to reproduce it locally with OSX and gtk 2.24

the bug happens when you receive Progress and then Established.
The duration timer is created twice in this case.

please re-test with git HEAD or commit 1a294142d2c3fddd225e7639f8988dcece4164d9

the code in question is here (after fix):

```c
void call_window_progress(struct call_window *win)
{
	if (!win)
		return;

	win->duration_timer_tag = g_timeout_add_seconds(1, call_timer, win);
	last_call_win = win;
	call_window_set_status(win, "progress");
}


void call_window_established(struct call_window *win)
{
	if (!win)
		return;

	call_window_update_duration(win);

	if (!win->duration_timer_tag) {
		win->duration_timer_tag = g_timeout_add_seconds(1, call_timer,
								win);
	}

	last_call_win = win;
	call_window_set_status(win, "established");
}
```

**Comment by alfredh** [comment]
@FallenChromium would you please be so kind to test my fix ?

@clehner is this a good fix do you think, or is there a better way ?


Alfred

**Comment by alfredh** [comment]
the issue should now be fixed. would be nice if someone can verify it.
