### ISSUE TITLE
How do I specify (and force use of) a TURN server?

### ISSUE THREAD

**Issue by tonylangley** [alfredh/baresip#632]
I'd like to force that a TURN server is used for the experiments I'm currently running.

Perhaps I don't really understand this whole STUN/TURN/ICE stuff, but from what I've seen elsewhere I believe we should be able to specify (at least) a STUN and TURN server. I've been able to specify a STUN server in the `accounts` config file, but I can't figure out how to specify a TURN server successfully.

This is the format I tried...

```
<sip:user@server.local>;auth_pass=none;regint=0;medianat=ice;stunserver=turn:xirsys_username:xirsys_password@m3.xirsys.com:3478?transport=tcp
```
and...
```
<sip:user@server.local>;auth_pass=none;regint=0;medianat=turn;stunserver=turn:xirsys_username:xirsys_password@m3.xirsys.com:3478?transport=tcp
```

This is a snippet of the console output...
```
account: unknown scheme: turn
ua: sip-stack exit
ua exited -- stopping main runloop
module account.so: Invalid argument
```

I've tried searching here to find the answers but haven't found anything. Any ideas or am I missing something?

**Comment by tonylangley** [comment]
...unless that's what the `ice_turn` parameter in the config is there to do. I'm trying all sorts of combinations, but I've still not got a TURN-relayed connection between 2 clients working.

**Comment by alfredh** [comment]
there are 3 modules related to STUN/TURN/ICE:

1. stun.so -- uses a STUN server to probe the public address (no ICE)
  this can be used against any endpoint.

2. turn.so -- uses a TURN server to create an allocation/mapping (no ICE)
  this can be used against any endpoint.

3. ice.so -- uses ICE stack for connectivity checks, uses STUN and optionally TURN.
  this must be used against a SIP client with ICE enabled.

with ice.so it is currently not possible to "force" the TURN candidate.

I think your best option is to use `turn.so` instead where the RTP media will
always be relayed via the TURN Server.

the format of the STUN/TURN Server is:

`stun:username:password@turn-server.org`

NOTE: STUN is the base protocol for STUN/TURN/ICE. So TURN is also STUN :)

**Comment by tonylangley** [comment]
Thanks for this info @alfredh :)

I have tried using turn.so only with a number of STUN & TURN service providers, but I keep having the same result - The audio seems to be relayed via the SIP Proxy and not the TURN Server as I would have expected.

**Comment by alfredh** [comment]
some SIP proxies (e.g. kamailio with nathelper) will rewrite the SDP and force
the RTP traffic via RTP Proxy. Which SIP proxy or provider are you using ?

the TURN allocation will already give you a public IP-address, so there should
be no need for the SIP-proxy to re-write it.

perhaps you can contact your provider and ask what is going on ?

**Comment by alfredh** [comment]
if the question was answered, I will close this one.

**Comment by tonylangley** [comment]
Thanks for your suggestion @alfredh The issue is unresolved at this stage. I'll try and follow this up with the two out of two providers I've experienced this with. Unfortunately my holidays have come to an end so my time to troubleshoot this is minimal.
