### ISSUE TITLE
make\make deb fails (probably libssl-dev versioning problems)

### ISSUE THREAD

**Issue by FallenChromium** [alfredh/baresip#634]
My env:
Distro:
```
uname -a
Linux xubuntu 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

libssl-dev version: 
```
sudo apt-cache policy libssl-dev
libssl-dev:
  Installed: 1.1.0g-2ubuntu4.3
```

re, rem and baresip are fetched from master as of Jan 11, 10:12 UTC.
The error log: 
```
  LD      baresip
build-x86_64/src/ua.o: In function `add_transp_af':
/home/xubuntu/src/baresip/src/ua.c:1230: undefined reference to `tls_alloc'
/home/xubuntu/src/baresip/src/ua.c:1242: undefined reference to `tls_add_ca'
collect2: error: ld returned 1 exit status
Makefile:204: recipe for target 'baresip' failed
make: *** [baresip] Error 1

```
I tried to use 1.0 version of libssl-dev, but that didn't helped. Any hints about what did I done wrong (2 days ago all was working fine) are appreciated.

**Comment by alfredh** [comment]
it looks like you have compiled libre without TLS support.

can you please try to make a full clean and rebuilt / install
libre, libre, baresip from scratch ?

if you want to check if the build has TLS support you can
use the `make info` command:

```
  USE_OPENSSL:   yes
  USE_OPENSSL_AES:   yes
  USE_OPENSSL_HMAC:  yes
  USE_TLS:       yes
  USE_DTLS:      yes
  USE_DTLS_SRTP: yes
```

**Comment by FallenChromium** [comment]
Yeah, looks like the problem is beyond baresip, it's libre thing. By the way, `USE_TLS:       yes
` showed up when I launched `make info`. All is fine when I build baresip with `make`, but when `make deb` comes in I have to `make deb` libre and librem (because they are listed as apt dependencies inside baresip ./debian folder), and that's the moment when things are screwing up - I'm getting libre without TLS if I'm using `make deb`
Thanks for the cool hint! Still can't solve my timer problem though, I even had to comment out all functions that use it to avoid segfaults... I'm going to close this issue as it's not directly related to baresip.
