### ISSUE TITLE
make call and play wav without alsa

### ISSUE THREAD

**Issue by fourti** [alfredh/baresip#635]
Hi,

I try to implement a "call this number and playback wav-file on connect" feature.
baresip runs on centos 7 vmware VM without any audio hardware.

How can I playback the wav file to the called number?

I registered to sipgate.de and just make d01234

pulseaudio and aufile is laoded

httpd: listening on 127.0.0.1:8000
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
auplay: pulse
ausrc: pulse
ausrc: aufile
Populated 1 account
Populated 3 contacts
Populated 2 audio codecs
Populated 1 audio filter
Populated 0 video codecs
Populated 0 video filters
baresip is ready.

play works
/play busy.wav
playing audio file "busy.wav" ..

**Comment by alfredh** [comment]
@fourti 

you can use `aufile` module or `gst` (Gstreamer) module to use a WAV file as the audio input.
this will be sent in the stream to the remote peer.

```
module  aufile.so
audio_source  aufile,test.wav
```

or

```
module gst1.so
audio_source gst,test.wav
```

The /play command is for local file playback.
