### ISSUE TITLE
200 OK not getting to Baresip

### ISSUE THREAD

**Issue by sbourji** [alfredh/baresip#636]
when Application sends an unregister thru ua the 200 OK not getting back to the ua response_handle from re, even thou re gets the 200 OK for unregister from the far end. Is there a why to send that 200 OK to the application from re?

**Comment by alfredh** [comment]
baresip and libre has no callback handler for when the SIP registration was
successfully un-registered.

the API looks like this:

```c
int sipreg_register(struct sipreg **regp, struct sip *sip, const char *reg_uri,
		    const char *to_uri, const char *from_name,
		    const char *from_uri, uint32_t expires,
		    const char *cuser, const char *routev[], uint32_t routec,
		    int regid, sip_auth_h *authh, void *aarg, bool aref,
		    sip_resp_h *resph, void *arg,
		    const char *params, const char *fmt, ...);
```

the only way to close the sip register object, is with `mem_deref` which is
a syncronous operation.

but it is possible to use the SIP stack exit handler to check when
all SIP registrations are unregistered and all SIP client transactions
are finished:

https://github.com/alfredh/baresip/blob/master/src/ua.c#L91


Alfred

**Comment by sbourji** [comment]
What if you have more than onne registration, I don’t see than how you distinguish between them. 
On a side not should I open the following as a trouble issue?
As it is when you try to re-register because the sip registration is about to expire, the stack send an unregistered followed by a registration, why is it I only trying to let the other end knows that I am still register, and this happened quit when you are in the background and you get an apps renew registration?
Thank you

**Comment by alfredh** [comment]
the SIP register client in libre will send periodic REGISTER requests.

there is no need to re-register, unless you change IP-address. in this cases it is correct
to un-register the old one.

I am sorry but this is the way the libre API is defined and it will not be changed.

**Comment by sbourji** [comment]
By the way, re does get the ok for un-register and does call men_deref, so I don’t think you are going to get anything from the exit handler
