### ISSUE TITLE
jitter buffer

### ISSUE THREAD

**Issue by cloud-jxy** [alfredh/baresip#638]
Baresip jitterbuffer is not an excellent one. It can only handle packet loss, out-of-order, delay arrival, but fails to make video play smoothly and avoid obvious accelerated play and slow play as much as possible.

This is the code of rtp_handler function in stream.c.I've removed some of the code for easy viewing.

```
static void rtp_handler(const struct sa *src, const struct rtp_header *hdr,
            struct mbuf *mb, void *arg)
{

    if (s->jbuf) {

        err = jbuf_put(s->jbuf, hdr, mb);

        if (jbuf_get(s->jbuf, &hdr2, &mb2)) {

            if (!s->jbuf_started)
                return;

            memset(&hdr2, 0, sizeof(hdr2));
        }

        handle_rtp(s, &hdr2, mb2);
    }
    else {
        handle_rtp(s, hdr, mb);
    }
}
```

When rtp_handler doesn't occor because of bad internat, the video displayed can't refresh.

**Comment by alfredh** [comment]
thanks for the input.

I have added the feature to the Roadmap:

https://github.com/alfredh/baresip/wiki/Roadmap

Using timestamps for video playout is something we wanted to do for a long
time. It is a rather complex feature and will take a long time to test and to tune.
