### ISSUE TITLE
avformat MJPEG stream avformat: decode: bad pixel format (13) (yuvj422p)

### ISSUE THREAD

**Issue by daanpape** [alfredh/baresip#639]
Hello,

I'm working a project and I want to take in an MJPEG camera stream and use it as a video input for a SIP call. I have compiled baresip with the VP8 encoder and while this works perfectly with a USB webcam it doesn't work with the avformat input. I'm probably setting up something wrong but I can't find the right documentation. This is my configuration:

```
#
# baresip configuration
#

#------------------------------------------------------------------------------

# Core
poll_method             epoll           # poll, select, epoll ..

# SIP
sip_trans_bsize         128
#sip_listen             0.0.0.0:5060
#sip_certificate        cert.pem

# Audio
audio_player            alsa,default
audio_source            alsa,default
audio_alert             alsa,default
audio_srate             
audio_channels          1-2
#ausrc_srate            48000
#auplay_srate           48000
#ausrc_channels         0
#auplay_channels                0

# Video
video_source            avformat,http://127.0.0.1:8080/?action=stream
#video_display          x11,nil
video_size              352x288
#video_bitrate          262144
#video_fps              10

# AVT - Audio/Video Transport
rtp_tos                 184
#rtp_ports              10000-20000
#rtp_bandwidth          512-1024 # [kbit/s]
rtcp_enable             yes
rtcp_mux                no
jitter_buffer_delay     0-5             # frames
rtp_stats               no

# Network
#dns_server             10.0.0.1:53
#net_interface          eth0.1

# BFCP
#bfcp_proto             udp

#------------------------------------------------------------------------------
# Modules

module_path             /usr/lib/baresip/modules

# UI Modules
module                  stdio.so
#module                 cons.so
#module                 evdev.so
#module                 httpd.so

# Audio codec Modules (in order)
module                  opus.so
#module                 silk.so
#module                 amr.so
#module                 g7221.so
module                  g722.so
#module                 g726.so
#module                 g711.so
#module                 gsm.so
#module                 l16.so
#module                 speex.so
#module                 bv32.so

# Audio filter Modules (in encoding order)
module                  vumeter.so
#module                 sndfile.so
#module                 speex_aec.so
#module                 speex_pp.so
#module                 plc.so

# Audio driver Modules
module                  alsa.so
#module                 portaudio.so

# Video codec Modules (in order)
#module                 avcodec.so
#module                 v4l2_codec.so
module                  vp8.so
module                  vp9.so

# Video filter Modules (in encoding order)
#module                 selfview.so

# Video source modules
#module                 v4l.so
#module                 v4l2.so
module                  avformat.so
#module                 x11grab.so
#module                 cairo.so

# Video display modules
#module                 x11.so
#module                 sdl2.so

# Audio/Video source modules
#module                 rst.so
#module                 gst.so

# Media NAT modules
module                  stun.so
module                  turn.so
module                  ice.so
#module                 natpmp.so

# Media encryption modules
#module                 srtp.so
#module                 dtls_srtp.so


#------------------------------------------------------------------------------
# Temporary Modules (loaded then unloaded)

module_tmp              uuid.so
module_tmp              account.so


#------------------------------------------------------------------------------
# Application Modules

module_app              auloop.so
module_app              contact.so
module_app              menu.so
#module_app             mwi.so
#module_app             natbd.so
#module_app             presence.so
#module_app             syslog.so
#module_app             vidloop.so


#------------------------------------------------------------------------------
# Module parameters


cons_listen             0.0.0.0:5555

http_listen             0.0.0.0:8000

evdev_device            /dev/input/event0

# Speex codec parameters
speex_quality           7 # 0-10
speex_complexity        7 # 0-10
speex_enhancement       0 # 0-1
speex_mode_nb           3 # 1-6
speex_mode_wb           6 # 1-6
speex_vbr               0 # Variable Bit Rate 0-1
speex_vad               0 # Voice Activity Detection 0-1
speex_agc_level         8000

# Opus codec parameters
opus_bitrate            28000 # 6000-510000

# NAT Behavior Discovery
natbd_server            creytiv.com
natbd_interval          600             # in seconds

# Selfview
#video_selfview         window # {window,pip}
#selfview_size          64x64

# ICE
ice_turn                no
ice_debug               no
ice_nomination          regular # {regular,aggressive}
ice_mode                full    # {full,lite}
```

The error message that I'm getting is the following:

`avformat: decode: bad pixel format (13) (yuvj422p)
avformat: decode: bad pixel format (13) (yuvj422p)=0.0/0.0`

Is it possible to give me any pointers. Many thanks in advance!

**Comment by alfredh** [comment]
@daanpape can you share some information like:

- platform and OS version
- baresip version
- baresip log
- v4l2 dump of your camera

the pixel format above is defined in ffmpeg api:

```
    AV_PIX_FMT_YUVJ422P,  ///< planar YUV 4:2:2, 16bpp, full scale (JPEG), deprecated in favor of AV_PIX_FMT_YUV422P and setting color_range
```

The pixel format is just regular YUV422P with JPEG color range.

**Comment by daanpape** [comment]
Hello Alfred,

Thank you for your response, please find the information below:

- platform and OS version: I'm using an alwinner A20 board on OpenWRT
- I'm using bareseip v0.6.0
- v4l2 dump: as this is an IP network camera I'm not using v4l2

Has anyone used an MJPEG IP-camera as video input before?

**Comment by alfredh** [comment]
@daanpape I need some more information from you:

1. full baresip log with baresip running with -v flag (verbose)
2. version of ffmpeg used

please try to update to git HEAD, I added some extra debug info

**Comment by alfredh** [comment]
we can also try to use the libavcodec handler `get_format` to print or set
the supported pixel formats:

https://stackoverflow.com/questions/9652760/how-to-set-decode-pixel-format-in-libavcodec

are you able to add this function, or should I create a patch for you ?

**Comment by alfredh** [comment]
@daanpape here is the patch to show the supported pixel formats:


```diff
diff --git a/modules/avformat/avformat.c b/modules/avformat/avformat.c
index a0e774e..7b1e8c8 100644
--- a/modules/avformat/avformat.c
+++ b/modules/avformat/avformat.c
@@ -223,6 +223,27 @@ static void *read_thread(void *data)
 }
 
 
+static enum AVPixelFormat get_format_callback(struct AVCodecContext *s,
+					      const enum AVPixelFormat *fmtv)
+{
+	enum AVPixelFormat fmt;
+	int i;
+
+	for (i=0; i<64; i++) {
+
+		fmt = fmtv[i];
+
+		if (fmt == -1)
+			break;
+
+		info("avformat: .... supported pixel format: %s\n",
+		     av_get_pix_fmt_name(fmt));
+	}
+
+	return AV_PIX_FMT_YUV420P;
+}
+
+
 static int alloc(struct vidsrc_st **stp, const struct vidsrc *vs,
 		 struct media_ctx **mctx, struct vidsrc_prm *prm,
 		 const struct vidsz *size, const char *fmt,
@@ -304,6 +325,8 @@ static int alloc(struct vidsrc_st **stp, const struct vidsrc *vs,
 		if (ctx->codec_type != AVMEDIA_TYPE_VIDEO)
 			continue;
 
+		ctx->get_format = get_format_callback;
+
 		debug("avformat: stream %u:  %u x %u "
 		      "  time_base=%d/%d\n",
 		      i, ctx->width, ctx->height,
```

when I run it locally I get something like this:

```
vidloop: avformat,/Users/alfredh/bin/ik.mkv: open video source: 320 x 240 at 25.00 fps
avformat: .... supported pixel format: videotoolbox_vld
avformat: .... supported pixel format: yuv420p
```

**Comment by alfredh** [comment]
@daanpape please confirm if you can provide the extra information.
if you can't provide it I will close the issue

**Comment by daanpape** [comment]
Hello Alfred, sorry for my late reply. I was some time offline due to the unexpected death of my grandmother. I will try to provide you with the correct information at the beginning of next week.

**Comment by alfredh** [comment]
@daanpape sorry to hear about your loss.

dont worry about this issue. I am not sure if we are able to fix it,
since the pixel format is not supported by baresip/rem ..

**Comment by alfredh** [comment]
closing this one for now until further information is provided.

**Comment by blizniukp** [comment]
Hello,
I have the same error: "avformat: decode: bad pixel format (13) (yuvj422p)"

I use baresip compiled from source (Tue Apr 27 14:44:53 2021).
For test I using movie converted to yuvj422p. Normally I use data from esp-cam.

log from baresip:

`Execute: ./baresip -f /home/khadas/baresip_new/config -v
baresip v1.1.0 Copyright (C) 2010 - 2021 Alfred E. Heggestad et al.
Local network address:  IPv4=wlan0|192.168.43.14
ui: stdio
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aucodec: L16/48000/2
aucodec: L16/44100/2
aucodec: L16/32000/2
aucodec: L16/16000/2
aucodec: L16/8000/2
aucodec: L16/48000/1
aucodec: L16/44100/1
aucodec: L16/32000/1
aucodec: L16/16000/1
aucodec: L16/8000/1
ausrc: aufile
auplay: aufile
vidcodec: H264
vidcodec: H264
vidcodec: H263
vidcodec: H265
avcodec: using H.264 encoder 'libx264' -- libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.264 decoder 'h264' -- H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.265 encoder 'libx265' -- libx265 H.265 / HEVC
avcodec: using H.265 decoder 'hevc' -- HEVC (High Efficiency Video Coding)
ausrc: avformat
vidsrc: avformat
gst: init: GStreamer 1.14.5
ausrc: gst
medianat: stun
medianat: turn
medianat: ice
uuid: loaded UUID 9c7f92af-c2d4-85e7-782c-36766e94b123 from file /home/khadas/baresip_new/config/uuid
ua: ua_register sip:test@192.168.200.100
Populated 1 account
module: loading app auloop.so
module: loading app contact.so
Populated 0 contacts
module: loading app debug_cmd.so
module: loading app menu.so
module: loading app presence.so
Subscribing to 0 contacts
module: loading app vidloop.so
Populated 12 audio codecs
Populated 0 audio filters
Populated 4 video codecs
Populated 0 video filters
baresip is ready.
test@91.209.200.100: (prio 0) {0/UDP/v4} 200 OK (YATE/6.2.1) [1 binding]
All 1 useragent registered successfully! (2740 ms)
presence: ua=0x55a1a90ae0 got event 1 (REGISTER_OK)
ua: sipsess connect via UDP 91.209.200.100:9005 --> 192.168.43.14:43265
test@91.209.200.100: selected for test-0x55a1a90ae0
ua: using AF from sdp offer: af=AF_INET
call: alloc with params laddr=192.168.43.14, af=AF_INET, use_rtp=1
call: use_video=1
call: no common audio codecs - rejected
presence: ua=0x55a1a90ae0 got event 15 (CALL_CLOSED)
video: stopping video source ..
video: stopping video display ..
audio: destroyed (started=0)
ua: sipsess connect via UDP 91.209.200.100:9005 --> 192.168.43.14:43265
test@91.209.200.100: selected for test-0x55a1a90ae0
ua: using AF from sdp offer: af=AF_INET
call: alloc with params laddr=192.168.43.14, af=AF_INET, use_rtp=1
call: use_video=1
call: answering call on line 1 from sip:komp-0@192.168.202.116:9005 with 200
call: update media
presence: ua=0x55a1a90ae0 got event 27 (CALL_REMOTE_SDP)
stream: update 'audio'
stream: audio: starting RTCP with remote 91.209.200.100:9007
stream: update 'video'
stream: video: starting RTCP with remote 91.209.200.100:9011
audio: update
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: start
audio: create recv buffer [20 - 160 ms] [320 - 2560 bytes]
audio: player started with sample format S16LE
audio: Set audio encoder: PCMU 8000Hz 1ch
audio: start
aufile: loading input file '/home/khadas/file.wav'
aufile: /home/khadas/file.wav: 22050 Hz, 1 channels, S16LE
aufile: audio ptime=20 sampc=441
aufile: read end of file
aufile: loaded 2646000 bytes
audio: source started with sample format S16LE
audio tx pipeline:      aufile ---> PCMU
video: update
Set video encoder: H264 packetization-mode=0 (1000000 bit/s, 1.00 fps)
avcodec: h264 encoder activated
avcodec: video encoder H264: 1.00 fps, 1000000 bit/s, pktsize=1024
video: start source
avformat: video: alloc dev='/home/khadas/yuv422.mov'
avformat: 'video' using decoder 'mjpeg' (MJPEG (Motion JPEG))
video: stopping video display ..
presence: ua=0x55a1a90ae0 got event 26 (CALL_LOCAL_SDP)
avformat: decode: bad pixel format (13) (yuvj422p)
avformat: decode: bad pixel format (13) (yuvj422p)
avformat: decode: bad pixel format (13) (yuvj422p)
avformat: decode: bad pixel format (13) (yuvj422p)
avformat: decode: bad pixel format (13) (yuvj422p)`
