### ISSUE TITLE
about mandatory srtp

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#641]
When account's mediaenc=srtp-mand, baresip uses RTP/SAVP in outbound calls, but hapily accepts incoming call with RTP/AVP.  Is there a way to make RTP/SAVP mandatory in incoming calls, i.e., make baresip to respond with "488 Not Acceptable Here" if RTP protocol of incoming call is not SAVP?

**Comment by alfredh** [comment]
the default SDP protocol for outgoing calls is RTP/AVP and this can be
overridden by the mediaenc protocol:

```c
struct menc {
	struct le le;
	const char *id;
	const char *sdp_proto;
	menc_sess_h *sessh;
	menc_media_h *mediah;
};
```

example usage in the `srtp` module:

```c
static struct menc menc_srtp_mand = {
	LE_INIT, "srtp-mand", "RTP/SAVP", NULL, alloc
};
```

for incoming calls, we add a list of sdp protocols to be more flexible:

```c
		err = sdp_media_set_alt_protos(st->sdpm, 4,
					       "RTP/AVP",
					       "RTP/AVPF",
					       "RTP/SAVP",
					       "RTP/SAVPF");
```

is there a special scenario that you are trying to get working?
or is there some interop issue with a different client ?

You can also have a look at Opportunistic SRTP:
https://tools.ietf.org/html/draft-ietf-sipbrandy-osrtp-07

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> is there a special scenario that you are trying to get working?
> or is there some interop issue with a different client ?

I try to make SAVP mandatory both in incoming and outgoing calls.
srtp-mand makes it mandatory only for outgoing calls.  As I explained, I
want baresip to respond with "488 Not Acceptable Here" if RTP protocol
of incoming call is not SAVP.

Currently it seems that mediaenc param only applies to outgoing calls
and there is no corresponding param for incoming calls.

-- Juha

**Comment by alfredh** [comment]
we can change it so that
alt protos is not added for mand

**Comment by alfredh** [comment]
if we dont call sdp_media_set_alt_protos then outgoing and incoming SDP protocol
is the same.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> we can change it so that alt protos is not added for mand

That would be great. Is a new config param needed for backwards
compatibility?

**Comment by alfredh** [comment]
I dont think there is a need for backwards compatibility.

one way to solve this is to modify the srtp module:

```
static int alloc(struct menc_media **stp, struct menc_sess *sess,
		 struct rtp_sock *rtp,
		 int proto, void *rtpsock, void *rtcpsock,
		 struct sdp_media *sdpm)
{
	struct menc_st *st;
	const char *rattr = NULL;
	int layer = 10; /* above zero */
	int err = 0;
	bool mux = (rtpsock == rtcpsock);
	(void)sess;
	(void)rtp;

	if (!stp || !sdpm)
		return EINVAL;
	if (proto != IPPROTO_UDP)
		return EPROTONOSUPPORT;

	st = (struct menc_st *)*stp;
	if (!st) {

		st = mem_zalloc(sizeof(*st), destructor);
		if (!st)
			return ENOMEM;

		st->sdpm = mem_ref(sdpm);

		err = sdp_media_set_alt_protos(st->sdpm, 4,
					       "RTP/AVP",
					       "RTP/AVPF",
					       "RTP/SAVP",
					       "RTP/SAVPF");
```

in the last step, when calling sdp_media_set_alt_protos, find a conditional
that can trigger this.

1. if proto is RTP/AVP then call `sdp_media_set_alt_protos`

2. if proto is RTP/SAVP or RTP/SAVPF then dont call it.

this should give the wanted behaviour that you are describing.

**Comment by juha-h** [comment]
Thanks for the suggestion. I'll try to create a pull request based on it.
