### ISSUE TITLE
Should presence status be printed in 'contacts' output, when the module 'presence.so' is not enabled?

### ISSUE THREAD

**Issue by github-ernst** [alfredh/baresip#645]
Hi,

Even if the module 'presence.so' is not enabled, the status is still printed in the contacts output.

Maybe something to look into.

**Comment by alfredh** [comment]
@github-ernst thanks for your input, I agree with your view here.

it can be solved by adding a flag if presence is enabled or not.

by default, if presence is not enabled we can print the contacts like this:

```
--- Contacts: (3) ---
   Albert Albertson <sip:albert@einstein.org>
>  Benny Baumeister <sip:benny@yahoo.com>
   Cavity McCavity <sip:cavity@dental.com>
```
