### ISSUE TITLE
Invalid SIP Address of Record: sip:1a@example.com

### ISSUE THREAD

**Issue by streaps** [alfredh/baresip#648]
It looks like baresip doesn't accept SIP URIs that start with a numeric character and also include alphabetic characters on account creation.

> **Notice:**
> Invalid SIP Address of Record:
> sip:1a@example.com

**Comment by alfredh** [comment]
I think you should report this bug to this project instead:

https://github.com/juha-h/baresip-studio

the uri in your example works just fine with baresip.

**Comment by streaps** [comment]
For some reason I thought baresip and barsip for Android is the same project. Thank you for the info, I will report it there.

**Comment by juha-h** [comment]
This is now fixed in baresip-studio.
