### ISSUE TITLE
excluding modules

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#661]
I have not found a means to exclude modules, such as menu or httpd, without editing modules.mk.  Is it possible somehow?

If not and If there would be an EXCLUDE_MODULES variable, then it might work to add a module to MODULES in modules.mk only if it is not listed in EXCLUDE_MODULES.

**Comment by alfredh** [comment]
the makefile variable `MOD_AUTODETECT` can be used to enable/disabled automatic
detection of modules, but this does not include the basic modules.

```
$ make info MOD_AUTODETECT=
info - baresip version 0.6.1
  MODULES:        stun turn ice auloop presence menu contact vumeter mwi account natpmp httpd srtp uuid debug_cmd ctrl_tcp b2bua aubridge aufile vidloop selfview vidbridge fakevideo dtls_srtp
```

the list of modules is created here:

```make
MODULES   += $(EXTRA_MODULES)
MODULES   += stun turn ice auloop presence
MODULES   += menu contact vumeter mwi account natpmp httpd
MODULES   += srtp
MODULES   += uuid
MODULES   += debug_cmd
MODULES   += ctrl_tcp
MODULES   += b2bua
```

instead of adding a new EXCLUDE modules variable, we could instead add
a variable BASIC_MODULES = yes|no that we can use to include this list or nor.
any extra modules can then be added to `EXTRA_MODULES`.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> instead of adding a new EXCLUDE modules variable, we could instead add
> a variable BASIC_MODULES = yes|no that we can use to include this list or nor.
> any extra modules can then be added to `EXTRA_MODULES`.

Sounds good to me.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> instead of adding a new EXCLUDE modules variable, we could instead add
> a variable BASIC_MODULES = yes|no that we can use to include this list or nor.
> any extra modules can then be added to `EXTRA_MODULES`.

Would the diff below be OK?

``
diff --git a/mk/modules.mk b/mk/modules.mk
index 5581942..dee20f7 100644
--- a/mk/modules.mk
+++ b/mk/modules.mk
@@ -265,6 +265,7 @@ endif
 # ------------------------------------------------------------------------- #
 
 MODULES   += $(EXTRA_MODULES)
+ifneq ($(BASIC_MODULES),no)
 MODULES   += stun turn ice natbd auloop presence
 MODULES   += menu contact vumeter mwi account natpmp httpd
 MODULES   += srtp
@@ -272,6 +273,7 @@ MODULES   += uuid
 MODULES   += debug_cmd
 MODULES   += ctrl_tcp
 MODULES   += b2bua
+endif

 ifneq ($(HAVE_LIBMQTT),)
 MODULES   += mqtt
``

**Comment by alfredh** [comment]
yeah looks great.

please feel free to commit directly to master :)

(as long as it does not break something :)

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> please feel free to commit directly to master :)

I did, but then it turned out that it was not enough.  These basic
modules got still included:

ifneq ($(HAVE_LIBMQTT),)
MODULES   += mqtt
endif

ifneq ($(HAVE_PTHREAD),)
MODULES   += aubridge aufile
endif
MODULES   += vidloop selfview vidbridge
MODULES   += fakevideo

Have to move endif after fakevideo.

**Comment by alfredh** [comment]
@juha-h thanks for the fix.

I also did some clean up in that section. anything else that has to be done here ?

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I also did some clean up in that section. anything else that has to be
> done here ?

Nothing important.  Only thing that I have been wondering, why some
variables, such as MOD_AUTODETECT, have "1/no value" choice, and some
others "yes/no" choice.  I would prefer that all these kind of binary
vars would have "yes/no" choice.

**Comment by alfredh** [comment]
the general rule about usage of makefile variables, is:

1. defined and set to something -- means "Enabled"
2. not defined -- means "Disabled".

for example from `modules.mk`:

```
# Default is enabled
MOD_AUTODETECT := 1

ifneq ($(MOD_AUTODETECT),)
```

`:=` means set to 1 (enabled) if not already defined.

it can be overridden by the makefile arguments.

To force enable of modules autodetect:

```
$ make MOD_AUTODETECT=yes
$ make MOD_AUTODETECT=1
```

To force disable of modules autodetect:

```
$ make MOD_AUTODETECT=
```

(i.e. not defined).

this is the same logic in libre re.mk and has been like this for many years.
there are many upstream makefiles and scripts that depend on this logic
so I dont think we should change the semantics now.

**Comment by alfredh** [comment]
I believe the issue has been fixed now. if not please re-open.
