### ISSUE TITLE
In daemon mode wav file not play

### ISSUE THREAD

**Issue by dekardkrr** [alfredh/baresip#663]
Hello.
I have a config file with params: 
audio_source            aufile,test.wav
module                  aufile.so
module                  httpd.so
When i started baresip without -d key and connect over http i dial command http://ip_adres/?d1234 
and audio file test.wav playing auto.
But when i started baresip as daemon with key -d file test.wav not playing and when i answer call is break.
What do i incorrect?

**Comment by alfredh** [comment]
I think the daemon mode changes the current path to something else.

Try to use absolute path for the test.wav

**Comment by dekardkrr** [comment]
Thanks a lot.
Excellent application!

**Comment by alfredh** [comment]
the wav file must be with absolute path:

https://github.com/alfredh/baresip/blob/master/modules/aufile/aufile.c#L14
