### ISSUE TITLE
MQTT subscribe topic

### ISSUE THREAD

**Issue by seamus-45** [alfredh/baresip#669]
Hi, appreciate your work!

Is there any reason for `/baresip/command/+' subscribe topic?
https://github.com/alfredh/baresip/blob/463be40fc55ccedf085b94b4ad768596c7e239f0/modules/mqtt/mqtt.c#L106

If so, docs must be updated. Currently, I can't control baresip with such command:
```
mosquitto_pub -t /baresip/command -m '{"command":"dial","params":"sip:1334@example.com"}'
```
and need to specify any sub channel, e.g. `/baresip/command/foo'

Next patch resolve problem for me:
```
--- a/modules/mqtt/mqtt.c       2019-03-14 13:56:26.303106238 +0500
+++ b/modules/mqtt/mqtt.c       2019-03-14 13:58:10.075489296 +0500
@@ -103,7 +103,7 @@
                broker_host, broker_port, mqttclientid, mqttbasetopic);

        snprintf(mqttsubscribetopic, sizeof(mqttsubscribetopic),
-               "/%s/command/+", mqttbasetopic);
+               "/%s/command", mqttbasetopic);
        snprintf(mqttpublishtopic, sizeof(mqttpublishtopic), "/%s/event",
                mqttbasetopic);
        info("mqtt: Publishing on %s, subscribing to %s\n",
```

**Comment by alfredh** [comment]
@seamus-45 thanks for your input


this command works for me:

```
$ mosquitto_pub -t /baresip/command/ -m '{"command":"sysinfo","token":"tok123"}'
```
(i.e. trailing slash after `command`)


and response from a sub client:

```
/baresip/command_resp/tok123 
--- System info: ---
 Machine:  x86_64/darwin
 Version:  0.6.1 (libre v0.6.0)
 Build:    64-bit little endian
 Kernel:   Darwin Johns-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Sun Oct 28 22:30:19 PDT 2018; root:xnu-3789.73.27~1/RELEASE_X86_64 x86_64
 Uptime:   40 secs
 Started:  Tue Mar 26 21:14:36 2019
 Compiler: 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)
 OpenSSL:  OpenSSL 1.0.2r  26 Feb 2019
```

@oej and @Ola-Palm any comments about this ? is the current code
working in your production environment ?

**Comment by oej** [comment]
It works, but the plus means that there has to be some trailing word after the slash. I was considering making it configurable.

**Comment by alfredh** [comment]
in this case I think we just keep the current logic as is.

I will update the example documentation.
