### ISSUE TITLE
More flexibility in gst_video

### ISSUE THREAD

**Issue by michaelkrog** [alfredh/baresip#67]
It's awesome that baresip can use gstreamer for video input,  but I cannot see how to use it for frames that are already encoded. 

I would like to serve video from a rtsp stream with h264 encoded video, but I don't know how.

**Comment by alfredh** [comment]
the gst_video module can only use raw video-frames as input.

however you might be able to tweak the Gstreamer pipeline to read
from your RTSP stream:

https://github.com/alfredh/baresip/blob/master/modules/gst_video1/encode.c#L231

another solution is to use the `avformat` module:

```
video_source      avformat,rtsp://your-stream-url
```
