### ISSUE TITLE
Unable to use sndfile module in Windows

### ISSUE THREAD

**Issue by alexander-elgin** [alfredh/baresip#672]
I compiled baresip in Ubuntu using [baresip-win32](https://github.com/alfredh/baresip-win32). Unfortunately if I enable `sndfile.so` module in the config file call recording is not activated. Here is the initialization log

```
baresip v0.6.1 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.
Local network address:  IPv4=:192.168.0.106 
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
[31mmodule sndfile.dll: unknown error
[;mwinwave: output devices: 1, input devices: 1
ausrc: winwave
auplay: winwave
vidsrc: dshow
medianat: stun
medianat: turn
medianat: ice
Populated 1 account
Populated 3 contacts
Populated 2 audio codecs
Populated 1 audio filter
Populated 0 video codecs
Populated 0 video filters
baresip is ready.
0042579440@sipnet.ru: {0/TCP/v4} 200 OK (CommuniGatePro/6.2.12) [1 binding]
ua: stop all (forced=0)
```

How can I fix it?

**Comment by Encamy** [comment]
Hello @alexander-elgin 
It seems like you do not have libsndfile installed. You can find option `USE_SNDFILE` in `mk/modules.mk`. So if you have libsndfile then this option will be enabled.

I would like to suggest to compile with Visual Studio on Windows if you are building project for Windows system (https://github.com/creytiv/re/issues/150#issuecomment-413457602).
`sndfile.c` is not included in project by default, so you have to do this manually (baresip/modules/Add Exiting Item)

**Comment by alexander-elgin** [comment]
I do have `libsndfile` installed using `sudo apt-get install libsndfile1-dev`. The `sndfile.h` is located under the `/usr/include` path. Actually I can build baresip package for Ubuntu without any issues. But if I set `USE_SNDFILE` to 1in the `mk/modules.mk` and try to cross compile using mingw-w64 (see https://github.com/alfredh/baresip-win32) I get the following error

```
  SH      src/static.c
  CC      build-i686/src/static.o
  CC [m]  build-i686/modules/sndfile/sndfile.o
modules/sndfile/sndfile.c:6:21: fatal error: sndfile.h: No such file or directory
compilation terminated.
mk/mod.mk:80: recipe for target 'build-i686/modules/sndfile/sndfile.o' failed
make[1]: *** [build-i686/modules/sndfile/sndfile.o] Error 1
```

Why is it so? Any suggestions?

**Comment by Encamy** [comment]
Try to add `-I/usr/include` to CFLAGS in `Makefile`. This fixed error for me

**Comment by alexander-elgin** [comment]
`libsndfile1-dev` installs `libsndfile` for Linux GNU compiler but it is required to integrate `libsndfile` to mingw-w64. For that purpose I clonned https://github.com/erikd/libsndfile and for the version 1.0.27 did the following:

```
./configure --host=i686-w64-mingw32 --prefix=/usr/i686-w64-mingw32
make
sudo make install
```

It puts `sndfile.h` and `sndfile.hh` to `/usr/i686-w64-mingw32/include` as well as `libsndfile.a`, `libsndfile.dll.a` and `libsndfile.la` to `/usr/i686-w64-mingw32/lib`.
There is no warning about missed library anymore (i.e. it seems that `libsndfile` is successfully integrated with mingw-w64). However `make` command in `baresip-win32` now fails with the following error

```
  LD      selftest.exe
./libbaresip.a(sndfile.o): In function `dec_destructor':
/home/alex/projects/baresip-win32/baresip/modules/sndfile/sndfile.c:67: undefined reference to `sf_close'
./libbaresip.a(sndfile.o): In function `enc_destructor':
/home/alex/projects/baresip-win32/baresip/modules/sndfile/sndfile.c:56: undefined reference to `sf_close'
./libbaresip.a(sndfile.o): In function `openfile':
/home/alex/projects/baresip-win32/baresip/modules/sndfile/sndfile.c:109: undefined reference to `sf_open'
/home/alex/projects/baresip-win32/baresip/modules/sndfile/sndfile.c:112: undefined reference to `sf_strerror'
./libbaresip.a(sndfile.o): In function `decode':
/home/alex/projects/baresip-win32/baresip/modules/sndfile/sndfile.c:213: undefined reference to `sf_write_raw'
./libbaresip.a(sndfile.o): In function `encode':
/home/alex/projects/baresip-win32/baresip/modules/sndfile/sndfile.c:197: undefined reference to `sf_write_raw'
collect2: error: ld returned 1 exit status
Makefile:212: recipe for target 'selftest.exe' failed
make[1]: *** [selftest.exe] Error 1
make[1]: Leaving directory '/home/alex/projects/baresip-win32/baresip'
Makefile:128: recipe for target 'baresip' failed
make: *** [baresip] Error 2
```

What is the reason of that?

**Comment by alexander-elgin** [comment]
Solved finally. `-lsndfile` flag had also be added to e.g. https://github.com/alfredh/baresip-win32/blob/master/Makefile#L48
