### ISSUE TITLE
Can i use delay before play media file?

### ISSUE THREAD

**Issue by dekardkrr** [alfredh/baresip#673]

**Comment by alfredh** [comment]
@dekardkrr 

currently there is no option to add delay before media file is played.

but you can insert silence at the start of your media file like this:

```
$ sox input.wav output.wav pad 5 0
```

(adds 5 seconds of silence to the beginning).


NOTE: next time please include a bit more information in the description :)
it is a bit hard to try to guess what you want from just one line of text.
