### ISSUE TITLE
Dont know how to set a proxy 

### ISSUE THREAD

**Issue by ccokee** [alfredh/baresip#675]
Well Im stuck configuring the account because my provider, which uses domain xxxxxx.net but also has a proxy on XXX.XXX.XXX.XXX:5070. How do I set the proxy and its port? Thx

**Comment by juha-h** [comment]
ccokee writes:

> Well Im stuck configuring the account because my provider, which uses
> domain xxxxxx.net but also has a proxy on XXX.XXX.XXX.XXX:5070. How do
> I set the proxy and its port?

In an account, try outbound="sip:XXX.XXX.XXX.XXX:5070;transport=YYY".

**Comment by ccokee** [comment]
I get Register: Destination address required

**Comment by ccokee** [comment]
I got it working
