### ISSUE TITLE
Freeze on calls

### ISSUE THREAD

**Issue by ccokee** [alfredh/baresip#676]
Everytime I run a call, I cant hear anything or send audio, and the program freezes, I cant hang up or close connection or send a ctrl+c. Also, the clock of the call doesn't even start to count, but I remark the call is running in the other end. Im on gentoo linux and using current release.

This is my config file:
https://bpaste.net/show/55d670fa105a

**Comment by ccokee** [comment]
Solved by changing some parameters and emerging missed packages

**Comment by bhautik-ziniya** [comment]
Hi @ccokee,

I'm faceing the same issue while making a call, what parameteres and packages you have changed to solve the issue ?

**Comment by fluffynukeit** [comment]
@ccokee exact same issue here.  What did you change to fix it?  Saying "I fixed it" with no explanation is a cardinal sin of the internet.
