### ISSUE TITLE
delay between physical line and voip

### ISSUE THREAD

**Issue by ccokee** [alfredh/baresip#677]
My ont-router config has a output for the typical rj11 infrastructure, I've tryed to do some calls but baresip always starts notifying the call like 4 tones latter than the "copper" instalation. What could I do to enhace the detection of incomming calls?

**Comment by alfredh** [comment]
@ccokee 

do you have some more information about the setup, versions, logs etc?

is the issue that there is a long delay for incoming calls ?
(how long is 4 tones ?)

Alfred

**Comment by ccokee** [comment]
Well I clearly didnt found the exact word I meant (Im spanish). I have a router+switch+ont+voip  box from my ftth provider. This box has an output for old twisted pair phone installations... Instead of having a PTR I get line in the classic telephones through that box. Well, the thing is, when I call my home with baresip open un my computer and connected to my home voip, baresip starts ringing waaaaaaay later than the normal phones do. Is this a known issue?

**Comment by alfredh** [comment]
in a normal setup there should be virtually no delay from the SIP proxy to baresip.

how long is the delay you are talking about? is it 1 second, 10 seconds or 100 seconds ?

can you please provide the baresip output from start and until there is
an incoming call ?

also a Wireshark or ngrep trace would be nice to have a look at.
(sudo ngrep -p -d any -W byline port 5060).

**Comment by alfredh** [comment]
closing due to lack of response. feel free to re-open if you can provide the requested info.
