### ISSUE TITLE
baresip return on error when receive call-in...

### ISSUE THREAD

**Issue by BroWater** [alfredh/baresip#68]
Hello Alfredh,

following are my environmental settings:

Baresip UA 1 (call BUA1 here) :    Centos 6.5 (virtual box) , public IP 
Baresip UA 2 (call BUA2 here) :    Centos 6.5  , behind NAT
Linphone PC UA (called LinphoneUA here)  : Windows 7 , public IP

I let BUA1 and BUA2  do registration and make a call between them,
however,  the callee always return 486 Busy here,
even I change the caller to LinphoneUA , the result is the same.

And if the caller remain as baresip but the callee is changed to LinphoneUA or other non-baresip UA,
it works!

Any thought about this ?  :P

**Comment by lmangani** [comment]
This requires further details and/or a SIP trace to even be interpreted, anyhow does not seem to be an issue with Baresip but rather with your setup or softswitch settings. Install SIPGREP or Ngrep, take a look at the SIP session details and you should see the root cause.

**Comment by BroWater** [comment]
Following is the result I captured by SIPGREP on callee side (which is baresip),
212.79.111.155 is the ip address of iptel.org

I found the weird part that the username of Request URI in INVITE is wrong,
should be "1234" , not "1234-0x843570",
but I check the original INVITE from the caller, it's normal.

Any idea why this happen?? 

=====================================================


U 2015/08/20 17:34:01.843371 212.79.111.155:5060 -> 192.168.1.219:5060

INVITE sip:1234-0x843570@192.168.1.219:5060 SIP/2.0.
Via: SIP/2.0/UDP 212.79.111.155;branch=z9hG4bKXFAZlaNU;rport.
From: <sip:5678@iptel.org>;tag=1C67030F-55D59EDD0001B420-B401D700.
To: <sip:1234@iptel.org>.
CSeq: 10 INVITE.
Call-ID: 4E06BFAB-55D59EDD0001B42D-B401D700.
Max-Forwards: 15.
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO.
User-Agent: XXXX 
P-hint: usrloc applied.
Session-Expires: 1800.
Content-Type: application/sdp.
Content-Length: 1564.
Contact: <sip:75F6C2A6-55D59EDD0001D4B0-B3E1B700@212.79.111.155;transport=udp>.
.
v=0.
o=- 0 0 IN IP4 212.79.111.155.
s=-.
c=IN IP4 212.79.111.155.
b=AS:621.
t=0 0.
m=audio 14932 RTP/AVP 9 0 8 15 101 102 103 104 105 97.
a=rtpmap:9 G722/8000.
a=rtpmap:0 PCMU/8000.
a=rtpmap:8 PCMA/8000.
a=rtpmap:15 G728/8000.
a=rtpmap:101 G7221/16000.
a=fmtp:101 bitrate=24000.
a=rtpmap:102 G7221/16000.
a=fmtp:102 bitrate=32000.
a=rtpmap:103 G7221/32000.
a=fmtp:103 bitrate=24000.
a=rtpmap:104 G7221/32000.
a=fmtp:104 bitrate=32000.
a=rtpmap:105 G7221/32000.
a=fmtp:105 bitrate=48000.
a=rtpmap:97 telephone-event/8000.
a=fmtp:97 0-11.
a=sendrecv.
m=video 14936 RTP/AVP 108 107 106 34 31.
b=TIAS:621000.
a=rtpmap:108 H264/90000.
a=fmtp:108 profile-level-id=640028;max-mbps=244800;max-fs=8160;max-br=621;packetization-mode=0.
a=rtpmap:107 H264/90000.
a=fmtp:107 profile-level-id=428028;max-mbps=244800;max-fs=8160;max-br=621;packetization-mode=0.
a=rtpmap:106 H263-1998/90000.
a=fmtp:106 CIF=1;QCIF=1.
a=rtpmap:34 H263/90000.
a=fmtp:34 CIF=1;QCIF=1.
a=rtpmap:31 H261/90000.
a=fmtp:31 CIF=2;QCIF=2.
a=sendrecv.
a=content:main.
a=label:1.
m=application 14938 RTP/AVP 100.
a=rtpmap:100 H224/4800.
a=sendrecv.



U 2015/08/20 17:34:01.844373 192.168.1.219:5060 -> 212.79.111.155:5060

SIP/2.0 180 Ringing.
Via: SIP/2.0/UDP 212.79.111.155;branch=z9hG4bKXFAZlaNU;rport=5060;received=212.79.111.155.
From: <sip:5678@iptel.org>;tag=1C67030F-55D59EDD0001B420-B401D700.
To: <sip:1234@iptel.org>;tag=6d5948d82b3371b5.
CSeq: 10 INVITE.
Call-ID: 4E06BFAB-55D59EDD0001B42D-B401D700.
Server: baresip v0.4.14 (x86_64/linux).
Contact: <sip:1234-0x843570@192.168.1.219:5060>.
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,REFER,NOTIFY,SUBSCRIBE,INFO,MESSAGE.
Content-Length: 0.
.


U 2015/08/20 17:34:01.844484 192.168.1.219:5060 -> 212.79.111.155:5060

SIP/2.0 486 Busy Here.
Via: SIP/2.0/UDP 212.79.111.155;branch=z9hG4bKXFAZlaNU;rport=5060;received=212.79.111.155.
From: <sip:5678@iptel.org>;tag=1C67030F-55D59EDD0001B420-B401D700.
To: <sip:1234@iptel.org>;tag=6d5948d82b3371b5.
CSeq: 10 INVITE.
Call-ID: 4E06BFAB-55D59EDD0001B42D-B401D700.
Server: baresip v0.4.14 (x86_64/linux).
Content-Length: 0.
.


U 2015/08/20 17:34:02.156138 212.79.111.155:5060 -> 192.168.1.219:5060

ACK sip:1234-0x843570@192.168.1.219:5060 SIP/2.0.
Via: SIP/2.0/UDP 212.79.111.155;branch=z9hG4bKXFAZlaNU;rport.
From: <sip:5678@iptel.org>;tag=1C67030F-55D59EDD0001B420-B401D700.
To: <sip:1234@iptel.org>;tag=6d5948d82b3371b5.
Call-ID: 4E06BFAB-55D59EDD0001B42D-B401D700.
CSeq: 10 ACK.
Content-Length: 0.

**Comment by alfredh** [comment]
hi, could you please try latest version of baresip from GIT ?

please also include the console output of Caller and Callee.

please also include config and accounts in $HOME/.baresip

NOTE: the username part of uri 1234-0x843570 is perfectly fine, it is the same as the username
in the REGISTER/Contact header.

**Comment by alfredh** [comment]
close due to lack of response
