### ISSUE TITLE
Exposing CANCEL SIP message on terminated session

### ISSUE THREAD

**Issue by eriksundin** [alfredh/baresip#681]
**Scenario**

A call goes out to multiple recipients -  A,B and C.
Recipient B picks upp the call. 
A and C wants to know if the caller hung up, or if someone else picked up the call (B did).

Currently as the call closes, all A and C will know is that the peer reset the connection.
The sip `CANCEL` message causing the call to terminate, however, contains a reason header which can be interpreted.

---

I hackishly tried propagating the sip message up from the `cancel_handler` in `accept.c` in re. That way I could get my hands on it in baresip and could extract the reason header I wanted so it could be passed out to my `ua_event_handler`.

But, this test aside - Is there currently a way for me to listen for or access the sip `CANCEL` using the library as-is ?

Kind Regards,
Erik

**Comment by alfredh** [comment]
hi,

if there is an incoming call that is cancelled, this function will be called (in call.c):

```c
static void sipsess_close_handler(int err, const struct sip_msg *msg,
				  void *arg)
{
	struct call *call = arg;
	char reason[128] = "";

	MAGIC_CHECK(call);

	if (err) {
		info("%s: session closed: %m\n", call->peer_uri, err);

		(void)re_snprintf(reason, sizeof(reason), "%m", err);

		if (call->not) {
			(void)call_notify_sipfrag(call, 500, "%m", err);
		}
	}
	else if (msg) {

		call->scode = msg->scode;

		(void)re_snprintf(reason, sizeof(reason), "%u %r",
				  msg->scode, &msg->reason);

		info("%s: session closed: %u %r\n",
		     call->peer_uri, msg->scode, &msg->reason);

		if (call->not) {
			(void)call_notify_sipfrag(call, msg->scode,
						  "%r", &msg->reason);
		}
	}
	else {
		info("%s: session closed\n", call->peer_uri);
	}

	call_stream_stop(call);
	call_event_handler(call, CALL_EVENT_CLOSED, reason);
}
```


in your case err will be set to `ECONNRESET` and msg will be `NULL`


so currently there is no way to interpret the incoming `CANCEL` message ...

**Comment by eriksundin** [comment]
Thanks for the response, @alfredh.
Alright, then I know I wasn't missing something.

If adding a way of getting your hands on more low level information as a user of baresip, like the `CANCEL` message above. Considering that also involves changes to how `re` is currently working in this case. 
Would you say that's stepping out of the design goals you have for the library?
If not, I'd be happy to contribute.

Kind Regards,
Erik

**Comment by alfredh** [comment]
I think this case is a bit of a corner case, and not many people have asked for it so far.

we will most likely not make changes in libre to propagate CANCEL up to the application.
the libre API has been designed to be simple and hide protocol complexities from the user.

you are welcome to make a patch/PR for libre, but I cannot guarantee that it will be
accepted into master.

**Comment by eriksundin** [comment]
Great, thanks for the input. Closing this one and will have a look at a patch/PR for libre.
