### ISSUE TITLE
Assign UAs to audio devices

### ISSUE THREAD

**Issue by premultiply** [alfredh/baresip#683]
Hi,
I try to set up a call-in application with multiple UAs where each of them should be assigned to a fixed audio i/o channel on a RME HDSP MADI (64 channels) or similar interface board.
I already set up a proper ALSA device configuration which assigns a virtual stereo sound device to every two audio i/o channels. This works flawless if I assign them in baresip config with single UA.

I know I could run multiple single UA baresip instances now with specific audio configuration for each of them.
But it would be much less complex if I could assign the audio_player and audio_source in individual account configuration instead of having only a global setting for all UAs of a single instance as is already mentioned here #384 (would also solve #399).

Is there already something which could help me in reducing the configuration (and control) overhead of all those parallel instances or any other good idea?

Thanks,
Uli.

**Comment by alfredh** [comment]
this is possible to implement, but would require a large refactoring of 
struct account and struct audio. we would have to read the audio_source
from account, and if set use it, otherwise fall back to global config.

It is something that I may look into later, so I would suggest that we put it
on the roadmap for now.

**Comment by premultiply** [comment]
Thanks Alfred!
I've put it on the roadmap/whishlist.

**Comment by alfredh** [comment]
thanks, I will close it for now until we start working on it

**Comment by premultiply** [comment]
#796
