### ISSUE TITLE
un-REGISTER should terminate active subscriptions

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#686]
If UA upon un-REGISTER has any subscriptions (e.g. mwi), those should be terminated before un-REGISTER takes place.

**Comment by alfredh** [comment]
is it very important that the un-SUBSCRIBE completes successfully
before sending out in-REGISTER ?

i.e. consider this sequence of messages:

```
----- un-SUBSCRIBE ----->
<----- 200 OK ----------

----- un-REGISTER ----->
<----- 200 OK ----------
```


or 

```
----- un-SUBSCRIBE ----->
----- un-REGISTER ----->
<----- 200 OK ----------
<----- 200 OK ----------
```

one way to solve this is to use a event `UA_EVENT_UNREGISTERING` that can
be picked up in e.g. mwi module. when the mwi module receives that event, it can
terminate its subscription.

```c
static void ua_event_handler(struct ua *ua,
			     enum ua_event ev,
			     struct call *call,
			     const char *prm,
			     void *arg )
{
    switch (ev) {

    case UA_EVENT_UNREGISTERING:
        mem_deref(mwi);
        break;
    }
}
```

if you want to have a full async shutdown procedure, it is going to be
a lot more complicated.

any other ideas ?

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> is it very important that the un-SUBSCRIBE completes successfully
> before sending out in-REGISTER ?
> 
> i.e. consider this sequence of messages:
> 
> ```
> ----- un-SUBSCRIBE ----->
> <----- 200 OK ----------
> 
> ----- un-REGISTER ----->
> <----- 200 OK ----------
> ```
> 
> 
> or 
> 
> ```
> ----- un-SUBSCRIBE ----->
> ----- un-REGISTER ----->
> <----- 200 OK ----------
> <----- 200 OK ----------
> ```

The latter option could be OK too.

> one way to solve this is to use a event `UA_EVENT_UNREGISTERING` that can
> be picked up in e.g. mwi module. when the mwi module receives that
> event, it can terminate its subscription.
> 
> ```c
> static void ua_event_handler(struct ua *ua,
> 			     enum ua_event ev,
> 			     struct call *call,
> 			     const char *prm,
> 			     void *arg )
> {
>     switch (ev) {
> 
>     case UA_EVENT_UNREGISTERING:
>         mem_deref(mwi);
>         break;
>     }
> }
> ```

It is not just mwi subscriptions that would need to be terminated, but
also any contact subscriptions.

> if you want to have a full async shutdown procedure, it is going to be
> a lot more complicated.

For me the most important thing is to be able to dynamically remove UAs
without shutting down baresip, i.e., mem_deref(ua) should un-subscribe
ua's subscriptions, remove event state of ua's publications (send
PUBLISH requests with Expires value 0) and then un-register the ua.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> perhaps we can add an event that will ask anyone using SUBSCRIBE
> to un-SUBSCRIBE ?
> 
> this event can be sent from application before calling mem_deref(ua):
> 
> ```
> 	ua_event(ua, UA_EVENT_PLEASE_UNSUBSCRIBE, NULL, NULL);
> ```
> 
> and then picked up by mwi.so and presence.so

Sounds good for SUBSCRIBEs.  How about un-PUBLISH requests?

**Comment by alfredh** [comment]
I am just brain-storming for now .. After some more thinking, perhaps
the event should be more generic and we should call it UA_EVENT_DESTROYED instead?

it will be sent out when the UA is being destroyed:

static void ua_destructor(void *arg)
{
	struct ua *ua = arg;

	ua_event(ua, UA_EVENT_DESTROYED, NULL, NULL);

	/* ... */
}

this event can then be used by anything, including SUBSCRIBE and PUBLISH.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I am just brain-storming for now .. After some more thinking, perhaps
> the event should be more generic and we should call it
> UA_EVENT_DESTROYED instead?

Sounds very good. I'm ready for testing if you can provide handlers
for mwi and presence modules.

**Comment by alfredh** [comment]
it turns out that we cannot use the ua_destructor for this, since mwi has a ref to ua.
this causes a cyclical dependency, and the event would never get sent.

one alternative is to use this function to actively shutdown the UA
(similar to mem_deref but ua_shutdown will do the work even is ua has 100 references):

```c
void ua_shutdown(struct ua *ua)
{
	if (!ua)
		return;

	list_unlink(&ua->le);

	/* send the shutdown event */
	ua_event(ua, UA_EVENT_SHUTDOWN, NULL, NULL);

	/* terminate all calls now */
	list_flush(&ua->calls);

	mem_deref(ua);
}
```

since this event is already handled in mwi:

```c
	else if (ev == UA_EVENT_SHUTDOWN) {

		struct mwi *mwi = mwi_find(ua);

		if (mwi) {

			info("mwi: shutdown of %s\n", ua_aor(ua));
			mwi->shutdown = true;

			if (mwi->sub) {
				mwi->sub = mem_deref(mwi->sub);
				tmr_start(&mwi->tmr, 500, deref_handler, mwi);
			}
			else
				mem_deref(mwi);
		}
	}
```


it should work ..

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> one alternative is to use this function to actively shutdown the UA
> (similar to mem_deref but ua_shutdown will do the work even is ua has
> 100 references):
> 
> ```c
> void ua_shutdown(struct ua *ua)
> {
> 	if (!ua)
> 		return;
> 
> 	list_unlink(&ua->le);
> 
> 	/* send the shutdown event */
> 	ua_event(ua, UA_EVENT_SHUTDOWN, NULL, NULL);
> 
> 	/* terminate all calls now */
> 	list_flush(&ua->calls);
> 
> 	mem_deref(ua);
> }
> ```

I'll give it a try tomorrow.

**Comment by juha-h** [comment]
I tested ua_shutdown with success.  When UA was registered and had
subscribed to mwi, ua_shutdown resulted in mwi un-SUBSCRIBE followed by
un-REGISTER.

The only concern I have is the name of the function.  Would ua_destroy
or ua_dealloc be better?

**Comment by alfredh** [comment]
great, thanks for testing.

yeah, ua_destroy is perhaps a better name:

```c
void ua_destroy(struct ua *ua);
```

I have renamed the function in the branch, should I merge it to master ?

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I have renamed the function in the branch, should I merge it to master
> ?

Please do,

**Comment by alfredh** [comment]
added in commit 1406caf404a0d402210e86529feb0e8b6e0ac207

@juha-h thanks for the report and the testing
