### ISSUE TITLE
log level default value

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#687]
I didn't find possibility to set default value for log level (to be used when baresip starts) in config file. Is there some way to do it?

**Comment by alfredh** [comment]
the default log level is INFO.

the log level can be set to DEBUG if the -v option is given to baresip executable.

also baresip has commands to toggling the loglevel:

```
  /loglevel           v        Log level toggle
```

currently the log level is not possible to set in config file. but this is of course
possible to add. this could be added to the "core" section and look something
like this:

```
log_level    info
```

**Comment by juha-h** [comment]
OK, I'll try to do add it when I have extra time.
