### ISSUE TITLE
L16 stereo encoding broken

### ISSUE THREAD

**Issue by premultiply** [alfredh/baresip#688]
The encoding of all L16 stereo formats seem to be broken. Mono is fine.
I have done tests with AVT, Orban, Luci Studio (and their iOS App) and microSIP (on Windows) and none of them is able to decode the Linear PCM stream from baresip.
At least AVT does output some crackling sound.

**Comment by alfredh** [comment]
I have tested baresip to baresip and L16 mono/stereo is working.

* Which audio driver are you using ?

* Can you test another codec with stereo ?

* Can you include here baresip output and your config ?
  (perhaps also Wireshark trace if you have it)

**Comment by premultiply** [comment]
Hi Alfred,
I am running all my tested audio interfaces with alsa driver.
It is the same result for all tested devices:
- RME HDSP (PCI)
- RME MADIface Pro (USB)
- Terratec Aureon Dual USB Stick
- On-Board audio interfaces

All these devices works fine when using Opus or MPA in Stereo mode.
Only L16 stereo is broken when using any other UA than baresip as counterpart, baresip to baresip L16 stereo is fine. So there may be something incompatible with the transmitted network audio stream by baresip. The received audio (other UA TX to baresip RX playback) from the remote device is fine too.

I have tried these UAs:
- AVT MAGIC ACip3 2M Audiocodec (Embedded Device)
- Orban Opticodec 7600 (Embedded Device)
- TECHNICA DEL ARTE Luci (Studio and iOS App)
- MicroSIP (Windows)



Output from baresip:
```
baresip v0.6.1 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.
Local network address:  IPv4=enp0s25:192.168.8.198  IPv6=enp0s25:2003:c9:f70f:af00:21c:x:y:z
ui: stdio
cons: UI console listening on 0.0.0.0:5520
ui: cons
ui: http
httpd: listening on 0.0.0.0:8020
aucodec: L16/44100/2
aucodec: L16/32000/2
aucodec: L16/16000/2
aucodec: L16/8000/2
aucodec: L16/44100/1
aucodec: L16/32000/1
aucodec: L16/16000/1
aucodec: L16/8000/1
aucodec: AMR-WB/16000/1
aucodec: AMR/8000/1
aucodec: G722/16000/1
aucodec: G726-40/8000/1
aucodec: G726-32/8000/1
aucodec: G726-24/8000/1
aucodec: G726-16/8000/1
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
gsm: GSM v1.0.18
aucodec: GSM/8000/1
aucodec: CODEC2/8000/1
ausrc: alsa
auplay: alsa
medianat: stun
medianat: turn
medianat: ice
uuid: loaded UUID a68c8e48-09b8-4b34-2890-2bce61e39683 from file /etc/baresip/266620//uuid
Populated 1 account
module: loading app auloop.so
module: loading app contact.so
Populated 3 contacts
module: loading app debug_cmd.so
module: loading app menu.so
module: loading app syslog.so
Populated 19 audio codecs
Populated 0 audio filters
Populated 0 video codecs
Populated 0 video filters
baresip is ready.
266620@91.x.y.z: {0/UDP/v4} 200 OK () [1 binding]
All 1 useragent registered successfully! (35 ms)
ua: sipsess connect via UDP 91.x.y.z:5060 --> 192.168.8.198:40227
call: alloc with params laddr=192.168.8.198, af=AF_INET, use_rtp=1
call: use_video=0
answering call from sip:4050330@91.x.y.z with 200
call: update media
audio: Set audio decoder: L16 44100Hz 2ch
audio: start
alsa: reset: srate=44100, ch=2, num_frames=882, pcmfmt=S16_LE
alsa: playback started (out78)
audio: player started with sample format S16LE
audio: Set audio encoder: L16 44100Hz 2ch
audio: start
alsa: reset: srate=44100, ch=2, num_frames=882, pcmfmt=S16_LE
alsa: recording started (in78) format=S16LE
audio: source started with sample format S16LE
audio tx pipeline:        alsa ---> L16
audio rx pipeline:        alsa <--- L16
stream: incoming rtp for 'audio' established, receiving from 192.168.8.160:5004
call: stream start (active=1)
audio: start
266620@91.x.y.z: Call established: sip:4050330@91.x.y.z
sip:4050330@91.x.y.z: session closed: Connection reset by peer
alsa: stopping recording thread (in78)
alsa: stopping playback thread (out78)
sip:266620@84.x.y.z: Call with sip:4050330@91.x.y.z terminated (duration: 1 min 3 secs)
audio: destroyed (started=1)

audio           Transmit:     Receive:
packets:           3163         9963
avg. bitrate:    1409.3       1290.4  (kbit/s)
errors:               0            0
```

**Comment by alfredh** [comment]
thanks for the detailed info.

keep in mind that L16/44100/2 will generate very large packets and very high bitrate.

perhaps there is a network problem, either some packets are lost or
problems with IP-fragmentation of UDP packets ?

it would be nice to see the RTCP stats if there is any packet loss.

1. can you test with a lower sample-rate e.g. L16/8000/2

2. can you try to enable RTCP on the other UAs ?

3. during a call please press 'A' to see the audio debug.

also if you see the number of packets, it is around 3 times more
packets received than sent. these 2 numbers should be roughly equal.

**Comment by premultiply** [comment]
> perhaps there is a network problem, either some packets are lost or
> problems with IP-fragmentation of UDP packets ?

Yes, it looks like this may be the problem. I had a look with Wireshark at the traffic now.
Baresip sends large fragmented IP packets to his counterpart while the other UAs send out well sized single RTP packets. Other UAs than baresip may not be able to reassamble the RTP packets.
It seems that baresip always sends 20ms of sampled audio (ptime) at each packet whereas other UAs use lower intervals. At least they expect unfragmented RTP packets.

AVT MAGIC ACip3 (and others) @ L16/32000/2 sends out per 10ms of audio (1280 bytes / 320 samples) per packet. So at least ptime should be adjusted to 10 ms for stereo modes in baresip too.
20 ms is fine for mono.

By the way EBU Tech 3326 Chapter 3.1.4 (https://tech.ebu.ch/docs/tech/tech3326.pdf Chapter 3.1.4) recommends a fixed value of 4 ms for linear pcm audio. This would allow even higher bitdepths or multichannel PCM transmissions.

**Comment by alfredh** [comment]
the ptime can be configured per account:

```
#    ;ptime={10,20,30,40,...}
```

perhaps you can try to set a lower ptime (4ms or 10ms) and see if it works better
between baresip and your UAs.

**Comment by premultiply** [comment]
Yep, setting ;ptime=10 made L16 working in stereo to other UAs!
So RTP packet fragmentation is the core problem indeed.

I would suggest to auto adjust it dependent on user selected ptime value (or default) / channelcount / bitdepth (two bytes for L16).

**Comment by alfredh** [comment]
great,

I see that you have access to some nice hardware endpoints.

if you feel that they have a good interop with baresip, you are welcome to add
them to this wiki page:

https://github.com/alfredh/baresip/wiki/Interoperability

**Comment by premultiply** [comment]
Yes, would be no problem for me to add some interop tests ;-)

By the way ptime for L16/48000/2 should be 7.5ms as seen from my AVT device.
Setting it to only 4 ms has little sound issues.

**Comment by alfredh** [comment]
the ptime parameter is integer type, that is correct:

```c
	uint32_t ptime;              /**< Configured packet time in [ms]     */
```

**Comment by alfredh** [comment]
the packet time is normally an integer value from e.g. 5ms to 60ms

some audio filters and audio codecs require that the ptime (frame_size) is
divisible by e.g. 10ms or 20ms.

for example opus codec supports ptime between 2.5ms and 60ms

the receiver's ptime should not be necessary to configure; the receiver should be
flexible enough to receive any ptimes e.g. 5, 10, 20 etc. the received should also
handle that the incoming ptime changes dynamically (from e.g. 20ms to 40ms).

I had a look at adding RTP packetization for large audio frames, which is similar to
how it's done in ffmpeg's libavformat. in theory it should be possible to break up
packets of linear codecs such as PCMA, PCMU, L16. splitting packets of other
non-linear codecs such as opus is not possible.

in my test I split the packets on e.g. 1024 bytes which gives non-integer ptime value
that is not divible with e.g. 20. the receiver was not so happy to receive this and playout
noise or crackling sound.

so my conclusion is that is probably makes more sense to split the audio-frame instead,
by using a lower ptime that is still divisible by 20ms:

* 20ms
* 10ms
* 5ms
* 4ms

if your baresip is sending with ptime=5 and your receiver is not able to decode it
properly, that is most likely a bug in that receiver.

baresip has mostly manual configuration, and there is not so much logic for
auto-adjusting values such as ptime and bitrate etc.

the reason for this is that baresip is written for experts and we like to keep it
simple and predictable.

**Comment by premultiply** [comment]
> I had a look at adding RTP packetization for large audio frames, which is similar to
> how it's done in ffmpeg's libavformat. in theory it should be possible to break up
> packets of linear codecs such as PCMA, PCMU, L16. splitting packets of other
> non-linear codecs such as opus is not possible.

I think it has to be the next smaller ptime value (divisible by 20ms) whichs avoids packet fragmentation.
So maybe it would be best to add a default samples-per-packet value (=ptime) to the struct in L16.c for each format.

> so my conclusion is that is probably makes more sense to split the audio-frame instead,
> by using a lower ptime that is still divisible by 20ms:
> 
>     * 20ms
> 
>     * 10ms
> 
>     * 5ms
> 
>     * 4ms

I'll second that.

> if your baresip is sending with ptime=5 and your receiver is not able to decode it
> properly, that is most likely a bug in that receiver.

ptime=5 was ok in my tests. ptime=4 was not ok (for that tested decoder). Others may be ok.

> baresip has mostly manual configuration, and there is not so much logic for
> auto-adjusting values such as ptime and bitrate etc.

Maybe it would be best if baresip tries to match/adapt to the ptime value from SIP session (if availible and possible) or from its depacketizer/decoder assuming that this is what the peer would like to receive/can decode properly.

**Comment by alfredh** [comment]
the ptime attribute is read from the remote SDP:

https://github.com/alfredh/baresip/blob/master/src/audio.c#L2008

if the remote SDP contains this:

```
a=ptime:10.
```

then the Sender's packet-time will be adjusted to 10ms.

I am not sure if we should add packet-time parameter to the audio codecs (L16)
and adjust it automatically to those values. 

it would be interesting to look at the SIP and RTP traffic from your sessions
between baresip and your Endpoints. do you have any option to run ngrep/wireshark ?

for a start ngrep dump of the SIP signaling would be a good start.

**Comment by premultiply** [comment]
Ok, this is a first case where it works almost fine. L16/48000/2 call initiated by Orban Opticodec 7600 and auto-answered by baresip 0.6.2.
I think that there is just the small issue where baresip returns ptime=20 in "200 Answering" message but acutally uses (correct) ptime=4 as requested and used by the peer. TX and RX RTP packets have equal sizes.

```
Frame 7: 717 bytes on wire (5736 bits), 717 bytes captured (5736 bits) on interface 0
Ethernet II, Src: AvmAudio_30:e5:30 (cc:ce:1e:30:e5:30), Dst: IntelCor_4c:78:9d (00:1c:c0:4c:78:9d)
Internet Protocol Version 4, Src: ["OTHER CODEC IP"], Dst: ["BARESIP IP"]
User Datagram Protocol, Src Port: 5060, Dst Port: 54422
Session Initiation Protocol (INVITE)
    Request-Line: INVITE sip:266620-0x5629b3db9b00@["BARESIP IP"]:54422 SIP/2.0
        Method: INVITE
        Request-URI: sip:266620-0x5629b3db9b00@["BARESIP IP"]:54422
            Request-URI User Part: 266620-0x5629b3db9b00
            Request-URI Host Part: ["BARESIP IP"]
            Request-URI Host Port: 54422
        [Resent Packet: False]
    Message Header
        Via: SIP/2.0/UDP ["OTHER CODEC IP"]:5060;branch=z9hG4bK5b6e3n102g156110u500.1
            Transport: UDP
            Sent-by Address: ["OTHER CODEC IP"]
            Sent-by port: 5060
            Branch: z9hG4bK5b6e3n102g156110u500.1
        From: "OPTICODEC7600" <sip:266610@["OTHER CODEC IP"]>;tag=-AyOmLB7
            SIP Display info: "OPTICODEC7600"
            SIP from address: sip:266610@["OTHER CODEC IP"]
                SIP from address User Part: 266610
                SIP from address Host Part: ["OTHER CODEC IP"]
            SIP from tag: -AyOmLB7
        To: <sip:266620@["GATEWAY IP"]>
            SIP to address: sip:266620@["GATEWAY IP"]
                SIP to address User Part: 266620
                SIP to address Host Part: ["GATEWAY IP"]
        Call-ID: UseE8ci2nX-Uixq9
        CSeq: 12903 INVITE
            Sequence Number: 12903
            Method: INVITE
        Contact: <sip:266610@["OTHER CODEC IP"]:5060;transport=udp>
            Contact URI: sip:266610@["OTHER CODEC IP"]:5060;transport=udp
                Contact URI User Part: 266610
                Contact URI Host Part: ["OTHER CODEC IP"]
                Contact URI Host Port: 5060
                Contact URI parameter: transport=udp
        Max-Forwards: 66
        User-Agent: Opticodec7600/5.11.115
        Content-Type: application/sdp
        Allow: INVITE, ACK, CANCEL, BYE, OPTIONS
        Content-Length: 163
    Message Body
        Session Description Protocol
            Session Description Protocol Version (v): 0
            Owner/Creator, Session Id (o): OC7600 1628178839 1 IN IP4 ["OTHER CODEC IP"]
                Owner Username: OC7600
                Session ID: 1628178839
                Session Version: 1
                Owner Network Type: IN
                Owner Address Type: IP4
                Owner Address: ["OTHER CODEC IP"]
            Session Name (s): audio
            Connection Information (c): IN IP4 ["OTHER CODEC IP"]
                Connection Network Type: IN
                Connection Address Type: IP4
                Connection Address: ["OTHER CODEC IP"]
            Time Description, active time (t): 0 0
                Session Start Time: 0
                Session Stop Time: 0
            Media Description, name and address (m): audio 20340 RTP/AVP 96
                Media Type: audio
                Media Port: 20340
                Media Protocol: RTP/AVP
                Media Format: DynamicRTP-Type-96
            Media Attribute (a): rtpmap:96 L16/48000/2
                Media Attribute Fieldname: rtpmap
                Media Format: 96
                MIME Type: L16
                Sample Rate: 48000
            Media Attribute (a): ptime:4
                Media Attribute Fieldname: ptime
                Media Attribute Value: 4
            Media Attribute (a): sendrecv
```

```
Frame 8: 513 bytes on wire (4104 bits), 513 bytes captured (4104 bits) on interface 0
Ethernet II, Src: IntelCor_4c:78:9d (00:1c:c0:4c:78:9d), Dst: AvmAudio_30:e5:30 (cc:ce:1e:30:e5:30)
Internet Protocol Version 4, Src: ["BARESIP IP"], Dst: ["OTHER CODEC IP"]
User Datagram Protocol, Src Port: 54422, Dst Port: 5060
Session Initiation Protocol (180)
    Status-Line: SIP/2.0 180 Ringing
        Status-Code: 180
        [Resent Packet: False]
        [Request Frame: 7]
        [Response Time (ms): 0]
    Message Header
        Via: SIP/2.0/UDP ["OTHER CODEC IP"]:5060;branch=z9hG4bK5b6e3n102g156110u500.1
            Transport: UDP
            Sent-by Address: ["OTHER CODEC IP"]
            Sent-by port: 5060
            Branch: z9hG4bK5b6e3n102g156110u500.1
        From: "OPTICODEC7600" <sip:266610@["OTHER CODEC IP"]>;tag=-AyOmLB7
            SIP Display info: "OPTICODEC7600"
            SIP from address: sip:266610@["OTHER CODEC IP"]
                SIP from address User Part: 266610
                SIP from address Host Part: ["OTHER CODEC IP"]
            SIP from tag: -AyOmLB7
        To: <sip:266620@["GATEWAY IP"]>;tag=330531e32bf66bda
            SIP to address: sip:266620@["GATEWAY IP"]
                SIP to address User Part: 266620
                SIP to address Host Part: ["GATEWAY IP"]
            SIP to tag: 330531e32bf66bda
        Call-ID: UseE8ci2nX-Uixq9
        CSeq: 12903 INVITE
            Sequence Number: 12903
            Method: INVITE
        Server: baresip v0.6.2 (x86_64/linux)
        Contact: <sip:266620-0x5629b3db9b00@["BARESIP IP"]:54422>
            Contact URI: sip:266620-0x5629b3db9b00@["BARESIP IP"]:54422
                Contact URI User Part: 266620-0x5629b3db9b00
                Contact URI Host Part: ["BARESIP IP"]
                Contact URI Host Port: 54422
        Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER
        Content-Length: 0
```

```
Frame 10: 871 bytes on wire (6968 bits), 871 bytes captured (6968 bits) on interface 0
Ethernet II, Src: IntelCor_4c:78:9d (00:1c:c0:4c:78:9d), Dst: AvmAudio_30:e5:30 (cc:ce:1e:30:e5:30)
Internet Protocol Version 4, Src: ["BARESIP IP"], Dst: ["OTHER CODEC IP"]
User Datagram Protocol, Src Port: 54422, Dst Port: 5060
Session Initiation Protocol (200)
    Status-Line: SIP/2.0 200 Answering
        Status-Code: 200
        [Resent Packet: False]
        [Request Frame: 7]
        [Response Time (ms): 21]
    Message Header
        Via: SIP/2.0/UDP ["OTHER CODEC IP"]:5060;branch=z9hG4bK5b6e3n102g156110u500.1
            Transport: UDP
            Sent-by Address: ["OTHER CODEC IP"]
            Sent-by port: 5060
            Branch: z9hG4bK5b6e3n102g156110u500.1
        From: "OPTICODEC7600" <sip:266610@["OTHER CODEC IP"]>;tag=-AyOmLB7
            SIP Display info: "OPTICODEC7600"
            SIP from address: sip:266610@["OTHER CODEC IP"]
                SIP from address User Part: 266610
                SIP from address Host Part: ["OTHER CODEC IP"]
            SIP from tag: -AyOmLB7
        To: <sip:266620@["GATEWAY IP"]>;tag=330531e32bf66bda
            SIP to address: sip:266620@["GATEWAY IP"]
                SIP to address User Part: 266620
                SIP to address Host Part: ["GATEWAY IP"]
            SIP to tag: 330531e32bf66bda
        Call-ID: UseE8ci2nX-Uixq9
        CSeq: 12903 INVITE
            Sequence Number: 12903
            Method: INVITE
        Server: baresip v0.6.2 (x86_64/linux)
        Contact: <sip:266620-0x5629b3db9b00@["BARESIP IP"]:54422>
            Contact URI: sip:266620-0x5629b3db9b00@["BARESIP IP"]:54422
                Contact URI User Part: 266620-0x5629b3db9b00
                Contact URI Host Part: ["BARESIP IP"]
                Contact URI Host Port: 54422
        Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER
        Content-Type: application/sdp
        Content-Length: 323
    Message Body
        Session Description Protocol
            Session Description Protocol Version (v): 0
            Owner/Creator, Session Id (o): - 109371034 344783500 IN IP4 ["BARESIP IP"]
                Owner Username: -
                Session ID: 109371034
                Session Version: 344783500
                Owner Network Type: IN
                Owner Address Type: IP4
                Owner Address: ["BARESIP IP"]
            Session Name (s): -
            Connection Information (c): IN IP4 ["BARESIP IP"]
                Connection Network Type: IN
                Connection Address Type: IP4
                Connection Address: ["BARESIP IP"]
            Time Description, active time (t): 0 0
                Session Start Time: 0
                Session Stop Time: 0
            Session Attribute (a): tool:baresip 0.6.2
                Session Attribute Fieldname: tool
                Session Attribute Value: baresip 0.6.2
            Media Description, name and address (m): audio 15916 RTP/AVP 96
                Media Type: audio
                Media Port: 15916
                Media Protocol: RTP/AVP
                Media Format: DynamicRTP-Type-96
            Media Attribute (a): rtpmap:96 L16/48000/2
                Media Attribute Fieldname: rtpmap
                Media Format: 96
                MIME Type: L16
                Sample Rate: 48000
            Media Attribute (a): sendrecv
            Media Attribute (a): label:1
                Media Attribute Fieldname: label
                Media Attribute Value: 1
            Media Attribute (a): rtcp-rsize
            Media Attribute (a): ssrc:302566108 cname:sip:266620@["GATEWAY IP"]
                Media Attribute Fieldname: ssrc
                Media Attribute Value: 302566108 cname:sip:266620@["GATEWAY IP"]
            Media Attribute (a): ptime:20
                Media Attribute Fieldname: ptime
                Media Attribute Value: 20
            Media Attribute (a): ebuacip:version 0
                Media Attribute Fieldname: ebuacip
                Media Attribute Value: version 0
            Media Attribute (a): ebuacip:jb 0
                Media Attribute Fieldname: ebuacip
                Media Attribute Value: jb 0
            Media Attribute (a): ebuacip:qosrec 46
                Media Attribute Fieldname: ebuacip
                Media Attribute Value: qosrec 46
```

```
Frame 32: 494 bytes on wire (3952 bits), 494 bytes captured (3952 bits) on interface 0
Ethernet II, Src: AvmAudio_30:e5:30 (cc:ce:1e:30:e5:30), Dst: IntelCor_4c:78:9d (00:1c:c0:4c:78:9d)
Internet Protocol Version 4, Src: ["OTHER CODEC IP"], Dst: ["BARESIP IP"]
User Datagram Protocol, Src Port: 5060, Dst Port: 54422
Session Initiation Protocol (ACK)
    Request-Line: ACK sip:266620-0x5629b3db9b00@["BARESIP IP"]:54422 SIP/2.0
        Method: ACK
        Request-URI: sip:266620-0x5629b3db9b00@["BARESIP IP"]:54422
            Request-URI User Part: 266620-0x5629b3db9b00
            Request-URI Host Part: ["BARESIP IP"]
            Request-URI Host Port: 54422
        [Resent Packet: False]
        [Request Frame: 7]
        [Response Time (ms): 97]
    Message Header
        Via: SIP/2.0/UDP ["OTHER CODEC IP"]:5060;branch=z9hG4bK9jqv3v304o1gj6lgc700.1
            Transport: UDP
            Sent-by Address: ["OTHER CODEC IP"]
            Sent-by port: 5060
            Branch: z9hG4bK9jqv3v304o1gj6lgc700.1
        From: "OPTICODEC7600" <sip:266610@["OTHER CODEC IP"]>;tag=-AyOmLB7
            SIP Display info: "OPTICODEC7600"
            SIP from address: sip:266610@["OTHER CODEC IP"]
                SIP from address User Part: 266610
                SIP from address Host Part: ["OTHER CODEC IP"]
            SIP from tag: -AyOmLB7
        To: <sip:266620@["GATEWAY IP"]>;tag=330531e32bf66bda
            SIP to address: sip:266620@["GATEWAY IP"]
                SIP to address User Part: 266620
                SIP to address Host Part: ["GATEWAY IP"]
            SIP to tag: 330531e32bf66bda
        Call-ID: UseE8ci2nX-Uixq9
        CSeq: 12903 ACK
            Sequence Number: 12903
            Method: ACK
        Contact: <sip:266610@["OTHER CODEC IP"]:5060;transport=udp>
            Contact URI: sip:266610@["OTHER CODEC IP"]:5060;transport=udp
                Contact URI User Part: 266610
                Contact URI Host Part: ["OTHER CODEC IP"]
                Contact URI Host Port: 5060
                Contact URI parameter: transport=udp
        Max-Forwards: 66
        User-Agent: Opticodec7600/5.11.115
        Content-Length: 0
```

**Comment by alfredh** [comment]
thanks for the update, your feedback is very helpful.

please test this patch:

https://github.com/alfredh/baresip/commit/af77e7e37a4332529bc4fdf3ed77f843e5347e3c


it will mirror the ptime from the incoming ptime:

SDP Offer:
```
a=ptime:10
```

SDP Answer:
```
a=ptime:10
```

we should also add a check that the ptime is within a sane range (e.g. 1ms - 60ms).

**Comment by premultiply** [comment]
Yes I can test it tomorrow.

Today I've done may interoperability tests between all my devices (including baresip).
And I can summarize that the main issues between all of them are as follows:

1. None of them (ok, excluding baresip) likes or accepts fragmented RTP packets at all. -> So this should be avoided where ever possible.
2. Too small/to many packets per time may lead to audio quality problems on most decoders (IO or CPU load?, time based jitter buffer management?) -> Packets should always be as large as possible with respect to the specific codec, application and network constraints.
3. Most of them do not send or respect ptime indication in SIP dialog. Most of them use fixed/predefined and mostly unconfigurable sizes for outgoing packets
4. Baresips ptime parameter in accounts configuration affects at least three different things at the same time which should have individual configuration settings (1. Recomended/whished ptime for received stream sent as SIP property during INVITE; 2. actual fix encoded packet time if not overwritten/adapted to by received ptime SIP property; 3. Seems to have influence at least on decoding MPA but I have to doublecheck that)
5. None of them can decode MPA Layer 3 from baresip. Something seems to be broken in the bitstream. -> I will create a new issue for that.

So setting a the existing ptime option in accounts may only be a workaround for avoiding packet fragmentation when fixed (L16) encodings and parameterization are transmitted and received.
But that is unrealistic when you try to connect with many different UAs for different applications.
Even only autoanswer (dial-in) will have issues with that as you do not know who is connecting with which codec parameterization.

I would recommend to add a new option to baresip configuration (or accounts) to set the **maximum** allowed outgoing packet time. Packets may be shorter if codec constraints a fixed frame size (or an integer number of frames) in a packet or the resulting timespan is to long to store all associated data into a single packet (primarily L16 case). The current ptime option should only set the according ptime metadata in outgoing SIP INVITE (calling other UA from baresip) but nothing else.

And last but not least: Baresips decoding interoperability is very good already! :-)

**Comment by premultiply** [comment]
https://github.com/alfredh/baresip/commit/af77e7e37a4332529bc4fdf3ed77f843e5347e3c#commitcomment-33291311

**Comment by alfredh** [comment]
RFC 4566 defines maxptime:

```
a=maxptime:<maximum packet time>

         This gives the maximum amount of media that can be encapsulated
         in each packet, expressed as time in milliseconds.  The time
         SHALL be calculated as the sum of the time the media present in
         the packet represents.  For frame-based codecs, the time SHOULD
         be an integer multiple of the frame size.  This attribute is
         probably only meaningful for audio data, but may be used with
         other media types if it makes sense.  It is a media-level
         attribute, and it is not dependent on charset.  Note that this
         attribute was introduced after RFC 2327, and non-updated
         implementations will ignore this attribute.
```

should we add this SDP attribute ?


we can also add a config for maximum packet size for outgoing packets,
that is close to or a bit less than MTU (e.g. 1480). if we want to have it
flexible we can have it different for audio and video.

```
audio_max_payload_size    1480
video_max_payload_size    1480
```

**Comment by premultiply** [comment]
It sounds reasonable to me. The max_payload_size is the most imporant I think.
Maybe it is even possible to make it have an "auto" setting where it automatically monitors, adapts and reflects the maximum incoming payload size (or to an incoming maxptime attribute if availible) of a session.
An outgoing maxptime attribute may be more or less cosmetic to most UAs.

**Comment by alfredh** [comment]
I suggest we add this item on the Roadmap for now.

I have many features to implement and limited time.

We can summarize the feature as follows:

* Add a configuration item for maximum outgoing audio/video packet size
* Adjust sending ptime automatically depending on codecs used and MTU.

**Comment by alfredh** [comment]
I have added the item to the roadmap:

https://github.com/alfredh/baresip/wiki/Roadmap
