### ISSUE TITLE
VIA port does not match connection port for TCP connections

### ISSUE THREAD

**Issue by gitkoyot** [alfredh/baresip#690]
Hello,
I have one account:
<sip:caller-baresip@172.20.0.3:5060>;regint=0;transport=tcp

I have UAS at 172.20.0.3 listening on tcp and udp.
When I try to dial: sip:caller-baresip@172.20.0.3:5060;transport=tcp
baresip 0.6.1 generates following invite:

T 2019/04/16 08:51:04.166473 172.20.0.2:46384 -> 172.20.0.3:5060 [AP] #27
INVITE sip:caller-baresip@172.20.0.3:5060;transport=tcp SIP/2.0.
Via: SIP/2.0/TCP 172.20.0.2:45533;branch=z9hG4bK381e33b5a4aab814;rport.
Contact: <sip:caller-baresip-0x5620d7c4dda0@172.20.0.2:45533;transport=tcp>.
Max-Forwards: 70.

Via port (45533) does not match connection port (46384)

root@ee61bf99421a:/# netstat -ntp; netstat -nltp
..
tcp        0      0 172.20.0.2:46384        172.20.0.3:5060         ESTABLISHED 433/baresip         
...
tcp        0      0 127.0.0.11:37751        0.0.0.0:*               LISTEN      -                   
tcp        0      0 172.20.0.2:34905        0.0.0.0:*               LISTEN      433/baresip         
tcp        0      0 172.20.0.2:45533        0.0.0.0:*               LISTEN      433/baresip

UAS via ip/port to reach baresip and  has to call back at 172.20.0.2:45533. Instead of one connection per call it uses two.

I checed for UDP and VIA ip/port matches UDP packet.

Is this misconfiguration of some sort on my part or is this behavior expected ? 

Thanks for any hint

**Comment by alfredh** [comment]
the port number in the Contact header is the port number for the listening
TCP socket, used for inbound connections.

this is according to RFC 3261.

if you want to use the same TCP connection from client to server for all
SIP messages, you should enable SIP outbound:

`;sipnat=outbound`

**Comment by sbourji** [comment]
I tried your suggestion, but it does not seems to work, when I look Wireshark
Transmission Control Protocol, src Port: 51079, Dat port: 5060, Seq 1, Ack: 1, Len: 837
Session Initiation Protocol **(REGISTER)**
- Request-Line:REGISTER sip:specter.canjalil.com;sipnat=outbound;transport=tcp SIP2/2.0
- Via: SIP2/2.0/TCP 192.168.87.142:51075; branch=z9hG4bK7756cfeb1b2059a8;rport
- Contact: <sip:1003-0x10339f300@192.168.87.142:51057;transport=tcp>
