### ISSUE TITLE
how to enable ipv6?

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#693]
I have built re, rem and baresip debian packages with this kind of debian rules entry:
```
build-stamp: configure-stamp 
	dh_testdir
	$(MAKE) RELEASE=1 HAVE_INET6=1  ...
```
Still, when I try to start baresip with account that has
```
;outbound="sip:[fe80::6e29:95ff:fe7d:37e6]:5060;transport=udp"
```
I get error message
```
test@test.tutpro.com: Using sipnat: `outbound'
ua: SIP register failed: Protocol not supported
account: failed to register ua 'sip:test@test.tutpro.com' (Protocol not supported)
```
baresip netinfo shows:
```
--- Network debug ---
 Preferred AF:  AF_INET6
 Local IPv4:    wlp1s0 - 192.168.43.98
 Local IPv6:           - ::
 Domain: 
net interfaces:
         lo:  127.0.0.1
     wlp1s0:  192.168.43.98
         lo:  ::1
     wlp1s0:  fe80::6e29:95ff:fe7d:37e6
net routes:
 Destination                                 Next Hop                                 Iface           Type
 0.0.0.0/0                                   192.168.43.230                           wlp1s0          
 192.168.43.0/24                             ?                                        wlp1s0          
 fe80::/64                                   ?                                        wlp1s0           LINKLOCAL
 DNS Servers from System: (1)
   0: 192.168.43.230:53
```
Why there is no Local IPv6 address?  Any ideas what goes wrong and how to fix it?

**Comment by alfredh** [comment]
I installed the miredo package on Debian which gives you a global IPv6 address:

```
teredo: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1280
        inet6 2001:0:53aa:64c:10ae:7945:ab2f:c2db  prefixlen 32  scopeid 0x0<global>
        inet6 fe80::ffff:ffff:ffff  prefixlen 64  scopeid 0x20<link>
        inet6 fe80::b29d:89b7:5f3a:ddb8  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6  bytes 288 (288.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

```
transports:
  10.0.1.2:33177 (UDP)
  10.0.1.2:45769 (TCP)
  10.0.1.2:42023 (TLS)
  [2001:0:53aa:64c:10ae:7945:ab2f:c2db]:47206 (UDP)
  [2001:0:53aa:64c:10ae:7945:ab2f:c2db]:38885 (TCP)
  [2001:0:53aa:64c:10ae:7945:ab2f:c2db]:33991 (TLS)
client transactions:
server transactions:
--- Network debug ---
 Preferred AF:  AF_INET
 Local IPv4:    enp2s0 - 10.0.1.2
 Local IPv6:    teredo - 2001:0:53aa:64c:10ae:7945:ab2f:c2db
 Domain: getinternet.no
net interfaces:
         lo:  127.0.0.1
     enp2s0:  10.0.1.2
         lo:  ::1
     enp2s0:  fe80::d63d:7eff:fef1:3048
     teredo:  2001:0:53aa:64c:10ae:7945:ab2f:c2db
     teredo:  fe80::ffff:ffff:ffff
     teredo:  fe80::b29d:89b7:5f3a:ddb8
net routes:
 Destination                                 Next Hop                                 Iface           Type
 0.0.0.0/0                                   10.0.1.1                                 enp2s0          
 10.0.1.0/24                                 ?                                        enp2s0          
 ::1/128                                     ?                                        lo              
 2001::/32                                   ?                                        teredo          
 fe80::/64                                   ?                                        enp2s0           LINKLOCAL
 fe80::/64                                   ?                                        teredo           LINKLOCAL
 DNS Servers from System: (1)
   0: 10.0.1.1:53
```

your IPv6 address (fe80::xxx) is a link-local address which is not globally routable.

the function that tries to determine the default IPv6 address will exclude loopback
address and link-local address.

link-local address is only useful for local testing, and is not working properly as you
have to include the name of the interface in the address. I would strongly recommend
to use a global IPv6 address instead.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> your IPv6 address (fe80::xxx) is a link-local address which is not
> globally routable.

I know.  My Linux host and Android phone are both connected to a wifi
hotspot provided by another Android phone.  The wifi hotspot only
provides link local IPv9 addresses to its clients.

> the function that tries to determine the default IPv6 address will
> exclude loopback address and link-local address.

> link-local address is only useful for local testing, and is not
> working properly as you  have to include the name of the interface in
> the address. I would strongly recommend to use a global IPv6 address
> instead.

I would prefer not to exclude link local addresses.  It is not a problem
for me to include the link (interface) in the IPv6 address, for example,
[fe80::6e29:95ff:fe7d:37e6%wlp1s0].  From that the link can be assigned
to sin6_scope_id, e.g., like this:

  addr->sin6.sin6_scope_id = if_nametoindex("wlp1s0");

**Comment by juha-h** [comment]
Package miredo can solve link local address problem in Debian, but how
can I get my Android baresip to use link local IPv6 address if that is
the only address my Android phone gets from Wifi hotspot?

**Comment by alfredh** [comment]
I dont think that libre supports parsing of link-local addresses with % interface.
adding support for it will be quite a lot of work I think.

there are probably Android apps that can give you global IPv6 address,
either natively or via tunelling.

here is one:

https://github.com/yingted/MireDroid

BTW: is there IPv6 connectivity from your WiFi hotspot to the public IPv6 internet ?
or does it have support for NAT64 / DNS64 ? in other words, can you run this
command on your linux box:

```
$ ping6 www.google.com
```

**Comment by juha-h** [comment]
The answer to this question shows how to get interface name of an
IPv6 address:

https://stackoverflow.com/questions/13504934/binding-sockets-to-ipv6-addresses

If that kind of function is used, user does not have to give interface
name of link local IPv6 address.

Without support of link local IPv6 addresses, I cannot figure out, how
my Android baresip app can work in a very common hotspot scenario.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I dont think that libre supports parsing of link-local addresses with
> % interface. adding support for it will be quite a lot of work I
> think.

It would be easier to use function similar to getScopeForIp of the
stackoverflow answer.  It is also a more practical solution, since it is
not possible to ask an average Android user to figure out the name of
the link local interface.

> BTW: is there IPv6 connectivity from your WiFi hotspot to the public
> IPv6 internet ?
> or does it have support for NAT64 / DNS64 ? in other words, can you run this
> command on your linux box:
> 
> ```
> $ ping6 www.google.com
> ```

I can run, but I get "connect: Network is unreachable".  I may not have
the same IPv6 environment than the user who asked for IPv6 support to my
Android baresip app.  In that environment the device only gets a link
local IPv6 address from the hotspot and the hotspot then maps that to a
global IPv6 address.

**Comment by juha-h** [comment]
Baresip works fine on Linux using link local IPv6 address with the
following very simple re patch:

```
diff --git a/src/net/if.c b/src/net/if.c
index ed99cbf..08f5fec 100644
--- a/src/net/if.c
+++ b/src/net/if.c
@@ -14,6 +14,8 @@
 #define DEBUG_LEVEL 5
 #include <re_dbg.h>
 
+#include <net/if.h>
+
 
 /** Interface address entry */
 struct ifentry {
@@ -86,8 +88,8 @@ static bool if_getaddr_handler(const char *ifname,
 		return false;
 
 #if 1
-	/* skip loopback and link-local IP */
-	if (sa_is_loopback(sa) || sa_is_linklocal(sa))
+	/* skip loopback IP */
+	if (sa_is_loopback(sa))
 		return false;
 #endif
 
@@ -99,6 +101,12 @@ static bool if_getaddr_handler(const char *ifname,
 	sa_cpy(ife->ip, sa);
 	ife->found = true;
 
+#ifdef HAVE_INET6
+	/* Assign IPv6 link local address scope id */
+	if (sa_is_linklocal(sa))
+		ife->ip->u.in6.sin6_scope_id = if_nametoindex(ifname);
+#endif
+
 	return ife->found;
 }
 
```

Is there any chance that such a pull request would be accepted?

**Comment by juha-h** [comment]
I created re pull request https://github.com/creytiv/re/pull/203.
