### ISSUE TITLE
Baresip behind NAT - no keepalives from

### ISSUE THREAD

**Issue by bambucha1** [alfredh/baresip#696]
Hi @alfredh,

I'm trying to use baresip behind NAT. 
Here is my account settings :

`<sip:1101@x.x.x.x:9998>;answermode=manual;auth_pass=yyyyyyy;video_codecs=h264;sipnat=outbound;outbound="sip:x.x.x.x:9998;transport=udp"`

Session established successfully :

user@host:/opt/sess/baresip$ baresip -f /opt/sess/baresip -v
baresip v0.6.1 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.
Local network address:  IPv4=eth0:192.168.1.2 
ui: stdio
cons: UI console listening on 0.0.0.0:5555
ui: cons
ui: http
httpd: listening on 0.0.0.0:8000
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
aufilt: sndfile
sndfile: saving files in /opt/sess/baresip/snd
auplay: pulse
ausrc: pulse
vidsrc: avformat
vidsrc: nullvideo
vidisp: nullvideo
vidcodec: H264
gst_video: using gstreamer (GStreamer 1.10.4)
medianat: stun
uuid: loaded UUID 33e2852e-0cd4-5e3c-7694-2ea0f5a954fd from file /opt/sess/baresip/uuid
using stunserver: stun:x.x.x.x
1101@x.x.x.x: Using medianat stun
Populated 1 account
module: loading app auloop.so
module: loading app contact.so
Populated 0 contacts
module: loading app menu.so
module: loading app vidloop.so
Populated 2 audio codecs
Populated 2 audio filters
Populated 1 video codec
Populated 0 video filters
baresip is ready.
ua: incoming OPTIONS message from sip:asterisk@x.x.x.x:9998 (x.x.x.x:9998)
call: alloc with params laddr=192.168.1.2, af=AF_INET, use_rtp=0
call: use_video=1
video: stopping video source ..
audio: destroyed (started=0)
1101@x.x.x.x: {0/UDP/v4} 200 OK (Asterisk PBX 13.18.3~dfsg-1ubuntu4) [1 binding]
All 1 useragent registered successfully! (145 ms)

But there is no any periodical keep-alives from baresip (tested via TCPDUMP), therefore a couple of seconds NAT closes incoming connections to external port and I loose connection with Asterisk.

How to enable keep-alives and how to set interval for them?

x.x.x.x:9998 - external IP of Asterisk server (running on 9998 port)
x,x,x,x - the same server with restund service started.

Thanks a lot!

**Comment by GGGO** [comment]
I think your Asterisk server does not support sip outbound (RFC 5626).
Your registrar must reply with these headers:
```
Supported: path, outbound
Require: outbound
```

**Comment by bambucha1** [comment]
Thanks, with these options enabled on Asterisk it's OK.
