### ISSUE TITLE
Question : how to use custom gstreamer graph as video source?

### ISSUE THREAD

**Issue by bambucha1** [alfredh/baresip#697]
Hi @alfredh ,

I'm trying to build a video intercom based on IP camera, baresip SIP client and asterisk server.
Stream from IP camera can be proceeded by GStreamer with graph:

`rtspsrc name=rtspsrc latency=0 tcp-timeout=2000000 is-live=TRUE location="rtsp://admin:admin@192.168.1.3/Streaming/Channels/102" ! progressreport update-freq=60 do-query=true ! rtph264depay name=depay !  video/x-h264,stream-format=byte-stream,profile=baseline,alignment=nal !  appsink name=sink`

Output sink contains H264 payload with suitable bitrate/framerate (setings at WEB interface of camera). I need to have a video call with "sendonly" flag in SDP for video RTP and origin stream from sink without any re-encoding (just only encapsulating to RTP protocol) from baresip. 

Is it possible to do?  

Thanks a lot!

**Comment by alfredh** [comment]
Hi,

there is a gstreamer module for video encoding:

https://github.com/alfredh/baresip/tree/master/modules/gst_video1

this module takes the input frame from inside the baresip stack,
and encodes it using gstreamer.

so it is most likely not possible to do what you suggest, unless you do some hacking.

the `avformat.so` module can take an RTSP source via network and use it as a
video source device, the module will also decode the incoming video stream.
baresip will re-encode the video stream to the video codec selected via the
SDP negotiation to the peer. (i.e. transcoding).
