### ISSUE TITLE
MPA Layer III has wrong frame header

### ISSUE THREAD

**Issue by premultiply** [alfredh/baresip#699]
During interop-tests with my devices I wondered why none of them is able to decode baresips Layer III MPEG Audio.

Now I found out that at least the MPEG frame headers of baresips RTP stream are wrong.
Where it should be set to "Layer 3" the header is indicating "Layer 2" (and the bitrate for Layer 2):

![grafik](https://user-images.githubusercontent.com/4681172/56664668-cc525f00-66a8-11e9-9fb9-bed5ce3fe7ff.png)

And the bitwise compare between baresips frame headers and one of my devices:
![l3header](https://user-images.githubusercontent.com/4681172/56664066-bb551e00-66a7-11e9-845b-722514bb1b96.png)

The "Original Flag" should not be set either.

Tested format above was MPEG1 L3 128kbit/s 48k stereo but none of the L3 encodings can be decoded by other UAs.

**Comment by alfredh** [comment]
@hoene do you have the same results in your testing ?

**Comment by premultiply** [comment]
As I saw now that TwoLAME is used for encoding, correct?
But TwoLAME is layer 2 only...

My theory:
baresip decodes layer 3 and indicates on SIP/SDP that it will transmit layer 3 too but transmits layer 2.

**Comment by hoene** [comment]
I did tests only with MP2.

**Comment by hoene** [comment]
Now that the MP3 patents have phased out, we could use a library to support MP3.

**Comment by premultiply** [comment]
Maybe libmp3lame?

**Comment by alfredh** [comment]
can you try to add this line to your config:

```
mpa_layer               2
```

the MPA codec allows all layers (1, 2 or 3).

so I think the MPA module is correctly implemented, even if it is using
layer 2 (TwoLame).

my SDP contains this:

```
m=audio 4038 RTP/AVP 14
a=rtpmap:14 MPA/90000.
a=fmtp:14 layer=2.
```

**Comment by premultiply** [comment]
Yes, I've already done this as workaround.
It is just the missing support for Layer 3 encoding.

**Comment by hoene** [comment]
ok, @premultiply  if you could help to test it, this would be great.

**Comment by premultiply** [comment]
No problem.

**Comment by alfredh** [comment]
the item is on the Roadmap for now:

https://github.com/alfredh/baresip/wiki/Roadmap

a tested patch is welcome :)

**Comment by premultiply** [comment]
#797
