### ISSUE TITLE
Switch audio-device

### ISSUE THREAD

**Issue by AlexMarlo** [alfredh/baresip#70]
I used this feature to switch device on call in other software, so it will be good to have this in baresip

And it will be great if you show me where to looks for this  in the code.

**Comment by alfredh** [comment]
what kind of "device" are you looking to switch? Audio-device, interface-device ?

**Comment by AlexMarlo** [comment]
audio device

**Comment by alfredh** [comment]
the code for setting/changing audio-device can be found in audio.c,
look for ausrc_alloc and auplay_alloc:

https://github.com/alfredh/baresip/blob/master/src/audio.c#L1032


can you please describe your desired behaviour of switch audio-device?

- are you using baresip program, do you want to update config and update audio-device ?
- are you using libbaresip as a library, do you need exposed functions to set audio dev ?
- do you need to switch input-device, output-device, or both ?

**Comment by AlexMarlo** [comment]
we have big project which is using freeswitch, for voip we used freeswitch module pa  and know we moved to baresip, in pa module we had functionality to change audio in/output device in eny moment, even during call

so we hope to see the same in baresip

**Comment by alfredh** [comment]
the new API looks like this:

```
int  audio_set_source(struct audio *au, const char *mod, const char *device);
int  audio_set_player(struct audio *au, const char *mod, const char *device);
```

please try it out :)
