### ISSUE TITLE
Regular RTP stats

### ISSUE THREAD

**Issue by snblitz** [alfredh/baresip#706]
Can I get regular RTP stats like
RTP statistics: RTT=55 ms, packet loss=1.0%, jitter RX/TX=7/8 ms
from somewhere in the library?
Maybe every 10 seconds or so?

**Comment by GGGO** [comment]
Hi,
without using a timer of 10s, you could register an event handler with 
`int err = uag_event_register(ua_event_handler, NULL);`
and in ua_event_handler function, listen for UA_EVENT_CALL_RTCP.
To read the stats, see src/event.c.

If you really want to print the stats at a specific interval, use `tmr_start` to call `printRtcpSummaryLine` (see modules/rtcpsummary/rtcpsummary.c)

**Comment by snblitz** [comment]
I will give this a try and report back.

**Comment by alfredh** [comment]
you can use this function to get the last RTCP statistics:

```c
const struct rtcp_stats *stream_rtcp_stats(const struct stream *strm);
```

and the struct looks like this:

```c
/** RTCP Statistics */
struct rtcp_stats {
	struct {
		uint32_t sent;  /**< Tx RTP Packets                  */
		int lost;       /**< Tx RTP Packets Lost             */
		uint32_t jit;   /**< Tx Inter-arrival Jitter in [us] */
	} tx;
	struct {
		uint32_t sent;  /**< Rx RTP Packets                  */
		int lost;       /**< Rx RTP Packets Lost             */
		uint32_t jit;   /**< Rx Inter-Arrival Jitter in [us] */
	} rx;
	uint32_t rtt;           /**< Current Round-Trip Time in [us] */
};
```

**Comment by snblitz** [comment]
I combined GGGO and alfredh answers and am happily printing the stats from the rtcp_stats structure.
