### ISSUE TITLE
How to propagate expected packet loss to OPUS encoder?

### ISSUE THREAD

**Issue by f-squirrel** [alfredh/baresip#708]
According to [OPUS documentation](https://wiki.xiph.org/index.php?title=OpusFAQ&mobileaction=toggle_view_desktop#Forward_Error_correction_.28FEC.29_doesn.27t_appear_to_do_anything.21_HELP.21) FEC is only used by the encoder:

- the feature must be enabled via the OPUS_SET_INBAND_FEC CTL(which baresip does)
- the encoder must be told to expect loss via the OPUS_SET_PACKET_LOSS_PERC CTL(which baresip does not)

Does baresip have a possibility to update OPUS encoder with a number of lost packets dynamically?

**Comment by snblitz** [comment]
It looks like OPUS_SET_PACKET_LOSS_PERC is never called at all.

**Comment by tonylangley** [comment]
I did have a good look around the implementation when I was adding multistream capability and that’s my recollection too.

In fact here’s a post I wrote up...
https://github.com/alfredh/baresip/issues/237

It would be great if this control were fully implemented but I’m not sure exactly what would need to be modified to make this work.

From my experience the current jitter buffer in baresip needs some attention.

**Comment by snblitz** [comment]
As alfredh mentioned in #237 the work is really in the testing rather than the implementation.
I cobbled together support for OPUS_SET_PACKET_LOSS_PERC in https://github.com/snblitz/baresip
However, i did run into some stuff that confused me.  I decided, at least for now, to force the opus encoder to listen to the "my side" configuration and ignore the opus related inband configuration coming from the other side.

**Comment by f-squirrel** [comment]
@snblitz , did you manage to see FEC packets in your traffic after the change?

**Comment by f-squirrel** [comment]
So, I've enabled inband fec on both sides and set the expected packet loss to 50%.
Then I've simulated packet loss with ```tc qdisc add dev eth0 root netem loss 20%```.
The sound quality is the same with and without inband fec.
Any ideas?

P.S. Frame duration is more than 10ms.

**Comment by alfredh** [comment]
the audio encoder api looks like this:


```c
/** Audio Codec parameters */
struct auenc_param {
	uint32_t ptime;    /**< Packet time in [ms]       */
	uint32_t bitrate;  /**< Wanted bitrate in [bit/s] */
};

struct auenc_state;
struct audec_state;
struct aucodec;

typedef int (auenc_update_h)(struct auenc_state **aesp,
			     const struct aucodec *ac,
			     struct auenc_param *prm, const char *fmtp);
typedef int (auenc_encode_h)(struct auenc_state *aes,
			     uint8_t *buf, size_t *len,
			     int fmt, const void *sampv, size_t sampc);
```

so there is no way to configure the expected packet loss.


it is probably better to fix this in the opus module,
and set `OPUS_SET_PACKET_LOSS_PERC` to a sane value (5% - 10%)
in case FEC is enabled.

you can also add an opus config item in case you want to control it.

**Comment by alfredh** [comment]
please notice that a patch/PR is welcome if you want to create it and test it.

for now I am closing the issue, as it is not a defect.

you can also add the feature to the Roadmap if you wish.

**Comment by f-squirrel** [comment]
@alfredh , thank you I see it is quite complicated.
I've added the config to opus setting packet loss to a non-zero value but I still see no difference in sound quality. So I don't think I'm ready to create a patch...
