### ISSUE TITLE
Websocket Support

### ISSUE THREAD

**Issue by moradec** [alfredh/baresip#709]
I have patched "re" and rebuilt "re" and "baresip" in order to use SIP over websockets.

My account in the accounts-file for testing is something like:
`<sip:my_user@my.gateway.com:443;transport=wss>;auth_pass=my_pass`

On every registration attempt, i get the following log output:
```
BSIP_WRAPPER: ua event (REGISTERING) 
BSIP_WRAPPER: sending ua/call 497890144272/0 event registering
BSIP_WRAPPER: ua: SIP register failed: Protocol not supported
BSIP_WRAPPER: ua event (REGISTER_FAIL) Protocol not supported
BSIP_WRAPPER: sending ua/call 497890144272/0 event registering failed,Protocol not supported
```

As mentioned in another thread, "baresip" needs to be patched also. Does the following branch still exist, or is there a patch for "baresip" too?
`https://github.com/alfredh/baresip/tree/sip_websock`

Maybe i do something wrong?

It would be more than great getting this feature working :)

BR
Andreas

**Comment by alfredh** [comment]
SIP over Websocket was an experimental patch written some time ago.

it is currently not supported in baresip/libre master.

yes, there are also a couple of things you need to do in baresip,
for example add the WS transport using:

```c
int  sip_transp_add_websock(struct sip *sip, enum sip_transp tp,
			    const struct sa *laddr,
			    bool server, const char *cert);
```

look for `sip_transp_add` in ua.c:

```c
	if (uag.use_udp)
		err |= sip_transp_add(uag.sip, SIP_TRANSP_UDP, &local);
	if (uag.use_tcp)
		err |= sip_transp_add(uag.sip, SIP_TRANSP_TCP, &local);
```

This feature is already on the roadmap:

https://github.com/alfredh/baresip/wiki/Roadmap#signaling

**Comment by alfredh** [comment]
please note that this Issue tracker is mainly used for bugs and defects.

for other things like new features and questions, please use the re-devel
mailing list:

http://lists.creytiv.com/mailman/listinfo/re-devel
