### ISSUE TITLE
Does Baresip/Libre run on Apple arm64?

### ISSUE THREAD

**Issue by tahahajar** [alfredh/baresip#71]
Hi there,

I am trying to do sip registration on an iOS app using libre. I compiled the library to run on the following architectures: i386, armv7 and aarch64 (arm64).  The app is built successfully on all architectures, and it does the sip registration on i386 (iphone simulator) and armv7. However, on arm64 everything runs normally until the line where the register sip packet should be sent it executes the statement but I don't see anything on wireshark and it waits for a reply but it gets nothing so an operation time out error appears. Has anyone tried running baresip or libre on an arm64 (iphone 5s, iphone 6 or iphone 6 plus)? 

Thanks,
Taha

**Comment by alfredh** [comment]
baresip/libre should work fine on ARM64 and also iOS arm64.

it would be interesting to see how your project is compiled, and which options are used etc.
Did you try the baresip-ios project:

https://github.com/alfredh/baresip-ios

let us try to make a simple network program work on iOS first. Can you try to make a simple
program that sends out an TCP/UDP packet ?

you can also try the retest program and report which testcases are working/failing:

http://www.creytiv.com/pub/retest-0.4.2.tar.gz

**Comment by alfredh** [comment]
closing due to lack of response
