### ISSUE TITLE
File descriptor handler set method doesn't work on Windows

### ISSUE THREAD

**Issue by ericmjones** [alfredh/baresip#711]
Latest baresip version.

On Windows the FD of the socket is essentially a random value, so it cannot be used as the index into re->fhs as it is on other platforms.

See issue: https://github.com/alfredh/baresip/issues/156

Although the code doesn't segfault as in the issue above, it does lead to incorrect error messages about exhaustion of FDs. It is very easy for the socket file descriptor to be greater than maxfds.

An index will need to be incremented for each new socket created. Access would be performed via the new field, for example: re->fhs[index].fd.

**Comment by ericmjones** [comment]
Request you close this ticket as I am moving to creytiv/re, sorry.

**Comment by Encamy** [comment]
Hello
I did not found your issue in creytiv/re, so I will write here
You can use patch https://github.com/creytiv/re/commit/49834b7afd0fe31660108271ef7657a34caa6a6d
It is not merged in master, but it is working for windows

**Comment by ericmjones** [comment]
Thanks for pointing me to that. I'll gauge it's performance and possibly write an IOCP implementation if it's not good enough.
