### ISSUE TITLE
webrtc_aec test call failed

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#712]
I built baresip for Linux using flags:

`STATIC=yes EXTRA_MODULES=webrtc_aec WEBRTC_PATH=/opt/webrtc`

Build went fine and when I started baresip, it reported:

`aufilt: webrtc_aec`

But when I made a test call, I got these errors:

```answering call from sip:test@test.tutpro.com with 200
audio: Set audio decoder: opus 48000Hz 2ch
audio: player started with sample format S16LE
audio: Set audio encoder: opus 48000Hz 2ch
webrtc_aec: unsupported sample format (S16LE)
audio: error in encode audio-filter 'webrtc_aec' (Operation not supported)
webrtc_aec: unsupported sample format (S16LE)
audio: error in decode audio-filter 'webrtc_aec' (Operation not supported)
audio: audio-filter 'webrtc_aec' update failed (Operation not supported)
```

Why doesn't webrtc_aec like S16LE?  Is there anything to be done to avoid the errors?

**Comment by juha-h** [comment]
From webrtc_aec module source I found that it supports only AUFMT_FLOAT format and otherwise issues the above `unsupported sample format (S16LE)` error.

I then went and added these two line to config:

```
ausrc_format		float
auplay_format		float
```
but I still get the same error even when player and source use float format:

```
audio: Set audio decoder: opus 48000Hz 2ch
audio: player started with sample format FLOAT
audio: Set audio encoder: opus 48000Hz 2ch
webrtc_aec: unsupported sample format (S16LE)
audio: error in encode audio-filter 'webrtc_aec' (Operation not supported)
webrtc_aec: unsupported sample format (S16LE)
audio: error in decode audio-filter 'webrtc_aec' (Operation not supported)
audio: audio-filter 'webrtc_aec' update failed (Operation not supported)
audio: source started with sample format FLOAT
audio tx pipeline:        alsa ---> opus
audio rx pipeline:        alsa <--- opus
webrtc_aec: unsupported sample format (S16LE)
audio: error in encode audio-filter 'webrtc_aec' (Operation not supported)
webrtc_aec: unsupported sample format (S16LE)
audio: error in decode audio-filter 'webrtc_aec' (Operation not supported)
audio: audio-filter 'webrtc_aec' update failed (Operation not supported)
```
What should I change in the config to tell webrtc_aec module flat float format is in use?

**Comment by alfredh** [comment]
Please see here for the different supported audio sample formats:

https://github.com/alfredh/baresip/wiki/Audio-sample-formats#audio-filters


the sample format for the audio filter is taken from the encoder and decoder.

you also need to set the encoder/decoder to use FLOAT:

```
ausrc_format            float             # s16, float, ..
auplay_format           float             # s16, float, ..
auenc_format            float             # s16, float, ..
audec_format            float             # s16, float, ..
```

if e.g. "src" and "enc" format is different, it will activate an internal audio sample
format converted (at the expense of increased CPU usage).

it is possible to implement support for S16 in webrtc_aec, this should be quite
easy by just using the audio sample converter `auconv` in librem:

https://github.com/creytiv/rem/blob/master/include/rem_auconv.h

```c
void auconv_from_s16(enum aufmt dst_fmt, void *dst_sampv,
		     const int16_t *src_sampv, size_t sampc);
void auconv_to_s16(int16_t *dst_sampv, enum aufmt src_fmt,
		   void *src_sampv, size_t sampc);
```

**Comment by juha-h** [comment]
Thanks for pointers.  I'll do more testing during the next couple of days and will reopen if needed. 

This now looks very promising also for Andoid due to pjsip's webrtc aec implementation.

**Comment by juha-h** [comment]
My config file now has:
```
ausrc_format		float
auplay_format		float
auenc_format            float
audec_format            float
```
and baresip reports at start:
```
aufilt: webrtc_aec
```
When I make test call, `unsupported sample format (S16LE)` errror messages don't anymore show up,
but the other error messages persist:
```
call: connecting to 'sip:jh@test.tutpro.com'..
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 180 Ringing (/)
audio: Set audio decoder: opus 48000Hz 2ch
audio: player started with sample format FLOAT
audio: Set audio encoder: opus 48000Hz 2ch
audio: error in encode audio-filter 'webrtc_aec' (Operation not supported)
audio: error in decode audio-filter 'webrtc_aec' (Operation not supported)
audio: audio-filter 'webrtc_aec' update failed (Operation not supported)
audio: source started with sample format FLOAT
audio tx pipeline:        alsa ---> opus
audio rx pipeline:        alsa <--- opus
audio: error in encode audio-filter 'webrtc_aec' (Operation not supported)
audio: error in decode audio-filter 'webrtc_aec' (Operation not supported)
audio: audio-filter 'webrtc_aec' update failed (Operation not supported)
test@test.tutpro.com: Call established: sip:jh@test.tutpro.com
```
Something else still missing from config?

**Comment by alfredh** [comment]
it is probably this check that fails:

```c
	if (prm->srate > MAX_SAMPLE_RATE || prm->ch > MAX_CHANNELS)
		return ENOTSUP;
```

which is currently defined as 16000 Hz and 1 channel.

**Comment by juha-h** [comment]
Yes, opus would not match those.  Also pjsip only supports mono, but does not seem to have restriction on rate:

```
if (channel_count != 1)
    	return PJ_ENOTSUP;

    echo->channel_count = channel_count;
    echo->samples_per_frame = samples_per_frame;
    echo->tail = tail_ms;
    echo->clock_rate = clock_rate;
    /* SWB is processed as 160 frame size */
    if (clock_rate > 8000)
        echo->subframe_len = 160;
    else
    	echo->subframe_len = 80;
    echo->options = options;
    
    /* Create WebRTC AEC */
    echo->AEC_inst = WebRtcAec_Create();
    if (!echo->AEC_inst) {
    	return PJ_ENOMEM;
    }
    
    /* Init WebRTC AEC */
    status = WebRtcAec_Init(echo->AEC_inst, clock_rate, clock_rate);
    if (status != 0) {
        print_webrtc_aec_error("Init", echo->AEC_inst);
        WebRtcAec_Free(echo->AEC_inst);
    	return PJ_ENOTSUP;
    }
```

**Comment by juha-h** [comment]
Pretty old webrtc demo

`https://github.com/ideawu/webrtc-demo/blob/master/src/audio_device.cpp`

Uses NULL as value of WebRtcAec_Process num_bands argument.

The default is set in aec_core.cc like this

```
if (sampFreq == 8000) {
    aec->num_bands = 1;
  } else {
    aec->num_bands = (size_t)(sampFreq / 16000);
  }
```

I wonder what is the reason for only supporting mono in baresip and pjsip?

Anyway, since opus is the current codec of choice, aec without opus support would not be very useful.

**Comment by alfredh** [comment]
I would like to suggest that you test this in two stages:

1. test aec with a narrowband codec like PCMA/PCMU, and if
  that is working:

2. test aec with a wideband codec like opus.

the samplerate has a big impact on the CPU usage for the AEC.
(higher samplerate uses more CPU).

if 1.) does not work, then there is no point in testing 2.)

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I would like to suggest that you test this in two stages:
> 
> 1. test aec with a narrowband codec like PCMA/PCMU, and if
>   that is working:

I tried those also and they didn't work:
```
sip:jh@test.tutpro.com: Answering incoming call
answering call from sip:test@test.tutpro.com with 200
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: player started with sample format FLOAT
audio: Set audio encoder: PCMU 8000Hz 1ch
webrtc_aec: creating shared state: [8000 Hz, 1 channels, subframe 80 bytes]
audio: source started with sample format FLOAT
audio tx pipeline:        alsa ---> webrtc_aec ---> PCMU
audio rx pipeline:        alsa <--- webrtc_aec <--- PCMU
jh@test.tutpro.com: Call established: sip:test@test.tutpro.com
audio: PCMU encode error: 160 samples (Operation not supported)
audio: PCMU encode error: 160 samples (Operation not supported)
audio: PCMU encode error: 160 samples (Operation not supported)
audio: PCMU encode error: 160 samples (Operation not supported)
audio: PCMU encode error: 160 samples (Operation not supported)
audio: PCMU encode error: 160 samples (Operation not supported)
audio: PCMU encode error: 160 samples (Operation not supported)
audio: PCMU encode error: 160 samples (Operation not supported)
...
```

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> the samplerate has a big impact on the CPU usage for the AEC.
> (higher samplerate uses more CPU).

It is OK if modern Android devices can handle that.  They do have lots
of CPU power and usually not many other things to do during a call.

-- Juha

**Comment by alfredh** [comment]
oh I see :)

then another option is to add support for S16 sample format in webrtc_aec ..

**Comment by juha-h** [comment]
That would be good.  I tried if webrtc_aec would work with G7221 codec that is 16000/1, but it turned out
that G7221 does not work at all with float.  With float G7221 just gave static noice.

**Comment by alfredh** [comment]
can you please try now with
commit 9f36ea11a2ee0a47a94e44eea8b800881afdbfbd ?

I added support for S16 sample format (both S16 and FLOAT supported).

now the codecs G711, G722 should work.

you also need to revert back to this configuration:

```
ausrc_format            s16
auenc_format            s16

auplay_format           s16
audec_format            s16
```

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> now the codecs G711, G722 should work.

I tried PCMA, G722 and G7221 and they all worked using

```
ausrc_format            s16
auenc_format            s16
auplay_format           s16
audec_format            s16
```

but with webrtc_aec.so I still get the errors:

```
audio: Set audio decoder: G7221 16000Hz 1ch
audio: player started with sample format S16LE
audio: Set audio encoder: G7221 16000Hz 1ch
webrtc_aec: unsupported sample format (S16LE)
audio: error in encode audio-filter 'webrtc_aec' (Operation not supported)
webrtc_aec: unsupported sample format (S16LE)
audio: error in decode audio-filter 'webrtc_aec' (Operation not supported)
audio: audio-filter 'webrtc_aec' update failed (Operation not supported)
audio: source started with sample format S16LE
audio tx pipeline:        alsa ---> G7221
audio rx pipeline:        alsa <--- G7221
webrtc_aec: unsupported sample format (S16LE)
audio: error in encode audio-filter 'webrtc_aec' (Operation not supported)
webrtc_aec: unsupported sample format (S16LE)
audio: error in decode audio-filter 'webrtc_aec' (Operation not supported)
audio: audio-filter 'webrtc_aec' update failed (Operation not supported)
```

**Comment by alfredh** [comment]
strange, are you sure you are using git HEAD and full recompile ?

that check looks like this now:


```c
	switch (prm->fmt) {

	case AUFMT_S16LE:
	case AUFMT_FLOAT:
		break;

	default:
		warning("webrtc_aec: unsupported sample format (%s)\n",
			aufmt_name((enum aufmt)prm->fmt));
		return ENOTSUP;
	}
```

it works for me on linux:

```
call: connecting to 'sip:music@iptel.org'..
audio: RTP/RTCP multiplexing enabled
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: player started with sample format S16LE
audio: Set audio encoder: PCMU 8000Hz 1ch
webrtc_aec: creating shared state: [8000 Hz, 1 channels, subframe 80 bytes]
audio: source started with sample format S16LE
audio tx pipeline:        alsa ---> webrtc_aec ---> PCMU
audio rx pipeline:        alsa <--- webrtc_aec <--- PCMU
aeh@iptel.org: Call established: sip:music@iptel.org
stream: incoming rtp for 'audio' established, receiving from 212.79.111.155:25266
call: terminate call '7aba32a6b3c3cf06' with sip:music@iptel.org
sip:aeh@iptel.org: Call with sip:music@iptel.org terminated (duration: 3 secs)
```

it was compiled like this:

```
 $  make EXTRA_MODULES=webrtc_aec WEBRTC_PATH=/home/alfredh/tmp STATIC=yes
```

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> strange, are you sure you are using git HEAD and full recompile ?

Maybe something went wrong with my git pull:
```
git pull
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
Unpacking objects: 100% (6/6), done.
remote: Total 6 (delta 1), reused 2 (delta 0), pack-reused 0
From github.com:alfredh/baresip
   9f36ea1..26fa0aa  master     -> origin/master
Your configuration specifies to merge with the ref 'refs/heads/sdp_remote_codec'
from the remote, but no such ref was fetched.
```
I'll do full 'git clone' and try again.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> strange, are you sure you are using git HEAD and full recompile ?

After full clone, the errors were gone.  I tested with PCMA and G7221.
With both codecs, there is quite strong noise for about a second at
the start of the call.

**Comment by juha-h** [comment]
juha-h writes:

> After full clone, the errors were gone.  I tested with PCMA and G7221.
> With both codecs, there is quite strong noise for about a second at
> the start of the call.

But looks like only if the call is between two baresips.  No noise to
music@iptel.org.  Will make more tests.

**Comment by juha-h** [comment]
I noticed this kind of new webrtc_aec related compiler warning when I built baresip for Android using pjsip webrtc lib:
```
  CXX [m] build-arm/modules/webrtc_aec/encode.o
modules/webrtc_aec/encode.cpp:133:10: warning: enumeration values 'AUFMT_PCMA', 'AUFMT_PCMU', and 'AUFMT_S24_3LE' not
      handled in switch [-Wswitch]
        switch (enc->fmt) {
                ^
1 warning generated.
```
Perhaps the definition of the enumeration differs from your version of the lib?

**Comment by juha-h** [comment]
Looks like the noice at the start of the call is present only when I make test calls between two baresips on the same Linux host.  I haven't been able to reproduce it in calls when caller and callee have separete devices.

I was able to build g7221 module for Android and webrtc_eac now seems to work fine with it also in my baresip Android app.

If it does not make sense to add webrtc_aec support for opus, I'll just add a note to the Android app, where I ask user to avoid opus if aec is important.

So other than the above mentioned compiler warning, I'm fine with current state of webrtc_aec module.

One small thing. This include can be removed from encode.cpp and decode.cpp, since it is in aec.h:
```
#include "modules/audio_processing/aec/echo_cancellation.h"
```

**Comment by alfredh** [comment]
On 19/05/2019 16:04, juha-h wrote:
> I noticed this kind of new webrtc_aec related compiler warning when I built baresip for Android using pjsip webrtc lib:
> 
> |CXX [m] build-arm/modules/webrtc_aec/encode.o modules/webrtc_aec/encode.cpp:133:10: warning: enumeration values 
> 'AUFMT_PCMA', 'AUFMT_PCMU', and 'AUFMT_S24_3LE' not handled in switch [-Wswitch] switch (enc->fmt) { ^ 1 warning generated. |
> 
> Perhaps the definition of the enumeration differs from your version of the lib?
> 

thanks, fixed in commit a4f49f13da4e1d4c26795dfdf6053a34ca1fa337

**Comment by alfredh** [comment]
thanks for testing !

both include file and warning should be fixed now..

**Comment by juha-h** [comment]
Thanks for your efforts.
