### ISSUE TITLE
gzrtp module needs updating

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#713]
Looks like gzrtp module needs updating:
```
CXX [m] build-x86_64/modules/gzrtp/gzrtp.o
modules/gzrtp/gzrtp.cpp:172:1: error: invalid conversion from ‘int (*)(menc_media**, menc_sess*, rtp_sock*, int, void*, void*, sdp_media*)’ to ‘int (*)(menc_media**, menc_sess*, rtp_sock*, udp_sock*, udp_sock*, const sa*, const sa*, sdp_media*)’ [-fpermissive]
 };
 ^
```
Its media_alloc function does not match current version of menc_media_h.  Or is it so that the module is not anymore used by anyone?

**Comment by alfredh** [comment]
thanks for the report, I just fixed it in commit
f9d1e0879c214c03a2f2408031b69233f707d4a7

I am not using the gzrtp module personally, but I think we can keep it here for now.

**Comment by juha-h** [comment]
Compiles now.
