### ISSUE TITLE
call: no common audio codecs - rejected

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#718]
I'm testing rtpengine's transcoding capabilities, but have a problem with baresip not accepting sdp from it.

I have configure baresip account so that it only support opus/48000/2 codec and /uastat shows:
```
Account:
...
 audio_codecs: opus/48000/2
```
When INVITE comes in, it has this kind of sdp:
```
.
v=0.
o=- 686726419 1742984825 IN IP4 192.168.43.99.
s=-.
c=IN IP4 192.168.43.99.
t=0 0.
a=tool:baresip 0.6.2.
m=audio 30244 RTP/AVP 8 0 101 96.
c=IN IP4 192.168.43.99.
a=label:1.
a=rtcp-rsize.
a=ssrc:3498303314 cname:sip:test@test.tutpro.com.
a=rtpmap:8 PCMA/8000.
a=rtpmap:0 PCMU/8000.
a=rtpmap:101 telephone-event/8000.
a=rtpmap:96 opus/48000/2.
a=fmtp:101 0-15.
...
```
Dots at the end of lines are added by ngrep.

When baresip receices the INVITE, it respods with `488 Not Acceptable Here` and writes to console:
```
call: no common audio codecs - rejected
```
Can anyone spot what is wrong with the SDP or is this a bug in baresip?

**Comment by juha-h** [comment]
I made a test where I removed 101 from the SDP before INVITE arrived to baresip:
```
v=0.
o=- 335166208 1601566012 IN IP4 192.26.134.10.
s=-.
c=IN IP4 192.26.134.10.
t=0 0.
a=tool:baresip 0.6.2.
m=audio 30000 RTP/AVP 96.
c=IN IP4 192.26.134.10.
a=label:1.
a=rtcp-rsize.
a=ssrc:3776330263 cname:sip:test@test.tutpro.com.
a=rtpmap:96 opus/48000/2.
```
and then baresip accepted the INVITE.

So either there is a bug in baresip (it assumes that codec IDs need are in increasing order on m line) or there is an RFC somewhere that tells that they have to be in increasing order.

I'll add bug label to this until such an RFC is found.

**Comment by juha-h** [comment]
I checked https://tools.ietf.org/html/rfc4566#section-5.14 and didn't find anything about ordering of codec IDs on m line.

**Comment by juha-h** [comment]
I tested with pjsua and it accepted INVITE with m-line where opus 96 is after 101:
```
m=audio 31174 RTP/AVP 101 96
c=IN IP4 192.168.43.99
a=label:1
a=rtcp-rsize
a=ssrc:1006889197 cname:sip:test@test.tutpro.com
a=rtpmap:101 telephone-event/8000
a=rtpmap:96 opus/48000/2
a=fmtp:101 0-15
```
When I replace pjsua UAS with baresip, exactly the same call fails with

`call: no common audio codecs - rejected`.

I then tried to figure out from baresip code, where the bug is.  Check of common codec is made by function `have_common_audio_codecs`  on line:
```
sc = sdp_media_rformat(stream_sdpmedia(audio_strm(call->audio)), NULL);
```
and those function calls were not easy to follow.

**Comment by alfredh** [comment]
here is the SDP debug for your session:

```
SDP session
  local attributes:
    tool='baresip 0.6.2'
  remote attributes:
session media:
audio RTP/AVP
  local formats:
    101 telephone-event/8000/1 (0-15) *
     96 opus/48000/2 (stereo=1;sprop-stereo=1;maxaveragebitrate=28000) *
  remote formats:
      8 PCMA/8000/1
      0 PCMU/8000/1
    101 telephone-event/8000/1 (0-15) *
     96 opus/48000/2 *
  local attributes:
    label='1'
    rtcp-rsize
    ssrc='4029404324 cname:sip:aeh@iptel.org'
    ptime='20'
  remote attributes:
local media:
```

and this is part of your SDP:

```
a=rtpmap:8 PCMA/8000.
a=rtpmap:0 PCMU/8000.
a=rtpmap:101 telephone-event/8000.
a=rtpmap:96 opus/48000/2.
```

the codec id can be in any order, but the codecs are listed in the order of priority.

so what it says is that `telephone-event` has a higher priority than `opus`.

here is the code that decides for a common codec:

```c
static bool have_common_audio_codecs(const struct call *call)
{
	const struct sdp_format *sc;
	struct aucodec *ac;

	sc = sdp_media_rformat(stream_sdpmedia(audio_strm(call->audio)), NULL);
	if (!sc)
		return false;

	ac = sc->data;  /* note: this will exclude telephone-event */

	return ac != NULL;
}
```

the sdp_format's `sc->data` points to a valid aucodec for all audio codecs,
except for `telephone-event` which uses `sc->data == NULL`

so in your case the function `sdp_media_rformat` will return `telephone-event`
and then return `false` because ac is NULL.

I have analyzed hundreds of SDP messages, and in most cases the `telephone-event`
always is listed as the last codec.

I think the SDP from RtpEngine is a bit strange, why would it list opus as the last codec ?

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I have analyzed hundreds of SDP messages, and in most cases the
> `telephone-event` always is listed as the last codec.
> 
> I think the SDP from RtpEngine is a bit strange, why would it list
> opus as the last codec ? 

When rtpengine is given instructions to transcode audio to a given codec
(in the example with flag codec-transcode=opus), it appends the target
codec as the last codec on m=audio line.

Would it make sense to pick the common non-telephone-event audio codec
no matter which position it has on the list?

**Comment by alfredh** [comment]
okay, could you please try this patch and see if it works better:

```diff
diff --git a/src/call.c b/src/call.c
index f98b3ce..2e77bbf 100644
--- a/src/call.c
+++ b/src/call.c
@@ -1430,12 +1430,39 @@ static void sipsess_close_handler(int err, const struct sip_msg *msg,
 }
 
 
+static const struct sdp_format *sdp_media_rcodec(const struct sdp_media *m)
+{
+	const struct list *lst;
+	struct le *le;
+
+	if (!m || !sdp_media_rport(m))
+		return NULL;
+
+	lst = sdp_media_format_lst(m, false);
+
+	for (le=list_head(lst); le; le=le->next) {
+
+		const struct sdp_format *fmt = le->data;
+
+		if (!fmt->sup)
+			continue;
+
+		if (!fmt->data)
+			continue;
+
+		return fmt;
+	}
+
+	return NULL;
+}
+
+
 static bool have_common_audio_codecs(const struct call *call)
 {
 	const struct sdp_format *sc;
 	struct aucodec *ac;
 
-	sc = sdp_media_rformat(stream_sdpmedia(audio_strm(call->audio)), NULL);
+	sc = sdp_media_rcodec(stream_sdpmedia(audio_strm(call->audio)));
 	if (!sc)
 		return false;
 
```

**Comment by juha-h** [comment]
juha-h writes:

> Would it make sense to pick the common non-telephone-event audio codec
> no matter which position it has on the list?

So the algorithm would be:

- go through list of account's audio_codecs in order until match is
  found in incoming sdp

- if incoming sdp has telephone-event audio codec, include also that in
  the response

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> okay, could you please try this patch and see if it works better:

I tried and now baresip accepted invite sdp:

```
c=IN IP4 192.168.43.99.
t=0 0.
a=tool:baresip 0.6.2.
m=audio 30538 RTP/AVP 96 8 101 0.
c=IN IP4 192.168.43.99.
a=label:1.
a=rtcp-rsize.
a=ssrc:94060335 cname:sip:test@test.tutpro.com.
a=rtpmap:96 opus/48000/2.
a=rtpmap:8 PCMA/8000.
a=rtpmap:101 telephone-event/8000.
a=rtpmap:0 PCMU/8000.
a=sendrecv.
```

with response sdp:

```
c=IN IP4 192.26.134.10.
t=0 0.
a=tool:baresip 0.6.2.
m=audio 24786 RTP/AVP 101 0.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-15.
a=rtpmap:0 PCMU/8000.
a=sendrecv.
```

But the problem now is that baresip is not sending any audio out.
Hangup shows:

```
audio           Transmit:     Receive:
packets:              0          317
avg. bitrate:       0.0         61.7  (kbit/s)
errors:               0            0
pkt.report:           0          247
lost:                 0            0
jitter:             0.0          7.8  (ms)
```

IP 192.168.43.99 is pingable from baresip host and I have not configured
any sip_listen address.

If I replace baresip with pjsua, audio flows both ways.

**Comment by alfredh** [comment]
thanks, it was just a simple test for now.

we need to replace all calls to `sdp_media_rformat` with the new function.
(for audio only).

if you prefer to have this behaviour, I can go ahead and create a proper patch/branch.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> thanks, it was just a simple test for now.

> we need to replace all calls to `sdp_media_rformat` with the new function.
> (for audio only).
> 
> if you prefer to have this behaviour, I can go ahead and create a
> proper patch/branch. 

How about audio transmission, how to get that activated?

**Comment by alfredh** [comment]
I rewrote the patch in a better way:

https://github.com/alfredh/baresip/tree/sdp_remote_codec

the logic is the same as before, except that it will exclude `telephone-event` codecs.
it searches the list of remote codecs from the top, and selects the first one that
is also supported locally.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I rewrote the patch in a better way:
> 
> https://github.com/alfredh/baresip/tree/sdp_remote_codec

Thanks, will try tomorrow morning.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I rewrote the patch in a better way:
> 
> https://github.com/alfredh/baresip/tree/sdp_remote_codec

This worked very well.  Now baresip accepted the INVITE and also
transmitted audio after responding with 200 OK.

Below is an example, where UAS baresip has ;audio_codecs=PCMU.

```
INVITE sip:test-0x55ed3a81a030@192.168.43.99:5066;transport=tcp SIP/2.0.
Record-Route: <sip:192.168.43.99;transport=tcp;lr;pm;tcf=PCMA;tct=PCMU>.
Via: SIP/2.0/TCP 192.168.43.99;branch=z9hG4bK0d66.32e432160ecd30af23e800218c1fa0a0.0;i=2.
Via: SIP/2.0/TCP 192.168.43.99:42219;received=192.168.43.99;branch=z9hG4bK3a20ca12d0e0dbf3;rport=33974.
Contact: <sip:jh@test.tutpro.com;gr=urn:uuid:55860551-f714-931b-2ad9-9ca935948d8b>.
Max-Forwards: 69.
To: <sip:test@test.tutpro.com>.
From: <sip:jh@test.tutpro.com>;tag=8eb151bc8c12f1f7.
Call-ID: 379775fd980216b4.
CSeq: 17673 INVITE.
User-Agent: baresip v0.6.2 (x86_64/linux).
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER.
Supported: gruu,path,outbound.
Content-Type: application/sdp.
Content-Length: 669.
P-Asserted-Identity: <sip:+35892345670@test.tutpro.com>.
.
v=0.
o=- 2463932337 325357272 IN IP4 192.168.43.99.
s=-.
c=IN IP4 192.168.43.99.
t=0 0.
a=tool:baresip 0.6.2.
m=audio 30610 RTP/AVP 96 8 101 0.
a=label:1.
a=rtcp-rsize.
a=ssrc:3797424177 cname:sip:jh@test.tutpro.com.
a=rtpmap:96 opus/48000/2.
a=rtpmap:8 PCMA/8000.
a=rtpmap:101 telephone-event/8000.
a=rtpmap:0 PCMU/8000.
a=fmtp:96 stereo=1;sprop-stereo=1;maxaveragebitrate=28000;cbr=0;useinbandfec=1.
a=fmtp:101 0-15.
a=sendrecv.
a=rtcp:30611.
a=ptime:20.
a=ice-ufrag:SBCRyX2D.
a=ice-pwd:oKKRaXDA4Qga7TzWFr9TQwwB72.
a=candidate:vKBm2HKdJjQPXPvN 1 UDP 2130706431 192.168.43.99 30610 typ host.
a=candidate:vKBm2HKdJjQPXPvN 2 UDP 2130706430 192.168.43.99 30611 typ host.
```

```
SIP/2.0 200 Answering.
Record-Route: <sip:192.168.43.99;transport=tcp;lr;pm;tcf=PCMA;tct=PCMU>.
Via: SIP/2.0/TCP 192.168.43.99;branch=z9hG4bK0d66.32e432160ecd30af23e800218c1fa0a0.0;i=2.
Via: SIP/2.0/TCP 192.168.43.99:42219;received=192.168.43.99;branch=z9hG4bK3a20ca12d0e0dbf3;rport=33974.
To: <sip:test@test.tutpro.com>;tag=ea28446111cec08f.
From: <sip:jh@test.tutpro.com>;tag=8eb151bc8c12f1f7.
Call-ID: 379775fd980216b4.
CSeq: 17673 INVITE.
Server: baresip v0.6.2 (x86_64/linux).
Contact: <sip:test@test.tutpro.com;gr=urn:uuid:9b21c1a8-dc58-a3d6-83d5-7be67cbe70ce>.
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER.
Content-Type: application/sdp.
Content-Length: 372.
.
v=0.
o=- 2122067077 1643755635 IN IP4 192.168.43.99.
s=-.
c=IN IP4 192.168.43.99.
t=0 0.
a=tool:baresip 0.6.2.
m=audio 9966 RTP/AVP 101 0.
c=IN IP4 109.240.60.205.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-15.
a=rtpmap:0 PCMU/8000.
a=rtcp:9967 IN IP4 109.240.60.205.
a=sendrecv.
a=label:1.
a=rtcp-rsize.
a=ssrc:4039866832 cname:sip:test@test.tutpro.com.
a=ptime:20.
```

**Comment by alfredh** [comment]
thanks for reporting and testing.

should I merge that branch to master?

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> should I merge that branch to master?

Yes, please do.
