### ISSUE TITLE
ctrl_tcp and dtfm events

### ISSUE THREAD

**Issue by Bettman66** [alfredh/baresip#719]
I use the ctrl_tcp module. How can I subscribe to the dtmf events?

**Comment by jmillan** [comment]
Please, use the mailing list for questions.

You don't have to subscribe to specific events when using the `ctrl_tcp` module, you'll receive all of them, so just act upon those that you need in your side.

**Comment by Bettman66** [comment]
That's my problem, it does not work.
console:
`door2sip@fritz.box: Call in-progress: sip:**610@fritz.box
stream: rtcp_send_app failed (Address family not supported by protocol)
stream: incoming rtp for 'audio' established, receiving from 192.168.12.1:7086
stream: rtcp_send_app failed (Address family not supported by protocol)
door2sip@fritz.box: Call established: sip:**610@fritz.box
received DTMF: '#' (duration=100)s)
received DTMF: '4' (duration=100)s)
received DTMF: '7' (duration=100)s)
received DTMF: '1' (duration=100)s)
received DTMF: '2' (duration=100)s)
sip:**610@fritz.box: session closed: Connection reset by peer
sip:door2sip@fritz.box: Call with sip:**610@fritz.box terminated (duration: 8 secs)
Quit
ua: stop all (forced=0)`

syslog:
`May 18 11:31:37 ubuntu baresip[1538]: door2sip@fritz.box: Call established: sip:**610@fritz.box
May 18 11:31:42 ubuntu baresip[1538]: received DTMF: '#' (duration=100)
May 18 11:31:42 ubuntu baresip[1538]: received DTMF: '4' (duration=100)
May 18 11:31:42 ubuntu baresip[1538]: received DTMF: '7' (duration=100)
May 18 11:31:42 ubuntu baresip[1538]: received DTMF: '1' (duration=100)
May 18 11:31:42 ubuntu baresip[1538]: received DTMF: '2' (duration=100)
May 18 11:31:45 ubuntu baresip[1538]: sip:**610@fritz.box: session closed: Connection reset by peer
May 18 11:31:45 ubuntu baresip[1538]: sip:door2sip@fritz.box: Call with sip:**610@fritz.box terminated (duration: 8 secs)
May 18 11:32:31 ubuntu baresip[1538]: ua: stop all (forced=0)`

crtl_tcp:
`Connected
Received: 199:{"event":true,"type":"CALL_PROGRESS","class":"call","accountaor":"sip:door2sip@fritz.box","direction":"outgoing","peeruri":"sip:**610@fritz.box","id":"4b54b98a48a39c68","param":"sip:**610@fritz.box"},
Received: 277:{"event":true,"type":"CALL_RTCP","class":"call","accountaor":"sip:door2sip@fritz.box","direction":"outgoing","peeruri":"sip:**610@fritz.box","id":"4b54b98a48a39c68","param":"audio","rtcp_stats":{"tx":{"sent":122,"lost":0,"jit":0},"rx":{"sent":125,"lost":0,"jit":3875},"rtt":0}},
Received: 277:{"event":true,"type":"CALL_RTCP","class":"call","accountaor":"sip:door2sip@fritz.box","direction":"outgoing","peeruri":"sip:**610@fritz.box","id":"4b54b98a48a39c68","param":"audio","rtcp_stats":{"tx":{"sent":286,"lost":0,"jit":0},"rx":{"sent":288,"lost":0,"jit":3875},"rtt":0}},
Received: 277:{"event":true,"type":"CALL_RTCP","class":"call","accountaor":"sip:door2sip@fritz.box","direction":"outgoing","peeruri":"sip:**610@fritz.box","id":"4b54b98a48a39c68","param":"audio","rtcp_stats":{"tx":{"sent":468,"lost":0,"jit":0},"rx":{"sent":470,"lost":0,"jit":3875},"rtt":0}},
Received: 202:{"event":true,"type":"CALL_ESTABLISHED","class":"call","accountaor":"sip:door2sip@fritz.box","direction":"outgoing","peeruri":"sip:**610@fritz.box","id":"4b54b98a48a39c68","param":"sip:**610@fritz.box"},
Received: 277:{"event":true,"type":"CALL_RTCP","class":"call","accountaor":"sip:door2sip@fritz.box","direction":"outgoing","peeruri":"sip:**610@fritz.box","id":"4b54b98a48a39c68","param":"audio","rtcp_stats":{"tx":{"sent":686,"lost":0,"jit":0},"rx":{"sent":689,"lost":0,"jit":3875},"rtt":0}},
Received: 202:{"event":true,"type":"CALL_CLOSED","class":"call","accountaor":"sip:door2sip@fritz.box","direction":"outgoing","peeruri":"sip:**610@fritz.box","id":"4b54b98a48a39c68","param":"Connection reset by peer"},
Received: 92:{"event":true,"type":"SHUTDOWN","class":"application","accountaor":"sip:door2sip@fritz.box"},
Received: 94:{"event":true,"type":"UNREGISTERING","class":"register","accountaor":"sip:door2sip@fritz.box"},
Received: 50:{"event":true,"type":"EXIT","class":"application"},
Connection closed`

**Comment by alfredh** [comment]
@Bettman66 

these events will be sent when you receive DTMF event,
either via SIP INFO or telephone-event:

```c
	UA_EVENT_CALL_DTMF_START,
	UA_EVENT_CALL_DTMF_END,
```

I just tested it locally and it works fine here.

can you please include the full baresip log and your config file?
also ngrep of SIP traffic if possible.

**Comment by Bettman66** [comment]
ngrep : https://pastebin.com/eBHpZnBB
baresip : https://pastebin.com/PrHcFPJp
config : https://pastebin.com/13N71JiA

**Comment by Bettman66** [comment]
I also tested mqtt and also version 0.5.11 without success. If it works for you, it can only be due to the Fritzbox protocol.

**Comment by alfredh** [comment]
can you please try to not load the `dtmfio.so` module ?

it looks like dtmfio module is grabbing the dtmf handler:

```c
	if ( ev == UA_EVENT_CALL_ESTABLISHED ) {
		fprintf(fd, "E");
		fflush(fd);
		call_set_handlers( call, NULL, dtmf_handler, NULL);
	}
```

**Comment by Bettman66** [comment]
yes that was it, thanks.
