### ISSUE TITLE
implement ch=1 variant of opus module

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#720]
Speex module was removed by commit https://github.com/alfredh/baresip/commit/388f04eba282d23a8f07386a57ccde371c99a1c0 from baresip as being obsolated by opus.

This is true what comes to codec audio quality, but opus has major problem in that it always has 2 channels and always uses high (48000) frequency. This has made it impossible to use webrtc aec when opus codec has been negotiated.

I therefore propose that the above mentioned commit is reverted restoring speex module to baresip.

**Comment by premultiply** [comment]
Opus is able to encode mono channels.
But what needs to be improved is the preselection of a prefered codec setup when baresip is the caller.
The common codec settings need to be splitted for incoming and outgoing calls.

**Comment by juha-h** [comment]
premultiply writes:

> Opus is able to encode mono channels.

Yes, but the sender cannot be forced to send mono and thus receiver must
always be able to decode both mono and stereo.

> But what needs to be improved is the preselection of a prefered codec
> setup when baresip is the caller. The common codec settings need to be
> splitted for incoming and outgoing calls.

As I mentioned, the problem is that webrtc_aec module does not accept 2
channels nor 48000 hz frequency, which opus is always advertising.

**Comment by alfredh** [comment]
the opus codec is not fixed to 48000/2. that is only for the SDP signalling.

opus can use many different samplerates and also multiple channels.
this has to be setup with the encoder/decoder. the opus codec also has
a built-in resampler, in case it receives a mono stream that is converted
to stereo.

I think that it is better to investigate how to get this working properly instead,
and also ask the experts on the opus-codec mailing list.

The speex module was deprecated and removed, because the upstream libspeex
project has been deprecated. I dont think we should revert it just because of this
quick fix, it would not benefit us in the long run.

**Comment by juha-h** [comment]
According to RFC7587 RTP Payload Format for the Opus Speech and Audio Codec, there is no way (signalling or otherwise) to force parties of the call to send only mono signals:
```
stereo:  specifies whether the decoder prefers receiving stereo or
      mono signals.  Possible values are 1 and 0, where 1 specifies that
      stereo signals are preferred, and 0 specifies that only mono
      signals are preferred.  Independent of the stereo parameter, every
      receiver MUST be able to receive and decode stereo signals, but
      sending stereo signals to a receiver that signaled a preference
      for mono signals may result in higher than necessary network
      utilization and encoding complexity.  If no value is specified,
      the default is 0 (mono).
```
```
   sprop-stereo:  specifies whether the sender is likely to produce
      stereo audio.  Possible values are 1 and 0, where 1 specifies that
      stereo signals are likely to be sent, and 0 specifies that the
      sender will likely only send mono.  This is not a guarantee that
      the sender will never send stereo audio (e.g., it could send a
      prerecorded prompt that uses stereo), but it indicates to the
      receiver that the received signal can be safely downmixed to mono.
      This parameter is useful to avoid wasting receiver resources by
      operating the audio processing pipeline (e.g., echo cancellation)
      in stereo when not necessary.  If no value is specified, the
      default is 0 (mono).
```
This means that opus cannot be used as a replacement of speex, which uses mono in all cicumstances.  For me opus show stopper is that calls using opus cannot benefit from echo cancellation provided by webrtc_aec module.

What comes to deprecation of libspeex, libspeex will still be included in the next Debian version Buster:
```
https://packages.debian.org/search?suite=buster&searchon=names&keywords=libspeex
```
So there is no hurry to remove speex module from baresip.  It can be removed later, when it is not anymore included in major Linux distributions.

**Comment by alfredh** [comment]
I think you are misunderstand me.

in the libopus api, there is a way to force mono independently of what is sent on the wire.
we need to create the encoder/decode like this:

```c
encoder_create(channels=1);

decoder_create(channels=1);
```

if the format sent on the wire is different from this, the internal libopus
resampler will be activated. in any case, this is transparent to the application api.

codecs with similar properties: MPA, AAC

for example the mpa module has a built-in audio resampler, that will resample the
audio to/from the desired format. in theory this resampler could also be located
in baresip core, so that it would do it automatically.

**Comment by alfredh** [comment]
looking at the decoder code:

```c
	ads->dec = opus_decoder_create(ac->srate, ac->ch, &opuserr);
	if (!ads->dec) {
		warning("opus: decoder create: %s\n", opus_strerror(opuserr));
		err = ENOMEM;
		goto out;
	}
```

```c
struct aucodec {
	struct le le;
	const char *pt;
	const char *name;
	uint32_t srate;             /* Audio samplerate */
	uint32_t crate;             /* RTP Clock rate   */
	uint8_t ch;
	uint8_t pch;                /* RTP packet channels */
	const char *fmtp;
	auenc_update_h *encupdh;
	auenc_encode_h *ench;
	audec_update_h *decupdh;
	audec_decode_h *dech;
	audec_plc_h    *plch;
	sdp_fmtp_enc_h *fmtp_ench;
	sdp_fmtp_cmp_h *fmtp_cmph;
};
```

so we can create a variant codec that has ch=1 and pch=2.

**Comment by juha-h** [comment]
Sounds good (internally 1 channel no matter what on wire).  I don't have enough know how to activate the resampler, but will test any time if the code becomes available.

**Comment by juha-h** [comment]
I got ilbc module working (after the changes in pull request https://github.com/alfredh/baresip/pull/723).  So I don't anymore need speex for webrtc_aec.  Anyway, it would be nice if webrtc_aec could some day be used also with opus.

**Comment by juha-h** [comment]
I gave "so we can create a variant codec that has ch=1 and pch=2" a try like this:
```
diff --git a/modules/opus/opus.c b/modules/opus/opus.c
index c2819f4..1d9111f 100644
--- a/modules/opus/opus.c
+++ b/modules/opus/opus.c
@@ -68,7 +68,7 @@ static struct aucodec opus = {
    .name      = "opus",
    .srate     = 48000,
    .crate     = 48000,
-   .ch        = 2,
+   .ch        = 1,
    .pch       = 2,
    .fmtp      = fmtp,
    .encupdh   = opus_encode_update,
@@ -95,7 +95,7 @@ static int module_init(void)
    struct conf *conf = conf_cur();
    uint32_t value;
    char *p = fmtp + str_len(fmtp);
-   bool b, stereo = true, sprop_stereo = true;
+   bool b, stereo = false, sprop_stereo = false;
    struct pl pl;
    int n = 0;
 
diff --git a/modules/webrtc_aec/aec.h b/modules/webrtc_aec/aec.h
index 06e4f5d..ad82fa9 100644
--- a/modules/webrtc_aec/aec.h
+++ b/modules/webrtc_aec/aec.h
@@ -8,7 +8,7 @@
 #include "modules/audio_processing/aec/echo_cancellation.h"
 
 
-#define MAX_SAMPLE_RATE  16000
+#define MAX_SAMPLE_RATE  48000
 #define MAX_CHANNELS         1
```
Test call resulted in webrtc lib error:
```
sip:jh@test.tutpro.com: Answering incoming call
answering call from sip:test@test.tutpro.com with 200
audio: Set audio decoder: opus 48000Hz 1ch
audio: player started with sample format S16LE
audio: Set audio encoder: opus 48000Hz 1ch
webrtc_aec: creating shared state: [48000 Hz, 1 channels, subframe 160 bytes]
audio: source started with sample format S16LE
audio tx pipeline:        alsa ---> webrtc_aec ---> opus
audio rx pipeline:        alsa <--- webrtc_aec <--- opus
jh@test.tutpro.com: Call established: sip:test@test.tutpro.com
stream: incoming rtp for 'audio' established, receiving from 192.168.43.99:32438
[0:00:00] audio=0/0 (bit/s)    
#
# Fatal error in ../../../modules/audio_processing/aec/aec_core.cc, line 1853
# last system error: 11
# Check failed: aec->num_bands == num_bands (3 vs. 1)
# 
#
Aborted
```

**Comment by alfredh** [comment]
I also got the same "Fatal Error" when testing this a couple of months ago.

perhaps it would help to upgrade your libwebrtc to latest version?

perhaps we can test a lower sample-rate such as 16000 Hz or 32000 Hz ?

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I also got the same "Fatal Error" when testing this a couple of months
> ago. 
> 
> perhaps it would help to upgrade your libwebrtc to latest version?

I'm using this:

> 251408 -rw-rw-r-- 1 jh jh 257436504 Mar 22  2018 libwebrtc_full.a

I haven't checked, if there exists newer pre-compiled Linux lib.

> perhaps we can test a lower sample-rate such as 16000 Hz or 32000 Hz ?

Is there a filter to re-sample to lower rate?

**Comment by alfredh** [comment]
in order to simplify the problem, I would like to suggest that we split the problem in
2 different parts:

1. add a version of opus codec with lower quality (e.g. 32000Hz, 1ch).

2. add support for higher samplerate to webrtc_aec, if possible.

step 1.) can be committed independently of 2.)

for step 2.) we can check the source code or ask the webrtc people
how that API is working.

**Comment by juha-h** [comment]
If (1) means also new sdp format, e.g. opus/32000/1, then I don't think it is a good idea, since we loose interoperability.

Regarding (2), looking at pjsip useage of webrtc_aec, they don't seem to put any restrictions on sample rate, but only on channel count (needs to be 1).

Page https://github.com/thepacific/webrtc-android-jni has an example of webrtc API usage.

**Comment by alfredh** [comment]
the SDP format of opus will always be this:

`opus/48000/2`

I am only talking about changing the *internal* sample-rate.

Here is an example:

```c
	.srate     = 24000,
	.crate     = 48000,
	.ch        = 1,
	.pch       = 2,
```

you can also look at the MPA module how it is done there,
it has a similar problem statement.

I would still suggest to split this problem in 2 parts:
Solving 1 complex problem is easier that solving 2 complex problems
at the same time.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I am only talking about changing the *internal* sample-rate.
> 
> Here is an example:
> 
> ```c
> 	.srate     = 24000,
> 	.crate     = 48000,
> 	.ch        = 1,
> 	.pch       = 2,
> ```

OK.

> you can also look at the MPA module how it is done there,
> it has a similar problem statement.

I looked at mpa module and it is using speex resampler.  Should we use
it also in opus module?

> I would still suggest to split this problem in 2 parts:
> Solving 1 complex problem is easier that solving 2 complex problems
> at the same time.

Fine, so opus at lower rate first.

**Comment by alfredh** [comment]
here is some code from the linphone project:

```c
       if (s->samplerate > 16000) {
                        nbands = s->samplerate / 16000;
                        bandsize = 160;
                }
```

**Comment by alfredh** [comment]
https://stackoverflow.com/questions/47376456/what-num-bands-parameter-do-in-webrtcaec-process-api-inside-webrtc-echo-modul

I tried setting nbands to 3, and in this case it does not assert but rather
segfault in some code related to memcpy. Not sure if the segfault is related
to wrong API usage or broken code/lib.

**Comment by juha-h** [comment]
As the stackoverflow answer hinted, there is two versions of WebRTC AEC module (mobile and desktop). pjproject seems to be succesfully using them both, e.g., in pjmedia/src/pjmedia/echo_webrtc.c:
```
        /* Process echo cancellation */
#if PJMEDIA_WEBRTC_AEC_USE_MOBILE
        status = WebRtcAecm_Process(echo->AEC_inst, &rec_frm[frm_idx],
        			    (echo->NS_inst? buf_ptr: NULL),
        			    out_buf_ptr, echo->subframe_len,
        			    echo->tail);
#else
        status = WebRtcAec_Process(echo->AEC_inst, &buf_ptr,
                                   echo->channel_count, &out_buf_ptr,
                                   echo->subframe_len, (int16_t)echo->tail, 0);
#endif
```
In the latter, echo->channel_count value is 1.

**Comment by alfredh** [comment]
I made some improvements to the webrtc_aec module.

I used this project to build WebRTC SDK on OSX and Linux:
https://github.com/vsimon/webrtcbuilds

the webrtc_aec module works for me, with audio codecs g711,g722,l16

it does not assert/segfault anymore ..

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I used this project to build WebRTC SDK on OSX and Linux:
> https://github.com/vsimon/webrtcbuilds

OK, I'll check what happens when I try to build it for Android.

> the webrtc_aec module works for me, with audio codecs g711,g722,l16

How about opus?

**Comment by alfredh** [comment]
opus should work if we set the number of channels to 1.

(the audio filter chain is independent of the audio codec used, only
 samplerate and channels matters).

I have only tested samplerates 8000Hz, 16000Hz, 32000Hz

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I made some improvements to the webrtc_aec module.
> 
> I used this project to build WebRTC SDK on OSX and Linux:
> https://github.com/vsimon/webrtcbuilds

I tried build.sh script yesterday and waited two of hours at this
stage:
```
[4:57:16] Still working on:
[4:57:16]   src/third_party
```
My mobile network speed is about 20 Mb/sec.  Looks like the source is
huge.

-- Juha

**Comment by juha-h** [comment]
juha-h writes:

> My mobile network speed is about 20 Mb/sec.  Looks like the source is
> huge.

After a few more hours of downloading, I got to the point where build.sh
started to download debian root image!

This AEC solution may be OK in some cases, but it is hard to image that
F-Droid would accept an app that requires such a huge source build each
time a new version is of the app created.

Perhaps a more realistic webrtc AEC implementation option would be the
one that pjproject is using.  They have extracted only some small pieces
(1.9M) from WebRTC source:
```
http://svn.pjsip.org/repos/pjproject/trunk/third_party/webrtc/
```

**Comment by alfredh** [comment]
any version of the WebRTC SDK can be used, as long as it is a rather
recent version that builds and works successfully.

the webrtc_aec module is just the source code, it does not put any
requirements on the library used.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> any version of the WebRTC SDK can be used, as long as it is a rather
> recent version that builds and works successfully.

I tested opus codec using pjproject-2.8/third_party/webrtc with these opus.c
mods:
```
diff --git a/modules/opus/opus.c b/modules/opus/opus.c
index c2819f4..1d9111f 100644
--- a/modules/opus/opus.c
+++ b/modules/opus/opus.c
@@ -68,7 +68,7 @@ static struct aucodec opus = {
    .name      = "opus",
    .srate     = 48000,
    .crate     = 48000,
-   .ch        = 2,
+   .ch        = 1,
    .pch       = 2,
    .fmtp      = fmtp,
    .encupdh   = opus_encode_update,
@@ -95,7 +95,7 @@ static int module_init(void)
    struct conf *conf = conf_cur();
    uint32_t value;
    char *p = fmtp + str_len(fmtp);
-   bool b, stereo = true, sprop_stereo = true;
+   bool b, stereo = false, sprop_stereo = false;
    struct pl pl;
    int n = 0;
```
There was no crash and I got to log:
```
D/Baresip Lib( 7116): audio: Set audio decoder: opus 48000Hz 1ch
D/Baresip Lib( 7116): audio: start
D/Baresip Lib( 7116): opensles: opening player 48000Hz, 1channels
D/Baresip Lib( 7116): audio: player started with sample format S16LE
D/Baresip Lib( 7116): audio: Set audio encoder: opus 48000Hz 1ch
D/Baresip Lib( 7116): opus: encoder fmtp (stereo=0;sprop-st
D/Baresip Lib( 7116): ereo=1;maxaveragebitrate=28000;cbr=0;useinbandfec=1)
D/Baresip Lib( 7116): audio: start
D/Baresip Lib( 7116): webrtc_aec: creating shared state: [48000 Hz, 1 channels, sub
D/Baresip Lib( 7116): frame 160 samples, num_bands 3]
D/Baresip Lib( 7116): opensles: opening recorder 48000Hz, 1channels
D/Baresip Lib( 7116): ua event (CALL_ESTABLISHED) sip:foo@test.tutpro.com
D/Baresip Lib( 7116): audio: source started with sample format S16LE
D/Baresip Lib( 7116): audio tx pipeline:    opensles ---> webrtc_aec ---> opus
D/Baresip Lib( 7116): audio rx pipeline:    o
D/Baresip Lib( 7116): pensles <--- webrtc_aec <--- opus
D/Baresip Lib( 7116): call: stream start (active=1)
D/Baresip Lib( 7116): opus: encoder fmtp (stereo=0;sprop-stereo=1;maxaveragebitrate=2
D/Baresip Lib( 7116): 8000;cbr=0;useinbandfec=1)
```
I was able to hear audio, but there was strong rattling noise too.

**Comment by alfredh** [comment]
great,

I suggest that we implement opus mono the following way:

1. check `opus_stereo` and `opus_sprop_stereo` config
2. if one of them, or both is `no` then enable mono-mode
3. in mono-mode, set `opus.ch = 1`


this is an isolated change, and it is not related to webrtc-aec or other things.
so I think that it can be committed even if AEC is not working 100%.


@juha-h are you able to create a Pull Request for this ?

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> @juha-h are you able to create a Pull Request for this ?

I created a pull request.  Also tested that opus call between mono and
stereo baresips works OK.

**Comment by alfredh** [comment]
thanks a lot :)

I merged the patch to master.

I would recommend to run the AEC with mono only. It is much harder for
the AEC algorithm to detect echo if 2 channels is used.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I would recommend to run the AEC with mono only. It is much harder for
> the AEC algorithm to detect echo if 2 channels is used.

Fine.

As I mentioned, in my opus mono tests using pjproject's version of
webrtc aec, I can hear audio, but there is rattling noise too.  How is
your opus mono audio using webrtcbuilds' aec?

**Comment by alfredh** [comment]
I have tested on OSX and Linux using latest version of WebRTC SDK from google.

The audio is clear for all samplerates, except 48000 Hz that has some
random noise from time to time.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> The audio is clear for all samplerates, except 48000 Hz that has some
> random noise from time to time.

Perhaps the same noise that I have experienced.  Would resampling to
lower rate help?

-- Juha

**Comment by alfredh** [comment]
libopus supports  samplerates 8000, 12000, 16000, 24000, 48000

webrtc supports samplerates 8000, 16000, 32000, 48000

so the common samplerates are 8000, 16000 and 48000.

you can try to set the opus samplerate to 16000 and see if this is working better.
(I have tested this and it works well).


NOTE: I have been thinking about re-designing the audio filter chain, so that
it can plug in any audio resampler and convert to/from any format or samplerate.
I'm afraid that this is quite a big change and will take some time to implement...

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> libopus supports  samplerates 8000, 12000, 16000, 24000, 48000
> 
> webrtc supports samplerates 8000, 16000, 32000, 48000
> 
> so the common samplerates are 8000, 16000 and 48000.
> 
> you can try to set the opus samplerate to 16000 and see if this is
> working better.
> (I have tested this and it works well).

Works well here too (on Android with pjproject-2.8 webrtc aec).

So would it be OK to set opus.srate to 16000 if opus_stereo or
opus_sprop_stereo is false?

**Comment by juha-h** [comment]
... or would it be better to introduce opus_samplerate config param?

**Comment by alfredh** [comment]
i think 
opus_samplerate
is more flexible

**Comment by alfredh** [comment]
it is probably more flexible to add a new config parameter to
control the opus sample-rate (application level).

for example:

`opus_samplerate    16000`

this will also cover other usecases.

are you able to make a PR for this ?

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> it is probably more flexible to add a new config parameter to
> control the opus sample-rate (application level).
> 
> for example:
> 
> `opus_samplerate    16000`
> 
> this will also cover other usecases.
> 
> are you able to make a PR for this ?

Will do.

**Comment by alfredh** [comment]
Thank You!

opus samplerate merged to master
in commit e7d4a61f05fc82ee7d1cd1b420a16c1c857e8c94

**Comment by zoff99** [comment]
hi guys did you manage to get webrtc aec or aecm to work? and does the echo cancellation acutally work?
i am having the same issues, but the actual echo removal does not work properly.
maybe you can give me some pointer?
