### ISSUE TITLE
Cannot add account

### ISSUE THREAD

**Issue by jroldroyd** [alfredh/baresip#725]
On Android app, versions 8.0.0 and 7.4.0, downloaded from F-Droid, cannot add an account.

You fill in a user@domain, click the "+" button, but all you get is a "Failed to create account" error message.

Phone is a Samsung S7e, latest up-to-date Android (which is Oreo on that device).

Edit: I just found version 8.3.0 on the Google Play Store.  That version works!

**Comment by juha-h** [comment]
jroldroyd writes:

> On Android app, downloaded from F-Droid, cannot add an account.
> 
> You fill in a user@domain, click the "+" button, but all you get is a
> "Failed to create account" error message.

This is not correct project to report issues in baresip android app.
Do it in baresip-studio project. What comes to the issue, it should be
fixed in version 8.0.2 of baresip android app.

**Comment by jroldroyd** [comment]
Thanks.
