### ISSUE TITLE
sound broken when decoder changes

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#727]
If caller mixes PCMU encoded wav file to audio stream of a call using some other codec,
basesip callee hears the sound quite badly broken.

Console shows decoder changes like this:
```
tream: incoming rtp for 'audio' established, receiving from 192.168.43.99:40074
Audio decoder changed payload 105 -> 0
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: player started with sample format S16LE
Audio decoder changed payload 0 -> 105
audio: Set audio decoder: opus 48000Hz 2ch
audio: player started with sample format S16LE
Audio decoder changed payload 105 -> 0
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: player started with sample format S16LE
Audio decoder changed payload 0 -> 105
audio: Set audio decoder: opus 48000Hz 2ch
```
If I replace baresip callee with pjsua, sound is played OK.

**Comment by alfredh** [comment]
I will take a look at this after 0.6.3 is released.

**Comment by alfredh** [comment]
baresip has only one audio decoder instance:

```c
struct aurx {
	/* ... */
	const struct aucodec *ac;     /**< Current audio decoder           */
	struct audec_state *dec;      /**< Audio decoder state (optional)  */
	/* ... */
```

if the payload type of the incoming RTP stream changes, it will
reset the decoder:


```c
	/* Audio payload-type changed? */
	if (hdr->pt != rx->pt) {

		err = update_payload_type(a, rx->pt, hdr->pt);
		if (err)
			return;
	}
```

https://github.com/alfredh/baresip/blob/master/src/audio.c#L683

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> baresip has only one audio decoder instance:
> 
> ```c
> struct aurx {
> 	/* ... */
> 	const struct aucodec *ac;     /**< Current audio decoder           */
> 	struct audec_state *dec;      /**< Audio decoder state (optional)  */
> 	/* ... */
> ```
> 
> if the payload type of the incoming RTP stream changes, it will
> reset the decoder:

So broken sound may be caused by these resets?

If I remember correctly, SIP UA has to be able to receive audio using
any of the codecs it has advertised.  Should there be same number of
decoder instances?

**Comment by alfredh** [comment]
the broken sound is probably because the audio-buffer and audio-player is reset.

the audio-player is reset because the sampling rate of PCMU and Opus is different
(8000 Hz vs 48000 Hz).

PCMU has no state, while Opus decoder has a state.

perhaps there is a work-around if you can force the activation of the
audio resampler, which will use the same sample-rate/channels all the time.

try this in the config:

```
auplay_srate           48000
auplay_channels                2
```

**Comment by juha-h** [comment]
I cannot reproduce the decoder change. Don't anymore remember, how I run the test where it occured.  Thus have to close this.
