### ISSUE TITLE
Finally complied basesip for windows

### ISSUE THREAD

**Issue by fdl33333** [alfredh/baresip#731]
had a lot of problems with vs not finding header files.. ended up by copying all header files of baresip, re, and rem into each of the projects headers directory.
Compliled, runs, but complains "too many open files" everywhere...
Also local-ip is totally WRONG!!! should be 192.168.0.101

baresip v0.6.3 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.
Local network address:  IPv4={61C7CDCB-C6FC-41DC-99D8-1D3B8239A984}|169.254.250.154
fd_listen: fd=1076 flags=0x01 - Max 1024 fds
fd_listen: fd=1076 flags=0x01 - Max 1024 fds
[31mua: SIP Transport failed: Too many open files
[;m[31mua: init failed (Too many open files)
[;mua: stop all (forced=1)

**Comment by alfredh** [comment]
try to increase `FD_SETSIZE` to e.g. 2048

https://github.com/alfredh/baresip/blob/master/mk/win32/baresip.vcxproj#L56

**Comment by fdl33333** [comment]
Thank you very much, it worked … almost …

Can dial, and receive calls ..

But it doesn’t answer on port 8000 and It reports a ridiculous IP address: 169.254.250.154 instead of my IP which is 192.168.0.101
funnily, if I connect to office via VPN, I get correct vpn address which is 10.0.0.3

 

Windows IP Configuration

 

 

Ethernet adapter Ethernet:

 

   Connection-specific DNS Suffix  . :

   IPv4 Address. . . . . . . . . . . : 192.168.0.101

   Subnet Mask . . . . . . . . . . . : 255.255.255.0

   IPv4 Address. . . . . . . . . . . : 192.168.1.101

   Subnet Mask . . . . . . . . . . . : 255.255.255.0

   Default Gateway . . . . . . . . . : 192.168.0.1

 

Ethernet adapter VirtualBox Host-Only Network:

 

   Connection-specific DNS Suffix  . :

   Link-local IPv6 Address . . . . . : fe80::e9bc:fc4a:c456:fa9a%6

   Autoconfiguration IPv4 Address. . : 169.254.250.154

   Subnet Mask . . . . . . . . . . . : 255.255.0.0

   Default Gateway . . . . . . . . . :

 

Ethernet adapter VMware Network Adapter VMnet1:

 

   Connection-specific DNS Suffix  . :

   Link-local IPv6 Address . . . . . : fe80::d5b5:84f:5fc9:2d59%9

   IPv4 Address. . . . . . . . . . . : 192.168.146.1

   Subnet Mask . . . . . . . . . . . : 255.255.255.0

   Default Gateway . . . . . . . . . :

 

Ethernet adapter VMware Network Adapter VMnet8:

 

   Connection-specific DNS Suffix  . :

   Link-local IPv6 Address . . . . . : fe80::6a:1aca:3590:6ae3%5

   IPv4 Address. . . . . . . . . . . : 192.168.44.1

   Subnet Mask . . . . . . . . . . . : 255.255.255.0

   Default Gateway . . . . . . . . . :

 

Ethernet adapter Ethernet 4:

 

   Media State . . . . . . . . . . . : Media disconnected

   Connection-specific DNS Suffix  . :

 

Ethernet adapter Ethernet 2:

 

   Media State . . . . . . . . . . . : Media disconnected

   Connection-specific DNS Suffix  . :

 

 

Baresip output:

 

 

 

baresip v0.6.3 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.

Local network address:  IPv4={61C7CDCB-C6FC-41DC-99D8-1D3B8239A984}|169.254.250.154

aucodec: PCMU/8000/1

aucodec: PCMA/8000/1

aufilt: vumeter

winwave: output devices: 3, input devices: 2

ausrc: winwave

auplay: winwave

vidsrc: dshow

medianat: stun

medianat: turn

medianat: ice

Populated 1 account

Populated 3 contacts

open: ./debug_cmd.dll LoadLibraryA() failed

[31mmodule debug_cmd.dll: No such file or directory

[;mPopulated 2 audio codecs

Populated 1 audio filter

Populated 0 video codecs

Populated 0 video filters

baresip is ready.

1009@192.168.0.234: {0/TCP/v4} 200 OK () [1 binding]

[32mAll 1 useragent registered successfully! (7 ms)[;m

**Comment by fdl33333** [comment]
This could help:

c:\users\fdl\documents\visual studio 2015\projects\re\src\net\net.c(44): warning C4996: 'gethostbyname': Use getaddrinfo() or GetAddrInfoW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings

1>   c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2238): note: see declaration of 'gethostbyname'

2>        

 

From: francesco.delagarda@shenker.it <francesco.delagarda@shenker.it> 
Sent: mercoledì 12 giugno 2019 15:19
To: 'alfredh/baresip' <reply@reply.github.com>; 'alfredh/baresip' <baresip@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [alfredh/baresip] Finally complied basesip for windows (#731)

 

Thank you very much, it worked … almost …

Can dial, and receive calls ..

But it doesn’t answer on port 8000 and It reports a ridiculous IP address: 169.254.250.154 instead of my IP which is 192.168.0.101
funnily, if I connect to office via VPN, I get correct vpn address which is 10.0.0.3

 

Windows IP Configuration

 

 

Ethernet adapter Ethernet:

 

   Connection-specific DNS Suffix  . :

   IPv4 Address. . . . . . . . . . . : 192.168.0.101

   Subnet Mask . . . . . . . . . . . : 255.255.255.0

   IPv4 Address. . . . . . . . . . . : 192.168.1.101

   Subnet Mask . . . . . . . . . . . : 255.255.255.0

   Default Gateway . . . . . . . . . : 192.168.0.1

 

Ethernet adapter VirtualBox Host-Only Network:

 

   Connection-specific DNS Suffix  . :

   Link-local IPv6 Address . . . . . : fe80::e9bc:fc4a:c456:fa9a%6

   Autoconfiguration IPv4 Address. . : 169.254.250.154

   Subnet Mask . . . . . . . . . . . : 255.255.0.0

   Default Gateway . . . . . . . . . :

 

Ethernet adapter VMware Network Adapter VMnet1:

 

   Connection-specific DNS Suffix  . :

   Link-local IPv6 Address . . . . . : fe80::d5b5:84f:5fc9:2d59%9

   IPv4 Address. . . . . . . . . . . : 192.168.146.1

   Subnet Mask . . . . . . . . . . . : 255.255.255.0

   Default Gateway . . . . . . . . . :

 

Ethernet adapter VMware Network Adapter VMnet8:

 

   Connection-specific DNS Suffix  . :

   Link-local IPv6 Address . . . . . : fe80::6a:1aca:3590:6ae3%5

   IPv4 Address. . . . . . . . . . . : 192.168.44.1

   Subnet Mask . . . . . . . . . . . : 255.255.255.0

   Default Gateway . . . . . . . . . :

 

Ethernet adapter Ethernet 4:

 

   Media State . . . . . . . . . . . : Media disconnected

   Connection-specific DNS Suffix  . :

 

Ethernet adapter Ethernet 2:

 

   Media State . . . . . . . . . . . : Media disconnected

   Connection-specific DNS Suffix  . :

 

 

Baresip output:

 

 

 

baresip v0.6.3 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.

Local network address:  IPv4={61C7CDCB-C6FC-41DC-99D8-1D3B8239A984}|169.254.250.154

aucodec: PCMU/8000/1

aucodec: PCMA/8000/1

aufilt: vumeter

winwave: output devices: 3, input devices: 2

ausrc: winwave

auplay: winwave

vidsrc: dshow

medianat: stun

medianat: turn

medianat: ice

Populated 1 account

Populated 3 contacts

open: ./debug_cmd.dll LoadLibraryA() failed

[31mmodule debug_cmd.dll: No such file or directory

[;mPopulated 2 audio codecs

Populated 1 audio filter

Populated 0 video codecs

Populated 0 video filters

baresip is ready.

1009@192.168.0.234 <mailto:1009@192.168.0.234> : {0/TCP/v4} 200 OK () [1 binding]

[32mAll 1 useragent registered successfully! (7 ms)[;m

**Comment by Encamy** [comment]
Hello @fdl33333 
First of all, you do not need to copy all header files into every folder. Check if you have correct folder structure [this link can help you:](https://github.com/creytiv/re/issues/150)
```
some_folder/
|-baresip/
|-re/
|-rem/
|-dirent/
```

For fixing **too many open files** error, use patch https://github.com/creytiv/re/commit/49834b7afd0fe31660108271ef7657a34caa6a6d please

Baresip gets last ip address of all available on your pc. In your case it can pick up ip of a virtual adapter or vpn adapter. Use config parameter `net_interface` for choosing an IP-address which you want to use. For example
> net_interface 192.168.0.101

**Comment by fdl33333** [comment]
Thank you Aleksei!!

II tried that:


didn’t work..
then I went and found myself a dirent.h off the net …

Will try now with your config parameter for network..

 

What’s a good way to run in background/as service in windows at startup?

**Comment by fdl33333** [comment]
Tried that, also enabled the httpd module in config, but it still doesn’t answer to http requests on port 8000

 

Is there any winsock interface? I noticed a section:

# UI Modules

module                                wincons.dll

#module                                             cons.dll

#module                                             evdev.dll

module                                httpd.dll

**Comment by fdl33333** [comment]
Thanks for all advice.. Now baresip runs fine in windows, but wont respond to http:x.x.x.x.x:8000 interface.
I've enabled http in UI Modules:
# UI Modules
module			wincons.dll
#module			cons.dll
#module			evdev.dll
module			httpd.dll


But when I start I get:
"open: ./httpd.dll LoadLibraryA() failed"




baresip v0.6.3 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.
Binding to interface or IP address '192.168.0.101'
Local network address:  IPv4={F425EA94-8292-4D99-B3B8-9F3961D7015E}|192.168.0.101
open: ./httpd.dll LoadLibraryA() failed
[31mmodule httpd.dll: No such file or directory
[;maucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
winwave: output devices: 3, input devices: 2
ausrc: winwave
auplay: winwave
vidsrc: dshow
medianat: stun
medianat: turn
medianat: ice
Populated 1 account
Populated 3 contacts
open: ./debug_cmd.dll LoadLibraryA() failed
[31mmodule debug_cmd.dll: No such file or directory
[;mPopulated 2 audio codecs
Populated 1 audio filter
Populated 0 video codecs
Populated 0 video filters
baresip is ready.
1009@192.168.0.234: {0/TCP/v4} 200 OK () [1 binding]
[32mAll 1 useragent registered successfully! (6 ms)[;m
