### ISSUE TITLE
Baresip Windows httpd interface

### ISSUE THREAD

**Issue by fdl33333** [alfredh/baresip#732]
I have successfully compiled baresip in VS 2015, as per instructions and it runs perfectly (after adjusting the FD_SETSIZE to 2048.

However all attempts to http to port 8000 fail. 
I enabled module hddp in config but on startup baresip reports "httpd.dll not found"

**Comment by alfredh** [comment]
can you please try to upgrade to GIT HEAD and try again ?

(commit d499fa005973d453b5138ac04f71c009e4d8e273)


after git update you need to rebuild from scratch.

**Comment by fdl33333** [comment]
PERFECT!
Worked like a charm first time.. Thank you v much!

**Comment by alfredh** [comment]
thanks for reporting and testing.

Please close the issue if it has been resolved.

**Comment by fdl33333** [comment]
Ofc!

Last question .. how far did you get with we interface, or else any other
way to connect except for “hit-and-run” http?

Francesco Facco de Lagarda


On 14 Jun 2019, at 13:58, Alfred E. Heggestad <notifications@github.com>
wrote:

thanks for reporting and testing.

Please close the issue if it has been resolved.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/alfredh/baresip/issues/732?email_source=notifications&email_token=AJOCQXRT2KZIOZ3BSZ5UWKDP2OBYBA5CNFSM4HYFK5G2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXWSPEQ#issuecomment-502081426>,
or mute the thread

**Comment by alfredh** [comment]
Please note that this Issue tracker is mainly for reporting defects and bugs.

if you want to ask questions, please use the mailing list:
http://lists.creytiv.com/mailman/listinfo/re-devel

you can also try the other management modules like mqtt.so or ctrl_tcp.so

**Comment by alexander-elgin** [comment]
@fdl33333 Do you have binaries working properly in Windows 10 (both 32bit and 64bit if you have)? I met the same issues. The solutions that you applied do not work for me.
I would highly appreciate any assistance with that. I would be glad to provide any kind of donation for such contribution.
