### ISSUE TITLE
how to get email notifications about commits?

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#734]
I have not been able to figure out, how to get email notifications about all commits.  I have checked all boxes in Email notification preferences, but there is no choice for commits.

**Comment by juha-h** [comment]
Found this link:
[https://help.github.com/en/articles/about-email-notifications-for-pushes-to-your-repository](url)
Could re-devel be used as the email address?

**Comment by alfredh** [comment]
just fork the project. See the 4th answer here:

https://stackoverflow.com/questions/9845655/how-do-i-get-notifications-for-commits-to-a-repository

```
6

I just found out by accident that you can easily manage to achieve this:

fork the project (if you haven't done it yet)
create a pull request for yourself from the selected branch, e.g. from master of head project to master of your fork:
base fork: original/project ; base: master ; head fork: your/project ; compare: master
do NOT merge this pull request
under the Email section of your Notifications settings enable:
Comments on Issues and Pull Requests
Pull Request reviews
Pull Request pushes
That's it. You will receive email notifications about every commit on master branch.
```

**Comment by juha-h** [comment]
Thanks.  I'll give it a try although I still don't understand why there does not exist "Commits" choice in notification preferences.
