### ISSUE TITLE
how to feed baresip with audio and video stream from 3rd party

### ISSUE THREAD

**Issue by lifugang** [alfredh/baresip#737]
Dear Alfredh,

I want to and new video(h264) and audio(g711) source which are from 3rd party,

how can I do it? and new module? can you show me an example or give me some guiding?

Thank you very much.

**Comment by Encamy** [comment]
For redirecting audio you can try to use virtual audio cable (VAC). In 3rd party app you should choose VAC as output and in baresip VAC should be choosen as input. Probably it will require additional step with redirecting VAC output to VAC input (VAC have an application named Audio Repeater)

P.S. VAC is a windows application, on linux I think `jack` can be a replacement

**Comment by lifugang** [comment]
> For redirecting audio you can try to use virtual audio cable (VAC). In 3rd party app you should choose VAC as output and in baresip VAC should be choosen as input. Probably it will require additional step with redirecting VAC output to VAC input (VAC have an application named Audio Repeater)
> P.S. VAC is a windows application, on linux I think jack can be a replacement

Thanks for your response, I am develop in embedded linux platform, and there is 3rd party SDK, which can get audio and video stream from low level hardware with diffrent data format as h264,h265,g711 etc, and I want to feed them to baresip ,in order to bring about a SIP Intercom videophone. that is my real requirement. So my difficulty is to compose the streams with baresip.

**Comment by Encamy** [comment]
As I think you need to write an application which will use both baresip as a library and 3rd party SDK as a source of media. Application will transmit data from 3rd party SDK to baresip. Probably you need to write some modules for baresip for passing audio/video data programmatically.
Maybe there is another approach to solve this task, but I don't know it

**Comment by alfredh** [comment]
can you please describe what is the interface between your SDK and baresip ?

i.e. is it a C library, TCP-socket, pipe, shared memory etc ?

**Comment by lifugang** [comment]
Hi, alfredh, the SDK is a library or a module, after run the demo, it can get audio and video stream , then put them in the audio/vedio ring buffer . I can compile sdk and baresip to one application, but how baresip can use data steam from ring buffer , when a remote sipphone call in  ? in fact , I want to know the interface between sdk and baresip

**Comment by alfredh** [comment]
can you please share the header files of your SDK so we can take a look at the interface ?

if your SDK can provide audio PCM samples in S16 or Float format, you have to implement
a new module that is using the `ausrc` api.

you can use the `aufile` module as a template:

https://github.com/alfredh/baresip/blob/master/modules/aufile/aufile.c

**Comment by renaud-sc** [comment]
What you can do is use libre for the SIP part and your SDK/library for all media stuff. I personally use libre + ffmpeg. But ended up having to write my own RTP handler as ffmpeg would not allow me to do symmetric RTP (at least I never found out how). Perhaps others have experience to share with gstreamer ?

**Comment by alfredh** [comment]
please note that this issue tracker is mainly for reporting defects/bugs.

for questions please use the re-devel mailing list.
