### ISSUE TITLE
Support media group/bundle

### ISSUE THREAD

**Issue by billsimon** [alfredh/baresip#738]
Feature request: Support media group/BUNDLE which is becoming popular especially in webrtc environments for multiplexing RTP streams on a single port. IETF draft https://tools.ietf.org/html/draft-ietf-mmusic-sdp-bundle-negotiation-54

**Comment by alfredh** [comment]
thanks for your input.

The goal for baresip is to become fully compatible with WebRTC protocols.
(i.e. not a browser, but a webrtc endpoint).

so adding Bundle is one thing that we would have to do.

do you have any suggestions for other WebRTC related protocols
that we should add support for ?

**Comment by billsimon** [comment]
Thanks for your reply. I am not aware of anything else that is missing.

**Comment by alfredh** [comment]
Can you please describe a bit more details about your use-case and environment ?

This is useful to understand before we start implementing Bundle.

I added the item to the Roadmap:

https://github.com/alfredh/baresip/wiki/Roadmap

**Comment by billsimon** [comment]
I am looking for a lightweight b2bua that can interwork webrtc and classic SIP and which includes bundle support. The only one I know of now is Asterisk.

**Comment by alfredh** [comment]
have you tested baresip with webrtc? it might be good to test the basics first
and see if that is working, before adding bundle.

please note that the only signaling protocol supported (currently) is SIP.
are you also planning to run a SIP stack in your Web browser ?
it is not possible to make a pure webrtc connection (peer connection).

BTW: The Janus Gateway is a project for a gateway between WebRTC
and other protocols like SIP, have you tried this:

https://janus.conf.meetecho.com

**Comment by alfredh** [comment]
thanks for your input, the feature request is now on the roadmap
so I will close this issue (issues are mainly for reporting bugs).
