### ISSUE TITLE
Minimal "hello world" example for baresip to baresip connection, same machine

### ISSUE THREAD

**Issue by fluffynukeit** [alfredh/baresip#741]
Hi.  I'm trying to evaluate baresip but I am having a lot of trouble getting anything working beyond "/play ring.wav".  I would like to narrow the scope to make sure things are working at the very lowest level.  Could you please provide instructions on how to configure baresip and execute the following scenario?

1. Start baresip in terminal A and select useragent A.
2. Start baresip in terminal B on the same machine and select useragent B.
3. Do not run any registrar server like freeswitch.
4. Have useragent B call useragent A (same machine, same IP address, etc).

Here is what I have tried to with no success.  In both terminals, I called "baresip" from the command line with no arguments.  IP 192.168.7.142 is my IP as reported by ifconfig.  I am running on Ubuntu 18.04 running on VirtualBox inside a company network.

Terminal A
```
baresip v0.5.7 Copyright (C) 2010 - 2017 Alfred E. Heggestad et al.
Local network address:  IPv4=enp0s3:192.168.7.142 
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
ausrc: alsa
auplay: alsa
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
medianat: stun
medianat: turn
medianat: ice
Populated 2 accounts
Populated 3 contacts
Populated 2 audio codecs
Populated 1 audio filter
Populated 3 video codecs
Populated 0 video filters
baresip is ready.
/uanext
ua: sip:test@192.168.7.142
--- sip:test@192.168.7.142 ---
 nrefs:     1
 cuser:     test-0x559a53de0d00
 pub-gruu:  
 af:        AF_INET
 Supported: gruu

Account:
 address:      <sip:test@192.168.7.142>;auth_pass=none;regint=0
 luri:         sip:test@192.168.7.142
 aor:          sip:test@192.168.7.142
 dispname:     
 answermode:   manual
 auth_user:    test
 mediaenc:     none
 medianat:     none
 ptime:        20
 regint:       0
 pubint:       0
 regq:         
 rtpkeep:      
 sipnat:       
 stunserver:   stun:test@192.168.7.142:0
```

Terminal B:

```
baresip v0.5.7 Copyright (C) 2010 - 2017 Alfred E. Heggestad et al.
Local network address:  IPv4=enp0s3:192.168.7.142 
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
ausrc: alsa
auplay: alsa
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
medianat: stun
medianat: turn
medianat: ice
Populated 2 accounts
Populated 3 contacts
Populated 2 audio codecs
Populated 1 audio filter
Populated 3 video codecs
Populated 0 video filters
baresip is ready.
/ 
--- sip:danielaustin@192.168.7.142 ---
 nrefs:     1
 cuser:     danielaustin-0x55aec1b98bf0
 pub-gruu:  
 af:        AF_INET
 Supported: gruu

Account:
 address:      <sip:danielaustin:danielaustin@192.168.7.142>;auth_pass=none;regint=0
 luri:         sip:danielaustin@192.168.7.142
 aor:          sip:danielaustin@192.168.7.142
 dispname:     
 answermode:   manual
 auth_user:    danielaustin
 mediaenc:     none
 medianat:     none
 ptime:        20
 regint:       0
 pubint:       0
 regq:         
 rtpkeep:      
 sipnat:       
 stunserver:   stun:danielaustin@192.168.7.142:0
/dial test@192.168.7.142
call: connecting to 'sip:test@192.168.7.142'..
sip:test@192.168.7.142: session closed: Connection timed out
```

I have also tried to call the test SIP endpoint sip:201@ideasip.com.  The call is established but there is no audio and apparently no bits sent.  I figured my company network might be to blame (NAT), which is why I wanted to do terminal-to-terminal call on the same machine to avoid problems crossing network or machine boundaries:
```
baresip v0.5.7 Copyright (C) 2010 - 2017 Alfred E. Heggestad et al.
Local network address:  IPv4=enp0s3:192.168.7.142 
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
ausrc: alsa
auplay: alsa
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
medianat: stun
medianat: turn
medianat: ice
Populated 2 accounts
Populated 3 contacts
Populated 2 audio codecs
Populated 1 audio filter
Populated 3 video codecs
Populated 0 video filters
baresip is ready.
/dial sip:201@ideasip.com
call: connecting to 'sip:201@ideasip.com'..
call: SIP Progress: 100 trying -- your call is important to us (/)
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: player started with sample format S16LE
audio: Set audio encoder: PCMU 8000Hz 1ch
audio: source started with sample format S16LE
audio tx pipeline:        alsa ---> vumeter ---> PCMU
audio rx pipeline:        alsa <--- vumeter <--- PCMU
danielaustin@192.168.7.142: Call established: sip:201@ideasip.com
[0:00:30] audio=0/0 (bit/s)
sip:201@ideasip.com: session closed: Connection reset by peer
```

**Comment by GGGO** [comment]
Hi,
you need to configure baresip to listen for incoming connection, see `sip_listen` in your config file.

**Comment by fluffynukeit** [comment]
Thanks, but how do I configure baresip A to listen on a different address compared to baresip B when both use the same config file?  If I uncomment the `sip_listen` line in my config file, then start baresip A then baresip B, I get the following error on baresip B.

```
ua: SIP Transport failed: Address already in use
ua: init failed (Address already in use)
```
Is there a way to override the config file variables individually, or is the only way to change configs for different baresip instances to use the -f CLI option to specify an entirely different config file?  Thank you for your help.

**Comment by juha-h** [comment]
Daniel Austin writes:

> Is there a way to override the config file variables individually, or
> is the only way to change configs for different baresip instances to
> use the -f CLI option to specify an entirely different config file?
> Thank you for your help.

Use two baresip configuration directories and -f option.

**Comment by fluffynukeit** [comment]
Holy moly, you guys are fast!

**Comment by fluffynukeit** [comment]
Here are the steps for the minimal example for future reference to anyone coming across this thread.  My username in this test is danielaustin.  I am not certain all of these steps and changes are 100% required but it is what I got working.

1. Start `baresip` and stop it with ctrl C to generate the default ~/.baresip configuration files if they don't exist already.
2. Edit the ~/.baresip/accounts file to uncomment the last line with a default user agent.  Change the @ to `0.0.0.0`.  Also add auth_pass=none and regint=0 like this: `<sip:danielaustin:danielaustin@0.0.0.0>;auth_pass=none;regint=0`
3. Copy baresip config.  `cp -r ~/.baresip ~/.baresiplisten`
4. Modify ~/.baresiplisten/config to uncomment the `sip_listen` line.
5. Check to ensure that you have a microphone hooked up and getting audio levels out of it.  If you don't have a working audio source, the call will connect but not transmit data and baresip will hang after the call.  See #62 
5. In terminal A, run `baresip -f ~/.baresiplisten`.  In terminal B, run `baresip`
6. In terminal B, execute baresip command `/dial danielaustin`.  You should hear an audio indication that the phone is ringing.
7.  In terminal A, hit `a` to accept the call.  Either terminal can hit `b` to hang up.

**Comment by juha-h** [comment]
Daniel Austin writes:

> 2. Edit the ~/.baresip/accounts file to uncomment the last line with a
> default user agent.  Change the @ to `0.0.0.0`.  Also add
> auth_pass=none and regint=0 like this:
> `<sip:danielaustin:danielaustin@0.0.0.0>;auth_pass=none;regint=0`

You should not need :danielaustin.  That used to be auth_pass.
