### ISSUE TITLE
which "Invalid argument"?

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#743]
Sometimes registering fails with this kind of error:
```
06-27 10:41:44.865 14382 14382 D ua event (REGISTERING) 
06-27 10:41:44.867 14382 14382 D ua event (REGISTER_FAIL) Invalid argument
```
The error message is not very useful, because it doesn't tell, which argument is invalid. How to find out, which argument it was?

**Comment by alfredh** [comment]
the error message is most likely printed with %m formatting, which maps to `errno`.

here is a couple of places where `UA_EVENT_REGISTER_FAIL` can come from:

reg.c:

```c
	if (err) {
		warning("reg: %s: Register: %m\n", ua_aor(reg->ua), err);

		reg->scode = 999;

		ua_event(reg->ua, UA_EVENT_REGISTER_FAIL, NULL, "%m", err);
		return;
	}
```

ua.c:

```
	for (le = ua->regl.head, i=0; le; le = le->next, i++) {
		struct reg *reg = le->data;

		err = reg_register(reg, reg_uri, params,
				   acc->regint, acc->outboundv[i]);
		if (err) {
			warning("ua: SIP register failed: %m\n", err);

			ua_event(ua, UA_EVENT_REGISTER_FAIL, NULL, "%m", err);
			goto out;
		}
	}
```

in both cases it prints a warning before the event, do you see any warnings in your logs?

you can also try to add additional debug lines in the relevant code, so see where the
event is coming from.

**Comment by juha-h** [comment]
The warning message doesn't tell anything more.  Perhaps it reg_register should print a warning message if it kwows which argument is invalid.

I cannot reprodude this failure, but have seen it a few times.  I suspect that I may have something to do with network connection/dns servers changing.

**Comment by alfredh** [comment]
you are welcome to add more logging and checking for valid arguments, if you wish.

you can also add some extra text to the last ua_event parameter,
for example:

```c
"%m", err
```

becomes

```c
"reg_register error (%m)", err
```

**Comment by juha-h** [comment]
I checked re/sipreg/reg.c and if Invalid argument is same as EINVAL,
there exist many places where the error can come from.

I'll close this now and try to find, how to reproduce the issue.  Then I can start adding
more warning messages.

After registration fails due to this issue, I need to restart baresip in order to get the registration succeed again.

**Comment by juha-h** [comment]
I added debug logging all over the place in re registration related code and found that invalid argument error comes from this place in re/src/sip/request.c sip_request() function:
```
	else if (route->port) {

		req->port = sip_transp_port(req->tp, route->port);
		err = addr_lookup(req, req->host);
		if (err)
			DEBUG_WARNING("addr_lookup failed\n");
	}
```
Most likely it happens when DNS server information is not correct.  I can update DNS servers from system when registration fails with "invalid argument" error, but also other problems can generate the same error result.

I guess by design, re keeps the actual cause of the errors deep in its pockets rather than revealing it via its API to applications.

**Comment by alfredh** [comment]
you can check if you have a working DNS client:

1. check if sip stack has a pointer to valid `struct dnsc`

2. check that `struct dnsc` has a list of valid nameservers (at least one).

baresip `net.c` has a 60 seconds timer that keeps refreshing
the DNS servers:

```c
/*
 * Detect changes in IP address(es)
 */
static void ipchange_handler(void *arg)
{
	struct network *net = arg;
	bool change;

	tmr_start(&net->tmr, net->interval * 1000, ipchange_handler, net);

	dns_refresh(net);

	change = net_check(net);
	if (change && net->ch) {
		net->ch(net->arg);
	}
}
```
