### ISSUE TITLE
TLS using baresip

### ISSUE THREAD

**Issue by mrcasablr** [alfredh/baresip#745]
I'm evaluating Asterisk with baresip on android and would like to use TLS with self-signed certificates. I was wondering how to enable TLS on android and if we can import a CA.

**Comment by juha-h** [comment]
mrcasablr writes:

> I'm evaluating Asterisk with baresip on android and would like to use
> TLS with self-signed certificates. I was wondering how to enable TLS
> on android and if we can import a CA.

If you are writing your own Android app. you can add to config
sip_certificate and sip_cafile variables.

**Comment by alfredh** [comment]
to enable TLS you need to add ;transport=tls to your SIP account:

```
<sip:user@domain;transport=tls>
```

or configure your domain to enable TLS records.

in `config` the `sip_cafile` should point to the local CA file or your self-signed cert:

```
sip_cafile              /etc/ssl/cert.pem
```

**Comment by alfredh** [comment]
@mrcasablr does it answer your questions ?

**Comment by alfredh** [comment]
I assume that the above text answers your questions ..

if something is unclear please use the re-devel mailing list for questions.
