### ISSUE TITLE
404 not found error incoming call to baresip

### ISSUE THREAD

**Issue by shantanubanerjee** [alfredh/baresip#746]
Hello,
I have compiled baresip and configured successfully. Outgoing call is working fine in baresip but when I am trying to check a incoming call then no incoming call received. And having SIP response code 404 user not found in other sip client. 

Here is my account info
<sip:shano@sip.xxx.org:5060;transport=tcp>;auth_pass=secret

**Comment by GGGO** [comment]
Hi,
first, you have to know who is sending the 404 Not found, baresip or your registrar ? Check that with tcpdump.

baresip will answer with 404 Not found if the URI.user does not match with shano.
A registrar could answer with 404 Not found if shano is not registered.

**Comment by alfredh** [comment]
@shantanubanerjee can you please provide:

1. baresip log
2. wireshark/ngrep log

**Comment by shantanubanerjee** [comment]
[wireshark.log](https://github.com/alfredh/baresip/files/3349973/wireshark.log)
[baresip.log](https://github.com/alfredh/baresip/files/3349974/baresip.log)

**Comment by shantanubanerjee** [comment]
> [wireshark.log](https://github.com/alfredh/baresip/files/3349973/wireshark.log)
> [baresip.log](https://github.com/alfredh/baresip/files/3349974/baresip.log)
> 
> It is rejected from REGISTER server. No packet coming during incoming. There also a unauthorized 401 in SIP registration.
> 
> Account :
> sip:shano_test2@sip.linphone.org:5060;transport=tcp;auth_user=shano_test2;auth_pass=xxxxx

**Comment by alfredh** [comment]
do you also have a trace of the SIP INVITE messages ?

most likely the TCP connection from baresip to the SIP server times out
after a while.

you can try to enable SIP outbound in accounts to keep the TCP connection alive:

```
;sipnat=outbound
```

**Comment by shantanubanerjee** [comment]
> do you also have a trace of the SIP INVITE messages ?
> 
> most likely the TCP connection from baresip to the SIP server times out
> after a while.
> 
> you can try to enable SIP outbound in accounts to keep the TCP connection alive:
> 
> ```
> ;sipnat=outbound
> ```

If don't have trace but when I try with ;sipnat=outbound not able to register and no packets as well.

**Comment by alfredh** [comment]
you need to make sure that the TCP connection is kept alive, either from client or from server.

you can try setting the registration interval to a lower value, for example 60 seconds:

```
<sip:user@domain>;auth_pass=XXX;regint=60
```

if this does not work, then please use tcpdump/wireshark to capture a full
trace from baresip to server, including all TCP packets.

**Comment by shantanubanerjee** [comment]
> you need to make sure that the TCP connection is kept alive, either from client or from server.
> 
> you can try setting the registration interval to a lower value, for example 60 seconds:
> 
> ```
> <sip:user@domain>;auth_pass=XXX;regint=60
> ```
> 
> if this does not work, then please use tcpdump/wireshark to capture a full
> trace from baresip to server, including all TCP packets.

Try with ;regint=60 and ;sipnat=outbound no registration. I have captured wireshark pcap could you please check
[trace.zip](https://github.com/alfredh/baresip/files/3350171/trace.zip)

**Comment by alfredh** [comment]
the trace.zip only contains bogus packets.

you can try to use the `tcpdump` command:

```
$ sudo tcpdump -pni eth0 -w foo.pcap port 5060
```

please provide the exact SIP accounts file that you have used.

please conduct the test with these steps:

1. start tcpdump
2. start baresip
3. wait 5 minutes
4. stop tcpdump

after the test is done, please upload the pcap file here.
(and also baresip config and log).

**Comment by shantanubanerjee** [comment]
> the trace.zip only contains bogus packets.
> 
> you can try to use the `tcpdump` command:
> 
> ```
> $ sudo tcpdump -pni eth0 -w foo.pcap port 5060
> ```
> 
> please provide the exact SIP accounts file that you have used.
> 
> please conduct the test with these steps:
> 
>     1. start tcpdump
> 
>     2. start baresip
> 
>     3. wait 5 minutes
> 
>     4. stop tcpdump
> 
> 
> after the test is done, please upload the pcap file here.
> (and also baresip config and log).

[dump.zip](https://github.com/alfredh/baresip/files/3350275/dump.zip)

[config.zip](https://github.com/alfredh/baresip/files/3350282/config.zip)
[baresip.log](https://github.com/alfredh/baresip/files/3350285/baresip.log)

Please find the attachment.

**Comment by alfredh** [comment]
the dump.zip pcap trace is empty (no packets).

I think you need to use port 5228 instead. do you also have a copy 
of `~/.baresip/accounts` ?

**Comment by shantanubanerjee** [comment]
> the dump.zip pcap trace is empty (no packets).
> 
> I think you need to use port 5228 instead. do you also have a copy
> of `~/.baresip/accounts` ?

I also believe some port related problem is happening, because outgoing call is fine but incoming call having some problem.

Please let me check and I will update

**Comment by shantanubanerjee** [comment]
> the dump.zip pcap trace is empty (no packets).
> 
> I think you need to use port 5228 instead. do you also have a copy
> of `~/.baresip/accounts` ?

No luck. During baresip incoming call always the other sip agent getting user not found from REGISTER server. I don't know but it might related to issue with registration.

**Comment by GGGO** [comment]
You may have a NAT problem. It could be you router or your flexisip configuration.
So be sure to disable SIP nat helper ou SIP ALG in your gateway/router, or configure baresip with TLS support, it will prevent the router to change anything in the SIP protocol.

Look your `SIP/2.0 200 Registration successful`, the contact header should be:
Contact: sip:shano_test2-0x1c26e50@**192.168.43.177**:5060;transport=tcp;expires=3770;+sip.instance="urn:uuid:11d4b060-a47d-0bec-4e09-58efb5a84e98"

**Comment by alfredh** [comment]
this is a bit strange. I have created 2 accounts on sip.linphone.org and tested
outgoing and incoming calls, it is working just fine.

I suggest you try the following:

* create 2 SIP accounts on a different SIP service, then test outgoing/incoming calls

* try to use SIP over TLS transport (`;transport=tls`) which should disable any
  local SIP ALGs (if present).

**Comment by alfredh** [comment]
my apologies, I have tested again with 2 different accounts on sip.linphone.org

the result is the same as you, when calling from A to B the linphone server
replies with 404 Not Found.

You need to contact the sip.linphone.org provider and report the bug to them.
This is not a bug in baresip as it is working with multiple other SIP providers
like antisip, sip2sip, iptel, sipgate.

Alfred
