### ISSUE TITLE
ctrl_tcp doesn't raise CALL_CLOSED if call_id not set

### ISSUE THREAD

**Issue by trampster** [alfredh/baresip#747]
If the call fails to setup because of a TURN failure then when CALL_CLOSED is raised the call_id has not been set yet, this results in null being passed to odict_entry_add which returns err=22. This results in an early exit without a warning in ctrl_tcp.c event_encode_dict.

As a result CALL_CLOSED is not raised by ctrl_tcp.

A fix is needed to event.c to check for a null call_id and not include it if null.

I also suggest adding a warning to the the early exit in ctrl_tcp.c

**Comment by alfredh** [comment]
fixed in

https://github.com/alfredh/baresip/pull/748
