### ISSUE TITLE
I can dial number but I dont know about incoming call 

### ISSUE THREAD

**Issue by ondralie** [alfredh/baresip#751]
Hi,
I can dial number inside LAN but I dont know about incoming call.
Baresip can call but it is not ready to receive it call.

Version: Baresip 0.6.1
Machine: RPi 3

Can you help me please?

`baresip v0.6.1 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.
Local network address:  IPv4=eth0:192.168.2.120
ui: stdio
evdev: device name: FaceCam 1000X: FaceCam 1000X
Supported event types:
  Event type 0x00  (Unknown event type: 0x0000)
  Event type 0x01  (Keys or Buttons)
Supported Keys:
  Key  0xd4  (Unknown key)
Supported LEDs:
ui: evdev
ui: http
httpd: listening on 0.0.0.0:8000
aucodec: G722/16000/1
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
ausrc: alsa
auplay: alsa
avcodec: using libavcodec H.264 encoder
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidcodec: H264
gst_video: using gstreamer (GStreamer 1.14.4)
vidfilt: selfview_window
vidsrc: v4l2
v4l2_codec inited
vidcodec: H264
vidsrc: v4l2_codec
vidsrc: avformat
vidsrc: x11grab
vidisp: x11
medianat: stun
uuid: loaded UUID 1be2e7bb-6b6e-1617-b60d-e1080a622925 from file /root/.baresip/uuid
8003@192.168.2.230: Using sipnat: `outbound'
Populated 1 account
module: loading app auloop.so
module: loading app contact.so
Populated 1 contacts
module: loading app debug_cmd.so
module: loading app menu.so
module: loading app vidloop.so
Populated 3 audio codecs
Populated 1 audio filter
Populated 5 video codecs
Populated 1 video filter
baresip is ready.
8003@192.168.2.230: {1/UDP/v4} 200 OK () [1 binding]
All 1 useragent registered successfully! (48 ms)
`

config:
`
# Core 
poll_method             epoll

# SIP 
sip_trans_bsize         128
sip_listen              0.0.0.0:5060

# Call
call_local_timeout      120
call_max_calls  4

# Audio 
audio_player            alsa,default
audio_source            alsa,plughw:1,0
audio_alert             alsa,default
audio_srate             8000-48000
audio_channels          1-2
ausrc_srate             48000
auplay_srate            48000
ausrc_channels          1
ausrc_format            s16 #s16|float|s24_3le

# AVT - Audio/Video Transport
rtp_tos                 184
rtcp_enable             yes
rtcp_mux                no
jitter_buffer_delay     5-10            # frames
rtp_stats               no

module_path             /usr/lib/baresip/modules

# UI Modules
module                  stdio.so
#module                 cons.so
module                  evdev.so
module                  httpd.so

# Audio codec Modules (in order)
module                  g722.so
#module                 g726.so
module                  g711.so

# Audio filter Modules (in encoding order)
module                  vumeter.so

# Media NAT modules
module                  stun.so

# Temporary Modules (loaded then unloaded)
module_tmp              uuid.so
module_tmp              account.so

# Application Modules

module_app              auloop.so
module_app              contact.so
module_app              debug_cmd.so
module_app              menu.so
module_app              vidloop.so

# Module parameters
cons_listen             0.0.0.0:5555
http_listen             0.0.0.0:8000
evdev_device            /dev/input/event0

`

accounts:
`8003 <sip:8003@192.168.2.230:5060>;answermode=auto;auth_user=8003;auth_pass=XXXX;sipnat=outbound;outbound="sip:192.168.2.230:5060";regint=120;video_codecs=h264;pubint=1;reqq=5
`

**Comment by GGGO** [comment]
Please use the mailing list for help [http://lists.creytiv.com/mailman/listinfo/re-devel](url)
Run baresip with 'v' option to get verbose debug and use ngrep to get SIP traffic for your incoming call.

**Comment by ondralie** [comment]
Thank you.

Baresip LOG:

`baresip v0.6.1 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.
Local network address:  IPv4=eth0:192.168.2.120
ui: stdio
evdev: device name: FaceCam 1000X: FaceCam 1000X
Supported event types:
  Event type 0x00  (Unknown event type: 0x0000)
  Event type 0x01  (Keys or Buttons)
Supported Keys:
  Key  0xd4  (Unknown key)
Supported LEDs:
ui: evdev
ui: http
httpd: listening on 0.0.0.0:8000
aucodec: G722/16000/1
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
ausrc: alsa
auplay: alsa
avcodec: using libavcodec H.264 encoder
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidcodec: H264
gst_video: using gstreamer (GStreamer 1.14.4)
vidfilt: selfview_window
vidsrc: v4l2
v4l2_codec inited
vidcodec: H264
vidsrc: v4l2_codec
vidsrc: avformat
vidsrc: x11grab
vidisp: x11
medianat: stun
uuid: loaded UUID 1be2e7bb-6b6e-1617-b60d-e1080a622925 from file /root/.baresip/uuid
8003@192.168.2.230: Using sipnat: `outbound'
Populated 1 account
module: loading app auloop.so
module: loading app contact.so
Populated 1 contacts
module: loading app debug_cmd.so
module: loading app menu.so
module: loading app vidloop.so
Populated 3 audio codecs
Populated 1 audio filter
Populated 5 video codecs
Populated 1 video filter
baresip is ready.
8003@192.168.2.230: {1/UDP/v4} 200 OK () [1 binding]
All 1 useragent registered successfully! (38 ms)
`

ngrep output while dialing from other client:

`interface: any
filter: ( port 5060 ) and (ip || ip6)
#
U 192.168.2.120:5060 -> 192.168.2.230:5060 #1
REGISTER sip:192.168.2.230:5060 SIP/2.0.
Via: SIP/2.0/UDP 192.168.2.120:5060;branch=z9hG4bK1305633f39ac6c12;rport.
Contact: <sip:8003-0x17a2c08@192.168.2.120:5060>;expires=120;+sip.instance="<urn:uuid:1be2e7bb-6b6e-1617-b60d-e1080a622925>";reg-id=1.
Max-Forwards: 70.
Route: <sip:192.168.2.230:5060;lr>.
To: <sip:8003@192.168.2.230:5060>.
From: "8003" <sip:8003@192.168.2.230:5060>;tag=3e0bbfbc8acf69aa.
Call-ID: 63c9ccc1498ada07.
CSeq: 6495 REGISTER.
User-Agent: baresip v0.6.1 (arm6/linux).
Supported: gruu, outbound, path.
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER.
Content-Length: 0.
.

#
U 192.168.2.230:5060 -> 192.168.2.120:5060 #2
SIP/2.0 401 Unauthorized.
Via: SIP/2.0/UDP 192.168.2.120:5060;branch=z9hG4bK1305633f39ac6c12;rport=5060.
From: "8003" <sip:8003@192.168.2.230:5060>;tag=3e0bbfbc8acf69aa.
To: <sip:8003@192.168.2.230:5060>;tag=1048025483.
Call-ID: 63c9ccc1498ada07.
CSeq: 6495 REGISTER.
WWW-Authenticate: Digest realm="VDP", nonce="06b151b88a54ff15fb7fc885038904f5", algorithm=MD5.
User-Agent: Dahua UAS/3.0 VTO2101E.
Content-Length: 0.
.

#
U 192.168.2.120:5060 -> 192.168.2.230:5060 #3
REGISTER sip:192.168.2.230:5060 SIP/2.0.
Via: SIP/2.0/UDP 192.168.2.120:5060;branch=z9hG4bK7663c58d21314ba8;rport.
Contact: <sip:8003-0x17a2c08@192.168.2.120:5060>;expires=120;+sip.instance="<urn:uuid:1be2e7bb-6b6e-1617-b60d-e1080a622925>";reg-id=1.
Max-Forwards: 70.
Authorization: Digest username="8003", realm="VDP", nonce="06b151b88a54ff15fb7fc885038904f5", uri="sip:192.168.2.230:5060", response="a0303e2c0cc41b7d0f961fbfb9ccf6b2".
Route: <sip:192.168.2.230:5060;lr>.
To: <sip:8003@192.168.2.230:5060>.
From: "8003" <sip:8003@192.168.2.230:5060>;tag=3e0bbfbc8acf69aa.
Call-ID: 63c9ccc1498ada07.
CSeq: 6496 REGISTER.
User-Agent: baresip v0.6.1 (arm6/linux).
Supported: gruu, outbound, path.
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER.
Content-Length: 0.
.

#
U 192.168.2.230:5060 -> 192.168.2.120:5060 #4
SIP/2.0 200 OK.
Via: SIP/2.0/UDP 192.168.2.120:5060;branch=z9hG4bK7663c58d21314ba8;rport=5060.
From: "8003" <sip:8003@192.168.2.230:5060>;tag=3e0bbfbc8acf69aa.
To: <sip:8003@192.168.2.230:5060>;tag=1439394264.
Call-ID: 63c9ccc1498ada07.
CSeq: 6496 REGISTER.
Contact: <sip:8003-0x17a2c08@192.168.2.120:5060>;expires=120;+sip.instance="<urn:uuid:1be2e7bb-6b6e-1617-b60d-e1080a622925>";reg-id=1.
User-Agent: Dahua UAS/3.0 VTO2101E.
Expires: 60.
Date: Fri,12 Jul 2019 09:04:06 UTC.
Content-Length: 0.
.

`

**Comment by GGGO** [comment]
Here you have `REGISTER sip:192.168.2.230:5060 SIP/2.0.`, so 8003 is well registered.
But there is no `INVITE sip:8003@192.168.2.120:5060 SIP/2.0`, so no incoming call on RPI3.
You should do ngrep on the server too, I mean on 192.168.2.230.

**Comment by ondralie** [comment]
Server is simple door station. I cannot run ngrep or something like that :(. 
SIP server: https://uk.dahuasecurity.com/uk/products/productDetail/21847

I think that is problem with communication protocol between baresip and SIP server. If I connected windows client and android client on sip server. Everything working ok. But I have problem just with baresip.

**Comment by GGGO** [comment]
Try with a simple account like this:
<sip:8003@192.168.2.230:5060>;answermode=auto;auth_user=8003;auth_pass=XXXX;regint=120
Maybe the door station does not like outbound mode.

**Comment by ondralie** [comment]
Still same :(. 
Any other idea, please? :)

**Comment by GGGO** [comment]
hmm, maybe the door station does not like the contact header:
Contact: sip:**8003-0x17a2c08**@192.168.2.120:5060, but there is no configuration setting for that, you have to change the source code.

**Comment by GGGO** [comment]
Edit src/ua.c, in `int ua_alloc(struct ua **uap, const char *aor)`
change:
`err = re_sdprintf(&ua->cuser, "%r-%p", &ua->acc->luri.user, ua);`
for this:
`err = re_sdprintf(&ua->cuser, "%r", &ua->acc->luri.user);`
And compile again.

**Comment by ondralie** [comment]
I did it but without success :(

`#
U 192.168.2.120:57392 -> 192.168.2.230:5060 #3
REGISTER sip:192.168.2.230:5060 SIP/2.0.
Via: SIP/2.0/UDP 192.168.2.120:57392;branch=z9hG4bK50b7da476251eb93;rport.
Contact: <sip:8003@192.168.2.120:57392>;expires=120;+sip.instance="<urn:uuid:1be2e7bb-6b6e-1617-b60d-e1080a622925>".
Max-Forwards: 70.
Authorization: Digest username="8003", realm="VDP", nonce="ada06a57a6ef02d299a713e2ad9ed922", uri="sip:192.168.2.230:5060", response="6234eb986507f01968a15eec7b8d8b80".
To: <sip:8003@192.168.2.230:5060>.
From: <sip:8003@192.168.2.230:5060>;tag=3cc47b346307e236.
Call-ID: 3fbbdb09670109e6.
CSeq: 17199 REGISTER.
User-Agent: baresip v0.6.3 (arm6/linux).
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER.
Content-Length: 0.
.

#
U 192.168.2.230:5060 -> 192.168.2.120:57392 #4
SIP/2.0 200 OK.
Via: SIP/2.0/UDP 192.168.2.120:57392;branch=z9hG4bK50b7da476251eb93;rport=57392.
From: <sip:8003@192.168.2.230:5060>;tag=3cc47b346307e236.
To: <sip:8003@192.168.2.230:5060>;tag=1670772006.
Call-ID: 3fbbdb09670109e6.
CSeq: 17199 REGISTER.
Contact: <sip:8003@192.168.2.120:57392>;expires=120;+sip.instance="<urn:uuid:1be2e7bb-6b6e-1617-b60d-e1080a622925>".
User-Agent: Dahua UAS/3.0 VTO2101E.
Expires: 60.
Date: Fri,12 Jul 2019 15:46:09 UTC.
Content-Length: 0.
`

**Comment by GGGO** [comment]
You said that it works for windows client and android client. So, grab the SIP traffic from one of them to compare with baresip.
Maybe it's time to ask help from the door station support :)

**Comment by ondralie** [comment]
Ok, I will try it.
I already contacted door station support but it is for long time :(.
Thank you very much for help.

**Comment by GGGO** [comment]
And do your test from a machine that you sure it works. Like your windows client or your android client. In case of network problem...

**Comment by alfredh** [comment]
please report this bug to your SIP server provider.

this is not a bug in baresip.
