### ISSUE TITLE
Digest Auth

### ISSUE THREAD

**Issue by akleymenov** [alfredh/baresip#757]
Hello!
How setting digest auth for sip acc?
Password auth work fine.

**Comment by alfredh** [comment]
hi @akleymenov 

what do you mean with "digest auth" ?

to specify your SIP account password use the `auth_pass` parameter:

```
<sip:user@domain.com>;auth_pass=XXXX
```

**Comment by alfredh** [comment]
please use the mailing-list for questions:

http://lists.creytiv.com/mailman/listinfo/re-devel

(This Issues tracker is mainly for reporting bugs and defects).
