### ISSUE TITLE
Callcontrol trough SIP (answer/hold/unhold)

### ISSUE THREAD

**Issue by jnaeff** [alfredh/baresip#758]
We are playing with the Baresip client on raspberry. The experience is directly really great! This makes it possible to put the audio through the raspberry and the interface on the Remote Desktop Client. This way you get great audio and interface experience. The only thing we are missing is some commands to control the call completely through SIP. The commands are Answer, Hold and Unhold. If we have these commands we can control the phone completely. 

The specific documentation you can find [here](http://lists.digium.com/pipermail/asterisk-dev/attachments/20080102/25aaa8a1/attachment-0001.pdf). You need to look into chapter 5 (answer) and 6 (hold).

Is it possible for you guys to implement this? We are also able to pay a little bit of money for this functionality.

**Comment by alfredh** [comment]
the referenced document is a Broadsoft SIP server.

it is not really clear to me what do you are doing or what you are trying to achieve?
is there a bug somewhere that should be fixed ?

are you asking us to implement a new feature ?

can you please describe properly here in the issue what you want to achieve ?

**Comment by jnaeff** [comment]
_it is not really clear to me what do you are doing or what you are trying to achieve?_
We want to run Baresip as a daemon on the Raspberry PI. We want to build a desk phone based on that without a display.  To control Baresip on the Raspberry PI we want to use sip commands todo call control.  We only miss the commands (answer/hold/unhold) to make this possible. We do already this trick with desk phones (Yealink and Snom ). We can control the complete phone from our platform through SIP without using, for example, using the Embedded web-server with HTTP interface or the Command-line console over UDP/TCP. We think it is nice that you reuse the   SIP session that you have already with the platform. 

_is there a bug somewhere that should be fixed ?_
No, it is a new feature. 

_are you asking us to implement a new feature ?_
See the answer above.

_can you please describe properly here in the issue what you want to achieve ?_
We want to have solutions for our client that don't want to have a desk phone. And with the solution with Baresip running native on the Raspberry PI we think we have a great solution. The audio goes directly through the Rasperry with Baresip and you can control your Phone (Rasperry) trough sip for example on a remote desktop without audio issues.

**Comment by alfredh** [comment]
I think this feature is a bit product spesific, and probably outside the scope
for a generic SIP client.

it is probably better if you use the mailing list to ask this question
if anyone can help you. Baresip is a open source project with contributions
from people, if you feel that this feature is very important to the project
you can implement the feature yourself and submit a Pull Request.

here is the mailing list:

http://lists.creytiv.com/mailman/listinfo/re-devel

you can also add your request to the Roadmap:

https://github.com/alfredh/baresip/wiki/Roadmap


please note that this Issues tracker is mainly for defects/bugs
and not for large features.
