### ISSUE TITLE
uanew not working?

### ISSUE THREAD

**Issue by Alv3s** [alfredh/baresip#759]
Hello,

I have been using Baresip for the past week and right now I need to build it from source. Last week, when using baresip, I could register an account with the command:

```/uanew sip:USER:SECRET@SERVERIP:PORT```

When building from source I can't and I get the following error:
```account: username:password is now disabled please use ;auth_pass=xxx instead```

As for my understanding, I would o something like this:
```/uanew sip:USER@SERVERIP:PORT;auth_pass:SECRET```

But didn't work. So I tried the same way I would do it on the configuration:

```/uanew <sip:USER@SERVERIP:PORT>;transport=udp;auth_pass=SECRET``` but with no success.

I tried all the following combinations with no sucess:

```
/uanew <sip:USER@IP:PORT>;transport=udp;auth_pass=SECRET
/uanew <sip:USER:SECRET@IP:PORT;transport=tcp>
/uanew <sip:USER@IP:PORT;auth_pass=SECRET>
/uanew <sip:USER@IP:PORT>auth_pass=SECRET
/uanew sip:USER:SECRET@IP:PORT
```

I may have tried other combinations. What exactly am I doing wrong?

**Comment by juha-h** [comment]
Alv3s writes:

> I have been using Baresip for the past week and right now I need to
> build it from source. Last week, when using baresip, I could register
> an account with the command: 
> 
> ```/uanew sip:USER:SECRET@SERVERIP:PORT```
> 
> When building from source I can't and I get the following error:
> ```account: username:password is now disabled please use ;auth_pass=xxx instead```
> 
> As for my understanding, I would o something like this:
> ```/uanew sip:USER@SERVERIP:PORT;auth_pass:SECRET```
> 
> But didn't work. So I tried the same way I would do it on the configuration:
> 
> ```/uanew <sip:USER@SERVERIP:PORT>;transport=udp;auth_pass=SECRET```
> but with no success. 
> 
> I tried all the following combinations with no sucess:
> 
> ```
> /uanew <sip:USER@IP:PORT>;transport=udp;auth_pass=SECRET
> /uanew <sip:USER:SECRET@IP:PORT;transport=tcp>
> /uanew <sip:USER@IP:PORT;auth_pass=SECRET>
> /uanew <sip:USER@IP:PORT>auth_pass=SECRET
> /uanew sip:USER:SECRET@IP:PORT
> ```
> 
> I may have tried other combinations. What exactly am I doing wrong?

I just tried and this worked for me:

/uanew sip:user@test.tutpro.com;auth_user=xxx;auth_pass=yyy

**Comment by Alv3s** [comment]
> Alv3s writes:
> I have been using Baresip for the past week and right now I need to build it from source. Last week, when using baresip, I could register an account with the command: ```/uanew sip:USER:SECRET@SERVERIP:PORT``` When building from source I can't and I get the following error: ```account: username:password is now disabled please use ;auth_pass=xxx instead``` As for my understanding, I would o something like this: ```/uanew sip:USER@SERVERIP:PORT;auth_pass:SECRET``` But didn't work. So I tried the same way I would do it on the configuration: ```/uanew <sip:USER@SERVERIP:PORT>;transport=udp;auth_pass=SECRET``` but with no success. I tried all the following combinations with no sucess: ``` /uanew <sip:USER@IP:PORT>;transport=udp;auth_pass=SECRET /uanew <sip:USER:SECRET@IP:PORT;transport=tcp> /uanew <sip:USER@IP:PORT;auth_pass=SECRET> /uanew <sip:USER@IP:PORT>auth_pass=SECRET /uanew sip:USER:SECRET@IP:PORT ``` I may have tried other combinations. What exactly am I doing wrong?
> I just tried and this worked for me: /uanew sip:user@test.tutpro.com;auth_user=xxx;auth_pass=yyy

Hello Juha! Thank you for the support.

Imagine that I have a user 12345 and password ABC123, would I do it like this?
```/uanew sip:12345@SOME_IP:SOME_PORT;auth_user=12345;auth_pass=ABC123```

**Comment by juha-h** [comment]
Alv3s writes:

> Imagine that I have a user 12345 and password ABC123, would I do it like this?
> ```/uanew sip:12345@SOME_IP:SOME_PORT;auth_user=12345;auth_pass=ABC123```

Should work.  Give it a try.

**Comment by Alv3s** [comment]
> Alv3s writes:
> Imagine that I have a user 12345 and password ABC123, would I do it like this? ```/uanew sip:12345@SOME_IP:SOME_PORT;auth_user=12345;auth_pass=ABC123```
> Should work. Give it a try.

Thanks again for the support. After your feedback, it still didn't work but started theworized other issues and eventually found it:

It seems likw Windows WSL doesn't work very well with baresip. I switched and compiled the code inside a Docker instead and what you have provided indeed worked. Thank you very much!
