### ISSUE TITLE
Cannot call from Wifi to 3G and 3G to Wifi

### ISSUE THREAD

**Issue by gambogo** [alfredh/baresip#76]
hi Alfredh,

I was researching on this some days, but i can't hear the sound between 3G and Wifi. (the phone still receives call, but no sound, no video), I'm developing on iOS.

I already tried to use some stun servers by set "medianat=stun;stunserver=stun:stun.l.google.com:19302" but no luck.

I tried  to make call between wifi to wifi, 3G to 3G and they work fine. And i think it only work for Lan network.
Can you teach me how to configure baresip or line of code to call different network ?

Thank you

**Comment by gambogo** [comment]
And i tried with natpmp as well. NatPMP only show external ip address: 0.0.0.0:port.
so sad...

**Comment by alfredh** [comment]
if your device is behind NAT you need to use enable a NAT-traversal method
which is suitable for your Router/NAT-type:

1. STUN might work for some routers, but is not recommended
2. TURN will always work but all packets are relayed via TURN-server
3. ICE the most flexible solution, all possible paths will be checked
4. NATPMP only if your Router/GW supports NATPMP

can you also try to enable RTP-statistics and see how many packets
are sent/received:

$HOME/.baresip/config

```
rtp_stats    yes
```

**Comment by gambogo** [comment]
so i change my config to use ICE with this ";medianat=ice;stunserver=stun:stun.l.google.com:19302".

**Comment by gambogo** [comment]
so i changed config to use ICE with this ";medianat=ice;stunserver=stun:stun.l.google.com:19302"
It can be received call but still no sound from 3G to Wifi.
i can see some candidates in log. do you know which issue is this ?


------------------------------------------ LOG ----------------------------

[   zrtp main]: START SESSION INITIALIZATION. sID=0.
[   zrtp main]: Profile in NULL - loading default one.
[   zrtp main]: Session initialization - DONE. sID=0.
[   zrtp main]: ATTACH NEW STREAM to sID=0:
[        zrtp]: 	Stream ID=0 UNKNOWN switching <NONE> ---> <ACTIVE>.
[   zrtp main]: 	Empty slot was found - initializing new stream with ID=0.
[   zrtp main]: 	Preparing ZRTP Hello according to the Session profile.
[   zrtp main]: ATTACH NEW STREAM - DONE.
[   zrtp main]: ATTACH NEW STREAM to sID=0:
[        zrtp]: 	Stream ID=0 UNKNOWN switching <NONE> ---> <ACTIVE>.
[   zrtp main]: 	Empty slot was found - initializing new stream with ID=1.
[   zrtp main]: 	Preparing ZRTP Hello according to the Session profile.
[   zrtp main]: ATTACH NEW STREAM - DONE.
audio: added interface: en0:192.168.1.78 (local prio 10)
video: added interface: en0:192.168.1.78 (local prio 10)
audio: comp1 setting local: 1.52.57.123:14826
audio: comp2 setting local: 1.52.57.123:14827
ice: audio: Default local candidates: 1.52.57.123:14826 / 1.52.57.123:14827
video: comp1 setting local: 1.52.57.123:18196
video: comp2 setting local: 1.52.57.123:18197
ice: video: Default local candidates: 1.52.57.123:18196 / 1.52.57.123:18197
sip:haoipad1@MyDomain Incoming call from:  sip:dai.doan@MyDomain - (press ENTER to accept)
2015-10-03 17:29:49.205 MyApp[2288:531399] callback, 51: CALL_INCOMING
2015-10-03 17:29:49.207 MyApp[2288:531399] Number of calls: 1
2015-10-03 17:29:49.207 MyApp[2288:531399] Scode 0
[31mmain: long async blocking: 527>100 ms (h=0x78bd05 arg=0x5d0ccd0)
[;m2015-10-03 17:29:49.236 MyApp[2288:531366] User is ready!

answering call from sip:dai.doan@MyDomain with 200

[ zrtp engine]: START STREAM ID=0 mode=CLEAR state=ACTIVE.
[        zrtp]: 	Stream ID=0 CLEAR switching <ACTIVE> ---> <START>.
zrtp_state: START
[  zrtp utils]: 	Send <HELLO> ssrc=4034190850 seq=5641 size=144. Stream 0:CLEAR:START
ice: stream 'video' is disabled -- ignore
ICE: ICE Start:  local_mode=Full, remote_mode=Full, local_role=Controlled
local_ufrag="pi1Q" local_pwd="fUwtNwndG10sqKN7RmT2p2"

----- ICE Media <audio> -----
Components: (2)
id=1 ldef=1.52.57.123:14826 rdef=113.187.16.142:5893 concluded=0
id=2 ldef=1.52.57.123:14827 rdef=113.187.16.142:9573 concluded=0
Local Candidates:  (4)
{1} fnd=c0a8014e prio=7e000aff en0:host:192.168.1.78:14826
{2} fnd=c0a8014e prio=7e000afe en0:host:192.168.1.78:14827
{1} fnd=0134397a prio=640000ff en0:srflx:1.52.57.123:14826 (rel-addr=192.168.1.78:14826)
{2} fnd=0134397a prio=640000fe en0:srflx:1.52.57.123:14827 (rel-addr=192.168.1.78:14827)
Remote Candidates:  (4)
{1} fnd=1  prio=7effffff host:10.147.22.35:7076
{2} fnd=1  prio=7efffffe host:10.147.22.35:7077
{1} fnd=2  prio=64ffffff srflx:113.187.16.142:5893 (rel-addr=10.147.22.35:7076)
{2} fnd=2  prio=64fffffe srflx:113.187.16.142:9573 (rel-addr=10.147.22.35:7077)
Check list: [state=(NULL)] (0)
Valid list:  (0)

----- ICE Media <video> -----
Components: (2)
id=1 ldef=1.52.57.123:18196 rdef= concluded=0
id=2 ldef=1.52.57.123:18197 rdef= concluded=0
Local Candidates:  (4)
{1} fnd=c0a8014e prio=7e000aff en0:host:192.168.1.78:18196
{2} fnd=c0a8014e prio=7e000afe en0:host:192.168.1.78:18197
{1} fnd=0134397a prio=640000ff en0:srflx:1.52.57.123:18196 (rel-addr=192.168.1.78:18196)
{2} fnd=0134397a prio=640000fe en0:srflx:1.52.57.123:18197 (rel-addr=192.168.1.78:18197)
Remote Candidates:  (0)
Check list: [state=(NULL)] (0)
Valid list:  (0)
STUN debug:
STUN client transactions: (0)
[33mchklist: audio: pruned candidate pairs: 4
[;maudio: Set audio decoder: opus 48000Hz 2ch
[  zrtp utils]: 	Send <HELLO> ssrc=4034190850 seq=5642 size=144. Stream 0:CLEAR:START
audio: Set audio encoder: opus 48000Hz 2ch
audio tx pipeline:   coreaudio ---> vumeter ---> opus
audio rx pipeline:   coreaudio <--- vumeter <--- opus
video stream is disabled..

[  zrtp utils]: 	Send <HELLO> ssrc=4034190850 seq=5643 size=144. Stream 0:CLEAR:START
[  zrtp utils]: 	Send <HELLO> ssrc=4034190850 seq=5644 size=144. Stream 0:CLEAR:START
[  zrtp utils]: 	Send <HELLO> ssrc=4034190850 seq=5645 size=144. Stream 0:CLEAR:START
[ zrtp engine]: WARNING! HELLO have been resent 5 times without a response. Raising ZRTP_EVENT_NO_ZRTP_QUICK event. ID=0
[  zrtp utils]: 	Send <HELLO> ssrc=4034190850 seq=5646 size=144. Stream 0:CLEAR:START
[  zrtp utils]: 	Send <HELLO> ssrc=4034190850 seq=5647 size=144. Stream 0:CLEAR:START
[  zrtp utils]: 	Send <HELLO> ssrc=4034190850 seq=5648 size=144. Stream 0:CLEAR:START
[  zrtp utils]: 	Send <HELLO> ssrc=4034190850 seq=5649 size=144. Stream 0:CLEAR:START
[  zrtp utils]: 	Send <HELLO> ssrc=4034190850 seq=5650 size=144. Stream 0:CLEAR:START
[  zrtp utils]: 	Send <HELLO> ssrc=4034190850 seq=5651 size=144. Stream 0:CLEAR:START
[  zrtp utils]: 	Send <HELLO> ssrc=4034190850 seq=5652 size=144. Stream 0:CLEAR:START
[  zrtp utils]: 	Send <HELLO> ssrc=4034190850 seq=5653 size=144. Stream 0:CLEAR:START
[  zrtp utils]: 	Send <HELLO> ssrc=4034190850 seq=5654 size=144. Stream 0:CLEAR:START
[  zrtp utils]: 	Send <HELLO> ssrc=4034190850 seq=5655 size=144. Stream 0:CLEAR:START
[  zrtp utils]: 	Send <HELLO> ssrc=4034190850 seq=5656 size=144. Stream 0:CLEAR:START
[  zrtp utils]: 	Send <HELLO> ssrc=4034190850 seq=5657 size=144. Stream 0:CLEAR:START
[  zrtp utils]: 	Send <HELLO> ssrc=4034190850 seq=5658 size=144. Stream 0:CLEAR:START
[  zrtp utils]: 	Send <HELLO> ssrc=4034190850 seq=5659 size=144. Stream 0:CLEAR:START
[  zrtp utils]: 	Send <HELLO> ssrc=4034190850 seq=5660 size=144. Stream 0:CLEAR:START
[ zrtp engine]: WARNING! HELLO Max retransmissions count reached (20 retries). ID=0
[        zrtp]: 	Stream ID=0 CLEAR switching <START> ---> <NOZRTP>.
zrtp_state: NOZRTP

haoipad1@MyDomain: Call established: sip:dai.doan@MyDomain
2015-10-03 17:29:55.621 MyApp[2288:531399] callback, 51: CALL_ESTABLISHED
2015-10-03 17:29:55.622 MyApp[2288:531399] Scode 0
call: video stream is disabled..

sip:dai.doan@MyDomain: session closed: Connection reset by peer
2015-10-03 17:29:55.786 MyApp[2288:531399] callback, 51: CALL_CLOSED

--- Video stream ---
tx: 0 x 0, fps=0
rx: pt=-1
video dir=sendrecv pt_enc=-1
local: 1.52.57.123:18196, remote: 0.0.0.0:0/0.0.0.0:0
RTP debug:
Encode: seq=23925 ssrc=0x34703632
----- RTCP Session: -----
cname= SSRC=0x34703632/879769138 rx=0Hz
TX: packets=0, octets=0
--- jitter buffer debug---
running=0 min=5 cur=0 max=10 [frames]
seq_put=0
Stat: put=0 get=0 oos=0 dup=0 late=0 or=0 ur=0 flush=1       put/get_ratio=0% lost=0 (0.00%)
2015-10-03 17:29:55.787 MyApp[2288:531399] Scode 0

audio           Transmit:     Receive:
packets:            229            0
avg. bitrate:       8.0          0.0  (kbit/s)
errors:               0            0

**Comment by alfredh** [comment]
which version of baresip are you using BTW ?


if you look in the log you will see a warning from ZRTP:

```
 WARNING! HELLO have been resent 5 times without a response. 
```

also no ICE candidate pairs have succeeded, indicating that the other
peer is not able to send packets to you (dropped by NAT).

can you try this:

- Enable ICE with TURN-server
- Disable video to make the use-case slightly simpler
- Disable ZRTP for now to make use-case simpler

enable this in $HOME/.baresip/config:

```
# ICE
ice_turn                yes
ice_debug               yes
ice_nomination          regular # {regular,aggressive}
ice_mode                full    # {full,lite}
```

for the TURN-server you can either download restund
(http://creytiv.com/restund.html) and host it on a public server,
or try our instance of restund running on creytiv.com
(contact me offline for credentials).

can you also try latest Baresip from github with some extra logging:

https://github.com/alfredh/baresip/commit/26b1c86e32abc1d2543d667c80b3532e6e178c16

**Comment by gambogo** [comment]
Updated latest Baresip and i can make call between 3G and Wifi now, it works very well. Thanks a lot.
and also sent email to you for asking about STUN account because i still have a problem with NAT.

**Comment by alfredh** [comment]
I think your setup should be working now, now that you are using a real TURN Server :)
