### ISSUE TITLE
no common audio codecs - rejected

### ISSUE THREAD

**Issue by bihackers** [alfredh/baresip#763]
I use linphone client test baresip client.
baresip print "no common audio codecs - rejected"

my wireshark log:
`
 ....INVITE sip:1003-0x172b690@192.168.43.96:51502 SIP/2.0
Record-Route: <sip:140.143.203.122;lr;nat=yes;did=ba4.1c17ef55>
Via: SIP/2.0/UDP 140.143.203.122:5060;branch=z9hG4bKa296.e3eea0f3.1
Via: SIP/2.0/UDP 10.66.52.212:49185;received=223.104.159.155;branch=z9hG4bK.-Otna5Gjp;rport=4944
From: <sip:1005@140.143.203.122>;tag=i7CZLYxIK
To: sip:1003@140.143.203.122
CSeq: 20 INVITE
Call-ID: LSoQVHiIbV
Max-Forwards: 69
Supported: replaces, outbound
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE
Content-Type: application/sdp
Content-Length: 1753
Contact: <sip:1005@223.104.159.155:4944;transport=udp>;+sip.instance="<urn:uuid:e4b47e22-abcd-445e-a461-78477b3476aa>"
User-Agent: LinphoneAndroid/3.2.4 (belle-sip/1.5.0)

v=0
o=1005 3435 2813 IN IP4 140.143.203.122
s=Talk
c=IN IP4 140.143.203.122
b=AS:380
t=0 0
a=ice-pwd:a488fa786096e320874fb198
a=ice-ufrag:df8614d0
a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
m=audio 49933 UDP/TLS/RTP/SAVP 8 101
c=IN IP4 140.143.203.122
a=rtpmap:101 telephone-event/8000
a=setup:actpass
a=fingerprint:SHA-256 25:DE:37:C6:F8:B7:AE:A9:09:8D:82:AE:42:BF:66:B7:5D:DA:64:2E:74:46:9E:B8:6E:4C:3E:08:14:D2:16:C6
a=ssrc:3741400014 cname:sip:1005@140.143.203.122
a=rtcp:58745
a=candidate:1 1 UDP 2130706431 10.66.52.212 7076 typ host
a=candidate:1 2 UDP 2130706430 10.66.52.212 7077 typ host
a=candidate:2 1 UDP 1694498815 223.104.159.155 17358 typ srflx raddr 10.66.52.212 rport 7076
a=candidate:3 1 UDP 16777215 140.143.203.122 49933 typ relay
a=candidate:2 2 UDP 1694498814 223.104.159.155 17359 typ srflx raddr 10.66.52.212 rport 7077
a=candidate:4 2 UDP 16777214 140.143.203.122 58745 typ relay
m=video 56176 UDP/TLS/RTP/SAVP 96
c=IN IP4 140.143.203.122
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=42801F
a=setup:actpass
a=fingerprint:SHA-256 25:DE:37:C6:F8:B7:AE:A9:09:8D:82:AE:42:BF:66:B7:5D:DA:64:2E:74:46:9E:B8:6E:4C:3E:08:14:D2:16:C6
a=ssrc:2840917662 cname:sip:1005@140.143.203.122
a=rtcp:59610
a=candidate:1 1 UDP 2130706431 10.66.52.212 9078 typ host
a=candidate:1 2 UDP 2130706430 10.66.52.212 9079 typ host
a=candidate:2 1 UDP 1694498815 223.104.159.155 17360 typ srflx raddr 10.66.52.212 rport 9078
a=candidate:3 1 UDP 16777215 140.143.203.122 56176 typ relay
a=candidate:2 2 UDP 1694498814 223.104.159.155 17361 typ srflx raddr 10.66.52.212 rport 9079
a=candidate:4 2 UDP 16777214 140.143.203.122 59610 typ relay
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 ccm fir
SIP/2.0 488 Not Acceptable Here
Via: SIP/2.0/UDP 140.143.203.122:5060;branch=z9hG4bKa296.e3eea0f3.1
Via: SIP/2.0/UDP 10.66.52.212:49185;received=223.104.159.155;branch=z9hG4bK.-Otna5Gjp;rport=4944
From: <sip:1005@140.143.203.122>;tag=i7CZLYxIK
To: sip:1003@140.143.203.122;tag=50026a606abea847
CSeq: 20 INVITE
Call-ID: LSoQVHiIbV
Server: baresip v0.6.3 (x86_64/linux)
Content-Length: 0

ACK sip:1003-0x172b690@192.168.43.96:51502 SIP/2.0
Via: SIP/2.0/UDP 140.143.203.122:5060;branch=z9hG4bKa296.e3eea0f3.1
From: <sip:1005@140.143.203.122>;tag=i7CZLYxIK
Call-ID: LSoQVHiIbV
To: sip:1003@140.143.203.122;tag=50026a606abea847
CSeq: 20 ACK
Max-Forwards: 70
User-Agent: OpenSIPS (2.4.5 (x86_64/linux))
Content-Length: 0

....INVITE sip:1003-0x172b690@192.168.43.96:51502 SIP/2.0
Record-Route: <sip:140.143.203.122;lr;nat=yes;did=ba4.1c17ef55>
Via: SIP/2.0/UDP 140.143.203.122:5060;branch=z9hG4bKa296.e3eea0f3.1
Via: SIP/2.0/UDP 10.66.52.212:49185;received=223.104.159.155;branch=z9hG4bK.-Otna5Gjp;rport=4944
From: <sip:1005@140.143.203.122>;tag=i7CZLYxIK
To: sip:1003@140.143.203.122
CSeq: 20 INVITE
Call-ID: LSoQVHiIbV
Max-Forwards: 69
Supported: replaces, outbound
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE
Content-Type: application/sdp
Content-Length: 1753
Contact: <sip:1005@223.104.159.155:4944;transport=udp>;+sip.instance="<urn:uuid:e4b47e22-abcd-445e-a461-78477b3476aa>"
User-Agent: LinphoneAndroid/3.2.4 (belle-sip/1.5.0)

v=0
o=1005 3435 2813 IN IP4 140.143.203.122
s=Talk
c=IN IP4 140.143.203.122
b=AS:380
t=0 0
a=ice-pwd:a488fa786096e320874fb198
a=ice-ufrag:df8614d0
a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
m=audio 49933 UDP/TLS/RTP/SAVP 8 101
c=IN IP4 140.143.203.122
a=rtpmap:101 telephone-event/8000
a=setup:actpass
a=fingerprint:SHA-256 25:DE:37:C6:F8:B7:AE:A9:09:8D:82:AE:42:BF:66:B7:5D:DA:64:2E:74:46:9E:B8:6E:4C:3E:08:14:D2:16:C6
a=ssrc:3741400014 cname:sip:1005@140.143.203.122
a=rtcp:58745
a=candidate:1 1 UDP 2130706431 10.66.52.212 7076 typ host
a=candidate:1 2 UDP 2130706430 10.66.52.212 7077 typ host
a=candidate:2 1 UDP 1694498815 223.104.159.155 17358 typ srflx raddr 10.66.52.212 rport 7076
a=candidate:3 1 UDP 16777215 140.143.203.122 49933 typ relay
a=candidate:2 2 UDP 1694498814 223.104.159.155 17359 typ srflx raddr 10.66.52.212 rport 7077
a=candidate:4 2 UDP 16777214 140.143.203.122 58745 typ relay
m=video 56176 UDP/TLS/RTP/SAVP 96
c=IN IP4 140.143.203.122
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=42801F
a=setup:actpass
a=fingerprint:SHA-256 25:DE:37:C6:F8:B7:AE:A9:09:8D:82:AE:42:BF:66:B7:5D:DA:64:2E:74:46:9E:B8:6E:4C:3E:08:14:D2:16:C6
a=ssrc:2840917662 cname:sip:1005@140.143.203.122
a=rtcp:59610
a=candidate:1 1 UDP 2130706431 10.66.52.212 9078 typ host
a=candidate:1 2 UDP 2130706430 10.66.52.212 9079 typ host
a=candidate:2 1 UDP 1694498815 223.104.159.155 17360 typ srflx raddr 10.66.52.212 rport 9078
a=candidate:3 1 UDP 16777215 140.143.203.122 56176 typ relay
a=candidate:2 2 UDP 1694498814 223.104.159.155 17361 typ srflx raddr 10.66.52.212 rport 9079
a=candidate:4 2 UDP 16777214 140.143.203.122 59610 typ relay
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 ccm fir
SIP/2.0 488 Not Acceptable Here
Via: SIP/2.0/UDP 140.143.203.122:5060;branch=z9hG4bKa296.e3eea0f3.1
Via: SIP/2.0/UDP 10.66.52.212:49185;received=223.104.159.155;branch=z9hG4bK.-Otna5Gjp;rport=4944
From: <sip:1005@140.143.203.122>;tag=i7CZLYxIK
To: sip:1003@140.143.203.122;tag=50026a606abea847
CSeq: 20 INVITE
Call-ID: LSoQVHiIbV
Server: baresip v0.6.3 (x86_64/linux)
Content-Length: 0

ACK sip:1003-0x172b690@192.168.43.96:51502 SIP/2.0
Via: SIP/2.0/UDP 140.143.203.122:5060;branch=z9hG4bKa296.e3eea0f3.1
From: <sip:1005@140.143.203.122>;tag=i7CZLYxIK
Call-ID: LSoQVHiIbV
To: sip:1003@140.143.203.122;tag=50026a606abea847
CSeq: 20 ACK
Max-Forwards: 70
User-Agent: OpenSIPS (2.4.5 (x86_64/linux))
Content-Length: 0

my account:
<sip:1003@140.143.203.122>;answermode=auto;auth_pass=pass;medianat=ice;mediaenc=dtls_srtp

my config:

sip_listen		
sip_certificate	
sip_cafile		

call_local_timeout	120
call_max_calls		4

audio_path		/usr/local/share/baresip
audio_player		,
audio_source		aufile,/home/apple/.baresip/output.wav
audio_alert		,
auplay_srate		0
ausrc_srate		0
auplay_channels		0
ausrc_channels		0
audio_level		no

video_source		avformat,1080p.mp4
video_display		,
video_size		"1920x1080"
video_bitrate		512000
video_fps		25.00
video_fullscreen	yes
videnc_format		yuv420p

rtp_tos			184
rtp_ports		1024-49152
rtp_bandwidth		0-0
rtcp_mux		no
jitter_buffer_delay	5-10
rtp_stats		no
rtp_timeout		0 # in seconds

net_prefer_ipv6		no
net_interface		

bfcp_proto	`

**Comment by juha-h** [comment]
Make sure that you have g711 module loaded.

**Comment by bihackers** [comment]
this is my baresip log:
apple@ubuntu:~/.baresip$ baresip 
baresip v0.6.3 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.
Local network address:  IPv4=enp0s5|192.168.3.12 
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
ausrc: aufile
vidcodec: H264
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
avcodec: using H.264 encoder 'libx264' -- libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.264 decoder 'h264' -- H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
vidsrc: avformat
medianat: stun
medianat: turn
medianat: ice
mediaenc: srtp
mediaenc: srtp-mand
mediaenc: srtp-mandf
mediaenc: dtls_srtp
1003@140.143.203.122: Using medianat 'ice'
1003@140.143.203.122: Using media encryption 'dtls_srtp'
Populated 1 account
Populated 1 contacts
Populated 2 audio codecs
Populated 0 audio filters
Populated 4 video codecs
Populated 0 video filters
baresip is ready.
1003@140.143.203.122: {0/UDP/v4} 200 OK (OpenSIPS (2.4.5 (x86_64/linux))) [2 bindings]
All 1 useragent registered successfully! (30 ms)
ice: new session with STUN-server at 140.143.203.122 (username=1003)
call: no common audio codecs - rejected

my accounts:
<sip:1003@140.143.203.122>;answermode=auto;auth_pass=pass;medianat=ice;mediaenc=dtls_srtp

my config where load g711:
# Audio codec Modules (in order)
#module                 opus.so
#module                 amr.so
#module                 g7221.so
#module                 g722.so
#module                 g726.so
module                  g711.so
#module                 gsm.so
#module                 l16.so
#module                 bv32.so
#module                 mpa.so
#module                 codec2.so
#module                 ilbc.so
#module                 isac.so

**Comment by alfredh** [comment]
the SDP protocol of your incoming SDP has this:

`m=audio 49933 UDP/TLS/RTP/SAVP 8 101`

while the dtls-srtp module in baresip has this:

```c
static struct menc dtls_srtp = {
	.id        = "dtls_srtp",
	.sdp_proto = "UDP/TLS/RTP/SAVPF",
	.wait_secure = true,
	.sessh     = session_alloc,
	.mediah    = media_alloc
};
```

(Notice the extra `F` at the end for Feedback).

this should be okay according to RFC 5764:

```
      When a RTP/SAVP or RTP/SAVPF stream is transported over DTLS with
      UDP, the token SHALL be UDP/TLS/RTP/SAVP or UDP/TLS/RTP/SAVPF
      respectively.
```

this is also handled in dtls-srtp module:

```c
	err = sdp_media_set_alt_protos(st->sdpm, 4,
				       "RTP/SAVP",
				       "RTP/SAVPF",
				       "UDP/TLS/RTP/SAVP",
				       "UDP/TLS/RTP/SAVPF");
```

we should first try to figure out what is mismatching; the sdp protocol
or the actual audio codec.

1. what happens if you change the calling direction, i.e. calling
  from baresip to linphone ?

2. what happens if you add more audio codecs, e.g. opus ?

**Comment by alfredh** [comment]
can you try to add this piece of code to stream.c, somewhere after `sdp_media_add`:

```c
	err = sdp_media_set_alt_protos(st->sdpm, 4,
				       "RTP/SAVP",
				       "RTP/SAVPF",
				       "UDP/TLS/RTP/SAVP",
				       "UDP/TLS/RTP/SAVPF");
```

it looks the call to mediaenc start happens too late, after the SDP exchange is done.

**Comment by bihackers** [comment]
after I add:
`err = sdp_media_set_alt_protos(st->sdpm, 4,
				       "RTP/SAVP",
				       "RTP/SAVPF",
				       "UDP/TLS/RTP/SAVP",
				       "UDP/TLS/RTP/SAVPF");`
in steam.c.This print no longer appears.It's ok now.

**Comment by landryb** [comment]
Fwiw it seems this didnt get commited to stream.c, and i get the same issue trying to call from linphone to baresip, when using `mediaenc=dtls_srtp` on OpenBSD with baresip 1.1.0 i get the `call: no common audio codecs - rejected` message.

**Comment by landryb** [comment]
tried with the following patch and unfortunately this didnt help:
```
Index: src/stream.c
--- src/stream.c.orig
+++ src/stream.c
@@ -563,6 +563,14 @@ int stream_alloc(struct stream **sp, struct list *stre
        if (err)
                goto out;
 
+       err = sdp_media_set_alt_protos(s->sdp, 4,
+                                      "RTP/SAVP",
+                                      "RTP/SAVPF",
+                                      "UDP/TLS/RTP/SAVP",
+                                      "UDP/TLS/RTP/SAVPF");
+       if (err)
+               goto out;
+
        if (label) {
                err |= sdp_media_set_lattr(s->sdp, true,
                                           "label", "%d", label);

```
not sure about the first argument though.

**Comment by haricane8133** [comment]
@alfredh, @juha-h, @sreimers, @bihackers, @landryb

I am facing the same issue when calling BareSip@3.9.0 from LinPhone app from Android.

I tried the fix provided here (I had to change a few field names), but it didn't work out.

If this is an outstanding bug, could we please re-open this ticket?

**Comment by haricane8133** [comment]
Here are some more details as requested in the chat above...

- The issue doesn't happen when calling from BareSip to Linphone.
- I have uncommented all the Audio Codec modules provided in default BareSip [except G7221 and MPA](https://github.com/baresip/baresip/discussions/2901).
- When the BareSip to Linphone call happens, it happens through Opus (details below)

```
stream: update 'audio'
audio: Set audio decoder: opus 48000Hz 2ch
pipewire: opening playback (48000 Hz, 2 channels, device default, ptime 20)
pipewire: stream baresip-playback started (Success [0])
audio: player started with sample format S16LE
audio: Set audio encoder: opus 48000Hz 2ch
pipewire: opening capture(48000 Hz, 2 channels,device 'default')
pipewire: stream baresip-capture started (Success [0])
audio: source started with sample format S16LE
audio tx pipeline:    pipewire ---> aubuf ---> auconv ---> auresamp ---> opus
audio rx pipeline:    pipewire <--- aubuf <--- auconv <--- auresamp <--- opus
[0:00:00] audio=21664/10800 (bit/s)
```

**Comment by cspiel1** [comment]
Maybe its better to open a new issue with the current details (config, accounts, logs) and add a link to this already closed issue.
