### ISSUE TITLE
ice failed 

### ISSUE THREAD

**Issue by bihackers** [alfredh/baresip#765]
Hello,when I configure ICE and DTLS in Linphone app,and call my baresip.
some error happened.
when I use Linphone call to antother Linphone, it was normal. So I post detailed information here. You can also use our SIP server test.thank you.
### wireshark
....INVITE sip:1003-0x1368990@192.168.3.12:43215 SIP/2.0
Record-Route: <sip:172.16.1.255;lr;nat=yes;did=d.f174cb11>
Via: SIP/2.0/UDP 172.16.1.255:5060;branch=z9hG4bKc843.dda753e5.0
Via: SIP/2.0/UDP 192.168.0.44:40719;received=223.95.81.141;branch=z9hG4bK.Hj-7MNum8;rport=26910
From: <sip:1005@47.254.89.249>;tag=U8nnGafdx
To: sip:1003@47.254.89.249
CSeq: 20 INVITE
Call-ID: MQBki7GwtT
Max-Forwards: 69
Supported: replaces, outbound
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE
Content-Type: application/sdp
Content-Length: 1588
Contact: <sip:1005@223.95.81.141:26910;transport=udp>;+sip.instance="<urn:uuid:e4b47e22-abcd-445e-a461-78477b3476aa>"
User-Agent: LinphoneAndroid/3.2.4 (belle-sip/1.5.0)

v=0
o=1005 1097 1134 IN IP4 192.168.0.44
s=Talk
c=IN IP4 192.168.0.44
b=AS:380
t=0 0
a=ice-pwd:8de831c29f58720cd4fe6593
a=ice-ufrag:33759464
a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
m=audio 23330 UDP/TLS/RTP/SAVP 0 8 101
c=IN IP4 223.95.81.141
a=rtpmap:101 telephone-event/8000
a=setup:actpass
a=fingerprint:SHA-256 25:DE:37:C6:F8:B7:AE:A9:09:8D:82:AE:42:BF:66:B7:5D:DA:64:2E:74:46:9E:B8:6E:4C:3E:08:14:D2:16:C6
a=ssrc:4152997452 cname:sip:1005@47.254.89.249
a=candidate:1 1 UDP 2130706431 192.168.0.44 7076 typ host
a=candidate:1 2 UDP 2130706430 192.168.0.44 7077 typ host
a=candidate:2 1 UDP 1694498815 223.95.81.141 23330 typ srflx raddr 192.168.0.44 rport 7076
a=candidate:2 2 UDP 1694498814 223.95.81.141 23331 typ srflx raddr 192.168.0.44 rport 7077
m=video 36060 UDP/TLS/RTP/SAVP 96 97
c=IN IP4 223.95.81.141
a=rtpmap:96 VP8/90000
a=rtpmap:97 H264/90000
a=fmtp:97 profile-level-id=42801F
a=setup:actpass
a=fingerprint:SHA-256 25:DE:37:C6:F8:B7:AE:A9:09:8D:82:AE:42:BF:66:B7:5D:DA:64:2E:74:46:9E:B8:6E:4C:3E:08:14:D2:16:C6
a=ssrc:1843560251 cname:sip:1005@47.254.89.249
a=rtcp:23332
a=candidate:1 1 UDP 2130706431 192.168.0.44 9078 typ host
a=candidate:1 2 UDP 2130706430 192.168.0.44 9079 typ host
a=candidate:2 1 UDP 1694498815 223.95.81.141 36060 typ srflx raddr 192.168.0.44 rport 9078
a=candidate:2 2 UDP 1694498814 223.95.81.141 23332 typ srflx raddr 192.168.0.44 rport 9079
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 nack sli
a=rtcp-fb:96 ack rpsi
a=rtcp-fb:96 ccm fir
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 ccm fir
SIP/2.0 180 Ringing
Record-Route: <sip:172.16.1.255;lr;nat=yes;did=d.f174cb11>
Via: SIP/2.0/UDP 172.16.1.255:5060;branch=z9hG4bKc843.dda753e5.0;received=47.254.89.249
Via: SIP/2.0/UDP 192.168.0.44:40719;received=223.95.81.141;branch=z9hG4bK.Hj-7MNum8;rport=26910
From: <sip:1005@47.254.89.249>;tag=U8nnGafdx
To: sip:1003@47.254.89.249;tag=b2fdeff7a3eb2106
CSeq: 20 INVITE
Call-ID: MQBki7GwtT
Server: baresip v0.6.3 (x86_64/linux)
Contact: <sip:1003-0x1368990@192.168.3.12:43215>
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER
Content-Length: 0

SIP/2.0 200 Answering
Record-Route: <sip:172.16.1.255;lr;nat=yes;did=d.f174cb11>
Via: SIP/2.0/UDP 172.16.1.255:5060;branch=z9hG4bKc843.dda753e5.0;received=47.254.89.249
Via: SIP/2.0/UDP 192.168.0.44:40719;received=223.95.81.141;branch=z9hG4bK.Hj-7MNum8;rport=26910
From: <sip:1005@47.254.89.249>;tag=U8nnGafdx
To: sip:1003@47.254.89.249;tag=b2fdeff7a3eb2106
CSeq: 20 INVITE
Call-ID: MQBki7GwtT
Server: baresip v0.6.3 (x86_64/linux)
Contact: <sip:1003-0x1368990@192.168.3.12:43215>
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER
Content-Type: application/sdp
Content-Length: 1228

v=0
o=- 3162123951 340234518 IN IP4 192.168.3.12
s=-
c=IN IP4 192.168.3.12
t=0 0
a=tool:baresip 0.6.3
a=ice-ufrag:xdHQ9bd
a=ice-pwd:aVLPh8UEaZZvu3B3XXqAZZBgxZpS4NE
a=setup:active
a=fingerprint:SHA-256 63:E2:FF:31:0F:E8:C2:E8:63:29:D4:48:72:EF:61:08:EE:F0:C6:E0:4A:E2:CB:99:78:B9:39:94:AC:66:58:50
m=audio 34586 UDP/TLS/RTP/SAVP 0 8 101
c=IN IP4 223.95.81.141
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=label:1
a=rtcp-rsize
a=ssrc:3464824102 cname:sip:1003@47.254.89.249
a=ptime:20
a=candidate:c0a8030c 1 UDP 2113932031 192.168.3.12 41794 typ host
a=candidate:df5f518c 1 UDP 1677721855 223.95.81.141 34586 typ srflx raddr 192.168.3.12 rport 41794
m=video 24806 UDP/TLS/RTP/SAVP 96 97
c=IN IP4 223.95.81.141
a=rtpmap:96 VP8/90000
a=fmtp:96 max-fs=3600
a=rtpmap:97 H264/90000
a=fmtp:97 packetization-mode=0;profile-level-id=42801f
a=sendonly
a=label:2
a=rtcp-rsize
a=ssrc:2806120015 cname:sip:1003@47.254.89.249
a=framerate:25.00
a=rtcp-fb:* nack pli
a=content:main
a=candidate:c0a8030c 1 UDP 2113932031 192.168.3.12 16782 typ host
a=candidate:df5f518c 1 UDP 1677721855 223.95.81.141 24806 typ srflx raddr 192.168.3.12 rport 16782
SIP/2.0 200 Answering
Record-Route: <sip:172.16.1.255;lr;nat=yes;did=d.f174cb11>
Via: SIP/2.0/UDP 172.16.1.255:5060;branch=z9hG4bKc843.dda753e5.0;received=47.254.89.249
Via: SIP/2.0/UDP 192.168.0.44:40719;received=223.95.81.141;branch=z9hG4bK.Hj-7MNum8;rport=26910
From: <sip:1005@47.254.89.249>;tag=U8nnGafdx
To: sip:1003@47.254.89.249;tag=b2fdeff7a3eb2106
CSeq: 20 INVITE
Call-ID: MQBki7GwtT
Server: baresip v0.6.3 (x86_64/linux)
Contact: <sip:1003-0x1368990@192.168.3.12:43215>
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER
Content-Type: application/sdp
Content-Length: 1228

v=0
o=- 3162123951 340234518 IN IP4 192.168.3.12
s=-
c=IN IP4 192.168.3.12
t=0 0
a=tool:baresip 0.6.3
a=ice-ufrag:xdHQ9bd
a=ice-pwd:aVLPh8UEaZZvu3B3XXqAZZBgxZpS4NE
a=setup:active
a=fingerprint:SHA-256 63:E2:FF:31:0F:E8:C2:E8:63:29:D4:48:72:EF:61:08:EE:F0:C6:E0:4A:E2:CB:99:78:B9:39:94:AC:66:58:50
m=audio 34586 UDP/TLS/RTP/SAVP 0 8 101
c=IN IP4 223.95.81.141
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=label:1
a=rtcp-rsize
a=ssrc:3464824102 cname:sip:1003@47.254.89.249
a=ptime:20
a=candidate:c0a8030c 1 UDP 2113932031 192.168.3.12 41794 typ host
a=candidate:df5f518c 1 UDP 1677721855 223.95.81.141 34586 typ srflx raddr 192.168.3.12 rport 41794
m=video 24806 UDP/TLS/RTP/SAVP 96 97
c=IN IP4 223.95.81.141
a=rtpmap:96 VP8/90000
a=fmtp:96 max-fs=3600
a=rtpmap:97 H264/90000
a=fmtp:97 packetization-mode=0;profile-level-id=42801f
a=sendonly
a=label:2
a=rtcp-rsize
a=ssrc:2806120015 cname:sip:1003@47.254.89.249
a=framerate:25.00
a=rtcp-fb:* nack pli
a=content:main
a=candidate:c0a8030c 1 UDP 2113932031 192.168.3.12 16782 typ host
a=candidate:df5f518c 1 UDP 1677721855 223.95.81.141 24806 typ srflx raddr 192.168.3.12 rport 16782
SIP/2.0 200 Answering
Record-Route: <sip:172.16.1.255;lr;nat=yes;did=d.f174cb11>
Via: SIP/2.0/UDP 172.16.1.255:5060;branch=z9hG4bKc843.dda753e5.0;received=47.254.89.249
Via: SIP/2.0/UDP 192.168.0.44:40719;received=223.95.81.141;branch=z9hG4bK.Hj-7MNum8;rport=26910
From: <sip:1005@47.254.89.249>;tag=U8nnGafdx
To: sip:1003@47.254.89.249;tag=b2fdeff7a3eb2106
CSeq: 20 INVITE
Call-ID: MQBki7GwtT
Server: baresip v0.6.3 (x86_64/linux)
Contact: <sip:1003-0x1368990@192.168.3.12:43215>
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER
Content-Type: application/sdp
Content-Length: 1228

v=0
o=- 3162123951 340234518 IN IP4 192.168.3.12
s=-
c=IN IP4 192.168.3.12
t=0 0
a=tool:baresip 0.6.3
a=ice-ufrag:xdHQ9bd
a=ice-pwd:aVLPh8UEaZZvu3B3XXqAZZBgxZpS4NE
a=setup:active
a=fingerprint:SHA-256 63:E2:FF:31:0F:E8:C2:E8:63:29:D4:48:72:EF:61:08:EE:F0:C6:E0:4A:E2:CB:99:78:B9:39:94:AC:66:58:50
m=audio 34586 UDP/TLS/RTP/SAVP 0 8 101
c=IN IP4 223.95.81.141
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=label:1
a=rtcp-rsize
a=ssrc:3464824102 cname:sip:1003@47.254.89.249
a=ptime:20
a=candidate:c0a8030c 1 UDP 2113932031 192.168.3.12 41794 typ host
a=candidate:df5f518c 1 UDP 1677721855 223.95.81.141 34586 typ srflx raddr 192.168.3.12 rport 41794
m=video 24806 UDP/TLS/RTP/SAVP 96 97
c=IN IP4 223.95.81.141
a=rtpmap:96 VP8/90000
a=fmtp:96 max-fs=3600
a=rtpmap:97 H264/90000
a=fmtp:97 packetization-mode=0;profile-level-id=42801f
a=sendonly
a=label:2
a=rtcp-rsize
a=ssrc:2806120015 cname:sip:1003@47.254.89.249
a=framerate:25.00
a=rtcp-fb:* nack pli
a=content:main
a=candidate:c0a8030c 1 UDP 2113932031 192.168.3.12 16782 typ host
a=candidate:df5f518c 1 UDP 1677721855 223.95.81.141 24806 typ srflx raddr 192.168.3.12 rport 16782
SIP/2.0 200 Answering
Record-Route: <sip:172.16.1.255;lr;nat=yes;did=d.f174cb11>
Via: SIP/2.0/UDP 172.16.1.255:5060;branch=z9hG4bKc843.dda753e5.0;received=47.254.89.249
Via: SIP/2.0/UDP 192.168.0.44:40719;received=223.95.81.141;branch=z9hG4bK.Hj-7MNum8;rport=26910
From: <sip:1005@47.254.89.249>;tag=U8nnGafdx
To: sip:1003@47.254.89.249;tag=b2fdeff7a3eb2106
CSeq: 20 INVITE
Call-ID: MQBki7GwtT
Server: baresip v0.6.3 (x86_64/linux)
Contact: <sip:1003-0x1368990@192.168.3.12:43215>
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER
Content-Type: application/sdp
Content-Length: 1228

v=0
o=- 3162123951 340234518 IN IP4 192.168.3.12
s=-
c=IN IP4 192.168.3.12
t=0 0
a=tool:baresip 0.6.3
a=ice-ufrag:xdHQ9bd
a=ice-pwd:aVLPh8UEaZZvu3B3XXqAZZBgxZpS4NE
a=setup:active
a=fingerprint:SHA-256 63:E2:FF:31:0F:E8:C2:E8:63:29:D4:48:72:EF:61:08:EE:F0:C6:E0:4A:E2:CB:99:78:B9:39:94:AC:66:58:50
m=audio 34586 UDP/TLS/RTP/SAVP 0 8 101
c=IN IP4 223.95.81.141
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=label:1
a=rtcp-rsize
a=ssrc:3464824102 cname:sip:1003@47.254.89.249
a=ptime:20
a=candidate:c0a8030c 1 UDP 2113932031 192.168.3.12 41794 typ host
a=candidate:df5f518c 1 UDP 1677721855 223.95.81.141 34586 typ srflx raddr 192.168.3.12 rport 41794
m=video 24806 UDP/TLS/RTP/SAVP 96 97
c=IN IP4 223.95.81.141
a=rtpmap:96 VP8/90000
a=fmtp:96 max-fs=3600
a=rtpmap:97 H264/90000
a=fmtp:97 packetization-mode=0;profile-level-id=42801f
a=sendonly
a=label:2
a=rtcp-rsize
a=ssrc:2806120015 cname:sip:1003@47.254.89.249
a=framerate:25.00
a=rtcp-fb:* nack pli
a=content:main
a=candidate:c0a8030c 1 UDP 2113932031 192.168.3.12 16782 typ host
a=candidate:df5f518c 1 UDP 1677721855 223.95.81.141 24806 typ srflx raddr 192.168.3.12 rport 16782
SIP/2.0 200 Answering
Record-Route: <sip:172.16.1.255;lr;nat=yes;did=d.f174cb11>
Via: SIP/2.0/UDP 172.16.1.255:5060;branch=z9hG4bKc843.dda753e5.0;received=47.254.89.249
Via: SIP/2.0/UDP 192.168.0.44:40719;received=223.95.81.141;branch=z9hG4bK.Hj-7MNum8;rport=26910
From: <sip:1005@47.254.89.249>;tag=U8nnGafdx
To: sip:1003@47.254.89.249;tag=b2fdeff7a3eb2106
CSeq: 20 INVITE
Call-ID: MQBki7GwtT
Server: baresip v0.6.3 (x86_64/linux)
Contact: <sip:1003-0x1368990@192.168.3.12:43215>
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER
Content-Type: application/sdp
Content-Length: 1228

v=0
o=- 3162123951 340234518 IN IP4 192.168.3.12
s=-
c=IN IP4 192.168.3.12
t=0 0
a=tool:baresip 0.6.3
a=ice-ufrag:xdHQ9bd
a=ice-pwd:aVLPh8UEaZZvu3B3XXqAZZBgxZpS4NE
a=setup:active
a=fingerprint:SHA-256 63:E2:FF:31:0F:E8:C2:E8:63:29:D4:48:72:EF:61:08:EE:F0:C6:E0:4A:E2:CB:99:78:B9:39:94:AC:66:58:50
m=audio 34586 UDP/TLS/RTP/SAVP 0 8 101
c=IN IP4 223.95.81.141
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=label:1
a=rtcp-rsize
a=ssrc:3464824102 cname:sip:1003@47.254.89.249
a=ptime:20
a=candidate:c0a8030c 1 UDP 2113932031 192.168.3.12 41794 typ host
a=candidate:df5f518c 1 UDP 1677721855 223.95.81.141 34586 typ srflx raddr 192.168.3.12 rport 41794
m=video 24806 UDP/TLS/RTP/SAVP 96 97
c=IN IP4 223.95.81.141
a=rtpmap:96 VP8/90000
a=fmtp:96 max-fs=3600
a=rtpmap:97 H264/90000
a=fmtp:97 packetization-mode=0;profile-level-id=42801f
a=sendonly
a=label:2
a=rtcp-rsize
a=ssrc:2806120015 cname:sip:1003@47.254.89.249
a=framerate:25.00
a=rtcp-fb:* nack pli
a=content:main
a=candidate:c0a8030c 1 UDP 2113932031 192.168.3.12 16782 typ host
a=candidate:df5f518c 1 UDP 1677721855 223.95.81.141 24806 typ srflx raddr 192.168.3.12 rport 16782

### accounts
<sip:1003@47.254.89.249>;answermode=auto;auth_pass=pass;regint=60;mediaenc=dtls_srtp;medianat=ice

### config
sip_listen		
sip_certificate	
sip_cafile		
call_local_timeout	120
call_max_calls		4
audio_path		/usr/local/share/baresip
audio_player		,
audio_source		aufile,/home/apple/.baresip/output.wav
audio_alert		,
auplay_srate		0
ausrc_srate		0
auplay_channels		0
ausrc_channels		0
audio_level		no
video_source		avformat,test.mp4
video_display		,
video_size		"544x960"
video_bitrate		512000
video_fps		25.00
video_fullscreen	yes
videnc_format		yuv420p
rtp_tos			184
rtp_ports		1024-49152
rtp_bandwidth		0-0
rtcp_mux		yes
jitter_buffer_delay	5-10
rtp_stats		no
rtp_timeout		0 # in seconds
net_prefer_ipv6		no
net_interface		
bfcp_proto	

### log
apple@ubuntu:~/.baresip$ baresip
baresip v0.6.3 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.
Local network address:  IPv4=enp0s5|192.168.3.12 
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
ausrc: aufile
vidcodec: H264
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
avcodec: using H.264 encoder 'libx264' -- libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.264 decoder 'h264' -- H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
vidcodec: VP8
vidsrc: avformat
medianat: stun
medianat: turn
medianat: ice
mediaenc: srtp
mediaenc: srtp-mand
mediaenc: srtp-mandf
mediaenc: dtls_srtp
1003@47.254.89.249: Using medianat 'ice'
1003@47.254.89.249: Using media encryption 'dtls_srtp'
Populated 1 account
Populated 1 contacts
Populated 2 audio codecs
Populated 0 audio filters
Populated 5 video codecs
Populated 0 video filters
baresip is ready.
1003@47.254.89.249: {0/UDP/v4} 200 OK (OpenSIPS (2.4.5 (x86_64/linux))) [1 binding]
All 1 useragent registered successfully! (193 ms)
ice: new session with STUN-server at 47.254.89.249 (username=1003)
ice: audio: Default local candidates: 223.95.81.141:12945 / ?
ice: video: Default local candidates: 223.95.81.141:46446 / ?
call: media-nat 'ice' established
answering call from sip:1004@47.254.89.249 with 200
stream: update
stream: update
{      audio.1} Set default remote candidate: host:192.168.0.165:7076
{      video.1} Set default remote candidate: host:192.168.0.165:9078
chklist: audio: pruned candidate pairs: 1
{      audio. } starting connectivity checks with 1 candidate pairs
{      audio.1}  host <--->  host  FSM:      Frozen ===> Waiting   
chklist: video: pruned candidate pairs: 1
{      video. } starting connectivity checks with 1 candidate pairs
{      audio.1}  host <--->  host  FSM:     Waiting ===> InProgress
{      audio.1} Tx enp0s5:host:192.168.3.12:11118 ---> host:192.168.0.165:7076 (InProgress)  
{      video.1}  host <--->  host  FSM:      Frozen ===> InProgress
{      video.1} Tx enp0s5:host:192.168.3.12:8760 ---> host:192.168.0.165:9078 (InProgress)  
{      audio.1} Rx enp0s5:host:192.168.3.12:11118 <--- host:192.168.0.165:7076 '0 ' (Connection timed out)
{      audio.1}  host <--->  host  FSM:  InProgress ===> Failed    
chklist: {audio.1} no valid candidate pair (validlist=0)
ice: audio: connectivity check is complete (update=0)
ice: connectivity check failed: No such file or directory
{      video.1} Rx enp0s5:host:192.168.3.12:8760 <--- host:192.168.0.165:9078 '0 ' (Connection timed out)
{      video.1}  host <--->  host  FSM:  InProgress ===> Failed    
chklist: {video.1} no valid candidate pair (validlist=0)
ice: video: connectivity check is complete (update=0)
ice: connectivity check failed: No such file or directory

**Comment by alfredh** [comment]
it looks like Linphone does not support rtcp-mux.

baresip supports rtcp-mux which is enabled in your config.

so Linphone will send 2 ice components (RTP and RTCP) while baresip
will only send 1 ice component (RTP).

you can try to disable it:

`rtcp_mux                no`

you can also try to enable ice debugging:

`ice_debug    yes`

and run baresip with verbose logging (-v).

**Comment by bihackers** [comment]
thanks. I will try it.

**Comment by bihackers** [comment]
I tried to set rtsp_mux to No.the log print:
________________________________log________________________________
ice: new session with STUN-server at 47.254.89.249 (username=1003)
ice: video: Default local candidates: 223.95.81.141:26372 / 223.95.81.141:33019
ice: audio: Default local candidates: 223.95.81.141:26371 / 223.95.81.141:33020
call: media-nat 'ice' established
answering call from sip:1005@47.254.89.249 with 200
stream: update
stream: update
{      audio.1} Set default remote candidate: srflx:112.17.238.104:42118
{      audio.2} Set default remote candidate: srflx:112.17.238.104:42119
{      video.1} Set default remote candidate: srflx:112.17.238.104:42120
{      video.2} Set default remote candidate: srflx:112.17.238.104:42121
chklist: audio: pruned candidate pairs: 4
{      audio. } starting connectivity checks with 4 candidate pairs
{      audio.1}  host <--->  host  FSM:      Frozen ===> Waiting   
{      audio.1}  host <---> srflx  FSM:      Frozen ===> Waiting   
chklist: video: pruned candidate pairs: 4
{      video. } starting connectivity checks with 4 candidate pairs
{      audio.1}  host <--->  host  FSM:     Waiting ===> InProgress
{      audio.1} Tx enp0s5:host:192.168.0.245:21708 ---> host:10.34.213.181:7076 (InProgress)  
{      video.1}  host <--->  host  FSM:      Frozen ===> InProgress
{      video.1} Tx enp0s5:host:192.168.0.245:33654 ---> host:10.34.213.181:9078 (InProgress)  
{      audio.1} Rx enp0s5:host:192.168.0.245:21708 <--- host:10.34.213.181:7076 '0 ' (Connection timed out)
{      audio.1}  host <--->  host  FSM:  InProgress ===> Failed    
{      audio.1}  host <---> srflx  FSM:     Waiting ===> InProgress
{      audio.1} Tx enp0s5:host:192.168.0.245:21708 ---> srflx:112.17.238.104:42118 (InProgress)  
{      video.1} Rx enp0s5:host:192.168.0.245:33654 <--- host:10.34.213.181:9078 '0 ' (Connection timed out)
{      video.1}  host <--->  host  FSM:  InProgress ===> Failed    
{      video.2}  host <--->  host  FSM:      Frozen ===> InProgress
{      video.2} Tx enp0s5:host:192.168.0.245:33655 ---> host:10.34.213.181:9079 (InProgress)  
{      audio.1} Rx enp0s5:host:192.168.0.245:21708 <--- srflx:112.17.238.104:42118 '0 ' (Connection timed out)
{      audio.1}  host <---> srflx  FSM:  InProgress ===> Failed    
{      audio.2}  host <--->  host  FSM:      Frozen ===> InProgress
{      audio.2} Tx enp0s5:host:192.168.0.245:21709 ---> host:10.34.213.181:7077 (InProgress)  
{      video.2} Rx enp0s5:host:192.168.0.245:33655 <--- host:10.34.213.181:9079 '0 ' (Connection timed out)
{      video.2}  host <--->  host  FSM:  InProgress ===> Failed    
{      video.1}  host <---> srflx  FSM:      Frozen ===> InProgress
{      video.1} Tx enp0s5:host:192.168.0.245:33654 ---> srflx:112.17.238.104:42120 (InProgress)  
{      audio.2} Rx enp0s5:host:192.168.0.245:21709 <--- host:10.34.213.181:7077 '0 ' (Connection timed out)
{      audio.2}  host <--->  host  FSM:  InProgress ===> Failed    
{      audio.2}  host <---> srflx  FSM:      Frozen ===> InProgress
{      audio.2} Tx enp0s5:host:192.168.0.245:21709 ---> srflx:112.17.238.104:42119 (InProgress)  
{      video.1} Rx enp0s5:host:192.168.0.245:33654 <--- srflx:112.17.238.104:42120 '0 ' (Connection timed out)
{      video.1}  host <---> srflx  FSM:  InProgress ===> Failed    
{      video.2}  host <---> srflx  FSM:      Frozen ===> InProgress
{      video.2} Tx enp0s5:host:192.168.0.245:33655 ---> srflx:112.17.238.104:42121 (InProgress)  
{      audio.2} Rx enp0s5:host:192.168.0.245:21709 <--- srflx:112.17.238.104:42119 '0 ' (Connection timed out)
{      audio.2}  host <---> srflx  FSM:  InProgress ===> Failed    
chklist: {audio.1} no valid candidate pair (validlist=0)
ice: audio: connectivity check is complete (update=0)
ice: connectivity check failed: No such file or directory
{      video.2} Rx enp0s5:host:192.168.0.245:33655 <--- srflx:112.17.238.104:42121 '0 ' (Connection timed out)
{      video.2}  host <---> srflx  FSM:  InProgress ===> Failed    
chklist: {video.1} no valid candidate pair (validlist=0)
ice: video: connectivity check is complete (update=0)
ice: connectivity check failed: No such file or directory
sip:1005@47.254.89.249: session closed: Connection timed out

**Comment by bihackers** [comment]
When I adjusted the mobile network to the same WIFI as the PC, I could see the image. What's the reason for this?

**Comment by bihackers** [comment]
Hello, @alfredh ,need your help.many thanks...

**Comment by alfredh** [comment]
aha, there is no connectivity between your 2 networks. that is why all
the host-host candidate pairs are failing.

if you are using 2 different NATs and one of the NAT is strict, you must
use a TURN server. A simple STUN server is not robust enough, it might work
in some cases but there is no guarantee. a TURN server will make sure that it
always works.

**Comment by bihackers** [comment]
my accounts:
<sip:1003@47.254.89.249>;answermode=auto;auth_pass=pass;regint=60;mediaenc=dtls_srtp;medianat=ice;stun:@47.254.89.249

How to configure account to get through two NATs？

**Comment by alfredh** [comment]
the `config` file should contain this:

```
ice_turn                yes
```

and the `accounts` file should contain this:

```
;stunserver=stun:username@turnserver.org;stunpass=PASSWORD
```


BTW: do you know if linphone works without turn ? perhaps you can setup
a working session between Linphone and baresip and then post the full
wireshark trace and log output here ?

**Comment by alfredh** [comment]
I have tested with linphone and baresip behind two different NATs
and it is working when using ICE with STUN-server and antisip.com SIP service.

the full baresip log is here:

https://gist.github.com/alfredh/233baf182b0440ab2808c92d3b23453f

I think you have a connectivity issue and I believe that baresip with ICE
is working as intended. If you can provide additional info, please
re-open the issue.
