### ISSUE TITLE
Turn Server TCP Support

### ISSUE THREAD

**Issue by kannanmaran** [alfredh/baresip#766]
Hello!

Am trying to use the turn server. by default you are supporting for UDP. is der any way to use turn server over TCP?

**Comment by alfredh** [comment]
the turn module currently only supports UDP.

which version of TURN/TCP do you mean ?

do you mean TCP from client to server and then UDP from server to peer, or
TCP all the way (TURN-TCP).

**Comment by alfredh** [comment]
thanks for your input. I have added TURN tunneling to the roadmap:

https://github.com/alfredh/baresip/wiki/Roadmap

the Issues tracker is mainly for reporting bugs.
For questions and feature request please use the re-devel mailing list:

http://lists.creytiv.com/mailman/listinfo/re-devel

**Comment by kannanmaran** [comment]
Hello @alfredh ,

We have an use cases like.. UDP port will be blocked in some network (Enterprise internal communication) in this case. We use TURN server. TCP from Client (Mobile application) to server and then UDP from server to peer. 

We have to check if UDP port is blocked and if they have turn server configuration for TCP then we have to use TURN with TCP.

I would like to contribute in this if you have some reference to work on this. Kindly share with me. it would be great. 

Thanks in advance,
Kannan
