### ISSUE TITLE
High RTP deltas in wireshark, intermittent sound on recording in Asterisk.

### ISSUE THREAD

**Issue by seamus-45** [alfredh/baresip#767]
Hi!

I'm not a voip engineer, coder, or native speaker, but I will try to explain correctly.
I have troubles with transmitting audio when `audio_txmode  poll`
Wireshark show periodic, not uniform, high RTP deltas, and call records are damaged on Asterisk end (or even call quality goes down).

Dumps for wireshark was made on client side, e.g this one with `ausrc_srate 48000`:
![20190730-13:11:03](https://user-images.githubusercontent.com/2586286/62112117-8c180380-b2cb-11e9-8dda-ca66a47a3201.png)

Reverse stream looks better:
![20190730-13:13:19](https://user-images.githubusercontent.com/2586286/62112277-d600e980-b2cb-11e9-84cf-85d0cc027217.png)

With `ausrc_srate 8000` deltas will be around 60ms, but still here. 

When `audio_txmode thread` is used, then all is fine!

I ask your advice in search of a possible reason. It's hardware or software problem? Below is my setup:

| name | value |
| --- | --- |
| Board | Raspberry Pi 3 B |
| Sound | [Jabra Evolve 20](https://www.jabra.com/business/office-headsets/jabra-evolve/jabra-evolve-20#/#4993-823-109) |
| Distro | Yocto (sumo) |
| Linux | 4.4.68 |
| Baresip | 1.6.3 (2894490) |
| libre/librem | 0.6.0 |
| Codec | PCMA;ptime=20 |

baresip config:
```
poll_method         epoll # poll, select, epoll ..
sip_trans_bsize     128
call_local_timeout  120
call_max_calls      4
audio_path          /usr/share/baresip
audio_player        alsa,default
audio_source        alsa,default
audio_alert         alsa,default
ausrc_srate         48000
auplay_srate        48000
audio_txmode        poll # poll, thread
rtp_tos             184
rtcp_enable         yes
rtcp_mux            no
jitter_buffer_delay 5-10 # frames
rtp_stats           yes
module_path         /usr/lib/baresip/modules
module              alsa.so
module              g711.so
module_app          auloop.so
module_app          menu.so
module_app          syslog.so
module_tmp          uuid.so
module_tmp          account.so
```

What else can I do? Thanks!

**Comment by alfredh** [comment]
the difference between poll and thread is basically:

* poll - send packets based on timing from sound card

* thread - send packets using a dedicated thread and a timer


please test the `auloop` command on your hardware:

(apply this patch first:
https://gist.github.com/alfredh/473a4ea2db44733786dd4d564846933c)

```
$ ./baresip -e "/auloop 8000 1"
```

and let is run for 10-20 seconds before doing "quit".

**Comment by alfredh** [comment]
here is the timing info from my Debian 10 computer (Intel Soundcard):

```
/auloop 8000 1
Audio-loop: 8000Hz, 1ch, S16LE
~~~~~ Audioloop summary: ~~~~~
8000 Hz 1ch S16LE

* Source
  module      alsa
  samples     89120
  duration    11.140 sec
  real ptime  0.03 / 19.95 / 30.18 ms (min/avg/max)
  avg.sampc   20.000 ms

* Player
  module      alsa
  samples     90080
  duration    11.259 sec
```


```
**** List of CAPTURE Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: ALC283 Analog [ALC283 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

the average ptime should be around 20ms.

**Comment by seamus-45** [comment]
```
/auloop 8000 1
Audio-loop: 8000Hz, 1ch, S16LE
~~~~~ Audioloop summary: ~~~~~
8000 Hz 1ch S16LE

* Source
  module      alsa
  samples     192960
  duration    24.120 sec
  real ptime  0.02 / 19.95 / 64.04 ms (min/avg/max)
  avg.sampc   20.000 ms

* Player
  module      alsa
  samples     193440
  duration    24.179 sec
```
```
/auloop 48000 1
Audio-loop: 48000Hz, 1ch, S16LE
~~~~~ Audioloop summary: ~~~~~
48000 Hz 1ch S16LE

* Source
  module      alsa
  samples     1160640
  duration    24.179 sec
  real ptime  0.02 / 19.95 / 63.97 ms (min/avg/max)
  avg.sampc   20.000 ms

* Player
  module      alsa
  samples     1169280
  duration    24.359 sec
```

**Comment by alfredh** [comment]
thanks,

could you please test with a different sound card and see how is the timing ?

**Comment by seamus-45** [comment]
Creative LIVE sound card

```
~~~~~ Audioloop summary: ~~~~~
8000 Hz 1ch S16LE

* Source
  module      alsa
  samples     175680
  duration    21.960 sec
  real ptime  0.02 / 20.07 / 22.16 ms (min/avg/max)
  avg.sampc   20.000 ms

* Player
  module      alsa
  samples     176640
  duration    22.079 sec
```

```
**** List of PLAYBACK Hardware Devices ****
card 0: U0x41e0x30d3 [USB Device 0x41e:0x30d3], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #290 
```

**Comment by seamus-45** [comment]
With Creative LIVE sound card similar picrure:
![20190806-15:12:14](https://user-images.githubusercontent.com/2586286/62532184-47f1a980-b85d-11e9-9d91-0abfa7c487e1.png)

Reverse:
![20190806-15:12:18](https://user-images.githubusercontent.com/2586286/62532192-4aec9a00-b85d-11e9-9ae4-0aba0ec0144e.png)

**Comment by seamus-45** [comment]
Hmm, I tend to believe this is not baresip problem at all.
I made these tests on other equipment (Atom Z8350). Same distro but with x64 4.15.18 kernel.
Tried two soundcards, es8316 and Creative LIVE. Results are excellent. Low jitter and normal average ptime. I guess the problem may be that raspberrypy does not have any hardware RTC or so.
Anyway, thank you for you attention and help!

**Comment by seamus-45** [comment]
@alfredh 
Interesting, I found if I change default ALSA device from `alsa,default` to `alsa,plughw:0,0` all works as intended. Deltas are gone. :confused:
