### ISSUE TITLE
Baresip as a lib: Attempting to use struct call results in error.

### ISSUE THREAD

**Issue by Alv3s** [alfredh/baresip#771]
Hello,

I've been using baresip as a library. Currently I'm passing baresip a callback function that receives a strctu call. As per my understanding, I can read this struct in order to have some context (for instance, I can know which call I'm on). Since I may have to handle a few calls, I need to read this struct to get the peerURI.

THe problem is: when you try to do it, the compiler gives the error:
``` error: invalid use of incomplete type 'struct call'```

The code is as follows:
```
void SIPPlayer::ua_event_handler(struct ua *ua, enum ua_event ev, struct call *call, const char *prm, void *arg)
{
                SIPPlayer* players = (SIPPlayer*)arg;
                logger.Info("UA Event: {0}", uag_event_str(ev));
                switch(ev)
                {
                    case UA_EVENT_CALL_RINGING:
                    {
                        logger.Info("Peer URI: {0}", call->peer_uri);
                        break;
                    }
                }
}
```

I tried to search for a header with it's declaration but it only happens on ```call.c```which, as expected, is not installed.

**Comment by GGGO** [comment]
Hello, 
to get peer_uri use call_peeruri(call).
Definition: `const char   *call_peeruri(const struct call *call);`
Please use the mailing list for question, http://lists.creytiv.com/mailman/listinfo/re-devel

**Comment by Alv3s** [comment]
@GGGO Thank you. You're a lifesaver!
