### ISSUE TITLE
how to change the starting source port

### ISSUE THREAD

**Issue by sbourji** [alfredh/baresip#772]

**Comment by sbourji** [comment]
is there a way to set the source port in the via and contact header to the source port in the  Transmission protocol for tcp?
this is the same for ump

**Comment by alfredh** [comment]
SIP over UDP and TLS will use the local port that is defined here:

```
transports:
  192.168.88.45:52511 (UDP)
  192.168.88.45:52470 (TCP)
  192.168.88.45:52471 (TLS)
```

the TCP connection will use a random ephemeral port for each connection
that is different from the listen port. this is correct.

you can use the `sip_listen` config:

`sip_listen             0.0.0.0:5050`

**Comment by sbourji** [comment]
I do understand that you can use sip_listen to change port for Via and contact header, but where are the above port defined? I cannot find them in the code, and as you see from the Wireshark, the TCP Port is 51079 not 52470.
The RFC state specifically the via header shall have the same local port
