### ISSUE TITLE
Android: What does the button next to the "more options" do? 

### ISSUE THREAD

**Issue by rodrigoaguilera** [alfredh/baresip#774]
This is the only app on f-droid that receives SIP calls correctly, thank you!

There is an icon in the top bar of the app that does not reveal any text when is long pressed and if tapped turns red but I don't know what is the function.

Can you clarify?

**Comment by juha-h** [comment]
As far as I know, this repo does not include any apps available f-droid.

**Comment by rodrigoaguilera** [comment]
Sorry wrong repo


https://github.com/juha-h/baresip-studio
