### ISSUE TITLE
I do understand that you can use sip_listen to change port for Via and contact header

### ISSUE THREAD

**Issue by sbourji** [alfredh/baresip#775]
I do understand that you can use sip_listen to change port for Via and contact header.
The RFC state specifically the via header shall have the same local port

_Originally posted by @sbourji in https://github.com/alfredh/baresip/issues/772#issuecomment-519044312_

**Comment by alfredh** [comment]
example SIP message when using TCP transport:


```
REGISTER sip:example.com SIP/2.0.
Via: SIP/2.0/TCP 192.168.88.41:57509;branch=z9hG4bK72f287bc03f2b1c5;rport.
Contact: <sip:aeh-0x7fbb50f1f930@192.168.88.41:57509;transport=tcp>;expires=600;+sip.instance="<urn:uuid:177c326b-3076-4da5-bd91-3d074d355dbc>";reg-id=1.
Max-Forwards: 70.
To: <sip:aeh@example.com>.
From: <sip:aeh@example.com>;tag=ce47fd7a54c718e6.
Call-ID: d56d207d50087d2b.
CSeq: 16245 REGISTER.
Content-Length: 0.
```

```
transports:
  192.168.88.41:59923 (UDP)
  192.168.88.41:57509 (TCP)
  192.168.88.41:57557 (TLS)
```

your SIP server should not look at those port numbers.
it should use the existing TCP connection for inbound requests
as per RFC 5626 (SIP Outbound).

Making a new TCP connection from a server with public IP-addr
to a client with NAT'ted private IP-address is not possible.
