### ISSUE TITLE
Feature request: MQTT API, add setanswermode command

### ISSUE THREAD

**Issue by seamus-45** [alfredh/baresip#776]
It will be not very difficult to add this command? As I can see, needed API already here: https://github.com/alfredh/baresip/commit/daa7013c1ca07cb6ede44673d526b6a16e77d824

Or maybe something like this: https://lists.nongnu.org/archive/html/linphone-developers/2010-02/msg00044.html

**Comment by alfredh** [comment]
yes it should be possible to add this command.

Does anyone want to volunteer to contribute a patch/PR ?

1. the new command can be implemented in menu.c
2. add a command handler for `/setanswermode`
3. resolve string to `enum answermode`
4. call `account_set_answermode` on the current ua/account.
