### ISSUE TITLE
If you implement a video encoding h264 on android, do you want to register the two strings "codec" and "vidsrc" at the same time, one is the video source and the other is video decoding?

### ISSUE THREAD

**Issue by yuexiajiayan** [alfredh/baresip#778]
Is that so? I think avformat module and avcodec are like this
vidsrc_register and vidcodec_register function

**Comment by alfredh** [comment]
for Android I would suggest that you use FFmpeg avcodec.

1. cross compile ffmpeg for android
2. build baresip with avcodec.so module
3. try to enable h264 encoder/decoder for android and enable the hwaccel backend "mediacodec"

```
# avcodec
avcodec_h264enc        h264_android
avcodec_h264dec        h264_android
avcodec_hwaccel        mediacodec
```

please let us know if this works :)

**Comment by juha-h** [comment]
Project https://github.com/juha-h/libbaresip-android/tree/video includes cross compile of ffmpeg.

**Comment by yuexiajiayan** [comment]
I need some time to test it.

**Comment by yuexiajiayan** [comment]
I implemented vidisp_register and vidsrc_register myself   and test mod avcodec  libx264 is ok  .  The horizontal screen is ok   but    the vertical screen is rotating. like this：

 Vertical screen  my Camera：
![1](https://user-images.githubusercontent.com/16077858/63578351-d6d32580-c5c2-11e9-96b4-fe1ab524e7ea.jpg)

but The other side sees：
![2](https://user-images.githubusercontent.com/16077858/63578423-041fd380-c5c3-11e9-87f5-dad3fed8d4a0.jpg)

The horizontal screen is OK,

Is there any way to change him? @juha-h @alfredh 

Copy from yup420 to vidframe like this ：

   struct vidframe vf;
        vf.fmt =VID_FMT_YUV420P;

        vf.size =st->sz;
        for (i=0; i<4; i++) {
            vf.data[i]     = frame->data[i];
            vf.linesize[i] = frame->linesize[i];
        }

**Comment by alfredh** [comment]
can you please share your code ?

1. please share the source code that you have used
2. please include a full log/output from this session.

**Comment by yuexiajiayan** [comment]
> can you please share your code ?
> 
> 1. please share the source code that you have used
> 2. please include a full log/output from this session.

hao to share my code ?Is it pasted here?

**Comment by alfredh** [comment]
there are many ways to share your code:

1. create a diff/patch and upload it here as a file
2. use github GIST to share the patch
3. if the code is small share it here as inline
4. fork the project and push your changes, publish the branch.

**Comment by yuexiajiayan** [comment]
> there are many ways to share your code:
> 
> 1. create a diff/patch and upload it here as a file
> 2. use github GIST to share the patch
> 3. if the code is small share it here as inline
> 4. fork the project and push your changes, publish the branch.

1.copy Nv12 data of camera to yuv Queue like this：
       AVFrame *avFrame = av_frame_alloc();
        int picture_size = av_image_get_buffer_size(AV_PIX_FMT_YUV420P, vw, vh, 1);
        uint8_t buffers[picture_size];
        av_image_fill_arrays(avFrame->data, avFrame->linesize, buffers, AV_PIX_FMT_YUV420P, vw, vh, 1);
        int size = vw * vh;
        memcpy(avFrame->data[0], bytes, size); //Y
        for (j = 0; j < size / 4; j++) {
            *(avFrame->data[2] + j) = *(bytes + size + j * 2); // V
            *(avFrame->data[1] + j) = *(bytes + size + j * 2 + 1); //U
        }
   frameQueue->putAvFrame(avFrame);

2. vidsrc_register like avformat 
 vidsrc_register(&mod_avf, baresip_vidsrcl(),   "avformat", alloc, NULL);
static void *read_thread(void *data)
{
    struct vidsrc_st *st =(struct vidsrc_st *) data;
    int64_t pts;
    uint64_t timestamp; unsigned i;
    while (st->run) {
        if( st->frameQueue==NULL ){  break;}
        AVFrame *frame=st->frameQueue->getAvFrame();
        if(  frame==NULL ){ continue;}
        struct vidframe vf;
        vf.fmt =VID_FMT_YUV420P;

        vf.size =st->sz;
        for (i=0; i<4; i++) {
            vf.data[i]     = frame->data[i];
            vf.linesize[i] = frame->linesize[i];
        }
        pts = frame->pts;
        timestamp = pts * VIDEO_TIMEBASE * 1 / 25;
       // LOGE("当前pts==%lld",pts);
        st->frameh(&vf, timestamp, st->arg);

        if (frame) {
            av_frame_free(&frame);
        }
    }
    LOGE("停止");
    return NULL;
}

static int alloc(struct vidsrc_st **stp, const struct vidsrc *vs,
                 struct media_ctx **mctx, struct vidsrc_prm *prm,
                 const  struct vidsz *size, const char *fmt,
                 const char *dev, vidsrc_frame_h *frameh,
                 vidsrc_error_h *errorh, void *arg)
{
    vidsrc_st *st;
    uint32_t i;
    int ret, err = 0;
    double input_fps = 0;

    (void)mctx;
    (void)fmt;
    (void)errorh;

    if (!stp || !vs || !prm || !size || !frameh)
        return EINVAL;

    st = static_cast<vidsrc_st *>(mem_zalloc(sizeof(*st), destructor));
    if (!st)
        return ENOMEM;
   if(frameQueue==NULL){frameQueue = new FrameQueue();}
 
    jmethodID jmid1=   g_ctx.env->GetMethodID(g_ctx.myCapiCls,"c_bareVstart","()V");
    g_ctx.env->CallVoidMethod(g_ctx.myCapiObj,jmid1); //

    st->frameQueue= frameQueue;
    st->vs     = vs;
    st->sz =  *size;
    st->frameh = frameh;
    st->arg    = arg; 
    st->sz.w  = 352;
    st->sz.h   = 288; 
    st->run = true;
    err = pthread_create(&st->thread, NULL, read_thread, st);
    if (err) {
        st->run = false;
        goto out;
    }
    //set
    g_ctx.st=st;
out:
    if (err)
        mem_deref(st);
    else
        *stp = st; 
    return err;
}
When connected, the other party can see the video.

**No problem under the horizontal screen. The vertical screen shows the same as the picture above.**
 
3. show like opengl   
vidisp_register(&vid, baresip_vidispl(), "opengl", alloc1, NULL, display, hide);

 
static int display(struct vidisp_st *st, const char *title,  const struct vidframe *frame, uint64_t timestamp)
{
    AVFrame *avFrame = av_frame_alloc();
    for (int i=0; i<4; i++) {
        avFrame->data[i]=frame->data[i] ;
        avFrame->linesize[i]=frame->linesize[i] ;
    }

    //**send  y u v data to android activity  opengl  show**
    int width=frame->size.w,height=frame->size.h;
    jmethodID jmid1=   g_ctx.env->GetMethodID(g_ctx.myCapiCls,"c_renderYUV","(II[B[B[B)V");

    jbyteArray y = g_ctx.env->NewByteArray(width * height);
    g_ctx.env->SetByteArrayRegion(y, 0, width * height, (const jbyte *)(avFrame->data[0]));

    jbyteArray u = g_ctx.env->NewByteArray(width * height / 4);
    g_ctx.env->SetByteArrayRegion(u, 0, width * height / 4, (const jbyte *)(avFrame->data[1]) );

    jbyteArray v = g_ctx.env->NewByteArray(width * height / 4);
    g_ctx.env->SetByteArrayRegion(v, 0, width * height / 4, (const jbyte *)(avFrame->data[2]));

    g_ctx.env->CallVoidMethod(g_ctx.myCapiObj ,jmid1,width,height, y,u,v); //

    g_ctx.env->DeleteLocalRef(y);
    g_ctx.env->DeleteLocalRef(u);
    g_ctx.env->DeleteLocalRef(v);

    av_frame_free(&avFrame);
    av_free(avFrame);
    avFrame=NULL;

    return 0;
}
static void hide(struct vidisp_st *st) {
    if (!st)
        return;

}
static void destructor1(void *arg)
{

}
static int alloc1(struct vidisp_st **stp, const struct vidisp *vd,
                 struct vidisp_prm *prm, const char *dev,
                 vidisp_resize_h *resizeh, void *arg)
{
    struct vidisp_st *st;
    st = static_cast<vidisp_st *>(mem_zalloc(sizeof(*st), destructor1));
    if (!st)
        return ENOMEM;

    st->vd = vd;

    *stp = st;
    return 0;
}

**I don't know how to rotate the picture under the vertical screen.**
@alfredh

**Comment by alfredh** [comment]
if you expect to receive any help here, you need to publish your complete
source code. it is not very easy for me/us to look at fragments of code and
guess what is the other parts doing.

the answer to your question is rather logical; you need to rotate the frame by 90 degrees :)

**Comment by alfredh** [comment]
please note that this Issue tracker is mainly for reporting bugs/defects.

if you want to ask questions please use the mailing list:

http://lists.creytiv.com/mailman/listinfo/re-devel

If you have working code that you want to contribute to the project,
please create Pull Request for that.
