### ISSUE TITLE
Security Voice call/ Video call

### ISSUE THREAD

**Issue by gambogo** [alfredh/baresip#78]
Hi Alfred,

I deployed your Restund server with my host, it run successfully and i can make video call, audio call with any network.
But i need actually do the peer to peer connection, so does your Restund server support peer to peer ?
If not, because my app should deploy with high security so need your help to indicate alternative way or change config on Restund to make the P2P call. I'm developing on iOS app.
Btw, about Restund, the mysql-db what tables does it need? what's the main purpose of mysql configuration ?

Thank you so much

**Comment by gambogo** [comment]
and in baresip with medianat=ice. how can we set up multiple STUN and TURN server ? currently, i can see only STUN or TURN is used combine with ICE, not both

**Comment by alfredh** [comment]
many questions here, not sure if I can answer all of them :)

- Restund is a STUN/TURN server that is relaying packets. It is recommended to enable
 authentication, and you can add your users in a MySQL database or in a text file.

- I dont really understand what you mean by restund doing P2P ? If you are using ICE for
  both SIP devices, then some network topologies may give you direct P2P traffic, and others
 might be relayed via TURN servers.

- baresip supports only 1 STUN or TURN server currently. It might be possible to implement
  support for multiple servers.

- using ZRTP should be transparent to the underlying media transport (i.e. direct or TURN).

**Comment by gambogo** [comment]
I think this is the last question for this topic, Alfred :)

Now i know only 1 STUN or TURN is selected at "config" file but i need to change between STUN and TURN programmatically.  Because the "config" file can't be changed at my app running (iOS app), so i can't change the server name, medianat type at run-time.

Can you give me some lines of code to switch between STUN or TURN server ?

Thanks so much
