### ISSUE TITLE
PulseAudio module doesn't follow default device

### ISSUE THREAD

**Issue by trampster** [alfredh/baresip#781]
If you don't specify a device then the PulseAudio module uses the first one in the list. In my case this isn't the default PulseAudio device.

If you call pa_simple_new with NULL for the device then it will use the default.

    const char *dev,                    /**< Sink (resp. source) name, or NULL for default */

So all baresip needs to do is use NULL if a device isn't specified. However instead it goes to a lot of effort to get the list of available devices and then use the first one.

I'm worried that there might be some obscure reason that baresip tries (and fails) to work out the default itself instead of using NULL that I'm unaware of. However if there isn't a reason then I'm more than happy to create a pull request to switch to using NULL if a device isn't specified.

**Comment by trampster** [comment]
You may be wondering why I don't just specify the device in the baresip config? 

Because I'd rather not have to reconfigure baresip every time I switch my headset.

**Comment by alfredh** [comment]
does it work if you use the magical device name `default` ?

I am happy to merge such a PR from you :)

do you have any example logs from a session that fails for you ?

**Comment by alfredh** [comment]
please note that the PR will be merge after 0.6.4 is released:

https://github.com/alfredh/baresip/issues/777

**Comment by trampster** [comment]
If i use default then I get the following:

     audio: start_source failed (pulse.default): No such device

This does work if you are using the Alsa module, but doesn't work with PulseAudio.

**Comment by trampster** [comment]
As far as logs go, there isn't anything interesting in the logs, it just uses the wrong device.

**Comment by trampster** [comment]
Pull request created #785

**Comment by alfredh** [comment]
fixed in 323e0dac0268951fe9dd53c99a4a9b742fa4d375
