### ISSUE TITLE
would be OK to add dns_debug API function?

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#788]
Baresip API has net_debug function that also prints dns_debug info.  In some cases, I'm only interested in dns_debug info and would like to skip the rest.

Would it be OK to expose net.c internal function
```
static int dns_debug(struct re_printf *pf, const struct network *net)
```
to baresip API?

**Comment by alfredh** [comment]
yes that should be fine. the function should have a "net_" prefix:

```c
int net_dns_debug(struct re_printf *pf, const struct network *net)
```

NOTE: I am releasing baresip 0.6.4 tomorrow so from now and until the
release is out, no commits to master please.

**Comment by juha-h** [comment]
OK, will do after that.
