### ISSUE TITLE
IPv6 in SDP

### ISSUE THREAD

**Issue by oej** [alfredh/baresip#79]
When sending an OFFER with IPv6 in the SDP to a baresip that's IPv4 only, Baresip responds 200 OK with IPv4 in the SDP. We get no media - of course.

RFC 6157 speaks clearly about this (and updates 3264):
" 2.  Each media description in the SDP answer MUST use the same
       network type as the corresponding media description in the offer.
       Thus, if the applicable "c=" line for a media description in the
       offer contained a network type with the value "IP4", the
       applicable "c=" line for the corresponding media description in
       the answer MUST contain "IP4" as the network type.  Similarly, if
       the applicable "c=" line for a media description in the offer
       contained a network type with the value "IP6", the applicable
       "c=" line for the corresponding media description in the answer
       MUST contain "IP6" as the network type.
"

**Comment by alfredh** [comment]
Olle, could you please try latest baresip from github and see if it works as expected?
