### ISSUE TITLE
Baresip places different src port in Contact header

### ISSUE THREAD

**Issue by dmitriybabintsev** [alfredh/baresip#792]
Hello.
Can you please advice why baresip agent sends TCP Register from one src port, but in the Contact header it places another one? Please see the attached screenshot of a wireshark packet.

And I have an additional question: may the src port be configured?
Thank you in advance.

![baresip_tcp_register](https://user-images.githubusercontent.com/53568385/64414753-9d0f1e00-d09c-11e9-87fe-79d9b52780b1.PNG)
 one?

**Comment by alfredh** [comment]
the TCP source port is an ephemeral port selected by the operating system.

use the `/sipstat` command to show the SIP listening ports:

```
/sipstat
transports:
  10.0.1.8:62368 (UDP)
  10.0.1.8:63291 (TCP)
  10.0.1.8:63292 (TLS)
client transactions:
server transactions:
```

the SIP listening port can be configured with `sip_listen` directive

```
sip_listen             0.0.0.0:5060
```

For SIP over TCP the inbound request is sent via:

1. if SIP outbound is used, reuse the same TCP connection from client to server
2. otherwise server to server, use the port number in the Contact header

the SIP stack is correctly implemented.

**Comment by dmitriybabintsev** [comment]
Thanks for your reply Alfred.
My application creates several client agents, so I believe sip_listen parameter is not sutable for me as it's configured in config file right?

Is it possible to make baresip put the same port into the Contact header as the src port it opened and sends the packets from?

Different Contact and src ports produce an issue with incoming calls because user agent puts wrong port in Contact header of 200Ok response that's why ACK request from the SIP proxy is tried to be sent to the port which is not opened by user agent.

**Comment by alfredh** [comment]
it is not possible to configure the local source port for TCP connections.

did you enable Record Routing on your SIP proxy ?

the SIP stack is listening on a single port for incoming TCP connections,
this port can easily be reused by many User-Agents.

can you please share the full SIP trace of your failing scenario?
(please use ngrep and paste the trace inline verbatim).

**Comment by dmitriybabintsev** [comment]
Hi Alfred.
Below is the SIP trace of incoming call.
Alfred I was wrong when said that baresip puts wrong port in 200Ok responce to Invite. Port in 200Ok is good, the only wrong port is in REGISTER, and looks like SIP proxy is trying to send ACK to the Contact from REGISTER.

`T 2019/09/09 07:09:40.084179 10.24.135.211:58750 -> 104.245.57.67:5090 [AP]
REGISTER sip:sip.ringcentral.com SIP/2.0.
Via: SIP/2.0/TCP 10.24.135.211:43233;branch=z9hG4bK8af881c7f57f5424;rport.
Contact: <sip:19705303795-0x2499890@10.24.135.211:43233;transport=tcp>;expires=3815.
Max-Forwards: 70.
Route: <sip:sip126.ringcentral.com:5090;transport=tcp;lr>.
To: <sip:19705303795@sip.ringcentral.com>.
From: <sip:19705303795@sip.ringcentral.com>;tag=bea1e2d9db14314b.
Call-ID: e184317bbfd294c1.
CSeq: 6322 REGISTER.
User-Agent: baresip v0.6.3 (x86_64/linux).
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER.
Content-Length: 0.
.


T 2019/09/09 07:09:40.091922 104.245.57.67:5090 -> 10.24.135.211:58750 [AP]
SIP/2.0 100 Giving a try.
Via: SIP/2.0/TCP 10.24.135.211:43233;branch=z9hG4bK8af881c7f57f5424;rport=58750.
To: <sip:19705303795@sip.ringcentral.com>.
From: <sip:19705303795@sip.ringcentral.com>;tag=bea1e2d9db14314b.
Call-ID: e184317bbfd294c1.
CSeq: 6322 REGISTER.
Server: kamailio (5.1.1 (x86_64/linux)).
Content-Length: 0.
.


T 2019/09/09 07:09:40.095967 104.245.57.67:5090 -> 10.24.135.211:58750 [AP]
SIP/2.0 401 Unauthorized.
Via: SIP/2.0/TCP 10.24.135.211:43233;branch=z9hG4bK8af881c7f57f5424;rport=58750.
To: <sip:19705303795@sip.ringcentral.com>;tag=bf6db0a8e1b42850df523c1d97291cbe-e836.
From: <sip:19705303795@sip.ringcentral.com>;tag=bea1e2d9db14314b.
Call-ID: e184317bbfd294c1.
CSeq: 6322 REGISTER.
WWW-Authenticate: Digest realm="sip.ringcentral.com", nonce="XXX74F11+rR8tsxqqx6kD6hgOS703TK5".
Content-Length: 0.
.


T 2019/09/09 07:09:40.598376 10.24.135.211:58750 -> 104.245.57.67:5090 [AP]
REGISTER sip:sip.ringcentral.com SIP/2.0.
Via: SIP/2.0/TCP 10.24.135.211:43233;branch=z9hG4bK0984f1885e7551f8;rport.
Contact: <sip:19705303795-0x2499890@10.24.135.211:43233;transport=tcp>;expires=3815.
Max-Forwards: 70.
Authorization: Digest username="15932361020", realm="sip.ringcentral.com", nonce="XXX74F11+rR8tsxqqx6kD6hgOS703TK5", uri="sip:sip.ringcentral.com", response="d9e47881bbee165f60b7b510f6163924".
Route: <sip:sip126.ringcentral.com:5090;transport=tcp;lr>.
To: <sip:19705303795@sip.ringcentral.com>.
From: <sip:19705303795@sip.ringcentral.com>;tag=bea1e2d9db14314b.
Call-ID: e184317bbfd294c1.
CSeq: 6323 REGISTER.
User-Agent: baresip v0.6.3 (x86_64/linux).
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER.
Content-Length: 0.
.


T 2019/09/09 07:09:40.604215 104.245.57.67:5090 -> 10.24.135.211:58750 [AP]
SIP/2.0 100 Giving a try.
Via: SIP/2.0/TCP 10.24.135.211:43233;branch=z9hG4bK0984f1885e7551f8;rport=58750.
To: <sip:19705303795@sip.ringcentral.com>.
From: <sip:19705303795@sip.ringcentral.com>;tag=bea1e2d9db14314b.
Call-ID: e184317bbfd294c1.
CSeq: 6323 REGISTER.
Server: kamailio (5.1.1 (x86_64/linux)).
Content-Length: 0.
.


T 2019/09/09 07:09:40.614220 104.245.57.67:5090 -> 10.24.135.211:58750 [AP]
SIP/2.0 200 OK.
Via: SIP/2.0/TCP 10.24.135.211:43233;branch=z9hG4bK0984f1885e7551f8;rport=58750.
To: <sip:19705303795@sip.ringcentral.com>;tag=77efe03e7c518d3cd3c9d0a5defcade8-ad43.
From: <sip:19705303795@sip.ringcentral.com>;tag=bea1e2d9db14314b.
Call-ID: e184317bbfd294c1.
CSeq: 6323 REGISTER.
Contact: <sip:19705303795-0x2499890@10.24.135.211:43233;transport=tcp>;expires=3600.
Content-Length: 0.
.


T 2019/09/09 07:10:10.865301 104.245.57.67:5090 -> 10.24.135.211:58750 [AP]
INVITE sip:19705303795-0x2499890@10.24.135.211:43233;transport=tcp SIP/2.0.
Via: SIP/2.0/TCP 104.245.57.67:5090;branch=z9hG4bKsjo3ra208oh7m33gh750.1.
Max-Forwards: 68.
User-Agent: RC_SIPWRP_22.254.
From: "Dmitry Babintsev" <sip:6502654878@104.245.57.67>;tag=10.13.22.254-5070-9d9d361d3f0042.
To: "Dmitry Babintsev" <sip:19705303795@10.24.135.211>.
Contact: <sip:6502654878@104.245.57.67:5090;transport=tcp>.
Call-ID: 66799578d7704ff9be1b1b21af112955.
CSeq: 17513 INVITE.
Call-Info: <5oBGYaIK1kNctHtoqIC0RA..>;purpose=info.
Allow: SUBSCRIBE, NOTIFY, REFER, INVITE, ACK, BYE, CANCEL, UPDATE, INFO.
Supported: replaces, timer, diversion.
Session-Expires: 14400;refresher=uac.
Min-SE: 90.
Content-Type: application/sdp.
Content-Length: 531.
P-Acme-VSA: 200:5oBGYaIK1kNctHtoqIC0RA...
.
v=0.
o=- 6017365704485824558 1854761014466916702 IN IP4 104.245.57.67.
s=SmcSip.
c=IN IP4 104.245.57.67.
t=0 0.
m=audio 26828 RTP/AVP 8 9 0 18 96 109 111 101.
a=rtpmap:8 pcma/8000.
a=rtpmap:9 g722/8000.
a=rtpmap:0 pcmu/8000.
a=rtpmap:18 g729/8000.
a=fmtp:18 annexb=no.
a=rtpmap:96 ilbc/8000.
a=fmtp:96 mode=20.
a=rtpmap:109 OPUS/16000.
a=fmtp:109 useinbandfec=1.
a=rtcp-fb:109 ccm tmmbr.
a=rtpmap:111 OPUS/48000/2.
a=fmtp:111 useinbandfec=1.
a=rtcp-fb:111 ccm tmmbr.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-15.
a=sendrecv.


T 2019/09/09 07:10:10.865925 10.24.135.211:58750 -> 104.245.57.67:5090 [AP]
SIP/2.0 180 Ringing.
Via: SIP/2.0/TCP 104.245.57.67:5090;branch=z9hG4bKsjo3ra208oh7m33gh750.1.
From: "Dmitry Babintsev" <sip:6502654878@104.245.57.67>;tag=10.13.22.254-5070-9d9d361d3f0042.
To: "Dmitry Babintsev" <sip:19705303795@10.24.135.211>;tag=91dfd6cc9fcd60e2.
Call-ID: 66799578d7704ff9be1b1b21af112955.
CSeq: 17513 INVITE.
Server: baresip v0.6.3 (x86_64/linux).
Contact: <sip:19705303795-0x2499890@10.24.135.211:58750;transport=tcp>.
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER.
Content-Length: 0.
.


T 2019/09/09 07:10:12.634644 10.24.135.211:58750 -> 104.245.57.67:5090 [AP]
SIP/2.0 200 Answering.
Via: SIP/2.0/TCP 104.245.57.67:5090;branch=z9hG4bKsjo3ra208oh7m33gh750.1.
From: "Dmitry Babintsev" <sip:6502654878@104.245.57.67>;tag=10.13.22.254-5070-9d9d361d3f0042.
To: "Dmitry Babintsev" <sip:19705303795@10.24.135.211>;tag=91dfd6cc9fcd60e2.
Call-ID: 66799578d7704ff9be1b1b21af112955.
CSeq: 17513 INVITE.
Server: baresip v0.6.3 (x86_64/linux).
Contact: <sip:19705303795-0x2499890@10.24.135.211:58750;transport=tcp>.
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER.
Content-Type: application/sdp.
Content-Length: 341.
.
v=0.
o=- 862138928 1726289264 IN IP4 10.24.135.211.
s=-.
c=IN IP4 10.24.135.211.
t=0 0.
a=tool:baresip 0.6.3.
m=audio 16168 RTP/AVP 8 0 101.
a=rtpmap:8 PCMA/8000.
a=rtpmap:0 PCMU/8000.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-15.
a=sendrecv.
a=label:1.
a=rtcp-rsize.
a=ssrc:2832096280 cname:sip:19705303795@10.24.135.211.
a=ptime:20.


T 2019/09/09 07:10:13.134594 10.24.135.211:58750 -> 104.245.57.67:5090 [AP]
SIP/2.0 200 Answering.
Via: SIP/2.0/TCP 104.245.57.67:5090;branch=z9hG4bKsjo3ra208oh7m33gh750.1.
From: "Dmitry Babintsev" <sip:6502654878@104.245.57.67>;tag=10.13.22.254-5070-9d9d361d3f0042.
To: "Dmitry Babintsev" <sip:19705303795@10.24.135.211>;tag=91dfd6cc9fcd60e2.
Call-ID: 66799578d7704ff9be1b1b21af112955.
CSeq: 17513 INVITE.
Server: baresip v0.6.3 (x86_64/linux).
Contact: <sip:19705303795-0x2499890@10.24.135.211:58750;transport=tcp>.
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER.
Content-Type: application/sdp.
Content-Length: 341.
.
v=0.
o=- 862138928 1726289264 IN IP4 10.24.135.211.
s=-.
c=IN IP4 10.24.135.211.
t=0 0.
a=tool:baresip 0.6.3.
m=audio 16168 RTP/AVP 8 0 101.
a=rtpmap:8 PCMA/8000.
a=rtpmap:0 PCMU/8000.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-15.
a=sendrecv.
a=label:1.
a=rtcp-rsize.
a=ssrc:2832096280 cname:sip:19705303795@10.24.135.211.
a=ptime:20.


T 2019/09/09 07:10:14.134585 10.24.135.211:58750 -> 104.245.57.67:5090 [AP]
SIP/2.0 200 Answering.
Via: SIP/2.0/TCP 104.245.57.67:5090;branch=z9hG4bKsjo3ra208oh7m33gh750.1.
From: "Dmitry Babintsev" <sip:6502654878@104.245.57.67>;tag=10.13.22.254-5070-9d9d361d3f0042.
To: "Dmitry Babintsev" <sip:19705303795@10.24.135.211>;tag=91dfd6cc9fcd60e2.
Call-ID: 66799578d7704ff9be1b1b21af112955.
CSeq: 17513 INVITE.
Server: baresip v0.6.3 (x86_64/linux).
Contact: <sip:19705303795-0x2499890@10.24.135.211:58750;transport=tcp>.
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER.
Content-Type: application/sdp.
Content-Length: 341.
.
v=0.
o=- 862138928 1726289264 IN IP4 10.24.135.211.
s=-.
c=IN IP4 10.24.135.211.
t=0 0.
a=tool:baresip 0.6.3.
m=audio 16168 RTP/AVP 8 0 101.
a=rtpmap:8 PCMA/8000.
a=rtpmap:0 PCMU/8000.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-15.
a=sendrecv.
a=label:1.
a=rtcp-rsize.
a=ssrc:2832096280 cname:sip:19705303795@10.24.135.211.
a=ptime:20.


T 2019/09/09 07:10:16.134603 10.24.135.211:58750 -> 104.245.57.67:5090 [AP]
SIP/2.0 200 Answering.
Via: SIP/2.0/TCP 104.245.57.67:5090;branch=z9hG4bKsjo3ra208oh7m33gh750.1.
From: "Dmitry Babintsev" <sip:6502654878@104.245.57.67>;tag=10.13.22.254-5070-9d9d361d3f0042.
To: "Dmitry Babintsev" <sip:19705303795@10.24.135.211>;tag=91dfd6cc9fcd60e2.
Call-ID: 66799578d7704ff9be1b1b21af112955.
CSeq: 17513 INVITE.
Server: baresip v0.6.3 (x86_64/linux).
Contact: <sip:19705303795-0x2499890@10.24.135.211:58750;transport=tcp>.
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER.
Content-Type: application/sdp.
Content-Length: 341.
.
v=0.
o=- 862138928 1726289264 IN IP4 10.24.135.211.
s=-.
c=IN IP4 10.24.135.211.
t=0 0.
a=tool:baresip 0.6.3.
m=audio 16168 RTP/AVP 8 0 101.
a=rtpmap:8 PCMA/8000.
a=rtpmap:0 PCMU/8000.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-15.
a=sendrecv.
a=label:1.
a=rtcp-rsize.
a=ssrc:2832096280 cname:sip:19705303795@10.24.135.211.
a=ptime:20.
`

**Comment by GGGO** [comment]
Hi @dmitriybabintsev, 
ACK is sent directy from 6502654878@104.245.57.67 to 19705303795@10.24.135.211, bypassing your kamailio server. You need to enable Record Routing in kamailio to prevent that.

**Comment by dmitriybabintsev** [comment]
Hi @GGGO 
I don't have kamailio in my network.

10.24.135.211 (user agent)  is interacting directly with 104.245.57.67(sip proxy)

**Comment by alfredh** [comment]
@dmitriybabintsev 

please report the issue to your SIP provider. this is not a bug in baresip.

**Comment by dmitriybabintsev** [comment]
But how can I make baresip put the correct port in Contact header of REGISTER request?

It's unclear for me why it places a correct port into the INVITE's Contact but a wrong one into REGISTER

**Comment by alfredh** [comment]
a client that is behind NAT can only make a TCP connection *from* the client
to the server. making a TCP connection from a server to NAT'ed client is not possible.

look carefully at the 200 ok response to the INVITE:

```
T 2019/09/09 07:10:12.634644 10.24.135.211:58750 -> 104.245.57.67:5090 [AP]
SIP/2.0 200 Answering.
Contact: <sip:19705303795-0x2499890@10.24.135.211:58750;transport=tcp>.
...
```

the port in Contact (58750) matches the TCP traffic. This is the port that the
ACK should be sent to, if it was not record routed.

But in a NAT'ed scenario the server MUST use recording routing.

It is very clear that your provider has a very buggy setup. Please report the
issue to them and ask them to enable Record-Routing.

**Comment by dmitriybabintsev** [comment]
Alfred, I don't have NAT in this scenario.
And the question is why:
```
T 2019/09/09 07:09:40.084179 10.24.135.211:58750 -> 104.245.57.67:5090 [AP]
REGISTER sip:sip.ringcentral.com SIP/2.0.
Via: SIP/2.0/TCP 10.24.135.211:43233;branch=z9hG4bK8af881c7f57f5424;rport.
Contact: <sip:19705303795-0x2499890@10.24.135.211:43233;transport=tcp>;expires=3815.
```
Actual src port was **58750**, but in Contact -  **43233**
While both ports in INVITE are correct - **58750**

Network interface of the host I use to start baresip agent has the only IP:
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.24.135.211 
```

**Comment by dmitriybabintsev** [comment]
Actually I can reproduce such behaviour on different hosts (when baresip places different TCP port into the Contact header of REGISTER)

**Comment by dmitriybabintsev** [comment]
Hi Alfred, below is the statistics of a created TCP connection
```
/uanew <sip:12054849118@sip.ringcentral.com>;auth_user=XXX;auth_pass=XXX;outbound="sip:sip125.ringcentral.com:5090;transport=tcp"
Creating UA for <sip:12054849118@sip.ringcentral.com>;auth_user=XXX;auth_pass=XXX;outbound="sip:sip125.ringcentral.com:5090;transport=tcp" ...
Entering sipreg_register function...
Dialog RURI in sip_dialog_alloc: sip:sip.ringcentral.com
Setting dlg->route from routes
Sending register request...
query: function entered
query: assigning dns query handler...
query: qp is not NULL
> sip:12054849118@sip.ringcentral.com        zzz 

Exiting from create_ua function
request.c: Request stateless
query: function entered
query: assigning dns query handler...
query: qp is not NULL
request.c: Request stateless
12054849118@sip.ringcentral.com: {0/TCP/v4} 200 OK () [1 binding]
All 1 useragent registered successfully! (10198 ms)
Useragent registered successfully
```

```
/sipstat
transports:
  10.0.2.15:53318 (UDP)
  10.0.2.15:42069 (TCP)
  10.0.2.15:9 (WS)
  10.0.2.15:41421 (TLS)
  10.0.2.15:9 (WSS)
connections:
  [1]   UDP  10.0.2.15:33752 --> 104.245.57.161:5090  (Established)
client transactions:
server transactions:
```

It seems strange to me why it shows  **10.0.2.15:42069 (TCP)** but the connection is marked as UDP (real is TCP):
**[1]   UDP  10.0.2.15:33752**

**Comment by alfredh** [comment]
it looks like you already have the SIP over Websocket patch working :)

many people are asking for that ..

**Comment by dmitriybabintsev** [comment]
yes, I previously applied this patch

**Comment by dmitriybabintsev** [comment]
I used this patch Alfred
https://github.com/alfredh/patches/blob/master/re-sip-websock-003.patch

**Comment by dmitriybabintsev** [comment]
But one more fix is required to prevent memory leak:
in file baresip-0.6.3/src/ua.c in condition _if (uag.use_wss)_ you need to add _if (!uag.tls)_ before tls_alloc function call:

```
if (uag.use_wss) {
                if (!uag.tls) {
                        err = tls_alloc(&uag.tls, TLS_METHOD_SSLV23, NULL, NULL);
                        if (err) {
                                warning("ua: tls_alloc() failed: %m\n", err);
                                return err;
                        }
                }
               ...
```

**Comment by alfredh** [comment]
it is the baresip patch that is missing. do you still have this one ?

**Comment by dmitriybabintsev** [comment]
no, that's all I have

**Comment by sreimers** [comment]
@alfredh is this the missing patch: https://github.com/sreimers/baresip/commits/sip_websock

**Comment by alfredh** [comment]
Thank you, Sebastian!

I have created a Wiki page for SIP over Websockets:

https://github.com/alfredh/baresip/wiki/SIP-over-Websockets

**Comment by juha-h** [comment]
Page

https://github.com/alfredh/baresip/wiki/SIP-over-Websockets

tells:
```
SIP over Websockets is currently an experimental feature.

Apply this patch to libre:
```

It would be simpler, it this patch would be included in

https://github.com/alfredh/re

**Comment by alfredh** [comment]
this issue became a bit off-topic ..

about the original issue: Please report the bug to your provider and
ask them to enable Record-Routing. This is not a bug in baresip.
