### ISSUE TITLE
How to specify a filename to save incoming audio to?

### ISSUE THREAD

**Issue by dmitriybabintsev** [alfredh/baresip#794]
Hello.
Sorry for this question, I just cannot find any related info.

I know that I can uncomment sndfile.so module in the config file and then incoming audio will be written to dump-2019-09-11-09-04-44-dec.wav files but the problem is I have multiple baresip agents running simultaneously and I need to distincguish their incoming audio threads.

**Comment by alfredh** [comment]
you can use the config option `snd_path` to set the path to the audio files:

```
snd_path    /tmp
```

Here is the example:

https://github.com/alfredh/baresip/blob/master/docs/examples/config#L195

**Comment by dmitriybabintsev** [comment]
Thanks for the info but this is not what I'm asking of..
Imagine, I have several baresip processes running sumultaneously:
baresip1
baresip2
baresip3

Each of them creates its own file with recorded audio, say
dump-2019-09-12-07-32-45-dec.wav
dump-2019-09-12-07-32-47-dec.wav
dump-2019-09-12-07-32-46-dec.wav

The problem is I don't understend which of these wav files was created by baresip1, which was created by baresip2 etc.

So the question is how can I make a certain baresip process to record audio to a custom file name, say, baresip1.wav for baresip1, baresip2.wav for baresip2 etc.
