### ISSUE TITLE
Make a call with a seamless 1k test tone

### ISSUE THREAD

**Issue by PhelarNord** [alfredh/baresip#795]
Hi!
Is there a function that makes it possible to send a +18 dBfs 1k sine loop. You can sometimes find this function in hardware codecs and its very convenient when doing quick tests and troubleshooting.

**Comment by alfredh** [comment]
have a look at librem's autone API:

```c
int autone_sine(struct mbuf *mb, uint32_t srate,
		uint32_t f1, int l1, uint32_t f2, int l2);
```

https://github.com/creytiv/rem/blob/master/include/rem_autone.h

you can create a new module (for example called `autone.so`) that
implements the AUSRC api and provides a continuous sine wave tone.

**Comment by PhelarNord** [comment]
Super! Thanks:)

I´ll look into this!
