### ISSUE TITLE
 how to compile webrtc_aec ?

### ISSUE THREAD

**Issue by blademckain** [alfredh/baresip#799]
Hello,
I would like to compile baresip with the webrtc aec module.
But in compiling it gives me an error as it requires the file echo_cancellation.h which I believe is part of the WEBRTC SDK.

Is there a guide explaining how to integrate the parts of SDK that are used in baresip?

**Comment by yuexiajiayan** [comment]
you can see https://github.com/juha-h/libbaresip-android  Makefile   or use it

**Comment by blademckain** [comment]
I need to compile it for raspberry arm6
not for android!

**Comment by blademckain** [comment]
ok i have cross compiled the webrtc using[ this guide](https://github.com/ipop-project/ipop-project.github.io/wiki/Build-WebRTC-Libraries-for-Raspberry-Pi-Zero-(Cross-compile-on-Ubuntu))

now how i can link it to baresip?

**Comment by blademckain** [comment]
I try to compile baresip with
`root@raspberrypi:~/baresip# make STATIC=yes EXTRA_MODULES=webrtc_aec WEBRTC_PATH=/root/libwebrtc/obj/
  CXX [m] build-arm6/modules/webrtc_aec/aec.o
modules/webrtc_aec/aec.cpp:13:10: fatal error: modules/audio_processing/aec/echo_cancellation.h: No such file or directory
 #include "modules/audio_processing/aec/echo_cancellation.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
`

and in /root/libwebrtc/obj/ i have the folder in the screenshot attached
![libwebrtc_folder](https://user-images.githubusercontent.com/39549249/65118191-15ee6e00-d9eb-11e9-8053-def2c64358fb.jpg)

**Comment by blademckain** [comment]
I had forgotten to include the headers in the WebRTC package

now the error that gives me this is:
`root@raspberrypi:~/baresip# make STATIC=yes EXTRA_MODULES=webrtc_aec WEBRTC_PATH=/root/libwebrtc
  LD      baresip
/usr/bin/ld: cannot find -lwebrtc_full
collect2: error: ld returned 1 exit status
make: *** [Makefile:199: baresip] Error 1
root@raspberrypi:~/baresip# find / -name libwebrtc_full.a
/root/libwebrtc/lib/libwebrtc_full.a
root@raspberrypi:~/baresip#
`

any help?

**Comment by alfredh** [comment]
the webrtc library must be put under the `Debug` folder:

```
#
# module.mk
#
# Copyright (C) 2010 Creytiv.com
#


WEBRTC_PATH	:= ../webrtc_sdk


MOD		:= webrtc_aec

$(MOD)_SRCS	+= aec.cpp
$(MOD)_SRCS	+= encode.cpp
$(MOD)_SRCS	+= decode.cpp

CPPFLAGS	+= -isystem $(WEBRTC_PATH)/include

LIBS	+= \
	-L$(WEBRTC_PATH)/lib/Debug \
	-lwebrtc_full \
	-lstdc++


include mk/mod.mk
```

try to add a `Debug` folder under lib and move the .a file there, i.e.:

`/root/libwebrtc/lib/Debug/libwebrtc_full.a`

**Comment by mrcasablr** [comment]
@blademckain I'm also interested in this. Here is another discussion on another project - https://github.com/kclyu/rpi-webrtc-streamer/issues/89

**Comment by blademckain** [comment]
anyone have an webrtc package compiled for raspberry pi zero ( armv6 ) ?

**Comment by blademckain** [comment]
i have compiled this package for pi zero ( armv6 )
https://freedesktop.org/software/pulseaudio/webrtc-audio-processing/
and build baresip with
`
make STATIC=yes EXTRA_MODULES=webrtc_aec WEBRTC_PATH=/root/libwebrtc

`

and now the error is:
`
call: connecting to 'sip:1002@127.0.0.1'..
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 180 Ringing (/)
stream: update 'audio'
audio: Set audio decoder: PCMA 8000Hz 1ch
audio: player started with sample format S16LE
audio: Set audio encoder: PCMA 8000Hz 1ch
webrtc_aec: creating shared state: [8000 Hz, 1 channels, subframe 80 samples, num_bands 1]
audio: source started with sample format S16LE
audio tx pipeline:        alsa ---> webrtc_aec ---> PCMA
audio rx pipeline:        alsa <--- webrtc_aec <--- PCMA
1001@127.0.0.1: Call established: sip:1002@127.0.0.1
Illegal instruction (core dumped)

`

**Comment by blademckain** [comment]
i have cross-compiled using this guide
https://github.com/kclyu/rpi-webrtc-streamer/blob/master/README_building.md

but now when start baresip i get:

`
root@raspberrypi:~/baresip# baresip
baresip v0.6.4 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.
Local network address:  IPv4=wlan0|192.168.14.80
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
dl: mod: /usr/local/lib/baresip/modules/webrtc_aec.so (/usr/local/lib/baresip/modules/webrtc_aec.so: undefined symbol: _ZN6webrtc31WebRtcAec_enable_delay_agnosticEPNS_7AecCoreEi)
module webrtc_aec.so: No such file or directory
ausrc: alsa
auplay: alsa
medianat: stun
medianat: turn
medianat: ice
medianat: ice-lite
Populated 1 account
Populated 3 contacts
Populated 2 audio codecs
Populated 0 audio filters
Populated 0 video codecs
Populated 0 video filters
baresip is ready.
1001@127.0.0.1: {0/UDP/v4} 200 OK (Asterisk PBX 16.2.1~dfsg-1+deb10u1) [1 binding]
All 1 useragent registered successfully! (55 ms)
terminated by signal 2
ua: stop all (forced=0)
root@raspberrypi:~/baresip#

`

**Comment by alfredh** [comment]
try to comment out this line:

https://github.com/alfredh/baresip/blob/master/modules/webrtc_aec/aec.cpp#L104

**Comment by blademckain** [comment]
hey @alfredh thx for support
but now the error is

`root@raspberrypi:~/baresip# baresip
baresip v0.6.4 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.
Local network address:  IPv4=wlan0|192.168.14.80
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
dl: mod: /usr/local/lib/baresip/modules/webrtc_aec.so (/usr/local/lib/baresip/modules/webrtc_aec.so: undefined symbol: _ZN6webrtc20WebRtcAec_set_configEPvNS_9AecConfigE)
module webrtc_aec.so: No such file or directory
ausrc: alsa
auplay: alsa
medianat: stun
medianat: turn
medianat: ice
medianat: ice-lite
Populated 1 account
Populated 3 contacts
Populated 2 audio codecs
Populated 0 audio filters
Populated 0 video codecs
Populated 0 video filters
baresip is ready.
1001@127.0.0.1: {0/UDP/v4} 200 OK (Asterisk PBX 16.2.1~dfsg-1+deb10u1) [1 binding]
All 1 useragent registered successfully! (24 ms)
`

**Comment by blademckain** [comment]
search with nm of my libwebrtc_full.a i found:

`aec_core.o:
         U __aeabi_idiv
         U __aeabi_ldivmod
         U floorf
         U _GLOBAL_OFFSET_TABLE_
00000000 r .LC0
0000002c r .LC1
00000000 r .LC10
00000000 r .LC11
00000030 r .LC12
00000044 r .LC2
00000000 r .LC3
00000004 r .LC4
0000000c r .LC5
00000000 r .LC6
00000020 r .LC7
00000040 r .LC8
00000058 r .LC9
         U log10f
         U logf
         U memcpy
         U __memcpy_chk
         U memmove
         U memset
         U powf
         U qsort
         U sincosf
         U sqrtf
         U __stack_chk_fail
         U __stack_chk_guard
         U strlen
         U WebRtc_available_read
         U WebRtc_available_write
         U WebRtc_CreateBuffer
         U WebRtc_FreeBuffer
         U WebRtc_InitBuffer
         U WebRtc_MoveReadPtr
         U WebRtc_ReadBuffer
         U WebRtcSpl_RandUArray
         U WebRtc_WriteBuffer
         U _Z16WebRtc_lookaheadPv
         U _Z17WebRtc_last_delayPv
         U _Z20WebRtc_set_lookaheadPvi
         U _Z25WebRtc_FreeDelayEstimatorPv
         U _Z25WebRtc_InitDelayEstimatorPv
         U _Z25WebRtc_last_delay_qualityPv
         U _Z25WebRtc_set_allowed_offsetPvi
         U _Z26WebRtc_AddFarSpectrumFloatPvPKfi
         U _Z27WebRtc_CreateDelayEstimatorPvi
         U _Z30WebRtc_SoftResetDelayEstimatorPvi
         U _Z31WebRtc_enable_robust_validationPvi
         U _Z31WebRtc_FreeDelayEstimatorFarendPv
         U _Z31WebRtc_InitDelayEstimatorFarendPv
         U _Z33WebRtc_CreateDelayEstimatorFarendii
         U _Z33WebRtc_DelayEstimatorProcessFloatPvPKfi
         U _Z36WebRtc_SoftResetDelayEstimatorFarendPvi
         U _ZdlPv
         U _ZN3rtc12FatalMessageC1EPKci
         U _ZN3rtc12FatalMessageC1EPKciPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
         U _ZN3rtc12FatalMessageD1Ev
00000000 W _ZN3rtc17MakeCheckOpStringIijEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc
00000000 T _ZN6webrtc10PowerLevelC1Ev
00000000 T _ZN6webrtc10PowerLevelC2Ev
00000000 T _ZN6webrtc11BlockBuffer10AdjustSizeEi
00000000 T _ZN6webrtc11BlockBuffer14AvaliableSpaceEv
00000000 T _ZN6webrtc11BlockBuffer20ExtractExtendedBlockEPf
00000000 T _ZN6webrtc11BlockBuffer4SizeEv
00000000 T _ZN6webrtc11BlockBuffer6InsertEPKf
00000000 T _ZN6webrtc11BlockBuffer6ReInitEv
00000000 T _ZN6webrtc11BlockBufferC1Ev
00000000 T _ZN6webrtc11BlockBufferC2Ev
00000000 T _ZN6webrtc11BlockBufferD1Ev
00000000 T _ZN6webrtc11BlockBufferD2Ev
         U _ZN6webrtc13ApmDataDumperC1Ei
         U _ZN6webrtc13ApmDataDumperD1Ev
00000000 T _ZN6webrtc15FormOutputFrameEjjPjPA128_fPKPf
00000000 T _ZN6webrtc16FormNearendBlockEjjPKPKfjPA48_S0_PA64_f
00000000 T _ZN6webrtc17BufferOutputBlockEjPA64_KfPjPA128_f
00000000 T _ZN6webrtc17WebRtcAec_FreeAecEPNS_7AecCoreE
00000000 t _ZN6webrtc17WebRtcAec_FreeAecEPNS_7AecCoreE.part.32
00000000 T _ZN6webrtc17WebRtcAec_InitAecEPNS_7AecCoreEi
00000000 T _ZN6webrtc18BufferNearendFrameEjjPKPKfjPA48_f
00000000 B _ZN6webrtc18WebRtcAec_SuppressE
         U _ZN6webrtc19BlockMeanCalculator5ResetEv
         U _ZN6webrtc19BlockMeanCalculator8AddValueEf
         U _ZN6webrtc19BlockMeanCalculatorC1Ej
00000000 T _ZN6webrtc19WebRtcAec_CreateAecEi
00000000 B _ZN6webrtc19WebRtcAec_FilterFarE
00000000 B _ZN6webrtc19WebRtcAec_OverdriveE
00000000 T _ZN6webrtc20WebRtcAec_echo_stateEPNS_7AecCoreE
00000000 B _ZN6webrtc20WebRtcAec_WindowDataE
00000000 R _ZN6webrtc21WebRtcAec_sqrtHanningE
00000000 R _ZN6webrtc21WebRtcAec_weightCurveE
00000000 T _ZN6webrtc22WebRtcAec_GetEchoStatsEPNS_7AecCoreEPNS_5StatsES3_S3_Pf
00000000 T _ZN6webrtc22WebRtcAec_system_delayEPNS_7AecCoreE
00000000 T _ZN6webrtc23DivergentFilterFraction14AddObservationERKNS_10PowerLevelES3_S3_
00000000 T _ZN6webrtc23DivergentFilterFraction5ClearEv
00000000 T _ZN6webrtc23DivergentFilterFraction5ResetEv
00000000 T _ZN6webrtc23DivergentFilterFractionC1Ev
00000000 T _ZN6webrtc23DivergentFilterFractionC2Ev
00000000 R _ZN6webrtc23WebRtcAec_kMinFarendPSDE
00000000 T _ZN6webrtc23WebRtcAec_ProcessFramesEPNS_7AecCoreEPKPKfjjiPKPf
00000000 T _ZN6webrtc23WebRtcAec_SetConfigCoreEPNS_7AecCoreEiii
00000000 R _ZN6webrtc24WebRtcAec_overDriveCurveE
00000000 B _ZN6webrtc24WebRtcAec_PartitionDelayE
00000000 T _ZN6webrtc24WebRtcAec_SetSystemDelayEPNS_7AecCoreEi
00000000 B _ZN6webrtc24WebRtcAec_StoreAsComplexE
00000000 B _ZN6webrtc26WebRtcAec_ComputeCoherenceE
00000000 B _ZN6webrtc26WebRtcAec_FilterAdaptationE
00000000 B _ZN6webrtc26WebRtcAec_ScaleErrorSignalE
00000000 T _ZN6webrtc27WebRtcAec_BufferFarendBlockEPNS_7AecCoreEPKf
00000000 T _ZN6webrtc29WebRtcAec_GetDelayMetricsCoreEPNS_7AecCoreEPiS2_Pf
00000000 T _ZN6webrtc31WebRtcAec_enable_delay_agnosticEPNS_7AecCoreEi
00000000 T _ZN6webrtc32WebRtcAec_delay_agnostic_enabledEPNS_7AecCoreE
00000000 T _ZN6webrtc32WebRtcAec_enable_extended_filterEPNS_7AecCoreEi
00000000 B _ZN6webrtc32WebRtcAec_UpdateCoherenceSpectraE
00000000 T _ZN6webrtc33WebRtcAec_extended_filter_enabledEPNS_7AecCoreE
00000000 R _ZN6webrtc38WebRtcAec_kNormalSmoothingCoefficientsE
00000000 T _ZN6webrtc40WebRtcAec_enable_refined_adaptive_filterEPNS_7AecCoreEb
00000000 R _ZN6webrtc40WebRtcAec_kExtendedSmoothingCoefficientsE
00000000 T _ZN6webrtc41WebRtcAec_refined_adaptive_filter_enabledEPKNS_7AecCoreE
00000000 T _ZN6webrtc46WebRtcAec_AdjustFarendBufferSizeAndSystemDelayEPNS_7AecCoreEi
00000000 T _ZN6webrtc7AecCoreC1Ei
00000000 T _ZN6webrtc7AecCoreC2Ei
00000000 T _ZN6webrtc7AecCoreD1Ev
00000000 T _ZN6webrtc7AecCoreD2Ev
         U _ZN6webrtc7metrics12HistogramAddEPNS0_9HistogramEi
         U _ZN6webrtc7metrics25HistogramFactoryGetCountsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiii
         U _ZN6webrtc8OouraFftC1Ev
         U _ZN6webrtc8OouraFftD1Ev
00000000 t _ZN6webrtcL10WindowDataEPfPKf
00000000 t _ZN6webrtcL11InitMetricsEPNS_7AecCoreE
00000000 r _ZN6webrtcL11kTargetSuppE
00000000 t _ZN6webrtcL11UpdateLevelEPNS_10PowerLevelEf
00000000 t _ZN6webrtcL14PartitionDelayEiPA2080_f
00000000 t _ZN6webrtcL14StoreAsComplexEPKfPA65_f
00000000 t _ZN6webrtcL16ComputeCoherenceEPKNS_14CoherenceStateEPfS3_
00000000 t _ZN6webrtcL16FilterAdaptationERKNS_8OouraFftEiiPA2080_fPA65_fS4_
00000000 t _ZN6webrtcL16ScaledInverseFftERKNS_8OouraFftEPA65_fPffi.constprop.40
00000000 t _ZN6webrtcL16ScaleErrorSignalEffPfPA65_f
00000000 t _ZN6webrtcL18UpdateDelayMetricsEPNS_7AecCoreE
00000000 r _ZN6webrtcL19kNormalMinOverDriveE
00000000 t _ZN6webrtcL19ProcessNearendBlockEPNS_7AecCoreEPfPA64_fS4_
00000000 t _ZN6webrtcL20UpdateLogRatioMetricEPNS_5StatsEff
00000000 r _ZN6webrtcL21kExtendedMinOverDriveE
00000000 t _ZN6webrtcL22UpdateCoherenceSpectraEibPA65_fS1_S1_PNS_14CoherenceStateEPsPi
00000000 t _ZN6webrtcL3FftERKNS_8OouraFftEPfPA65_f
00000000 t _ZN6webrtcL8CmpFloatEPKvS1_
00000000 t _ZN6webrtcL8SuppressEPKfPA65_f
00000000 t _ZN6webrtcL9FilterFarEiiPA2080_fS1_PA65_f
00000000 t _ZN6webrtcL9OverdriveEffPf
         U _ZNK6webrtc19BlockMeanCalculator10EndOfBlockEv
         U _ZNK6webrtc19BlockMeanCalculator13GetLatestMeanEv
00000000 T _ZNK6webrtc23DivergentFilterFraction17GetLatestFractionEv
         U _ZNK6webrtc8OouraFft10InverseFftEPf
         U _ZNK6webrtc8OouraFft3FftEPf
         U _ZNKSt5ctypeIcE13_M_widen_initEv
         U _ZNSo3putEc
         U _ZNSo5flushEv
         U _ZNSo9_M_insertImEERSoT_
         U _ZNSolsEi
         U _ZNSt6localeC1Ev
         U _ZNSt6localeD1Ev
         U _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_replaceEjjPKcj
00000000 W _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag
         U _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4_
         U _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERjj
         U _ZNSt8ios_baseC2Ev
         U _ZNSt8ios_baseD2Ev
         U _ZNSt9basic_iosIcSt11char_traitsIcEE4initEPSt15basic_streambufIcS1_E
         U _ZNSt9basic_iosIcSt11char_traitsIcEE5clearESt12_Ios_Iostate
         U _Znwj
         U _ZSt16__ostream_insertIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_PKS3_i
         U _ZSt16__throw_bad_castv
         U _ZSt19__throw_logic_errorPKc
         U _ZSt4endlIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_
         U _ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE
         U _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE
         U _ZTVNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE
         U _ZTVSt15basic_streambufIcSt11char_traitsIcEE
         U _ZTVSt9basic_iosIcSt11char_traitsIcEE
00000000 b _ZZN6webrtc12_GLOBAL__N_123MaybeLogDelayAdjustmentEiNS0_11DelaySourceEE24atomic_histogram_pointer
00000000 b _ZZN6webrtc12_GLOBAL__N_123MaybeLogDelayAdjustmentEiNS0_11DelaySourceEE24atomic_histogram_pointer_0`

**Comment by blademckain** [comment]
Yeah! 
I managed to compile webrtc for armv6

the compilation of baresip only works with the command

make STATIC = yes EXTRA_MODULES = webrtc_aec WEBRTC_PATH =....

**Comment by mrcasablr** [comment]
@blademckain  would you mind sharing the steps (in detail) to compile webrtc_sdk on armv6?

**Comment by blademckain** [comment]
yeah, 
whan i have tested all
i create another repo with the detailed info and a precompiled build.

At this time i have some trouble with the AEC. Is enable but doesn't work
i have to debug

**Comment by blademckain** [comment]
anyone know why the function
`void webrtc_aec_debug(const struct aec *aec)
`
in aec.cpp
doesn't print nothing though if i run baresip -v ?

**Comment by alfredh** [comment]
The webrtc_aec.so module is using the AEC code from the Google WebRTC project.
if there is any bugs in this library,  then it is outside our control and we cannot fix it.

Please note that the AEC code is most likely tuned for desktop and mobile, and
the algorithm is extremely sensitive to audio hardware (microphone, speaker).
Dont put your hopes that this AEC will run on your exotic hardware, and that
it shall work out of the box. You will most likely spend weeks and months
testing and tuning it.

This issue tracker is mainly kept for reporting and tracking defects.

For questions please use the mailing list:

http://lists.creytiv.com/mailman/listinfo/re-devel

**Comment by nyxnyx** [comment]
This is simple - webrtc is compiled using clang++ and baresip using gcc. clang++ and gcc have different mangling, meaning they name methods, functions differently. For that reason gcc compiled baresip can't find methods in libwebrtc. Same is for libwebrtc which is using libc++ delivered from clang toolchain but it is not attached to object files. Later when we are looking for c++ objects we have libstrc++ from gcc which have again different mangling. I'm right now trying to compile baresip using clang and GN tool.

**Comment by Vinayak-YB** [comment]
Hi @blademckain Did you build and use webrtc_aec with baresip? Can I get some documentation or steps to follow for building it?. I am trying too and facing same issues.
