### ISSUE TITLE
Error in compiling mqtt

### ISSUE THREAD

**Issue by blademckain** [alfredh/baresip#800]
Hi, i want compile baresip with mqtt support
but i get some errore
where i wrong?
i do:
`
root@raspberrypi:~/baresip/baresip# apt-get install libmosquitto-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  rpi.gpio-common
Use 'apt autoremove' to remove it.
The following NEW packages will be installed:
  libmosquitto-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/52.5 kB of archives.
After this operation, 136 kB of additional disk space will be used.
Selecting previously unselected package libmosquitto-dev:armhf.
(Reading database ... 94037 files and directories currently installed.)
Preparing to unpack .../libmosquitto-dev_1.5.7-1_armhf.deb ...
Unpacking libmosquitto-dev:armhf (1.5.7-1) ...
Setting up libmosquitto-dev:armhf (1.5.7-1) ...
Processing triggers for man-db (2.8.5-2) ...
root@raspberrypi:~/baresip/baresip# make EXTRA_MODULES="mqtt"
mk/mod.mk:35: warning: overriding recipe for target 'mqtt.so'
mk/mod.mk:35: warning: ignoring old recipe for target 'mqtt.so'
  LD [M]  mqtt.so
/usr/bin/ld: build-arm6/modules/mqtt/mqtt.o:/root/baresip/baresip/modules/mqtt/mqtt.c:193: multiple definition of `exports'; build-arm6/modules/mqtt/mqtt.o:/root/baresip/baresip/modules/mqtt/mqtt.c:193: first defined here
/usr/bin/ld: build-arm6/modules/mqtt/publish.o: in function `mqtt_publish_message':
/root/baresip/baresip/modules/mqtt/publish.c:51: multiple definition of `mqtt_publish_message'; build-arm6/modules/mqtt/publish.o:/root/baresip/baresip/modules/mqtt/publish.c:51: first defined here
/usr/bin/ld: build-arm6/modules/mqtt/publish.o: in function `mqtt_publish_init':
/root/baresip/baresip/modules/mqtt/publish.c:88: multiple definition of `mqtt_publish_init'; build-arm6/modules/mqtt/publish.o:/root/baresip/baresip/modules/mqtt/publish.c:88: first defined here
/usr/bin/ld: build-arm6/modules/mqtt/publish.o: in function `mqtt_publish_close':
/root/baresip/baresip/modules/mqtt/publish.c:100: multiple definition of `mqtt_publish_close'; build-arm6/modules/mqtt/publish.o:/root/baresip/baresip/modules/mqtt/publish.c:100: first defined here
/usr/bin/ld: build-arm6/modules/mqtt/subscribe.o: in function `mqtt_subscribe_init':
/root/baresip/baresip/modules/mqtt/subscribe.c:113: multiple definition of `mqtt_subscribe_init'; build-arm6/modules/mqtt/subscribe.o:/root/baresip/baresip/modules/mqtt/subscribe.c:113: first defined here
/usr/bin/ld: build-arm6/modules/mqtt/subscribe.o: in function `mqtt_subscribe_start':
/root/baresip/baresip/modules/mqtt/subscribe.c:124: multiple definition of `mqtt_subscribe_start'; build-arm6/modules/mqtt/subscribe.o:/root/baresip/baresip/modules/mqtt/subscribe.c:124: first defined here
/usr/bin/ld: build-arm6/modules/mqtt/subscribe.o: in function `mqtt_subscribe_close':
/root/baresip/baresip/modules/mqtt/subscribe.c:141: multiple definition of `mqtt_subscribe_close'; build-arm6/modules/mqtt/subscribe.o:/root/baresip/baresip/modules/mqtt/subscribe.c:141: first defined here
collect2: error: ld returned 1 exit status
make: *** [mk/mod.mk:36: mqtt.so] Error 1

`

**Comment by mrcasablr** [comment]
@blademckain what version of baresip? I'm able to compile mqtt on rpi4b.  Try without `make EXTRA_MODULES="mqtt"`  baresip should automatically pickup mqtt if the libraries are available.

**Comment by blademckain** [comment]
yeah!
compiled only with "make" works
it is possibile configure the host, port, username, password of the mqtt server to connect?
