### ISSUE TITLE
add g729 audio codec test ，Can you refer to him for rewriting ? 

### ISSUE THREAD

**Issue by yuexiajiayan** [alfredh/baresip#801]
**1. i see pjsip use g729** 
git clone git://git.linphone.org/bcg729.git （cmake 3.7.2）
cd
cmake -DDEBUG=ON -DCMAKE_TOOLCHAIN_FILE=/opt/ffandroid/android-ndk-r15c/build/cmake/android.toolchain.cmake -DCMAKE_INSTALL_PREFIX=./androidlib  -DANDROID_NDK=/opt/ffandroid/android-ndk-r15c    -DANDROID_ABI=arm64-v8a  -DANDROID_TOOLCHAIN=clang   -DANDROID_PLATFORM=android-26     -DANDROID_STL=c++_shared 
make 
make install

I have 729 libraries ready
2.pjsip use it in http://svn.pjsip.org/repos/pjproject/trunk/pjmedia/src/pjmedia-codec/bcg729.c

Can you refer to him for rewriting ? 

g7221 like this：

#include <re.h>
#include <baresip.h>
#include "g7221.h"

static struct g7221_aucodec g7221 = {
	.ac = {
		.name      = "G7221",
		.srate     = 16000,
		.crate     = 16000,
		.ch        = 1,
		.pch       = 1,
		.encupdh   = g7221_encode_update,
		.ench      = g7221_encode,
		.decupdh   = g7221_decode_update,
		.dech      = g7221_decode,
		.fmtp_ench = g7221_fmtp_enc,
		.fmtp_cmph = g7221_fmtp_cmp,
	},
	.bitrate = 32000,
};

static int module_init(void)
{
	aucodec_register(baresip_aucodecl(), (struct aucodec *)&g7221);

	return 0;
}

static int module_close(void)
{
	aucodec_unregister((struct aucodec *)&g7221);

	return 0;
}

EXPORT_SYM const struct mod_export DECL_EXPORTS(g7221) = {
	"g7221",
	"audio codec",
	module_init,
	module_close,
};
========================================
pjsip2 like :
static pjmedia_codec_op bcg729_op =
{
    &bcg729_codec_init,
    &bcg729_codec_open,
    &bcg729_codec_close,
    &bcg729_codec_modify,
    &bcg729_codec_parse,
    &bcg729_codec_encode,
    &bcg729_codec_decode,
    &bcg729_codec_recover
};

**Comment by alfredh** [comment]
BCG729 is GPL code and we cannot use that in baresip.

Baresip is using BSD license and libraries that we use must be
compliant with BSD.
