### ISSUE TITLE
hao to Using baresip as a library in vs2015?

### ISSUE THREAD

**Issue by benmcq2019** [alfredh/baresip#806]
i'm want to use it on qt  but i don't hao to use on vs2015 ?   Do you compile a .lib first?

**Comment by alfredh** [comment]
1. open mk/win32/baresip.vcxproj in VS2015
2. build the project
3. look at the API in include/baresip.h
4. read this https://github.com/alfredh/baresip/wiki/Using-baresip-as-a-library
5. create your application

please use the mailing-list for questions:

http://lists.creytiv.com/mailman/listinfo/re-devel
