### ISSUE TITLE
baresip win32 .lib file How do you use it in qt ?

### ISSUE THREAD

**Issue by yuexiajiayan** [alfredh/baresip#810]
I successfully compiled the mk/win32/baresip  project and i find the 
baresip-win32.lib 、re-win32.lib、rem-win32.lib
in Win32\Debug\bin

I add it to qt :
#pragma comment(lib, "re-win32.lib")
#pragma comment(lib, "rem-win32.lib")
#pragma comment(lib, "baresip-win32.lib")

but get it:
error LNK2019:unresolved external symbol   _conf_configure， The sign is in the function "protected: virtual void __thiscall QtBaresipThread::run(void)" (?run@QtBaresipThread@@MAEXXZ) Cited in。

 _conf_modules、_conf_path_set and other has same error

Is the library unavailable or is there a problem with its use?

**Comment by alfredh** [comment]
I think the baresip win32 project is just the baresip executable, and not the library.

are you linking to baresip.lib statically or dynamically ?

it would probably be helpful if you can share the full build logs and your QT Project.

**Comment by yuexiajiayan** [comment]
Can't this lib library be used in vs anymore? How to create a library and use it in qt?

**Comment by yuexiajiayan** [comment]
i'm used like this https://github.com/alfredh/baresip/wiki/Using-baresip-as-a-library

**Comment by alfredh** [comment]
The libre Visual Studio project file will produce a library.

I think the baresip Visual Studio project file will produce a binary application
and not a library. For example it includes main.c which is not needed for a library.

you most likely have to modify the VS project file, at least disable main.c

or create a new VS project that only includes src/*.c (except main.c) and
selected modules.

**Comment by yuexiajiayan** [comment]
ok i'm try it

**Comment by yuexiajiayan** [comment]
I tried to make the Lib library many times, but it failed. Can I modify it on the original baresip Win32 project

**Comment by Ackles-Olga** [comment]
Hello, please tell me, what edits are needed to run baresip on the visual studio ? I read articles on this subject, but nothing works yet
