### ISSUE TITLE
baresip win32 .sln run uanew   reg error? No such file or directory?

### ISSUE THREAD

**Issue by yuexiajiayan** [alfredh/baresip#812]
baresip v0.6.3 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.
Local network address:  IPv4={C119F2AE-6064-43F3-896B-BD03BFA9D218}|169.254.160.163
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
winwave: output devices: 1, input devices: 1
ausrc: winwave
auplay: winwave
vidsrc: dshow
medianat: stun
medianat: turn
medianat: ice
Populated 0 accounts
account: No SIP accounts found
 -- check your config or add an account using 'uanew' command
Populated 3 contacts
open: ./debug_cmd.dll LoadLibraryA() failed
module debug_cmd.dll: No such file or directory
Populated 2 audio codecs
Populated 0 audio filters
Populated 0 video codecs
Populated 0 video filters
baresip is ready.
============
/uanew <sip:1000@ip:7056>;auth=h12345
===================  
return this:
Creating UA for <sip:1000@ip:7056>;auth_pass=h12345
ua: SIP register failed: No such file or directory
> sip:1000@ip:7056                zzz

need config? hao to  set?

**Comment by alfredh** [comment]
maybe try to add angle brackets around the SIP uri, like:

```
<sip:1000@ip:7056>;auth_pass=h12345
```

otherwise try to add printf to the code and see where ENOENT is coming from.

**Comment by yuexiajiayan** [comment]
i'm  used <sip:1000@ip:7056>;auth_pass=h12345
but i't error  Is it related to this：

open: ./debug_cmd.dll LoadLibraryA() failed
module debug_cmd.dll: No such file or directory

**Comment by alfredh** [comment]
did you try with angle brackets as I asked you ?

the debug_cmd.dll warning is not related to this.

**Comment by yuexiajiayan** [comment]
yes i'm try   have same error :
![QQ图片20191014202021](https://user-images.githubusercontent.com/16077858/66750866-31e91080-eec0-11e9-8965-a67e1f3eaf05.png)

**Comment by alfredh** [comment]
this version is very old, please upgrade to latest version (0.6.4) or git and try again.

also please test if the accounts file is working,

$HOME/.baresip/accounts:

`<sip:username@domain.com>;auth_pass=XXXX`

**Comment by yuexiajiayan** [comment]
i‘m test it,I found it uses vmare's IP:
 VMware Network Adapter VMnet8:
  
   IPv4 address . . . . . . . . . . . . : 192.168.49.1 

wifi WLAN:
 
   IPv4 地址 . . . . . . . . . . . . : 192.168.10.231

**Comment by Encamy** [comment]
@yuexiajiayan sorry for late response, you can set config option `net_interface` to wanted ip. See https://github.com/alfredh/baresip/issues/403
