### ISSUE TITLE
Custom Ringtones and autorun

### ISSUE THREAD

**Issue by abzsol** [alfredh/baresip#814]
Hi, i've searched but i have not found an answer.

I'm trying to use a raspberry to register multiple account, set a different ringtone for every account and connect to a speaker as a Loud ringer for a pbx.

I have 2 problems:

- don't know how to start at boot

- can't figure how to set a custom ringtone on account setting.

Thanks

**Comment by premultiply** [comment]
Solution 1:
Create a simple systemd service to run baresip.

**Comment by Bettman66** [comment]
/etc/systemd/system/baresip.service
`[Unit]
Description=baresip
After=syslog.target network.target ntpdate.service

[Service]
Type=simple
User=pi
Group=pi
ExecStart=/usr/local/bin/baresip -f /home/pi/.baresip

[Install]
WantedBy=multi-user.target`

`sudo servicectl enable baresip
sudo service baresip start`

**Comment by abzsol** [comment]
Thanks! any hints on custom ringtone?

**Comment by alfredh** [comment]
currently it is not supported to set different ringtones per account.

you can emulate the custom ringtones by replacing the content
of the WAV files in:

```sh
l share/*.wav
-rw-r--r--  1 alfredh  staff  64320 Oct 18  2018 share/busy.wav
-rw-r--r--  1 alfredh  staff  80418 Oct 18  2018 share/callwaiting.wav
-rw-r--r--  1 alfredh  staff  16776 Oct 18  2018 share/error.wav
-rw-r--r--  1 alfredh  staff   6356 Oct 18  2018 share/message.wav
-rw-r--r--  1 alfredh  staff  16568 Oct 18  2018 share/notfound.wav
-rw-r--r--  1 alfredh  staff  12180 Oct 18  2018 share/ring.wav
-rw-r--r--  1 alfredh  staff  68084 Oct 18  2018 share/ringback.wav
```
