### ISSUE TITLE
No "incomming call" notification when using STUN

### ISSUE THREAD

**Issue by chaseadam** [alfredh/baresip#816]
If not using STUN, I get the following in the console and "the phone is ringing":

> sip:XXX: Incoming call from:  sip:XXX - (press 'a' to accept)

If I specify a STUN server, I do not get this notification, *but if I press `a`* then it will answer the call. The following is two calls which hung up before answer and then me pressing `a` while ringing.

> All 1 useragent registered successfully! (130 ms)
> sip:XXX: session closed: Connection reset by peer
> sip:XXX: session closed: Connection reset by peer
> sip:XXX: Answering incoming call
> answering call from sip:XXX with 200

I would expect to receive the incoming call notification in the log and "the phone is ringing" message.

Possible there is an issue with the STUN server (compatibility)?

I am using:
`;medianat=stun;stunserver=stun:stun.ekiga.net`
baresip v0.6.4 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al. compiled from source

**Comment by alfredh** [comment]
the STUN client in libre, that baresip is using, is compatible with RFC 5389:

https://tools.ietf.org/html/rfc5389

is stun.ekiga.net compatible with this ?

try to use a different STUN server e.g.:

```
stun.l.google.com:19302
```

**Comment by chaseadam** [comment]
Thank you for the referral, I can confirm the example stun server does not exhibit this issue, but the ekiga.net server does.

@alfredh Thank you so much for the high quality project and attention to the issues!
