### ISSUE TITLE
"H264 decode_slice_header error" in long time

### ISSUE THREAD

**Issue by dichkv** [alfredh/baresip#819]
Hi,

I'm not sure this is baresip's issue. But I need some help.
My PBX is Asterisk 16.5. Two Baresip 0.6.3 one callerid 208, other 209.
I make video call in local LAN work well. But when I setup one baresip behide NAT (router with DMZ), like this :

baresip208 <-------> asterisk <-------> Cisco Router with DMZ <-----> baresip209.
192.168.1.4                     192.168.1.14                    192.168.1.13        192.168.9.1               192.168.9.2
When I make a call from 209 to 208. Everything OK.
But, When I make a call from 208 to 209, 209 answer that call, 208's debug output like this 
_"[h264 @ 0xffff88103000] decode_slice_header error
[h264 @ 0xffff88103000] Frame num change from 14 to 4"_
 very much and very long time. After that, 208's display not smooth. 209 work well.

Can you help me any suggetion to fix this error? Why h264 slide header in this case while work well in local LAN?

Thanks you.

**Comment by premultiply** [comment]
Mmmh maybe one of your network devices does packet reordering in one path?

**Comment by dichkv** [comment]
Hi premultiply,

What about this log?

_main: long async blocking: 337>100 ms (h=0xffffab2a7728 arg=0xffff88ea3c60)
[h264 @ 0xffff88103000] non-existing PPS 0 referenceds) efps=20.6/0.0    
[h264 @ 0xffff88103000] decode_slice_header error
[h264 @ 0xffff88103000] non-existing PPS 0 referenced
[h264 @ 0xffff88103000] decode_slice_header error
[h264 @ 0xffff88103000] non-existing PPS 0 referenced
[h264 @ 0xffff88103000] decode_slice_header error
[h264 @ 0xffff88103000] non-existing PPS 0 referenced
[h264 @ 0xffff88103000] decode_slice_header error
[h264 @ 0xffff88103000] non-existing PPS 0 referenced
[h264 @ 0xffff88103000] decode_slice_header error
[h264 @ 0xffff88103000] non-existing PPS 0 referenced
[h264 @ 0xffff88103000] decode_slice_header error
[h264 @ 0xffff88103000] non-existing PPS 0 referenced
[h264 @ 0xffff88103000] decode_slice_header error
[h264 @ 0xffff88103000] non-existing PPS 0 referenced
[h264 @ 0xffff88103000] decode_slice_header error
[h264 @ 0xffff88103000] no frame!
avcodec: avcodec_send_packet error, packet=7062 bytes, ret=-1094995529 (Invalid data found when processing input)_

**Comment by alfredh** [comment]
most likely the first keyframe was dropped.

try to run baresip with -v and keep the call up until the next keyframe arrives
(the H.264 keyframes are sent at a regular interval around 10-60 seconds).

**Comment by dichkv** [comment]
Hi alfredh,

When I return to H264, I will post baresip log with -v parameter.
I'm using VP9, it's worked. I think quantity of H264 same VP9, not VP8. VP8 so bad. I need any advice for improve video quantity.
And, do you try DTLS_SRTP with Kamailio?

**Comment by alfredh** [comment]
can you please create a new ticket for the VP8 problem, remember to include
build information, logs, wireshark traces and also screen captures so that we
can see what "bad quality" means.

**Comment by dichkv** [comment]
Hi,

I will, wait me few hours.

**Comment by alfredh** [comment]
then please close this ticket, and create a new one for your next problem.

(one ticket per problem please.)
