### ISSUE TITLE
re make fails: Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by seeker12** [alfredh/baresip#82]
On macbook pro, OS X 10.11 El Capitan, Xcode 7.0.1 installed:
re-0.4.13 make fails with:
Undefined symbols for architecture x86_64:
  "__mod_close", referenced from:
      _mod_destructor in mod.o
  "__mod_open", referenced from:
      _mod_load in mod.o
  "__mod_sym", referenced from:
      _mod_load in mod.o
  "_lock_alloc", referenced from:
      _rtcp_sess_alloc in sess.o
  "_lock_read_get", referenced from:
      _rtcp_stats in sess.o
      _rtcp_debug in sess.o
  "_lock_rel", referenced from:
      _rtcp_sess_tx_rtp in sess.o
      _rtcp_stats in sess.o
      _rtcp_debug in sess.o
      _mk_sr in sess.o
  "_lock_write_get", referenced from:
      _rtcp_sess_tx_rtp in sess.o
      _mk_sr in sess.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libre.dylib] Error 1

make CC=clang produces same results. Am I doing it wrong?

**Comment by alfredh** [comment]
you can install baresip from Homebrew or Macports:

```
$ sudo port install baresip
```

or 

```
$ brew install baresip
```

if you want to build from Source you need to install Xcode Command-Line tools.

**Comment by seeker12** [comment]
Installed command-line tools and built as expected. Thank you.
