### ISSUE TITLE
VP9 configure in Baresip

### ISSUE THREAD

**Issue by dichkv** [alfredh/baresip#824]
Hi alfredh, Hi all,

Can you tell me how to config to using VP9 codec? VP8 work fine but video disable when i config video_codecs=vp9. My PBX is Asterisk 16.5.

Thanks you,

**Comment by yuexiajiayan** [comment]
make modules/vp9

**Comment by dichkv** [comment]
No, vp9.so allready to load and vidloop with vp9 worked.

**Comment by dichkv** [comment]
Hi,

I'm trying to use VP8 codec, but I see that quatity of H264 better than VP8. Can you tell me how to improve quantity of VP8? Config? Patch code?

Thanks you,

**Comment by yuexiajiayan** [comment]
you can see source code to find Config info

**Comment by dichkv** [comment]
It's seem asterisk not accept VP9 codec. VP9 and directly call work well. My plan switch from Asterisk to Kamailio.
