### ISSUE TITLE
MQTT: Raw string instead of JSON in command_resp

### ISSUE THREAD

**Issue by premultiply** [alfredh/baresip#826]
When sending a JSON-formated command to baresip via MQTT the response to /baresip/command_resp/ is not JSON-formated but raw string.
The same on ctrl_tcp works fine and the answer will be correctly JSON-formated as expected.
So the JSON-encoding step is missing for MQTT command response.

Response format and behaviour should be the same on MQTT or ctrl_tcp.

By the way: Events on MQTT are JSON-formated as with ctrl_tcp.

**Comment by alfredh** [comment]
can you please paste a copy here of the string you see:

1. the exact response string that you see.
2. how you would like to see it.

**Comment by premultiply** [comment]
Request is:
`{"command":"listcalls","token":""}`

1. Response on MQTT is
`--- Active calls (0) ---\n\n`
(Wrong, JSON encoding is missig)

2. Response on ctrl_tcp is
`{"response":true,"ok":true,"data":"\n--- Active calls (0) ---\n\n","token":""}`
(Correctly JSON encoded)

**Comment by alfredh** [comment]
I am not sure if we should change this, as it does not add any extra information.
The token is already included in the MQTT topic, so adding the token to the JSON
will be redundant information.

Also the whole command response has to be JSON encoded, parsing all characters
in the string to escape certain characters.

There are companies (Swedish Radio) using this code in production systems,
are they happy about such a protocol change ?

@Ola-Palm what do you think ?

**Comment by premultiply** [comment]
My points are:
1. If the Request is JSON the anwer should be JSON too.
2. My opinion is that JSON content should be the always the same between die different ways of transport for a clean und common API. The token attribute should be optional.
3. For MQTT we should discuss if there are more useful ways to also prefilter the events to special subtopics instead as this would help to reduce the amount of traffic to some clients. The token may also further be used for command subtopics but they should and can be included in JSON too.

**Comment by alfredh** [comment]
here is a patch if you want to test it:

```patch
diff --git a/modules/mqtt/subscribe.c b/modules/mqtt/subscribe.c
index 9de703a..95d4779 100644
--- a/modules/mqtt/subscribe.c
+++ b/modules/mqtt/subscribe.c
@@ -22,7 +22,7 @@ static void handle_command(struct mqtt *mqtt, const struct pl *msg)
 {
 	struct mbuf *resp = mbuf_alloc(1024);
 	struct re_printf pf = {print_handler, resp};
-	struct odict *od = NULL;
+	struct odict *od = NULL, *od_resp = NULL;
 	const struct odict_entry *oe_cmd, *oe_prm, *oe_tok;
 	char buf[256], resp_topic[256];
 	const char *aor, *callid;
@@ -86,6 +86,8 @@ static void handle_command(struct mqtt *mqtt, const struct pl *msg)
 		warning("mqtt: error processing command (%m)\n", err);
 	}
 
+	err |= mbuf_write_u8(resp, '\0');
+
 	/* NOTE: the command will now write the response
 	   to the resp mbuf, send it back to broker */
 
@@ -93,9 +95,23 @@ static void handle_command(struct mqtt *mqtt, const struct pl *msg)
 		    "/%s/command_resp/%s", mqtt->basetopic,
 		    oe_tok ? oe_tok->u.str : "nil");
 
+	err = odict_alloc(&od_resp, 8);
+	if (err)
+		goto out;
+
+	err  = odict_entry_add(od_resp, "response", ODICT_BOOL, true);
+	err |= odict_entry_add(od_resp, "ok", ODICT_BOOL, (bool)err==0);
+	err |= odict_entry_add(od_resp, "data", ODICT_STRING, resp->buf);
+	if (oe_tok) {
+		err |= odict_entry_add(od_resp, "token",
+				       ODICT_STRING, oe_tok->u.str);
+	}
+	if (err)
+		goto out;
+
 	err = mqtt_publish_message(mqtt, resp_topic,
-				   "%b",
-				   resp->buf, resp->end);
+				   "%H",
+				   json_encode_odict, od_resp);
 	if (err) {
 		warning("mqtt: failed to publish message (%m)\n", err);
 		goto out;
@@ -103,6 +119,7 @@ static void handle_command(struct mqtt *mqtt, const struct pl *msg)
 
  out:
 	mem_deref(resp);
+	mem_deref(od_resp);
 	mem_deref(od);
 }
 
```

**Comment by Ola-Palm** [comment]
Hello. I think that this suggestion doesn’t affect our running code that much. Well we have to rewrite the command response parser, but we are happy to do that. No issues. 
We do use tokens In topic, this is something that we have to look in to. Of cause we could  find ways around this as well. 
I could run baresip with this patch and see what that gives us.
I do agree that the command response benefits if it’s the same which ever transport you choose to use.

**Comment by alfredh** [comment]
thanks for the input :)

I will apply the patch.
