### ISSUE TITLE
ua_connect(baresipgua, &baresipcall, NULL, callurl, VIDMODE_ON) return 24 Call again

### ISSUE THREAD

**Issue by yuexiajiayan** [alfredh/baresip#828]
The first video call is OK ，Call again after hang up return 24 ,I'll be fine in a moment。
Is the resource not released? How to judge the situation。Sound doesn't make this happen.
testd in window qt

**Comment by GGGO** [comment]
Hi,
are you using a custom version of baresip, or baresip as library ?
You talk about window qt, do you mean qtcapture ?
Try to run baresip in debug mode to see more verbose.

**Comment by GGGO** [comment]
Please see [https://github.com/alfredh/baresip/wiki/Guidelines-for-reporting-Issues](url)

**Comment by alfredh** [comment]
please note that we only support stock baresip here, we dont support any custom
applications with closed source.

You are welcome to use the re-devel mailing list to ask for help.

**Comment by yuexiajiayan** [comment]
> Hi,
> are you using a custom version of baresip, or baresip as library ?
> You talk about window qt, do you mean qtcapture ?
> Try to run baresip in debug mode to see more verbose.

qt can't show print log  , Do you have a way

i use it  as a library
