### ISSUE TITLE
DTLS_SRTP in directly call

### ISSUE THREAD

**Issue by dichkv** [alfredh/baresip#829]
Hi @alfredh, hi all

I'm trying DTLS_SRTP in directly call between two baresip 0.6.3, with account config:
`<sip:202@192.168.1.51;transport=tcp>;auth_pass=1234;video_codecs=vp9;mediaenc=dtls_srtp;regint=60`
it's seem dtls_srtp not run, because I checked that `verify_fingerprint` function in `dtls_srtp.c` never run.
DTLS_SRTP is p2p protocol, i don't know why directly call not work? Any wrong in my config?

But, If I register this two baresip to Kamailio + rtpengine, `verify_fingerprint` function run but I get some error: 
`dtls_srtp: unsupported fingerprint hash 'sha-1'
stream: mediaenc update: Protocol error`
and the call hangup. 
Rtpengine alway send to baresip with `a=fingerprint:sha-1`

Can you tell me how to using dtls_srtp on baresip? with which SIP proxy?

BR,

**Comment by GGGO** [comment]
Hi,

I just tested between two baresip 0.6.4 and it works.
I got `dtls_srtp: verified SHA-256 fingerprint OK`

Check your SIP trace to be sure.

**Comment by alfredh** [comment]
I am also using DTLS-SRTP locally here between 2 baresip's and it works fine.

Please upgrade to latest version and try again. If it still does not work, please
include baresip logs, config, accounts and Wireshark trace.

NOTE: SHA-1 is not supported by baresip anymore. Don't use SHA-1 it
is not secure, it has known collisions:
https://en.wikipedia.org/wiki/SHA-1

**Comment by alfredh** [comment]
closing, please re-open if you can provide logs.
