### ISSUE TITLE
local IPv6 address not detected automatically

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#831]
baresip Android app user reported that baresip is not automatically detecting global IPv6 address of the device although it has two of them:

https://github.com/juha-h/baresip-studio/issues/56#issuecomment-546453814

https://github.com/juha-h/baresip-studio/issues/56#issuecomment-546464204

The only way he can get registration and calls to work over IPv6 is to manually set bind_address to a global IPv6 address of the device. Config has 'prefer_ipv6=yes'.

What could cause this issue?  Anything to do about it?

**Comment by juha-h** [comment]
Maybe the only choice is to override baresip/re network auto-configuration altogether if it has not been designed to work in Android environment?

Something like this:
- get prefer_ipv6 from config
- get ifname of default network and ip addresses of DNS servers dynamically from Android
- with that info, create new network object using net_alloc() baresip API call
- using that object, call net_force_change() baresip API function

Would that work?

**Comment by juha-h** [comment]
In baresip API, there is function `net_use_nameserver` that can be used to dynamically update DNS servers, but I have not found a corresponding function `net_use_interface`. 

Would this kind of function do it provided that `ifname` is not longer that 63 chars?
```
void net_use_interface(char *ifname)
{
    struct config *conf = conf_config();
    strcpy(conf->net.ifname, ifname);
    net_force_change(baresip_network());
}
```
Variable name `ifname` is a bit misleading, since if I have understood correctly, it can contain either interface name is its IP address.

**Comment by juha-h** [comment]
In order to facilitate IPv6 address use without need to give it in net_interface config variable, I obtained a public IP address from Android OS and then tried to set the address like this:
```
    struct config_net *nc = net_config(baresip_network());
    LOGD("setting address '%s'\n", native_addr);
    strcpy(nc->ifname, native_addr);
    nc->prefer_ipv6 = strchr(native_addr, ':') != NULL;
    net_force_change(baresip_network());
```
`net_config()` is a new API function that just returns `&net->cfg`.

I tested it with an IPv4 address, since I don't have IPv6 network available. It produced to log:
```
10-27 18:16:22.524 16681 16681 D Baresip Lib: setting address '100.68.58.54'
10-27 18:16:22.524 16681 16717 D Baresip Lib: IP-address changed: 192.168.43.174
```
I got the same result when I tried with the function in the previous comment.

The device has these addresses:
```
10-27 18:15:43.711 16681 16716 D Baresip Lib: net interfaces:
10-27 18:15:43.711 16681 16716 D Baresip Lib:          lo:  127.0.0.1
10-27 18:15:43.711 16681 16716 D Baresip Lib:      ccmni0:  100.68.58.54
10-27 18:15:43.711 16681 16716 D Baresip Lib:         ap0:  192.168.43.174
```
and it successfully uses both of the non-lo interface addresses, if I give the address as net_interface config var value and restart baresip.

This is getting desperate. How can the net_interface address be changed on the fly?

**Comment by juha-h** [comment]
I wrote a new API function `net_use_interface` (below) and with that I'm able to change bind address on the fly.   Would it make sense to create a pull request?
```
/**
 * Bind to specific interface or IP address and preferred address family
 *
 * @param net         Network instance
 * @param ifname      Interface name or IP address
 * @param prefer_ipv6 Prefer IPv6 address family
 *
 * @return 0 if success, otherwise errorcode
 */

int net_use_interface(struct network *net, const char *ifname,
		      bool prefer_ipv6)
{
	struct sa temp_sa;
	bool got_it = false;
	char buf4[128] = "", buf6[128] = "";
	int err;
	
	info("Binding to interface or IP address '%s'\n", ifname);
	
	/* check for valid IP-address */
	if (0 == sa_set_str(&temp_sa, ifname, 0)) {
		
		switch (sa_af(&temp_sa)) {
			
		case AF_INET:
			net->laddr = temp_sa;
			break;

#ifdef HAVE_INET6
		case AF_INET6:
			net->laddr6 = temp_sa;
			break;
#endif

		default:
			return EAFNOSUPPORT;
		}

		goto print_network_data;
	}
	
	err = net_if_getaddr(ifname, AF_INET, &net->laddr);
	if (err) {
		info("net: %s: could not get IPv4 address (%m)\n",
		     ifname, err);
	}
	else
		got_it = true;

#ifdef HAVE_INET6
	err = net_if_getaddr(ifname, AF_INET6, &net->laddr6);
	if (err) {
		info("net: %s: could not get IPv6 address (%m)\n",
		     ifname, err);
	}
	else
		got_it = true;
#endif
	if (!got_it) {
		warning("net: %s: could not get network address\n",
			ifname);
		return EADDRNOTAVAIL;
	}

print_network_data:

	if (sa_isset(&net->laddr, SA_ADDR)) {
		re_snprintf(buf4, sizeof(buf4), " IPv4=%H",
			    print_addr, &net->laddr);
	}
#ifdef HAVE_INET6
	if (sa_isset(&net->laddr6, SA_ADDR)) {
		re_snprintf(buf6, sizeof(buf6), " IPv6=%H",
			    print_addr, &net->laddr6);
	}
#endif

	info("Local network address: %s %s\n", buf4, buf6);

	net->af = prefer_ipv6 ? AF_INET6 : AF_INET;

	if (net->ch) {
		net->ch(net->arg);
	}

	return 0;
}
```

**Comment by juha-h** [comment]
Related to #834, it might be better to set net->af to AF_INET6 only if net->laddr6 was set.  Also, if net->laddr or net->laddr6 was not set, should it be set to null?

**Comment by juha-h** [comment]
Below is new version of  net_use_interface API function that initializes laddr and ladd6 and (due to net_prefer_ipv6 bug or feature) does not set af to AF_INET6 if IPv6 address is not set.
```
int net_use_interface(struct network *net, const char *ifname,
		      bool prefer_ipv6)
{
	struct sa temp_sa;
	char buf4[128] = "", buf6[128] = "";
	int err;
	
	info("Binding to interface or IP address '%s'\n", ifname);

	sa_init(&net->laddr, AF_INET);
	sa_init(&net->laddr6, AF_INET6);
	
	/* check for valid IP-address */
	if (0 == sa_set_str(&temp_sa, ifname, 0)) {
		
		switch (sa_af(&temp_sa)) {
			
		case AF_INET:
			net->laddr = temp_sa;
			break;

#ifdef HAVE_INET6
		case AF_INET6:
			net->laddr6 = temp_sa;
			break;
#endif

		default:
			return EAFNOSUPPORT;
		}

		goto print_network_data;
	}
	
	err = net_if_getaddr(ifname, AF_INET, &net->laddr);
	if (err) {
		info("net: %s: could not get IPv4 address (%m)\n",
		     ifname, err);
	}

#ifdef HAVE_INET6
	err = net_if_getaddr(ifname, AF_INET6, &net->laddr6);
	if (err) {
		info("net: %s: could not get IPv6 address (%m)\n",
		     ifname, err);
	}

#endif
	if (!sa_isset(&net->laddr, SA_ADDR) &&
	    !sa_isset(&net->laddr6, SA_ADDR)) {
		warning("net: %s: could not get network address\n",
			ifname);
		return EADDRNOTAVAIL;
	}

print_network_data:

	if (sa_isset(&net->laddr, SA_ADDR)) {
		re_snprintf(buf4, sizeof(buf4), " IPv4=%H",
			    print_addr, &net->laddr);
	}
#ifdef HAVE_INET6
	if (sa_isset(&net->laddr6, SA_ADDR)) {
		re_snprintf(buf6, sizeof(buf6), " IPv6=%H",
			    print_addr, &net->laddr6);
	}
#endif

	info("Local network address: %s %s\n", buf4, buf6);

	net->af = prefer_ipv6 && sa_isset(&net->laddr6, SA_ADDR) ?
		AF_INET6 : AF_INET;

	if (net->ch) {
		net->ch(net->arg);
	}

	return 0;
}
```

**Comment by alfredh** [comment]
baresip's net.c is calling this:

````
		(void)net_default_source_addr_get(AF_INET6, &net->laddr6);
```

and here is the code (in libre):

```c
int net_default_source_addr_get(int af, struct sa *ip)
{
#if defined(WIN32)
	return net_hostaddr(af, ip);
#else
	char ifname[64] = "";

#ifdef HAVE_ROUTE_LIST
	/* Get interface with default route */
	(void)net_rt_default_get(af, ifname, sizeof(ifname));
#endif

	/* First try with default interface */
	if (0 == net_if_getaddr(ifname, af, ip))
		return 0;

	/* Then try first real IP */
	if (0 == net_if_getaddr(NULL, af, ip))
		return 0;

	return net_if_getaddr4(ifname, af, ip);
#endif
}
```

1. Does your build of libre have HAVE_ROUTE_LIST enabled ?

here is net_if_getaddr:

```c
/**
 * Get IP address for a given network interface
 *
 * @param ifname  Network interface name (optional)
 * @param af      Address Family
 * @param ip      Returned IP address
 *
 * @return 0 if success, otherwise errorcode
 *
 * @deprecated Works for IPv4 only
 */
int net_if_getaddr(const char *ifname, int af, struct sa *ip)
{
	struct ifentry ife;
	int err;

	if (!ip)
		return EINVAL;

	ife.af     = af;
	ife.ifname = (char *)ifname;
	ife.ip     = ip;
	ife.sz     = 0;
	ife.found  = false;

#ifdef HAVE_GETIFADDRS
	err = net_getifaddrs(if_getaddr_handler, &ife);
#else
	err = net_if_list(if_getaddr_handler, &ife);
#endif

	return ife.found ? err : ENODEV;
}
```

Please notice the comment: "Works for IPv4 only"

2. Does your build of libre have HAVE_GETIFADDRS enabled ?

The function `net_getifaddrs()` should support both v4+v6 but
the function `net_if_list` supports only v4.

3. my advice is to add print debug code to libre, re-compile
  and try to figure out which path it takes and where it terminated.

4. also try to use `net_if_debug` to see the real status of the networking side.

Here is an example from a Linux host, default build of libre
and both IPv4 and IPv6 address:

```
/netstat
--- Network debug ---
 Preferred AF:  AF_INET
 Local IPv4:  ens3|172.31.1.100
 Local IPv6:  ens3|2a01:4f8:c0c:34f9::2
 Domain: 
net interfaces:
         lo:  127.0.0.1
       ens3:  172.31.1.100
         lo:  ::1
       ens3:  2a01:4f8:c0c:34f9::2
       ens3:  fe80::5054:a2ff:fe02:1840
net routes:
 Destination                                 Next Hop                                 Iface           Type
 0.0.0.0/0                                   172.31.1.1                               ens3            
 172.31.1.0/24                               ?                                        ens3            
 2a01:4f8:c0c:34f9::/64                      ?                                        ens3            
 fe80::/64                                   ?                                        ens3             LINKLOCAL
 DNS Servers from System: (3)
   0: 213.133.100.100:53
   1: 213.133.98.98:53
   2: 213.133.99.99:53
```

As you can see, the "Local IPv6" also appears in the list of net interfaces.

**Comment by alfredh** [comment]
in this build, HAVE_GETIFADDRS is disabled:

https://github.com/alfredh/baresip-android/blob/master/Makefile#L99

try to enable this flag and see if it works.
you might need to provide a copy of ifaddrs.h if it is missing from Android NDK.

**Comment by juha-h** [comment]
Thanks for the tips.

It turned out that Android has getifaddrs starting from API level 24, but source of ifaddrs-android.h plus two other .h files could be included in apps targeting earlier APIs.  The include alternative sounds too complicated to me.  So the practical options are (1) drop IPv6 support from my Android app or (2) increase its minimum API level from 21 to 24.

On the other hand, my app is able to learn all IP addresses (IPv4 and IPv6) the active interface of the Android device has.  So how about creating a new API function that can be used to set net->laddr and net->laddr6?

**Comment by alfredh** [comment]
on a high level I think the policy should be something like:

1. libre/baresip provides network addresses and dns nameservers for
  common platforms.

2. it is possible to override via baresip.h API for certain platforms that
wants to do that (e.g. Android).

it would be great if you can add such a function to set the IP-address.

```c
struct network {
	struct config_net cfg;
	struct sa laddr;
#ifdef HAVE_INET6
	struct sa laddr6;
#endif
```

the function can be as simple as:

```c
void net_set_address(struct network *net, const struct sa *ip)
{
    // if IPv4:
    net->laddr = *ip;

    // if IPv6:
    net->laddr6 = *ip;
}
```

and the function can be called directly after `net_alloc`.

**Comment by juha-h** [comment]
OK, I could try that.  How about  net->af?

**Comment by alfredh** [comment]
if you need to be able to change this on the fly, you can add an extra setter function for that.

this is orthogonal to setting the IP-address itself.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> if you need to be able to change this on the fly, you can add an extra
> setter function for that.
> 
> this is orthogonal to setting the IP-address itself.

I wrote the function like this:
```

void net_set_address(struct network *net, const struct sa *ip,
		     bool preferred)
{
	switch (sa_af(ip)) {
			
	case AF_INET:
		sa_cpy(&net->laddr, ip);
		if (preferred)
			net->af = AF_INET;
		return;

#ifdef HAVE_INET6
	case AF_INET6:
		sa_cpy(&net->laddr6, ip);
		if (preferred)
			net->af = AF_INET6;
		return;
#endif
	}
}
```
Is is OK or is a separate function needed?

**Comment by alfredh** [comment]
great, this looks good to me.

you can send me a PR or just push the code to master.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> great, this looks good to me.
> 
> you can send me a PR or just push the code to master.

Perhaps still better with separate setter:
```
int  net_af(const struct network *net);
int  net_set_af(const struct network *net, int af);
```
Will work on it.

**Comment by alfredh** [comment]
great, thanks for the code.

**Comment by juha-h** [comment]
Right after baresip_init(), I call net_set_addr() with IPv6 address provided that the active Android
network has an IPv6 address, and then call net_set_af() with AF_INET6 if the user wants to prefer IPv6. I do the same if a new network becomes available after network loss.

I have not been able to test any of that yet, because my mobile operator does not support IPv6 and my Android device is not able to get IPv6 address from my WiFi router using DHCP.

Once some testing gets done, I'll report what happened.
