### ISSUE TITLE
alsa: could not open ausrc device 'default' (No such file or directory)

### ISSUE THREAD

**Issue by webstean** [alfredh/baresip#832]
Could I have some help troubleshooting an alsa error?

I am able to play a WAV file with /play command

Dailing anywhere, I get the error:
alsa: could not open ausrc device 'default' (No such file or directory)

module: loading app contact.so
Populated 5 contacts
module: loading app debug_cmd.so
module: loading app dtmfio.so
module: loading app menu.so
Populated 2 audio codecs
Populated 0 audio filters
Populated 0 video codecs
Populated 0 video filters
baresip is ready.
/about
.------------------------------------------------------------.
|                      baresip 0.6.4                         |
|                                                            |
| Baresip is a portable and modular SIP User-Agent           |
| with audio and video support                               |
|                                                            |
| License:   BSD                                             |
| Homepage:  https://github.com/alfredh/baresip              |
|                                                            |
'------------------------------------------------------------'
/sysinfo

--- System info: ---
 Machine:  arm6/linux
 Version:  0.6.4 (libre v0.6.1)
 Build:    32-bit little endian
 Kernel:   Linux pabx1 4.19.80-v7+ #1274 SMP Mon Oct 21 16:23:10 BST 2019 armv7l
 Uptime:   
 Started:  Sun Oct 27 01:10:46 2019
 Compiler: 6.3.0 20170516
999@192.168.0.11: {0/UDP/v4} 200 OK () [9 bindings]
All 1 useragent registered successfully! (171 ms)
/play busy.wav
playing audio file "busy.wav" ..
alsa: reset: srate=8000, ch=1, num_frames=320, pcmfmt=S16_LE
alsa: playback started (default)
play: player complete.
alsa: stopping playback thread (default)
>                              000
call: alloc with params laddr=192.168.0.11, af=AF_INET, use_rtp=1
call: use_video=0
call: connecting to 'sip:000@192.168.0.11'..
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 180 Ringing (/)
alsa: reset: srate=8000, ch=1, num_frames=320, pcmfmt=S16_LE
alsa: playback started (default)
stream: incoming rtp for 'audio' established, receiving from 192.168.0.11:7034
call: got SDP answer (257 bytes)
call: update media
stream: update 'audio'
stream: audio: starting RTCP with remote 192.168.0.11:7035
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: start
alsa: reset: srate=8000, ch=1, num_frames=160, pcmfmt=S16_LE
alsa: playback started (default)
audio: player started with sample format S16LE
audio: Set audio encoder: PCMU 8000Hz 1ch
audio: start
alsa: could not open ausrc device 'default' (No such file or directory)
audio: start_source failed (alsa.default): Unknown error -2
sip:000@192.168.0.11: session closed: Unknown error -2
alsa: stopping playback thread (default)
alsa: stopping playback thread (default)
audio: destroyed (started=0)

**Comment by dichkv** [comment]
Do you hear the ring tone when your phone in ringing state? If yes, you can try my solution in

**Comment by webstean** [comment]
Thanks - could you please elaborate on your solution:
Create dmix alsa device and share it for both alert and play, it's worked.

**Comment by dichkv** [comment]
I mean, I create dmix alsa device for multi process can be work on same alsa device. You have to google for dmix alsa plugin and how to using it. This is my asound.conf 
`pcm.dmix_stream
{
	type dmix
	ipc_key 321456 
	ipc_key_add_uid true
	slave.pcm "hw:0,0"
}

pcm.mix_stream
{
	type plug
	slave.pcm dmix_stream
}`
and my audio baresip config
`audio_path		/usr/share/baresip
audio_player		alsa,mix_stream
audio_source		alsa,plughw:0,0
audio_alert		alsa,mix_stream
ausrc_srate		48000
auplay_srate		48000`

**Comment by webstean** [comment]
OK - thanks I get it now
