### ISSUE TITLE
baresip chooses wrong IP address for RTP audio

### ISSUE THREAD

**Issue by afcady** [alfredh/baresip#833]
Using the `A` keybinding I was able to determine a reason why audio was only
moving in one direction over the network.

On my local side, where no audio comes in, this is visible:

```
--- Audio stream ---
 tx:   PCMU 8000Hz/1ch wish_sz=640 cur_sz=0 filling=0 ptime=20ms
 rx:   PCMU 8000Hz/1ch wish_sz=320 cur_sz=0 filling=1 ptime=20ms pt=0
 audio tx pipeline:        alsa ---> vumeter ---> sndfile ---> PCMU
 audio rx pipeline:        alsa <--- vumeter <--- sndfile <--- PCMU
 audio dir=sendrecv pt_enc=0
 local: 0.0.0.0:10610, remote: [2601:...]:19798/[2601:...]:19799
RTP debug:
 Encode: seq=31081 ssrc=0x84ca6e3b
----- RTCP Session: -----
  cname=sip:d@[2601:...] SSRC=0x84ca6e3b/2227859003 rx=8000Hz
  TX: packets=340, octets=54400
--- jitter buffer debug---
 running=0 min=5 cur=0 max=10 [frames]
 seq_put=0
[0:00:14] audio=64000/0 video=0/0 (bit/s) efps=0/0          [                ]
```

(Notice the `audio=64000/0`.)

On the remote side, which successfully plays audio coming from the local side's
mic, this is visible:

```
--- Audio stream ---
 tx:   PCMU 8000Hz/1ch wish_sz=640 cur_sz=0 filling=0 ptime=20ms
 rx:   PCMU 8000Hz/1ch wish_sz=320 cur_sz=2240 filling=0 ptime=20ms pt=0
 audio tx pipeline:        alsa ---> vumeter ---> PCMU
 audio rx pipeline:        alsa <--- vumeter <--- PCMU
 audio dir=sendrecv pt_enc=0
 local: 0.0.0.0:19798, remote: [fd53:...]:10610/[fd53:...]:10611
RTP debug:
 Encode: seq=6905 ssrc=0xc5dd3de6
----- RTCP Session: -----
  cname=sip:ella@[2601:...] SSRC=0xc5dd3de6/3319610854 rx=8000Hz
  member 0x84ca6e3b: lost=0 Jitter=0.0ms RTT=0.0ms
                 IP=[2601:...]:10610 psent=265 rcvd=412
  TX: packets=413, octets=66080
--- jitter buffer debug---
 running=1 min=5 cur=5 max=10 [frames]
 seq_put=31152
[0:00:10] audio=64000/63573 (bit/s)                         [=               ]  [                ]
```

(Notice the `audio=64000/63573`.)

The problem line is this, on the side that cannot send audio:

    local: 0.0.0.0:16306, remote: [fd53:...]:19671

This latter `fd53:...` address is a private LAN address. (`fd::/8` on IPv6 is
equivalent to 10./8 on IPv4.) The machine that is reporting this line is not
even on any such IPv6 network, but the other machine is. The address must be
being sent from the local machine to the remote machine, which is then using the
wrong address to send sound my way. Thus I receive no audio over the network.

The machine that I am using has both this private address (used for an IPsec
VPN) and a globally routable IPv6 address. The remote machine has only the
global IPv4 address.

Removing the VPN address from the network interface in the local side fixes the
behavior shown. (I still have nothing audible but the audio signal shows up in
the vu-meter and even in the `pavucontrol` graphical output for one of the ALSA
devices. Seems it's something to do with ALSA.)

I have an IP address specified in `sip_listen` which uses the global IP. The
only enabled account name in `.baresip/accounts` is also using that IP as its
listening address. (At first I had two accounts, one with the VPN address, since
I want to use baresip over the VPN too, but I removed it for testing.)

I was thinking maybe baresip is trying to do some unnecessary NAT traversal
thing here. Maybe it is *intended* to show the local behind-NAT IP address. (When
I do not use `-6`, baresip does show behind-NAT IPv4 addresses.)

I think that if `sip_listen` is specified baresip should always or by default
use that same IP address for these other ports as well. Maybe have a separate
`rtp_address` setting (there is already `rtp_ports`).

**Comment by GGGO** [comment]
Hi,

sip_listen is only for sip signalling, not for RTP.

You can try this:
1- play with `net_interface` in the config file
or
2- enable ICE with `medianat=ice`

**Comment by afcady** [comment]
I see, `net_interface` lets you specify an IP address (since #420 / 507cf074), which does then become the RTP address.  Seems this is also available recently on the command line as `-n <net_if>`.  Though these parameters are now misnamed.

**Comment by alfredh** [comment]
can you please paste the output of the `/netstat` command ?

baresip is trying to fetch the best local IP address, but sometimes it is not able
to figure out the "best" one. in this case you need to specify the IP address with -n:

```
	-n <net_if>      Specify network interface
```

```
$ baresip -n 2001:aa:bb:cc:dd
```

**Comment by afcady** [comment]
Sure.  Please note: it does work with `-n` or `net_interface`.  I removed those options to generate this.

```
--- Network debug ---
 Preferred AF:  AF_INET6
 Local IPv4:  wlan0|192.168.0.8
 Local IPv6:  lo|fd53:...
 Domain: 
net interfaces:
         lo:  127.0.0.1
      wlan0:  192.168.0.8
         lo:  fd53:...
         lo:  ::1
      wlan0:  2601:...
      wlan0:  2601:...
      wlan0:  fe80::...
net routes:
 Destination                                 Next Hop                                 Iface           Type
 0.0.0.0/0                                   192.168.0.1                              wlan0           
 192.168.0.0/24                              ?                                        wlan0           
 ::1/128                                     ?                                        lo              
 2601:.../64                                 ?                                        wlan0           
 fd00::/8                                    ?                                        lo              
 fe80::/64                                   ?                                        wlan0            LINKLOCAL
 DNS Servers from Config: (1)
   0: 127.0.0.1:53
```

**Comment by alfredh** [comment]
```
net interfaces:
         lo:  127.0.0.1
      wlan0:  192.168.0.8
         lo:  fd53:...       <---------- chosen
         lo:  ::1
      wlan0:  2601:...
      wlan0:  2601:...
      wlan0:  fe80::...
```

the code for picking the "default" IP address is very basic, and
in your case it picks a non-ideal one. this is how it is at the moment,
but the default address can be specified explicitly with the -n option.

on your machine, is it possible to disable that private LAN IPv6 address ?

**Comment by afcady** [comment]
Yeah, I was disabling the address originally, since I didn't know about `-n`/`net_interface`.

**Comment by alfredh** [comment]
at the moment this is how the local address detection works, and it is very
unlikely to change any time soon.

your best options to get this working is:

1. disable the unwanted address
2. specify address using -n or net_interface


Alfred

**Comment by afcady** [comment]
I see that, however, there ought to be an open bug for the whole issue of the IP address needing to be specified like this.

I was thinking that with the `net_set_address()` function, you could call it on an incoming SIP connection with the address of the remote side; and also when you make an outgoing SIP connection you could check the default route to the destination IP (you can do this on Linux at least) and again call that function.

Of course the real problem is that there is a global address at all; it should be local to each connection.  But setting the global address upon each connection is a step in that direction.
