### ISSUE TITLE
ZRTP: when zrtp in key-agreement state, none-encrypt voice is still transfered.

### ISSUE THREAD

**Issue by dichkv** [alfredh/baresip#835]
Hi,

I'm trying to using zrtp for encrypt audio and video data. But when zrtp in key-agreement state, none-encrypt voice is still transfer. I thing it's issue, it's should be no audio transfer in key-agreement state.
Can you point me how to drop audio in this state? Because I don't want to call to none-zrtp phone.

Thanks,

**Comment by GGGO** [comment]
Hi,

maybe `.wait_secure = true` is missing in:
```
static struct menc menc_zrtp = {
	.id        = "zrtp",
	.sdp_proto = "RTP/AVP",
	.sessh     = session_alloc,
	.mediah    = media_alloc
};

```

**Comment by dichkv** [comment]
Hi,
My stupid solution : 

I add `if (st->zrtp_stream->state != ZRTP_STATE_SECURE) return true;` in `udp_helper_send` function in zrtp.so and add `on_zrtp_protocol_event` to check secure event, and drop the call when recieve NO_ZRTP event.

**Comment by GGGO** [comment]
Did you try with `.wait_secure = true` ?

**Comment by juha-h** [comment]
GG writes:

> Did you try with `.wait_secure = true` ?

I just tried and no audio was sent out from baresip.

**Comment by dichkv** [comment]
Thanks you,

I will try version 0.6.4 and add `.wait_secure` to menc struct. Version 0.6.3 not support it.

**Comment by alfredh** [comment]
ZRTP is best effort encryption, and involves no signaling. The protocol is
end-to-end and multiplexed on the audio path.

This means that when you make a call to a remote party, you dont know if the
remote party supports ZRTP or not. So the audio is established and the
ZRTP exchange is started at the same time.

if both sides support ZRTP and the exchange is successful,
the encryption is enabled and both sides get a random
shared Short Authentication String (SAS) that you can verify with
the peer using out-of-bands method, for example reading out the SAS
to the remote peer.

I believe the current implementation is doing the right thing.
