### ISSUE TITLE
hostnames in /etc/hosts don't work

### ISSUE THREAD

**Issue by afcady** [alfredh/baresip#841]
Apparently if no DNS server is specified then `baresip`  actually parses `/etc/resolv.conf` (through the `re` library) to get the name of a DNS server.  

Baresip should use `getaddrinfo(3)` to look up names when no nameserver is specified.  That way the system's libc determines how hostnames are resolved, enabling the user to specify names with `/etc/hosts` or other db type specified in `/etc/nsswitch.conf`.

The actual code that does lookups appears to reside in `re` in the file `src/dns/client.c` in the function `query()`.  The `re` library provides functions that `baresip` uses to generate a `struct dnsc` representing the DNS client, but that value is only ever passed back to `re` to be used in various functions that call `query()` (such as `sip_alloc()`).

**Comment by alfredh** [comment]
we use the DNS resolver from libre, which is asynchronous.

the whole system is running in an async I/O run-loop, using e.g. epoll or select.
we cannot block the system by calling getaddrinfo and wait for the DNS response.

**Comment by GGGO** [comment]
In the past I encountered the same problem. Now I use outbound to force a destination. Of course outbound need to be a resolved IP. 
I use this a lot when testing on a computer without dns server.

**Comment by alfredh** [comment]
baresip and multiple protocols in libre is using the libre DNS client.

re-writing the DNS client to use getaddrinfo_a is not an option.

closing this issue as "Not going to fix".

**Comment by afcady** [comment]
I reported this in `re` here: https://github.com/creytiv/re/issues/232
