### ISSUE TITLE
Windows, after running for two minutes, the process exits

### ISSUE THREAD

**Issue by 75535552** [alfredh/baresip#842]
baresip in windwos10 after running for two minutes, the process exits.

remote baresip in pi3b+。the sound and video are normal。after running for two minutes, windows baresip process exits。

How do I collect info。or use breakpad?  find a better way.  thanks.

**Comment by GGGO** [comment]
Hi,

Please see [https://github.com/alfredh/baresip/wiki/Guidelines-for-reporting-Issues](https://github.com/alfredh/baresip/wiki/Guidelines-for-reporting-Issues)

**Comment by alfredh** [comment]
please provide logs and/or backtrace.

**Comment by alfredh** [comment]
@75535552 if you want any help here, please provide the required info.
I am going to close this for now, please re-open if you can provide the info.

**Comment by 75535552** [comment]
thank you very much 
run win10 
//log
PS D:\baresip\bin> .\baresip-win32.exe
baresip v0.6.4 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.
Local network address:  IPv4={36374788-1E6F-4FDE-9496-EB66083BCBE0}|10.8.0.3
aucodec: opus/48000/2
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
winwave: output devices: 2, input devices: 1
ausrc: winwave
auplay: winwave
vidcodec: H264
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidcodec: H265
avcodec: using H.264 encoder 'libx264' -- libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.264 decoder 'h264' -- H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.265 encoder 'libx265' -- libx265 H.265 / HEVC
avcodec: using H.265 decoder 'hevc' -- HEVC (High Efficiency Video Coding)
vidsrc: dshow
vidisp: sdl
medianat: stun
medianat: turn
medianat: ice
medianat: ice-lite
Populated 1 account
Populated 3 contacts
Populated 3 audio codecs
Populated 0 audio filters
Populated 5 video codecs
Populated 0 video filters
baresip is ready.
unhandeled request from 10.8.0.3:5060: REGISTER sip:10.8.0.3
[31mreg: sip:0755000003@10.8.0.3: 501 Not Implemented (baresip v0.6.4 (?/win32))
>                                 long async blocking: 1000>100 ms (h=0x9934c0 arg=0x7d8d30)
>          sip:0755000002@10.8.0.2unhandeled request from 10.8.0.3:5060: REGISTER sip:10.8.0.3
[31mreg: sip:0755000003@10.8.0.3: 501 Not Implemented (baresip v0.6.4 (?/win32))
[;m
call: connecting to 'sip:0755000002@10.8.0.2'..
call: SIP Progress: 180 Ringing (/)
[31mplay: /usr/share/baresip/ringback.wav: No such file or directory
stream: incoming rtp for 'audio' established, receiving from 10.8.0.2:31822
audio: Set audio decoder: opus 48000Hz 2ch
audio: player started with sample format S16LE
long async blocking: 246>100 ms (h=0x97b730 arg=0x7f7c60)
stream: update 'audio'
stream: update 'video'
audio: Set audio encoder: opus 48000Hz 2ch
audio: source started with sample format S16LE
audio tx pipeline:     winwave ---> opus
audio rx pipeline:     winwave <--- opus
Set video encoder: H264 packetization-mode=0 (2000000 bit/s, 25.00 fps)
avcodec: h264 encoder activated
dshow: got device '' id=0
Set video decoder: H264 packetization-mode=0
avcodec: h264 decoder activated
avcodec: decode: hardware accel disabled
0755000003@10.8.0.3: Call established: sip:0755000002@10.8.0.2
long async blocking: 989>100 ms (h=0x97b730 arg=0x7f8890)
stream: incoming rtp for 'video' established, receiving from 10.8.0.2:5380
sdl: created renderer 'direct3d'
long async blocking: 168>100 ms (h=0x97b730 arg=0x7f8160)
[libx264 @ 02aa8f80] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 02aa8f80] profile Constrained Baseline, level 3.1, 4:2:0, 8-bit
long async blocking: 1401>100 ms (h=0x9407e0 arg=0x8361f8)
long async blocking: 560>100 ms (h=0x9407e0 arg=0x8361f8)fps=9.8/11.5
[h264 @ 02a89d80] concealing 126 DC, 126 AC, 126 MV errors in P frame
[h264 @ 02a89d80] concealing 193 DC, 193 AC, 193 MV errors in P frame
long async blocking: 431>100 ms (h=0x9407e0 arg=0x8361f8)fps=9.8/15.1
[h264 @ 02a89d80] concealing 147 DC, 147 AC, 147 MV errors in P frame1
[h264 @ 02a89d80] Frame num change from 15 to 0
[h264 @ 02a89d80] decode_slice_header error
[h264 @ 02a89d80] Frame num change from 15 to 0
[h264 @ 02a89d80] decode_slice_header error
[h264 @ 02a89d80] Frame num change from 15 to 0
[h264 @ 02a89d80] decode_slice_header error
[h264 @ 02a89d80] Frame num change from 15 to 1
[h264 @ 02a89d80] decode_slice_header error
[h264 @ 02a89d80] Frame num change from 15 to 1
[h264 @ 02a89d80] decode_slice_header error
[h264 @ 02a89d80] Frame num change from 15 to 1
[h264 @ 02a89d80] decode_slice_header error
[h264 @ 02a89d80] Frame num change from 15 to 1
[h264 @ 02a89d80] decode_slice_header error
[h264 @ 02a89d80] Frame num change from 15 to 1
[h264 @ 02a89d80] decode_slice_header error
[h264 @ 02a89d80] Frame num change from 15 to 1
[h264 @ 02a89d80] decode_slice_header error
[h264 @ 02a89d80] Frame num change from 15 to 1
[h264 @ 02a89d80] decode_slice_header error
[h264 @ 02a89d80] concealing 337 DC, 337 AC, 337 MV errors in P frame
[h264 @ 02a89d80] concealing 76 DC, 76 AC, 76 MV errors in P frame12.1
[h264 @ 02a89d80] concealing 7 DC, 7 AC, 7 MV errors in I frame.0/12.1
[h264 @ 02a89d80] P sub_mb_type 10 out of range at 2 3) efps=10.0/12.1
[h264 @ 02a89d80] error while decoding MB 2 3
[h264 @ 02a89d80] concealing 61 DC, 61 AC, 61 MV errors in P frame
[h264 @ 02a89d80] cbp too large (2895) at 6 621 (bit/s) efps=10.0/12.1
[h264 @ 02a89d80] error while decoding MB 6 6
[h264 @ 02a89d80] concealing 72 DC, 72 AC, 72 MV errors in P frame
[h264 @ 02a89d80] dquant out of range (219) at 3 0it/s) efps=10.0/11.5
[h264 @ 02a89d80] error while decoding MB 3 0
[h264 @ 02a89d80] concealing 54 DC, 54 AC, 54 MV errors in P frame
[h264 @ 02a89d80] cbp too large (127) at 2 9597 (bit/s) efps=10.0/11.5
[h264 @ 02a89d80] error while decoding MB 2 9
[h264 @ 02a89d80] concealing 76 DC, 76 AC, 76 MV errors in P frame
[h264 @ 02a89d80] concealing 82 DC, 82 AC, 82 MV errors in P frame11.5
[h264 @ 02a89d80] P sub_mb_type 9 out of range at 4 9s) efps=10.0/11.5
[h264 @ 02a89d80] error while decoding MB 4 9
[h264 @ 02a89d80] concealing 71 DC, 71 AC, 71 MV errors in P frame
[h264 @ 02a89d80] mb_type 269 in P slice too large at 14 5ps=10.0/11.5
[h264 @ 02a89d80] error while decoding MB 14 5
[h264 @ 02a89d80] concealing 56 DC, 56 AC, 56 MV errors in P frame
[h264 @ 02a89d80] negative number of zero coeffs at 11 2efps=10.0/11.5
[h264 @ 02a89d80] error while decoding MB 11 2
[h264 @ 02a89d80] Frame num change from 11 to 12
[h264 @ 02a89d80] decode_slice_header error
[h264 @ 02a89d80] concealing 303 DC, 303 AC, 303 MV errors in P frame
[h264 @ 02a89d80] concealing 11 DC, 11 AC, 11 MV errors in I frame9.5
[h264 @ 02a89d80] concealing 71 DC, 71 AC, 71 MV errors in P frame9.5
long async blocking: 2404>100 ms (h=0x93aa10 arg=(nil)) efps=10.0/11.5
PS D:\baresip\bin> 59/25085 video=659883/392587 (bit/s) efps=10.0/12.0

config file
#
# baresip configuration
#

#------------------------------------------------------------------------------

# Core
poll_method		select		# poll, select

# SIP
sip_listen		0.0.0.0:5060
#sip_certificate	cert.pem
#sip_cafile		/etc/ssl/certs/ca-certificates.crt

# Call
call_local_timeout	120
call_max_calls		4

# Audio
#audio_path		/usr/share/baresip
audio_player		winwave,nil
audio_source		winwave,nil
audio_alert		winwave,nil
#ausrc_srate		48000
#auplay_srate		48000
#ausrc_channels		0
#auplay_channels	0
#audio_txmode		poll		# poll, thread
audio_level		no
ausrc_format		s16		# s16, float, ..
auplay_format		s16		# s16, float, ..
auenc_format		s16		# s16, float, ..
audec_format		s16		# s16, float, ..

# Video
#video_source		dshow,nil
#video_display		sdl,nil
#video_size		352x288
video_size		1280x720
#video_bitrate		500000
video_bitrate		2000000
video_fps		25.00
video_fullscreen	no
videnc_format		yuv420p

# AVT - Audio/Video Transport
rtp_tos			184
#rtp_ports		10000-20000
#rtp_bandwidth		512-1024 # [kbit/s]
rtcp_mux		no
jitter_buffer_delay	5-10		# frames
rtp_stats		no
#rtp_timeout		60

# Network
net_prefer_ipv6		no
#dns_server		1.1.1.1:53
#dns_server		1.0.0.1:53
#net_interface		eth0

#------------------------------------------------------------------------------
# Modules

#module_path		/usr/lib/baresip/modules

# UI Modules
module			wincons.dll
#module			cons.dll
#module			evdev.dll
#module			httpd.dll

# Audio codec Modules (in order)
module			opus.dll
#module			amr.dll
#module			g7221.dll
#module			g722.dll
#module			g726.dll
module			g711.dll
#module			gsm.dll
#module			l16.dll
#module			mpa.dll
#module			codec2.dll
#module			ilbc.dll
#module			isac.dll

# Audio filter Modules (in encoding order)
#module			vumeter.dll
#module			sndfile.dll
#module			speex_pp.dll
#module			plc.dll
#module			webrtc_aec.dll

# Audio driver Modules
module			winwave.dll
#module			jack.dll
#module			portaudio.dll
#module			aubridge.dll
#module			aufile.dll

# Video codec Modules (in order)
module			avcodec.dll
#module			vp8.dll
#module			vp9.dll

# Video filter Modules (in encoding order)
#module			selfview.dll
#module			snapshot.dll
#module			swscale.dll
#module			vidinfo.dll

# Video source modules
module			dshow.dll
#module			avformat.dll
#module			x11grab.dll
#module			cairo.dll
#module			vidbridge.dll

# Video display modules
#module			x11.dll
module			sdl.dll
#module			fakevideo.dll

# Audio/Video source modules
#module			rst.dll
#module			gst.dll
#module			gst_video.dll

# Media NAT modules
module			stun.dll
module			turn.dll
module			ice.dll
#module			natpmp.dll
#module			pcp.dll

# Media encryption modules
#module			srtp.dll
#module			dtls_srtp.dll
#module			zrtp.dll


#------------------------------------------------------------------------------
# Temporary Modules (loaded then unloaded)

module_tmp		uuid.dll
module_tmp		account.dll


#------------------------------------------------------------------------------
# Application Modules
#module_app		glog.dll
module_app		auloop.dll
#module_app		b2bua.dll
module_app		contact.dll
module_app		debug_cmd.dll
#module_app		echo.dll
#module_app		gtk.dll
module_app		menu.dll
#module_app		mwi.dll
#module_app		presence.dll
#module_app		syslog.dll
#module_app		mqtt.dll
#module_app		ctrl_tcp.dll
module_app		vidloop.dll


#------------------------------------------------------------------------------
# Module parameters


# UI Modules parameters
cons_listen		0.0.0.0:5555 # cons

http_listen		0.0.0.0:8000 # httpd - server

ctrl_tcp_listen		0.0.0.0:4444 # ctrl_tcp

evdev_device		/dev/input/event0

# Opus codec parameters
opus_bitrate		28000 # 6000-510000
#opus_stereo		yes
#opus_sprop_stereo	yes
#opus_cbr		no
#opus_inbandfec		no
#opus_dtx		no
#opus_mirror		no
#opus_complexity	10
#opus_application	audio	# {voip,audio}
#opus_samplerate	48000
#opus_packet_loss	10	# 0-100 percent

# Opus Multistream codec parameters
#opus_ms_channels	2	#total channels (2 or 4)
#opus_ms_streams		2	#number of streams
#opus_ms_c_streams	2	#number of coupled streams

vumeter_stderr		yes

# Selfview
video_selfview		window # {window,pip}
#selfview_size		64x64

# ICE
ice_turn		no
ice_debug		no
ice_nomination		regular	# {regular,aggressive}

# ZRTP
#zrtp_hash		no  # Disable SDP zrtp-hash (not recommended)

# Menu
#menu_bell		yes
#redial_attempts	0 # Num or <inf>
#redial_delay		5 # Delay in seconds
#ringback_disabled	no
#statmode_default	off

# avcodec
avcodec_h264enc	libx264
avcodec_h264dec	h264
#avcodec_h265enc	libx265
#avcodec_h265dec	hevc
#avcodec_hwaccel	none

# mqtt
#mqtt_broker_host	127.0.0.1
#mqtt_broker_port	1883
#mqtt_broker_clientid	baresip01
#mqtt_broker_user	user
#mqtt_broker_password	pass
#mqtt_basetopic		baresip/01

# sndfile
#snd_path		/tmp
