### ISSUE TITLE
Terminal freezed after call hanguped

### ISSUE THREAD

**Issue by ricar87** [alfredh/baresip#845]
Hi,
I'm using Baresip v.0.6.4 on: 
Operating System: Debian GNU/Linux 9 (stretch)
Kernel: Linux 4.9.88-10182-gec7d7d8
Architecture: arm.
After I answered an  incoming call with "a" command from terminal and hanguped the call, I'm not able to send other commands from terminal. The terminal seems to be freezed, no longer responds to any commands. If I kill baresip and I restart it, It works, but stopped to running again when a call is hanguped. 
Thank you

**Comment by GGGO** [comment]
Hi,

We need more information, give us your config file, console log and SIP trace, and run baresip in debug mode.

Blind guess, it could be a sound/video driver problem.
Enable echo.so and aubridge.so modules in your config file, make an inbound call and hangup.
For testing, make a simple audio call, not a video one.

Note: with echo module, Baresip will auto-answer the call.

Please see please [https://github.com/alfredh/baresip/wiki/Guidelines-for-reporting-Issues](https://github.com/alfredh/baresip/wiki/Guidelines-for-reporting-Issues)

**Comment by ricar87** [comment]
Hi,
thank you for your reply.
I attached my config file (config.txt).
[config.txt](https://github.com/alfredh/baresip/files/3807901/config.txt)
I attached console logs during an incoming call, answering and hangup (consoleLog.txt).Terminal freezed after hangup.
[consoleLog.txt](https://github.com/alfredh/baresip/files/3807907/consoleLog.txt)
I try to enable echo.so and aubridge.so modules, I attached the console logs during the call  (consoleLogAubridge.txt) . When I make an inbound call with this configuration, no sound can be heard but the terminal doesn't freeze. 
[consoleLogAubridge.txt](https://github.com/alfredh/baresip/files/3807967/consoleLogAubridge.txt)

Thank you

**Comment by GGGO** [comment]
So, pulse doesn’t work in your case, I don’t know why but maybe you could try alsa.so ?

**Comment by ricar87** [comment]
Hi,
I also tried alsa but I have the same problem. I noticed that if I start baresip as root, it doesn't freeze after the call is hanguped. If I start baresip from another user, it freezes after the call is hanguped. I need to start baresip as another user who is not root.

Thank you

**Comment by alfredh** [comment]
it could be that the main thread is waiting for the pa record thread to exit:

modules/pulse/recorder.c:

destructor:
```c
	/* Wait for termination of other thread */
	if (st->run) {
		debug("pulse: stopping record thread\n");
		st->run = false;
		(void)pthread_join(st->thread, NULL);
	}
```

read_thread:
```c
	while (st->run) {

		ret = pa_simple_read(st->s, st->sampv, num_bytes, &pa_error);
		if (ret < 0) {
			warning("pulse: pa_simple_write error (%s)\n",
				pa_strerror(pa_error));
			continue;
		}
```

in the destructor, *before* calling `pthread_join` you might perhaps add
a call to one of these:

- pthread_kill
- pa_simple_free
- pa_simple_drain
- pa_simple_flush

if you can run baresip in gdb, press Ctrl-C when the freeze happens,
and then look at the backtrace of all threads.

**Comment by alfredh** [comment]
you should also consider to remove Pulseaudio and use ALSA directly:

https://www.howtoinstall.co/en/debian/stretch/pulseaudio?action=remove

are you using a USB soundcard ?

**Comment by ricar87** [comment]
I'm not using USB soundcard. I use the earphone output and the microphone input.
I can' t use ALSA directly beacause I need to record call using port monitor and arecord.
I can confirm that the problem could be related to pulse, since if I kill pulse when baresip is blocked, it works again.

**Comment by alfredh** [comment]
You can also use the module `sndfile.so` to record audio to WAV files.

Can you test if the program `parecord` is working ?

Did you have a chance to test my suggestions ?

**Comment by ricar87** [comment]
Thank you for your suggestion. I recorded audio to WAV files using sndfile.so and it works. 
I have another question. I need to read and write custom fields in the INVITE header .Is it possible?

**Comment by alfredh** [comment]
the pulseaudio system also has an alsa emulation layer
to the application. so it should still be possible to run the pulseaudio server
and use alsa from the application.

can you please test if this is working:

```
audio_player            alsa,default
audio_source            alsa,default
```

**Comment by ricar87** [comment]
Using 
`audio_source            alsa,default` 
`audio_player            alsa,default`   
it works.
I am able to record audio using sndfile.so

**Comment by alfredh** [comment]
thanks, then I will close it.
