### ISSUE TITLE
dtls_srtp problem

### ISSUE THREAD

**Issue by idelac3** [alfredh/baresip#847]
baresip v0.6.4 terminates call with following error:

`stream: audio: starting mediaenc 'dtls_srtp' (wait_secure=1)`
`call: connecting to 'sip:1001@192.168.56.1'..`
`stream: drop incoming RTCP packet on RTP port (pt=75)`
`call: SIP Progress: 180 Ringing (/)`
`stream: update 'audio'`
`stream: audio: starting mediaenc 'dtls_srtp' (wait_secure=1)`
`dtls_srtp: media=audio -- start DTLS server`
`1002@192.168.56.1: Call established: sip:1001@192.168.56.1`
`dtls_srtp: incoming DTLS connect from 192.168.56.1:15007`
`tls: 140424615628224:error:141A20F4:SSL routines:ossl_statem_server_read_transition:unexpected message:../ssl/statem/statem_srvr.c:298:`
`dtls: accept error: 1`
`dtls_srtp: dtls-connection closed (Protocol error)`
`call: mediaenc 'dtls_srtp' error: Protocol error`
`sip:1002@192.168.56.1: Call with sip:1001@192.168.56.1 terminated (duration: 2 secs)`

I have noticed that on another system this error occurs:

`stream: audio: starting mediaenc 'dtls_srtp' (wait_secure=1)`
`call: connecting to 'sip:1002@127.0.0.1'..`
`call: SIP Progress: 180 Ringing (/)`
`stream: update 'audio'`
`stream: audio: starting mediaenc 'dtls_srtp' (wait_secure=1)`
`dtls_srtp: media=audio -- start DTLS server`
`1001@127.0.0.1: Call established: sip:1002@127.0.0.1`
`dtls_srtp: incoming DTLS connect from 10.7.82.174:15009`
`tls: 139961918744320:error:140FC0F4:SSL routines:dtls1_get_message:unexpected message:d1_both.c:522:`
`dtls: accept error: 1`
`dtls_srtp: dtls-connection closed (Protocol error)`
`call: mediaenc 'dtls_srtp' error: Protocol error`
`sip:1001@127.0.0.1: Call with sip:1002@127.0.0.1 terminated (duration: 2 secs)`

Tested on Ubuntu 18.04.2 with libssl-dev:amd64 1.1.1-1ubuntu2.1
Tested on Mint 18 Sarah with libssl-dev:amd64  1.0.2g-1ubuntu4.15

For first error, test call was made from Mint system to Ubuntu. Second error appear when call was made from Ubuntu system to Mint system.

Both baresip systems have dtls_srtp modules installed and enabled with account setup like:

`<sip:1002:1002@192.168.56.1>;answermode=auto;mediaenc=dtls_srtp`

Could it be problem with different OpenSSL lib. versions ?

**Comment by idelac3** [comment]
Seems that DTLS and SRTP direct call between two baresip phones works.

Only when SIP proxy is involevd, DTLS session fails.

**Comment by juha-h** [comment]
idelac writes:

> Seems that DTLS and SRTP direct call between two baresip phones works.
> 
> Only when SIP proxy is involevd, DTLS session fails.

SIP proxy has nothing to do with SDP.

**Comment by idelac3** [comment]
I had to turn off RTP media proxy on SIP proxy, and enable direct (S)RTP flow between baresip phones.

DTLS-SRTP is probably not possible at all if SIP proxy enforce RTP packet forwarding. SIP proxy should let media flow directly between two endpoints (two baresip phones in my example).

**Comment by alfredh** [comment]
DTLS-SRTP between 2 baresip's is working fine, see here for a Wireshark trace:

[dtls.pcapng.zip](https://github.com/alfredh/baresip/files/3832459/dtls.pcapng.zip)

if you think that there is a bug in baresip, please provide the following:

1. wireshark trace of SIP/DTLS traffic between baresip and server
2. the corresponding baresip log
3. the corresponding server-side log
