### ISSUE TITLE
(cedrus264) Possibility to directly pipe h264 encoded FFmpeg stream without further encoding from baresip

### ISSUE THREAD

**Issue by xn2000** [alfredh/baresip#85]
I am trying to use an Allwinner A20 Board with cedrus264 enabled FFmpeg hardware encoding with baresip.
Unfortunately my attempts failed so far.
I have tried to pipe FFmpeg output to a MKFIFO generated output file and use baresip with "avformat" input, which resulted in no video data.
It seemed as if baresip ignored all Parameters related to avformat.
The FFmpeg stream itself is fine. I tested it with gstreamer which accepts it without issues.
Is it possible to have some sort of packaging only audio/video input without mkfifo and sorts or some way to integrate FFmpeg encoders?

Best Regards,

xn2000

My Config:

#
# baresip configuration
#

#------------------------------------------------------------------------------

# Core
poll_method		epoll		# poll, select, epoll ..

# SIP
sip_trans_bsize		128
sip_listen		0.0.0.0:5060
#sip_certificate	cert.pem

# Audio
audio_player		alsa,default
audio_source		alsa,default
audio_alert		alsa,default
audio_srate		8000-48000
audio_channels		1-2
#ausrc_srate		48000
#auplay_srate		48000
#ausrc_channels		0
#auplay_channels		0

# Video
video_source            avformat,/root/out.mp4
#video_source		v4l2,/dev/video0
#video_display		x11,nil
#video_size		1280x720
#video_bitrate		300
#video_fps		15

# AVT - Audio/Video Transport
rtp_tos			184
#rtp_ports		10000-20000
#rtp_bandwidth		512-1024 # [kbit/s]
rtcp_enable		yes
rtcp_mux		no
jitter_buffer_delay	15-30		# frames
rtp_stats		no

# Network
#dns_server		10.0.0.1:53
#net_interface		eth0

# BFCP
#bfcp_proto		udp

#------------------------------------------------------------------------------
# Modules

module_path		/usr/local/lib/baresip/modules

# UI Modules
module			stdio.so
module			cons.so
#module			evdev.so
module			httpd.so

# Audio codec Modules (in order)
#module			opus.so
#module			silk.so
#module			amr.so
#module			g7221.so
#module			g722.so
#module			g726.so
module			g711.so
#module			gsm.so
#module			l16.so
#module			speex.so
#module			bv32.so

# Audio filter Modules (in encoding order)
module			vumeter.so
#module			sndfile.so
#module			speex_aec.so
#module			speex_pp.so
#module			plc.so

# Audio driver Modules
module			alsa.so
#module			portaudio.so

# Video codec Modules (in order)
module			avcodec.so
module			vpx.so

# Video filter Modules (in encoding order)
#module			selfview.so

# Video source modules
#module			v4l.so
module			v4l2.so
#module			x11grab.so
#module			cairo.so

# Video display modules
#module			x11.so
#module			sdl2.so

# Audio/Video source modules
#module			rst.so
#module			gst.so

# Media NAT modules
module			stun.so
module			turn.so
module			ice.so
#module			natpmp.so

# Media encryption modules
#module			srtp.so
#module			dtls_srtp.so

#------------------------------------------------------------------------------
# Temporary Modules (loaded then unloaded)

module_tmp		uuid.so
module_tmp		account.so

#------------------------------------------------------------------------------
# Application Modules

module_app		auloop.so
module_app		contact.so
module_app		menu.so
#module_app		mwi.so
#module_app		natbd.so
#module_app		presence.so
#module_app		syslog.so
module_app		vidloop.so

#------------------------------------------------------------------------------
# Module parameters

cons_listen		0.0.0.0:5555

http_listen		0.0.0.0:8000

evdev_device		/dev/input/event0

# Speex codec parameters
speex_quality		7 # 0-10
speex_complexity	7 # 0-10
speex_enhancement	0 # 0-1
speex_mode_nb		3 # 1-6
speex_mode_wb		6 # 1-6
speex_vbr		0 # Variable Bit Rate 0-1
speex_vad		0 # Voice Activity Detection 0-1
speex_agc_level		8000

# Opus codec parameters
opus_bitrate		28000 # 6000-510000

# NAT Behavior Discovery
natbd_server		creytiv.com
natbd_interval		600		# in seconds

# Selfview
video_selfview		window # {window,pip}
#selfview_size		64x64

# ICE
ice_turn		no
ice_debug		no
ice_nomination		regular	# {regular,aggressive}
ice_mode		full	# {full,lite}

**Comment by alfredh** [comment]
have you tried the v4l2_codec module ?

what kind of codecs does your Hardware support. If your hardware can generate
H.264 frames which can be read by FFmpeg, then we can implement a new module
that reads raw input from FFmpeg and then do H.264 packetization+RTP send.

can you also share some FFmpeg/Gstreamer command line examples
that work with your Hardware ?

**Comment by xn2000** [comment]
Yes i have tried it but unfortunately had no success. 
The hardware encoder can compress to H.264 Mainline with NV12 or NV16 colorspace.
It also does only accept NV12/16 raw input.
Its limitations regarding colorspace in conjunction with baresip are probably a problem because i could not find any "yuv420 <--> nv12/16" converter in librem.
I did manage to get it working with gstreamer but had to modify: 

modules/v4l2/v4l2.c (added NV12 to input formats)
modules/gst_video/encode.c (modified pipeline and removed yuv420 hardcoding)
and src/video.c (changed default format to NV12).

It´s a rather ugly hack which breaks functionality of most of the other modules which rely on yuv420.
Additionally the gstreamer module is not performing very well (4-5 fps@720p, which by the way is still 10x better than software encoding). Its FFmpeg counterpart does perform way better (30fps@720p).

A new module which could do that would be great. :-)
I think the possiblity to change colorspace throughout baresip or have a converter "yuv420 <--> nv12/16" would also be required. But i would rather like to avoid conversion altogether because of its impact on performance.


Commandline Examples:

Working FFmpeg:
/usr/bin/ffmpeg -f v4l2 -s 1280x720 -pix_fmt nv12 -i /dev/video0 -c:v cedrus264 -qp 28 -b:v 1000k -vewait 1000 -f h264 - |

Working Gstreamer:
gst-launch-0.10 -v v4l2src device=/dev/video0 ! videoparse format=nv12 width=1280 height=720 framerate=30\1 ! cedar_h264enc ! h264parse ! fdsink |


Thank you in advance for your effort.


Best Regards,

xn2000

**Comment by alfredh** [comment]
could you try the latest "v4l2_codec.so" module again, and see if it works?

baresip is using librem which supports nv12_to_yuv420p (see the vidconv module).

I believe that the hardware-accellerated codec is compressing all directly to H.264
frames (with a given colorspace format). So there should not be a need to convert
the colorspace inside baresip. This is how the v4l2_codec module works,
grep for V4L2_PIX_FMT_H264.

I would prefer to use the v4l2 interface directly, the gstreamer framework is quite
bloated and adds too much unnecessary code.

BTW. Next time you are testing a scenario that fails, could you paste the whole debug output
here plz? it is a bit easier for me to understand what is going on :)

**Comment by alfredh** [comment]
can you also list the V4L2 caps of your device:

```
$ ffmpeg -f v4l2 -list_formats all -i /dev/video0
```

https://trac.ffmpeg.org/wiki/Capture/Webcam

**Comment by xn2000** [comment]
I have not tested the new v4l2_codec module yet. But from what i can see in the source it does not seem to solve my problem because I do not have a camera with builtin compression, but a normal camera paired with a SoC which has an integrated encoding block.
My setup looks like:
V4L2 uncompressed > gst_video (SoC: Allwinner A20 - cedrus264 encoder)  h264 > output
In my case this command  "ffmpeg -f v4l2 -list_formats all -i /dev/video0" only lists  uncompressed colorspaces like YUV420,NV12...

Librem nv12_to_yuv420p does not solve my problem either because i also need the opposite, meaning yuv420_to_nv12. That is because the encoder only accepts nv12 as input.

**Comment by alfredh** [comment]
aha, I understand your setup then :)

I am working on librem to add support for YUV420P to NV12.

But can you try something else... it should be possible to other pixelformats than YUV420P
in the encoder pipeline. In video.c there is a compile-time value:

```
/** Internal video-encoder format */
#ifndef VIDENC_INTERNAL_FMT
#define VIDENC_INTERNAL_FMT (VID_FMT_YUV420P)
#endif
```

try changing this to "NV12" and also add a line for NV12 in v4l2.

at least then you should be able to pass NV12 frames all the way from
camera to encoder-block, without any colorspace conversion.

**Comment by xn2000** [comment]
Good to hear :)

I already did what you proposed for the gst_video module like I have written in the 3rd post.
It does work but the gstreamer module seems to be still buggy. For example putting a call on hold does work, but resuming it does not. On top of that the gstreamer implementation of cedrus264 is average at best. It only does 5fps at 720p, whereas another plugin for cedrus264 based on FFmpeg can achieve much higher fps and bitrates.
What I would really like is a possibility to use FFmpeg plugins other than x264. This one in particular:
[https://github.com/Alcantor/FFmpeg/commit/ab871a6b7c20f144d510c800d6bfeb698ade9ab9](url)
The avcodec module from baresip seems to be hardcoded to x264 and YUV420 colorspace.

**Comment by xn2000** [comment]
I just saw that i ignored your comment about debug-logs, sorry about that.
Next time I will post a complete log via pastebin. ;)

**Comment by alfredh** [comment]
Hey,

we added support for YUV420P to NV12 pixelformat conversion in librem:

 URL for public read-only subversion access: https://svn.creytiv.com/rem/trunk (username: anon, password: anon) 

we also added support in the avcodec-module for NV12 pixelformat:

https://github.com/alfredh/baresip/commit/b821c1b3293d61fd091e22f588dd5032b3bef8e4

could you please try it and post full debug output here (baresip -v) ?

**Comment by alfredh** [comment]
Baresip's avcodec support 2 different H.264 encoders; using libx264 directly or using FFmpeg's H.264 encoder (which may or may not be x264).

To build avcodec module without x264:

```
$ make USE_X264=
```

you may test avcodec with the FFmpeg variant that supports cedrus264. Perhaps it will
open it by default, if not we might have to tweak the code a bit to explicitly select cedrus264.

**Comment by alfredh** [comment]
I am closing this issue due to lack of response from the reporter.
Feel free to open a new issue.
