### ISSUE TITLE
audio: Marker bit handling

### ISSUE THREAD

**Issue by premultiply** [alfredh/baresip#852]
I think patch https://github.com/alfredh/baresip/pull/724 makes decoding of RFC 3640 AAC mpeg4-generic streams impossible as they have set the marker bit on each RTP packet.
https://tools.ietf.org/html/rfc3640#section-3.1

Maybe the current RX (and TX) marker bit handling has to be completly redesigned.
It would be better if the audio encoding and decoding functions have direct access to the tx/rx marker bits.

**Comment by premultiply** [comment]
After a little more investigation I think there is a general problem with the current marker bit handling when they are set on all packets as requiered for RFC 3640.
But wasn't able to get it exactly why no data is passed continuously to the decoder in this case. It looks to me like just the first RX packet is passed through and all further packets are discarded.

**Comment by alfredh** [comment]
this looks like video decoding, where the marker bit indicates the
last packet of a complete frame (fragmented).

so far we did not need to use the marker bit for audio codecs.

do you have a copy of a Wireshark trace from an endpoint that supports this ?

**Comment by premultiply** [comment]
Yes. I sent you an E-mail with a Wireshark trace.

**Comment by alfredh** [comment]
one solution is to extend the aucodec API with an optional marker bit flag:

old:

```c
typedef int (auenc_encode_h)(struct auenc_state *aes,
			     uint8_t *buf, size_t *len,
			     int fmt, const void *sampv, size_t sampc);
```

new:

```c
typedef int (auenc_encode_h)(struct auenc_state *aes,
			     bool *marker, uint8_t *buf, size_t *len,
			     int fmt, const void *sampv, size_t sampc);
```


the question is if there are other fields of the RTP header that also
should be passed to/from aucodec ?

**Comment by alfredh** [comment]
at the moment I would like to suggest the following solution:

1. add marker bit to encode API (`bool *marker`)
2. add RTP header to decode API (`struct rtp_header`)

**Comment by premultiply** [comment]
Sounds good to me.

**Comment by alfredh** [comment]
patch related to aac mpeg4-generic work:

https://gist.github.com/alfredh/90dd76b912ef86a38dee61e7252c5e71

I did some testing with Linphone for iOS which supports AAC-ELD (etc)
using mpeg4-generic

**Comment by alfredh** [comment]
here is a patch for review/testing:

https://gist.github.com/alfredh/4a81beef98479302b504b201dc2ae347

after some more thinking I think its enough to add the marker bit
to the encode/decode functions.

**Comment by premultiply** [comment]
I am looking forward to use it ;-)

**Comment by alfredh** [comment]
the patch was merged to master.

the audio encoder/decoder should now have access to the marker bit.

please note that we no longer reset the jitter-buffer if the marker bit is set:

```c
#if 0
	/* The marker bit indicates the beginning of a talkspurt. */
	if (hdr->m && s->type == MEDIA_AUDIO)
		flush = true;
#endif
```

**Comment by premultiply** [comment]
Where is or was this used?

**Comment by alfredh** [comment]
it was used for incoming RTP packets, before this patch.

anyway in the RTP profile the marker-bit is just a hint, and now it is up
to each codec to handle it.
