### ISSUE TITLE
How to configure x11grab module to share screen?

### ISSUE THREAD

**Issue by Code2Life** [alfredh/baresip#856]
after installing "libx11-dev libxext-dev", baresip could recognize x11grab video source, but there isn't a document to describe how to use it for content sharing. could anyone know how to use baresip to share screen in meeting?

![image](https://user-images.githubusercontent.com/14833440/69390361-f6850180-0d09-11ea-8fb8-ce6455b58cc6.png)

note that x11grab module is registered successfully

**Comment by alfredh** [comment]
use the x11grab as a video_source:

```
video_source    x11grab,nil
```

please read this:
https://github.com/alfredh/baresip/wiki/Guidelines-for-reporting-Issues
