### ISSUE TITLE
Can't manage to set caller-ID data

### ISSUE THREAD

**Issue by mlopez-egi** [alfredh/baresip#857]
I'm trying to send caller ID text data to the pbx.
I suppose that caller-ID is the Displayname field in account config file:
Displayname <sip:user@domain>
I tried to write, in account file:
"hall" <sip:user@domain>
But looking in the asterisk pbx, the caller-ID has not been set.

**Comment by alfredh** [comment]
can you please provide the SIP traffic between baresip and asterisk ?

also please read this:
https://github.com/alfredh/baresip/wiki/Guidelines-for-reporting-Issues

**Comment by alfredh** [comment]
please re-open if you can provide more details.

**Comment by iEdward** [comment]
@mlopez-egi Hi! I have same issue. Did you solve problem?

**Comment by ninp0** [comment]
@mlopez-egi  && @iEdward 

I had the same issue and found that it was related to the configuration on the VOIP provider side...outside of that, it was simply a matter of editing your ~/.baresip/accounts file to contain the following:

```
<sip:CALLERIDNUMBER@SIP_DOMAIN.com>;auth_user=AUTH_USER;auth_pass=AUTH_PASS
```

Hope that helps!
