### ISSUE TITLE
SIP over websockets (wss/ws)

### ISSUE THREAD

**Issue by donaldkwak** [alfredh/baresip#859]
Secure websocket connection switches from "wss" to "ws" after receiving a Record-Route containing "ws". Connection should not switch according to the RFC 7118. Record-Route should always hold "ws" even though the connection is secure.

Please see the following issue commented a while ago. Could not re-open the issue.
#807

**Comment by alfredh** [comment]
could you please provide the complete SIP trace for this session?
without it it is difficult to tell what is wrong.

**Comment by alfredh** [comment]
I have tested with SIP over Websock using the Antisip service.
Not sure if it is configured correctly or not.

SIP trace when using WS transport:

```
call: connecting to 'sip:echo@sip.antisip.com'..
#
WS 10.0.1.12:58793 -> 91.121.30.149:8080
INVITE sip:echo@sip.antisip.com SIP/2.0
Via: SIP/2.0/WS 10.0.1.12:9;branch=z9hG4bK7da34c0369e4ee3d;rport
Contact: <sip:alfredh-0x7fd686445990@10.0.1.12:9;transport=ws>
Max-Forwards: 70
Route: <sip:sip.antisip.com:8080;transport=ws;lr>
To: <sip:echo@sip.antisip.com>
From: "Anti Alf" <sip:alfredh@sip.antisip.com>;tag=407518935bd5aa4a
Call-ID: ec6847e1a715b0f6
CSeq: 22751 INVITE
User-Agent: baresip v0.6.5 (x86_64/darwin)
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER
Supported: gruu
Content-Type: application/sdp
Content-Length: 434

v=0
o=- 2848043386 148954453 IN IP4 10.0.1.12
s=-
c=IN IP4 10.0.1.12
t=0 0
a=tool:baresip 0.6.5
m=audio 23680 RTP/AVP 0 8 101
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=label:1
a=rtcp-rsize
a=ssrc:1884321226 cname:sip:alfredh@sip.antisip.com
a=minptime:20
a=ptime:20
a=ebuacip:version 0
a=ebuacip:jb 0
a=ebuacip:jbdef 0 auto 40-80
a=ebuacip:qosrec 46

#
WS 91.121.30.149:8080 -> 10.0.1.12:58793
SIP/2.0 100 trying -- your call is important to us
Via: SIP/2.0/WS 10.0.1.12:9;branch=z9hG4bK7da34c0369e4ee3d;rport=46085;received=84.208.97.1
To: <sip:echo@sip.antisip.com>
From: "Anti Alf" <sip:alfredh@sip.antisip.com>;tag=407518935bd5aa4a
Call-ID: ec6847e1a715b0f6
CSeq: 22751 INVITE
Server: kamailio (5.3.1 (x86_64/linux))
Content-Length: 0


call: SIP Progress: 100 trying -- your call is important to us (/)
#
WS 91.121.30.149:8080 -> 10.0.1.12:58793
SIP/2.0 200 OK
Via: SIP/2.0/WS 10.0.1.12:9;received=84.208.97.1;branch=z9hG4bK7da34c0369e4ee3d;rport=46085
Record-Route: <sip:91.121.30.149;r2=on;lr=on;ftag=407518935bd5aa4a>
Record-Route: <sip:91.121.30.149:8080;transport=ws;r2=on;lr=on;ftag=407518935bd5aa4a>
From: "Anti Alf" <sip:alfredh@sip.antisip.com>;tag=407518935bd5aa4a
To: <sip:echo@sip.antisip.com>;tag=BZ5FtD3Xjep8j
Call-ID: ec6847e1a715b0f6
CSeq: 22751 INVITE
Contact: <sip:echo@127.0.0.1:6080;transport=udp>
User-Agent: FreeSWITCH-mod_sofia/1.10.1-release-12-f9990221e6~64bit
Accept: application/sdp
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
Supported: path, replaces
Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
Content-Type: application/sdp
Content-Disposition: session
Content-Length: 222
Remote-Party-ID: "9196" <sip:9196@sip.antisip.com>;party=calling;privacy=off;screen=no

v=0
o=FreeSWITCH 1576245358 1576245359 IN IP4 91.121.30.149
s=FreeSWITCH
c=IN IP4 91.121.30.149
t=0 0
m=audio 21268 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
```

I also tested using WSS transport.

Comparing WS/WSS transport of 200 OK:

```
WS:
Record-Route: <sip:91.121.30.149:8080;transport=ws;r2=on;lr=on;ftag=407518935bd5aa4a>

WSS:
Record-Route: <sip:91.121.30.149:4443;transport=ws;r2=on;lr=on;ftag=dcbe022ab2d6642e>
```

the second entry is using port 4443 (HTTPS/WSS) so I am wondering
how can the transport be *ws* and not *wss* ?

I also tested tryit.jssip.net and here is the 200 OK:

```
SIP/2.0 200 OK
Record-Route: <sip:62.210.59.78:7060;transport=tcp;lr;ovid=3843b84e>
Record-Route: <sip:bed1d6c073@62.210.59.78:10443;transport=wss;lr;ovid=3843b84e>
Via: SIP/2.0/WSS vr1nm5dii0bv.invalid;branch=z9hG4bK6421219
To: <sip:music@iptel.org>;tag=10B052A3-5DF3E8A20004AFD1-2C1E2700
From: "Alf" <sip:alf_cjckld@tryit.jssip.net>;tag=0djb7r0cj4
Call-ID: q9ogpgklu6bshtp5tmri
CSeq: 194 INVITE
Contact: <sip:10B052A3-5DF3E8A20004AFD1-2C1E2700@212.79.111.155;transport=tcp>
Content-Type: application/sdp
Content-Length: 682
```

Perhaps we can ask @jmillan for help to find out what is correct usage ?

BTW: Does anyone know of other free SIP services that support SIP/WS ?

**Comment by juha-h** [comment]
A month or two ago I tested a baresip websocket patch that I got from Alfred. I noticed a few things that were wrong and emailed about them.  I don't know if they have been fixed. If I remember correctly, fixes were needed (also) in libre.

**Comment by alfredh** [comment]
@juha-h some of those bugs should be fixed now, but it is not related to this issue.

it seems to be some confusion regarding the transport=ws parameter
in Record-Route.

it is my feeling that the public SIP servers with Websock are incorrectly configured,
but the people who runs them are either too incompetent or lazy to fix it properly.

therefore it would be rather interesting if you can re-test the patch on your
SIP Proxy environment, which I understand is high quality.

WS is working as expected, WSS is not working in some cases.

**Comment by alfredh** [comment]
@donaldkwak the Record-Route uri that you receive is invalid,
the uri is "sip:" and the IP/port points to a WSS server, and transport=ws.

ACK is end-to-end message, and there is no way for the session layer
to know that WSS should be used for this, even if the 200 OK was received
via WSS. the session layer and transaction layer is decoupled.

However, I have made a workaround for this so that it should handle
both cases. You can find an updated patch here:

https://gist.github.com/alfredh/227f9ef4ee4b0203a647ff5e723b5493

NOTE: there seem to be some confusion regarding this topic.
Even if the RFC 7118 allows only transport=ws, people are still using
both transport=ws and transport=wss. So far now the patch will
also deviate from the standard, and it will still be regarded as "experimental".

**Comment by alfredh** [comment]
I now regard this issue as "fixed", even on an experimental patch ...

**Comment by juha-h** [comment]
Using JsSIP, I can specify URI of my websocket outbound proxy like this:
```
wss://<address-of-proxy>:433/wss/
```
What is the corresponding baresip way?

This
```
sip:<address-of-proxy>:443/wss/;transport=wss
```
results in
```
ua: SIP register failed: Protocol not supported
```

**Comment by alfredh** [comment]
https://github.com/alfredh/baresip/wiki/SIP-over-Websockets

**Comment by juha-h** [comment]
Thanks for the link.  Tried like this:
```
outbound="sip:192.26.134.1:443/wss/;transport=wss"
```
and got:
```
ua: SIP register failed: Function not implemented
account: failed to register ua 'sip:test@test.tutpro.com' (Function not implemented)
```
I need to have the path /wss/ in the URI, since I'm using SSLProxyEngine on an Apache web server, that is serving also other stuff.

**Comment by juha-h** [comment]
Here is another try with
```
;outbound="sip:192.26.134.1:443/wss/;transport=wss"
```
resulting in
```
websock: connecting to 'wss://192.26.134.1:443/'
Populated 1 account
Populated 2 contacts
Subscribing to 0 contacts
Populated 5 audio codecs
Populated 0 audio filters
Populated 5 video codecs
Populated 0 video filters
baresip is ready.
sip: websock connection closed (Protocol error)
reg: sip:test@test.tutpro.com: Register: Protocol error
```
websock: connecting to 'wss://192.26.134.1:443/'
...
baresip is ready.
sip: websock connection closed (Protocol error)
reg: sip:test@test.tutpro.com: Register: Protocol error
```
Path 'wss/' is missing from the URI and nothing shows up in Apache logs.

**Comment by alfredh** [comment]
couple of ideas:

1. try to print out the error codes in src/websock/websock.c
https://github.com/alfredh/re/blob/master/src/websock/websock.c#L383
(int err and msg->scode)

2. append the string "wss" to the websock connect uri, here:
https://gist.github.com/alfredh/227f9ef4ee4b0203a647ff5e723b5493#file-re-sip-websock-patch-L459

**Comment by juha-h** [comment]
I followed suggestion (2) and hardcoded the path /wss/ to the URI:
```
	/* Use port if specified, otherwise use default HTTP/HTTPS ports */
	if (sa_port(dst)) {
		if (re_snprintf(ws_uri, sizeof(ws_uri),
				"%s://%J/wss/", prefix, dst) < 0) {
			err = ENOMEM;
			goto out;
		}
	}
```
After that, registration worked fine:
```
...
websock: connecting to 'wss://192.26.134.1:443/wss/'
...
baresip is ready.
<0x558163ef6d50> WSS websock established to 192.26.134.1:443
--> send
test@test.tutpro.com: {1/WSS/v4} 200 OK (OpenSIPg SIP Proxy (5.3.1-3 (x86_64/linux))) [1 binding]
All 1 useragent registered successfully! (32 ms)
```
So looks like the issue would be solved, if the path would not get stripped from the ;outbound URI.

**Comment by datpt11** [comment]
Does the port have to be 443 when using wss?

**Comment by datpt11** [comment]
I want to use another port, is it possible?

**Comment by juha-h** [comment]
Dat Phung writes:

> Does the port have to be 443 when using wss?

No.
