### ISSUE TITLE
transport not included in account's AoR

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#860]
I have in accounts file an account defined like this:
```
"Test Account" <sip:test@test.tutpro.com:5060;transport=tcp>;auth_user=test;auth_pass=foobar;audio_codecs=PCMA,PCMU;regint=600;pubint=0;regq=0.5
```
When I then make `account_aor` API call, I get
```
sip:test@test.tutpro.com:5060
```
that is, port is included in the aor, but transport param is not.

Is that a bug?  If not, what is the logic of including port, but excluding transport?

**Comment by GGGO** [comment]
In account_alloc you have:
`err = re_sdprintf(&acc->aor, "%H", encode_uri_user, &acc->luri);`

And encode_uri_user removes not only transport but password, params and headers too:
`uuri.password = uuri.params = uuri.headers = pl_null;`

I think transport param is not included here to keep thing simple.

Maybe uri_param_get could help you ?

**Comment by juha-h** [comment]
I can get the transport with account_laddr. My point was that port should not be included either.

**Comment by alfredh** [comment]
the answer is that I dont know or dont remember :)

if you want to change this, we need to analyze all functions
calling `account_aor` and check for strange side-effects.

**Comment by juha-h** [comment]
OK, will check. My net is now so slow that I can't get to GitHub web site.

**Comment by alfredh** [comment]
I think we should just leave the code as is.

Even if I cant remember why, and with the port/transport not being set,
I think it is too dangerous to start changing this code.

**Comment by juha-h** [comment]
I agree. I can filter the Port out in the app. Can't close this due to poor network connection.
