### ISSUE TITLE
Error with inbound calls over IPv6 <incompatible address-family>

### ISSUE THREAD

**Issue by simonsimon006** [alfredh/baresip#862]
I have an asterisk pbx with an ipv6 and ipv4 address which is connected to a SIP Provider. Baresip Android registers with TLS at said pbx. When I call out everything works. But if I am called it rejects the call with:
> incompatible address-family (local=AF_INET6, remote=AF_INET)

which I do not understand, as my LAN and pbx is IPv6 capable.

From reading the logs baresip seems to see the IPv6 address but still fails.

I have attached a logcat dump from the baresip process.
[baresip.log](https://github.com/alfredh/baresip/files/3906462/baresip.log)

**Comment by alfredh** [comment]
can you please transfer this issue to:

https://github.com/juha-h/baresip-studio

**Comment by simonsimon006** [comment]
I opened the issue at the other repo because I can not transfer it. Can you close this one?
