### ISSUE TITLE
Supporting various codecs on OSX

### ISSUE THREAD

**Issue by sosaucily** [alfredh/baresip#866]
Do you have advice for getting codecs other than 711 working on OSX? In particular, I see the android baresip app by juha-h (https://github.com/juha-h/baresip-studio) supports 722, 726 and opus. But getting these installed on OSX does not seem trivial. I tried building opus from source, and installing from homebrew, but it creates a dylib file that doesn't seem it will work easily with the baresip client module-load system.

Thanks

**Comment by alfredh** [comment]
try this:

`$ brew install fdk-aac spandsp opus`

or

`$ sudo port install libfdk-aac spandsp-devel libopus`

and then re-compile baresip

**Comment by sosaucily** [comment]
That does not seem to create an opus.so file either, unfortunately.

**Comment by alfredh** [comment]
make USE_OPUS=yes

**Comment by sosaucily** [comment]
100% you got it, thank you!

**Comment by frequencebanane** [comment]
Hello, @alfredh can you explain a bit more what do you mean ?
I'm installing on mac os using 
`brew install baresip`
