### ISSUE TITLE
How to correspond to version baresip、rem、re

### ISSUE THREAD

**Issue by yuexiajiayan** [alfredh/baresip#868]
![2](https://user-images.githubusercontent.com/16077858/70214891-38389200-1777-11ea-9493-e166eba64c93.jpg)

How to select the re and rem versions of baresip 0.6.5

**Comment by alfredh** [comment]
Please read this before creating an issue:

https://github.com/alfredh/baresip/wiki/Guidelines-for-reporting-Issues

as a general rule, the latest version of libre and librem should
work with the latest version of baresip.
