### ISSUE TITLE
Using libre for WebRTC, datachannels support

### ISSUE THREAD

**Issue by chertov** [alfredh/baresip#870]
Hi! I am trying to use libre webrtc components in my C application. libre is awesome, i was build it for armv5 and i can run it on hisilicon chip for ip cams with 64Mb ram.
We have only 16Mb spi flash for linux and 32-256Mb ram on iot devices like ip cams.
libnice has dependencies on glib and needs additional code, libwebrtc from google needs C++ runtime and it can't take raw h264 nal stream, pion webrtc doesn't support to build with tinyGo at the moment..
I think to use libre for iot communicate via WebRTC is a good choice!
My build for armv5: libre.so (only webrtc + rtmp) 1.9Mb, librem.so 177kb, baresip 663kb without strip and compression
Maybe we can get a bit small size

I can't find datachannels in libre. Do you have any plans to support them?

**Comment by alfredh** [comment]
What is the name of the Hisilicon chip that you are using ?

when compiled for OpenWRT the filesize is a bit smaller than yours:

https://openwrt.org/packages/pkgdata_lede17_1/libre
https://openwrt.org/packages/pkgdata_lede17_1/baresip

libre: 129kB
baresip: 206kB

have a look at the openwrt toolchain for how it is compiled:

https://github.com/openwrt/telephony/tree/master/net/baresip

can you share details about your build environment ?

when compiling for embedded targets you should use this flag:

`$ make RELEASE=yes`

Have a look at this WebRTC demo which is a complete
Web server with signaling and media:

https://github.com/alfredh/baresip-webrtc

Have a look at this comparison table:

https://github.com/alfredh/baresip/wiki/WebRTC-features

Data-channels is not supported, patch to baresip is welcome.

**Comment by nonibytes** [comment]
Having data channels would be great as that would make it possible to use libre on low footprint devices as a replacement for WebRTC.
