### ISSUE TITLE
windows runs, the process exits

### ISSUE THREAD

**Issue by 75535552** [alfredh/baresip#872]
PS D:\baresip\bin> .\baresip-win32.exe
baresip v0.6.5 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.
Binding to interface or IP address '192.168.9.100'
Local network address:  IPv4={B27E6E89-9D5F-46E7-A871-C7B529CA1BD2}|192.168.9.100
aucodec: opus/48000/2
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: speex_pp
aufilt: webrtc_aec
winwave: output devices: 1, input devices: 1
ausrc: winwave
auplay: winwave
vidcodec: H264
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidcodec: H265
avcodec: using H.264 encoder 'libx264' -- libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.264 decoder 'h264' -- H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.265 encoder 'libx265' -- libx265 H.265 / HEVC
avcodec: using H.265 decoder 'hevc' -- HEVC (High Efficiency Video Coding)
vidsrc: dshow
vidisp: sdl
medianat: stun
medianat: turn
medianat: ice
medianat: ice-lite
Populated 1 account
Populated 3 contacts
Populated 3 audio codecs
Populated 2 audio filters
Populated 5 video codecs
Populated 0 video filters
baresip is ready.
10000001690@120.52.96.193: {0/TCP/v4} 200 OK () [1 binding]
[32mAll 1 useragent registered successfully! (87 ms)[;m
--- Help ---
                      ESC      Hangup call
  /about                       About box
  /accept             a        Accept incoming call
  /answermode ..               Set answer mode
  /auloop ..                   Start audio-loop <srate ch>
  /auloop_stop                 Stop audio-loop
  /auplay ..                   Switch audio player
  /ausrc ..                    Switch audio source
  /callstat           c        Call status
  /conf_reload                 Reload config file
  /config                      Print configuration
  /contact_next       >        Set next contact
  /contact_prev       <        Set previous contact
  /contacts           C        List contacts
  /dial ..            d ..     Dial
  /dialcontact        D        Dial current contact
  /hangup             b        Hangup call
  /help               h        Help menu
  /insmod ..                   Load module
  /listcalls          l        List active calls
  /loglevel           v        Log level toggle
  /main                        Main loop debug
  /memstat            y        Memory status
  /message ..         M ..     Message current contact
  /modules                     Module debug
  /netstat            n        Network debug
  /options ..         o ..     Options
  /play ..                     Play audio file
  /quit               q        Quit
  /reginfo            r        Registration info
  /rmmod ..                    Unload module
  /sipstat            i        SIP debug
  /sysinfo            s        System info
  /timers                      Timer debug
  /uadel ..                    Delete User-Agent
  /uafind ..                   Find User-Agent <aor>
  /uanew ..                    Create User-Agent
  /uanext             T        Toggle UAs
  /uastat             u        UA debug
  /uuid                        Print UUID
  /vidloop ..                  Start video-loop <codec>
  /vidloop_stop                Stop video-loop
  /vidsrc ..                   Switch video source

/loglevel
Log level 'DEBUG'
>                          4002103
call: alloc with params laddr=192.168.9.100, af=AF_INET, use_rtp=1
call: use_video=1
call: connecting to 'sip:4002103@120.52.96.193;transport=tcp'..
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 180 Ringing (/)
video: stopping video source ..
[31mplay: /usr/share/baresip/ringback.wav: No such file or directory
call: got SDP answer (1262 bytes)
call: update media
stream: update 'audio'
stream: audio: starting RTCP with remote 120.52.96.193:53173
stream: update 'video'
stream: video: starting RTCP with remote 120.52.96.193:53203
audio: Set audio decoder: opus 48000Hz 2ch
audio: start
audio: player started with sample format S16LE
audio: Set audio encoder: opus 48000Hz 2ch
opus: encoder fmtp (useinbandfec=1)
audio: start
speex_pp: Speex preprocessor loaded: srate = 48000Hz
[31mwebrtc_aec: unsupported channels (2 > 1)
[;m[31maudio: error in encode audio-filter 'webrtc_aec' (Unknown error)
[;m[31mwebrtc_aec: unsupported channels (2 > 1)
[;m[31maudio: error in decode audio-filter 'webrtc_aec' (Unknown error)
[;m[31maudio: audio-filter 'webrtc_aec' update failed (Unknown error)
[;maudio: source started with sample format S16LE
audio tx pipeline:     winwave ---> speex_pp ---> opus
audio rx pipeline:     winwave <--- opus
Set video encoder: H264 packetization-mode=0 (2000000 bit/s, 25.00 fps)
avcodec: h264 encoder activated
avcodec: video encoder H264: 25.00 fps, 2000000 bit/s, pktsize=1024
dshow: got device '' id=0
warning: The VAD has been replaced by a hack pending a complete rewrite
speex_pp: state inited (frame_size=1920)
call: stream start (active=1)
opus: encoder fmtp (useinbandfec=1)
audio: start
Set video decoder: H264 packetization-mode=0
avcodec: h264 decoder activated
avcodec: decode: hardware accel disabled
avcodec: video decoder H264 ()
10000001690@120.52.96.193: Call established: sip:4002103@120.52.96.193;transport=tcp
long async blocking: 1074>100 ms (h=0x869960 arg=0x1427f50)
stream: incoming rtp for 'audio' established, receiving from 120.52.96.193:53172
[libx264 @ 030c8780] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 030c8780] profile Constrained Baseline, level 2.1, 4:2:0, 8-bit
stream: incoming rtp for 'video' established, receiving from 120.52.96.193:53202
avcodec: decoder waiting for keyframe
avcodec: decoder waiting for keyframe
avcodec: decoder waiting for keyframe
avcodec: decoder waiting for keyframe
avcodec: decoder waiting for keyframe
avcodec: decoder waiting for keyframe
avcodec: decoder waiting for keyframe
avcodec: decoder waiting for keyframe
avcodec: decoder waiting for keyframe efps=0.0/0.0
avcodec: decoder waiting for keyframe
avcodec: decoder waiting for keyframe
avcodec: decoder waiting for keyframe
avcodec: decoder waiting for keyframe
sdl: created renderer 'direct3d'
long async blocking: 191>100 ms (h=0x86ba30 arg=0x144fbd0)
avcodec: encoder picture updatebit/s) efps=0.0/0.0
avcodec: encoder picture updatebit/s) efps=0.0/0.0
avcodec: encoder picture updatebit/s) efps=0.0/0.0
[h264 @ 030ab840] Frame num change from 86 to 87.0
[h264 @ 030ab840] decode_slice_header error
[h264 @ 030ab840] Frame num change from 86 to 87
[h264 @ 030ab840] decode_slice_header error
[h264 @ 030ab840] Frame num change from 86 to 87
[h264 @ 030ab840] decode_slice_header error
[h264 @ 030ab840] Frame num change from 86 to 87
[h264 @ 030ab840] decode_slice_header error
[h264 @ 030ab840] Frame num change from 86 to 87
[h264 @ 030ab840] decode_slice_header error
[h264 @ 030ab840] Frame num change from 86 to 87
[h264 @ 030ab840] decode_slice_header error
[h264 @ 030ab840] concealing 119 DC, 119 AC, 119 MV errors in P frame
avcodec: encoder picture updateeo=625567/1279986 (bit/s) efps=28.3/27.1
long async blocking: 2576>100 ms (h=0x86ba30 arg=0x144fbd0)ps=28.3/27.1
PS D:\baresip\bin> 05/19620 video=625567/1279986 (bit/s) efps=28.3/27.1

**Comment by alfredh** [comment]
can you please provide a backtrace ?

**Comment by 75535552** [comment]
Thank you very much for your reply.
what should I do? It's a good way for breaktrace in windows
I tried GLOG but didn't print it successfully

**Comment by alfredh** [comment]
Perhaps you should ask a search-engine or ask one of your friendly co-workers ?

I am not a windows-expert, but I would assume something like this:

1. Start Visual Studio and load your project.
2. Run in debug mode
3. When program crashes, it will most likely stop and show you the backtrace
