### ISSUE TITLE
Register on Asterisk with TLS

### ISSUE THREAD

**Issue by Telefonorosso** [alfredh/baresip#876]
Good morning sir.

I can't register on an Asterisk server with TLS, the Baresip client fails issuing a "Connection timed out" error. On server side I see TLS traffic being exchanged (so not a firewall issue) but no logs on Asterisk console.

- OS server: Amazon Ubuntu server 18 kernel 4.15.0
- OS client: Ubuntu kernel 4.15.0
- Asterisk version 17 with Pjproject 2.9
- Baresip 0.5.7
- Certificates issued by Letsencrypt
- Client certificate created with this command:

`ast_tls_cert -m client -c /etc/letsencrypt/live/sip.pgpwaves.eu/fullchain.pem -k /etc/letsencrypt/live/sip.pgpwaves.eu/privkey.pem -C sip.pgpwaves.eu -O "PGPwaves" -d /etc/asterisk/keys -o client`

Here is the source of the "ast_tls_cert" helper script:
https://github.com/asterisk/asterisk/blob/master/contrib/scripts/ast_tls_cert#L49

On client machine I've copied:
- fullchain.pem -> renamed to ca.crt
- client.pem

Server is natted (Amazon web services), client too (behind home router).
Domain name and server IP are correctly matched.
Server hostname is correct ( "hostname" returns sip.pgpwaves.eu)
All relevant files are attached.
Thanks in advance for your valuable time!

[pjsip.conf.txt](https://github.com/alfredh/baresip/files/3968037/pjsip.conf.txt)
[tcpdump.zip](https://github.com/alfredh/baresip/files/3968038/tcpdump.zip)
[baresip.cli.output.txt](https://github.com/alfredh/baresip/files/3968039/baresip.cli.output.txt)
[baresip.accounts.txt](https://github.com/alfredh/baresip/files/3968040/baresip.accounts.txt)
[baresip.config.txt](https://github.com/alfredh/baresip/files/3968041/baresip.config.txt)

**Comment by Telefonorosso** [comment]
Baresip 0.5.7 was silently ignoring **sip_cafile** directive.
Upgraded to baresip v0.6.5 but still having the same issue.

**Comment by alfredh** [comment]
the TCP connection is closed by the server, after the first encrypted SIP packet
has arrived.


here are a couple of ideas:

1. can you test if SIP over TCP is working ?

2. can you test if the TLS server is working, by using a different client ?
  for example openssl client:

```
$ openssl s_client -connect www.apple.com:443
```

3. can you test other SIP client and see if that is working ?

4. can you enable verbose logging on the server to see what is going on ?


Alfred

**Comment by Telefonorosso** [comment]
Hello and thank you!
1. SIP TLS _without client certificate checking_ works so I assume SIP/TCP works too but I'll try.
2. I presume I've messed up certificates because...

`openssl s_client -connect sip.pgpwaves.eu:5561`

...reports multiple issues:

> depth=0 CN = sip.pgpwaves.eu
> verify error:num=20:unable to get local issuer certificate
> verify return:1
> depth=0 CN = sip.pgpwaves.eu
> verify error:num=21:unable to verify the first certificate
> verify return:1
> 139916936294848:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../ssl/record/rec_layer_s3.c:1399:SSL alert number 40

3. I get same results with Blink client (timeout errors and identical tcpdump trace).
4. Asterisk server verbose logging is silent.

So 99% not a Baresip issue but rather me doing a mess with certificates. Solving that would be a nice and useful wiki page for future reference! Thanks again.

**Comment by Telefonorosso** [comment]
Hello!
After cleaning up the mess with certificates I'm getting NO ERRORS when testing Asterisk TLS with:

`openssl s_client -connect sip.pgpwaves.eu:5561 -cert client.pem -CAfile fullchain.pem`

as per attached file! [openssl-test.txt](https://github.com/alfredh/baresip/files/3982473/openssl-test.txt)
But still being kicked off at the first encrypted packet in the tcpdump trace!

**Comment by alfredh** [comment]
Can you please test 2-3 other SIP clients and try to determine if the problem
is on the Client side or the Server side ?

I think you should report this issue to the Asterisk Project.

**Comment by Telefonorosso** [comment]
Yes, I'll report to Asterisk and close this. How can I report back to you if needed? Thanks a lot.
