### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [alfredh/baresip#879]
I would like to point out that an identifier like “[`BARESIP_H__`](https://github.com/alfredh/baresip/blob/939740c1a9a37c99c7c94d1a5d0a109861a8a3d9/include/baresip.h#L7 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by alfredh** [comment]
is this a real problem for you, or is it just a theoretical problem?

so far the current code has compiled fine also for C++.

I doubt that C++ is using the keyword "BARESIP".

**Comment by elfring** [comment]
How do you [think about](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by alfredh** [comment]
please send a PR if you want to change the code.

I dont regard this as a super-important problem.
