### ISSUE TITLE
call: no common audio codecs - rejected

### ISSUE THREAD

**Issue by fapw** [alfredh/baresip#88]
Hello, dear colleagues.
Could you help me please.
I'm trying to make test call to baresip.
SIP server Asterisk 12.8.2 is running under Ubuntu 12.04.05. Have tested with sipML5 client - to -sipML5 client  in Chrome - works fine. But when I'm trying to call from sipML5 to baresip - I'm getting error : 
call: no common audio codecs - rejected
Is it problem with Asterisk, Ubuntu or baresip configuration? If required, can upload config files. 
Thank you very much.
Have a nice day.

**Comment by alfredh** [comment]
can you make a Wireshark trace of the SIP/SDP traffic ?

alternatively, please share the SDP offer and your Baresip account/config file.

**Comment by alfredh** [comment]
close due to lack of feedback

**Comment by meerd** [comment]
Dear @alfredh,

I have experienced the similar issue. When the server application is called through linphone
(iOS) client, I got "no common audio codecs -rejected" message. Please find attached config and account files. 

Thanks.

PS: I am sure all of the codecs are enabled on the client side.
---- 
baresip v0.5.0 Copyright (C) 2010 - 2016 Alfred E. Heggestad et al.
Local network address:  IPv4=eth0:192.168.1.103 
httpd: listening on 0.0.0.0:8000
aucodec: opus/48000/2
aucodec: AMR/8000/1
aucodec: L16/44100/2
aucodec: L16/32000/2
aucodec: L16/16000/2
aucodec: L16/8000/2
aucodec: L16/44100/1
aucodec: L16/32000/1
aucodec: L16/16000/1
aucodec: L16/8000/1
aucodec: speex/32000/2
aucodec: speex/16000/2
aucodec: speex/8000/2
aucodec: speex/32000/1
aucodec: speex/16000/1
aucodec: speex/8000/1
aufilt: vumeter
ausrc: alsa
auplay: alsa
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidcodec: VP8
vidcodec: VP9
vidsrc: x11grab
vidisp: x11
medianat: stun
medianat: turn
medianat: ice
Populated 1 account
Populated 3 contacts
Populated 16 audio codecs
Populated 1 audio filter
Populated 5 video codecs
Populated 0 video filters
baresip is ready.
1002@192.168.1.103: {0/TCP/v4} 200 OK () [1 binding]
All 1 useragent registered successfully! (1 ms)
call: no common audio codecs - rejected

[accounts.zip](https://github.com/alfredh/baresip/files/695396/accounts.zip)
[config.zip](https://github.com/alfredh/baresip/files/695397/config.zip)

**Comment by meerd** [comment]
[wireshark_dump.txt](https://github.com/alfredh/baresip/files/695424/wireshark_dump.txt)
