### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [alfredh/baresip#880]
I suggest to reuse a higher level build system than [your current make script](https://github.com/alfredh/baresip/blob/8c7cf7d47d0ffd42a1ba35b608fb420781c6501b/Makefile#L12 "Update candidate") so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/ "Building software with CMake")
- [Autotools](https://www.gnu.org/software/autoconf/autoconf.html#introduction "Building software with Autoconf")

**Comment by alfredh** [comment]
please read the answer here:

https://github.com/alfredh/baresip/issues/853
