### ISSUE TITLE
make EXTRA_MODULES=avcodec error!

### ISSUE THREAD

**Issue by yuexiajiayan** [alfredh/baresip#884]
i'm installd ffmpeg but i get baresip source make:
make EXTRA_MODULES=avcodec
/usr/bin/ld: build-arm6/modules/avcodec/sdp.o: in function `h264_fmtp_cmp':
/root/baresip/baresip/modules/avcodec/sdp.c:30: multiple definition of `h264_fmtp_cmp'; build-arm6/modules/avcodec/sdp.o:/root/baresip/baresip/modules/avcodec/sdp.c:30: first defined here
collect2: error: ld returned 1 exit status
make: *** [mk/mod.mk:36: avcodec.so] Error 1

i'm error in linux

**Comment by mrcasablr** [comment]
Try make USE_AVCODEC=1 RELEASE=1

I'm able to compile baresip with avcodec on RPi 4b

**Comment by alfredh** [comment]
the module avcodec should be auto-detected.

try to remove "EXTRA_MODULES=avcodec", and do just:

```
$ make
```

NOTE: please do some effort on your own, and try different things,
before posting for help here.
