### ISSUE TITLE
Unresponsive app after hangup

### ISSUE THREAD

**Issue by Telefonorosso** [alfredh/baresip#885]
Hello sir.
In a really clean, minimal Debian virtual machine installation I got Baresip "stuck" on the **_CALLED_** party at hangup.

With "stuck" I mean: I have to quit the menu by pressing "ctrl+z" and have to kill baresip with "kill -9".

Last debug line in the "stuck" console is:
`alsa: stopping playback thread (default)
`

The **_CALLING_** instance on the second virtual machine is OK.

It's a direct call test with no registering involved, started by pressing "d" and typing "call@192.168.1.187"

Disabling the alsa.so module results in no audio but no "hangs".
All relevant files are attached. Thank you and merry christmas!

`--- System info: ---
 Machine:  x86_64/linux
 Version:  0.6.5 (libre v0.6.1)
 Build:    64-bit little endian
 Kernel:   Linux debian 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64
 Uptime:   3 secs
 Started:  Sun Dec 22 05:48:26 2019
 Compiler: 8.3.0
`

[config-and-accounts.txt](https://github.com/alfredh/baresip/files/3992360/config-and-accounts.txt)
[install-steps.txt](https://github.com/alfredh/baresip/files/3992361/install-steps.txt)

**Comment by alfredh** [comment]
it is most likely stuck here: (waiting for the thread to exit)

```c
	/* Wait for termination of other thread */
	if (st->run) {
		debug("alsa: stopping playback thread (%s)\n", st->device);
		st->run = false;
		(void)pthread_join(st->thread, NULL);
	}
```

thread:

```c
		n = snd_pcm_writei(st->write, sampv, samples);
```

couple of ideas:

1. run baresip in gdb, and after the hang get a full backtrace for all threads:

`
(gdb) thread apply all bt
`

2. disable or uninstall pulseaudio, reboot, and use a pure ALSA environment.

3. add a call to `pthread_kill` before `pthread_join`

4. add a call to `snd_pcm_close` before `pthread_join`

5. use pulseaudio.so module instead

**Comment by Telefonorosso** [comment]
Hello and thank you.
Can't read C code, sorry!

> 2. disable or uninstall pulseaudio, reboot, and use a pure ALSA environment.

Pulseaudio is not installed, it is pure ALSA.

Doesn't hangs on Raspberry PI 3 armv7l and Asus EeePC i386.
I'll try to debug with GDB and report back. Thank you very much.

**Comment by alfredh** [comment]
I tried the same with Debian 9 running in VirtualBox.
The result is that the audio (ALSA) is working fine, and that the call
is hanged up fine (not stuck).

I think it is related to the audio driver and that some resource
is shared between recording and playback. When the recording thread
is stopped first, it does something in the driver that blocks the
playback thread from returning (just a hunch).

You can try to use different names for audio_source and audio_player,
for example:

```
audio_source alsa,plughw:0,0
audio_player alsa,plughw:0,1
```

some more questions for you:

1. which VM software are you using ?

2. can you get the output of `arecord -l`

you can also try to swap the order of stop_tx/rx in:

```c
void audio_stop(struct audio *a)
{
	if (!a)
		return;

	stop_tx(&a->tx, a);
	stop_rx(&a->rx);
}
```

**Comment by Telefonorosso** [comment]
VM software is Virtualbox 6.0.14. It provides 3 emulated audio controllers which I all tried out without success while dealing with this glitch:
- ICH AC97 (dafault)
- Intel HD Audio
-  Soundblaster 16

**With suggested **audio_source** and **audio_player** I get:**

`alsa: could not open auplay device 'plughw:0,0' (Device or resource busy)`
`audio: start_player failed (alsa.plughw:0,0): Unknown error -16`

**arecord -l returns:**

`**** List of CAPTURE Hardware Devices ****`
`card 0: I82801AAICH [Intel 82801AA-ICH], device 0: Intel ICH [Intel 82801AA-ICH]`
`  Subdevices: 1/1`
`  Subdevice #0: subdevice #0`
`card 0: I82801AAICH [Intel 82801AA-ICH], device 1: Intel ICH - MIC ADC [Intel 82801AA-ICH - MIC ADC]`
`  Subdevices: 1/1`
`  Subdevice #0: subdevice #474` 

Many thanks.

**Comment by alfredh** [comment]
my device was only
an example :)

you should use the
correct alsa device, try all
until it works

are you really sure
there is no pulseaudio involved?
Debian uses pulse and you
said «clean install»

i am waiting for
the gdb bt from you

**Comment by Telefonorosso** [comment]
Hello sir.
Since Virtual machine was used only for testing and on physical machines the issue is not present I am closing this.
In **debian-10.2.0-amd64-netinst** Pulseaudio is not present.
Thank you very much for helping out and happy new year!
[closing.txt](https://github.com/alfredh/baresip/files/4012837/closing.txt)

**Comment by alfredh** [comment]
I tested again with Debian 10 on VM and Physical machine:

1. VM (VirtualBox) -- hangs
2. Physical machine -- no hang

in anycase a workaround is to call `snd_pcm_drop` before `pthread_join`.

**Comment by Telefonorosso** [comment]
Thank you. Sorry, the workaround have to be made in alsa.c or main.c?
Cheers
