### ISSUE TITLE
Audio Glitches with Opus/Jack

### ISSUE THREAD

**Issue by AaronHorn** [alfredh/baresip#886]
Hello,

I am trying to create a simple way for remote broadcasters to be able to utilise audio software at a radio station.  The playout system is Rivendell which talks to jack running in promiscious mode.

I am using stereo opus at 96kbps.  My client is linphone on the Mac.  I am making a direct connection between linphone by dialing sip:user@baresiphost

Jack is running with the current paramters: /bin/jackd -d alsa -d hw:0 -r48000 -p1024 -n3 The soundcard is a M-Audio Delta 1010 so is capable of running much lower frames etc.

I am not seeing xruns in qjackctl.

I have tried various iterations of settings, including poll vs. thread, fec on/off.  I have also played with buffers etc, it doesn't seem to make much difference.

The problem is that I am hearing occasional 'clicks'.  To my ear they sound like digital clips (but the input is patched directly to the software output with the music normalised to -13dBFS) or slight timing glitches (like where you have two sound cards whose clocks aren't synced).

I've tried over LAN (currently trying to get it working across a OpenVPN tunnel) - doesn't appear to be a network problem - very minimal lost packets (perhaps 5-10 in an 20 minute test run, yet clicking every 10-30 seconds).

The only thing I've noticed is that it appears to sound 'worse' when the audio is more complex (e.g. music).  Also where you get the cmd-line VU meter, when you get a click, the cursor between the incoming and outgoing bars appears to flicker (like it's slowing down between redraws).

I run jack in realtime but I can't tell if baresip runs as a realtime client for jack.

Config file for the best working version:

#
# baresip configuration
#

#------------------------------------------------------------------------------

# Core
poll_method		epoll		# poll, select, epoll ..

# SIP
sip_listen		XXXX:5060
#sip_certificate	cert.pem
#sip_cafile		/etc/ssl/certs/ca-certificates.crt

# Call
call_local_timeout	120
call_max_calls		4

# Audio
#audio_path		/usr/local/share/baresip
audio_player		jack
audio_source		jack
audio_alert		jack
ausrc_srate		48000
auplay_srate		48000
ausrc_channels		2
auplay_channels		2
audio_txmode		poll		# poll, thread
audio_level		yes
ausrc_format		float		# s16, float, ..
auplay_format		float		# s16, float, ..
auenc_format		float		# s16, float, ..
audec_format		float		# s16, float, ..
audio_buffer            1-100          # ms

# Video
#video_source		v4l2,/dev/video0
#video_display		x11,nil
video_size		352x288
video_bitrate		500000
video_fps		25.00
video_fullscreen	no
videnc_format		yuv420p

# AVT - Audio/Video Transport
rtp_tos			184
#rtp_ports		10000-20000
#rtp_bandwidth		512-1024 # [kbit/s]
rtcp_mux		no
jitter_buffer_delay	5-10		# frames
rtp_stats		yes
#rtp_timeout		60

# Network
net_prefer_ipv6		no
#dns_server		1.1.1.1:53
#dns_server		1.0.0.1:53
net_interface		tun0

#------------------------------------------------------------------------------
# Modules

module_path		/usr/local/lib/baresip/modules

# UI Modules
module			stdio.so
#module			cons.so
#module			evdev.so
#module			httpd.so

# Audio codec Modules (in order)
module			opus.so
#module			amr.so
#module			g7221.so
#module			g722.so
#module			g726.so
#module			g711.so
#module			gsm.so
#module			l16.so
#module			mpa.so
#module			codec2.so
#module			ilbc.so
#module			isac.so

# Audio filter Modules (in encoding order)
module			vumeter.so
#module			sndfile.so
#module			speex_pp.so
#module			plc.so
#module			webrtc_aec.so

# Audio driver Modules
#module			alsa.so
#module			pulse.so
module			jack.so
#module			portaudio.so
#module			aubridge.so
#module			aufile.so

# Video codec Modules (in order)
#module			avcodec.so
#module			vp8.so
#module			vp9.so

# Video filter Modules (in encoding order)
#module			selfview.so
#module			snapshot.so
#module			swscale.so
#module			vidinfo.so

# Video source modules
#module			v4l2.so
#module			v4l2_codec.so
#module			avformat.so
#module			x11grab.so
#module			cairo.so
#module			vidbridge.so

# Video display modules
#module			directfb.so
#module			x11.so
#module			sdl.so
#module			fakevideo.so

# Audio/Video source modules
#module			rst.so
#module			gst.so
#module			gst_video.so

# Media NAT modules
#module			stun.so
#module			turn.so
#module			ice.so
#module			natpmp.so
#module			pcp.so

# Media encryption modules
#module			srtp.so
#module			dtls_srtp.so
#module			zrtp.so

#------------------------------------------------------------------------------
# Temporary Modules (loaded then unloaded)

module_tmp		uuid.so
module_tmp		account.so

#------------------------------------------------------------------------------
# Application Modules

module_app		auloop.so
#module_app		b2bua.so
module_app		contact.so
module_app		debug_cmd.so
#module_app		dtmfio.so
#module_app		echo.so
#module_app		gtk.so
module_app		menu.so
#module_app		mwi.so
#module_app		presence.so
#module_app		syslog.so
#module_app		mqtt.so
#module_app		ctrl_tcp.so
module_app		vidloop.so

#------------------------------------------------------------------------------
# Module parameters

# UI Modules parameters
cons_listen		0.0.0.0:5555 # cons

http_listen		0.0.0.0:8000 # httpd - server

ctrl_tcp_listen		0.0.0.0:4444 # ctrl_tcp

evdev_device		/dev/input/event0

# Opus codec parameters
opus_bitrate		96000 # 6000-510000
opus_stereo		yes
opus_sprop_stereo	yes
opus_cbr		yes
opus_inbandfec		no
#opus_dtx		no
#opus_mirror		no
opus_complexity		10
opus_application	audio	# {voip,audio}
opus_samplerate		48000
#opus_packet_loss	10	# 0-100 percent

# Opus Multistream codec parameters
#opus_ms_channels	2	#total channels (2 or 4)
#opus_ms_streams		2	#number of streams
#opus_ms_c_streams	2	#number of coupled streams

vumeter_stderr		yes

# Selfview
video_selfview		window # {window,pip}
#selfview_size		64x64

# ICE
ice_turn		no
ice_debug		no
ice_nomination		regular	# {regular,aggressive}

# ZRTP
#zrtp_hash		no  # Disable SDP zrtp-hash (not recommended)

# Menu
#menu_bell		yes
#redial_attempts	0 # Num or <inf>
#redial_delay		5 # Delay in seconds
#ringback_disabled	no
#statmode_default	off

# avcodec
#avcodec_h264enc	libx264
#avcodec_h264dec	h264
#avcodec_h265enc	libx265
#avcodec_h265dec	hevc
#avcodec_hwaccel	vaapi

# mqtt
#mqtt_broker_host	127.0.0.1
#mqtt_broker_port	1883
#mqtt_broker_clientid	baresip01
#mqtt_broker_user	user
#mqtt_broker_password	pass
#mqtt_basetopic		baresip/01

# sndfile
#snd_path		/tmp

Output from a test run:

[rd@rdplayout1 ~]$ baresip -v
baresip v0.6.5 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.
Binding to interface or IP address 'tun0'
net: tun0: could not get IPv6 address (No such device)
Local network address:  IPv4=tun0|XXXX
ui: stdio
opus: fmtp="stereo=1;sprop-stereo=1;maxaveragebitrate=96000;cbr=1;useinbandfec=0"
aucodec: opus/48000/2
aufilt: vumeter
auplay: jack
ausrc: jack
uuid: loaded UUID XXXX from file /home/rd/.baresip/uuid
Populated 1 account
module: loading app auloop.so
module: loading app contact.so
Populated 3 contacts
module: loading app debug_cmd.so
module: loading app menu.so
module: loading app vidloop.so
Populated 1 audio codec
Populated 1 audio filter
Populated 0 video codecs
Populated 0 video filters
baresip is ready.
ua: sipsess connect via UDP XXXX:5060 --> XXXX:5060
call: alloc with params laddr=XXXX, af=AF_INET, use_rtp=1
call: use_video=0
answering call from sip:aaron@XXXX with 200
call: update media
stream: update 'audio'
stream: audio: starting RTCP with remote XXXX:7079
audio: Set audio decoder: opus 48000Hz 2ch
audio: start
audio: create recv buffer [1 - 100 ms] [384 - 38400 bytes]
jack: play 48000Hz,2ch
jack: engine sample rate: 48000 max_frames=1024
jack: sampc=2048
audio: player started with sample format FLOAT
audio: Set audio encoder: opus 48000Hz 2ch
opus: encoder fmtp (useinbandfec=1)
audio: start
jack: unique name `baresip-01' assigned
jack: engine sample rate: 48000 max_frames=1024
jack: source sampc=2048
audio: source started with sample format FLOAT
audio tx pipeline:        jack ---> vumeter ---> opus
audio rx pipeline:        jack <--- vumeter <--- opus
call: stream start (active=1)
opus: encoder fmtp (useinbandfec=1)
audio: start
studio@XXX: Call established: sip:aaron@XXXX
stream: incoming rtp for 'audio' established, receiving from XXXX:7078
[0:03:01] audio=95586/80000 (bit/s)                         [=========       ]  [                ]
--- Audio stream ---
 tx:   encode: opus 48000Hz/2ch ptime=20ms FLOAT
       aubuf: wish_sz=7680 cur_sz=2560 filling=0 (cur 6.66ms, max 600.00ms, or 0, ur 0)
       source: jack, FLOAT
       time = 181.539 sec
 rx:   decode: opus 48000Hz/2ch FLOAT
       aubuf: wish_sz=384 cur_sz=22528 filling=0 (cur 58.66ms, max 100.00ms, or 2, ur 8)
       player: jack, FLOAT
       n_discard:0
       time = 180.800 sec
 audio tx pipeline:        jack ---> vumeter ---> opus
 audio rx pipeline:        jack <--- vumeter <--- opus
 audio dir=sendrecv pt_enc=96
 local: 0.0.0.0:17126, remote: XXXX:7078/XXXX:7079
 mnat: (none) (connected=no)
 menc: (none) (secure=no)
RTP debug:
 Encode: seq=20567 ssrc=0xdc4441eb
----- RTCP Session: -----
  cname=sip:studio@XXXX SSRC=XXXX/XXXX rx=48000Hz
  member XXXX: lost=2 Jitter=5.0ms RTT=32.1ms
                 IP=XXXX:7078 psent=9008 rcvd=9046
  TX: packets=9077, octets=2187679
--- jitter buffer debug---
 running=1 min=5 cur=5 max=10 [frames]
 seq_put=9045
 Stat: put=9046 get=9046 oos=0 dup=0 late=0 or=0 ur=5 flush=0       put/get_ratio=100% lost=0 (0.00%)

[0:03:22] audio=96877/79466 (bit/s)                         [=========       ]  [                ]
===== Call debug (ESTABLISHED) =====
 local_uri:  <sip:studio@XXXX>
 peer_uri:   <sip:aaron@XXXX>
 af=AF_INET id=XXXX
 direction: Incoming
SDP session
  local attributes:
    tool='baresip 0.6.5'
  remote attributes:
    rtcp-xr='rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics'
session media:
audio RTP/AVP
  local formats:
     96 opus/48000/2 (stereo=1;sprop-stereo=1;maxaveragebitrate=96000;cbr=1;useinbandfec=0) *
    101 telephone-event/8000/1 (0-15)
  remote formats:
     96 opus/48000/2 (useinbandfec=1) *
    101 telephone-event/48000/1
  local attributes:
    label='1'
    ssrc='XXXX cname:sip:studio@XXXX'
    minptime='20'
    ptime='20'
  remote attributes:
    rtcp-fb='* trr-int 5'
    rtcp-fb='* ccm tmmbr'
local media:

--- sip:studio@XXXXX ---t/s)
 nrefs:     1
 cuser:     studio-XXXX
 pub-gruu:  
 af:        AF_INET
 Supported: gruu

Account:
 address:      <sip:studio@XXXXX>;auth_pass=none;regint=0;answermode=auto
 luri:         sip:studio@XXXX
 aor:          sip:studio@XXXX
 dispname:     
 answermode:   auto
 auth_user:    
 mediaenc:     none
 medianat:     none
 mwi:          yes
 ptime:        20
 regint:       0
 pubint:       0
 regq:         
 sipnat:       
 stunserver:   stun:studio@XXXX:0
 call_transfer:         yes
 extra:         none
sip:aaron@XXXXX: session closed: Connection reset by peer
jack: source destroy
jack: destroy
sip:studio@XXXX: Call with sip:aaron@XXXX terminated (duration: 4 mins 3 secs)
audio: destroyed (started=1)

audio           Transmit:     Receive:
packets:          12173        12142
avg. bitrate:      96.3         79.9  (kbit/s)
errors:               0            0
pkt.report:       12044        12014
lost:                 2            0
jitter:             4.7          6.2  (ms)

**Comment by Telefonorosso** [comment]
Hello sir.
Had a similar problem here.
Test your (nice!) setup with Opus mono:

> opus_stereo no
> opus_sprop_stereo no

**Comment by AaronHorn** [comment]
> Hello sir.
> Had a similar problem here.
> Test your (nice!) setup with Opus mono:
> 
> > opus_stereo no
> > opus_sprop_stereo no

Hello,

Strangely enough I had cause to try this around the same time you posted.  It does sound better but I can still hear the occasional click.  Summon both L/R into one input also seems to sound bad as well.

Hmmm

**Comment by alfredh** [comment]
it could be a drift in
clock rates

if you can assist with testing,
I can add some extra debug/stats

**Comment by AaronHorn** [comment]
> it could be a drift in
> clock rates
> 
> if you can assist with testing,
> I can add some extra debug/stats

Definitely sounds 'clocky'.  I can rebuild from git etc, just let me know what you need.

**Comment by alfredh** [comment]
is the click sound on the receive/decode path ?


your receive aubuf has overruns and underruns:

```
aubuf: wish_sz=384 cur_sz=22528 filling=0 (cur 58.66ms, max 100.00ms, or 2, ur 8)
```

this could be one reason for the "click" sound.

if you want to correlate the audible "click" sound and aubuf or/ur, you can enable
the debug logging in audio.c:

line 619:

```c
	if (rx->aubuf_started && aubuf_cur_size(rx->aubuf) < num_bytes) {

		++rx->stats.aubuf_underrun;

#if 0
		debug("audio: rx aubuf underrun (total %llu)\n",
		      rx->stats.aubuf_underrun);
#endif
	}
```

line 800:

```c
	if (aubuf_cur_size(rx->aubuf) >= rx->aubuf_maxsz) {

		++rx->stats.aubuf_overrun;

#if 0
		debug("audio: rx aubuf overrun (total %llu)\n",
		      rx->stats.aubuf_overrun);
#endif
	}
```

**Comment by alfredh** [comment]
can you please test the latest version from git, using the `auloop` module?

configure your preferred audio module/device, and start the audio-loop.
let it run for a long time, at least 5 minutes.

examples from Debian 10 with alsa:

```
$ ./baresip -e "/auloop 48000 1" -t 300

~~~~~ Audioloop summary: ~~~~~
48000 Hz 1ch S16LE

* Source
  module      rst
  samples     14402880
  duration    300.060 sec
  frames      15003 (avg ptime 20.00ms)

* Aubuf
  overrun     0
  underrun    0

* Player
  module      alsa
  samples     14405760
  duration    300.120 sec
  frames      15006 (avg ptime 20.00ms)
```


if everything is normal, the audio buffer should have zero overrun/underrun,
and the duration of source and player should be almost equal.

this test is used to verify the audio hardware.

**Comment by AaronHorn** [comment]
OK, on it now!

**Comment by AaronHorn** [comment]
So I enabled the debug lines.  I see several underuns but these are near the start of the call (interestingly, it sounds like the music I'm playing is artificially being slowed down and then returning to normal speeds).  It's not being to clicky today but the clicks I could hear didn't seem to be generating underun events:

[XX@XXX1 ~]$ baresip -v
baresip v0.6.5 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.
Binding to interface or IP address 'tun0'
net: tun0: could not get IPv6 address (No such device)
Local network address:  IPv4=tun0|XXXX
ui: stdio
opus: fmtp="stereo=1;sprop-stereo=1;maxaveragebitrate=96000;cbr=1;useinbandfec=1"
aucodec: opus/48000/2
auplay: jack
ausrc: jack
uuid: loaded UUID XXXX from file /home/XX/.baresip/uuid
Populated 1 account
module: loading app auloop.so
module: loading app contact.so
Populated 3 contacts
module: loading app debug_cmd.so
module: loading app menu.so
module: loading app vidloop.so
Populated 1 audio codec
Populated 0 audio filters
Populated 0 video codecs
Populated 0 video filters
baresip is ready.
ua: sipsess connect via UDP XXXX:5060 --> XXXX:5060
call: alloc with params laddr=XXXX, af=AF_INET, use_rtp=1
call: use_video=0
answering call from sip:aaron@XXXX with 200
call: update media
stream: update 'audio'
stream: audio: starting RTCP with remote XXXX:7079
audio: Set audio decoder: opus 48000Hz 2ch
audio: start
audio: create recv buffer [1 - 100 ms] [384 - 38400 bytes]
jack: play 48000Hz,2ch
jack: engine sample rate: 48000 max_frames=1024
jack: sampc=2048
audio: player started with sample format FLOAT
audio: Set audio encoder: opus 48000Hz 2ch
opus: encoder fmtp (useinbandfec=1)
audio: start
jack: unique name `baresip-01' assigned
jack: engine sample rate: 48000 max_frames=1024
jack: source sampc=2048
audio: source started with sample format FLOAT
audio tx pipeline:        jack ---> opus
audio rx pipeline:        jack <--- opus
call: stream start (active=1)
opus: encoder fmtp (useinbandfec=1)
audio: start
studio@XXXX: Call established: sip:aaron@XXXX
stream: incoming rtp for 'audio' established, receiving from XXXX:7078
audio: rx aubuf underrun (total 1)
audio: rx aubuf underrun (total 2)
audio: rx aubuf underrun (total 3)
audio: rx aubuf underrun (total 4))    
terminated by signal 280000 (bit/s)    
ua: stop all (forced=0)
sip:studio@XXXX: Call with sip:aaron@XXXX terminated (duration: 4 mins 21 secs)
jack: source destroy
jack: destroy
audio: destroyed (started=1)

audio           Transmit:     Receive:
packets:          13050        13006
avg. bitrate:      96.3         79.9  (kbit/s)
errors:               0            0
pkt.report:       12914        12870
lost:                 0            0
jitter:             5.6          3.1  (ms)
ua: sip-stack exit
ua exited -- stopping main runloop
module: unloading app vidloop
module: unloading app menu
menu: close (redial current_attempts=0)
module: unloading app debug_cmd
module: unloading app contact
module: unloading app auloop
main: unloading modules..


I then ran the test you suggest.  It appears somewhat inconclusive to me:

[XX@XXXX1 ~]$ baresip -v -e "/auloop 48000 1" -t 300
baresip v0.6.5 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.
Binding to interface or IP address 'tun0'
net: tun0: could not get IPv6 address (No such device)
Local network address:  IPv4=tun0|XXXX
ui: stdio
opus: fmtp="stereo=1;sprop-stereo=1;maxaveragebitrate=96000;cbr=1;useinbandfec=1"
aucodec: opus/48000/2
auplay: jack
ausrc: jack
uuid: loaded XXXX from file /home/XX/.baresip/uuid
Populated 1 account
module: loading app auloop.so
module: loading app contact.so
Populated 3 contacts
module: loading app debug_cmd.so
module: loading app menu.so
module: loading app vidloop.so
Populated 1 audio codec
Populated 0 audio filters
Populated 0 video codecs
Populated 0 video filters
baresip is ready.
/auloop 48000 1
Audio-loop: 48000Hz, 1ch, FLOAT
jack: play 48000Hz,1ch
jack: engine sample rate: 48000 max_frames=1024
jack: sampc=1024
jack: unique name `baresip-01' assigned
jack: engine sample rate: 48000 max_frames=1024
jack: source sampc=1024
ua: stop all (forced=0)ad=299.989 n_write=300.031 rw_delay=-0.042 [sec] rw_ratio=0.999857          
ua: sip-stack exit
ua exited -- stopping main runloop
module: unloading app vidloop
module: unloading app menu
menu: close (redial current_attempts=0)
module: unloading app debug_cmd
module: unloading app contact
module: unloading app auloop
~~~~~ Audioloop summary: ~~~~~
48000 Hz 1ch FLOAT

jack: source destroy
* Source
  module      jack
  samples     14400512
  duration    300.010 sec
  frames      14063 (avg ptime 21.33ms)

* Aubuf
  overrun     0
  underrun    1

jack: destroy
* Player
  module      jack
  samples     14404608
  duration    300.096 sec
  frames      14067 (avg ptime 21.33ms)


main: unloading modules..



I'm going to try running everything as root in case that makes any difference (since I'm using jack in promiscious mode)

**Comment by alfredh** [comment]
thanks, the auloop test shows that your audio hardware is working properly.
the stream duration is around 300 seconds for both source and playback,
which is very close to the realtime duration. JACK is also known for being
a very high-precision quality software.

could you please clarify if your problem is:

1. on the send/encode path (i.e. from baresip to X) or
2. on the recv/decode path (i.e. from X to baresip).

NOTE: baresip does not try to speed up/down the audio in any way.

**Comment by AaronHorn** [comment]
So my setup:

M-Audio Delta 1010 (very good soundcard with lots of linux support) being exclusively controlled by jack (running under user privileges in promiscious mode).

Audio comes in from real-world source and is patched to baresip as above.  Baresip is encoding the audio and when I'm playing it back on my Mac with Linphone, I am experiencing the artefacts as described.

I did try baresip<-pulse<-jack<-alsa but that also seemed to have the same problems.  I can't really do alsa->baresip in this setup as I need the virtual routing.

I think the 'slowing down' is happening as linphone starts to decode packets as soon as it receives them - once it has enough opus data it starts to make sense and plays at the correct speed.  I then just get clicks which sound like they're being caused by dropped samples.

I can try to make a screen recording if that helps?

**Comment by AaronHorn** [comment]
FML...

This appears to be an issue with linphone.  I installed baresip from git on my Mac OS client.  I have great audio with no audible clips.

When I was running linphone, I was seeing lines like this in the stdout:

[Warning]Core:linphone: Flow controlled bufferizer of max 40 ms was filled with at least 43 ms in the last 5000 ms, asking to drop 3 ms

and

[Warning]Core:linphone: Too much buffered audio signal, throwing out 19 ms

I'll take this up with the linphone people (but they aren't very responsive from what I've seen).

Sorry to waste your time!

**Comment by alfredh** [comment]
I think you should double check the duration of the outgoing stream from baresip.
if the duration roughly matches the wall-clock time, and there is no packet loss,
then the outgoing stream should be in good shape.

example with 60 seconds session:

```
$ ./baresip -edmusic -t 60
```

after the session is done:

```
 tx:   encode: PCMU 8000Hz/1ch ptime=20ms S16LE
       aubuf:  (cur 0.00ms, max 600.00ms, or 0, ur 2)
       source: none,default S16LE
       time = 59.659 sec
```

you should try with longer session times, e.g. 10 or 30 minutes so that the
initial setup delay has a less portion. Or you can use a stopwatch.

**Comment by alfredh** [comment]
I will close this ticket now, feel free to reopen if the bug is still there.
