### ISSUE TITLE
Compilation baresip-webrtc in OpenWrt

### ISSUE THREAD

**Issue by ZigFisher** [alfredh/baresip#887]
Good afternoon.
To start, I apologize.
I did not find how to ask questions in the baresip-webrtc repository.

I try to build baresip-webrtc and it fails.
Libraries and programs re-0.6.1 rem-0.6.0 baresip-0.6.5 are assembled without problems. Development environment .h files are also written wherever needed. Unfortunately, I can’t understand what else is needed for the assembly. I ask for tips, thanks.

**Comment by ZigFisher** [comment]
> make[3]: Entering directory '/mnt/raid/OpenWrt/OpenIPC/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/baresip-webrtc-0.6.0-c83d2e09feca34c666f7c5878ccd89bd2ec4163b'
  CC      build-arm/src/main.o
  CC      build-arm/src/session.o
src/session.c: In function 'destructor':
src/session.c:92:8: warning: implicit declaration of function 'stream_name' [-Wimplicit-function-declaration]
        media->ix, stream_name(media_get_stream(media)));
        ^
src/session.c:92:8: warning: nested extern declaration of 'stream_name' [-Wnested-externs]
src/session.c:112:4: warning: implicit declaration of function 'video_stop' [-Wimplicit-function-declaration]
    video_stop(media->u.vid);
    ^
src/session.c:112:4: warning: nested extern declaration of 'video_stop' [-Wnested-externs]
src/session.c: In function 'rtcsession_create':
src/session.c:376:7: warning: passing argument 4 of 'menc->sessh' from incompatible pointer type [enabled by default]
       menc_error_handler, sess);
       ^
src/session.c:376:7: note: expected 'void (*)(enum menc_event,  const char *, void *)' but argument is of type 'void (*)(enum menc_event,  const char *, struct stream *, void *)'
src/session.c: In function 'rtcsession_add_audio':
src/session.c:429:6: warning: ISO C forbids passing argument 17 of 'audio_alloc' between function pointer and 'void *' [-Wpedantic]
      audio_err_handler, sess);
      ^
In file included from src/session.c:9:0:
/mnt/raid/OpenWrt/OpenIPC/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/usr/include/baresip/baresip.h:1137:5: note: expected 'void *' but argument is of type 'void (*)(int,  const char *, void *)'
 int audio_alloc(struct audio **ap, struct list *streaml,
     ^
src/session.c:429:6: error: too many arguments to function 'audio_alloc'
      audio_err_handler, sess);
      ^
In file included from src/session.c:9:0:
/mnt/raid/OpenWrt/OpenIPC/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/usr/include/baresip/baresip.h:1137:5: note: declared here
 int audio_alloc(struct audio **ap, struct list *streaml,
     ^
src/session.c:440:9: warning: passing argument 3 of 'stream_set_session_handlers' from incompatible pointer type [enabled by default]
         stream_error_handler, media);
         ^
In file included from src/session.c:9:0:
/mnt/raid/OpenWrt/OpenIPC/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/usr/include/baresip/baresip.h:1214:6: note: expected 'void (*)(struct stream *, int,  void *)' but argument is of type 'void (*)(struct stream *, void *)'
 void stream_set_session_handlers(struct stream *strm,
      ^
src/session.c:440:9: warning: ISO C forbids passing argument 4 of 'stream_set_session_handlers' between function pointer and 'void *' [-Wpedantic]
         stream_error_handler, media);
         ^
In file included from src/session.c:9:0:
/mnt/raid/OpenWrt/OpenIPC/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/usr/include/baresip/baresip.h:1214:6: note: expected 'void *' but argument is of type 'void (*)(struct stream *, struct rtcp_msg *, void *)'
 void stream_set_session_handlers(struct stream *strm,
      ^
src/session.c:440:9: error: too many arguments to function 'stream_set_session_handlers'
         stream_error_handler, media);
         ^
In file included from src/session.c:9:0:
/mnt/raid/OpenWrt/OpenIPC/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/usr/include/baresip/baresip.h:1214:6: note: declared here
 void stream_set_session_handlers(struct stream *strm,
      ^
src/session.c: In function 'rtcsession_add_video':
src/session.c:469:2: warning: implicit declaration of function 'video_alloc' [-Wimplicit-function-declaration]
  err = video_alloc(&media->u.vid, &sess->streaml,
  ^
src/session.c:469:2: warning: nested extern declaration of 'video_alloc' [-Wnested-externs]
src/session.c:489:9: warning: passing argument 3 of 'stream_set_session_handlers' from incompatible pointer type [enabled by default]
         stream_error_handler, media);
         ^
In file included from src/session.c:9:0:
/mnt/raid/OpenWrt/OpenIPC/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/usr/include/baresip/baresip.h:1214:6: note: expected 'void (*)(struct stream *, int,  void *)' but argument is of type 'void (*)(struct stream *, void *)'
 void stream_set_session_handlers(struct stream *strm,
      ^
src/session.c:489:9: warning: ISO C forbids passing argument 4 of 'stream_set_session_handlers' between function pointer and 'void *' [-Wpedantic]
         stream_error_handler, media);
         ^
In file included from src/session.c:9:0:
/mnt/raid/OpenWrt/OpenIPC/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/usr/include/baresip/baresip.h:1214:6: note: expected 'void *' but argument is of type 'void (*)(struct stream *, struct rtcp_msg *, void *)'
 void stream_set_session_handlers(struct stream *strm,
      ^
src/session.c:489:9: error: too many arguments to function 'stream_set_session_handlers'
         stream_error_handler, media);
         ^
In file included from src/session.c:9:0:
/mnt/raid/OpenWrt/OpenIPC/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/usr/include/baresip/baresip.h:1214:6: note: declared here
 void stream_set_session_handlers(struct stream *strm,
      ^
src/session.c: In function 'rtcsession_start_video':
src/session.c:651:3: warning: implicit declaration of function 'video_encoder_set' [-Wimplicit-function-declaration]
   err  = video_encoder_set(vid, vc, sc->pt, sc->params);
   ^
src/session.c:651:3: warning: nested extern declaration of 'video_encoder_set' [-Wnested-externs]
src/session.c:658:3: warning: implicit declaration of function 'video_start' [-Wimplicit-function-declaration]
   err = video_start(vid, NULL);
   ^
src/session.c:658:3: warning: nested extern declaration of 'video_start' [-Wnested-externs]
Makefile:57: recipe for target 'build-arm/src/session.o' failed
make[3]: *** [build-arm/src/session.o] Error 1

**Comment by alfredh** [comment]
have you tried to compile this on a desktop OS ?

latest baresip-webrtc needs latest version of baresip from GIT.

**Comment by ZigFisher** [comment]
Good day, sir
Yes, i update baresip and lib's to last version
Ok, i probe build on a desktop OS and write report
Now i build it on a OpenWrt SDK
Thank you !
