### ISSUE TITLE
Program running crash in win10

### ISSUE THREAD

**Issue by 75535552** [alfredh/baresip#890]
hello sir.
I used VS2015 to run this program, and it crashed during a video call
and the backtrace as fallows.

>	0d4f4590() 	
 	wdmaud.drv!60c68aa8()	
 	wdmaud.drv!60c67f4e()	
 	wdmaud.drv!60c677fe()	
 	wdmaud.drv!60c6769c()

**Comment by alfredh** [comment]
this is most likely a duplicate of https://github.com/alfredh/baresip/issues/888

**Comment by 75535552** [comment]
ok
