### ISSUE TITLE
when both IPv4 and 6 address is available, baresip should be able to use both of them

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#897]
See http://lists.creytiv.com/pipermail/re-devel/2020-January/001480.html.

**Comment by alfredh** [comment]
Call from A to B, what is the resulting AF for media (please fill in the blanks):

```
| A/B Matrix  | B IPv4-only | B IPv6-only | B Dualstack |
| ----------- | ----------- | ----------- | ----------- |
| A IPv4-only | IPv4        | n/a         | ?           |
| A IPv6-only | n/a         | IPv6        | ?           |
| A Dualstack | ?           | ?           | ?           |
```

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I think the current code needs to be properly cleaned up
> regarding IPv6 and dualstack. There are many things to improve.
> 
> Are there any public SIP Servers that supports IPv6 ?

I don't know about public ones, but mine (to which you have account)
does support IPv6.

On the road where my mobile network operator does not support IPv6, I
set up for testing IPv6/IPv4 WiFi hotspot on my Linux laptop that also
has SIP Proxy.

**Comment by juha-h** [comment]
Here are results for the case where both A and B are dualstack:
```
a=dualstack net_prefer_ipv6=no
b=duastack  net_prefer_ipv6=no
offered media AF = IPv4 (accepted)

a=dualstack net_prefer_ipv6=yes
b=duastack  net_prefer_ipv6=no
offered media AF = IPv6 (rejected)

a=dualstack net_prefer_ipv6=no
b=duastack  net_prefer_ipv6=yes
offered media AF = IPv4 (rejected)

a=dualstack net_prefer_ipv6=yes
b=duastack  net_prefer_ipv6=yes
offered media AF = IPv6 (accepted)
```
My 9.0 Android One device does not support IPv6 only stack.  There must always be at least IPv4 available.

**Comment by alfredh** [comment]
we should agree on the expected behaviour first.

for example, what is the resulting address family for RTP when:

1. A is Dualstack, B is IPv6-only
2. A is IPv6-only, B is Dualstack

**Comment by juha-h** [comment]
Dualstack baresip UAS should accept the offered media AF (in case (2) it would be IPv6).

In case (1), A and B can use ICE negotiation (or the new alt address SDP attribute) to determine that IPv6 should be used as media AF.  If neither is available, A would default to IPv4 media AF and the INVITE would not be accepted by B.

**Comment by alfredh** [comment]
here is my work-in-progress branch:

https://github.com/alfredh/baresip/tree/network_improve_dualstack

**Comment by juha-h** [comment]
Thanks, will test during the next couple of days.

**Comment by juha-h** [comment]
I did some tests.  Network of baresip is configured like this:
```
01-20 18:46:19.815 25918 25965 D Baresip Lib: Local network address:  IPv4=wlan0|10.42.0.214 
01-20 18:46:19.815 25918 25964 D Baresip Lib: setting IPv4 address 10.42.0.214
01-20 18:46:19.815 25918 25964 D Baresip Lib: setting IPv6 address 2001:db8:0:1:8cc0:36cd:3ab5:b0dc
01-20 18:46:19.815 25918 25964 D Baresip Lib: setting address family AF_INET6
01-20 18:46:19.816 25918 25964 D Baresip Lib: --- Network debug ---
01-20 18:46:19.816 25918 25964 D Baresip Lib:  Local IPv4:  wlan0|10.42.0.214
01-20 18:46:19.816 25918 25964 D Baresip Lib:  Local IPv6:  ???|2001:db8:0:1:8cc0:36cd:3ab5:b0dc
```
The addresses are set with net_set_address calls and address family with
net_set_af call.

Observations:

(1) Registering of a UA works OK if its outbound proxy has IPv6 address,
but fails if its outbound proxy has IPv4 address:
```
01-20 18:03:47.452 24249 24295 D Baresip Lib: ua event (REGISTER_FAIL) Protocol not supported
```
(2) Incoming call with IPv6 media AF works OK.

(3) Incoming call with IPv4 media AF works, but there is (I think
unnecessary) error message:
```
01-20 18:08:51.108 24249 24297 D Baresip Lib: ua: using AF from sdp offer: af=AF_INET
01-20 18:08:51.108 24249 24297 D Baresip Lib: ua: SDP offer AF not supported (AF_INET)
01-20 18:08:51.108 24249 24297 D Baresip Lib: call: alloc with params laddr=10.42.0.214, af=AF_INET, use_rtp=1
```
Regarding (1) it would be nice if net_set_af would only indicate the
preferred SIP AF if both are available so that some of the UAs could use
IPv4 SIP AF and some others IPv6 SIP AF.

**Comment by alfredh** [comment]
the information about dualstack preference is spread across
multiple subsystems:

1. network (global)
2. ua
3. call


for example for the SIP stack (ua) in a dualstack configuration,
it is not easy to indicate local preference. this information comes
from the SIP domain via SRV records.

the most important place to indicate preferred AF is for
a call (outgoing) and which AF to use for SDP/RTP.
perhaps this information can be extracted from the
result of the SIP registration process.

I am wondering if we should move the preferred UA config
to struct ua/struct account, and have it configurable per account
with the following options:

af_media = IPv4|IPv6|auto

**Comment by juha-h** [comment]
Looks like we agree.

When UA sends a request, its SIP AF is based on the IP address of the destination.  If destination is domain name and DNS query results in both IPv4 and IPv6 addresses with equal priority, then it should not matter which one is chosen.  Thus there is no need configure UA's SIP AF.

Regarding media AF, if ICE negotiation does not succeed, then UAs preferred AF (based on UA's af_media) is used.

**Comment by alfredh** [comment]
yes, agree

please take a look at commit 5bd1b823ebb43d17bd54cfa334855bdd5d454a42

1. remove preferred af from net.c
2. added net_af_enabled for each AF
3. the media AF is now done for each UA
4. if registration is successful, the used AF will be also used for media
5. user can force IPv4 or IPv6 with the -4 and -6 flags

Here is an example from a machine with dualstack:

```
$ ./baresip -4
--- Network debug ---
 Local IPv4:  [E] ens3|172.31.1.100
 Local IPv6:  [.] (not set)
 Domain: 
net interfaces:
         lo:  127.0.0.1
       ens3:  172.31.1.100
 DNS Servers from Config: (2)
   0: 1.1.1.1:53
   1: [2606:4700:4700::1111]:53
```


```
$ ./baresip -6
--- Network debug ---
 Local IPv4:  [.] (not set)
 Local IPv6:  [E] ens3|2a01:4f8:c0c:34f9::2
 Domain: 
net interfaces:
         lo:  ::1
       ens3:  2a01:4f8:c0c:34f9::2
       ens3:  fe80::5054:a2ff:fe02:1840
 DNS Servers from Config: (2)
   0: 1.1.1.1:53
   1: [2606:4700:4700::1111]:53
```

**Comment by juha-h** [comment]
I built latest baresip and registration works when account't outbound proxy (on the same Linux host) has an IPv4 address, but does not work if it has IPv6 address.  I get 'Network is unreachable':
```
baresip v0.6.5 Copyright (C) 2010 - 2020 Alfred E. Heggestad et al.
Local network address:  IPv4=wlp1s0|10.10.10.201  IPv6=vboxnet0|2002:db8:0:1::1
...
jh@test.tutpro.com: Using sipnat: 'outbound'
ua: SIP register failed: Network is unreachable
account: failed to register ua 'sip:jh@test.tutpro.com' (Network is unreachable)

--- Network debug ---
 Local IPv4:  [E] wlp1s0|10.10.10.201
 Local IPv6:  [E] vboxnet0|2002:db8:0:1::1
 Domain: 
net interfaces:
         lo:  127.0.0.1
     wlp1s0:  10.10.10.201
   vboxnet0:  192.26.134.1
         lo:  ::1
     wlp1s0:  fe80::ee04:67c0:17aa:18a1
   vboxnet0:  2002:db8:0:1::1
   vboxnet0:  fe80::800:27ff:fe00:0
 DNS Servers from System: (1)
   0: 10.10.10.1:53

--- sip:jh@test.tutpro.com ---
 nrefs:     1
 cuser:     jh-0x55e7888e1060
 pub-gruu:  
 af_media:  AF_UNSPEC
 Supported: gruu,path,outbound

Account:
 address:      "Juha Heinanen" <sip:jh@test.tutpro.com>;auth_user=jh;auth_pass=foobar;outbound="sip:[2001:db8:0:1::1]:5060;transport=tcp";audio_codecs=OPUS/48000/2,PCMA,PCMU;regint=600;pubint=0;regq=0.5;sipnat=outbound;call_transfer=yes;mwi=no
 luri:         sip:jh@test.tutpro.com
 aor:          sip:jh@test.tutpro.com
 dispname:     Juha Heinanen
 answermode:   manual
 audio_codecs: opus/48000/2 PCMA/8000/1 PCMU/8000/1
 auth_user:    jh
 mediaenc:     none
 medianat:     none
 outbound1:    sip:[2001:db8:0:1::1]:5060;transport=tcp
 mwi:          no
 ptime:        20
 regint:       600
 pubint:       0
 regq:         0.5
 sipnat:       outbound
 stunserver:   stun:jh@test.tutpro.com:0
 call_transfer:         yes
 extra:         none

Register client:
 id:     1
 scode:  0 (zzz)
 srv:    
 af:     v?

```
Same result if I start baresip with '-6' flag.

I can telnet to the outbound address:
```
$ telnet 2002:db8:0:1::1 5060
Trying 2002:db8:0:1::1...
Connected to 2002:db8:0:1::1.
Escape character is '^]'.
```
So it should be reachable. What is it that I missed?

**Comment by juha-h** [comment]
Could preferred media AF be also included in struct account and as an optional account parameter?  If set, ua->af_media could then get its initial value based on that when ua is allocated.

**Comment by juha-h** [comment]
This https://github.com/alfredh/baresip/issues/897#issuecomment-578284310 problem was my fault.  The host had two IPv6 addresses and I used the wrong one in account config.

**Comment by juha-h** [comment]
I made more tests and mostly had success.  One thing that I noticed is that if IPv6-only (-6) baresip receives INVITE, where media IP is IPv4, it prints the issue to console, but accepts the call with media IP address 0.0.0.0:
```
ua: using AF from sdp offer: af=AF_INET
ua: SDP offer AF not supported (AF_INET)
sip:jh@test.tutpro.com: Incoming call from: Foo sip:foo@test.tutpro.com - (press 'a' to accept)
sip:jh@test.tutpro.com: Answering incoming call
answering call from sip:foo@test.tutpro.com with 200
```
Wouldn't it be better to reply with "488 Not acceptable here", since media would flow one way only?

**Comment by juha-h** [comment]
Similar to the previous, if UA's
```
	int af_media;                /**< Preferred Address Family for media */
```
has been set to AF_INET6,  call's media AF is INET6 even when there is no local  IPv6 address available. 
That results to IP6 address :: in the SDP.

Perhaps check, if ua->af_media has been enabled, could be added to ua_call_alloc():
```
        /* 1. if AF_MEDIA is set and enabled, we prefer it
	 * 2. otherwise fall back to SIP AF
	 */
	if (ua->af_media && net_af_enabled(baresip_network(), af_media)) {
		af = ua->af_media;
	}
        ...
```

**Comment by juha-h** [comment]
The above net_af_enabled() check does not work, since it does not check if the AF is currently available.  I tried to replace it with net_laddr_af(baresip_network(), ua->af_media), but that doesn't work either, since it returns IPv6 address :: even when net_debug tells:
```
Local IPv6:  [E] (not set)
```
This starts to get hopeless.  Perhaps the best choice is that I make my Android app user to choose, which world (IPv4 or IPv6) he/she wants to live and don't provide any interoperability between the two.

**Comment by alfredh** [comment]
net->laddr is inited to 0.0.0.0

I think the same should be done for IPv6 net->laddr6

i.e. -> sa_init(, AF_INET6);

for incoming offers we should check 2 things:

1. AF is enabled
2. AF is locally supported

if not satisfies, reply with 488 Not Acceptable Here

**Comment by juha-h** [comment]
Sounds good to me. 

How about outgoing? Would it make sense do to what I tried to do, i.e., not to offer IPvX media, if AF X is not locally supported even when X is the preferred AF for media?

**Comment by alfredh** [comment]
are you calling this to set the AF:

```c
/**
 * Set the preferred address family for media
 *
 * @param ua       User-Agent
 * @param af_media Address family (e.g. AF_INET, AF_INET6)
 */
void ua_set_media_af(struct ua *ua, int af_media)
{
	if (!ua)
		return;

	ua->af_media = af_media;
}
```

you should not call this with an AF that is not
enabled/supported -- your application should know that.

IMO you should forget about "preferred AF". your application should
only have 2 settings:

```
[ ] Enable IPv4 (on/off)
[ ] Enable IPv6 (on/off)
```

this will give the user enough flexibility and simplicity.
the rest is taken care of by libbaresip.

**Comment by juha-h** [comment]
> you should not call this with an AF that is not enabled/supported -- your application should know that.

I call ua_set_media_af with AF_INET6 arg at the time when the UA is created if user prefers to use IPv6 media AF.  The application cannot know at the time when the UA is created, if all networks where the device is connected, will support IPv6.

This has worked fine in my tests:
```
	/* 1. if AF_MEDIA is set and the device has local address in that AF, we prefer it
	 * 2. otherwise fall back to SIP AF
	 */
	
	if (ua->af_media && sa_isset(net_laddr_af(net, ua->af_media), SA_ADDR)) {
		af = ua->af_media;
	}
	else if (af_sdp) {
		af = af_sdp;
	}
	else
		af = best_effort_af(net);
```
There is an extra test in the first if-statement to prevent forcing the use of currently unavailable media AF.

> IMO you should forget about "preferred AF". your application should
only have 2 settings:
>
>[ ] Enable IPv4 (on/off)
[ ] Enable IPv6 (on/off)
>
>this will give the user enough flexibility and simplicity.
the rest is taken care of by libbaresip.

What kind of API-calls would those two choices map to?

**Comment by juha-h** [comment]
If incoming call needs to be rejected due to unavailable media AF, ua_call_alloc() should somehow be able to tell that to sipsess_conn_handler() so that it knows to generate 488 response.

**Comment by alfredh** [comment]
to enable/disable IPv4/v6:

```c
struct config_net -> af
```

where af is:

AF_INET - IPv4 Only
AF_INET6 - IPv6 Only
AF_UNSPEC - Dualstack

or:

```c
int  net_set_af(struct network *net, int af);
```

the unsupported af check is done inside call.c, in call_accept:

```c
		/*
		 * Each media description in the SDP answer MUST
		 * use the same network type as the corresponding
		 * media description in the offer.
		 *
		 * See RFC 6157
		 */
		m = stream_sdpmedia(audio_strm(call->audio));
		raddr = sdp_media_raddr(m);

		if (sa_af(raddr) != call->af) {
			info("call: incompatible address-family"
			     " (local=%s, remote=%s)\n",
			     net_af2name(call->af),
			     net_af2name(sa_af(raddr)));

			sip_treply(NULL, uag_sip(), msg,
				   488, "Not Acceptable Here");

			call_event_handler(call, CALL_EVENT_CLOSED,
					   "Wrong address family");
			return 0;
		}
```

**Comment by juha-h** [comment]
In ua_call_alloc() when the call comes in:

- use media AF from SDP if it is enabled and currently available
- otherwise, generate 488 response

In ua_call_alloc() when call goes out:

- use media AF ua->af_media if set and currently available
- otherwise, use best_effort_af
- if best_effort_af is AF_UNSPEC, generate call alloc error

**Comment by juha-h** [comment]
I wrote the above before I saw your comment.  Will study your comment.

**Comment by juha-h** [comment]
> the unsupported af check is done inside call.c, in call_accept:

I made a test where baresip -6, i.e., conf_config()->net.af = AF_INET6, receives call where SDP has IPv4 address:
```
c=IN IP4 10.42.0.1.
```
ua_call_alloc was using AF from the offer:
```
ua: using AF from sdp offer: af=AF_INET
ua: SDP offer AF not supported (AF_INET)
```
but call_accept was not rejecting the call due to incompatible address family:
```
sip:jh@test.tutpro.com: Incoming call from: Test Account sip:test@test.tutpro.com - (press 'a' to accept)
sip:jh@test.tutpro.com: Answering incoming call
answering call from sip:test@test.tutpro.com with 200
```
So looks like the test
```
		m = stream_sdpmedia(audio_strm(call->audio));
		raddr = sdp_media_raddr(m);

		if (sa_af(raddr) != call->af) {
```
failed, because both AFs in the test were AF_INET.

**Comment by juha-h** [comment]
With this ua_call_alloc code the unsupported AF check inside call_accept is working:
```
	if (msg) {
		af_sdp = sdp_af_hint(msg->mb);

		info("ua: using AF from sdp offer: af=%s\n",
		     net_af2name(af_sdp));

		if (!net_af_enabled(net, af_sdp)) {
			warning("ua: SDP offer AF not supported (%s)\n",
				net_af2name(af_sdp));
			af_sdp = AF_UNSPEC;
		}
		else if (!sa_isset(net_laddr_af(net, af_sdp), SA_ADDR)) {
			warning("ua: SDP offer AF not available (%s)\n",
				net_af2name(af_sdp));
			af_sdp = AF_UNSPEC;
		}
	}

	if (ua->af_media &&
	    sa_isset(net_laddr_af(net, ua->af_media), SA_ADDR)) {
		af = ua->af_media;
	}
	else if (af_sdp) {
		af = af_sdp;
	}
	else
		af = best_effort_af(net);
```
```
ua: using AF from sdp offer: af=AF_INET
ua: SDP offer AF not supported (AF_INET)
call: incompatible address-family (local=AF_INET6, remote=AF_INET)
```

**Comment by juha-h** [comment]
Below is improved version:
- If incoming request includes offer, use its AF if available or reject the request.
- If incoming request does not include offer or if request is outgoing, use preferred AF (if configured and available) or best effort AF.
```
	if (msg) {
		af_sdp = sdp_af_hint(msg->mb);
		/* INVITE reqest may not include offer */
		if (af_sdp) {
			info("ua: using AF from sdp offer: af=%s\n",
			     net_af2name(af_sdp));
			if (!net_af_enabled(net, af_sdp)) {
				warning("ua: SDP offer AF not supported (%s)\n",
					net_af2name(af_sdp));
			}
			else if (!sa_isset(net_laddr_af(net, af_sdp), SA_ADDR)) {
				warning("ua: SDP offer AF not available (%s)\n",
					net_af2name(af_sdp));
			}
			else {
				af = af_sdp;
			}
		}
		else if (ua->af_media &&
			 sa_isset(net_laddr_af(net, ua->af_media), SA_ADDR)) {
			af = ua->af_media;
		} else
			af = best_effort_af(net);
	} else if (ua->af_media &&
		 sa_isset(net_laddr_af(net, ua->af_media), SA_ADDR)) {
		af = ua->af_media;
	} else
		af = best_effort_af(net);
```

**Comment by alfredh** [comment]
this looks very good. can you please push your changes to master ?

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> this looks very good. can you please push your changes to master ?

I can but there is repetition in the code that does not look good.  I'll
try first to clean it up a bit.  Will be offline the next few days.

**Comment by juha-h** [comment]
Closed by https://github.com/alfredh/baresip/commit/4b68c0433ddf5d928f2436fe2ec3cffd8a85c48b

**Comment by alfredh** [comment]
Thanks! I also made some cosmetic changes in ua.c
