### ISSUE TITLE
Aufile cannot play files shorter than 1 s.

### ISSUE THREAD

**Issue by tomek-o** [alfredh/baresip#903]
First - I'm sorry that I'm not testing this on latest sources and/or sending direct patch, but I think problem still exists, seems interesting and easy to reproduce.

This is kind of edge case issue with files shorter than 1 second not being played by aufile - this probably would not be typical use case, I've found this accidentally, passing files from text-to-speech to softphone.

Aufile allocates aubuf with minimal size of 1 second (wish_sz), which may be larger than size of the source file, causing aubuf to be in "filling" (pre-buffering) state indefinitely and returning silence.
To fix this I've added aubuf_stop_buffering(struct aubuf *ab) function (not sure if this would be best name) passing to aubuf information that no additional samples would be appended and resetting "filling" state at end of the file (next to info("aufile: end of file\n") aufile line). This is related commit: https://github.com/tomek-o/tSIP/commit/896dced65eca992ec9d033525d1b5e06c3f434dd

**Comment by alfredh** [comment]
thanks for reporting :)

please have a look at my commit, it should fix your issue.
