### ISSUE TITLE
Send DTMF digit after auto answer

### ISSUE THREAD

**Issue by apascual** [alfredh/baresip#909]
Hi,

I would like to know if there is a way of sending a DTMF digit automatically after answering an incoming call. Unfortunately I couldn't find anything related in the documentation.

Thank you.

**Comment by alfredh** [comment]
currently there is no way to automatically send DTMF tones after answer.

you can create a module that listens to the ua event handler:

```c
static void ua_event_handler(struct ua *ua, enum ua_event ev,
			     struct call *call, const char *prm, void *arg)
{
	switch (ev) {

	case UA_EVENT_CALL_ESTABLISHED:
		call_send_digit(call, '1');
		call_send_digit(call, '2');
		call_send_digit(call, '3');
		break;
	}
}
```

**Comment by apascual** [comment]
@alfredh Sorry for the late reply, thank you for the guidance, I'll try it our.
