### ISSUE TITLE
Registration failed in android

### ISSUE THREAD

**Issue by magnatestech** [alfredh/baresip#913]
Registration is working perfectly on below Pie(Android 9), but it fails in android pie and android 10 with authentication issue.

JNIEXPORT jint JNICALL
Java_com_iotran_ioconnect_voipmodels_Api_ua_1register(JNIEnv *env, jobject thiz, jstring javaUA) {
    const char *native_ua = (*env)->GetStringUTFChars(env, javaUA, 0);
    struct ua *ua = (struct ua *) strtoul(native_ua, NULL, 10);
    (*env)->ReleaseStringUTFChars(env, javaUA, native_ua);
    LOGD("registering UA '%s'\n", native_ua);
    return ua_register(ua);
}

above function should return zero but it returns non-zero value '22'

**Comment by alfredh** [comment]
please see here for how to report issues:

https://github.com/alfredh/baresip/wiki/Guidelines-for-reporting-Issues

can you please include more information, like which project
are you using, how did you build it, logs etc.
