### ISSUE TITLE
module coreaudio.so: Invalid argument in v0.6.5 on macOS v10.15.2

### ISSUE THREAD

**Issue by phoenixwu** [alfredh/baresip#914]
baresip v0.5.10 runs fine on macOS for a long time. (installed by homebrew)

Just upgrade to baresip v0.6.5 by homebrew, then I got an error message: ”module coreaudio.so: Invalid argument“ when starting baresip.
Registration works ok, but the call has no sound.
It seems sound module didn't load correctly.

**Comment by phoenixwu** [comment]
update: I overwrite the coreaudio.so with the old version(v0.5.10) one, then the error message is gone and the voice is back.

/usr/local/Cellar/baresip/0.6.5/lib/baresip/modules

**Comment by alfredh** [comment]
https://github.com/alfredh/baresip/wiki/Guidelines-for-reporting-Issues

can you please include the full log ?

you should not mix modules from different major release (0.M.x)
the ABI is most likely different and other issues will appear.

**Comment by alfredh** [comment]
just installed baresip from homebrew, it works fine:


```
$ brew install baresip
==> Downloading https://homebrew.bintray.com/bottles/baresip-0.6.5.mojave.bottle.tar.gz
Already downloaded: /Users/alfredh/Library/Caches/Homebrew/downloads/69cf535fe46f675a97bf19ca4c64cd57985f8eb6c1524e6239abc7532bc9ed5b--baresip-0.6.5.mojave.bottle.tar.gz
==> Pouring baresip-0.6.5.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/baresip/0.6.5: 40 files, 974.9KB
```

```
$ baresip -f /tmp/bare2
baresip v0.6.5 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.
config: creating config template /tmp/bare2/config
/usr/local/Cellar/baresip/0.6.5/lib/baresip/modules: detected 28 modules
Local network address:  IPv4=en0|192.168.88.51  IPv6=en0|2a02:d8::9:884:87f0:faed:ab4
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
auplay: coreaudio
ausrc: coreaudio
vidsrc: avcapture
medianat: stun
medianat: turn
medianat: ice
medianat: ice-lite
uuid: generated new UUID in /tmp/bare2/uuid
account: creating accounts template /tmp/bare2/accounts
Populated 0 accounts
account: No SIP accounts found
 -- check your config or add an account using 'uanew' command
contact: creating contacts template /tmp/bare2/contacts
Populated 3 contacts
Populated 2 audio codecs
Populated 0 audio filters
Populated 0 video codecs
Populated 0 video filters
baresip is ready.
terminated by signal 2
ua: stop all (forced=0)
```

**Comment by crazyclona** [comment]
Yo Alfredh ;) 

Guess who has this issue ;) 

-A

**Comment by greenmns** [comment]
Hi i want use silk codec on baresip version v0.5.7
after install from ubuntu repository module silk.so not exist
How can i use silk codec with baresip?

**Comment by juha-h** [comment]
greenmns writes:

> Hi i want use silk codec on baresip version v0.5.7
> after install from ubuntu repository module silk.so not exist
> How can i use silk codec with baresip?

baresip does not anymore have silk module.  use opus instead.

**Comment by greenmns** [comment]
> greenmns writes:
> Hi i want use silk codec on baresip version v0.5.7 after install from ubuntu repository module silk.so not exist How can i use silk codec with baresip?
> baresip does not anymore have silk module. use opus instead.

because of a university project i need to generate a sip call with codec silk 12 , 24 
i think baresip support silk codec but now understand it doesn't support it.
