### ISSUE TITLE
Baresip backup server solution

### ISSUE THREAD

**Issue by dichkv** [alfredh/baresip#916]
Hi,

Is there any solution to support backup server in baresip. For example, when baresip call to primary server get error, it's call to backup server with different public address. Any solution to do that? 

Thanks you,

**Comment by alfredh** [comment]
You can enable SIP outbound with 2 outbound servers.

See the example:

https://github.com/alfredh/baresip/blob/master/docs/examples/accounts

```
<sip:user@domain>;sipnat=outbound;outbound="sip:1.example.com";outbound2=sip:2.example.com
```

or you can configure your SIP domain to support multiple servers
and SRV records.

Please use the mailing-list for questions like this:
https://github.com/alfredh/baresip/wiki/Guidelines-for-reporting-Issues
