### ISSUE TITLE
vumeter

### ISSUE THREAD

**Issue by gogonowski** [alfredh/baresip#918]
Updated to baresip 0.6.5 from 0.5.7
Ubuntu 18.04.4 LTS
vumeter no longer shows on command line. Not even the vumeter end brackets.
Yes, I have changed the Modules path in config after update.
So far, everything audio seems to be working well. Makes connection to another client.
No error messages.
Using StreamS IOdigi2X UAC2 USB Audio Device - ALSA
Using Opus 48000.
Am I missing a dependency that is not reporting missing, or is this a known issue?
baresip 0.5.7 vumeter was working.
 
`
baresip is ready.
->                 sip@10.1.1.127
call: connecting to 'sip:sip@10.1.1.127'..
call: SIP Progress: 100 Trying (/)
stream: update 'audio'
audio: Set audio decoder: opus 48000Hz 2ch
audio: player started with sample format S16LE
audio: Set audio encoder: opus 48000Hz 2ch
audio: source started with sample format S16LE
audio tx pipeline:        alsa ---> vumeter ---> opus
audio rx pipeline:        alsa <--- vumeter <--- opus
sip@10.1.1.127: Call established: sip:sip@10.1.1.127
stream: incoming rtp for 'audio' established, receiving from 10.1.1.127:5062
Audio decoder changed payload 107 -> 96
call: terminate call '4dfe78e50c241727' with sip:sip@10.1.1.127
sip:sip@10.1.1.127: Call with sip:sip@10.1.1.127 terminated (duration: 35 secs)

audio           Transmit:     Receive:
packets:           3477         1739
avg. bitrate:      64.7         51.1  (kbit/s)
errors:               0            0
pkt.report:        2826         1414
lost:                 0            0
jitter:             1.5          0.6  (ms)

`

**Comment by alfredh** [comment]
try to generate a fresh config file, you will see what has changed.

try to enable this config:

```
vumeter_stderr          yes
```

**Comment by gogonowski** [comment]
All working now.
Thank you.
