### ISSUE TITLE
baresip-webrtc

### ISSUE THREAD

**Issue by gogonowski** [alfredh/baresip#919]
baresip-webrtc unable to build.
Ubuntu 18.04.4 LTS
baresip 0.6.5 is installed from git.
Is there more documentation available for baresip-webrtc?

streams@ubuntu:~/baresip-webrtc/baresip-webrtc-master$ make
  CC      build-x86_64/src/main.o
In file included from src/main.c:13:0:
src/demo.h:30:16: warning: ‘struct stun_uri’ declared inside parameter list will not be visible outside of this definition or declaration
         struct stun_uri *stun_srv,
                ^~~~~~~~
  CC      build-x86_64/src/session.o
In file included from src/session.c:10:0:
src/demo.h:30:16: warning: ‘struct stun_uri’ declared inside parameter list will not be visible outside of this definition or declaration
         struct stun_uri *stun_srv,
                ^~~~~~~~
src/session.c: In function ‘destructor’:
src/session.c:92:19: warning: implicit declaration of function ‘stream_name’; did you mean ‘stream_call’? [-Wimplicit-function-declaration]
        media->ix, stream_name(media_get_stream(media)));
                   ^~~~~~~~~~~
                   stream_call
src/session.c:92:19: warning: nested extern declaration of ‘stream_name’ [-Wnested-externs]
src/session.c:112:4: warning: implicit declaration of function ‘video_stop’; did you mean ‘video_strm’? [-Wimplicit-function-declaration]
    video_stop(media->u.vid);
    ^~~~~~~~~~
    video_strm
src/session.c:112:4: warning: nested extern declaration of ‘video_stop’ [-Wnested-externs]
src/session.c: At top level:
src/session.c:312:16: warning: ‘struct stun_uri’ declared inside parameter list will not be visible outside of this definition or declaration
         struct stun_uri *stun_srv,
                ^~~~~~~~
src/session.c:307:5: error: conflicting types for ‘rtcsession_create’
 int rtcsession_create(struct rtcsession **sessp, const struct config *cfg,
     ^~~~~~~~~~~~~~~~~
In file included from src/session.c:10:0:
src/demo.h:25:5: note: previous declaration of ‘rtcsession_create’ was here
 int rtcsession_create(struct rtcsession **sessp, const struct config *cfg,
     ^~~~~~~~~~~~~~~~~
src/session.c: In function ‘rtcsession_create’:
src/session.c:359:7: warning: passing argument 5 of ‘mnat->sessh’ from incompatible pointer type [-Wincompatible-pointer-types]
       stun_srv,
       ^~~~~~~~
src/session.c:359:7: note: expected ‘const char *’ but argument is of type ‘struct stun_uri *’
src/session.c:360:7: warning: passing argument 6 of ‘mnat->sessh’ makes integer from pointer without a cast [-Wint-conversion]
       NULL, NULL,
       ^~~~
src/session.c:360:7: note: expected ‘uint16_t {aka short unsigned int}’ but argument is of type ‘void *’
src/session.c:361:7: warning: passing argument 8 of ‘mnat->sessh’ from incompatible pointer type [-Wincompatible-pointer-types]
       sess->sdp, !got_offer,
       ^~~~
src/session.c:361:7: note: expected ‘const char *’ but argument is of type ‘struct sdp_session *’
src/session.c:361:18: warning: passing argument 9 of ‘mnat->sessh’ makes pointer from integer without a cast [-Wint-conversion]
       sess->sdp, !got_offer,
                  ^
src/session.c:361:18: note: expected ‘struct sdp_session *’ but argument is of type ‘int’
src/session.c:362:7: warning: the address of ‘mnat_estab_handler’ will always evaluate as ‘true’ [-Waddress]
       mnat_estab_handler, sess);
       ^~~~~~~~~~~~~~~~~~
src/session.c:362:27: warning: passing argument 11 of ‘mnat->sessh’ from incompatible pointer type [-Wincompatible-pointer-types]
       mnat_estab_handler, sess);
                           ^~~~
src/session.c:362:27: note: expected ‘void (*)(int,  uint16_t,  const char *, void *) {aka void (*)(int,  short unsigned int,  const char *, void *)}’ but argument is of type ‘struct rtcsession *’
src/session.c:356:9: error: too few arguments to function ‘mnat->sessh’
   err = mnat->sessh(&sess->mnats, mnat,
         ^~~~
src/session.c:375:7: warning: passing argument 4 of ‘menc->sessh’ from incompatible pointer type [-Wincompatible-pointer-types]
       menc_event_handler,
       ^~~~~~~~~~~~~~~~~~
src/session.c:375:7: note: expected ‘void (*)(enum menc_event,  const char *, void *)’ but argument is of type ‘void (*)(enum menc_event,  const char *, struct stream *, void *)’
src/session.c: In function ‘rtcsession_add_audio’:
src/session.c:429:6: warning: ISO C forbids passing argument 17 of ‘audio_alloc’ between function pointer and ‘void *’ [-Wpedanti ]
      audio_err_handler, sess);
      ^~~~~~~~~~~~~~~~~
In file included from src/session.c:9:0:
/usr/local/include/baresip.h:1137:5: note: expected ‘void *’ but argument is of type ‘void (*)(int,  const char *, void *)’
 int audio_alloc(struct audio **ap, struct list *streaml,
     ^~~~~~~~~~~
src/session.c:422:8: error: too many arguments to function ‘audio_alloc’
  err = audio_alloc(&media->u.au, &sess->streaml,
        ^~~~~~~~~~~
In file included from src/session.c:9:0:
/usr/local/include/baresip.h:1137:5: note: declared here
 int audio_alloc(struct audio **ap, struct list *streaml,
     ^~~~~~~~~~~
src/session.c:438:9: warning: passing argument 3 of ‘stream_set_session_handlers’ from incompatible pointer type [-Wincompatible-pointer-types]
         rtpestab_handler,
         ^~~~~~~~~~~~~~~~
In file included from src/session.c:9:0:
/usr/local/include/baresip.h:1214:6: note: expected ‘void (*)(struct stream *, int,  void *)’ but argument is of type ‘void (*)(struct stream *, void *)’
 void stream_set_session_handlers(struct stream *strm,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/session.c:439:9: warning: ISO C forbids passing argument 4 of ‘stream_set_session_handlers’ between function pointer and ‘void *’ [-Wpedantic]
         rtcp_handler,
         ^~~~~~~~~~~~
In file included from src/session.c:9:0:
/usr/local/include/baresip.h:1214:6: note: expected ‘void *’ but argument is of type ‘void (*)(struct stream *, struct rtcp_msg *, void *)’
 void stream_set_session_handlers(struct stream *strm,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/session.c:437:2: error: too many arguments to function ‘stream_set_session_handlers’
  stream_set_session_handlers(strm, mnatconn_handler,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/session.c:9:0:
/usr/local/include/baresip.h:1214:6: note: declared here
 void stream_set_session_handlers(struct stream *strm,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/session.c: In function ‘rtcsession_add_video’:
src/session.c:469:8: warning: implicit declaration of function ‘video_alloc’; did you mean ‘audio_alloc’? [-Wimplicit-function-declaration]
  err = video_alloc(&media->u.vid, &sess->streaml,
        ^~~~~~~~~~~
        audio_alloc
src/session.c:469:8: warning: nested extern declaration of ‘video_alloc’ [-Wnested-externs]
src/session.c:487:9: warning: passing argument 3 of ‘stream_set_session_handlers’ from incompatible pointer type [-Wincompatible-pointer-types]
         rtpestab_handler,
         ^~~~~~~~~~~~~~~~
In file included from src/session.c:9:0:
/usr/local/include/baresip.h:1214:6: note: expected ‘void (*)(struct stream *, int,  void *)’ but argument is of type ‘void (*)(struct stream *, void *)’
 void stream_set_session_handlers(struct stream *strm,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/session.c:488:9: warning: ISO C forbids passing argument 4 of ‘stream_set_session_handlers’ between function pointer and ‘void *’ [-Wpedantic]
         rtcp_handler,
         ^~~~~~~~~~~~
In file included from src/session.c:9:0:
/usr/local/include/baresip.h:1214:6: note: expected ‘void *’ but argument is of type ‘void (*)(struct stream *, struct rtcp_msg *, void *)’
 void stream_set_session_handlers(struct stream *strm,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/session.c:486:2: error: too many arguments to function ‘stream_set_session_handlers’
  stream_set_session_handlers(strm, mnatconn_handler,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/session.c:9:0:
/usr/local/include/baresip.h:1214:6: note: declared here
 void stream_set_session_handlers(struct stream *strm,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/session.c: In function ‘rtcsession_start_video’:
src/session.c:651:10: warning: implicit declaration of function ‘video_encoder_set’; did you mean ‘audio_encoder_set’? [-Wimplicit-function-declaration]
   err  = video_encoder_set(vid, vc, sc->pt, sc->params);
          ^~~~~~~~~~~~~~~~~
          audio_encoder_set
src/session.c:651:10: warning: nested extern declaration of ‘video_encoder_set’ [-Wnested-externs]
src/session.c:658:9: warning: implicit declaration of function ‘video_start’; did you mean ‘video_strm’? [-Wimplicit-function-declaration]
   err = video_start(vid, NULL);
         ^~~~~~~~~~~
         video_strm
src/session.c:658:9: warning: nested extern declaration of ‘video_start’ [-Wnested-externs]
Makefile:57: recipe for target 'build-x86_64/src/session.o' failed
make: *** [build-x86_64/src/session.o] Error 1
streams@ubuntu:~/baresip-webrtc/baresip-webrtc-master$

**Comment by alfredh** [comment]
try to use latest baresip from git HEAD

**Comment by gogonowski** [comment]
OK.
This made a vast improvement of things, however, there is still one error left.
What are the requirements to build baresip to produce dtls_srtp.so?
I can't find a complete list of build dependencies for baresip. Does this exist?
This is important when building from GIT.

Also, I notice that re.so does not indicate having been built with TLS/SSL.

We are anxious to test baresip-webrtc.

Please advise.
Thanks.
/g.

streams@ubuntu:~/baresip/re-0.6.1$ make info
info - re version 0.6.1
  MODULES:       sip sipevent sipreg sipsess uri http httpauth msg websock stun turn ice natbd rtp sdp jbuf telev dns md5 crc32 sha hmac base64 udp sa net tcp tls list mbuf hash fmt tmr main mem dbg sys lock mqueue mod conf bfcp aes srtp odict json rtmp
  MACHINE:       x86_64-linux-gnu
  ARCH:          x86_64
  OS:            linux
  BUILD:         build-x86_64
  CCACHE:
  CC:            gcc 8.04.x
  CFLAGS:        -Wall -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wbad-function-cast -Wsign-compare -Wnested-externs -Wshadow -Waggregate-return -Wcast-align -g -fPIC -DLINUX -DOS="linux" -std=c99 -pedantic -DARCH="x86_64" -DUSE_ZLIB -DHAVE_PTHREAD -DHAVE_GETIFADDRS -DHAVE_STRERROR_R -DHAVE_GETOPT -DHAVE_INTTYPES_H -DHAVE_NET_ROUTE_H -DHAVE_SYS_SYSCTL_H -DHAVE_STDBOOL_H -DHAVE_INET6 -DHAVE_RESOLV -DHAVE_SYSLOG -DHAVE_FORK -DHAVE_INET_NTOP -DHAVE_PWD_H -DHAVE_POLL      -DHAVE_INET_PTON -DHAVE_SELECT -DHAVE_SELECT_H -DHAVE_SETRLIMIT -DHAVE_SIGNAL -DHAVE_SYS_TIME_H -DHAVE_EPOLL -DHAVE_UNAME -DHAVE_UNISTD_H -DHAVE_STRINGS_H -DVERSION="0.6.1" -DVER_MAJOR=0 -DVER_MINOR=6 -DVER_PATCH=1  -Iinclude -DHAVE_ROUTE_LIST
  DFLAGS:        -MD -MF info -MT info
  LFLAGS:        -fPIC
  SH_LFLAGS:     -shared
  MOD_LFLAGS:
  APP_LFLAGS:    -rdynamic
  LIBS:          -ldl -lz -lpthread
  LIBRE_MK:
  LIBRE_INC:     /usr/local/include/re
  LIBRE_SO:      /usr/local/lib
  USE_OPENSSL:
  USE_OPENSSL_AES:
  USE_OPENSSL_HMAC:
  USE_TLS:
  USE_DTLS:
  USE_DTLS_SRTP:
  USE_ZLIB:      yes
  GCOV:
  GPROF:
  CROSS_COMPILE:
  SYSROOT:       /usr
  SYSROOT_ALT:
  LIB_SUFFIX:    .so
  MOD_SUFFIX:    .so
  BIN_SUFFIX:
streams@ubuntu:~/baresip/re-0.6.1$

**Comment by gogonowski** [comment]
Fixed and Running.
/g.
