### ISSUE TITLE
Support for SIP over websocket

### ISSUE THREAD

**Issue by urbaniak** [alfredh/baresip#92]
Is there any chance getting SIP over websocket (https://tools.ietf.org/html/rfc7118) support?

**Comment by alfredh** [comment]
yes, this is something that many people have been asking for

if I create a patch for this, will you assist with testing ?

in which setup are you planning on using this? is it so that SIP over WS
is most useful in Web browsers ? If you are using a SIP-proxy
like Kamailio I guess you can have 1 leg over WS and the other leg over UDP/TCP ?

**Comment by urbaniak** [comment]
I would be happy testing and helping with that. ;)

I'm using sip.js for web based calls, but want to also introduce an iOS application and looking right now for possible sip libraries. It does not matter for Android, cause it has proper WebRTC support in the webview.

I'm asking for sip over websockets cause HA/loadbalancing and advanced routing is provided by http when connecting to websocket and I don't want to handle things like round robin load balancing in the application itself. It's also useful for going through firewalls and providing encryption (https).

**Comment by alfredh** [comment]
great! I have implemented SIP over Websockets as a patch to libre+baresip:

https://github.com/alfredh/baresip/tree/sip_websock

you can try to add ;transport=ws to your account file.

**Comment by urbaniak** [comment]
Cool, thanks, I'll try adding baresip to my iOS app tomorrow and test this patch

**Comment by alfredh** [comment]
Hey, did you have any luck testing the SIP over Websockets?

it might be easier to try out baresip on a host platform like Linux or OSX.

**Comment by urbaniak** [comment]
Hi, I was unable to compile that for iOS, even without websocket support, that's why I haven't touched that for a while.

Compiled that on plain OS X - looks like it's somehow working. I was able to register successfully, just needed to hack the url in libre patch, cause websocket is not at root (/) url in my case.

```
if (re_snprintf(ws_uri, sizeof(ws_uri), "ws://%J/path", dst) < 0) {
```

We should have a way of specifying that somehow in the accounts file instead of constructing that in libre, the common practice is just having ws://127.0.0.1:8000/path as a sip proxy server.

Also wondered how about https/wss support? We need another transport type or just wss://127.0.0.1/path url.

I'll keep looking at that, still unable to make a call, because of some crypto issues when negotiating media stream.

```
[Jan  4 11:04:46] NOTICE[2317][C-0000000c]: chan_sip.c:10130 process_sdp: Received AVP profile in audio answer but AVPF is enabled, disabling: audio 11322 RTP/AVP 0 8 101
[Jan  4 11:04:46] WARNING[2317][C-0000000c]: chan_sip.c:10525 process_sdp: Failed to receive SDP offer/answer with required SRTP crypto attributes for audio
```

**Comment by juha-h** [comment]
Krzysztof Urbaniak writes:

> We should have a way of specifying that somehow in the accounts file
> instead of constructing that in libre, the common practice is just
> having ws://127.0.0.1:8000/path as a sip proxy server. 
> 
> Also wondered how about https/wss support? We need another transport
> type or just wss://127.0.0.1/path url.

yes, it would make sense to allow

outbound="ws[s]://<addr>:port/path"

in accounts file.

-- juha

**Comment by alfredh** [comment]
updated patch with support for both WS and WSS:

https://github.com/alfredh/patches/blob/master/re-sip-websock-003.patch

https://github.com/alfredh/baresip/tree/sip_websock

Tested with Kamailio 4.4.0 using the following SIP uris:

```
<sip:test:test@10.0.0.2:8000;transport=ws>
<sip:test:test@10.0.0.2:4443;transport=wss>
```

**Comment by lmangani** [comment]
Not sure what I am missing but I cant compile the ```sip_websock``` branch
```
src/reg.c:48:7: error: ‘SIP_TRANSP_WS’ undeclared (first use in this function)
src/reg.c:49:7: error: ‘SIP_TRANSP_WSS’ undeclared (first use in this function)
src/reg.c:74:7: error: ‘SIP_TRANSP_WS’ undeclared (first use in this function)
src/reg.c:75:7: error: ‘SIP_TRANSP_WSS’ undeclared (first use in this function)
```

**Comment by alfredh** [comment]
you need to patch libre first:

```
$ wget http://www.creytiv.com/pub/re-0.4.16.tar.gz
$ tar -xzvf re-0.4.16.tar.gz 
$ patch -p0 < re-sip-websock-003.patch
$ make
$ sudo make install
```

... and then build baresip ..

**Comment by lmangani** [comment]
doh... i downloaded the patchfile as HTML and missed the patch failing to apply ;)
Thanks!

**Comment by alfredh** [comment]
I have updated the patch for libre:

https://github.com/creytiv/re/tree/sip_websock

please try it out, more testing and review is needed :)

**Comment by alfredh** [comment]
I dont have any time to work on this at the moment.
Closing the issue for now, will reopen when I have some time to look into it.

**Comment by zhuchinskyi** [comment]
Hi, 
Can not find info in the description of your library,
so is it now already available SIP over WebSocket for IOS and Android?

**Comment by murugancmi** [comment]
HI is there any update on this feature for android and IOS?

**Comment by sandeep2244** [comment]
@urbaniak @alfredh 

how to use libre as SIP gateway in IOS ?

I have my own SIP server(Astrisk) credential wich i need to just configure in gateway and call to PSTN number from Native WEBRTC Application 

Webrtc -> SIP gateway(Libre) -> Server(Asterisk) -> PSTN

Thank you

**Comment by sandeep2244** [comment]
@urbaniak @alfredh 

how to use libre as SIP gateway in IOS ?

I have my own SIP server(Astrisk) credential wich i need to just configure in gateway and call to PSTN number from Native WEBRTC Application 

Webrtc -> SIP gateway(Libre) -> Server(Asterisk) -> PSTN

Thank you

**Comment by Pastor02** [comment]
Hi somebody can send me the download path for support websocket in baresip.

The actual link is down.

Thanks.

**Comment by lmangani** [comment]
@Pastor02 which link are you referring to? this is a 2+ year old thread

**Comment by sreimers** [comment]
Websocket is supported by baresip/re since version v1.1.0: https://github.com/baresip/re/blame/master/CHANGELOG.md#L81

**Comment by Pastor02** [comment]
> SIP Websocket is supported by baresip/re since version v1.1.0: https://github.com/baresip/re/blame/master/CHANGELOG.md#L81

Thanks

**Comment by moradi-morteza** [comment]
> SIP Websocket is supported by baresip/re since version v1.1.0: https://github.com/baresip/re/blame/master/CHANGELOG.md#L81

whats happened for link? its not available!

**Comment by moradi-morteza** [comment]
> > SIP Websocket is supported by baresip/re since version v1.1.0: https://github.com/baresip/re/blame/master/CHANGELOG.md#L81
> 
> Thanks

does it work for you?

**Comment by mbattista** [comment]
The default branch got renamed from master to main.

This would be the new link, line 887 right now.
https://github.com/baresip/re/blob/main/CHANGELOG.md

**Comment by moradi-morteza** [comment]
> The default branch got renamed from master to main.
> 
> This would be the new link, line 887 right now. https://github.com/baresip/re/blob/main/CHANGELOG.md

thank you, do you know any sample for usage this library in android

**Comment by datpt11** [comment]
any update
