### ISSUE TITLE
baresip logo - vector:svg

### ISSUE THREAD

**Issue by gogonowski** [alfredh/baresip#920]
Does anyone have a vector version of the baresip logo?
SVG?
If not, what 2 fonts were used to create this, and I will create an SVG and submit.
Thanks.
/greg.

**Comment by alfredh** [comment]
hi,

please read this:

https://github.com/alfredh/baresip/wiki/Guidelines-for-reporting-Issues

it is probably better to ask on the re-devel mailing list
