### ISSUE TITLE
How to configure Bluetooth player in audio config

### ISSUE THREAD

**Issue by 75535552** [alfredh/baresip#921]
I tested the audio in terminal cmd.  linux
test cmd ok。
aplay ~/10.wav //ok

//linux bluetooth device view
~/.asoundrc

aplay -D bluealsa:DEV=00:0D:45:9D:65:C7,PROFILE=a2dp,HCI=hci0 ~/10.wav //ok

how to configure item "audio_player" in config file ?

**Comment by alfredh** [comment]
please use re-devel mailing list for questions like this:

https://github.com/alfredh/baresip/wiki/Guidelines-for-reporting-Issues
