### ISSUE TITLE
Send pause or DTMF after outgoing call is established

### ISSUE THREAD

**Issue by jose1711** [alfredh/baresip#931]
I am unaware of any way (except for writing a custom module as mentioned in https://github.com/alfredh/baresip/issues/909) how to send `DTMF` codes once the call is established. That makes automation of interaction with IVR or joining a conference difficult. Therefore I believe it would be great if `baresip` accepts and interprets command like:
`d123|pp3p456`
as
1. dial `123`
2. wait 2x pause interval
3. send DTMF 3
4. wait pause interval
5. send DTMF dials 4, 5, 6

Similar URI-schemas are common on Android but I don't think SIP-URI alternative exists.

**Comment by alfredh** [comment]
a Pull Request is welcome. You can add the item to the roadmap if you want.
Please also read this one:

https://github.com/alfredh/baresip/wiki/Guidelines-for-reporting-Issues
