### ISSUE TITLE
CALL_RINGING event plays sound over "audio_alert" device

### ISSUE THREAD

**Issue by gblair** [alfredh/baresip#934]
First: Thanks for sharing this lovely software with the world!

I noticed that, when making an outbound call, the ringback tone appears to be played over the configured `audio_alert` output. Is this the expected behavior? I was sort of expecting to hear the ringback in the `audio_player` output (e.g. the speaker on a handset, etc.).

Here's the bit of relevant config (I can post all of it, if it would help)
```
# Audio
audio_path		/usr/local/share/baresip
audio_player		alsa,default
audio_source		alsa,default
audio_alert		alsa,hw:0
auplay_srate		0
ausrc_srate		0
auplay_channels		0
ausrc_channels		0
audio_level		no
```

**Comment by premultiply** [comment]
You are able to specify an individual audio device for audio in and out for each account but as far as I can see there is no such option for alerts yet.
What I did is disabling alerts completly for now.

**Comment by gblair** [comment]
Thanks @premultiply. I would be totally fine just having a globally-configured separate "alert" audio output device (and the sample config would seem to suggest this is possible). In fact, I can confirm that, when a call is incoming, the alternative output configured in `audio_alert` is used to play the ring tone. Then, after answering the call, audio source is my handset mic (as configured), and audio coming from the other end of the line comes out of the default audio device (also as configured). 

The only weird thing is that, when I make an outbound call with this configuration, the ringback tone comes out of the speaker that is configured for `audio_alert`. "Speakerphone" modes of operation aside, shouldn't the ringback tone come from the playback device (e.g. in the earpiece), like on any standard telephone interface? If this is not by design, perhaps I will get in there and see if I can sort it out. Full disclosure: C is not really my forte, but I'll try it!!!

I suppose I could disable alerts entirely, but I'd like to avoid the need to use some other process to play the ringtone (and assumedly the ringback tone) when calls are incoming/outgoing.

**Comment by premultiply** [comment]
I think the reason for this is that there is no audio stream on the transmission path during outbound call setup and ringing. So there is nothing to play on the specified device.

The emulated ringtone is just an audiofile locally played by baresip on the special audio device.

Some SIP telephone servers transmit an audio stream with ringtone, announcement etc. from itself during ringing. This will be played on the accounts audio playback device.

I think what you request is that the emulated local ringtone can or should be redirected to the accounts specific audio playback device instead of the global alert device if enabled. Right?

**Comment by gblair** [comment]
> I think what you request is that the emulated local ringtone can or should be redirected to the accounts specific audio playback device instead of the global alert device if enabled. Right?

Thanks, yes, I think that sounds right. I would expect the emulated sound (in case there's no streamed ringback tone) to go through the same output (playback) that the streamed one would.

I submitted a PR here (#935) that attempts to tighten up the choice of alert vs. playback device, specifically it adds the following change in behavior:
- Play the ringback sound over the playback device instead of alert device (I think this covers the "emulated" case, not sure about the streamed case)
- Play the "call waiting" sound over the playback device instead of alert device (just noticed this as I was making the changes)

With those ∆s, the library seems to be behave as I had originally expected it would. I'm still not 100% confident that's what is warranted for the general case, but hopefully the PR can afford the chance for discussion, if anyone wants.
