### ISSUE TITLE
RTCP-XR/VQ Support

### ISSUE THREAD

**Issue by Hafler** [alfredh/baresip#936]
#328 shows that RTCP-XR PUBLISH support was intended, but I don't see anywhere where it is implemented current releases. I tested, but found that the only time that I see any stats is when the call ends and X-RTP-Stat are sent in the BYE messages.

My main goal here is to gather quality statistics while a call (baresip to baresip) is running. Could someone let me know if this was ever implemented?

**Comment by alfredh** [comment]
it is not implemented ..

a patch is welcome if someone wants to implement it ..
