### ISSUE TITLE
Upgrade: opengl es for Android compatible (videocall)

### ISSUE THREAD

**Issue by p5panam** [alfredh/baresip#937]
Hello,
I like baresip and use it a lot on android. I would like to add videocall on android version, but module opengl es on source is mainly for MAC or iOS. Is there any possibility of porting the code to android and add interaction with baresip?

Regards,

**Comment by juha-h** [comment]
William Anderson writes:

> I like baresip and use it a lot on android. I would like to add
> videocall on android version, but module opengl es on source is mainly
> for MAC or iOS. Is there any possibility of porting the code to
> android and add interaction with baresip?

If I remember correctly, opengles module compiles using NDK toolchain,
but I don't know what needs to be changed to make it usable for an
Android app.

**Comment by alfredh** [comment]
it is probably better to create a new module for video output for Android.
I think there are better ways to display a video frame in a Window, using
Android specific APIs.

Have a look at the SDK/NDK documentation and check if there are other methods.

**Comment by alfredh** [comment]
note: https://github.com/alfredh/baresip/wiki/Guidelines-for-reporting-Issues
