### ISSUE TITLE
baresip and g722.2

### ISSUE THREAD

**Issue by Disinterpreter** [alfredh/baresip#941]
Does baresip support g722.2?
How I can play sound via baresip to phone with amr-wb codec?

**Comment by alfredh** [comment]
g722.2 is the same as AMR-WB, which is supported.

This should be documented in the README.md file

**Comment by Disinterpreter** [comment]
![изображение](https://user-images.githubusercontent.com/3816155/77064688-05966a80-69f1-11ea-9fb5-0c8ebd9ae1f0.png)

Yes. Should be.

**Comment by Disinterpreter** [comment]
Yes. Should be. (I really didn't see g722.2 module on my PC)
![изображение](https://user-images.githubusercontent.com/3816155/77064770-2a8add80-69f1-11ea-9781-bd468b589420.png)

**Comment by alfredh** [comment]
https://github.com/alfredh/baresip/wiki/Guidelines-for-reporting-Issues
