### ISSUE TITLE
Windows binaries not working properly

### ISSUE THREAD

**Issue by alexander-elgin** [alfredh/baresip#942]
Please, can you provide the latest windows binaries (both 32bit & 64bit)? Compiling working binaries for windows is unresolved puzzle for me.

**Comment by Encamy** [comment]
Hello! Which binaries do you need? baresip-executable or compiled baresip lib?
You can use this instructions for compiling project for your need   
 https://github.com/alfredh/baresip/issues/731#issuecomment-501284999  
https://github.com/creytiv/re/issues/150  
https://github.com/alfredh/baresip/issues/711  

There is ready solution (baresip/mk/win32/baresip.sln) for compilation, all what you need is to get right project structure and load solution

**Comment by alexander-elgin** [comment]
I guess I need baresip executable. I need exe files (both 32bit & 64bit) for Windows 10 that can call answer calls and interact with http (localhost:8000).

**Comment by alexander-elgin** [comment]
Please, can you provide windows binary files of any version which works properly on Windows 10?

**Comment by alexander-elgin** [comment]
@Encamy Any luck?

**Comment by alexander-elgin** [comment]
Actually I followed the folder structure (see https://github.com/alfredh/baresip/issues/731#issuecomment-501284999). It is even compiled without any errors either warning but the binary file is not working properly on Windows 10 (64 bit). The util can answer call but it cannot dial a number (change of `FD_SETSIZE` value see https://github.com/alfredh/baresip/issues/731#issuecomment-500957006 did fixed the issue). HTTP serer on 127.0.0.1:8000 is not working as well. You can check

error log

```
open: ./httpd.dll LoadLibraryA() failed
open: ./sndfile.dll LoadLibraryA() failed
open: ./debug_cmd.dll LoadLibraryA() failed
All 1 useragent registered successfully! (170 ms)
>                             1111
fd_listen: fd=1056 flags=0x01 - Max 1024 fds
fd_listen: fd=1056 flags=0x01 - Max 1024 fds
fd_listen: fd=1056 flags=0x01 - Max 1024 fds
fd_listen: fd=1056 flags=0x01 - Max 1024 fds
fd_listen: fd=1056 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1112 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1116 flags=0x01 - Max 1024 fds
fd_listen: fd=1120 flags=0x01 - Max 1024 fds
fd_listen: fd=1120 flags=0x01 - Max 1024 fds
fd_listen: fd=1120 flags=0x01 - Max 1024 fds
fd_listen: fd=1120 flags=0x01 - Max 1024 fds
long async blocking: 291>100 ms (h=0x67d1d8a0 arg=0xd85003f0)
```

output log

```
baresip v0.6.1 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.
Local network address:  IPv4=:192.168.0.105 
[31mmodule httpd.dll: No such file or directory
[;maucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
[31mmodule sndfile.dll: No such file or directory
[;mwinwave: output devices: 1, input devices: 1
ausrc: winwave
auplay: winwave
vidsrc: dshow
medianat: stun
medianat: turn
medianat: ice
Populated 1 account
Populated 3 contacts
[31mmodule debug_cmd.dll: No such file or directory
[;mPopulated 2 audio codecs
Populated 1 audio filter
Populated 0 video codecs
Populated 0 video filters
baresip is ready.
154023@sip.zadarma.com: {0/UDP/v4} 200 OK (Zadarma server) [1 binding]
[31mstream: rtp_listen failed: af=AF_INET ports=1024-49152 (Too many open files)
[;m[31mstream: failed to create socket for media 'audio' (Too many open files)
[;m[31mmenu: ua_connect failed: Too many open files
[;mua: stop all (forced=0)
```

It was reported (see https://github.com/alfredh/baresip/issues/654) with a reference to your profile that there was the release for Windows 10. Please, can you just provide the builds.

**Comment by Ola-Palm** [comment]
Hi. To be able to use getopt i have used vcpkg install getopt then vcpkg integrate install to get the headerfiles visible for vs2019. Then it's possible to use -n <interface> to select interface to be used by baresip. I also change added HAVE_GETOPT in the projektfile
<https://github.com/microsoft/vcpkg>

I still have issues with 
fd_listen: fd=1168 flags=0x01 - Max 1024 fds
even though i've set FD_SETSIZE=2048 in the same projectfile.

**Comment by alexander-elgin** [comment]
@Ola-Palm Do you have binaries which work properly in Windows 10?

**Comment by Ola-Palm** [comment]
@alexander-elgin 
I need to fix the FD_SETSIZE, to get calls working.

**Comment by Ola-Palm** [comment]
After updating FD_SETSIZE in re projectfile to the same value as set in baresip projectfile, all is working.

**Comment by alexander-elgin** [comment]
@Ola-Palm Please, can you share the exe files?

**Comment by alfredh** [comment]
there are some errors in the VC Project file.

it would be nice if someone can update the VC file, test it, and send
the changes as a PR.

@alexander-elgin if you want binaries you can also try to ask
on the re-devel mailinglist.

**Comment by Ola-Palm** [comment]
I can update with my project files.
But currently the release config doesn’t work. I will try to find time to fix this during the weekend or the next coming week.
I’ll push current state to my fork of baresip in a new branch. Then perhaps we could make a PR from that branch when everything’s working.

Skickat från min iPhone

21 mars 2020 kl. 13:14 skrev Alfred E. Heggestad <notifications@github.com>:

﻿

there are some errors in the VC Project file.

it would be nice if someone can update the VC file, test it, and send
the changes as a PR.

@alexander-elgin<https://github.com/alexander-elgin> if you want binaries you can also try to ask
on the re-devel mailinglist.

**Comment by alexander-elgin** [comment]
Why can't you upload the binaries here or send them by email (you can find my email address on my profile page) to me?

**Comment by alexander-elgin** [comment]
@Ola-Palm Which patch did you use to fix the `FD_SETSIZE` issue https://github.com/alfredh/baresip/issues/731#issuecomment-500957006 or https://github.com/creytiv/re/commit/49834b7afd0fe31660108271ef7657a34caa6a6d?

**Comment by Ola-Palm** [comment]
@alexander-elgin 
I didn't use any patch. I changed the FD_SETSIZE=2048 in re projectfile. 
you will find this in re\mk\win32\re.vcxproj or by rightclick the re project and make the change in properties --> c/c++ -->preprocessor --> perprocessor definnitions. This is also set to the same value in baresip projectfile.
I still have som issues building a release version.

**Comment by alexander-elgin** [comment]
@Ola-Palm Please, can you share the binary files which work anyhow better?

**Comment by nicotyze** [comment]
Hi,
Here is an archive with the windows binaries (version: git master of the day , tested on Win10, cross compiled with mingw):
https://filesender.renater.fr/?s=download&token=b5035c23-17a0-b81c-eb8f-af8e074ec81d&lang=en
There is also a .bat to launch baresip and use it from an **experimental** (experimental => really dirty, please be aware of that) web interface (should work with others OS).

Hope this helps.

**Comment by alexander-elgin** [comment]
@nicotyze Many thanks for that. It works almost fine but the calls are not recorded. I think that's because you compiled the project without `sndfile`. I reported the issue (see https://github.com/alfredh/baresip/issues/672) and created a fix for that (see https://github.com/alexander-elgin/baresip-win32). I would be very thankful if you can include it into your build.
@nicotyze Please, can you share a guidance on how you compile the exe file (including the OS version, what compiler you used and where you got it, any fixes that you applied, versions of the re, rem, openssl, dirent and etc.)? Taking into account https://github.com/alfredh/baresip/issues/731, https://github.com/alfredh/baresip/issues/732, https://github.com/alfredh/baresip/issues/711, https://github.com/alfredh/baresip/issues/888, https://github.com/alfredh/baresip/issues/881, https://github.com/alfredh/baresip/issues/872, https://github.com/alfredh/baresip/issues/842, https://github.com/alfredh/baresip/issues/212 and even comments in this thread from the maintainers e.g. https://github.com/alfredh/baresip/issues/942#issuecomment-602035860 and https://github.com/alfredh/baresip/issues/942#issuecomment-602042767 I am not the only one who met issues with compilation for Windows

**Comment by nicotyze** [comment]
This is a detailed guide in order to generate/test windows binaries with sndfile support (among others):
https://github.com/nicotyze/Baresip-Win32

**Comment by alexander-elgin** [comment]
@nicotyze Many thanks for that
