### ISSUE TITLE
Outgoing call with non-default auplay fails

### ISSUE THREAD

**Issue by robdyck** [alfredh/baresip#945]
Baresip for desktop.
My preferred audio device is a headset ( plughw:3,0 ). The system default is the speaker. If baresip is configured to use the headset an outgoing call will fail when call is answered. Incoming calls work with either device. See attached verbose output.
[baresip-outgoing-fail.txt](https://github.com/alfredh/baresip/files/4365736/baresip-outgoing-fail.txt)

**Comment by alfredh** [comment]
perhaps the ringback tone is not stopped before audio is started ?

perhaps you can try to disable ringback tone in config:

```
ringback_disabled    yes
```

**Comment by robdyck** [comment]
Disabling ringback cures it. A race?

**Comment by alfredh** [comment]
your device handles only 1 client at the same time.

baresip assumes that the audio devices can be opened by multiple clients
at the same time, and that the devices can handle mixing.
for example the "call waiting" tone is played in the active stream, if there
is an incoming call.

you need to create a virtual ALSA device that supports mixing
and is mapped to your physical device. This has been asked by many people
already. Please refer to the ALSA documentation for how to do this.

**Comment by robdyck** [comment]
ALSA is a bit mysterious for me. I will do the research but first a quick question. is the default device a virtual device?

**Comment by alfredh** [comment]
yes, the default alsa device handles mixing and multiple access:

```
audio_player            alsa,default
```

if ALSA is a mystery for you, then you can also try some alternatives:

- pulse.so
- jack.so
- portaudio.so

**Comment by robdyck** [comment]
They are no less mysterious but that is my problem. My concern with audio is minimizing latency. To me that seems to suggest a hardware approach as much as possible.

**Comment by alfredh** [comment]
it is not a bug in baresip. you can disable the ringtone as a workaround.
