### ISSUE TITLE
run baresip on raspberry pi via omx render 

### ISSUE THREAD

**Issue by yangaphero** [alfredh/baresip#946]
int omx_display_enable(struct omx_state* st,
	int width, int height, int stride)
{
	unsigned int i;
	OMX_PARAM_PORTDEFINITIONTYPE portdef;
#ifdef RASPBERRY_PI
	OMX_CONFIG_DISPLAYREGIONTYPE config;
#endif
	OMX_ERRORTYPE err = 0;
	OMX_STATETYPE eState;//by ahpero
	info("omx:omx_update_size %d %d\n", width, height);
	
	//by aphero 2018-2-23	
	OMX_GetState(st->video_render, &eState);
	if (eState == OMX_StateExecuting) {
		err = OMX_SendCommand(st->video_render,OMX_CommandStateSet, OMX_StateIdle, NULL);//可以不用设置
		//info("OMX_SendCommand  OMX_StateIdle err=%d\n",err);
		err = OMX_SendCommand(st->video_render,OMX_CommandStateSet, OMX_StateLoaded, NULL);//可以不用设置
		//info("OMX_SendCommand  err=%d\n",err);
		err = OMX_SendCommand(st->video_render,OMX_CommandFlush, VIDEO_RENDER_PORT, NULL);
		//info("OMX_CommandFlush  err=%d\n",err);
		err = OMX_SendCommand(st->video_render,OMX_CommandPortDisable, VIDEO_RENDER_PORT, NULL);//必须关闭端口使能，否则无法设置端口
		//if (err) warning("OMX_CommandPortDisable: err\n");
		
		//释放渲染器的缓存空间，这里必须释放，否则vidframe_init_buf出现段错误
		if (st->buffers) {
			OMX_FreeBuffer(st->video_render, VIDEO_RENDER_PORT,st->buffers[0]); //默认是3个，portdef.nBufferCountActual＝３
			OMX_FreeBuffer(st->video_render, VIDEO_RENDER_PORT,st->buffers[1]); 
			OMX_FreeBuffer(st->video_render, VIDEO_RENDER_PORT,st->buffers[2]); 
			free(st->buffers);
			st->buffers=NULL;
			st->num_buffers = 0;
			st->current_buffer = 0;
		}
	}
	info("omx_update_size %d %d\n", width, height);

	#ifdef RASPBERRY_PI
	memset(&config, 0, sizeof(OMX_CONFIG_DISPLAYREGIONTYPE));
	config.nSize = sizeof(OMX_CONFIG_DISPLAYREGIONTYPE);
	config.nVersion.nVersion = OMX_VERSION;
	config.nPortIndex = VIDEO_RENDER_PORT;
	config.fullscreen = 1;
	config.set = OMX_DISPLAY_SET_FULLSCREEN;

	err |= OMX_SetParameter(st->video_render,
		OMX_IndexConfigDisplayRegion, &config);

	#endif

	memset(&portdef, 0, sizeof(OMX_PARAM_PORTDEFINITIONTYPE));
	portdef.nSize = sizeof(OMX_PARAM_PORTDEFINITIONTYPE);
	portdef.nVersion.nVersion = OMX_VERSION;
	portdef.nPortIndex = VIDEO_RENDER_PORT;

	/* specify buffer requirements */
	err |= OMX_GetParameter(st->video_render,
		OMX_IndexParamPortDefinition, &portdef);
	if (err != 0) {
		warning("omx_display_enable: couldn't retrieve port def\n");
		err = ENOMEM;
		goto exit;
	}

	info("omx:1-omx port definition: h=%d w=%d s=%d sh=%d\n",
		portdef.format.video.nFrameWidth,
		portdef.format.video.nFrameHeight,
		portdef.format.video.nStride,
		portdef.format.video.nSliceHeight);
		
	if(portdef.bEnabled != 1){//如果端口关闭就打开 by aphero
		err |=OMX_SendCommand(st->video_render,OMX_CommandPortEnable, VIDEO_RENDER_PORT, NULL);//前面关闭了，一定要打开,aphero
	}

**Comment by alfredh** [comment]
many thanks for the code

can you please clarify what you intend with this code ?
is it a bugreport or patch ?

**Comment by yangaphero** [comment]
When the received video resolution is different from the last time, using OMX can not output video, you can add these codes.

**Comment by alfredh** [comment]
thanks. would you please be so kind to create a Pull Request (PR) for this patch ?

I dont want to extract the portions of your code that looks like addition,
this is very error prone.

**Comment by alfredh** [comment]
closing the issue, please create a PR.
