### ISSUE TITLE
master fails to build on debian testing

### ISSUE THREAD

**Issue by haraldg** [alfredh/baresip#949]
Hi,

following the very easy build instructions from the README was not possible for me on debian testing arm64:

```
harald@teres:~/baresip$ make
/usr/share/re/re.mk:415: Could not detect ARCH
ERROR: Missing library files for libre. Check LIBRE_SO
make: *** [Makefile:187: sanity] Fehler 2
harald@teres:~/baresip$ dpkg -l "libre*"
||/ Name                Version         Architektur  Beschreibung
+++-===================-===============-============-===========================
ii  libre-dev           0.6.0-4         arm64        generic library for real-ti
ii  libre0              0.6.0-4         arm64        generic library for real-ti
[...]
harald@teres:~/baresip$ ARCH="arm64" make
ERROR: Missing library files for libre. Check LIBRE_SO
make: *** [Makefile:187: sanity] Fehler 2
```

BTW, thanks for this nice piece of software!

**Comment by haraldg** [comment]
Got around to try this on a x86 system and it is reproducible there.

**Comment by alfredh** [comment]
please use libre from git:

https://github.com/creytiv/re

and build and install:

```
$ cd re
$ make
$ sudo make install
```

and the same with librem.

then build baresip:

```
$ cd baresip
$ make
```

to override arch:

```
$ make ARCH=arm64
```

To dump the re build info:

```
$ cd re
$ make info
```

**Comment by haraldg** [comment]
Yes, building against the git version of the libraries fixes the problem.

I think debian/control should be updated to demand the proper versions.

**Comment by alfredh** [comment]
ok, please create a PR if you want the debian files changed.
