### ISSUE TITLE
crash on 32 bit armeabi-v7a cpu architecture

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#957]
baresip is crashing on 32 bit armeabi-v7a cpu architecture when call is started.  There is no crash if I revert commit https://github.com/alfredh/baresip/commit/3f2a18227adef0b4b9db2edc660c69862532bf2d.  This is pretty urgent. Can I do the revert on master?

**Comment by sreimers** [comment]
The ODICT_INT needs a conversion to int64_t:

https://github.com/alfredh/baresip/commit/3f2a18227adef0b4b9db2edc660c69862532bf2d#diff-9aaeeea7d049e7e72712e2431786c414R184

`...(int64_t)audio_jb_current_value(call_audio(call))...`

should fix this.

**Comment by juha-h** [comment]
I don't get it.  Make a pull request that includes the fix or revert https://github.com/alfredh/baresip/commit/3f2a18227adef0b4b9db2edc660c69862532bf2d.

**Comment by Ola-Palm** [comment]
Informationsklass: Sveriges Radio Intern


@Juha.. Sorry for the inconvinience.
Could you verify that casting to int64 at line 184 in audio.c fix this issue on a 32bit system.
from
audio_jb_current_value(call_audio(call)));
To
(int64_t)audio_jb_current_value(call_audio(call)));



I can update the PR.


Från: juha-h <notifications@github.com>
Skickat: den 6 april 2020 12:36
Till: alfredh/baresip <baresip@noreply.github.com>
Kopia: Subscribed <subscribed@noreply.github.com>
Ämne: Re: [alfredh/baresip] crash on 32 bit armeabi-v7a cpu architecture (#957)


I don't get it. Make a pull request that includes the fix or revert 3f2a182<https://github.com/alfredh/baresip/commit/3f2a18227adef0b4b9db2edc660c69862532bf2d>.

-

**Comment by juha-h** [comment]
Closed by 7de41392ae243e0bc602449c56909dc2f9d8ab6b.
