### ISSUE TITLE
MQTT / TCP on connection client state request

### ISSUE THREAD

**Issue by Roog** [alfredh/baresip#959]
Hi Alfred, 
I'm working with @djhenley and @Ola-Palm at Swedish Radio on our implementation of Baresip. As I hope you are aware, we are using Baresip on a daily basis and it's at the core of radio production at [Sveriges Radio](https://sverigesradio.github.io). 

So I just want to extend an enormous **THANK YOU** for the continuous improvements of Baresip. This magical application helps our journalist do their normal day to day work at ease with amazing sound quality and in these Covid-19 times also providing remote production capabilities!

So to the actual point.. :)

We are using the MQTT or TCP connection with a Node.js app (hoping to distribute this soon). While connected to the "bus" the messages arrives in a nice JSON formatted way. But when connecting at a later stage, like during a call, we need to get the current state. Therefor our app is sending the "/callstat" and "/uastat" command to get the current state. While this comes back as a "sort of" formatted JSON blob, there could be some improvements. We are now parsing the text blob to get some key things like,
- are we registered and with what credentials?
- are we in a call and with who?
- are we in a call with what settings?
In the best of worlds, we would like to get a JSON object with the current state.

So my question to you, 
- What is needed and where should we put a receiver for commands coming from the MQTT/TCP connection? (So that we could respond with a full JSON response).

- I'm suggesting a JSON response for the general state request, what is your opinion on the contents? and as mentioned above, the basic things are most important, like registration status and call status. 

- Is there anything that need to be considered for implementations not using SIP?

Best regards
Roger

```js
{
  accountId: "cuser-id|rogersan-0x7fc96e722770",
  accountName: "Display Name Account",
  settings {
    answermode: "auto|manual|..",
    callTransfer: true|false,
  },
  sip: {
    state: "registered|unregistered",
    registered: true|false,
    uri: "me@sip-example.com",
    displayName: "Me Nice Name",
    domain: "sip-example.com",
    authUser: "me",
    responseCode: "200 OK",
    SRV: sip-example.com.
    AF: "v4",
    regInterval: 3779,
    pubInterval: "??",
    nat: true|false,
    stun: {
      user: "",
      server: ""
    },
  },
  call {
    state: "disconnected|connecting|connected|disconnecting",
    peerUri: "you@sip-example.com",
    peerDisplayName: "You Nice Name",
    direction: "incoming|outgoing",
    started: "unix-timestamp",
    localAttributes: {
      minptime: "20"
      ptime: "20",
      lostPackets: 0
    },
    remoteAttributes: {
      ptime: "20",
      jitterBuffer: "200",
      jitterBufferType: "fixed|auto",
      qosRec: "<dscp-value-rtp>",
      lostPackets: 0
    }
  }
}

**Comment by premultiply** [comment]
Hi Rodger,
I have read a little bit about your very well done project.
We use baresip now it in our master control room applications (TV for now only) for production intercom connection, commentary audio, talkback and mix minus lines. It is really better and much more flexible than other legacy hardware boxes.

Our control interface architecture looks the same way. We are building a node.js Webapp which connects through MQTT, JSON and Websockets to baresip.

So I can second everything you have have written. I already improved the JSON responses there and there to make all responses at least parseble using JS regex. But this should be improved much further as you already mentioned.

What we are still missing on JSON is a way to display the negotiated/selected codec on the connection as we use many different peers. So I would like to add this to your list.

**Comment by alfredh** [comment]
Hi Roger,

at the moment the MQTT commands are implemented as a wrapper on top
of core commands. That means that any command implemented in core,
will be automatically available also via MQTT.

for your new command, I think we have 2 options:

1. create a new generic command that implements your proposal,
and writes the output as JSON

2. create an MQTT specific command for this, that is implemented in mqtt.so
this command will then not be available in core commands.


Alfred

**Comment by Roog** [comment]
Hi again, been trying to stay away from the computer during easter.

@premultiply it would be very interesting to know how you are solving it with the intercom connections :) The improvements of the JSON formatting was a great step in the right direction.
- So do i understand you, that in the JSON (on connection status object) you would like to have like:
`call.localAttributes.codec/sdp` and `call.remoteAttributes.codec/sdp` ?

@alfredh ah yes. I'm in favor of the (2) option since it will be quite specific. But on the other hand, we have made it so we can choose if our Node.js application uses MQTT or the TCP connection. I'm in favor of the TCP connection since it doesn't require a broker (even though it is simple to install, it's just one extra thing). So to not deviate too much between the API:s, maybe the generic command option is not so bad (1). 
- Where are these general commands caught, is it in one location like 'menu' or 'event'?

Best regards
Roger

**Comment by alfredh** [comment]
you can start by implemented your command in e.g.
menu.so or debug_cmd.so

the syntax of commands is:

```c
static const struct cmd debugcmdv[] = {
{"conf_reload", 0,       0, "Reload config file",     reload_config       },
{"config",      0,       0, "Print configuration",    cmd_config_print    },
{"loglevel",   'v',      0, "Log level toggle",       cmd_log_level       },
{"main",        0,       0, "Main loop debug",        re_debug            },
/* ... */
};
```

add a new entry for your command, and a callback handler for it.

I think it is best to just start hacking some working code, and submit it as a PR.
then I can help with testing and review, and we will take it from there.

**Comment by alfredh** [comment]
please note that we mainly use the issue tracker to track defects.

For your feature request, please create a PR or add the item to the Roadmap.

https://github.com/alfredh/baresip/wiki/Guidelines-for-reporting-Issues
