### ISSUE TITLE
audio problems in Windows

### ISSUE THREAD

**Issue by jobo-zt** [alfredh/baresip#960]
The master code is tested in Windows 10, with the following problems.（test winows10 baresip <-> linux(RPI) baresip）
1. The local audio has no code to spread to the remote.
2. During the meeting, the local cannot hang up normally. (neither remote nor local)

//log
PS D:\baresip\bin_vpn>  .\baresip-win32.exe -e "/dial sip:0755000002@10.8.0.2"
baresip v0.6.5 Copyright (C) 2010 - 2020 Alfred E. Heggestad et al.
Binding to interface or IP address '10.8.0.3'
Local network address:  IPv4={E6BEA673-6CFE-46B8-A7E8-B6CEB6F98FBB}|10.8.0.3
httpd: listening on 0.0.0.0:8000
aucodec: opus/48000/2
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: speex_pp
winwave: output devices: 1, input devices: 1
ausrc: winwave
auplay: winwave
vidcodec: H264
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidcodec: H265
avcodec: using H.264 encoder 'libx264' -- libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.264 decoder 'h264' -- H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.265 encoder 'libx265' -- libx265 H.265 / HEVC
avcodec: using H.265 decoder 'hevc' -- HEVC (High Efficiency Video Coding)
vidsrc: dshow
vidisp: sdl
medianat: stun
medianat: turn
medianat: ice
medianat: ice-lite
Populated 1 account
glog: module init
Could not create logging file: No such file or directory
Could not create logging file: No such file or directory
Populated 3 contacts
Populated 3 audio codecs
Populated 1 audio filter
Populated 5 video codecs
Populated 0 video filters
baresip is ready.
/dial sip:0755000002@10.8.0.2
ua: using best effort AF: af=AF_INET
call: connecting to 'sip:0755000002@10.8.0.2'..
unhandeled request from 10.8.0.3:5060: REGISTER sip:10.8.0.3
reg: sip:0755000003@10.8.0.3: 501 Not Implemented (baresip v0.6.5 (?/win32))
call: SIP Progress: 180 Ringing (/)
play: /usr/share/baresip/ringback.wav: No such file or directory
stream: incoming rtp for 'audio' established, receiving from 10.8.0.2:18348
audio: Set audio decoder: opus 48000Hz 2ch
audio: player started with sample format S16LE
long async blocking: 240>100 ms (h=0xfc9f00 arg=0x1592e38)
stream: update 'audio'
stream: update 'video'
audio: Set audio encoder: opus 48000Hz 2ch
speex_pp: Speex preprocessor loaded: srate = 48000Hz
audio: source started with sample format S16LE
audio tx pipeline:     winwave ---> speex_pp ---> opus
audio rx pipeline:     winwave <--- opus
Set video encoder: H264 packetization-mode=0 (2000000 bit/s, 25.00 fps)
avcodec: h264 encoder activated
dshow: got device '' id=0
Set video decoder: H264 packetization-mode=0
avcodec: h264 decoder activated
avcodec: decode: hardware accel disabled
0755000003@10.8.0.3: Call established: sip:0755000002@10.8.0.2
long async blocking: 715>100 ms (h=0xfc9f00 arg=0x1593180)
stream: incoming rtp for 'video' established, receiving from 10.8.0.2:48144
[h264 @ 038e8bc0] no frame!
avcodec: avcodec_send_packet error, packet=26 bytes, ret=-1094995529 (Invalid data found when processing input)
video: H264 decode error (seq=9012, 5 bytes): Unknown error
video: receiving with resolution 352 x 288 and format 'yuv420p'
sdl: created renderer 'direct3d'
long async blocking: 308>100 ms (h=0xfc9f00 arg=0x15a0890)
[libx264 @ 038d6940] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 038d6940] profile Constrained Baseline, level 3.1, 4:2:0, 8-bit
long async blocking: 762>100 ms (h=0xf81760 arg=0x158fcd8).8/22.0
long async blocking: 102>100 ms (h=0xfad4c0 arg=0x15e1ec0).7/22.8
unhandeled request from 10.8.0.3:5060: REGISTER sip:10.8.0.34/21.0
reg: sip:0755000003@10.8.0.3: 501 Not Implemented (baresip v0.6.5 (?/win32))
long async blocking: 108>100 ms (h=0xfad4c0 arg=0x15e1ec0)0.5/22.8
long async blocking: 617>100 ms (h=0xf7b950 arg=(nil))ps=10.0/19.0
long async blocking: 108>100 ms (h=0xf7b950 arg=(nil))ps=10.0/19.0
[0:01:43] audio=0/28390 video=506620/281671 (bit/s) efps=10.0/14.5

**Comment by alfredh** [comment]
hi @75535552 

I just wanted to check if you are a real person and not a robot.

Are you working for a company that is using the product ?

if the request for help is coming from a real person, it is easier for me
to help you.

if the request is coming from 981723981264912763912837 I am not really sure what to do :)


Alfred

**Comment by 75535552** [comment]
hi @alfredh 
I'm a multimedia communications developer and I'm sure it's not a robot. It's not used in my project. Baresip implementation is very good. I like it in my spare time. I put it in RPI, which can connect with the Windows client very well. when the code is updated, I will test it in windows and Linux. about "981723981264912763912837" I don't quite understand what line and column marks my from. I don't think it's valid

**Comment by alfredh** [comment]
if you have signed your request with a real name, it would become more personal,
and hence easier for me to help you.

if I receive a bug report from 12345 it is not really easy for me to take it seriously.
it can be a automated bot.

regarding your issue:

* what OS version are you running (exact) ?

* what kind of audio hardware do you use ?

* please share the full config+accounts

* have you tried if the `/auloop` command is working?

* please dump the output of `/audio_debug` command after 10 second in the call

* add some debug code here and check if samples are coming:

https://github.com/alfredh/baresip/blob/master/modules/winwave/src.c#L81

* this line: "glog: module init" is not from stock baresip. Please use a clean baresip
from git HEAD without any local modifications when reporting.

**Comment by jobo-zt** [comment]
Thanks. I'll update it later.

**Comment by jobo-zt** [comment]
hi @alfredh 

I git reset --hard *** without any. in win10 thinkpad t470s IDE is vs2015

I went back to the code to confirm that the problem was introduced in the following submission. The previous version is OK.
//
Revision: 3f2a18227adef0b4b9db2edc660c69862532bf2d
Author: Ola Palm <ola.palm@me.com>
Date: 2020/4/4 15:43:41
Message:
Aubuf current jb value to mqtt (#954)
* Aubuf current jb value to mqtt
* fix comments.
* changed type for current_jb value to uint32
* another type update to get by clang on mac
* tabs not spaces
----
Modified: include/baresip.h
Modified: modules/mqtt/publish.c
Modified: src/audio.c
Modified: src/event.c

//config
#
# baresip configuration
#

#------------------------------------------------------------------------------

# Core
poll_method		select		# poll, select

# SIP
sip_listen		0.0.0.0:5060
#sip_certificate	cert.pem
#sip_cafile		/etc/ssl/certs/ca-certificates.crt

# Call
call_local_timeout	120
call_max_calls		4

# Audio
#audio_path		/usr/share/baresip
audio_player		winwave,nil
audio_source		winwave,nil
audio_alert		winwave,nil
#ausrc_srate		48000
#auplay_srate		48000
#ausrc_channels		0
#auplay_channels	0
#audio_txmode		poll		# poll, thread
audio_level		no
ausrc_format		s16		# s16, float, ..
auplay_format		s16		# s16, float, ..
auenc_format		s16		# s16, float, ..
audec_format		s16		# s16, float, ..
audio_buffer		20-160		# ms

# Video
#video_source		dshow,nil
#video_display		sdl,nil
video_size		352x288
video_bitrate		500000
video_fps		25.00
video_fullscreen	no
videnc_format		yuv420p

# AVT - Audio/Video Transport
rtp_tos			184
#rtp_ports		10000-20000
#rtp_bandwidth		512-1024 # [kbit/s]
rtcp_mux		no
jitter_buffer_delay	5-10		# frames
rtp_stats		no
#rtp_timeout		60

# Network
#dns_server		1.1.1.1:53
#dns_server		1.0.0.1:53
#net_interface		eth0
#net_interface		192.168.9.100
net_interface		10.8.0.3

#BFCP
bfcp_proto udp

#------------------------------------------------------------------------------
# Modules

#module_path		/usr/lib/baresip/modules

# UI Modules
module			wincons.dll
#module			cons.dll
#module			evdev.dll
#module			httpd.dll

# Audio codec Modules (in order)
#module			opus.dll
#module			amr.dll
#module			g7221.dll
#module			g722.dll
#module			g726.dll
module			g711.dll
#module			gsm.dll
#module			l16.dll
#module			mpa.dll
#module			codec2.dll
#module			ilbc.dll
#module			isac.dll

# Audio filter Modules (in encoding order)
#module			vumeter.dll
#module			sndfile.dll
#module			speex_pp.dll
#module			plc.dll
#module			webrtc_aec.dll

# Audio driver Modules
module			winwave.dll
#module			jack.dll
#module			portaudio.dll
#module			aubridge.dll
#module			aufile.dll

# Video codec Modules (in order)
#module			avcodec.dll
#module			vp8.dll
#module			vp9.dll

# Video filter Modules (in encoding order)
#module			selfview.dll
#module			snapshot.dll
#module			swscale.dll
#module			vidinfo.dll

# Video source modules
module			dshow.dll
#module			x11grab.dll
#module			cairo.dll
#module			vidbridge.dll

# Video display modules
#module			x11.dll
#module			sdl.dll
#module			fakevideo.dll

# Audio/Video source modules
#module			avformat.dll
#module			rst.dll
#module			gst.dll
#module			gst_video.dll

# Compatibility modules
#module			ebuacip.dll

# Media NAT modules
module			stun.dll
module			turn.dll
module			ice.dll
#module			natpmp.dll
#module			pcp.dll

# Media encryption modules
#module			srtp.dll
#module			dtls_srtp.dll
#module			zrtp.dll


#------------------------------------------------------------------------------
# Temporary Modules (loaded then unloaded)

module_tmp		uuid.dll
module_tmp		account.dll


#------------------------------------------------------------------------------
# Application Modules

module_app		auloop.dll
#module_app		b2bua.dll
module_app		contact.dll
module_app		debug_cmd.dll
#module_app		echo.dll
#module_app		gtk.dll
module_app		menu.dll
#module_app		mwi.dll
#module_app		presence.dll
#module_app		syslog.dll
#module_app		mqtt.dll
#module_app		ctrl_tcp.dll
module_app		vidloop.dll


#------------------------------------------------------------------------------
# Module parameters


# UI Modules parameters
cons_listen		0.0.0.0:5555 # cons

http_listen		0.0.0.0:8000 # httpd - server

ctrl_tcp_listen		0.0.0.0:4444 # ctrl_tcp

evdev_device		/dev/input/event0

# Opus codec parameters
opus_bitrate		28000 # 6000-510000
#opus_stereo		yes
#opus_sprop_stereo	yes
#opus_cbr		no
#opus_inbandfec		no
#opus_dtx		no
#opus_mirror		no
#opus_complexity	10
#opus_application	audio	# {voip,audio}
#opus_samplerate	48000
#opus_packet_loss	10	# 0-100 percent

# Opus Multistream codec parameters
#opus_ms_channels	2	#total channels (2 or 4)
#opus_ms_streams		2	#number of streams
#opus_ms_c_streams	2	#number of coupled streams

vumeter_stderr		yes

#jack_connect_ports	yes

# Selfview
video_selfview		window # {window,pip}
#selfview_size		64x64

# ICE
ice_debug		no

# ZRTP
#zrtp_hash		no  # Disable SDP zrtp-hash (not recommended)

# Menu
#menu_bell		yes
#redial_attempts	0 # Num or <inf>
#redial_delay		5 # Delay in seconds
#ringback_disabled	no
#statmode_default	off

# avcodec
#avcodec_h264enc	libx264
#avcodec_h264dec	h264
#avcodec_h265enc	libx265
#avcodec_h265dec	hevc
#avcodec_hwaccel	none

# mqtt
#mqtt_broker_host	127.0.0.1
#mqtt_broker_port	1883
#mqtt_broker_clientid	baresip01
#mqtt_broker_user	user
#mqtt_broker_password	pass
#mqtt_basetopic		baresip/01

# sndfile
#snd_path		/tmp

# EBU ACIP
#ebuacip_jb_type	fixed	# auto,fixed

//accounts
<sip:0755000003@10.8.0.3>;auth_pass=0755000003

I will continue to provide other info.

**Comment by jobo-zt** [comment]
hi @alfredh @Ola Palm
I found waveInGetPosition function in waveInCallback.

[waveInGetPosition is no longer supported for use as of Windows Vista. Instead, use IAudioClock::GetPosition
https://docs.microsoft.com/zh-cn/windows/win32/api/mmeapi/nf-mmeapi-waveingetposition?redirectedfrom=MSDN

**Comment by alfredh** [comment]
I pushed a fixed that uses `tmr_jiffies_usec` instead

if you want to use IAudioClock::GetPosition then please make a PR for that.

Many thanks for reporting the bug!
