### ISSUE TITLE
Honor format options in SDP for Opus

### ISSUE THREAD

**Issue by nivex** [alfredh/baresip#961]
Polycom phones can only deal with Opus audio encoded at 16KHz. They indicate this in their SDP with the following:
```
a=rtpmap:107 opus/48000/2
a=fmtp:107 maxplaybackrate=16000;sprop-maxcapturerate=16000;maxaveragebitrate=24000
```
If audio is sent with a wider audio bandwidth, it is simply not played resulting in essentially one-way audio (baresip has no problem decoding what the Polycom is sending it). It would be useful if baresip could configure its Opus encoder with these values received in the SDP.

I can work around this by setting `opus_bitrate` to 16000 in `~/.baresip/config`, thus forcing the encoding audio rate down to 16Khz, but this is limiting when talking to other devices that are more capable.

Here is the full SIP message with SDP as seen from the intermediate Asterisk box for your reference: [sdp-to-baresip.txt](https://github.com/alfredh/baresip/files/4466751/sdp-to-baresip.txt)

**Comment by alfredh** [comment]
is there any chance that you can try to implement this logic,
and submit it as a PR ?

if you can make a PR with the suggested code, I am happy to help you
to progress the PR and get it implemented in a proper way.

you can start with the following steps:

1. try to extract the given parameter from the remote SDP fmtp

2. if present, try to pass the parameter value back the core via the aucodec api

3. somehow in the core, change the samplerate if this condition occured.


Alfred

**Comment by alfredh** [comment]
a pull request is welcome for this:

https://github.com/alfredh/baresip/wiki/Guidelines-for-reporting-Issues
