### ISSUE TITLE
sipsess_conn_handler hardwires VIDMODE_ON

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#962]
Currently ua.c sipsess_conn_handler() hardwires VIDMODE_ON when incoming call is handled:
```
	err = ua_call_alloc(&call, ua, VIDMODE_ON, msg, NULL, to_uri, true);
```
User who answers the call should be able to tell if video stream is on or off when the call starts.

**Comment by juha-h** [comment]
How about adding to struct account
```
	enum vidmode vmode;          /**< Video mode for incoming calls      */
```
and account_set_vmode() API function?

Once done, sipsess_conn_handler() ua_call_alloc call could look like this:
```
err = ua_call_alloc(&call, ua, ua->acc->vmode, msg, NULL, to_uri, true);
```

**Comment by juha-h** [comment]
Best solution would be if vmode param could be added to ua_answer API function:
```
int  ua_answer(struct ua *ua, struct call *call, enum vidmode vmode);
```
same way as it is in ua_connect().  Then user could decide on the fly if he/she wants to have video stream in the call.

**Comment by alfredh** [comment]
here is a suggestion:

```c
int call_answer(struct call *call, uint16_t scode, enum vidmode vidmode)
{
    if (vidmode == VIDMODE_OFF)
        call->video = mem_deref(call->video);
}
```

adding a vidmode parameter to the API should be a fine solution, I think ..

**Comment by juha-h** [comment]
Looks good.  For apps that do not call call_answer() directly, but via ua_answer(), would it be OK to also include vidmode param to ua_answer:
```
int ua_answer(struct ua *ua, struct call *call, enum vidmode vidmode)
{
	if (!ua)
		return EINVAL;

	if (!call) {
		call = ua_call(ua);
		if (!call)
			return ENOENT;
	}

	return call_answer(call, 200, vidmode);
}
```

**Comment by alfredh** [comment]
yes, ua_answer and call answer should have a similar signature.

**Comment by juha-h** [comment]
Done by https://github.com/alfredh/baresip/commit/b01f649c06e34cf7a3f6a6072796b96e182f3088.
