### ISSUE TITLE
;audio_codecs="" and 'video_codecs="" is equal to all codecs

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#964]
Is it intentional or bug that `;audio_codecs=""` is equal to all audio codecs and `;video_codecs=""` is equal to all video_codecs rather than no audio/video codecs?

**Comment by alfredh** [comment]
this depends on how you look at it.

why did the user set `audio_codecs=""` ?

this could have one out of two meanings:

1. Use zero audio codecs (then he would get no audio)
2. Use all default audio codecs, same as parameter being absent

I think there is no good answer for that, and open to interpretation.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> why did the user set `audio_codecs=""` ?
> 
> this could have one out of two meanings:
> 
> 1. Use zero audio codecs (then he would get no audio)
> 2. Use all default audio codecs, same as parameter being absent
> 
> I think there is no good answer for that, and open to interpretation.

I noticed this when I set `video_codecs=""` and thought that it would
cause video being off for that account, but it didn't work, because it
defaulted to all video codecs.

If there is no [audio|video]_codec in accounts then it could equal to
all codecs (i.e. the user does care), but if user explicitly tells that
codecs are = "", then it could mean that there is none.

**Comment by alfredh** [comment]
if you want to disable video, then you can unload the video codec modules.

what you are describing, is a very rare corner case. I think we should keep the current logic,
and not spend too much time on discussing it.

**Comment by juha-h** [comment]
Fine. I agree it is a corner case, useful, for example, when there is two or more accounts in accounts file and some of them want to use video and some don't.
