### ISSUE TITLE
Low FPS performance in VOIP call

### ISSUE THREAD

**Issue by Syirrus** [alfredh/baresip#965]
First, I want to say thank you the owner and all the contributions to this project. After trying various cmd sip client's this one just works. 

I'm a bit of a newbie, but I managed to get things up and working with video on a Raspberry Pi Zero. The only issue I'm having is the video is slow and delayed by about 3-5 seconds and the framerate is maybe 5 fps.  I know what your thinking.... its a Pi Zero and those things are Armv6 which is slow. However, when using gstreamer1.0; I can stream video from the camera to another computer on my network at: CPU usage 10 - 30% and at 640x480 @ 25 fps.  

My question is, how can I obtain better performance during a video call with baresip?   I'm pretty sure I'm probably not using the right codec, (openh264 is install) or I don't have a hardware accelerated module loaded. Can anyone help?  

Below is the video sections of my `config` file:

-------------------------------------

#Video
video_source            v4l2,/dev/video0
#video_display          x11,nil
video_size              352x288
video_bitrate           500000
video_fps               25.00
video_fullscreen        no
videnc_format           yuv420p

#Video codec Modules (in order)
module                  avcodec.so
#module                 vp8.so
#module                 vp9.so

#Video filter Modules (in encoding order)
#module                 selfview.so
#module                 snapshot.so
#module                 swscale.so
#module                 vidinfo.so

#Video source modules
module                  v4l2.so
#module                 v4l2_codec.so
#module                 x11grab.so
#module                 cairo.so
#module                 vidbridge.so

#Video display modules
#module                 directfb.so
#module                 x11.so
#module                 sdl.so
#module                 fakevideo.so

#Audio/Video source modules
module                  avformat.so
#module                 rst.so
#module                  gst.so
#module                  gst_video.so

-------------------------------------

Here is a copy of the `status log` when running baresip

aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
ausrc: alsa
auplay: alsa
vidcodec: H264
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidcodec: H265
avcodec: using H.264 encoder 'libx264' -- libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.264 decoder 'h264' -- H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.265 decoder 'hevc' -- HEVC (High Efficiency Video Coding)
vidsrc: v4l2
ausrc: avformat
vidsrc: avformat
medianat: stun
medianat: turn
medianat: ice
Populated 1 account
Populated 3 contacts
Populated 2 audio codecs
Populated 0 audio filters
Populated 5 video codecs
Populated 0 video filters
baresip is ready.

-------------------------------------

Any ideas? I'm really new to video encoders and such. All I want is close to real-time stream as possible given my hardware constraints. As eluded to before, with gstreamer1.0 I get excellent performance on this hardware and the latency is maybe 500ms with 25fps or more.

**Comment by mrcasablr** [comment]
Have you tried this? - https://github.com/alfredh/baresip/tree/master/modules/omx

**Comment by Syirrus** [comment]
@mrcasablr how would you go about compiling this and implementing this.  When I run gcc omx.c I get and error.  I'm a noob.

**Comment by alfredh** [comment]
I think you should first try to determine what is causing the slowness,
is it the encoder or decode. Try to test the following:

1. Encoding only (no decoding, disable source on remote peer)
2. Decoding only (no encoding, disable local video source)

my guess would be encoding, but you need to test/verify that.

then, check which codecs your ffmpeg supports:

from the ffmpeg source code:

```
$ ./configure --list-encoders | grep omx
flac                    mpeg4_omx               text
h264_omx                pcm_alaw                vp8_vaapi
```

perhaps the codec *h264_omx* can be used ?

in your local ffmpeg installation, you can check which codecs it supports:

```
$ ffmpeg -hide_banner -encoders | grep 264
 V..... libx264              libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (codec h264)
 V..... libx264rgb           libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 RGB (codec h264)
 V..... h264_videotoolbox    VideoToolbox H.264 Encoder (codec h264)
```

please run the above command, and paste the output here.

NOTE: The omx.so module is for video display, and can be compiled with:

`$ make EXTRA_MODULES=omx`

**Comment by alfredh** [comment]
You also need to research the topic of hardware codecs on RPI:

https://www.raspberrypi.org/forums/viewtopic.php?t=256572

**Comment by Syirrus** [comment]
@alfredh  Thank you for responding. I think I have a better understanding.  I definitely need hardware encoding to send the video out from baresip. I don't really need to receive video at all. I just want to send video and ignore receiving it.  The CPU is being taxed when encoding via software h264 in baresip.  

I ran the above commands and the output looks identical to your illustrations. 
I have tried repeatedly to compile. However, when I actually try to compile FFmpeg from source it fails with the following message:  

`ERROR: OpenMAX IL headers from raspberrypi/firmware not found.`

I google this to death and I installed the raspberrypi kernel headers per one of the Google posts.

I still get that error and for the life of me, I cannot figure out how to solve this. FFmpeg with omx_h264 support stands in my way :(. It's strange.

**Comment by Syirrus** [comment]
> You also need to research the topic of hardware codecs on RPI:
> 
> https://www.raspberrypi.org/forums/viewtopic.php?t=256572

@alfredh I think I have made some progress.  
I was finally able to properly install omx_h264 onto my pi. 

When I run the following command: `ffmpeg -hide_banner -encoders | grep 264`

 _V..... libx264              libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (codec h264)
 V..... libx264rgb           libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 RGB (codec h264)
 V..... h264_omx             OpenMAX IL H.264 video encoder (codec h264)
 V..... h264_v4l2m2m         V4L2 mem2mem H.264 encoder wrapper (codec h264)
 V..... h264_vaapi           H.264/AVC (VAAPI) (codec h264)_

So, it appears that I have HW acceleration installed via ffmpeg. 

Now, I just don't see how I can configure baresip to use the encoder.  How would you do that in the baresip `config` file?
I only need to be able to transmit video on the pi. I don't need to receive (decode) it.

**Comment by Syirrus** [comment]
> I think you should first try to determine what is causing the slowness,
> is it the encoder or decode. Try to test the following:
> 
> 1. Encoding only (no decoding, disable source on remote peer)
> 2. Decoding only (no encoding, disable local video source)
> 
> my guess would be encoding, but you need to test/verify that.
> 
> then, check which codecs your ffmpeg supports:
> 
> from the ffmpeg source code:
> 
> ```
> $ ./configure --list-encoders | grep omx
> flac                    mpeg4_omx               text
> h264_omx                pcm_alaw                vp8_vaapi
> ```
> 
> perhaps the codec _h264_omx_ can be used ?
> 
> in your local ffmpeg installation, you can check which codecs it supports:
> 
> ```
> $ ffmpeg -hide_banner -encoders | grep 264
>  V..... libx264              libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (codec h264)
>  V..... libx264rgb           libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 RGB (codec h264)
>  V..... h264_videotoolbox    VideoToolbox H.264 Encoder (codec h264)
> ```
> 
> please run the above command, and paste the output here.
> 
> NOTE: The omx.so module is for video display, and can be compiled with:
> 
> `$ make EXTRA_MODULES=omx`

Also, I tried to compile the EXTRA_MODULES=omx and I get the following error:

make EXTRA_MODULES=omx
  CC [M]  build-arm6/modules/omx/omx.o
In file included from modules/omx/omx.c:10:
modules/omx/omx.h:13:10: fatal error: OMX_Core.h: No such file or directory
 #include <OMX_Core.h>

Any ideas?

**Comment by juha-h** [comment]
Syirrus writes:

> Also, I tried to compile the EXTRA_MODULES=omx and I get the following error:
> 
> make EXTRA_MODULES=omx
>   CC [M]  build-arm6/modules/omx/omx.o
> In file included from modules/omx/omx.c:10:
> modules/omx/omx.h:13:10: fatal error: OMX_Core.h: No such file or directory
>  #include <OMX_Core.h>
> 
> Any ideas?

Check where you have installed ffmpeg include files and libraries and
then, if needed, use -I and -L flags to point to those dirs.

**Comment by Syirrus** [comment]
> Syirrus writes:
> Also, I tried to compile the EXTRA_MODULES=omx and I get the following error: make EXTRA_MODULES=omx CC [M] build-arm6/modules/omx/omx.o In file included from modules/omx/omx.c:10: modules/omx/omx.h:13:10: fatal error: OMX_Core.h: No such file or directory #include <OMX_Core.h> Any ideas?
> Check where you have installed ffmpeg include files and libraries and then, if needed, use -I and -L flags to point to those dirs.

Thank you for the suggestion. I have updated things accordingly. 
I believe I'm almost there though.  Everything works but video unfortunately.  
When I run, here is the error and output: `baresip`

[ERROR]
[AVHWDeviceContext @ 0x1483d40] No VA display found for device: .
avcodec: Failed to create HW device (Invalid argument)
module avcodec.so: Operation not supported
____
[BARESIP OUTPUT LOG]
baresip v0.6.6 Copyright (C) 2010 - 2020 Alfred E. Heggestad et al.
Local network address:  IPv4=wlan0|192.168.1.22  IPv6=wlan0|2a01:c23:7c57:ea00:ba27:ebff:fe1a:72af
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
ausrc: alsa
auplay: alsa
vidcodec: H264
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidcodec: H265
avcodec: using H.264 encoder 'libx264' -- libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.264 decoder 'h264' -- H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.265 encoder 'libx265' -- libx265 H.265 / HEVC
avcodec: using H.265 decoder 'hevc' -- HEVC (High Efficiency Video Coding)
avcodec: enable hwaccel using 'vaapi'
avcodec: decode: using hardware pixel format 'vaapi_vld'
[AVHWDeviceContext @ 0x1483d40] No VA display found for device: .
avcodec: Failed to create HW device (Invalid argument)
module avcodec.so: Operation not supported
vidcodec: VP8
vidcodec: VP9
vidsrc: v4l2
v4l2_codec inited
vidcodec: H264
vidsrc: v4l2_codec
ausrc: avformat
vidsrc: avformat
medianat: stun
medianat: turn
medianat: ice
Populated 1 account
Populated 3 contacts
Populated 2 audio codecs
Populated 0 audio filters
Populated 3 video codecs
Populated 0 video filters
baresip is ready.
____

[FFMPEG LOG]
ffmpeg version 4.1.4-1+rpt7~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Raspbian 8.3.0-6+rpi1)
  configuration: --prefix=/usr --extra-version='1+rpt7~deb10u1' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --libdir=/usr/lib/arm-linux-gnueabihf --cpu=arm1176jzf-s --arch=arm
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Hyper fast Audio and Video encoder

____
Any ideas as to what I'm missing?

**Comment by mrcasablr** [comment]
@Syirrus see - https://github.com/alfredh/baresip/tree/master/modules/omx

You have update your baresip configuration for omx module. I'm keen to use baresip on pi zero w and I hope you get it working. I use an rpi 4b now and want to replace with pi zero w

**Comment by Syirrus** [comment]
> @Syirrus see - https://github.com/alfredh/baresip/tree/master/modules/omx
> 
> You have update your baresip configuration for omx module. I'm keen to use baresip on pi zero w and I hope you get it working. I use an rpi 4b now and want to replace with pi zero w

I recompiled baresip with the omx module with limited success. During the 'make' process, it error'd  but created the omx.so.  When adding the omx.so module to the config file; baresip loads, but then throws a segmentation fault. 

In spite of this, I did however have some success with getting the pi camera and sound to work with baresip. It seems to work with HW acceleration when I set the avcodec_h264enc to h264_omx. It renders at 30 fps @ 640x480 but the there are some color chromatic aberrations in the video feed.  CPU usage is about 75% and the latency is very low.  I used microsip (for windows) to test the video call. I'm still having trouble getting it to work with vaapi though as explained above. If anyone know how to removed the color abberations and sometimes (green lines in the feed) that would be awesome!

**Comment by Syirrus** [comment]
Sorry guys, I hope that I'm not blowing up your inboxes.  
I just wanted to share my finds and proof that baresip works with the pi zero w. 
[COLOR PROBLEM](https://drive.google.com/file/d/1g6T2ZJHRIwR-QCATYvcSaw4DuqKyghPy/view)
[HTOP](https://drive.google.com/file/d/16D2gxXVTwL7ZvWrSBzjlLCMrUmXznpR1/view)

**Comment by mrcasablr** [comment]
@Syirrus good progress!  See here to flip the camera - https://www.raspberrypi.org/forums/viewtopic.php?t=211271 you can do this before you start baresip

Do you need 30fps? try something lower. Could you also post your baresip config?

**Comment by Syirrus** [comment]
> @Syirrus good progress! See here to flip the camera - https://www.raspberrypi.org/forums/viewtopic.php?t=211271 you can do this before you start baresip.
> 
> v4l2-ctl has plenty of options to tweak the camera and it may help with picture quality - https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=62364&start=500
> 
> Do you need 30fps? try something lower. Could you also post your baresip config? Out of curiosity, what audio hardware are you using?

I tried to lower the fps in the config file, but regardless it reports 30 fps.
The sounds card I'm using is:  [seeed-voice](https://github.com/respeaker/seeed-voicecard) 2 mic version (hat)

Here is my config file. Enjoy.  Also, hopefully someone can help me with the camera rotation issue.  Thank you for the link, I will check it out and see if this doesn't remedy the color aberration issue. 
_______

#
# baresip configuration
#

#------------------------------------------------------------------------------

# Core
poll_method             epoll           # poll, select, epoll ..

# SIP
#sip_listen             0.0.0.0:5060
#sip_certificate        cert.pem
#sip_cafile             /etc/ssl/certs/ca-certificates.crt

# Call
call_local_timeout      120
call_max_calls          4

# Audio
audio_path              /usr/local/share/baresip
audio_player            alsa,default
audio_source            alsa,default
audio_alert             alsa,default
#ausrc_srate            48000
#auplay_srate           48000
#ausrc_channels         0
#auplay_channels        0
#audio_txmode           poll            # poll, thread
audio_level             no
ausrc_format            s16             # s16, float, ..
auplay_format           s16             # s16, float, ..
auenc_format            s16             # s16, float, ..
audec_format            s16             # s16, float, ..
audio_buffer            20-160          # ms

# Video
video_source            v4l2,/dev/video0
# video_display         omx,nil
#video_display           x11,nill
#video_size             352x288
video_size              640x480
#video_bitrate          500000
video_bitrate           1000000
video_fps               30.00
video_fullscreen        no
videnc_format           yuv420p

# AVT - Audio/Video Transport
rtp_tos                 184
#rtp_ports              10000-20000
#rtp_bandwidth          512-1024 # [kbit/s]
rtcp_mux                no
jitter_buffer_delay     5-10            # frames
rtp_stats               no
#rtp_timeout            60

# Network
#dns_server             1.1.1.1:53
#dns_server             1.0.0.1:53
#net_interface          wlan0

#------------------------------------------------------------------------------
# Modules

module_path             /usr/local/lib/baresip/modules

# UI Modules
module                  stdio.so
#module                 cons.so
#module                 evdev.so
#module                 httpd.so

# Audio codec Modules (in order)
#module                 opus.so
#module                 amr.so
#module                 g7221.so
#module                 g722.so
#module                 g726.so
module                  g711.so
#module                 gsm.so
#module                 l16.so
#module                 mpa.so
#module                 codec2.so
#module                 ilbc.so
#module                 isac.so

# Audio filter Modules (in encoding order)
#module                 vumeter.so
#module                 sndfile.so
#module                 speex_pp.so
#module                 plc.so
#module                 webrtc_aec.so

# Audio driver Modules
module                  alsa.so
#module                 pulse.so
#module                 jack.so
#module                 portaudio.so
#module                 aubridge.so
#module                 aufile.so

# Video codec Modules (in order)
module                  avcodec.so
#module                 vp8.so
#module                 vp9.so
#module                  omx.so

# Video filter Modules (in encoding order)
#module                 selfview.so
#module                 snapshot.so
#module                 swscale.so
#module                 vidinfo.so

# Video source modules
module                  v4l2.so
module                  v4l2_codec.so
#module                 x11grab.so
#module                 cairo.so
#module                 vidbridge.so

# Video display modules
#module                 directfb.so
#module                 x11.so
#module                 sdl.so
#module                 fakevideo.so

# Audio/Video source modules
module                  avformat.so
#module                 rst.so
#module                 gst.so
#module                 gst_video.so

# Compatibility modules
#module                 ebuacip.so

# Media NAT modules
module                  stun.so
module                  turn.so
module                  ice.so
#module                 natpmp.so
#module                 pcp.so

# Media encryption modules
#module                 srtp.so
#module                 dtls_srtp.so
#module                 zrtp.so


#------------------------------------------------------------------------------
# Temporary Modules (loaded then unloaded)

module_tmp              uuid.so
module_tmp              account.so


#------------------------------------------------------------------------------
# Application Modules

module_app              auloop.so
#module_app             b2bua.so
module_app              contact.so
module_app              debug_cmd.so
#module_app             echo.so
#module_app             gtk.so
module_app              menu.so
#module_app             mwi.so
#module_app             presence.so
#module_app             syslog.so
#module_app             mqtt.so
#module_app             ctrl_tcp.so
module_app              vidloop.so


#------------------------------------------------------------------------------
# Module parameters


# UI Modules parameters
cons_listen             0.0.0.0:5555 # cons

http_listen             0.0.0.0:8000 # httpd - server

ctrl_tcp_listen         0.0.0.0:4444 # ctrl_tcp

evdev_device            /dev/input/event0

# Opus codec parameters
opus_bitrate            28000 # 6000-510000
#opus_stereo            yes
#opus_sprop_stereo      yes
#opus_cbr               no
#opus_inbandfec         no
#opus_dtx               no
#opus_mirror            no
#opus_complexity        10
#opus_application       audio   # {voip,audio}
#opus_samplerate        48000
#opus_packet_loss       10      # 0-100 percent

# Opus Multistream codec parameters
#opus_ms_channels       2       #total channels (2 or 4)
#opus_ms_streams                2       #number of streams
#opus_ms_c_streams      2       #number of coupled streams
vumeter_stderr          yes

#jack_connect_ports     yes

# Selfview
video_selfview          window # {window,pip}
#selfview_size          64x64

# ICE
ice_debug               no

# ZRTP
#zrtp_hash              no  # Disable SDP zrtp-hash (not recommended)

# Menu
#menu_bell              yes
#redial_attempts        0 # Num or <inf>
#redial_delay           5 # Delay in seconds
#ringback_disabled      no
#statmode_default       off

# avcodec
#avcodec_h264enc               libx264
avcodec_h264enc         h264_omx

#avcodec_h264dec               h264
#avcodec_h265enc               libx265
#avcodec_h265dec               hevc
#avcodec_hwaccel               vaapi

# mqtt
mqtt_broker_host        127.0.0.1
#mqtt_broker_port       1883
#mqtt_broker_clientid   baresip01
#mqtt_broker_user       user
#mqtt_broker_password   pass
#mqtt_basetopic         baresip/01

# sndfile
#snd_path               /tmp

# EBU ACIP
#ebuacip_jb_type        fixed   # auto,fixed

**Comment by alfredh** [comment]
A couple of points to clarify things:

1. avcodec.so needs to use the h264_omx encoder w/hwaccel
2. omx.so is a video display module

please understand that those two items are completely separated.
(you said that you only need to send video, so why are you using omx.so) ?

to use h264 omx encoder, specify this in config:

```
avcodec_h264enc    h264_omx
```

if that does not work, I will get back to you.
Also can you give the output of this command:

```
ffmpeg -hwaccels
```

Regarding your issue with green pixellation, I would suggest that we try to determine
where it is coming from. Is it coming from the video source or the encoder ?

1. Try to use a different video source, e.g. cairo.so
2. Try to use a different encoder, e.g. libx264

when we have determined where the green pixel is coming from, we can
debug further.

NOTE: Please also paste the output of `baresip -v` command.

**Comment by Syirrus** [comment]
> ffmpeg -hwaccels

Since my original post, I removed `omx.so` and set:
`avcodec_h264enc    h264_omx`

Hardware encoding definitely works.

When I use the encoder libx264 the quality is great.  There are no color aberrations or green/yellow/red chromatic effects.  This appears to be related to the h264_omx encoder.

Below is the output of baresip:

baresip v0.6.6 Copyright (C) 2010 - 2020 Alfred E. Heggestad et al.
Local network address:  IPv4=wlan0|192.168.1.22  IPv6=wlan0|xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx
ui: stdio
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
ausrc: alsa
auplay: alsa
vidcodec: H264
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidcodec: H265
avcodec: using H.264 encoder 'h264_omx' -- OpenMAX IL H.264 video encoder
avcodec: using H.264 decoder 'h264' -- H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.265 encoder 'libx265' -- libx265 H.265 / HEVC
avcodec: using H.265 decoder 'hevc' -- HEVC (High Efficiency Video Coding)
vidsrc: v4l2
v4l2_codec inited
vidcodec: H264
vidsrc: v4l2_codec
ausrc: avformat
vidsrc: avformat
medianat: stun
medianat: turn
medianat: ice
uuid: loaded UUID 17685351-519e-0dd3-0fd8-2fc9bc28033f from file /root/.baresip/uuid
Populated 1 account
module: loading app auloop.so
module: loading app contact.so
Populated 3 contacts
module: loading app debug_cmd.so
module: loading app menu.so
module: loading app vidloop.so
Populated 2 audio codecs
Populated 0 audio filters
Populated 6 video codecs
Populated 0 video filters
baresip is ready.


--- MY EDITS = after video call connection was established ---


stream: update 'video'
stream: video: starting RTCP with remote xxx.xxx.xxx.xxx:19617
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: start
audio: create recv buffer [20 - 160 ms] [320 - 2560 bytes]
alsa: reset: srate=8000, ch=1, num_frames=160, pcmfmt=S16_LE
alsa: playback started (default)
audio: player started with sample format S16LE
audio: Set audio encoder: PCMU 8000Hz 1ch
audio: start
alsa: reset: srate=8000, ch=1, num_frames=160, pcmfmt=S16_LE
alsa: recording started (default) format=S16LE
audio: source started with sample format S16LE
audio tx pipeline:        alsa ---> PCMU
audio rx pipeline:        alsa <--- PCMU
Set video encoder: H264 packetization-mode=1 (1000000 bit/s, 25.00 fps)
avcodec: h264 encoder activated
avcodec: video encoder H264: 25.00 fps, 1000000 bit/s, pktsize=1024
video: no video display
v4l2: /dev/video0: found valid V4L2 device (640 x 480) pixfmt=YU12
v4l2: Current input: "Camera 0"
v4l2: current framerate is 10.00 fps
call: stream start (active=1)
audio: start
Set video decoder: H264 packetization-mode=1
avcodec: h264 decoder activated
avcodec: decode: hardware accel disabled
avcodec: video decoder H264 ()
101@xxx.xxx.xxx.xxx: Call established: sip:102@xxx.xxx.xxx.xxx
stream: incoming rtp for 'audio' established, receiving from xxx.xxx.xxx.xxx:13744
[h264_omx @ 0xac200470] Using OMX.broadcom.video_encode
call: receive media control: fast_update=1=0.0/0.0
avcodec: encoder picture update
net: check for IP changes: change=062346/0 (bit/s) efps=10.0/0.0
ua: incoming OPTIONS message from sip:asterisk@xxx.xxx.xxx.xxx (xxx.xxx.xxx.xxx:5060)
ua: using best effort AF: af=AF_INET
call: alloc with params laddr=192.168.1.22, af=AF_INET, use_rtp=0
call: use_video=1
video: stopping video source ..
audio: destroyed (started=0)
[0:00:41] audio=64000/64000 video=255338/0 (bit/s) efps=10.0/0.0

Thank you again for taking the time to respond to my request.  I did some further digging and I was able to set the FPS and rotation of the camera. For those interested the Pi Zero W will use about 60% of its CPU @ 10fps/640x480 at 30fps/ 640x480 around 80%

**Comment by alfredh** [comment]
so we have determined that the source of the color distortion is
the ffmpeg h264_omx encoder.

a couple of ideas:

1. please verify that ffmpeg is working fine using h264_omx encoder.
(no baresip involved). you can test this command:

```
$ ffmpeg -y -t 30 -f lavfi -i testsrc2=size=640x480 -vcodec h264_omx foo.mp4
```

2. please test different resolutions, and see if this affects the colors. some
resolutions that you can test:

- 352x288
- 320x240
- 640x480
- 1280x720

also test different frame-rates.


3. you can also test the vidloop command, in this case you also need a video display.
example:

```
/vidloop h264
```

**Comment by Syirrus** [comment]
> so we have determined that the source of the color distortion is
> the ffmpeg h264_omx encoder.
> 
> a couple of ideas:
> 
> 1. please verify that ffmpeg is working fine using h264_omx encoder.
>    (no baresip involved). you can test this command:
> 
> ```
> $ ffmpeg -y -t 30 -f lavfi -i testsrc2=size=640x480 -vcodec h264_omx foo.mp4
> ```
> 
> 1. please test different resolutions, and see if this affects the colors. some
>    resolutions that you can test:
> 
> * 352x288
> * 320x240
> * 640x480
> * 1280x720
> 
> also test different frame-rates.
> 
> 1. you can also test the vidloop command, in this case you also need a video display.
>    example:
> 
> ```
> /vidloop h264
> ```

Thank you for looking into this. I will test this tomorrow.

**Comment by alfredh** [comment]
hi, did you follow my advice and verify if ffmpeg is working as expected?

did you also test ffmpeg git HEAD ?

**Comment by Syirrus** [comment]
Yes, sorry for the delay. 
 
It appears that it works just fine when running:
`ffmpeg -y -t 30 -f lavfi -i testsrc2=size=640x480 -vcodec h264_omx foo.mp4`

However, I do see some artificting and it's hard to tell if they are chromatic aberrations.  I think they are, maybe you can have a look [here](https://drive.google.com/file/d/1wDTE7meRtI7ApymgfdlAoKKyIMuchhKV/view?usp=sharing)

The resolutions don't seem to have an effect anything and the aberrations still persist.
I have not tried testing the latest ffmpeg though. I had a cursory look at some of the commits and didn't see anything mentioning this issue, but I could be wrong; plus having to recompile everything takes ages on this device, but I probably should and will.  Right now, a server of mine that I'm using with this is not working for some reason, which is hamstringing my efforts :(

Please advise :)

Syirrus

**Comment by alfredh** [comment]
what I can see from this video is that the image is heavily compressed.
it has a reduced perceived quality.

what it means is one of:

1. bitrate is too low
2. quality parameter is too low

when comparing the same input (testsrc2) with x264 and h264_omx
the output has very different bitrate:

libx264: 917 kb/s
h264_omx: 203 kb/s

You can try to force a higher bitrate and see if this has any effect,
by adding the `-b:v` option:

```
$ ffmpeg -y -t 30 -f lavfi -i testsrc2=size=640x480 -b:v 2M -vcodec h264_omx foo.mp4
```

the corresponding baresip config:

`video_bitrate           3000000`

Please test different bitrates; 1M, 2M, 3M, 4M etc.

Note:

you can also use your camera as input:

```
$ ffmpeg -y -t 30 -f v4l2 -i /dev/video0 -b:v 2M -vcodec h264_omx foo.mp4
```

**Comment by alfredh** [comment]
I hope that my advice is useful for you.

Please note that your issue is not a bug in baresip, we mainly want to use
the Issues tracker for defects/bugs.

If you want more help please use the Baresip mailing-list:

https://groups.google.com/forum/#!forum/baresip
