### ISSUE TITLE
about opengles module

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#968]
As I mentioned on re-devel list, I managed to get a modified version of opengles module working as video display module for Android.

In order to get reference to the native Android window, I made a hack by sending from opengles_alloc() a new UA event UA_EVENT_GET_WINDOW, which gave the window reference back in its (struct call *) parameter.

What is the proper way of getting the window reference when opengles module is allocated?

Also, when there are changes to the window during the call, what is the proper way of telling to opengles module about them?  Should the module register a command for that purpose?

Finally, what should be done with this modified module?  Apply the changes to the existing opengles module (which for sure does not work as Android display module, but might work as Darwin display module) or create a new module?

**Comment by alfredh** [comment]
regarding the status of the opengles module, I think it is quite it in the open.
it used to work on both iOS and Android, but that is a long time ago.
I dont think anyone is using it, so please feel to hack it.


if your code is working on Android, we can easily change the module
to only support Android. If any iOS people are using it, please speak out.

also related to using OpenGLES, are we sure that it is the best current way to
display video in Android? are there other APIs that is better, e.g.:

https://developer.android.com/ndk/reference/group/bitmap

another aspect is the usage of modules for this. If you implement a video display
module in your Android app, it can be done in one of two ways:

1. as a module (e.g. opengles.so)
2. in your app as regular code, just need to call `vidisp_register`

regarding how to send/recv Window ID from/to application and module,
that is also an api enhancement that would have to be done.

if you go for option 2.) this would be much easier, and the need for api changes
would disappear.

I think you should check with other Android Video apps, which API they use.

**Comment by juha-h** [comment]
Thanks for the advise.  I'll start working on option 2).

**Comment by juha-h** [comment]
Just to complete this, I managed to move opengles module alloc() and display() functions to native part of my Android app and then from there register the video display.
