### ISSUE TITLE
Support for h263/h264 rtsp video ip cameras

### ISSUE THREAD

**Issue by BlindCrow** [alfredh/baresip#97]
Some simple video intercom systems support video by using a small rtsp video ip camera non sip , and calling the rtsp service in the camera to prepare it and start it using the client ip that have connected to the voip board.

Do you think that this is possible to implement in baresip ?

**Comment by alfredh** [comment]
if you can use ```ffplay``` to play your RTSP stream, then you also use the ```avformat.so```
module to play the same URL.

```
video_source    avformat,rtsp://ip-address:port/path
module     avformat.so
```
