### ISSUE TITLE
API function to insert/remove video stream to/from a call

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#970]
I haven't found API function(s) that would allow adding/removing video stream from a call.  In case there isn't a way to do that, I wrote this:
```
int call_set_video(const struct call *call, enum vidmode vmode)
{
	if (!call)
		return EINVAL;

	if (call->video && (vmode == VIDMODE_OFF)) {
		video_stop(call->video);
		call->video = mem_deref(call->video);
		return call_modify(call);
	}

	if (!call->video && (vmode == VIDMODE_ON)) {
		/* do something */
		return call_modify(call);
	}

	return 0;
}
```
Removing seems easy, but adding I don't know how to do.  Any ideas?

**Comment by alfredh** [comment]
if you want to enable/disable video during a call, there are two ways to do it:

1. disable video in the SDP and send a Re-INVITE

2. disable local video source and display, no signalling

in my experience, method 1 is very error prone and sensitive to protocol
implementation on the remote peer.

I think it is much simpler to have a local camera on/off toggle button.

if you want to implement 1. you need to disable SDP video-line:

`void sdp_media_set_disabled(struct sdp_media *m, bool disabled);`

**Comment by alfredh** [comment]
please use the baresip mailing-list for questions:

https://groups.google.com/forum/#!forum/baresip

**Comment by juha-h** [comment]
> please use the baresip mailing-list for questions:
> 
> https://groups.google.com/forum/#!forum/baresip

I tried that link and got "You do not have permission to access this content".

**Comment by juha-h** [comment]
This is confusing.  Wiki https://github.com/alfredh/baresip/wiki tells to use re-devel mailing list for discussions, but no questions there was answered in April. Now there is this google group that I'm not allowed to access.

**Comment by alfredh** [comment]
please try again.

the baresip google group should be available to anyone.

**Comment by juha-h** [comment]
Now I got invitation and was able to join the group.  Group tells:

baresip Shared privately

In contrast, jssjp group tells:

 JsSIP Shared publicly
