### ISSUE TITLE
Doesn't build on MacOS with TLS enabled

### ISSUE THREAD

**Issue by xjosh** [alfredh/baresip#971]
System is MacBook Pro 15, 2014. OS is 10.15.4. Xtools, Xtools command line is installed. A full log of the output of 'make' is attached, but the relevant snip is:

...
 LD      baresip
Undefined symbols for architecture x86_64:
  "_tls_add_ca", referenced from:
      _add_transp_af in ua.o
  "_tls_alloc", referenced from:
      _add_transp_af in ua.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [baresip] Error 1

Don't know if this is relevant but will post as separate issue, but it doesn't seem that stdio.so is not being built either (even when disabling TLS).

Thanks!
[buildlog.txt](https://github.com/alfredh/baresip/files/4560072/buildlog.txt)

**Comment by alfredh** [comment]
you need to install openssl first.

then recompile re,rem from git

```
$ cd re
$ make USE_TLS=yes USE_OPENSSL=yes
$ sudo make USE_TLS=yes USE_OPENSSL=yes install
```

```
$ cd rem
$ make
$ sudo make install
```

```
$ cd baresip
$ make
$ sudo make install
```

if that does not work, please paste the output of `make info`.

**Comment by xjosh** [comment]
OK thanks! That worked. I had originally installed re and rem from Homebrew. I uninstalled those, complied according to these instructions (leaving my Homebrew OpenSSL), and it worked. I'm not sure the difference as the formula for libre seems to have openssl as a requirement and is installed in /usr/local/lib. At any rate, it's working. Thanks again!
