### ISSUE TITLE
Doesn't build stdio.so

### ISSUE THREAD

**Issue by xjosh** [alfredh/baresip#972]
System is MacBook Pro 15, 2014. OS is 10.15.4. Xtools, Xtools command line is installed. A full log of the output of 'make' and 'make install' is attached. Application does not seem to respond to commands as I might expect. First run of application reports:

baresip v0.6.6 Copyright (C) 2010 - 2020 Alfred E. Heggestad et al.
Local network address:  IPv4=en6|192.168.2.118 
dl: mod: /usr/local/lib/baresip/modules/stdio.so (dlopen(/usr/local/lib/baresip/modules/stdio.so, 6): image not found)
module stdio.so: No such file or directory
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
auplay: coreaudio
...

Note that TLS is disabled due to other issue.
 
Thanks!
[buildlog-notls.txt](https://github.com/alfredh/baresip/files/4560132/buildlog-notls.txt)
[installog-notls.txt](https://github.com/alfredh/baresip/files/4560133/installog-notls.txt)

**Comment by juha-h** [comment]
Your make does not make stdio module. Check that this include file exists:
```
USE_STDIO := $(shell [ -f $(SYSROOT)/include/termios.h ] && echo "yes")
```

**Comment by alfredh** [comment]
@xjosh please read this:

https://github.com/alfredh/baresip/wiki/Guidelines-for-reporting-Issues

please dont create multiple issues.

to answer your question, you can enable stdio with:

```
$ make USE_STDIO=yes
```

**Comment by xjosh** [comment]
Sorry for the multiples, advice duly noted. 

Making with `USE_STDIO=yes` produced a working executable. Might be worth including this in the build instructions. Even with this information, I couldn't go back and find it in the instructions. 

Thanks again!
