### ISSUE TITLE
baresip and linphone

### ISSUE THREAD

**Issue by holdenc** [alfredh/baresip#974]
Hi,

I have an account on linphone and I wanted to test it with baresip (latest version from git).
My account file looks like this:

`<sip:holdenc@sip.linphone.org;transport=udp>;auth_pass=xxx`

It seems like I am able to register because I get this message in the console:

```
holdenc@sip.linphone.org: {0/UDP/v4} 200 Registration successful (Flexisip/2.0.0-beta-57-gc9f98e9d (sofia-sip-nta/2.0)) [1 binding]
All 1 useragent registered successfully! (126 ms)
```

but then I am unable to receive any call, although outgoing calls are working fine.

Does baresip work with linphone? (maybe related to #746 ?)

If it can help, here's a tcpdump:
```
$ sudo tcpdump -i any -n -v ip
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
12:32:24.244592 IP (tos 0x0, ttl 64, id 7671, offset 0, flags [DF], proto UDP (17), length 72)
    127.0.0.1.34016 > 127.0.0.53.53: 54054+ SRV? _sip._udp.sip.linphone.org. (44)
12:32:24.244801 IP (tos 0x0, ttl 64, id 20749, offset 0, flags [DF], proto UDP (17), length 122)
    127.0.0.53.53 > 127.0.0.1.34016: 54054 2/0/0 _sip._udp.sip.linphone.org. SRV sip6.linphone.org.:5060 0 100, _sip._udp.sip.linphone.org. SRV sip1.linphone.org.:5060 10 100 (94)
12:32:24.247949 IP (tos 0x0, ttl 64, id 7672, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.1.34016 > 127.0.0.53.53: 53448+ A? sip6.linphone.org. (35)
12:32:24.248151 IP (tos 0x0, ttl 64, id 20750, offset 0, flags [DF], proto UDP (17), length 79)
    127.0.0.53.53 > 127.0.0.1.34016: 53448 1/0/0 sip6.linphone.org. A 54.37.202.229 (51)
12:32:24.248239 IP (tos 0x0, ttl 64, id 19180, offset 0, flags [DF], proto UDP (17), length 586)
    192.168.1.8.5060 > 54.37.202.229.5060: SIP, length: 558
	REGISTER sip:sip.linphone.org;transport=udp SIP/2.0
	Via: SIP/2.0/UDP 192.168.1.8:5060;branch=z9hG4bK7aa02f56adfa0b6d;rport
	Contact: <sip:holdenc-0x560ec5a4bed0@192.168.1.8:5060>;expires=3685;+sip.instance="<urn:uuid:0a655929-2612-5ce8-360d-d576065f572f>"
	Max-Forwards: 70
	To: <sip:holdenc@sip.linphone.org>
	From: <sip:holdenc@sip.linphone.org>;tag=4eabf61d194fb199
	Call-ID: a0cf541c10f924aa
	CSeq: 54443 REGISTER
	User-Agent: baresip v0.6.6 (x86_64/linux)
	Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER
	Content-Length: 0
	
12:32:24.298479 IP (tos 0x0, ttl 50, id 19037, offset 0, flags [none], proto UDP (17), length 537)
    54.37.202.229.5060 > 192.168.1.8.5060: SIP, length: 509
	SIP/2.0 401 Unauthorized
	Via: SIP/2.0/UDP 192.168.1.8:5060;branch=z9hG4bK7aa02f56adfa0b6d;rport=5060;received=31.185.52.11
	From: <sip:holdenc@sip.linphone.org>;tag=4eabf61d194fb199
	To: <sip:holdenc@sip.linphone.org>;tag=Fe9HF07vvgS9r
	Call-ID: a0cf541c10f924aa
	CSeq: 54443 REGISTER
	Server: Flexisip/2.0.0-beta-57-gc9f98e9d (sofia-sip-nta/2.0)
	WWW-Authenticate: Digest realm="sip.linphone.org", nonce="yMFf4gAAAAD1YuxcAACY6dXEWwcAAAAA", opaque="+GNywA==", algorithm=MD5, qop="auth"
	Content-Length: 0
	
12:32:24.298953 IP (tos 0x0, ttl 64, id 7674, offset 0, flags [DF], proto UDP (17), length 72)
    127.0.0.1.34016 > 127.0.0.53.53: 5031+ SRV? _sip._udp.sip.linphone.org. (44)
12:32:24.299223 IP (tos 0x0, ttl 64, id 20751, offset 0, flags [DF], proto UDP (17), length 122)
    127.0.0.53.53 > 127.0.0.1.34016: 5031 2/0/0 _sip._udp.sip.linphone.org. SRV sip6.linphone.org.:5060 0 100, _sip._udp.sip.linphone.org. SRV sip1.linphone.org.:5060 10 100 (94)
12:32:24.299299 IP (tos 0x0, ttl 64, id 7675, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.1.34016 > 127.0.0.53.53: 48992+ A? sip6.linphone.org. (35)
12:32:24.299424 IP (tos 0x0, ttl 64, id 20752, offset 0, flags [DF], proto UDP (17), length 79)
    127.0.0.53.53 > 127.0.0.1.34016: 48992 1/0/0 sip6.linphone.org. A 54.37.202.229 (51)
12:32:24.299500 IP (tos 0x0, ttl 64, id 19186, offset 0, flags [DF], proto UDP (17), length 852)
    192.168.1.8.5060 > 54.37.202.229.5060: SIP, length: 824
	REGISTER sip:sip.linphone.org;transport=udp SIP/2.0
	Via: SIP/2.0/UDP 192.168.1.8:5060;branch=z9hG4bK846dd4d01a96a621;rport
	Contact: <sip:holdenc-0x560ec5a4bed0@192.168.1.8:5060>;expires=3685;+sip.instance="<urn:uuid:0a655929-2612-5ce8-360d-d576065f572f>"
	Max-Forwards: 70
	Authorization: Digest username="holdenc", realm="sip.linphone.org", nonce="yMFf4gAAAAD1YuxcAACY6dXEWwcAAAAA", uri="sip:sip.linphone.org;transport=udp", response="01a539c498af59d4d4674320f81111cc", opaque="+GNywA==", cnonce="b6cde3395a9e669a", qop=auth, nc=00000001
	To: <sip:holdenc@sip.linphone.org>
	From: <sip:holdenc@sip.linphone.org>;tag=4eabf61d194fb199
	Call-ID: a0cf541c10f924aa
	CSeq: 54444 REGISTER
	User-Agent: baresip v0.6.6 (x86_64/linux)
	Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER
	Content-Length: 0
	
12:32:24.361215 IP (tos 0x0, ttl 50, id 19047, offset 0, flags [none], proto UDP (17), length 543)
    54.37.202.229.5060 > 192.168.1.8.5060: SIP, length: 515
	SIP/2.0 200 Registration successful
	Via: SIP/2.0/UDP 192.168.1.8:5060;branch=z9hG4bK846dd4d01a96a621;rport=5060;received=31.185.52.11
	From: <sip:holdenc@sip.linphone.org>;tag=4eabf61d194fb199
	To: <sip:holdenc@sip.linphone.org>;tag=H0U3jp93p25eg
	Call-ID: a0cf541c10f924aa
	CSeq: 54444 REGISTER
	Contact: <sip:holdenc-0x560ec5a4bed0@31.185.52.11:5060>;expires=3685;+sip.instance="<urn:uuid:0a655929-2612-5ce8-360d-d576065f572f>"
	Server: Flexisip/2.0.0-beta-57-gc9f98e9d (sofia-sip-nta/2.0)
	Content-Length: 0
	
12:32:26.108721 IP (tos 0x0, ttl 64, id 7715, offset 0, flags [DF], proto UDP (17), length 72)
    127.0.0.1.34016 > 127.0.0.53.53: 39702+ SRV? _sip._udp.sip.linphone.org. (44)
12:32:26.109287 IP (tos 0x0, ttl 64, id 21145, offset 0, flags [DF], proto UDP (17), length 122)
    127.0.0.53.53 > 127.0.0.1.34016: 39702 2/0/0 _sip._udp.sip.linphone.org. SRV sip6.linphone.org.:5060 0 100, _sip._udp.sip.linphone.org. SRV sip1.linphone.org.:5060 10 100 (94)
12:32:26.109511 IP (tos 0x0, ttl 64, id 7716, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.1.34016 > 127.0.0.53.53: 44164+ A? sip6.linphone.org. (35)
12:32:26.109844 IP (tos 0x0, ttl 64, id 21146, offset 0, flags [DF], proto UDP (17), length 79)
    127.0.0.53.53 > 127.0.0.1.34016: 44164 1/0/0 sip6.linphone.org. A 54.37.202.229 (51)
12:32:26.110103 IP (tos 0x0, ttl 64, id 19558, offset 0, flags [DF], proto UDP (17), length 849)
    192.168.1.8.5060 > 54.37.202.229.5060: SIP, length: 821
	REGISTER sip:sip.linphone.org;transport=udp SIP/2.0
	Via: SIP/2.0/UDP 192.168.1.8:5060;branch=z9hG4bK8e496c3b2ed957bb;rport
	Contact: <sip:holdenc-0x560ec5a4bed0@192.168.1.8:5060>;expires=0;+sip.instance="<urn:uuid:0a655929-2612-5ce8-360d-d576065f572f>"
	Max-Forwards: 70
	Authorization: Digest username="holdenc", realm="sip.linphone.org", nonce="yMFf4gAAAAD1YuxcAACY6dXEWwcAAAAA", uri="sip:sip.linphone.org;transport=udp", response="c1b5410657709da660ea1eef864be57b", opaque="+GNywA==", cnonce="afb4b7eef1fe33d2", qop=auth, nc=00000002
	To: <sip:holdenc@sip.linphone.org>
	From: <sip:holdenc@sip.linphone.org>;tag=4eabf61d194fb199
	Call-ID: a0cf541c10f924aa
	CSeq: 54445 REGISTER
	User-Agent: baresip v0.6.6 (x86_64/linux)
	Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER
	Content-Length: 0
	
12:32:26.171264 IP (tos 0x0, ttl 50, id 19062, offset 0, flags [none], proto UDP (17), length 409)
    54.37.202.229.5060 > 192.168.1.8.5060: SIP, length: 381
	SIP/2.0 200 Registration successful
	Via: SIP/2.0/UDP 192.168.1.8:5060;branch=z9hG4bK8e496c3b2ed957bb;rport=5060;received=31.185.52.11
	From: <sip:holdenc@sip.linphone.org>;tag=4eabf61d194fb199
	To: <sip:holdenc@sip.linphone.org>;tag=XeXZSy9FU72Ug
	Call-ID: a0cf541c10f924aa
	CSeq: 54445 REGISTER
	Server: Flexisip/2.0.0-beta-57-gc9f98e9d (sofia-sip-nta/2.0)
	Content-Length: 0
```

**Comment by GGGO** [comment]
Hi @holdenc,

baresip works with linphone and yes you may have a NAT issue.

Please refer to #746 and https://github.com/alfredh/baresip/wiki/Guidelines-for-reporting-Issues

Have a great day!

**Comment by holdenc** [comment]
Hi @GGGO ,

thanks for your reply. I have also tested with TLS using:

'<sip:holdenc@sip.linphone.org;transport=tls>;auth_pass=xxx'

but no luck. The [latest comment](https://github.com/alfredh/baresip/issues/746#issuecomment-510574418) from @alfredh in #746 suggests that there is currently an issue with baresip+linphone.

**Comment by GGGO** [comment]
I mean baresip works with linphone client but not with Flexisip provided by sip.linphone.org.

You have to contact the provider and report the bug to them.

**Comment by alfredh** [comment]
this is not a bug in baresip. please report the issue to the linphone.org people

**Comment by holdenc** [comment]
Thanks, I just did: [https://github.com/BelledonneCommunications/flexisip/issues/95](https://github.com/BelledonneCommunications/flexisip/issues/95)

**Comment by fbradasc** [comment]
Hi,
sorry if I reopen this discussion after almost an year...

I think I found the solution of this annoying problem.

Comparing the SIP dumps from pjsip, which is not affected by this issue, and from baresip and after a lot of trials & errors changes in libre SIP registration messages I finally found which is the data not correctly handled by the flexisip server, it is the "**;expires=**" parameter int the "**Contact:**" header in the registration message.

libre set this data _**only**_ as a parameter for the the **Contact:** header (which, according to the [RFC3261 
"10.2 Constructing the REGISTER Request"](https://tools.ietf.org/html/rfc3261#section-10.2) should be enough):

> "Contact: <<sip:user@domain;params>>**;expires=_duration_**"

pjsip, instead, passes this data _**only**_ in the dedicated **Expires:** header:

> "Expires: _duration_"


The following change in libre to allow baresip to pass the expiration time both as a parameter and as an header:

```
diff --git a/src/sipreg/reg.c b/src/sipreg/reg.c
index e9a08f5..6ea5d3a 100644
--- a/src/sipreg/reg.c
+++ b/src/sipreg/reg.c
@@ -286,6 +286,8 @@ static int send_handler(enum sip_transp tp, const struct sa *src,
 
        err |= mbuf_printf(mb, "\r\n");
 
+       err |= mbuf_printf(mb, "Expires: %u\r\n",reg->expires);
+
        return err;
 }
 
```

**Comment by juha-h** [comment]
Baresip behaves according to RFC3261.  You need to open an issue against
flexsip if it cannot handle ;expires contact parameter.

**Comment by fbradasc** [comment]
An issue against flexisip exists (and ignored) since 2017: ["Contact Header expires field is ignored"](https://github.com/BelledonneCommunications/flexisip/issues/11)

Even the "Expires:" header is RFC3261 compliant:

`      expires: The "expires" parameter indicates how long the UA would
           like the binding to be valid.  The value is a number
           indicating seconds.  If this parameter is not provided, the
           value of the Expires header field is used instead.
           ...
`

Preventing a sip.linphone.org account registered by a baresip client application could be a show stopper, for this reason I put  in this thread the "flexisip workaround" I found.

I don't know if it will be integrated or not, but I hope it could help.

**Comment by juha-h** [comment]
It does not make sense to have both Expires header and ;expires contact
parameter.  I don't know if it would be possible to make it
configurable, which one to use.

**Comment by fbradasc** [comment]
I totally agree with you about to parametrize the placement of the expires data based on field(s) in the account configuration.

The new configuration field(s) shall allow the user to choose where the **expires** data shall be placed between the following three options:

1) in the _Contact:_ header's "**;expires=**" parameter [default behaviour if not otherwise specified]
2) as value of the _Expires:_ header for its own
3) both the above (just to cover all the possible scenarios)

**Comment by fbradasc** [comment]
> It does not make sense to have both Expires header and ;expires contact parameter.

Well, acording to your statement, in the account configuration a new single boolean parameter is sufficient, if this is present then the expires data is placed _only_ in the "**Expires:**" header, otherwise it follows the current behaviour and it's placed as "**;expires=**" parameter in the "_Contact:_" header

**Comment by joenye** [comment]
@fbradasc Did you make any progress getting this configuration merged? I would also like to connect to Linphone and have the same issue.

**Comment by juha-h** [comment]
It is not practical to start fixing in baresip issues that exist in other SIP clients/servers.

**Comment by fbradasc** [comment]
> @fbradasc Did you make any progress getting this configuration merged? I would also like to connect to Linphone and have the same issue.

No but you can use the patch I suggested [here](https://github.com/baresip/baresip/issues/974#issuecomment-825492528)
