### ISSUE TITLE
API call missing to stop video display

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#976]
There exist API call stop_video(), but it only stops video source.  There should also be an API call to stop video display, since at least on Android, opengles_display() starts to produce errors when the rendering surface is destroyed.  That happens when the activity displaying the video becomes invisible, for example, when the home button is pressed.  There is also need to restart video display, when orientation of the surface (and thus its X/Y size) changes.

**Comment by alfredh** [comment]
here is the code for video_stop:

```c
/**
 * Stop the video source
 *
 * @param v   Video object
 */
void video_stop(struct video *v)
{
	if (!v)
		return;

	debug("video: stopping video source ..\n");

	v->started = false;
	v->vtx.vsrc = mem_deref(v->vtx.vsrc);
}
```

currently in only stops the video source.

I can see 2 solutions to this issue:

1. add stopping of display in video_stop

2. add a new function called video_stop_display

in both cases the display can be stopped with this code:


```c
	vrx->vidisp = mem_deref(vrx->vidisp);
```

**Comment by juha-h** [comment]
OK, thanks for the code.  I prefer option (2) so that camera can be kept operational when rendering surface is destroyed.  I'll test and create pull request.

**Comment by juha-h** [comment]
This pull request https://github.com/alfredh/baresip/pull/977 adds video_stop_display() API function.  Should video_stop() be renamed to video_stop_source() for consistency?

**Comment by alfredh** [comment]
many thanks.

I think it does not matter to me, it could be called
video_stop or video_stop_source, I am fine with either.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I think it does not matter to me, it could be called
> video_stop or video_stop_source, I am fine with either.

OK, let it be as is.
