### ISSUE TITLE
avcodec/decode.c/avcodec_open2() fails due to missing AVCodecContext extradata

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#985]
I tried to use in avcodec module MediaCodec h264 decoder:
```
avcodec_h264dec    h264_mediacodec 
```
That failed in avcodec/decode.c init_decoder() function at
```
if (avcodec_open2(st->ctx, st->codec, NULL) < 0)
```
I then traced ffmpeg source code and found that the function call failed because there was no extradata in AVCodecContext parameter st->ctx.

This context is initialized by earlier call:
```
st->ctx = avcodec_alloc_context3(st->codec);
```
but that does not add any extradata to the context.

I then found a StackOverflow discussion about populating extradata:
[https://stackoverflow.com/questions/35144059/ffmpeg-how-do-i-get-the-extradata-required-to-open-the-alac-codec](url), but haven't figured out, how to do that in avcodec module.

Any help is appreciated, since the code as it currently stands, does not work.

Here is another reference about the same topic: [https://trac.ffmpeg.org/ticket/5838](url).

**Comment by juha-h** [comment]
I got this reply from the author of ffmpeg h264_mediacodec decoder (Matthieu Bouron), when I asked about the extradata:

> Extradata are mandatory for the h264_mediacodec decoder because we want
MediaCodec to fail during init (if the underlying codec does not support
the stream) so the user gets a chance to use a software fallback without
having to wait for avcodec_receive_frame() to fail.

**Comment by alfredh** [comment]
the extradata should contain the Sequence Parameter Set (SPS)
and Picture Parameter Set (PPS). what you need to do is:

1. save the incoming SPS
2. save the incoming PPS
3. when both SPS and PPS have arrived, write them to extradata

The SPS/PPS needs to have the NAL escape sequence in front (0x00000001):

`0x00000001 <SPS> 0x00000001 <PPS>`

**Comment by juha-h** [comment]
OK thanks.  I'll try later to figure out how I can get access to SPS and PPS.  I don't currently use h264_mediacodec decoder, so this is not an urgent issue. I'll add a TODO comment about this to avcodec module.
