### ISSUE TITLE
v4l2_codec not intialized

### ISSUE THREAD

**Issue by LiohAu** [alfredh/baresip#99]
In the new v4l2_codec module, the src_alloc functions does not seems to be called. As a result the v4l2 static struct keeps the default hardcoded values.

I'm not sure but I think that the "src_alloc" function pointer stored in the "alloch" variable of the vidsrc structure is never called (and probably vidsrc_alloc is also never called).

In my config file I have the following instructions : "video_source v4l2_codec, /dev/video1" and "module v4l2_codec.so"

**Comment by alfredh** [comment]
can you run baresip with -v and do a call setup, then include the full log here ?

**Comment by LiohAu** [comment]
This is the output I get if I do not change anything in the v4l2_codec.c file.

./baresip -v
baresip v0.4.16 Copyright (C) 2010 - 2015 Alfred E. Heggestad et al.
Local network address: IPv4=eth0:192.168.1.26
ui: stdio
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
ausrc: alsa
auplay: alsa
v4l2_codec inited
vidcodec: H264
vidsrc: v4l2_codec
avcodec: x264 build 142
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidisp: x11
medianat: stun
medianat: turn
medianat: ice
Populated 1 account
Populated 6 contacts
Populated 2 audio codecs
Populated 1 audio filter
Populated 4 video codecs
Populated 0 video filters
baresip is ready.
motion: Passive
set motion : 0x9079828
play: /usr/local/share/baresip/ring.wav: No such file or directory
sip:201@192.168.1.26: Incoming call from:  sip:202@192.168.1.25 - (press ENTER to accept)
answering call from sip:202@192.168.1.25 with 200
audio: Set audio decoder: PCMU 8000Hz 1ch
alsa: playback started (default)
audio: Set audio encoder: PCMU 8000Hz 1ch
alsa: recording started (default)
audio tx pipeline:        alsa ---> vumeter ---> PCMU
audio rx pipeline:        alsa <--- vumeter <--- PCMU
Set video encoder: H264 packetization-mode=0 (5000000 bit/s, 25 fps)
v4l2_codec: Driver Caps:
  Driver:        "uvcvideo"
  Card:          "USB 2.0 Camera"
  Bus:           "usb-0000:02:03.0-1"
  Version:       3.0
  Capabilities:  0x84000001
  FMT : CE Desc
--------------------
     MJPG: C  'MJPEG'
     YUYV:    'YUV 4:2:2 (YUYV)'

v4l2_codec: Doesn't support H264.
v4l2_codec: encoder stats (keyframes:0, deltaframes:0)
video: encoder alloc: No such device
call: video stream error: No such device
main: long async blocking: 244>100 ms (h=0xb7783a2d arg=0x9069078)
terminated by signal 2                                      [                ]
ua: stop all (forced=0)
Stopping 1 useragent..

**Comment by alfredh** [comment]
aha, your hardware does not support H.264 hardware encoding :)

v4l2_codec is ONLY for hardware with H.264 encoding.

for a regular camera, use "v4l2.so"

**Comment by LiohAu** [comment]
No my camera does H.264 hardware encoding. I have only 1 USB camera connected that creates /dev/video0 AND /dev/video1, as you can see (with the v4l2-ctl outputs that I pasted in my previous message), only /dev/video1 has the H264 pixel format.

But v4l2_codec ignores the /dev/video1 from the config file and takes the default value hardcoded in the struct defined in  v4l2_codec.c because these values should be replaced in src_alloc, and that src_alloc function is never called in my case.

**Comment by LiohAu** [comment]
the src_alloc stored in the "alloch" function pointer of the vidsrc struct is executed from vidsrc_alloc (vidsrc.c) OR from set_encoder_format (video.c).

"vidsrc_alloc" is only called from vidloop.c, so the bug may not be present if for people using vidloop but this is not my case.

Concerning the alloch, it is executed from "set_encoder_format", which is only called by "video_start". This last function is only called if there was no error in "video_encoder_set" (and "video_decoder_set") but since the src_alloc has not been called yet, the v4l2 static struct in v4l2_codec.c still contains the default values (in my case /dev/video0 instead of /dev/video1). 
So "video_encoder_set" will execute the "encupdh" function pointer which I guess contains "encode_update" from v4l2_codec.c, and this function will fail since it uses the incorrect device. And this error will prevent "video_start" from being called.

**Comment by LiohAu** [comment]
So, any idea?

**Comment by alfredh** [comment]
do you have this in your config:

```
video_source            v4l2_codec,/dev/video1
```

also, you can try to replace /dev/video0 with /dev/video1 in v4l2_codec.c

**Comment by LiohAu** [comment]
Obviously I have this in my config file, else the module wouldn't have been initialized.
As I wrote in my previous post, replacing  /dev/video0 by /dev/video1 in the .c works, but it makes the config file useless.

**Comment by LiohAu** [comment]
@alfredh can't we just add a "vidsrc_alloc" call somewhere (video.c maybe?) ?

**Comment by alfredh** [comment]
there was indeed a bug in the v4l2_codec module, many thanks for reporting!

can you try the latest version of baresip and see if it works now ?

**Comment by LiohAu** [comment]
I'm back on that project, i'll try to try (:D) in the coming days/weeks
